### ISSUE TITLE
Mateba codex Damage modifier: -5.96046e-006%

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#1002]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/53925388-e1d7df00-4090-11e9-889c-84ca18caa680.png)

**Comment by Hughgent** [comment]
re-upload your picture

**Comment by Hughgent** [comment]
Unable to reproduce
![image](https://user-images.githubusercontent.com/45076386/53927407-681e0200-404c-11e9-8982-4f342ec7cec1.png)
Also, Mateba has a burst fire mode?

**Comment by Ghommie** [comment]
Yes, it has a burst fire mode.
