### ISSUE TITLE
Drone gibs itself when it salvages.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#1003]
## Reproduction: Says this in chat when the drone gets gibbed by salvaging a dead xeno." SALVAGE ESSENCE DEBUG: absorbed_plasma: 22 absorbed_evolution: 12.5 absorbed_upgrade: 12.875 target.evolution_stored: 100 target.upgrade_stored: 207 "

**Comment by Ghommie** [comment]
@Surrealaser, I'm pretty sure you forgot to put the prefix upon calling `gib()` or whatever.
Also did you forget to reove the local test debug strings?
