### ISSUE TITLE
There is no anaesthetic closet in surgery room in PoS

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#10059]
### Description

See title. This is important for things like bringing one over to tadpole or just having one lost to shittery since it'd mean stealing the one surgery already needs.

### Test Merges

[#9772: 'TGUI updates' by TiviPlus at commit 16b87e0607](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9977: 'Health kits chain apply' by QualityVan at commit 5afedc795b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9977)
[#10008: 'Boxing+' by breadhunt at commit beb71c8b35](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10008)
[#10031: 'Refactors gun icon/item code' by Lumipharon at commit 622e614bac](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10031)
[#9979: 'Add wraith portal, remove hyperposition, remove phasing' by BraveMole at commit 0b2b974fee](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9979)

### Reproduction Steps

Go to surgery
Cry

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/164995127-14187837-a268-4a95-8324-02e322b131bd.png)
![image](https://user-images.githubusercontent.com/72712909/164995139-f328ddc3-3d91-4206-84a4-4b1607df71d5.png)

**Comment by Derrick2Electricboogaloo** [comment]
Was this fixed ever?

**Comment by Losenis** [comment]
I believe the PoS got yet another map rework after this pr that gave them closets

**Comment by RipGrayson** [comment]
This issue was fixed during one of the many reworks Elsa did for PoS, it's no longer valid.
