### ISSUE TITLE
Sulaco Drop Pods cant be opened by a smartgunner ID

### ISSUE THREAD

**Issue by realroyalderg** [tgstation/TerraGov-Marine-Corps#10054]
### Description

Description says it all, they're ID locked for god knows why

### Test Merges

[#10017: 'Adds the T-100Y howitzer and rebalances the mortar, renamed mortar.' by Pariah919 at commit b667312bfa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10017)
[#10032: 'Plasma Cutter Change' by Arctrooper8 at commit ee845aa771](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10032)

### Reproduction Steps

Go to Sulaco Ship map as normal SG
Press drop pod bay door shutter button
Cry as it says access denied

**Comment by TiviPlus** [comment]
Intended

**Comment by realroyalderg** [comment]
Inconsistent but intended based??
