### ISSUE TITLE
Wraith can teleport structures with portals

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#10062]
### Description

read title

### Test Merges

#9979

### Reproduction Steps

1. Banish structure
2. Put portal where it last was
3. Unbanish
4. Done

### Screenshots

https://user-images.githubusercontent.com/24631139/165008928-d42a6fcf-e131-467a-9049-447dd2b68648.mp4

**Comment by BraveMole** [comment]
fixes
