### ISSUE TITLE
Ice Colony Landing Zone 2 has no APC/Walls wont accept an APC

### ISSUE THREAD

**Issue by realroyalderg** [tgstation/TerraGov-Marine-Corps#10066]
### Description

Title says it all no APC or ability to put an APC down on the few walls that exist

### Test Merges

[#9772: 'TGUI updates' by TiviPlus at commit 16b87e0607](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9977: 'Health kits chain apply' by QualityVan at commit 5afedc795b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9977)
[#10008: 'Boxing+' by breadhunt at commit beb71c8b35](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10008)
[#9979: 'Add wraith portal, remove hyperposition, remove phasing' by BraveMole at commit c1d7367aad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9979)

### Reproduction Steps

go to

LZ2 Ice Colony map

realize there is no APC, no way to place an APC

cry

**Comment by breadhunt** [comment]
strangely enough intended, though a PR to make it have an APC would probably be accepted

**Comment by RipGrayson** [comment]
This was addressed here,
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10509
