### ISSUE TITLE
Hivemind can no longer weed FOB/Tadpole

### ISSUE THREAD

**Issue by Crystal9156** [tgstation/TerraGov-Marine-Corps#10078]
### Description

Hivemind should be able to place weeds in FOBs as long as they have LOS. 

They in fact can't weed FOB at all anymore. "You cannot weed here" is the message.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14402](https://scrubby.melonmesa.com/round/14402)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [63e1ea78abcd96eb558f20fc694ae7acf79d8326](https://github.com/tgstation/TerraGov-Marine-Corps//commit/63e1ea78abcd96eb558f20fc694ae7acf79d8326)
The following pull requests are currently test merged:
[#9772: 'TGUI updates' by TiviPlus at commit 16b87e0607](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9977: 'Health kits chain apply' by QualityVan at commit 5afedc795b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9977)
[#10008: 'Boxing+' by breadhunt at commit beb71c8b35](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10008)
[#9979: 'Add wraith portal, remove hyperposition, remove phasing' by BraveMole at commit f8e4fc7151](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9979)

Local commit: 5e00e1f988eb64d1b7f430ef6feff7d429fab472
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Choose Hivemind.
Attempt to weed FOB or Tadpole anytime after shutters open.
You cannot.

### Screenshots

![image](https://user-images.githubusercontent.com/43763972/165654216-81f61b2b-4797-416d-ac9e-dcbe830e3455.png)

**Comment by magatsuchi** [comment]
![image](https://user-images.githubusercontent.com/88991542/167301859-1a413d04-679f-41d7-9e23-d96bb621aae1.png)

this appears to be intended behavior

**Comment by BraveMole** [comment]
Oversight from the wraith portal pr, but I like it.

Not a bug
