### ISSUE TITLE
Crusher can crest toss over wall + gen

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#10123]
### Description

Despite both wall and gen being unwalkable turfs, crusher can toss you over them if you happen to be diagonally in a tile past them. Screenshot: Wall had been where acid and razorwire now are, crusher can toss you over them.

### Test Merges

[#10098: 'Add automatic weeding to weeds ability' by Walarks at commit e03ba831db](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10098)
[#9971: 'Fixes/improves Quick Equip functionality' by Lumipharon at commit 904f89d35a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9971)
[#9772: 'TGUI updates' by TiviPlus at commit 37664ca40e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9977: 'Health kits chain apply' by QualityVan at commit 2851cbd672](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9977)

### Reproduction Steps

E

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/166341300-ec0841f1-b2e3-4e75-9080-acc7ebadad26.png)

**Comment by Lumipharon** [comment]
"Stop tossing me, you can't do that over a generator!" Said the unga.
"Lol." Said Pitboss. "Lmao"

**Comment by BraveMole** [comment]
Yeah, not a real bug.

It is really unintuitive and I can understand the salt, but that's how the game work
