### ISSUE TITLE
USL powder money miniflamer has no nozzle

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#10135]
### Description

what I expect to happen
> see that I can use miniflamer
> activate miniflamer
> right click
> shoot out flames

what actually happens
> see that I can use miniflamer
> activate miniflamer
> right click
> this miniflamer has no nozzle

### Test Merges

[#9977: 'Health kits chain apply' by QualityVan at commit 2851cbd672](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9977)
[#9772: 'TGUI updates' by TiviPlus at commit 37664ca40e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9971: 'Fixes/improves Quick Equip functionality' by Lumipharon at commit 904f89d35a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9971)

probobly irrelevant

### Reproduction Steps

watch round end
join as ERT
roll USL powder monkey (dunno about other ERT kits I only checked this one)
see that you can use miniflamer
activate miniflamer
right click
this miniflamer has no nozzle

**Comment by Lumipharon** [comment]
It seems to be an issue that attached weapons do not themselves get attachments when spawned as part of the gun.

The actual miniflamer attachment itself works fine when spawned separately. I'm not entirely certain how to fix the root issue.
