### ISSUE TITLE
Deployables cannot be placed on a huge percentage of tiles

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#10165]
### Description

Caused by #10152

The above PR restricted deployables from being deployed on a turf with ANY structures or machinery, dense or not.
This uh, includes this such as: 
- Power cables
- disposal or air pipes
- buttons
- extinguisher cabinets
- light fixtures
- patches of grass
etc etc

This probably needs to be reverted, or a large white list/black list of things need to be setup for this to work properly.

### Test Merges

Not relevant

### Reproduction Steps

Place deployable on a tile with a power cable under the floor
Cry

### Screenshots

![image](https://user-images.githubusercontent.com/7869430/167323338-62422974-884a-4eae-809d-89b56f0c3e64.png)

**Comment by FosterGrime-Heymynameslouie** [comment]
speed revent pr, cant place the literally all engie deployables in 90% of tiles this sucks

**Comment by Lumipharon** [comment]
Closed by #10166
