### ISSUE TITLE
250-T FuelTank not refilling standard 250-T ammo tanks.

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#1018]
Discovered by accident during one of the attempts to refuel the 20/100 fuel tank and later 0/100 one only to receive a message that 'The bag is full'. To clarify, in description of the object it says that it contains 500 units of 250-T flamer fuel.

**Comment by Shadow-Quill** [comment]
Did you _drag_ the tank to the bag?

**Comment by Urthrem** [comment]
I tried all attempts to refuel. Dragging, clicking on the tank when its on the back, when its in other hand, clicking the fueltank with the tank, clicking the fueltank with tank, trying to refuel while fueltank was on the ground as well.

**Comment by Alterist** [comment]
i think the fuel tank has to be empty before it can be refueled, carryover from CM

**Comment by DominikPanic** [comment]
Yeah because the fire proc uses only one kind of fuel, mixing fuel is not allowed. It should allow the same one though.

**Comment by Urthrem** [comment]
I was using the Spec one and as said, I did forget to add that I did try to repeat the process after I emptied the tank completely. But also yeah, I would argue that if anything then only the tanks with special flames (Blue and green) shouldn't be refillable with Specs fueltank
