### ISSUE TITLE
SG Rifle ammo factory recipe

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/TerraGov-Marine-Corps#10226]
### Description

Round ID: [14629](https://scrubby.melonmesa.com/round/14629)

The factorio portion of requisitions still has a recipe for making T-25 refills, despite the recent removal and replacement of the weapon.

### Test Merges

[#9938: 'Orion Military Outpost' by tyeagg at commit d27217ec5c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9938)

### Reproduction Steps

Examine requisition's factory order list, and factory recipes.

### Screenshots

![Screenshot 2022-05-15 193534](https://user-images.githubusercontent.com/85206687/168505426-3ca2338d-4fc4-4add-8591-6b88fb21972c.png)

**Comment by Arctrooper8** [comment]
Working on SG minigun factory, I forgot to fully remove the T-25 parts stuff but will do so soon.
