### ISSUE TITLE
making and destroying resin walls fucks with the floor beneath

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#1023]
if you make a resin wall and destroy it, the floor beneath gets fucked with:
snow reappears on rice colony
directional floor tiles get forced to face down

**Comment by DominikPanic** [comment]
That's because they're a proper turf, and the old_turf is stored as a variable so it only places the default type instead of the specifics like icon_state, etc. Not sure how to properly fix this though.

**Comment by Rohesie** [comment]
Possibly by turning xeno walls into structures.

**Comment by psykzz** [comment]
Would it work out, if we force a turf under a wall to be a weed?

**Comment by Rohesie** [comment]
The long-term solution is to port the way /tg/ handles turf changes, which is not a small change. I've started doing part of it, but there's more to go.
