### ISSUE TITLE
Railgun APDS bug

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#10238]
### Description

At the moment there's a chance for the railguns APDS ammo to go over a xeno instead of hit it. I have reason to suspect this to be the pierce code attached to it piercing before it does any actual damage. I confirmed this issue when i watched it fly over a runner and do no damage only to smack the shit out of a wraith behind him.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14658](https://scrubby.melonmesa.com/round/14658)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [9b4eac96e6613e7e128576b575d6b10438cf4b4e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9b4eac96e6613e7e128576b575d6b10438cf4b4e)
The following pull requests are currently test merged:
[#10227: 'Sandbags are unmeltable.' by Pariah919 at commit 39b8ee9673](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10227)
[#10129: 'Med rework' by goose4429 at commit 7a61b19915](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10129)
[#9938: 'Orion Military Outpost' by tyeagg at commit d27217ec5c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9938)
[#10125: 'Railgun Changes' by tyeagg at commit 80870f0a32](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10125)
[#10224: 'Armor Check Refactor (Now With Manual Merge Conflict Resolution)' by KornFlaks at commit a3a5e5243a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10224)

Local commit: bbb46488d17807e0c0842fcd3f0ff8b9f90a3741
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. acquire railgun
2. acquire APDS ammo for it
3. shoot at moving or active xenos till one of the rounds eventually just flys over it

### Screenshots

sadly I don't have screenshots nor was I recording the incident.

**Comment by BraveMole** [comment]
You can dodge railgun by timing your movement well
