### ISSUE TITLE
AI remotely controlled droids/UGVs doesn't provide camera feed & cannot be spoken through

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/TerraGov-Marine-Corps#10234]
### Description

Round ID: [14649](https://scrubby.melonmesa.com/round/14649)

When remotely controlling a droid as an AI you are unable to see the area around the droid, which severely restricts the usability of the droid, preventing you from either seeing where the enemy is or knowing where you are going.

In addition, the AI is unable to speak through drones using ".h", as it previously was able to.

### Test Merges

[#9938: 'Orion Military Outpost' by tyeagg at commit d27217ec5c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9938)
[#10129: 'Med rework' by goose4429 at commit 7a61b19915](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10129)
[#10227: 'Sandbags are unmeltable.' by Pariah919 at commit 39b8ee9673](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10227)

### Reproduction Steps

Camera Feed Bug
1. As an AI, remotely control a drone/droid.
2. Move to an area on the edges of vision covered by ship cameras or helmet cameras.
3. Be unable to see past the vision of the cameras.

Droid Chatter
1. As an AI, remotely control a drone/droid.
2. Use ".h" as a prefix in any sentence while still remotely controlling the droid.
3. Receive silence.

### Screenshots

![Screenshot 2022-05-17 180301](https://user-images.githubusercontent.com/85206687/168951395-a67cd721-5d82-436d-abba-638e2d70a9d5.png)

**Comment by BraveMole** [comment]
Duplicated and soon to be fixed
