### ISSUE TITLE
bullet despawn issue

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#10237]
### Description

This was found with the br-64 marksmen rifle. Currently if you put a T-47 rail scope on it the bullets will despawn about 5ish tiles before they reach the end of your vision range. As you can guess this causes some problems (i blame the wide screen pr)

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14657](https://scrubby.melonmesa.com/round/14657)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [9b4eac96e6613e7e128576b575d6b10438cf4b4e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9b4eac96e6613e7e128576b575d6b10438cf4b4e)
The following pull requests are currently test merged:
[#10227: 'Sandbags are unmeltable.' by Pariah919 at commit 39b8ee9673](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10227)
[#10129: 'Med rework' by goose4429 at commit 7a61b19915](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10129)
[#9938: 'Orion Military Outpost' by tyeagg at commit d27217ec5c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9938)
[#10125: 'Railgun Changes' by tyeagg at commit 80870f0a32](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10125)
[#10224: 'Armor Check Refactor (Now With Manual Merge Conflict Resolution)' by KornFlaks at commit a3a5e5243a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10224)

Local commit: bbb46488d17807e0c0842fcd3f0ff8b9f90a3741
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Get br-64
2. put a T-47 rail scope on it
3. fire it at max vision range

### Screenshots

![image](https://user-images.githubusercontent.com/77692311/169143280-d19706fe-59ec-44ef-85d0-ed96409cdc9f.png)
the gun i was using when i found this issue

**Comment by BraveMole** [comment]
> Max range of BR bullets is 20 tiles now. I unno if this was an intended change.

Always was, no ?

Anyway this is definitly not a bug
