### ISSUE TITLE
Pipes being rotated due to tadpole landing on it

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#10286]
### Description

What we expect

![image](https://user-images.githubusercontent.com/6610922/170129665-289ff94e-fd9a-48a2-92d7-72933aeee786.png)

What happened when tadpole lands on pipe

![image](https://user-images.githubusercontent.com/6610922/170129706-c73daab2-ca28-438b-8eec-1ae0bd00e556.png)

Bravemole asks me to make bug report.

### Test Merges

tadpole

### Reproduction Steps

1. have tadpole
2. rotate tadpole
3. land on pipes
4. check pipes
5. pipes are rotated

**Comment by tyeagg** [comment]
this also effects turfs with dirs
