### ISSUE TITLE
Going into a cryopod makes your surroundings disappear

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/TerraGov-Marine-Corps#10297]
### Description

Round ID: [14765](https://scrubby.melonmesa.com/round/14765)

When you go into a cryopod **(The medical one.)** , all your nearby surroundings turn invisible.

This includes
- Mobs
- Objects
- Furniture
- Vendors
Etc.
The only things which remain visible is the floor and walls.

### Test Merges

[#10233: 'Rework accuracy mechanics' by Lumipharon at commit 1b6653d8c3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10233)
[#10269: 'Github my beloathed (PC gains charge on hit)' by Arctrooper8 at commit 9f6c93dbee](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10269)
[#10131: 'Robot overclocking, or how I learned to love the no crit robot.' by Arctrooper8 at commit ad89514be7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10131)

### Reproduction Steps

1. Go into a cryopod. 
2. Witness your surroundings disappear.

### Screenshots

![Screenshot 2022-05-26 193112](https://user-images.githubusercontent.com/85206687/170610833-bb05afd6-b881-4923-a8e1-75ec7e3bedec.png)

**Comment by Al-1ce** [comment]
This seems completely intended? The same also happens in a cryotube.
