### ISSUE TITLE
New Smartgun PR Bug

### ISSUE THREAD

**Issue by Durandalphor** [tgstation/TerraGov-Marine-Corps#10317]
### Description

SG-85 Smart Minigun Power Pack is unable to be reloaded from SG-85 Ammo Bins.
Clicking, dragging, unloading a handful of rounds and doing either do not work.
I spoke with Zack24 and he confirmed that the reloading is bugged.

### Test Merges

Round ID: [14790](https://scrubby.melonmesa.com/round/14790)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [71b7a66ba881c39fe8d829aec5a3e2e3d7784c32](https://github.com/tgstation/TerraGov-Marine-Corps//commit/71b7a66ba881c39fe8d829aec5a3e2e3d7784c32)
The following pull requests are currently test merged:
[#10034: 'Rocinante Polar Colony' by tyeagg at commit db3fe7566a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10034)
[#10265: 'Tadpole Gunship Expansion 2' by tyeagg at commit 83d7e91cd8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10265)
[#10268: 'SG Minigun Definitive Edition' by Arctrooper8 at commit 28419395cb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10268)
[#10273: 'TGUI Hive Status (Completed!)' by KornFlaks at commit 11cf0508d3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10273)
[#10300: 'Converts Bullet Ping Overlay Duration to Subsystem' by KornFlaks at commit 5aaca2222a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10300)

### Reproduction Steps

Try to reload the SG-85 Powerpack

### Screenshots

Not sure how to screenshot this

**Comment by Arctrooper8** [comment]
Fixed, I forgot the refillable flag for the powerpack from an earlier version of the branch. (Merge conflicts my beloved)
The TM just needs to be updated then we can all enjoy the wonders of minigun ammo bins.
