### ISSUE TITLE
Another Smart Minigun Bug

### ISSUE THREAD

**Issue by Durandalphor** [tgstation/TerraGov-Marine-Corps#10339]
### Description

Smart Minigun and associated items cannot be pulled from the Automated Loadout Vendor (saved loadout vendor). However, it is doing something as the Smartgun Vendor shows the items having been pulled, but they are not in my inventory.

### Test Merges

Round ID: [14801](https://scrubby.melonmesa.com/round/14801)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [3fd43eb9edece4c4c5619d184647af0a066549f5](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3fd43eb9edece4c4c5619d184647af0a066549f5)
The following pull requests are currently test merged:
[#10314: 'Adds an argument to flamer_fire_act, buffs flamer against resin' by QualityVan at commit c108b2ca51](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10314)
[#10265: 'Tadpole Gunship Expansion 2' by tyeagg at commit 83d7e91cd8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10265)
[#10268: 'SG Minigun Definitive Edition' by Arctrooper8 at commit 29c2393158](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10268)

### Reproduction Steps

Make a loadout with the new Smart Minigun items
Save in the Loadout Vendor
Try to pull it out

### Screenshots

![SmartGun_sc_3](https://user-images.githubusercontent.com/71823262/170897515-97846209-9e63-4432-90b5-40a5b8b6e739.PNG)
![SmartGun_sc_2](https://user-images.githubusercontent.com/71823262/170897517-eabec9c9-5446-4f77-8234-ea83ff28ba73.PNG)
![SmartGun_sc_1](https://user-images.githubusercontent.com/71823262/170897519-82f9de90-b17a-42b9-a6fc-e1617f7abb2d.PNG)

**Comment by Arctrooper8** [comment]
Strange bug, I'll start working on fixing it.
Thanks for making an issue report.

**Comment by Arctrooper8** [comment]
Do you know if SG-29 and associated items can be pulled from the vendor?

**Comment by Durandalphor** [comment]
Not sure, I haven't made a loadout with the new variant of that. Ill try it out when I can!

**Comment by Arctrooper8** [comment]
Fix is up!

**Comment by Durandalphor** [comment]
awesome! Ill let you know if I run into anything else but so far Im loving the new minigun
