### ISSUE TITLE
Green visor color option results in a white visor

### ISSUE THREAD

**Issue by Durandalphor** [tgstation/TerraGov-Marine-Corps#10369]
### Description

If you try to make any marine helmet visors green they instead become white. This issue has been a thing since we changed fom RGB coloring to the more limited options.

### Test Merges

Round ID: [14846](https://scrubby.melonmesa.com/round/14846)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [e1d5be187440ba9250a954dce3c475b5b450d787](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e1d5be187440ba9250a954dce3c475b5b450d787)
The following pull requests are currently test merged:
[#10287: 'Ice Colony Changes: Nuclear War Edition' by novaepee at commit f1564e2b33](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10287)
[#10313: 'Mobs no longer breathe' by BraveMole at commit 465e4209b7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10313)

Local commit: 57a5945f334d271eed6661dc490b946d023f6278
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Grab a green facepaint and a helmet
right click to change visor color
select green
get a white visor

### Screenshots

![visorissue_1](https://user-images.githubusercontent.com/71823262/171534512-279cbc2e-9c11-4b0f-bb85-411c631d28c6.PNG)
![visorissue_2](https://user-images.githubusercontent.com/71823262/171534756-772e2ef9-9539-45c2-b07f-8bb76eaa8034.PNG)
![visorissue_3](https://user-images.githubusercontent.com/71823262/171534753-2931fbb1-b4d7-403a-a490-70e6b3e5c862.PNG)

**Comment by Kuro020** [comment]
Not a bug
