### ISSUE TITLE
Freezing xenos possible solution.

### ISSUE THREAD

**Issue by krutoi2000** [tgstation/TerraGov-Marine-Corps#10362]
It is wildly-known that that not a minority of xeno players experience freezing at their first shoots. But as the times goes on, mostly, you would never experience it again in a round until a new one.

It might sound not as important is it might be, but such experience can negatively affect new players to the point of never playing again.

My possible solution is this one:
Let a xeno player at the moment of spawning as xeno experience all kind of damages(of course reduced to infinitely small numbers)
or have it as a separate button.

My solution is not a perfect one, but there is no good in letting this problem be.

**Comment by BraveMole** [comment]
this is an issue tracker
