### ISSUE TITLE
Bullet speed modifiers do nothing

### ISSUE THREAD

**Issue by Jordanstolethepreciousslam** [tgstation/TerraGov-Marine-Corps#10364]
### Description

Gun variable shell_speed_mod(and by extension attachment attach_shell_speed_mod) does not affect actual projectile speed at all.
Practically it means that supressor, barrel charger and extended barrel does not affect bullet speed. It also means barrel charger is effectively a direct downgrade.

### Test Merges

None

### Reproduction Steps

1. Get a gun
2. Attach barrel charger/supressor
3. Witness no difference

Bonus steps
1. Get a gun
2. Directly modify it's shell_speed_mod to ridiculous values
3. Witness even more of no difference

### Screenshots

https://user-images.githubusercontent.com/78968085/171409953-107e8046-c114-4ec9-9c82-a4dc35fbab27.mp4

**Comment by Lumipharon** [comment]
Projectiles are supposed to stack trace and qdel if they're at negative speed, so that's pretty funny.
