### ISSUE TITLE
GL-54 Loadout Bug

### ISSUE THREAD

**Issue by maikilangiolo** [tgstation/TerraGov-Marine-Corps#10365]
### Description

When spawning/vending the GL54 via a saved loadout, it spawns without its special scope, and it also comes with a "ghost" magazines: appears loaded in the sprite, yet it is an empty magazine that can only be unloaded with unique action, after which it simply disappears.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14840](https://scrubby.melonmesa.com/round/14840)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [e1d5be187440ba9250a954dce3c475b5b450d787](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e1d5be187440ba9250a954dce3c475b5b450d787)
The following pull requests are currently test merged:
[#10287: 'Ice Colony Changes: Nuclear War Edition' by novaepee at commit f1564e2b33](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10287)
[#10313: 'Mobs no longer breathe' by BraveMole at commit 465e4209b7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10313)

Local commit: 57a5945f334d271eed6661dc490b946d023f6278
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. save loadout with GL54 (loaded in my case too)
2. spawn it
3. GL54 is scope less and with ghost magazine

### Screenshots

![image](https://user-images.githubusercontent.com/40152611/171470673-7a3d7515-9b63-4652-909a-b1d0e42b7131.png)
![image](https://user-images.githubusercontent.com/40152611/171470690-e8b882a1-5bb2-4ca1-9b64-51d8348aad68.png)

**Comment by Lumipharon** [comment]
Not sure why the mag thing is happening, but I suspect the scope issue is due to the attachment itself not being available via vendor. It should be an easy fix because there must already be code to not check for visual only stocks and the like. I'll check myself later otherwise.

**Comment by maikilangiolo** [comment]
Flamer for example spawns correctly, with a magazine loaded and full (even when saved unloaded). Might want to have a comparison I suppose.
