### ISSUE TITLE
Lemoline spawns with incorrect amount of regnant. 

### ISSUE THREAD

**Issue by Al-1ce** [tgstation/TerraGov-Marine-Corps#10395]
### Description

Lemoline ordered from req spawns in 10u containers. However, MDs spawn with the same containter that has _30u_ of Lemoline. I am to assume that this was an oversight, as ordering three different containers of lemoline is slow and inefficient. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14919](https://scrubby.melonmesa.com/round/14919)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [da2a6f52a2f1d44d43e8296d6a08c7253022b632](https://github.com/tgstation/TerraGov-Marine-Corps//commit/da2a6f52a2f1d44d43e8296d6a08c7253022b632)
The following pull requests are currently test merged:
[#10316: 'Heart and lung damage affect stamina, nothing else' by BraveMole at commit b01427fbbd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10316)

Local commit: 952ad3f9184583550e61375b769030f4718844ee
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Spawn as MD
2. Equip lemoline bottle
3. Make 90u Dermaline (with the 30u you spawn with)
4. Order more lemo' from req
5. It comes in 10u containers
6. Suffer

**Comment by Arctrooper8** [comment]
Not a bug as shown in https://github.com/tgstation/TerraGov-Marine-Corps/pull/10136
Doctors are supposed to spawn with more than the req amount.
Don't forget that if you can grind up larva and add the grinded larva to lemoline to make more lemoline.

**Comment by BraveMole** [comment]
not a bug
