### ISSUE TITLE
Defib not being able to revive even though there is no heart damage

### ISSUE THREAD

**Issue by Panzerkampfwaggen** [tgstation/TerraGov-Marine-Corps#10419]
### Description

Found out if the heart takes too much damage even after surgery you cannot revive the patient, even though there is zero heart damage shown on the body scanner

### Test Merges

The following pull requests are currently test merged:
[#10342: 'Radial menu for metal recipes + small cleanup of mats code' by breadhunt at commit 5e4388b6b0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10342)
[#10316: 'Heart and lung damage affect stamina, health and speed' by BraveMole at commit a5324e6106](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10316)

### Reproduction Steps

1. Get a patient that died to organ failure, i.e OD on oxycodone
2. Fix the heart via surgery
3. try to defib
4. get the error message that the heart has sustained too much damage
5. Check that the body scanner says there is no heart damage

### Screenshots

No screenshots

**Comment by BraveMole** [comment]
should be fixed. reopen if needed
