### ISSUE TITLE
BYOND hub connection inaccessible. 

### ISSUE THREAD

**Issue by Al-1ce** [tgstation/TerraGov-Marine-Corps#10412]
### Description

Title. Attempting to connect to the server through the hub doesn't work. I wouldn't imagine this is anything more than a typo or two on the hyperlink but I could be gravely mistaken.

### Test Merges

The following pull requests are currently test merged:
[#10316: 'Heart and lung damage affect stamina, health and speed' by BraveMole at commit 7e1d99b55d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10316)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14967](https://scrubby.melonmesa.com/round/14967)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [e091f4da76880e9672a4ba4db27a26e6d2255d00](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e091f4da76880e9672a4ba4db27a26e6d2255d00)
The following pull requests are currently test merged:
[#10316: 'Heart and lung damage affect stamina, health and speed' by BraveMole at commit 7e1d99b55d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10316)

Local commit: 011dd00cd8c29a9ba4c4c57be7b556b3e1a04dd8
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Launch BYOND
2. Access the hub
3. Attempt to join the server
5. Picture below
![image](https://user-images.githubusercontent.com/71247506/172536860-0d3b564d-0e30-4627-b358-820271badb55.png)

### Screenshots

![image](https://user-images.githubusercontent.com/71247506/172536519-eb09e5d5-202f-4f35-8527-5235aca5159f.png)

Elsa mentioned to someone else in the discord that they should report this as an issue. But they didn't. So I did.

I haven't seen this server at 10-30 pop since capture-gameplay and I'd rather not. 

![image](https://user-images.githubusercontent.com/71247506/172537025-52606305-55dd-4431-9c3f-022e04a43f5c.png)

**Comment by BraveMole** [comment]
Elsa is wrong
