### ISSUE TITLE
Loadouts don't know how to take pill bottles from the NanotrasenMed Plus

### ISSUE THREAD

**Issue by Durbles** [tgstation/TerraGov-Marine-Corps#10421]
### Description

As per the title. 

-Any pill bottle that you take from the NanotrasenMed Plus, put into storage and save into a loadout will never vend when you later equip that loadout. 
-This is as a Corpsman, by the way, so there shouldn't be any issues with access.
-The problem might only be exclusive to items vended from the NanotrasenMed Plus and saved while in the Medical Storage Module.

I think the source of the issue is this PR: https://github.com/tgstation/TerraGov-Marine-Corps/pull/10129. Before this those pill bottles vended fine when they were in the MarineMed.

### Test Merges

Round ID: [14984](https://scrubby.melonmesa.com/round/14984)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [02c5fd5d0e1df28fc0af6e993ebe0acd0f4922e0](https://github.com/tgstation/TerraGov-Marine-Corps//commit/02c5fd5d0e1df28fc0af6e993ebe0acd0f4922e0)
The following pull requests are currently test merged:
[#10342: 'Radial menu for metal recipes + small cleanup of mats code' by breadhunt at commit 5e4388b6b0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10342)
[#10316: 'Heart and lung damage affect stamina, health and speed' by BraveMole at commit a5324e6106](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10316)

### Reproduction Steps

1. Go to any NanotrasenMed Plus.
2. Vend pill bottles from the appropriate tab and add them to your inventory.
3. Save your equipped gear as a loadout.
4. Try to later vend the loadout.
5. "in your loadout is an invalid item, it has probably been changed or removed."

**Comment by Arctrooper8** [comment]
Which class are you trying to vend them as?

**Comment by goose4429** [comment]
1. https://github.com/tgstation/TerraGov-Marine-Corps/pull/10320
2. For some reason for cpsman loadouts also don't work

**Comment by Durbles** [comment]
> Which class are you trying to vend them as?

As a Corpsman. So there shouldn't be any access issues.

**Comment by BraveMole** [comment]
Just tried and no problem

**Comment by Durbles** [comment]
> Just tried and no problem

The problem seems to arise specifically when the vended items are saved in the medical storage module.

**Comment by goose4429** [comment]
> Just tried and no problem

I have same problems. Putting second INAP bottle into belt and HYPER into backpack yields nothing after loadout.

**Comment by goose4429** [comment]
In current state corpsmen don't have problems. Maybe others have

**Comment by BraveMole** [comment]
Not an issue
