### ISSUE TITLE
Nanites waste on robo limbs

### ISSUE THREAD

**Issue by goose4429** [tgstation/TerraGov-Marine-Corps#10423]
### Description

Nanites check for total body damage. If you have some, they are consumed and heal the limb.
Unless the limb is robotic - then the heal proc doesn't actually do anything. Just consumes nanites endlessly.

Fix option 1:
Check for non-robotic damage
Heal only organic limbs

Fix option 2:
Nanites are nanomachines, why not let them heal robo limbs

### Test Merges

None

### Reproduction Steps

1. Be human
2. Have nanites in blood (after they are accustomed)
3. Have robo limb with damage

**Comment by Lumipharon** [comment]
To clarify, are you saying that having a damaged robotic limb while having medical nanites in your system will just endlessly consume medical nanites until you die, because it's not actually healing the robo limb?

**Comment by goose4429** [comment]
> To clarify, are you saying that having a damaged robotic limb while having medical nanites in your system will just endlessly consume medical nanites until you die, because it's not actually healing the robo limb?

Precisely
