### ISSUE TITLE
Flares are all anchored to the ground

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#10478]
### Description

Can't pick them up after thrown, even if they aren't activated at all.

### Test Merges

[#10433: 'Add a new wraith ability: woosh swoosh' by BraveMole at commit 25ad4dc298](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10433)
[#10265: 'Tadpole Gunship Expansion 2' by tyeagg at commit 0fcc48b8d3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10265)
[#10468: 'optimize /obj/item for initialization.' by SplinterGP at commit 9f98f3e6ca](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10468)

### Reproduction Steps

Grab flare
Ignite, or don't
Throw
Can't pick it back up

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/174092692-48b24c45-d717-4b0b-857a-e4e975c7017e.png)

**Comment by QualityVan** [comment]
Fixed by the last commit to #10265
