### ISSUE TITLE
CAS pilote can't change weapon slots

### ISSUE THREAD

**Issue by krutoi2000** [tgstation/TerraGov-Marine-Corps#10474]
### Description

CAS pilot can't change weapon slots

Due to a new WASD system of changing directions, it triggers a game to block all of your possible button actions. It even goes as far as partially disconnecting you from the server.

### Test Merges

In any round

### Reproduction Steps

1. Become a pilote
2. Use Condor
3. Press WASD for changing camera view.
4. Profit.

### Screenshots

![13333333](https://user-images.githubusercontent.com/98636012/173889503-f9ea3a3b-b126-4e4c-9aa1-723c21a24098.png)

**Comment by BraveMole** [comment]
Host issues
