### ISSUE TITLE
MG42 has the halo br sprite

### ISSUE THREAD

**Issue by crayonLover09** [tgstation/TerraGov-Marine-Corps#10476]
### Description

title

### Test Merges

Round ID: [15100](https://scrubby.melonmesa.com/round/15100)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [86d1f587ca61cc16a0a176b9c374bbeae00f2853](https://github.com/tgstation/TerraGov-Marine-Corps//commit/86d1f587ca61cc16a0a176b9c374bbeae00f2853)
The following pull requests are currently test merged:
[#10433: 'Add a new wraith ability: woosh swoosh' by BraveMole at commit 25ad4dc298](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10433)
[#10265: 'Tadpole Gunship Expansion 2' by tyeagg at commit 0fcc48b8d3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10265)
[#10468: 'optimize /obj/item for initialization.' by SplinterGP at commit 9f98f3e6ca](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10468)

### Reproduction Steps

Get mg42, see halo br sprite

### Screenshots

![mg42 2](https://user-images.githubusercontent.com/105026812/173971539-1b9a379c-b74d-4cf6-9b82-367d2156a0ac.PNG)
![mg42](https://user-images.githubusercontent.com/105026812/173971541-785c33c3-e0ed-45c2-887a-006ecd68745b.PNG)

**Comment by Kuro020** [comment]
that's the intended sprite denthead
