### ISSUE TITLE
Autoinjectors tomf*ckery

### ISSUE THREAD

**Issue by CharlieDownsin** [tgstation/TerraGov-Marine-Corps#1048]
When trying to inject other people (sometimes even yourself), there will be cases of the game giving you an error message stating "You cannot directly fill this object" or some nonsense like that. Can become extremely disruptive to the point where it's impossible to administer medicine to someone.

**Comment by DominikPanic** [comment]
@Ghommie

**Comment by Ghommie** [comment]
On it.
