### ISSUE TITLE
Boiler gas is reduced after going through portals, due to the fact portals change the current Firer var to itself.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#10494]
### Description

Basically, globs have their range increased based on the maturity of the boiler, but whenever a projectile goes through a portal, it changes the firer var, so that marines are able to hit themselves with their own projectiles (this is why you never hit yourself while sprinting and shooting) This has the unfortunate side effect of changing even xeno projectiles, allowing to hit themselves, and unwittingly change the boilers gas range, due to the fact gas is dependent of maturity, which portals do not have.

![image](https://user-images.githubusercontent.com/24631139/174456664-b9a065e6-c74b-4a26-a952-dee0248495ab.png)

Side note: I'll be splitting this issue, I'll make this one meant for boiler gas, and make another issue report meant for xeno projectiles in general.

### Test Merges

doesn't matter, none of the tms affect portal.

### Reproduction Steps

1. Go to a portal
2. Throw a glob at it
3. Glob has 0 gas range even if you're ancient

### Screenshots

With Portal

https://user-images.githubusercontent.com/24631139/174456623-558db66d-286a-4827-9c62-3a77e27a151c.mp4

Without Portal

https://user-images.githubusercontent.com/24631139/174456635-2192661b-0169-4166-af9e-0dd8df605c30.mp4

Me using timestop to change the firer var, and setting it to null.

https://user-images.githubusercontent.com/24631139/174456649-8f8e7141-9615-4947-b35b-48d869e4ed44.mp4

**Comment by Autisem** [comment]
Would the time stop not effect other bullets aswel that have damage fall off? like shotguns or something
