### ISSUE TITLE
Vallhalla for xenomorphs

### ISSUE THREAD

**Issue by uuuuhuuuu** [tgstation/TerraGov-Marine-Corps#10513]
Vallhalla right now, is a greate place to practice as a marine and you can safly try out all the stuff without interrupting the round and wasting resources. Now it would be nice to improve on it and make it useful for xenos too. Right now trying out castes requires waiting for up to 30 minits  and then you just die becouse you do not know what to do. 

The feature would be adding option to spawn as xeno any xeno with choosable maturity in vallhalla . To further improve on it ,you can also add way to spawn marines wearing some specific gear to see how many hits you need to kill marine wearing that gear. Or it can be achieved by some preset human and robot dummies that respawn when they die.

This feature would make players able to try out all the castes and abilities without fear of making the round worse for others and that can help both xenos (to know how they work) and marines (to know what they are facing).

**Comment by RipGrayson** [comment]
As TGMC's unofficial lead mapper, I can assure you this is something on the agenda. Hopefully it will done by the end of the year.

**Comment by BraveMole** [comment]
This is a issue tracker not a feature request tracker sorry
