### ISSUE TITLE
Dispenser doesn't heal robotic limbs (TMC bug)

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#10521]
### Description

read title,

### Test Merges

https://github.com/tgstation/TerraGov-Marine-Corps/pull/10425/

### Reproduction Steps

1. Get a robot
2. Place dispenser
3. Be hurt
4. Don't get healed
5. Change the robotic_limb into a human limb
6. It starts healing

### Screenshots

https://user-images.githubusercontent.com/24631139/175721732-224bc705-44df-4da2-a369-02a3e089053b.mov

**Comment by BraveMole** [comment]
dispenser dead again
