### ISSUE TITLE
[bug] Reqtorio pamphlet incorrect

### ISSUE THREAD

**Issue by Araulius** [tgstation/TerraGov-Marine-Corps#10564]
### Description

the instructions for scout rifle ammo under the reqtorio pamphlet are incorrect. this is weird to me, because i wrote the code for that addition to reqtorio, and the pamphlet instructions. someone diddled my code.

### Test Merges

Round ID: [15387](https://scrubby.melonmesa.com/round/15387)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [24a4c9323d58f334c262fdc41c177bec47c69424](https://github.com/tgstation/TerraGov-Marine-Corps//commit/24a4c9323d58f334c262fdc41c177bec47c69424)
The following pull requests are currently test merged:
[#10489: 'Stun tweaks' by Losenis at commit 14046365b0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10489)

Local commit: 0582bf72cac54586e63283e4d3a349cfc5196161
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

set up factory for battle rifle 8 mags as the pamphlets instruct, and behold as it is unfinished.

**Comment by mrhugo13** [comment]
Less of a bug more of an oversight, the oversight-er being the person who did #9265 forgot to remove the last tidbit with the BR-8 scout rifle magazine when they merged it into the IFF ammo recipe
