### ISSUE TITLE
Shoulder Attachment armor module cannot reload as intended

### ISSUE THREAD

**Issue by maikilangiolo** [tgstation/TerraGov-Marine-Corps#10580]
### Description

Per description, right-clicking the armor in which a shoulder gun is mounted, with ammo in hand, reloads the gun. this does not happen. I have tested it with the flamethrower and las carbine, both do not work. 
you have to take off the armor, remove the module from the armor and manually reload the gun.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [15452](https://scrubby.melonmesa.com/round/15452)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [18fbf6b5d90fe462e23f2e7e80376e8c35bed55a](https://github.com/tgstation/TerraGov-Marine-Corps//commit/18fbf6b5d90fe462e23f2e7e80376e8c35bed55a)
The following pull requests are currently test merged:
[#10425: 'Adds Dispenser, take Â³' by SplinterGP at commit 3038f38f9a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10425)

Local commit: 49dd388587c1a2ae4d2d79dae5419707101a63a5
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. attach module to one gun compatible with shoulder module (of which there are a pitiful few)
2. put on the armor
3. get ammo for the gun
4. right click the armor
5. ???
6. "there is no room for [magazine name]

**Comment by BraveMole** [comment]
Tested and working as intended.

But how do you even use shouldermount of flamethrower?
