### ISSUE TITLE
Backpacks dont render properly (or entirely) on robots

### ISSUE THREAD

**Issue by helper-2** [tgstation/TerraGov-Marine-Corps#10604]
### Description

If you put different backpacks on your roboback, only TGMC satchel and TGMC lightweight backpack will render their sprites, and only small part of them. Other backpacks dont even sprited at all.

### Test Merges

nope

### Reproduction Steps

1. Be robot
2. Worn welding backpack
3. Sprite unchanged

### Screenshots

Without backpack
![(null)scrnshot1](https://user-images.githubusercontent.com/107619191/178468752-e1753915-dc78-4150-a768-27da89b22ce2.png)
![scrnshot2](https://user-images.githubusercontent.com/107619191/178468797-f8fd88ff-a2e0-4b40-91e5-1f9dd8b6f336.png)

With TGMC satchel
![scrnshot3](https://user-images.githubusercontent.com/107619191/178468997-ba10977f-bbfb-4b1f-95a5-0aeb617d4bff.png)
![scrnshot4](https://user-images.githubusercontent.com/107619191/178469032-8966075b-daba-4e22-9b5f-03cc848de873.png)

With TGMC lightweight backpack
![scrnshot5](https://user-images.githubusercontent.com/107619191/178469160-71ca5286-2361-48bf-9fbc-0486d1b859b5.png)
![scrnshot6](https://user-images.githubusercontent.com/107619191/178469179-ddf0815d-1e3c-41e1-9641-a07ff89371c4.png)

With TGMC corpsman backpack
![scrnshot7](https://user-images.githubusercontent.com/107619191/178469301-09fabb86-354b-472c-babc-c0da28af8fe8.png)
![scrnshot8](https://user-images.githubusercontent.com/107619191/178469349-663f699f-956b-4133-baa0-d9c207b207fe.png)

With welderpack
![scrnshot9](https://user-images.githubusercontent.com/107619191/178469491-01b8179d-c2b3-48ee-a9c5-f902699fa359.png)
![scrnshot10](https://user-images.githubusercontent.com/107619191/178469512-dd36a6d7-97e3-4e20-b62e-d8c6e95c4f9f.png)

With industrial backpack (from lockers)
![scrnshot11](https://user-images.githubusercontent.com/107619191/178469780-84ee39c7-6201-42f5-ad0b-1a945354b78e.png)
![scrnshot12](https://user-images.githubusercontent.com/107619191/178469792-e7442199-8fe3-4994-9150-43bde1a6cdae.png)

With leather satchel (from ERT)
![scrnshot13](https://user-images.githubusercontent.com/107619191/178470003-7d5a87b6-18d5-4cbb-bbbf-5783a686c733.png)
![scrnshot14](https://user-images.githubusercontent.com/107619191/178470016-a12fe369-15ad-4467-a1b9-e3a8a089fb35.png)

Same problem with others backpacks, but I dont think it needed to screenshot every single one.

**Comment by Kuro020** [comment]
its intended, robots need unique backpack sprites since their mob sprite is different, so the bags that dont have a unique sprite dont show onmob
