### ISSUE TITLE
ai can control doors groundside from shipside

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#10606]
### Description

Pr in question : #7267

Pr affecting airlock code and ai code

![image](https://user-images.githubusercontent.com/24631139/179335721-6832a0df-d69a-48eb-8ba5-60d8ec248e45.png)

On-click code

![image](https://user-images.githubusercontent.com/24631139/179335730-82b61b6c-c904-4dcb-94ff-62a9cd88adfb.png)

### Test Merges

none, it was already merged. #7267

### Reproduction Steps

1. Get power groundside.
2. Ai can open, close, and bolt doors.
3. Profit.

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/179335801-7c91a1e7-075d-4c5a-84e6-a52b42f9df2c.png)
![image](https://user-images.githubusercontent.com/24631139/179335802-69b1ceae-6dcb-4293-a9f6-73b27a50daa2.png)

**Comment by Al-1ce** [comment]
This was already discussed and decided to have been fine months ago.

**Comment by BraveMole** [comment]
No this is a bug

**Comment by Wayland-Smithy** [comment]
The proc in your first screenshot is being overridden with `return True` in #7569
https://github.com/tgstation/TerraGov-Marine-Corps/blob/3d778ed9fadfd6fe1fbbb539b7cb34ff64ba3ba4/code/game/objects/machinery/doors/airlock_types.dm#L883-L884
Should it be just for `airlock/dropship_hatch/`?

**Comment by Derrick2Electricboogaloo** [comment]
I am not sure how this was a bug. This definitely felt very intentional. Who was the bean that got fucking ganked by an ai?
