### ISSUE TITLE
Players can vote more than 100 times via clicking the same option

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#10623]
### Description

I expect multiple choices, not rigging the votes.

### Test Merges

#10612

### Reproduction Steps

1. Make votes.
2. Click once.
3. One vote.
4. Click twice on the same choice.
5. Two votes.
6. Click on same choice to infinity.
7. 1000 votes since people caught on.

### Screenshots

https://www.youtube.com/watch?v=ojmD44BJwyA

**Comment by FosterGrime-Heymynameslouie** [comment]
I love democracy

**Comment by blackdav123** [comment]
I think this only happens on votes with two options like the gamemode vote and is definitely caused by [#10612](https://github.com/tgstation/TerraGov-Marine-Corps/pull/10612)

**Comment by Lumipharon** [comment]
Runtime on restart vote occurs after voting, removing the vote, then voting again.
![image](https://user-images.githubusercontent.com/7869430/181408352-0510ca86-628d-4b9f-8976-d9ef22b57ac7.png)

When a vote wasn't a multivote, the user was not being removed from the voted list, so they could vote, then unvote fine, but if they vote again after that it would runtime there and do the funny.
