### ISSUE TITLE
MG27 had incorrect firerate temporarily

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#10630]
### Description

Code implies it shold have 0.15 firerate, doesn't look like any TMs touch on it, and ahelped to be told nothing was VVd. Eventually it fixed itself, was told nothing was edited still. Something might be messing with firerates in some manner. It even updated the codex as screenshotted, no lag. 

Round ID: [15679](https://scrubby.melonmesa.com/round/15679)

### Test Merges

[#10567: 'Dead marines do not reduce number of xenos for crash' by Autisem at commit 369504ef45](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10567)
[#10579: 'Combat Patrol game mode - TGMC vs SOM' by Lumipharon at commit a047e8c5bc](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10579)

### Reproduction Steps

Grab MG27
Magic

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/180692031-388b4b23-5e51-4971-8c62-710622709ad8.png)
![image](https://user-images.githubusercontent.com/72712909/180692062-bc0d2f73-aee4-4d54-9ae1-f13f3032f5ad.png)
![image](https://user-images.githubusercontent.com/72712909/180692076-34ee5abe-e4b3-4b73-a96c-7d1f651a8b12.png)

**Comment by Lumipharon** [comment]
Are you sure the firerate was actually incorrect, and not just the codex entry?

**Comment by Losenis** [comment]
Yeah I kinda needed to find that out before even checking the codex, it shot way slower and I shot a T12 to check if it was just lag but no it shot just fine at the same time

**Comment by BraveMole** [comment]
Not enough context
