### ISSUE TITLE
Tactical sensor doesn't work in tarp 

### ISSUE THREAD

**Issue by Lauwma** [tgstation/TerraGov-Marine-Corps#10636]
### Description

I expected to be able to use tactical sensor while in tarp.
The tactical sensor does not beep even if a xeno is standing next to you

### Test Merges

#10579 
#10567

### Reproduction Steps

1. Go in tarp
2. wield gun with tacsensor or tacsensor
3. Activate tacsensor (or it's already activated)
4. no beeps even if there's xenos around

**Comment by Wayland-Smithy** [comment]
Tarp works like a locker, so that probably has something to do with it.
Bet you don't show up on other friendly sensors at all either or for resin turrets and silos.

Might be a case of feature not a bug here and the description just needs to make it clear tarp blocks sensors.

**Comment by Lauwma** [comment]
> Tarp works like a locker, so that probably has something to do with it.
> 
> Bet you don't show up on other friendly sensors at all either or for resin turrets and silos.
> 
> 
> 
> Might be a case of feature not a bug here and the description just needs to make it clear tarp blocks sensors.

Actually from what I understand in the code tarp functions the same way as a bodybag. (That's probably the same thing as a locker though). In HvH this feature makes it more interesting since it would counter tac sensors though in HvX I'd like to think being able to read tac sensor while you are in a tarp to see if you are out of danger would be a pretty interesting use (or also to prepare to ambush the enemy)

**Comment by Wayland-Smithy** [comment]
> (That's probably the same thing as a locker though)

Correct, and the trouble is that does funny things to your mobs location like vent crawling does to xenos which tac sensor and the hive tracker depend on to function.

I agree it would be the most fun if it worked in tarp, but I fear a fix will be a huge undertaking.

**Comment by BraveMole** [comment]
More of a feature request than a bug per se. 

Would probably be nice though
