### ISSUE TITLE
recycler does not work on the pillar of spring

### ISSUE THREAD

**Issue by restedwaves** [tgstation/TerraGov-Marine-Corps#10652]
### Description

the recycler should remove things that are belted into it, it does not do so

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [15761](https://scrubby.melonmesa.com/round/15761)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [a3363bfdf0467375ecebe88a7153c9d8248dc7b7](https://github.com/tgstation/TerraGov-Marine-Corps//commit/a3363bfdf0467375ecebe88a7153c9d8248dc7b7)
The following pull requests are currently test merged:
[#10634: 'Adds normal smoke grenades' by Lauwma at commit 7ef930e0e1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10634)
[#10567: 'Dead marines do not reduce number of xenos for crash' by Autisem at commit d316869fa7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10567)
[#10558: 'Vendors improve' by goose4429 at commit c857ce75eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10558)
[#10629: 'Remove permutated from projectile code' by BraveMole at commit e9e3026a99](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10629)

Local commit: 5443d5fc88b483b92b5637889f2a1bbb4cd85fda
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

turn on the recycler's belt, watch as the garbage is all merely forced to one tile in front of said recycler

**Comment by Derrick2Electricboogaloo** [comment]
Easy fix, copy minerva, or Sulaco recycler and replace it. It will then work.

**Comment by Lumipharon** [comment]
not sure if this is still occuring, but easy fix.
