### ISSUE TITLE
Synth's getting human limbs after aheal

### ISSUE THREAD

**Issue by Panzerkampfwaggen** [tgstation/TerraGov-Marine-Corps#10661]
### Description

we rolled crash so icy did a small event, I was playing synth and he wanted to make my sprite big but I died and got my right hand chopped off, icy ahealed me and the right hand I received was an organic hand, I could even break the bones of the right hand.

### Test Merges

[#10629: 'Remove permutated from projectile code' by BraveMole at commit e9e3026a99](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10629)
[#10558: 'Vendors improve' by goose4429 at commit c857ce75eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10558)
[#10567: 'Dead marines do not reduce number of xenos for crash' by Autisem at commit d316869fa7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10567)
[#10634: 'Adds normal smoke grenades' by Lauwma at commit 7ef930e0e1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10634)

### Reproduction Steps

1. spawn a synth
2. delimb a hand or a foot of the synth
3. aheal the synth
4. damage the replaced limb
5. try to fix it with solder
6. it says it's not a robotic limb

**Comment by helper-2** [comment]
Aheal also replace robots limbs with organic limbs
