### ISSUE TITLE
Infinite tile distance when patching combat bot with wire to resolve burn damage

### ISSUE THREAD

**Issue by caballs** [tgstation/TerraGov-Marine-Corps#10688]
### Description

I expected the channel cast when repairing burn damage via wire on combat androids to stop.

The channel cast did not stop when repairing burn damage via wire, and persisted even when 7 tiles away.

### Test Merges

Round ID: [15817](https://scrubby.melonmesa.com/round/15817)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [c1c3c67410f6c4e80b2f5530d36a90e8a4183e4d](https://github.com/tgstation/TerraGov-Marine-Corps//commit/c1c3c67410f6c4e80b2f5530d36a90e8a4183e4d)
The following pull requests are currently test merged:
[#10634: 'Adds normal smoke grenades' by Lauwma at commit 7ef930e0e1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10634)
[#10558: 'Vendors improve' by goose4429 at commit c857ce75eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10558)
[#10629: 'Remove permutated from projectile code' by BraveMole at commit e9e3026a99](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10629)
[#10595: 'Converts auras to a subsystem' by QualityVan at commit 129e3ffcc8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10595)

Local commit: 899fca4cecb9c9a32fa41a5ae91edf37fd2267cc
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Attempt to fix burn damage on combat android
2. Utilize wire to fix burn damage
3. Have combat android move away during channel cast
4. Repairing damage persists even when distanced

**Comment by Derrick2Electricboogaloo** [comment]
Little known secret :) Makes for good times.
