### ISSUE TITLE
Loadouts don't take from NTMed+ on Sulaco

### ISSUE THREAD

**Issue by goose4429** [tgstation/TerraGov-Marine-Corps#10694]
### Description

Title. Seems like it only happens on Sulaco.

### Test Merges

None

### Reproduction Steps

1. Take corpsman on Sulaco
2. Be frustrated

### Screenshots

https://tenor.com/view/skill-issue-gif-19411985

**Comment by Derrick2Electricboogaloo** [comment]
I do believe this is now fixed.
