### ISSUE TITLE
Alamo wrong gib radius

### ISSUE THREAD

**Issue by goose4429** [tgstation/TerraGov-Marine-Corps#10697]
### Description

When Alamo lands, everything below it (blue circles) is gibbed/deleted.
However, sometimes this gib radius is far larger.
Last game, on hijack, marines were gibbed 5(!) tiles away from landing area.
If this intended, adjustments to "landing area" should be made.

### Test Merges

None

### Reproduction Steps

1. Hijack Alamo
2. Stand near Alamo when it is landing
3. Get gibbed, even though you're outside of zone where Alamo landed.

**Comment by BraveMole** [comment]
Looks like big one off due to lag. 

Were there a lot of players ? I don't think that happens on a daily basis

**Comment by Lumipharon** [comment]
alamo has kill zones around the entrances, to stop it from getting stuck in dead areas. You uh, probably don't want to be standing near the alamo when it crashes.
