### ISSUE TITLE
Xenos are instantly regenerating off crit

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#10700]
### Description

Per title. Xenos are capable of regenerating immediately out of crit.

I figure the intended behavior is for xenos to be stuck in crit for at least a few moments, giving people the chance to kill them proper.
As is currently, they can go into crit and immediately get back up.

### Test Merges

Irrelevant; this bug has been in game for almost a month now, and should be unaffected by TMs.
Regardless: #10634, #10558, #10629, #10595

### Reproduction Steps

1. Crit a xeno.
2. Watch it get back up immediately.
3. Miss the kill.
4. Cry.

**Comment by blackdav123** [comment]
if this is just xenos hitting their heal tick right after they get downed cope seethe not a bug etc

**Comment by BraveMole** [comment]
Not a bug
