### ISSUE TITLE
88 Mod 4 lack ammo packets

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#10716]
### Description

The vendor has 9mm packets, but the 88 Mod 4 pistol uses a different 9mm cartridge incompatible with the packet. The packet is for P14 and such.

### Test Merges

None

### Reproduction Steps

Try to load a 88mod4 mag with 9mm.

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/182914049-a8b98574-6f81-4f58-a0cd-63bb7ac65c6f.png)

**Comment by Liznerd** [comment]
i could swear it was intended with how good the weapon is

**Comment by Xander3359** [comment]
88Mod uses packet of 9mm AP. This is resolved.
![image](https://user-images.githubusercontent.com/66163761/221987503-2e5a6b01-3f9c-4259-b8dd-55798b966e18.png)
