### ISSUE TITLE
Autodoc and Cryo are no longer healing organs

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#10717]
### Description

Per title.

### Test Merges

None.

### Reproduction Steps

1. Get organ damage.
2. Try to heal via autodoc or cryo.
3. Organs are still damaged.

**Comment by QualityVan** [comment]
Cryo isn't a bug, can't replicate with autodocs.

**Comment by Derrick2Electricboogaloo** [comment]
It is because of no Peri

**Comment by Xander3359** [comment]
Autodoc fixes organs and cryo doesn't fix organs (cryo isnt supposed to). This is resolved.
