### ISSUE TITLE
Ai can't give orders

### ISSUE THREAD

**Issue by Panzerkampfwaggen** [tgstation/TerraGov-Marine-Corps#10722]
### Description

Can't give orders as AI to point out xeno locations making AI nearly useless at pointing out locations

### Test Merges

Round ID: [15861](https://scrubby.melonmesa.com/round/15861)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [b866f26d1446dfcdfd7fdd4f602fcfbb3b2abeea](https://github.com/tgstation/TerraGov-Marine-Corps//commit/b866f26d1446dfcdfd7fdd4f602fcfbb3b2abeea)
The following pull requests are currently test merged:
[#10715: 'Fix climbing' by BraveMole at commit b9b2193c60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10715)

Local commit: 0e1a13ce2f1ea20a92660e174608243b527eb9db
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. play AI
2. Click to select orders
3. can't select them
4. can't alt click to give orders

**Comment by novaepee** [comment]
#10648 made it that shipside orders can't use ATTACK, DEFEND, and RETREAT orders. Still figuring out how to fix it.

**Comment by BraveMole** [comment]
Fixed
