### ISSUE TITLE
Certain spawned guns dont register ammo until you unload them and load them

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/TerraGov-Marine-Corps#10735]
### Description

Certain guns like the Double-Barrel Shotgun for SOMs or revolvers start loaded with ammo but apparently that gun thinks it doesnt have ammo loaded so you have to open them and load the ammo they have in them into them again

### Test Merges

No clue, server aint running but its still an issue on the master branch, definently has nothing to do with testmerges

### Reproduction Steps

1. Find a revolver or DB or whatever in EORD or the Firing Range
2. Attempt to fire it
3. Gun does not fire
4. Open the chamber and ammo pops out
5. Load gun with said ammo
6. Close chamber
7. Gun fires

**Comment by BraveMole** [comment]
Fixed
