### ISSUE TITLE
One-Way Emegency Doors

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1073]
## Reproduction:
1) Close any emergency shutter.
2) On shutters oriented like this:
![image](https://user-images.githubusercontent.com/44811257/54466006-e0bb4780-474b-11e9-8daa-28a0265fe85e.png)
You can pass North to South (but not south to north).
3) On shutters oriented like this:
![image](https://user-images.githubusercontent.com/44811257/54466041-047e8d80-474c-11e9-8928-313cc49f3047.png)
You can pass East to West (but not west to east).
4) All shutters can be passed through the sides.

![](https://i.imgur.com/d5qF31k.gif)
![](https://i.imgur.com/OkkZZxE.gif)

**Comment by Rohesie** [comment]
This one is likely mine, on `Adjacent`.

**Comment by Shadow-Quill** [comment]
I was looking through the emergency shutter code, and saw this:
```DM
/obj/machinery/door/firedoor/border_only/CanPass(atom/movable/mover, turf/target)
    if(istype(mover) && mover.checkpass(PASSGLASS))
        return TRUE
    if(get_dir(loc, target) == dir) //Make sure looking at appropriate border
        return !density
    else
        return TRUE
```
