### ISSUE TITLE
(F) to follow is broken.

### ISSUE THREAD

**Issue by FIXTHERADBOXPLEASE** [tgstation/TerraGov-Marine-Corps#10754]
### Description

When you're a ghost there's an (F) next to everyone's name so you can jump to them. Stopped working the last few days. Now it doesn't do anything when pressed.
Weirdly still works if you're an alive xeno trying to view another alive xeno.

This still works fine on the Russian server so I have no idea what's going on. Might just be me, honestly. But it's worth bug reporting.

### Test Merges

None.

### Reproduction Steps

Die.
Be a ghost.
Press the (F) next to someone's name in chat.
Notice how it does nothing.

**Comment by BraveMole** [comment]
Fixed
