### ISSUE TITLE
SOM Engineer Loadout 1 (at least) does not have welding goggles.

### ISSUE THREAD

**Issue by Cowbin** [tgstation/TerraGov-Marine-Corps#10755]
### Description

SOM Engineer Loadout 1 should have welding goggles on their helmet or something as they have to weld their turret to repair it.

### Test Merges

Local commit: 41ad309c6c3ce7e2fcb105a79c650a0077c74ebd
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Chose SOM engineer loadout 1/

**Comment by Lumipharon** [comment]
It's a helmet module, did you click this? 
![image](https://user-images.githubusercontent.com/7869430/184463509-2a64c71f-9d4a-46be-a42c-81f92bcc7236.png)

**Comment by Cowbin** [comment]
Maybe it was invisible, I might have been mistaken though, sorry if I was.

**Comment by BraveMole** [comment]
Not a bug
