### ISSUE TITLE
Disposable Rocket Launcher Unwieldable

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#10764]
### Description

Attempted to wield disposable rocket launcher, told me I had to deploy it to use it, similar to the text when trying to hand fire a sentry or HSG without deploying it. You also cannot deploy this rocket.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16013](https://scrubby.melonmesa.com/round/16013)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [2fea0c46cd7e81630beb603686dea6246b125b41](https://github.com/tgstation/TerraGov-Marine-Corps//commit/2fea0c46cd7e81630beb603686dea6246b125b41)
The following pull requests are currently test merged:
[#10646: 'Combat Patrol Base Remap and Fluff' by tyeagg at commit 9363ed1b8b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10646)
[#10669: 'Add a rust pathfinding' by BraveMole at commit 8306df43a9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10750: 'Projectile performance improvement' by BraveMole at commit baeb9395d6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10750)
[#10762: 'Revert "Improve do_surgery code"' by BraveMole at commit 5f524fc9f8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10762)

Local commit: be61cd5577a6c5ca526c61d73ba946b41a34f95e
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Grab Disposable rocket launcher
Attempt to wield it
Be unable to wield it

**Comment by Lumipharon** [comment]
You need to unfold it first, press space or whatever your unique action key is. That said, deploying it seems to be bugged, as the inhand sprite vanishes, the mob sprite is incorrect and it can't be fired as apparently it's empty.
![image](https://user-images.githubusercontent.com/7869430/184582782-0a7a3c76-0919-4636-b8d5-95768316901c.png)

**Comment by BraveMole** [comment]
Not a bug
