### ISSUE TITLE
Deja vu. Management of the items we touched.

### ISSUE THREAD

**Issue by CnCForever** [tgstation/TerraGov-Marine-Corps#10777]
### Description

Items, and especially containers, suddenly start to overlap interactions with other items. The pill bottles try to fit into each other instead of the belt, the webbing conflicts when removing one, causing items to fit in only one. The arm slot is occupied by an invisible item that you actually dropped on the floor, but if you REALLY drop it on the floor a second time, it will teleport to your feet like a Jedi's lightsaber. The Hypospray injects the Marine, who has long since run off the screen. And other mystical nonsense.

### Test Merges

IDK, guys. Server was launched on 08/16/2022.

### Reproduction Steps

Just try to build a loadout or interact with containers in three levels: man / belt / bottle of pills.

### Screenshots

¯\_(ツ)_/¯

**Comment by Lumipharon** [comment]
I have no idea what this is meant to be talking about.
