### ISSUE TITLE
Can't click on dark tiles to shoot

### ISSUE THREAD

**Issue by SilencedMP5A5** [tgstation/TerraGov-Marine-Corps#10787]
### Description

Title.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16057](https://scrubby.melonmesa.com/round/16057)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [599c26055d187dd3964ca10f039365268e70eaee](https://github.com/tgstation/TerraGov-Marine-Corps//commit/599c26055d187dd3964ca10f039365268e70eaee)
The following pull requests are currently test merged:
[#10762: 'Revert "Improve do_surgery code"' by BraveMole at commit 5f524fc9f8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10762)
[#10750: 'Projectile performance improvement' by BraveMole at commit baeb9395d6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10750)
[#10669: 'Add a rust pathfinding' by BraveMole at commit 8306df43a9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10646: 'Combat Patrol Base Remap and Fluff' by tyeagg at commit 9363ed1b8b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10646)

Local commit: 543f2bd36ff3a71a0b152d298df906eff86fb2d6
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Join game.
2. Be marine.
3. Get gun.
4. Try to lead shoot by not clicking directly on xeno.
5. Realize you can't because someone fucking made it so you can't click dark tiles.
6. Die.

**Comment by Al-1ce** [comment]
Probably because the tile doesn't have a turf. Whodathunk?

**Comment by Lumipharon** [comment]
Pretty sure this has been reported before, it's been a thing for ages. Restarting your client and/or comp magically fixes it, so god knows what the root cause is.

**Comment by Serxule** [comment]
oh yeah this exists on basically every server, tg actually fixed it i think

**Comment by Lumipharon** [comment]
dup
