### ISSUE TITLE
Default race of human isn't actually selected

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#10784]
### Description

If you're making a new character, and try to customise your spaceman, you can't select any options until you select your race, despite it visually showing as human already.

### Test Merges

NA

### Reproduction Steps

Create new character
Species default to human
Try select a hairstyle etc
Nothing happens
Select human in the race dropdown
Magically works

**Comment by ivanmixo** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/13353
