### ISSUE TITLE
Combat Robots get affected by neuro spits (I guess?)

### ISSUE THREAD

**Issue by DerpiestBruh** [tgstation/TerraGov-Marine-Corps#10795]
### Description

I assume it's been a thing since Robots got added. They're supposed to be not affected by chemicals be it benefitial or not. Yet they still get slowdown on direct hits and probably other debuffs related to it. The stagger icon shows up whenever this happens, I may be wrong and not give anything else than slowdown though.

### Test Merges

[#10669: 'Add a rust pathfinding' by BraveMole at commit 48ce81d35d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10646: 'Combat Patrol Base Remap and Fluff' by tyeagg at commit 9363ed1b8b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10646)
[#10750: 'Projectile performance improvement' by BraveMole at commit baeb9395d6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10750)

### Reproduction Steps

1. Be robot
2. Go groundside
3. Get Neuro Spitted by a Sent/Prae/anything that spits neuro
4. Slowdown

**Comment by Lumipharon** [comment]
Not a bug. Robots are immune to neurotoxin the chemical, not to the spit itself, which is a projectile that causes stagger.

**Comment by BraveMole** [comment]
Not a bug as lumi said. CR should not be stagger issue
