### ISSUE TITLE
Piercing projectiles can hit multiple times (AT Gun oneshots queens)

### ISSUE THREAD

**Issue by collinlunn** [tgstation/TerraGov-Marine-Corps#10791]
### Description

1) If a mob is running in the same direction as a AMMO_PASS_THROUGH_MOVABLE projectile (Railgun, TX8 impact magazine, AT APCR, a few others) that hits them, they can be hit twice. Looks like they are hit once, they move in front of the projectile, then the projectile updates and hits them again. I'm not sure if this happens frequently in practice, but some guns like Railgun can one-hit crit a xeno if they manage to double-hit.
2) Relatedly, the AT gun's APCR ammo has knockback that pushes the hit target further into the projectiles path, so you don't need good timing for it to multi-hit. In fact, you can easily get it to triple hit, for ~600 damage with 40 armor pen, which instantly kills (not crits, kills) most xenos (Including Ancient Queen, Ancient Ravager, Elder Crusher). Since this is a roundstart weapon, I think this is a big issue.

### Test Merges

Tested on master 8/19 (d5b49d2e49bcaae9840024416953181426e166a8)

### Reproduction Steps

For AT gun:
1) Spawn in AT gun (/obj/machinery/deployable/mounted/moveable/atgun)
2) Spawn in APCR ammo (/obj/item/ammo_magazine/standard_atgun/apcr)
3) Spawn a Primordial Queen directly up from the gun
4) Fire the gun well past the xeno
5) See in the logs how it was hit 3 times, instantly killing it

For other guns:
1) Put a xeno on a conveyor belt
2) Fire the piercing gun around the time it the xeno away from you (TX8 impact magazine is easiest since it has a lot of ammo)
3) Note that sometimes chat says you hit the xeno twice (Can't consistently time the shot to make it do it, but I definitely got it to happen multiple times)

**Comment by Lumipharon** [comment]
Pretty sure caused by #10629 
@BraveMole
