### ISSUE TITLE
The AI can't use the FOB drone thing anymore.

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#10803]
### Description

The AI used to be able to use the FOB beacon to build stuff, which is both thematic & useful mechanically, especially on low pop.

Now, when you click on it, nothing happens at all, which is lame, I don't need to explain that.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16119](https://scrubby.melonmesa.com/round/16119)
BYOND Version: 514.1584
Server revision compiled on: 
Master commit: [77e60625d0d5551c1c85686990583ccee46b18f1](https://github.com/tgstation/TerraGov-Marine-Corps//commit/77e60625d0d5551c1c85686990583ccee46b18f1)
The following pull requests are currently test merged:
[#10669: 'Add a rust pathfinding' by BraveMole at commit f12be47650](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10750: 'Projectile performance improvement' by BraveMole at commit baeb9395d6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10750)

Local commit: 04403cb20c63cb0adc2057bef0afb4c62804879e
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Play AI.
Go to FOB drone in the ship.
Click.
Nothing happens.

**Comment by Al-1ce** [comment]
Around two years ago the AI would be given a unique piece of dialogue explaining why they can't interact with the remote-drone. I've never built the FOB as the AI but I'll take a stab in the dark and assume that has something to do with it?

**Comment by RikuTheKiller** [comment]
If #10886 is merged this will be fixed.

(I forgot to add fixes: #issuenumber to the PR...)

**Comment by ivanmixo** [comment]
Just edit in `closes #10803` into the PR body.
