### ISSUE TITLE
cannot change hair styles (and related things)

### ISSUE THREAD

**Issue by Serxule** [tgstation/TerraGov-Marine-Corps#10802]
### Description

no menu appears, cant seem to fix by any means

### Test Merges

[#10750: 'Projectile performance improvement' by BraveMole at commit baeb9395d6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10750)
[#10669: 'Add a rust pathfinding' by BraveMole at commit 48ce81d35d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)

### Reproduction Steps

go to change hair, watch as clicking it does nothing

**Comment by Lumipharon** [comment]
See #10784

**Comment by BraveMole** [comment]
Duplicate
