### ISSUE TITLE
Can't Click On Darkness

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1082]
## Testmerges:

#1063 #827 #958 #1043 #1032 #1046 #1057 #1075 #1068 #814 #1081

## Reproduction:

1) Click on entirely dark tiles. The ones where you can't see anything.
2) Observe how what you're trying to use (whether gun, throwing, middle click ability, etc.) fails at doing the thing it's supposed to do.

**Comment by DominikPanic** [comment]
Depends on #1068 to get merged

**Comment by DominikPanic** [comment]
Fixed in #1100
