### ISSUE TITLE
mosin nagant rail scope has no sprite when unattached

### ISSUE THREAD

**Issue by Serxule** [tgstation/TerraGov-Marine-Corps#10828]
### Description

where is its sprite

### Test Merges

[#10800: 'Hunter Swap control simplification' by collinlunn at commit 89d99fb2b0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10800)
[#10669: 'Add a rust pathfinding' by BraveMole at commit f12be47650](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10804: 'Fix piercing projectile hitting the same atom multiple times' by BraveMole at commit 502fffbd62](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10804)

### Reproduction Steps

get mosin, take off its scope (or replace with other rail thing), see it is invisible

**Comment by This1sPanda** [comment]
I may be retarded, but it seems the little name of the mosin scope in the dmi fille is mosinscope_a, while his item code calls for mosinscope.

Still new to this, but it could be a dumb value call mistake. Just need to do some minor changes.

**Comment by This1sPanda** [comment]
Bug Fixed, issue should be closed.
