### ISSUE TITLE
Wraith's Time Stop is permanently stopping projectiles

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#10839]
### Description

Per title. Projectiles caught by Time Stop while it is active will be permanently stopped, even after the ability expires.

### Test Merges

#10800, #10669, #10804

### Reproduction Steps

1. Use Time Stop.
2. Shoot projectiles.
3. Watch them. They will be permanently stopped even after it expires.
4. Optional: run into them and die!

**Comment by Lumipharon** [comment]
I've seen timestopped used in the last week without this bug occuring, so if it's still an issue it's not happening consistantly.

**Comment by BraveMole** [comment]
Fixed
