### ISSUE TITLE
tac reloading causes ghost item in pockets

### ISSUE THREAD

**Issue by Technical-l** [tgstation/TerraGov-Marine-Corps#10889]
### Description

Was testing out tac reloading in valhalla, put a mag in my pocket and dragged it to my gun. Few minutes later, i try to put a pouch in my pocket and there is an invisible mag in my pocket so i can't put anything in there.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16366](https://scrubby.melonmesa.com/round/16366)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [4c95e300c0751095a71b36f5840c43241a174edc](https://github.com/tgstation/TerraGov-Marine-Corps//commit/4c95e300c0751095a71b36f5840c43241a174edc)
The following pull requests are currently test merged:
[#10669: 'Add a rust pathfinding' by BraveMole at commit 698d21f85d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10793: 'New Map: Gelida IV [MDB ignore]' by RipGrayson at commit 04e02e6c85](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10793)
[#10847: 'Make Tac/Rangefinder binoculars able to link to multiple mortars' by mc-oofert at commit 6e8735c08d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10847)
#10851: 'Improves the  wide flamer nozzle and related refactor' by Lumipharon at commit eef0c85415

Local commit: b6bc9485712867d031f3b19e7fff55cc7326c8e4
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Put magazine in pocket (i was using an mp-19 machinepistol and mag)
2. Drag magazine to empty gun
3. Right click your pocket, you will see the ghost item. You cant put anything into the pockets

### Screenshots

https://youtu.be/MfqU7pZe7Ec

**Comment by BraveMole** [comment]
Is this replicable ? 

We have this ghost item issue popping from time to time, are you sure that what you saw is linked with tacreload?
