### ISSUE TITLE
Tank has crashed DS console and welcome board at lz1, then runner slashed it 4 times then stuck THEN I CANT ANSWER ADMIN TICKET!

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#1089]
## Testmerges:
THEN I CANT ANSWER ADMIN TICKET!

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/54499574-5ed24680-4924-11e9-88ac-bd13d8a0734e.png)

**Comment by Monikawales** [comment]
I press all blue purple link buttons and links does nothing

**Comment by Monikawales** [comment]
Nobody was able to enter tank slot

**Comment by DominikPanic** [comment]
Considering you aren't staff you shouldn't even be able to see that in the first place. You can't interact with it beacuse you don't have permissions.

**Comment by DominikPanic** [comment]
Fixed in #1081
