### ISSUE TITLE
Large open areas indoors have terrible lighting 

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#10908]
### Description

Almost all hangars and large briefing areas have pretty janky lights. 
POS hangar is especially bad in this regard, with large blind spots for the AI, and darkness for everyone there. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16410](https://scrubby.melonmesa.com/round/16410)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [e77a0bb89d18d85edb75e8d9f61a37a879d4108d](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e77a0bb89d18d85edb75e8d9f61a37a879d4108d)
The following pull requests are currently test merged:
[#10849: 'Adds a buffer between a limb's max damage and the brute required to sever' by QualityVan at commit a5132b3221](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10849)
[#10669: 'Add a rust pathfinding' by BraveMole at commit 698d21f85d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10793: 'New Map: Gelida IV [MDB ignore]' by RipGrayson at commit a99f7bfc47](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10793)
[#10847: 'Make Tac/Rangefinder binoculars able to link to multiple mortars' by mc-oofert at commit 6e8735c08d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10847)
#10851: 'Improves the  wide flamer nozzle and related refactor' by Lumipharon at commit eef0c85415
[#10901: 'Kuro2.0 gun sprites' by Xsdew at commit fafb99d1e8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10901)

Local commit: d78c84e497050d812c401b8231d7ad499b50132e
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Go to POS hangar
See that it is plunged in darkness even when everything works fine. 

### Screenshots

![image](https://user-images.githubusercontent.com/24830358/189251426-d9b909d4-3f22-48b2-972f-786eb33ec03b.png)

**Comment by Lumipharon** [comment]
That's an issue with lights not being designed for such large spaces. Would probs jsut need a new child light with a higher radius, specifically for areas like this.

**Comment by Serxule** [comment]
because there's no lights in the middle of landing zones, and there's no lights on the condor

**Comment by Xander3359** [comment]
Resolved by https://github.com/tgstation/TerraGov-Marine-Corps/pull/12152
