### ISSUE TITLE
CAS does not have a clear and easy way to reopen its screen during flight

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#10907]
### Description

CAS needs its fancy screen to be able to do its missions. However, you can close it, by accident or on purpose. 
This leaves you stranded, and it is really janky. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16410](https://scrubby.melonmesa.com/round/16410)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [e77a0bb89d18d85edb75e8d9f61a37a879d4108d](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e77a0bb89d18d85edb75e8d9f61a37a879d4108d)
The following pull requests are currently test merged:
[#10849: 'Adds a buffer between a limb's max damage and the brute required to sever' by QualityVan at commit a5132b3221](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10849)
[#10669: 'Add a rust pathfinding' by BraveMole at commit 698d21f85d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10669)
[#10793: 'New Map: Gelida IV [MDB ignore]' by RipGrayson at commit a99f7bfc47](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10793)
[#10847: 'Make Tac/Rangefinder binoculars able to link to multiple mortars' by mc-oofert at commit 6e8735c08d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10847)
#10851: 'Improves the  wide flamer nozzle and related refactor' by Lumipharon at commit eef0c85415
[#10901: 'Kuro2.0 gun sprites' by Xsdew at commit fafb99d1e8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10901)

Local commit: d78c84e497050d812c401b8231d7ad499b50132e
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Get in CAS
Take off and begin firemission
Close both the menu and the CAS screen. 
Get stuck in limbo till you run out of fuel.

**Comment by Serxule** [comment]
have you checked the top right of the screen where the tabs are to see if there's a condor tab? drop pods have this same exact thing

**Comment by BraveMole** [comment]
That is more of a feature request than a bug
