### ISSUE TITLE
You can't shuffle when moving diagonaly if there's a wall nearby

### ISSUE THREAD

**Issue by Dgeen** [tgstation/TerraGov-Marine-Corps#10916]
### Description

After merg this pr: #9534, marines can bodyblock you, If you try to escape diagonally in a standard garden.

### Test Merges

N/A

### Reproduction Steps

1. Make test wall as in the screenshot
2. Try shuffle diagonally (go down and then right)
3. You can't, marines bodyblock you
4. Delete pr #9534
5. Now you can

### Screenshots

![image](https://user-images.githubusercontent.com/79422708/189487984-350a11d9-f0c8-44a4-a8dd-1cc876c57a37.png)

**Comment by BraveMole** [comment]
Most probably unfixeable with the current move system

**Comment by Dgeen** [comment]
Sad, but understandable.

**Comment by Serxule** [comment]
because you still have to pass by one of the tiles when moving diagonally, not really a bug

**Comment by Dgeen** [comment]
> because you still have to pass by one of the tiles when moving diagonally, not really a bug

You must be able shuffle marines when you in green intent. But you can't, this IS a bug.
