### ISSUE TITLE
Chigusa ingame webmap link not working?

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#10924]
### Description

![image](https://user-images.githubusercontent.com/24830358/189548152-5a021134-9f69-41ba-b9a1-76dd5a8efd04.png)

### Test Merges

Not relevant

### Reproduction Steps

Play chigusa and try to open the webmap

**Comment by Serxule** [comment]
we dont run or own webmap, hence why a lot of the maps are broken at times

**Comment by TiviPlus** [comment]
Actually might be config issue idk

**Comment by ivanmixo** [comment]
Chigusa doesnt exist anymore
