### ISSUE TITLE
APC Auto Mode Is Broken

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1093]
## Reproduction:

1) Find an APC.
2) Disconnect it from the grid, or disable charging. (Not sure if disabling charging works.)
3) Observe how the APC eventually completely shuts down, instead of drawing from the internal cell and gradually shutting things off.
<hr>
This may be due to something else. Will test repro steps later.

**Comment by DominikPanic** [comment]
@Menshin

**Comment by DominikPanic** [comment]
Is this still an issue?

**Comment by DominikPanic** [comment]
Should be alright now
