### ISSUE TITLE
Loadout vendor vends wrong shells in shotguns

### ISSUE THREAD

**Issue by Jalopkomit18** [tgstation/TerraGov-Marine-Corps#10949]
### Description

The loadout vendor will vend shotguns only with buckshot, regardless of the shell type loaded when saving. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16490](https://scrubby.melonmesa.com/round/16490)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [e0eedcf94f4aec6334771bd8ba4548bcd6b44b7e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e0eedcf94f4aec6334771bd8ba4548bcd6b44b7e)
The following pull requests are currently test merged:
[#10793: 'New Map: Gelida IV [MDB ignore]' by RipGrayson at commit a99f7bfc47](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10793)

Local commit: 986c12054baeb20072d0f01e0a808b4fa76bfa5c
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Save loadout with shotgun. Have shells other than buckshot loaded into it
2. Vend loadout. The shotgun will have buckshot loaded regardless of ammo type saved.

**Comment by BraveMole** [comment]
It doesn't save the ammo. This is more a feature request that a bug
