### ISSUE TITLE
Seed vendors don't show seed type

### ISSUE THREAD

**Issue by Dikozda** [tgstation/TerraGov-Marine-Corps#10950]
### Description

When i interact with a seed vendor i see a long list of seed packets, no info on seed type, just seed packets.

oh and one water flower.

also the amount of seed packets don't update unless you take one out from the last one which then lowers all the seed packet amount by 1, also they all show 2 packets available despite the fact they have 3 packets for each seed type.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16490](https://scrubby.melonmesa.com/round/16490)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: e0eedcf94f4aec6334771bd8ba4548bcd6b44b7e
The following pull requests are currently test merged:
#10793: 'New Map: Gelida IV [MDB ignore]' by RipGrayson at commit a99f7bfc47

### Reproduction Steps

go to a seed vendor
click on it
look at the seed packets

**Comment by Derrick2Electricboogaloo** [comment]
Fixed this issue. WAY OLD, but what ever. Something for me to try.
