### ISSUE TITLE
The flamerthrower unlinks itself from the backpack fuel tank even with mag harness

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#10966]
### Description

When using a backpack fuel tank, I didn't expect that my gun would be unlinked every time I fell. 
Especially not when I do not move away from the gun, or use a mag harness. 

Instead, this is precisely what happens, and it makes the weapon & mag harness not so good. I remember this wasn't the case before, so something must be off. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16511](https://scrubby.melonmesa.com/round/16511)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [5005414a4a7e9e08be632c2c017d661030a8e52f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/5005414a4a7e9e08be632c2c017d661030a8e52f)
The following pull requests are currently test merged:
[#10965: 'Attempt at fixing bullet pings' by TiviPlus at commit f417a750e1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10965)
[#10953: 'Hyperscale Guns' by hyper2snyper at commit c302f6b765](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10953)

Local commit: 10b4c8958b27c21608cd897cfb7b59e52842ecf8
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Get flamer
Get mag harness
Link it to backpack fuel tank
Fall down or drop your gun
Realize the gun is no longer linked, despite it never really leaving your reach

**Comment by Lumipharon** [comment]
This is intended behavior, and is part of what balances having a huge amount of ammo in your gun.

**Comment by Lumipharon** [comment]
it was bugged for a bit, but yeah this is definitely intended, it was a balance point in the original pr even.

**Comment by private-tristan** [comment]
> Do you have the PR? I can't find it.

#5612  "Dropping your gun or the fuel tank breaks the link between them, even with magnetic harness or belt harness."
