### ISSUE TITLE
vote window is empty

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#1097]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/54560310-1faefe80-49d3-11e9-8a1c-9d5cdfc86ae6.png)

**Comment by Monikawales** [comment]
After reboot
![image](https://user-images.githubusercontent.com/45321263/54560369-453c0800-49d3-11e9-891f-33aad3cc7d56.png)

**Comment by Monikawales** [comment]
![image](https://user-images.githubusercontent.com/45321263/54560393-54bb5100-49d3-11e9-8500-d741e02c4b08.png)

**Comment by DominikPanic** [comment]
Unable to reproduce, unless you give specific steps this is unlikely to get fixed, as it may be just a local issue.
