### ISSUE TITLE
You can shoot through windows if you are next to them.

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#10976]
### Description

Hugging a window, not the full sized ones, lets you shoot through them

Acid spits work.
RPG's & Airburst grenades work.
HMG works, if you use admin tools to put the glass into place.

Grenade launchers do not work. 
Throwing manually does not work.
Flamethrowers do not work. 

### Test Merges

Irrelevant. 

### Reproduction Steps

Clear enough.  

### Screenshots

![dreamseeker_2022-09-16_02-16-51](https://user-images.githubusercontent.com/24830358/190531930-8cd6148a-68f1-40fe-985c-cf8e297bab4a.gif)
![dreamseeker_2022-09-16_02-21-19](https://user-images.githubusercontent.com/24830358/190531932-ff4e19a8-2444-45fe-b501-2e2d682dff64.gif)
![dreamseeker_2022-09-16_02-29-15](https://user-images.githubusercontent.com/24830358/190531933-42ed7952-b676-4096-9228-2631fe36d055.gif)
![dreamseeker_2022-09-16_02-36-05](https://user-images.githubusercontent.com/24830358/190532018-2ebfe5fc-d30e-40c2-ae71-abfd054170f1.gif)

**Comment by Lumipharon** [comment]
dup
