### ISSUE TITLE
Rail gun / CO consoles 

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#11]
![tgm11252018](https://user-images.githubusercontent.com/45321263/48973716-50031380-f057-11e8-954a-a1febe5a7a61.png)

Edit: Railgun ammo is normal not bug. CO cannot use consoles is a bug.

**Comment by Rohesie** [comment]
Should be fixed once https://github.com/tgstation/TerraGov-Marine-Corps/pull/109 gets merged.
