### ISSUE TITLE
Opening character customization bluescreens setup window

### ISSUE THREAD

**Issue by Edelor68** [tgstation/TerraGov-Marine-Corps#11004]
### Description

When I try to open the character customization while having my first character selected the setup window will instantly bluescreen. Restarting the game doesn't fix it, only a round restart will. This only happens on my first character not my second or any of the others.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16615](https://scrubby.melonmesa.com/round/16615)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [3a094664193ff95c0e12659b05e7cef86f362076](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3a094664193ff95c0e12659b05e7cef86f362076)
The following pull requests are currently test merged:
[#10953: 'Hyperscale Guns' by hyper2snyper at commit c302f6b765](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10953)
[#10610: 'Widow [MDB ignore]' by Zar000 at commit e4cc8fd53f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10610)
[#10891: 'tadpole swagger buff [MDB ignore]' by tyeagg at commit ebc47d3897](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10891)

Local commit: 18a7f99490f24ac204f853506066b968303909b3
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Open the Setup Character window
2. Select the first character
3. Click Character customization

### Screenshots

![TGMCSetupBluescreen](https://user-images.githubusercontent.com/85312201/191027952-41fdfd7c-3616-4953-8ad5-a4ac414b0561.png)

**Comment by Serxule** [comment]
this is generally a clientside issue

**Comment by Edelor68** [comment]
Any ideas on how to fix it?

**Comment by Lumipharon** [comment]
dup
