### ISSUE TITLE
Akimbo Autoburst results in no fire delay.

### ISSUE THREAD

**Issue by Alexeivichi** [tgstation/TerraGov-Marine-Corps#11022]
### Description

While dual wielding, any weapon set to autoburst firemode while applicable allows it to be fired with 0 fire delay. Even when the weapon is dropped and picked up and fired while being solely wielded, it will retain no fire delay on autoburst mode.

Please look into this urgently.

### Test Merges

#10998

### Reproduction Steps

Hold any firearm with autoburst mode - set to autoburst.
Hold secondary firearm in the other hand, regardless of firemode capability.
Any weapon with autoburst in your hand while holding akimbo weaponry automatically has 0 fire delay.
Weapon can now be fired in akimbo with no delay, or fired on its own as it remains on autoburst fire mode.

**Comment by Serxule** [comment]
this works even with guns that require wielding (oh god)
