### ISSUE TITLE
AI can see through camera static sometimes

### ISSUE THREAD

**Issue by Notamaniac** [tgstation/TerraGov-Marine-Corps#11038]
### Description

Usually the AI can't see without a camera. Untill you can for some reason. Can't reproduce reliably.

https://user-images.githubusercontent.com/17688334/191862098-9e63f91d-4a4d-4aad-9237-877f9bb92770.mp4

### Test Merges

[#10610: 'Widow [MDB ignore]' by Zar000 at commit 82f535b701](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10610)
[#10998: 'Lets primordial hunters have stealth as well as disguise (again) but they cant be active at the same time' by iLikeMemes at commit 9ade2e8133](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10998)
[#11011: 'Xenomorphs can pull objects again' by lKiseki at commit 1b3d6d408a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11011)

### Reproduction Steps

1. Jump Z levels via return to AI core/ Use bot/ Use follow hyperlink in chat
2. See through static

**Comment by TiviPlus** [comment]
Known byond issue I think we have an issue on this already
