### ISSUE TITLE
cant shoot, sentrys stop working, cant put out any object from sentry container and tool belt, cant shoot, etc

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#1103]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/54634188-b989b080-4a92-11e9-8ddf-1e6ef2548924.png)

**Comment by Monikawales** [comment]
sentrys became unclickable

**Comment by DominikPanic** [comment]
@Monikawales Please, I beg you, include testmerges in your bug reports

**Comment by Shadow-Quill** [comment]
You can find out current TMs by going into the discord and running the command `!tgs prs`

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1100
