### ISSUE TITLE
SSD Mobs shows wrong names

### ISSUE THREAD

**Issue by Edelor68** [tgstation/TerraGov-Marine-Corps#11049]
### Description

Sometimes when you look for SSD mobs you wont find anyone by that name when you try to orbit them.

### Test Merges

The following pull requests are currently test merged:
[#11011: 'Xenomorphs can pull objects again' by lKiseki at commit 1b3d6d408a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11011)
[#10998: 'Lets primordial hunters have stealth as well as disguise (again) but they cant be active at the same time' by iLikeMemes at commit 9ade2e8133](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10998)
[#10610: 'Widow [MDB ignore]' by Zar000 at commit 82f535b701](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10610)

### Reproduction Steps

1. Go to take SSD Mob
2. Search one of the shown names in the Orbit menu
3. No mobs by that name exist

### Screenshots

![TGMCSSDMobBug](https://user-images.githubusercontent.com/85312201/192109146-99f6bc63-3a29-4ed0-92c1-02f5c0cf54df.png)

**Comment by FIXTHERADBOXPLEASE** [comment]
This happens when they're in cryo I think.
