### ISSUE TITLE
You can't dispense xenonauten armor in valhalla

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#11083]
### Description

Trying to dispense one from the vendor counts it as a banned item. Due to that, loadouts with said armor also don't work.

### Test Merges

[#11031: 'Uses maptext to show what key actions are binded to.' by MLGTASTICa at commit 57a4b8f753](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11031)
[#10998: 'Lets primordial hunters have stealth as well as disguise (again) but they cant be active at the same time' by iLikeMemes at commit 9ade2e8133](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10998)
[#11011: 'Xenomorphs can pull objects again' by lKiseki at commit 1b3d6d408a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11011)

### Reproduction Steps

Go to valhalla
Try

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/192575479-78548d4e-1710-42ba-804d-25644452145a.png)
![image](https://user-images.githubusercontent.com/72712909/192575516-847466a4-4af5-44e4-b1f3-66c4ef7b90b7.png)

**Comment by Nickkoranda** [comment]
Issue with valhalla during Combat Patrol rounds.
