### ISSUE TITLE
Build a sentry rr issue

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#11105]
### Description

The build a sentry attachment can be put on the recoilless rifle however it will not fire (it also reads the ammo as half full when its loaded)

I believe this to be a bug with the RR's code (either its delay in and of itself is to short and causes it to spaz out the semi auto feature on the sentry, OR its how the mag system for launchers work).

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16862](https://scrubby.melonmesa.com/round/16862)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [ffece68946946955f8f3558d9ed769efb7ce8c67](https://github.com/tgstation/TerraGov-Marine-Corps//commit/ffece68946946955f8f3558d9ed769efb7ce8c67)
Server tools version: 5.1.0

### Reproduction Steps

get a RR 
place the build a sentry attachment to it
place a xeno infront of it

**Comment by Lumipharon** [comment]
I'm testing it right now and it works fine for me.

**Comment by isotope436** [comment]
can confirm this isnt actually an issue its just never had a chance to fully prime and fire (however i believe that the heat rockets arent working correct in the RR as they seem to expload when they fire but i could be wrong)

**Comment by isotope436** [comment]
your free to close this it would appear i just never had xenos around it long enough to fully track and prime
