### ISSUE TITLE
Valhalla Build a sentry bug

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#11111]
### Description

i wanted to test out and see what guns i could use for the BSA and found out that they dont work in valhalla (they wont let you access them at all and give you access denied in chat) 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16872](https://scrubby.melonmesa.com/round/16872)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [fd0c8e2705b023a4e1b22feff1b96b8908cce6a1](https://github.com/tgstation/TerraGov-Marine-Corps//commit/fd0c8e2705b023a4e1b22feff1b96b8908cce6a1)
The following pull requests are currently test merged:
[#11044: 'tadpole 3 tile cade all sides' by tyeagg at commit 47fe525df5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11044)
[#11088: 'Game update chat config' by TiviPlus at commit 6cf7950dff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11088)
[#11107: 'Reverts all gun hyyperscale' by TiviPlus at commit 2397c44fc2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11107)

Local commit: f4842f3380ec3cf27cf7ef503c540da2c545ff38
Server tools version: 5.1.1

### Reproduction Steps

place any build a sentry gun well in valhalla (class doesnt matter but engi is the only way you can get them)

### Screenshots

![image](https://user-images.githubusercontent.com/77692311/193312663-0a34a9a2-5f8b-478c-a66e-600196a7caf5.png)
![image](https://user-images.githubusercontent.com/77692311/193312694-74f9464c-abb2-44ff-a383-b666e453b964.png)

**Comment by FosterGrime-Heymynameslouie** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10934#issue-1370639397

this might have something to do with that

**Comment by Derrick2Electricboogaloo** [comment]
Definitely.

**Comment by Derrick2Electricboogaloo** [comment]
Wonder if we have, or could add a valhalla version of it.

**Comment by isotope436** [comment]
after 7 months i would like to let you know this counts for all turrets
