### ISSUE TITLE
The yeetus deletus rocket sledge maneuver 

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#11110]
### Description

If you smash your unprotected head with a rocket sledge it just straight up deletes your body entirely (sometimes it leaves your hands) it also spews out runtimes and causes A-logs to have a stroke.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [16872](https://scrubby.melonmesa.com/round/16872)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [fd0c8e2705b023a4e1b22feff1b96b8908cce6a1](https://github.com/tgstation/TerraGov-Marine-Corps//commit/fd0c8e2705b023a4e1b22feff1b96b8908cce6a1)
The following pull requests are currently test merged:
[#11044: 'tadpole 3 tile cade all sides' by tyeagg at commit 47fe525df5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11044)
[#11088: 'Game update chat config' by TiviPlus at commit 6cf7950dff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11088)
[#11107: 'Reverts all gun hyyperscale' by TiviPlus at commit 2397c44fc2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11107)

Local commit: f4842f3380ec3cf27cf7ef503c540da2c545ff38
Server tools version: 5.1.1

### Reproduction Steps

grab rocket sledge 
apply directly to unsecured face

### Screenshots

![image](https://user-images.githubusercontent.com/77692311/193309020-4b7485e6-cbeb-402b-be04-1fd7769220ae.png)

**Comment by Losenis** [comment]
If you're testing it on valhalla, it deletes your body on death and ghosting

**Comment by isotope436** [comment]
can confirm its a valhalla thing that deletes the body but according to a staff member who was with me it still spams runtimes and alogs
