### ISSUE TITLE
LV Tunnels don't transport from A to B.

### ISSUE THREAD

**Issue by Alibouk1** [tgstation/TerraGov-Marine-Corps#1112]
![scrnshot1](https://user-images.githubusercontent.com/48772272/54715963-f1592c80-4b54-11e9-8c5b-5cfd9280dc53.png)

**Comment by DominikPanic** [comment]
For anyone looking into this: tunnels do link up, but it seems like the tunnel gets either deleted while the loc remains or the loc gets set wrongfully

**Comment by DominikPanic** [comment]
Is this still an issue?
