### ISSUE TITLE
Advanced hypos won't accept pills while held

### ISSUE THREAD

**Issue by Anonmare** [tgstation/TerraGov-Marine-Corps#1114]
## Testmerges:
#1100: 'Click refactor.' by DominikPanic at commit 92bb7aeeae 
#1043: '[EXPERIMENTAL]Moves chat processing into a subsystem.' by DominikPanic at commit 6dc554a93a 
#1081: 'Admin Tweaks' by DominikPanic at commit 1215b3ca0c 
#1079: 'Minigun ammo swap' by InterroLouis at commit b3e6228483 
#1033: 'Tank Rebalance' by Surrealaser at commit f9aa761f7c 
#1094: 'Fixes firedoors acting like boder_only.' by Rohesie at commit b3b2eb7a92 
#1071: 'Sniper Kit Buffs' by Surrealaser at commit 025e894c27 
#931: 'New Boiler Ability: Emit Acid' by Surrealaser at commit bf316176dd 
#1032: 'Ravager Balance Tweaks' by Surrealaser at commit 1899cbcc6a 
#1057: 'Adjusting some facehugger quirkiness.' by Ghommie at commit 714d9612d9 
#827: 'Reduces message spam and hopefully lag.' by DominikPanic at commit 78d192c828 
#1107: 'Fixes initial damages not being applied on flamer_fire instanciation' by Menshin at commit f6435a0199 

## Reproduction:
Hold an advanced hypospray and attempting to put a pill in it will do nothing. Placing the hypo on the ground will have it function normally.

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1100
