### ISSUE TITLE
Tank Bug

### ISSUE THREAD

**Issue by WolfyPT** [tgstation/TerraGov-Marine-Corps#1116]
Reproduction:

I was stripping the damaged armor off the tank, it wasent broken, just damaged, i was experimenting to see if you could weld the tank and reattach the armor to see if it fixed it or not, when i tried to pick up the caustic armor it wouldnt work, i could only drag and then 1 minute later after i dragued it it just literally went poof and despawned.

**Comment by DominikPanic** [comment]
@Ghommie finish your PR reeee
