### ISSUE TITLE
Sniper Laser Targeting Issue

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#1119]
## Testmerges:

https://gyazo.com/bfa88e192fa864429762ac564501b554

## Reproduction:

Right, so, I'm not sure what caused this at all. Basically, I went to grab a marine with control click, and instead of grabbing them I started to lase. Found that wherever I control clicked, I simply lased. The thing is, the rifle was not in my hand, it was in my suit storage. I had previously been firing at a laser marked xenomorph-and may have put my gun into my suit storage straightaway rather than lowering it and then putting it away. It's possible that may have caused the CAS laser to be active until the next time I took my rifle out, because shortly after I did that, it was functioning normally once more. The map for the round was Ice Colony.

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1100
