### ISSUE TITLE
Fumbling robotic limb blowtorch repair

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#11192]
### Description

You need two progress bars to actually repair a robotic limb that has brute damage with blowtorch. The first one will do nothing, the second will actually repair. Problem is there's no question mark icon over your mob to indicate it's an actual intended fumble, and given you don't fumble wire repair it smells like a bug.

### Test Merges

idk server is down atm

### Reproduction Steps

Be human
Knife your arm off
Get it replaced with a robotic limb
Accrue brute damage on it
Use blowtorch on it
Notice that the first repair progress bar does nothing, not even a log on chat. It's only the second that does anything.

**Comment by helper-2** [comment]
It's not a bug, it's the "balance" feature. I don't understand why. Maybe coders thought it was op to repair yourself for a half minute and so they double the time for it

**Comment by Losenis** [comment]
Even synth skills cause fumbling on this, pretty sure it's a bug
