### ISSUE TITLE
Clicking on certain open storages doesn't place items inside them.

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#1120]
## Testmerges:

#1111 #1109 #1091 #1100 #1081 #1033 #1107 #982

## Reproduction:

Happens for example with boxes (such as the admin thunderdome box of cuffs) or surgery tools in any OR. You can place them with E or clicking in the box icon, but if you open it and click on the screen storage object it won't do anything.

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1100
