### ISSUE TITLE
MG42 invisible

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#11217]
### Description

yes

### Test Merges

idk

### Reproduction Steps

firmly grasp it

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/195403837-f23d8191-72c3-4079-9f37-373abddb4edc.png)

**Comment by Derrick2Electricboogaloo** [comment]
FIRMLY GRASP IT!

**Comment by Lumipharon** [comment]
Fixed by #11353
