### ISSUE TITLE
There is no beer 

### ISSUE THREAD

**Issue by Edelor68** [tgstation/TerraGov-Marine-Corps#11244]
### Description

You can not dispense beer from the booze dispenser. Tried with multiple people and multiple different dispensers.
Every other beverage works as normal, just beer wont work for some reason

### Test Merges

[logs/sybil/server_side_modifications.dm](https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm)

Round ID: [17191](https://scrubby.melonmesa.com/round/17191)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [3bb051ba922305abb667b07f59e39b5e379de56f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3bb051ba922305abb667b07f59e39b5e379de56f)
The following pull requests are currently test merged:
[#11056: 'Intro Sequence Or Something Idk What To Call It' by tyeagg at commit b06ecc9b13](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11056)
[#11117: 'Investigation for the crashes. DO NOT MERGE!' by hyper2snyper at commit c069b98506](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11117)

Local commit: 82be73307205f3692e8657c7c0651ae6bc1f3476
Server tools version: 5.2.2
[Common (Mar)] LCPL Kanata

### Reproduction Steps

1. Go to booze dispenser
2. Click on beer
3. Nothing happens

**Comment by helper-2** [comment]
Literally unplayable.
