### ISSUE TITLE
Show Hive Status as a ghost missing burrowed

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1125]
## Reproduction:

1) Be dead/ghost.
2) Click "Show hive status"
3) Observe how there is no "Burrowed Larvae" count, even with an alive queen.

**Comment by DominikPanic** [comment]
@spookydonut

**Comment by Rohesie** [comment]
This has always been like this since the start of the verb implementation, but it would be a nice addition.

**Comment by DominikPanic** [comment]
No longer an issue
