### ISSUE TITLE
No/wrong groundside webmap for Orion Military Outpost

### ISSUE THREAD

**Issue by Edelor68** [tgstation/TerraGov-Marine-Corps#11254]
### Description

When you try to open the webmap for Orion Military Outpost you get rerouted to this website:
https://affectedarc07.co.uk/tgmc.php?m=orionoutpost.dmm
WHich just gives you an error message

### Test Merges

Not relevant

### Reproduction Steps

1. Be on Orion Military Outpost
2. Try to open the webmap through the game

**Comment by Serxule** [comment]
we dont run the webmap, thats a them problem
