### ISSUE TITLE
librust_g.so causing crashes and runtimes

### ISSUE THREAD

**Issue by XElectricX** [tgstation/TerraGov-Marine-Corps#11288]
### Description

Server should be running without problems. Crashes on start if using the repo-provided file, causes runtimes if using my own compiled file. This is all happening on the master branch too.

### Test Merges

It's on local, there are no TMs.

### Reproduction Steps

1. Host using Linux (I use Debian 11)
2. Crash when starting.

Or:

2. Compile a new librust_g.so
4. Use that one for the server, start Daemon
5. See runtimes in multiple pathfinding-related procs

### Screenshots

One of the runtimes when using my own compiled file:
```
Initialized Advanced_pathfinding subsystem within 0 seconds!
[00:03:51] Runtime in advanced_pathfinding.dm,15: ./librust_g.so: undefined symbol: register_nodes_astar
  proc name: Initialize (/datum/controller/subsystem/advanced_pathfinding/Initialize)
  src: Advanced_pathfinding (/datum/controller/subsystem/advanced_pathfinding)
  call stack:
  Advanced_pathfinding (/datum/controller/subsystem/advanced_pathfinding): Initialize(2314)
  Master (/datum/controller/master): Initialize(10, 0, 1)
```
When using the one in the repo:
```
Welcome BYOND! (5.0 Public Version 514.1585)
BUG: Crashing due to an illegal operation!
proc name: log world (/proc/log_world)
  source file: _logging.dm,204
  usr: (src)
  src: null
  call stack:
log world("531 global variables")
Global Variables (/datum/controller/global_vars): New()
Master (/datum/controller/master): New()
world: ()
Segmentation fault
```

**Comment by BraveMole** [comment]
Readme added
