### ISSUE TITLE
Hivemind is now slain when ship is invaded

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/TerraGov-Marine-Corps#11286]
### Description

Hivemind now gets slain when the ship takes off for hijack

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [17278](https://scrubby.melonmesa.com/round/17278)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [35d91d65c70e178a0573266fc54ab1d8d286bcf7](https://github.com/tgstation/TerraGov-Marine-Corps//commit/35d91d65c70e178a0573266fc54ab1d8d286bcf7)
The following pull requests are currently test merged:
[#11031: 'Uses maptext to show what key actions are binded to. Reworks action handling' by MLGTASTICa at commit 1f4cdc606f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11031)
[#11189: 'makes mounted guns easy to use' by tyeagg at commit eecfe4421f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11189)

Local commit: eab27903d70383cce7ec372016cd9398eab809b1
Server tools version: 5.2.2

### Reproduction Steps

1. Be hivemind
2. Be on ship 
3. ship takes off
4. die because your core now gets deleted

**Comment by TheWiznard** [comment]
probably because #11050 now hivemind core is structure?

**Comment by FosterGrime-Heymynameslouie** [comment]
I believe you have to be on the ship as it takes off, otherwise you get obliterated

**Comment by QualityVan** [comment]
Fixed by #11398
