### ISSUE TITLE
Hivemind is incapable of walking through or on fire

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/TerraGov-Marine-Corps#11287]
### Description

Hivemind cannot move through any sort of fire at all, weeds or no weeds.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [17278](https://scrubby.melonmesa.com/round/17278)
BYOND Version: 514.1585
Server revision compiled on: 
Master commit: [35d91d65c70e178a0573266fc54ab1d8d286bcf7](https://github.com/tgstation/TerraGov-Marine-Corps//commit/35d91d65c70e178a0573266fc54ab1d8d286bcf7)
The following pull requests are currently test merged:
[#11031: 'Uses maptext to show what key actions are binded to. Reworks action handling' by MLGTASTICa at commit 1f4cdc606f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11031)
[#11189: 'makes mounted guns easy to use' by tyeagg at commit eecfe4421f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11189)

Local commit: eab27903d70383cce7ec372016cd9398eab809b1
Server tools version: 5.2.2

### Reproduction Steps

1. Be hivemind, manifested
2. attempt to move through any of the 900 options of fire creation
3. be stuck unable to move at all

**Comment by BraveMole** [comment]
Feature
