### ISSUE TITLE
Hunter mirage is badly broken.

### ISSUE THREAD

**Issue by FIXTHERADBOXPLEASE** [tgstation/TerraGov-Marine-Corps#11322]
### Description

Whole point of the ability was that it'd spawn fake copies of yourself that ran after the marines to distract them.
Now for some reason they stick to you like glue, accomplishing nothing of value besides telling the marines where to shoot.
Also fucks up the swap ability since there's no reason swapping with a copy 1 tile away from you.

### Test Merges

Irrelevant.

### Reproduction Steps

1. Use mirage.
2. See that, instead of running after any marines within your screen, your copies just stay 1 tile near you at all times.
3. Optionally use swap.
4. Realize that swap has no reason to exist, because why would you need to swap 1 tile away from yourself.

**Comment by Zar000** [comment]
The original behavior was somewhat of a bug that my PR fixed.  ( #10610 ) 

I believe that they still do chase marines if your intent is on help though.

**Comment by ivanmixo** [comment]
Probably fixed now with the recent prs
