### ISSUE TITLE
Sprite offset

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/TerraGov-Marine-Corps#1138]
![tgmc offset xenos sprite](https://user-images.githubusercontent.com/11809482/54887702-005e1880-4e8e-11e9-8d8b-b3cda8175664.png)
As is hopefully visible in the image, my runner sprite wound up offset downward for some reason. I last recall seeing it being fine before I got onto the shuttle to the Theseus with all the other xenos.

## Testmerges:
#827 #1100 #1129 #1130 #1131 #1134 #1132 #1128 #1109 #1104 #1091 #1046 #1033 #952
## Reproduction:
Not sure how to reproduce.

**Comment by DominikPanic** [comment]
@Alterist

**Comment by Rohesie** [comment]
This looks like an old and no longer present bug, probably from a TM. Re-open if it happens again.
