### ISSUE TITLE
Cells of research pens inaccessible

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/TerraGov-Marine-Corps#1139]
## Testmerges:
#952 #1033 #1046 #1091 #1104 #1109 #1128 #1132 #1134 #1131 #1130 #1129 #1100 #827

## Reproduction:
Click on research remote control console, no window pops up. The containment cells themselves are otherwise inaccessible.

**Comment by DominikPanic** [comment]
@Alterist
