### ISSUE TITLE
Shotgun being able to go into Glove and Eye Slot

### ISSUE THREAD

**Issue by David-Stormwell-TGCM** [tgstation/TerraGov-Marine-Corps#1148]
### Reproduction:

If you get a Double Barrel Shotgun, You can Put it into a glove slot If you dont have Gloves already, And If You have A Mk221 Tactical Shotgun you can also put it in your Eye slot.

This can Lead into the abuse of Having More guns then you should on yourself.

![eye shottys](https://user-images.githubusercontent.com/48974113/55047502-e9940d80-50a9-11e9-8856-a3cccc43dd8d.PNG)

**Comment by Ghommie** [comment]
Testmerge issue with #1136. Will be fixed.
~~"I have special eyes 2: The Vendetta."~~

**Comment by Metroidlover** [comment]
Should be fixed now
