### ISSUE TITLE
Round:17761 Invincible Synth brains   Synths loose xeno tounge upon Decap 

### ISSUE THREAD

**Issue by ro3ger** [tgstation/TerraGov-Marine-Corps#11504]
### Description

First starting off with synths loosing Xeno tongue where you can find on round:17761  I made a Ahelp requesting that my xeno tounge be given back to me as I was a decapitated synthetic

2nd: https://youtu.be/9u5V5L_kWwo Same round just durring EORG 

My Byond username:Ro3ger
IC name: Adam
IC Role: Synth
Helping admin Byond key: Soulstolen

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [17762](https://scrubby.melonmesa.com/round/17762)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [b504c46486bccd82884901a364335c5a5f3a55a0](https://github.com/tgstation/TerraGov-Marine-Corps//commit/b504c46486bccd82884901a364335c5a5f3a55a0)
The following pull requests are currently test merged:
[#11381: 'Adds TGMC pack boxes' by Pariah919 at commit 4241d64a27](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11381)
[#11451: 'TGUI update' by SplinterGP at commit 91d65594be](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11451)
[#11447: 'Marine masks no longer protect against ash/sandstorms' by Sunsidec at commit 33991671ad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11447)

Local commit: 2f58c5947e146e1bc96d9f846a2f0648e3b197a2
Server tools version: 5.2.3

### Reproduction Steps

Get decapitated as a synthetic and attempt to talk in xeno tounge

Start EORG as a decapitated synthetic

### Screenshots

https://www.youtube.com/watch?v=9u5V5L_kWwo

**Comment by FIXTHERADBOXPLEASE** [comment]
Yeah I've noticed synths lose their languages when you get decapped too.
