### ISSUE TITLE
Some computers cannot be fixed despite saying they can be

### ISSUE THREAD

**Issue by Gevbon-Drooks** [tgstation/TerraGov-Marine-Corps#11524]
### Description

Supply drop console says it needs a full rebuild—cannot rebuild it.

### Test Merges

bug has existed for a while

### Reproduction Steps

1. someone blows up supply drop computer
2. try to fix
3. cannot fix
4. cry

**Comment by Derrick2Electricboogaloo** [comment]
Should be easy to address. I will start looking into.

**Comment by Derrick2Electricboogaloo** [comment]
Issue resolved. Going to make a PR soon.
