### ISSUE TITLE
aimbot bug that every ranged attack can use

### ISSUE THREAD

**Issue by Zerdon13** [tgstation/TerraGov-Marine-Corps#11528]
### Description

For a long time there has been a way to aimbot with every ranged attack, as in every marine weapon and every ranged xeno attack.

### Test Merges

The following pull requests are currently test merged:
[#11451: 'TGUI update' by SplinterGP at commit 4ab6216a07](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11451)
[#11447: 'Marine masks no longer protect against ash/sandstorms' by Sunsidec at commit 33991671ad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11447)
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 5bea043bfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
(Local commit: 7e31872b3d68db94ed0cbaa0e71fd90ea0dd57b4
Server tools version: 5.2.3)

i mean here it is from today, but its been here for like 6 months 

### Reproduction Steps

1. Pick a ranged ability and or any ranged marine weapon
2. hold right click on target sprite and drag mouse cursor to the right window area (chat area/info/action pannel/ whatever it is called)
3. place mouse cursor back on the "screen" while still holding right click down
4. you now have off screen aimbot lockon on whatever you  chose to hold right click on
5. Profit??? you filfy cheater

**Comment by Zerdon13** [comment]
updated my client and can no longer been able to to it per 25-11-22

**Comment by Lumipharon** [comment]
dup
