### ISSUE TITLE
Rollerbed abuse via going through a window

### ISSUE THREAD

**Issue by Ruediger4** [tgstation/TerraGov-Marine-Corps#11533]
### Description

Was shown this by a player while I was testing shit in thunderdome:
You can alt click a window tile, then click the floor tile with a rollerbed to place the bed in the window's tile. Afterwards, you need help from a friend to grab you and click you onto the bed (it will move you to the bed tile, **_ESSENTIALLY INTO THE WINDOW_**), and from there you can just. Walk past it.

This includes unbreakable windows.

### Test Merges

The following pull requests are currently test merged:
[#11451: 'TGUI update' by SplinterGP at commit 4ab6216a07](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11451)
[#11447: 'Marine masks no longer protect against ash/sandstorms' by Sunsidec at commit 33991671ad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11447)
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 5bea043bfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)

### Reproduction Steps

1. Get a rollerbed
2. find window which you wanna trespass
3. alt-click the window tile so it shows the floor tile on the top-right corner of your game
4. click that floor tile with your rollerbed in hand
5. have a buddy grab you, then click the rollerbed so they put you on it
6. congratulations, you trespassed

### Screenshots

https://cdn.discordapp.com/attachments/978348083597410354/1041056329671909518/image.png
https://cdn.discordapp.com/attachments/978348083597410354/1041056420084338738/image.png
https://cdn.discordapp.com/attachments/978348083597410354/1041056523369062400/image.png

**Comment by Losenis** [comment]
funny
![image](https://user-images.githubusercontent.com/72712909/201496581-c825adfc-a066-4a2c-824b-d08d219e5bf1.png)

**Comment by GravitronBlue** [comment]
This works on more than just widows, generally any tile with a normal floor supports this techinque.
So it's possible to rollerbed clip past certain doors and prep shutters.

Still looking to find a way to perform a bypass technique like this that can be done solo.

**Comment by Oscari-pog** [comment]
breaking into thunderdome while rue is fucking around with SoM guns
![igor](https://user-images.githubusercontent.com/70425197/201514355-72982f60-1234-4789-8110-5c54a3511744.png)
