### ISSUE TITLE
TGUI update is preventing admins from playing music via the Play-Internet-Sound verb

### ISSUE THREAD

**Issue by Andromalis** [tgstation/TerraGov-Marine-Corps#11544]
### Description

The newest TGUI update (with the updated window timers and dynamic window loading feature) has prevented me from playing any music ingame since it has been introduced.

### Test Merges

Round ID: [17838](https://scrubby.melonmesa.com/round/17838)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [55eed239935cf231b48d496837514d77bbcfe6f9](https://github.com/tgstation/TerraGov-Marine-Corps//commit/55eed239935cf231b48d496837514d77bbcfe6f9)
The following pull requests are currently test merged:
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 5bea043bfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
[#11489: 'Scatter increase per shot mechanics.' by SplinterGP at commit 849ed23da1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11489)

Local commit: 49e8b4fbf03d6320c5c0c93c8be254829510ffc9
Server tools version: 5.2.3

### Reproduction Steps

1. Use the Play-Internet-Sound verb
2. Paste random music URL that the verb accepts (it usually accepts YouTube links)
3. Proceed to not be able to play the music at all

**Comment by MiniMeatwad** [comment]
Try again.

**Comment by Andromalis** [comment]
> Try again.

Still doesn't work. I tried playing several different pieces.

**Comment by SilencedMP5A5** [comment]
fix this i beg of thee
