### ISSUE TITLE
BR-8 scout rifle impact rounds are misleading or broken

### ISSUE THREAD

**Issue by Oscari-pog** [tgstation/TerraGov-Marine-Corps#11541]
### Description

BR-8 scout rifle impact rounds are intended to briefly stun target, like slugs. Instead, they dont do that, and deal LESS damage than the regular rounds, which are way cheaper than the impacts.

Seeing as a stun on the scout rifle could be a bit too much, perhaps giving them a different upside could be in order? They are just useless right now, no niche and are outright inferior.

### Test Merges

The following pull requests are currently test merged:
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 5bea043bfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
[#11489: 'Scatter increase per shot mechanics.' by SplinterGP at commit 849ed23da1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11489)

### Reproduction Steps

1. Get BR-8 scout rifle
2. Oh whoa these rounds are labelled "impact" so they must do something cool right????
3. Try them, realize they deal less damage than the regular, cheaper rounds
4. Waaaaah

**Comment by Lumipharon** [comment]
They don't stun. They apply slowdown, have 50% better AP, and pierce mobs, so you can hit multiple mobs if lined up.

**Comment by Oscari-pog** [comment]
> They don't stun. They apply slowdown, have 50% better AP, and pierce mobs, so you can hit multiple mobs if lined up.

The (extremely outdated) wiki says that they stun so bleh.
