### ISSUE TITLE
Bipod sets scatter to 10

### ISSUE THREAD

**Issue by nalleinz** [tgstation/TerraGov-Marine-Corps#11552]
### Description

Firing a weapon with a bipod deployed will set scatter angle to 10 once it is undeployed no matter what the original value is, scatter angle stays at 10 after bipod attachment is removed.

If bipod is deployed and then undeployed without firing, weapon scatter value stays normal.

Tested with the AR12, AR18, MG42, MG60, DMR. 
Deployable guns not affected, tested on MG27

Bug happens in all fire mode.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [17851](https://scrubby.melonmesa.com/round/17851)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [55eed239935cf231b48d496837514d77bbcfe6f9](https://github.com/tgstation/TerraGov-Marine-Corps//commit/55eed239935cf231b48d496837514d77bbcfe6f9)
The following pull requests are currently test merged:
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 5bea043bfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
[#11489: 'Scatter increase per shot mechanics.' by SplinterGP at commit 849ed23da1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11489)

Local commit: 49e8b4fbf03d6320c5c0c93c8be254829510ffc9
Server tools version: 5.2.3

### Reproduction Steps

1. Attach any gun with bipod
2. Deploy bipod
3. Fire the gun
4. Un-deploy the gun
5. Gun scatter angle is now set to 10

### Screenshots

![AR12 Base](https://user-images.githubusercontent.com/118119239/201556671-1e492796-4358-47db-bc9b-ac64d9dded04.jpg)
1.AR12 base stats with no attachment, for reference

![AR12 Bipod undeployed, before shooting](https://user-images.githubusercontent.com/118119239/201556705-0c6aa534-7724-4e87-aac5-dac5db80640d.jpg)
2.AR12 with bipod, not deployed, before shooting

![AR12 Bipod deployed, before shooting](https://user-images.githubusercontent.com/118119239/201556732-2de1de6f-eb26-468e-8684-4a1e53622045.jpg)
3.AR12 with bipod, deployed, before shooting

![AR12 Bipod deployed, after shooting](https://user-images.githubusercontent.com/118119239/201556762-e7ad4bb1-ace2-4dc1-8b39-8e04887dcea0.jpg)
4.AR12 with bipod, deployed, after shooting. Scatter angle value goes missing but weapon shoots with no scatter.

![AR12 Bipod undeployed, after shooting](https://user-images.githubusercontent.com/118119239/201556811-68b92f11-bab7-4fb8-a39c-fe57120e943f.jpg)
5.AR12 with bipod, undeployed, after shooting. Scatter angle value is permanently 10, weapon scatter is all over the place.
_Deploying the bipod again turns gun stat to screenshot 4_

![AR12 with bipod removed after bug](https://user-images.githubusercontent.com/118119239/201557101-1238713c-cfb6-4f07-87ba-d5260a951e27.jpg)
6.AR12 after taking off bipod, after bug happens.

**Comment by Lumipharon** [comment]
I can't reproduce this, it's behaving normally for me?

**Comment by QualityVan** [comment]
Testmerge bug, fixed before merging.
