### ISSUE TITLE
Teleporters aren't saved in loadouts

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#11551]
### Description

If you have a loadout with a dispenser and teleporters inside it, the dispensers wont be bought. You'll have to manually purchase the dispensers with the 25 points that were not spent.

### Test Merges

[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 5bea043bfd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
[#11489: 'Scatter increase per shot mechanics.' by SplinterGP at commit 849ed23da1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11489)

### Reproduction Steps

Make engi loadout with dispenser and teleporters in it
Try to get loadout
Everything but the teleporters is bought

**Comment by Lumipharon** [comment]
It probably won't be fixed. When you buy teleporters, you're actually buying an object that spawns the paired teleporters then deletes itself, so teleporters aren't directly available from any vendor.

**Comment by Serxule** [comment]
quite a few engi items are bugged like this too

**Comment by lbnesquik** [comment]
I guess we could have a variable that's called Loadout_item, which points to a reference item, for this sort of thing.

**Comment by Xander3359** [comment]
(Closed because teleporters are no longer vendable as of https://github.com/tgstation/TerraGov-Marine-Corps/pull/12128 )
