### ISSUE TITLE
M4A3 incendiary magazine codex entry wrong

### ISSUE THREAD

**Issue by KwinOriginal** [tgstation/TerraGov-Marine-Corps#1156]
Hey lads. I just examined a M4A3 incendiary magazine and looked at the codes. It statet the text for a reinforced table ("You can climb on it, it is deconstrucable, it's currently wrenched into place"), one might want to fix those lines.

Cheers!

**Comment by DominikPanic** [comment]
@Hughgent

**Comment by Hughgent** [comment]
Unable to reproduce, magazines in general do not have specific or automatically generated codex entries.

![image](https://user-images.githubusercontent.com/45076386/55187264-84eab880-5166-11e9-9b14-db05db93aafa.png)

there is potential that the person was looking at something like above and assumed that the codex entry there was for the magazine below it.

**Comment by KwinOriginal** [comment]
That's odd, it was on the floor right between Alamo and the Medbay, so there was definitely no table present. But since that's not that big of an issue, it might've been a one-timer (if that's even possible).
