### ISSUE TITLE
Orbit menu doesn't show anything

### ISSUE THREAD

**Issue by Panzerkampfwaggen** [tgstation/TerraGov-Marine-Corps#11565]
### Description

Title

### Test Merges

The following pull requests are currently test merged:
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 1fea547ad0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
[#11489: 'Scatter increase per shot mechanics.' by SplinterGP at commit 849ed23da1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11489)
[#11546: 'Fatty Rework 2.0 (Cluster strikes back!)' by KacperRaid at commit f69dc85c37](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11546)

### Reproduction Steps

just click on follow in the ghost tab

### Screenshots

![Screenshot 2022-11-17 090829](https://user-images.githubusercontent.com/98385549/202329266-67c696e7-0576-49a7-a051-b9883029859a.png)

**Comment by Lumipharon** [comment]
Was only one round
