### ISSUE TITLE
Bug With Grenade Casing

### ISSUE THREAD

**Issue by Gureboy** [tgstation/TerraGov-Marine-Corps#1157]
The Sprite of the grenade casing is unpickable, or unexistant, like it happened before with the Blowtorch and Wirecutters

**Comment by Hughgent** [comment]
current master - Still broken.

cannot interact with the grenade casing unless it's via right click menu. 

no pickup, no examine, can't click it with igniters/beakers/anything. You can place the item into an open inventory slot by clicking the open inventory slot/storage item. You can place the grenade casing onto tables (provided you picked it up via the Rclick menu).

you also cannot interact (via clicking) with completed spawned grenades. This includes the metal foam grenades and cleaner grenades that sometimes spawn on maps. However, if you pick one up (again with the Rclick menu), you can still activate/prime the grenade and throw it via the activate held object verb.

no runtimes when interacting with the grenade casing.
