### ISSUE TITLE
TGS SULACO cannot change orbit

### ISSUE THREAD

**Issue by Araulius** [tgstation/TerraGov-Marine-Corps#11578]
### Description

I got generators running, apc is powered, all the SMES are fully charged. I still cannot change orbit.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [17955](https://scrubby.melonmesa.com/round/17955)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [979775c7745a6b00b6bcde3764915a076bc699af](https://github.com/tgstation/TerraGov-Marine-Corps//commit/979775c7745a6b00b6bcde3764915a076bc699af)
The following pull requests are currently test merged:
[#11475: 'Magmoor Digsite IV Rework | Justice for the Lavaplanet™' by Overdrive659 at commit 1fea547ad0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11475)
[#11489: 'Scatter increase per shot mechanics.' by SplinterGP at commit 849ed23da1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11489)
[#11546: 'Fatty Rework 2.0 (Cluster strikes back!)' by KacperRaid at commit f69dc85c37](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11546)

Local commit: 90f1b448029c650bf4a9f2b5c1903103c79b4679
Server tools version: 5.2.3

### Reproduction Steps

run tgs sulaco, power up ship, attempt to change orbit, get told "not enough power"

### Screenshots

![image](https://user-images.githubusercontent.com/36761380/202889983-67786812-7565-479e-82af-5f3dab55152f.png)
![image](https://user-images.githubusercontent.com/36761380/202890021-39befda2-628f-4935-83cd-8bc7e6606bd3.png)

**Comment by lbnesquik** [comment]
Output is what matters, it doesn't draw directly from the SMES. To be checked with full SMES output.

**Comment by lbnesquik** [comment]
I changed orbit today. I think there is no bug currently, just unclear instructions. The text could be changed to 'power in the grid' or something, to make it clearer.

**Comment by Derrick2Electricboogaloo** [comment]
Yes it can, someone did not set up output correctly. I assure you you can change orbit.

**Comment by Derrick2Electricboogaloo** [comment]
Set output to 200K each not 50K that is so low. Sulaco has a lot of engines.

**Comment by Araulius** [comment]
> Yes it can, someone did not set up output correctly. I assure you you can change orbit.

do you know what power reserves means? It does not mean output, I will tell you that righ tnow.
