### ISSUE TITLE
Shrike: gravity grenade does not work correctly

### ISSUE THREAD

**Issue by lorianss** [tgstation/TerraGov-Marine-Corps#11603]
### Description

I expected the grenade to attract 5 tiles wherever the object is, but if the target is in the east/north, it will attract only 1 tile (goggle translate)

### Test Merges

On the local server

### Reproduction Steps

1. Throw gravity grenade
2. Stand in the east/north next to the grenade

### Screenshots

https://user-images.githubusercontent.com/99790528/203303758-6e34ba9a-d87f-4046-b8dc-5c5dd8009d84.mp4

**Comment by coldironwarrior** [comment]
closed by #13123
