### ISSUE TITLE
Hunter mirages seem to have widow spiderling ai and makes it nearly impossible to use hunter swap.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#11657]
### Description

Try to use mirage on a person so I can swap to them once my plasma is back. Watch as my mirages suddenly snap towards me like a rocket.

On top of this, swap always picks the closest mirage, so even if some of the mirages stick to a marine, you better hope one of them doesn't stick to you like a tick.

### Test Merges

doesn't matter, none of the tms touch mirage behaviour 

### Reproduction Steps

1. Use mirage
2. Move away
3. Watch as all your mirages move close to you
4. Be unable to utilize swap properly.

### Screenshots

https://user-images.githubusercontent.com/24631139/204964741-36ceda57-b912-4552-9774-fd8e1369988f.mp4

https://user-images.githubusercontent.com/24631139/204964745-539ff194-3189-4c5d-b35c-9fdf04166924.mp4

**Comment by Al-1ce** [comment]
Hunter mirage AI acts differently depending on your intent. This is not a bug.

**Comment by FIXTHERADBOXPLEASE** [comment]
> Hunter mirage AI acts differently depending on your intent. This is not a bug.

It does, however, make mirage completely useless.

**Comment by 2whatever2** [comment]
The ai is terrible, even while on help intent, but yeah this isn't a bug which sucks.
