### ISSUE TITLE
The changelog is broken.

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#11666]
### Description

The dev changelog is broken, and doesn't seem to update anymore.
Last update seems to have been the 22 october. 

I don't know if the changelog is handled by our codebase, but it isn't up to date.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [18168](https://scrubby.melonmesa.com/round/18168)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [d8f2f636e05c828c050eb71657dfe624179bd8b4](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d8f2f636e05c828c050eb71657dfe624179bd8b4)
The following pull requests are currently test merged:
[#11573: 'Warlock - new xeno caste' by Lumipharon at commit ecfb06915f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11573)
[#11576: 'Unique Flaregun Flare' by Pariah919 at commit 3725696f52](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11576)

Local commit: 1e1a0ebf44a219c3bf3e34aed3054afb6d649b02
Server tools version: 5.2.3

### Reproduction Steps

Open game.
Check out changelog
See nothing new.

### Screenshots

![image](https://user-images.githubusercontent.com/24830358/205342729-7d972edd-6e3b-4b40-889b-37dbddc1b1d0.png)

**Comment by Lumipharon** [comment]
Fixed
