### ISSUE TITLE
Wrath's Bane kills facehuggers

### ISSUE THREAD

**Issue by Shootnik01** [tgstation/TerraGov-Marine-Corps#11671]
### Description

What did you expect: Normal larva infestation after Bane

What happened instead: If you use Bane on marine with the hugger on their face - there will be no larva infestation after re-apearing

### Test Merges

Round ID: [6842](https://scrubby.melonmesa.com/round/6842)
BYOND Version: 514.1584
Server revision compiled on: 2022-12-02
Master commit: [891b6d894c92d7dcde96a3a0e128a0cff34ec20d](https://github.com/ss220-space/TerraGov-Marine-Corps/commit/891b6d894c92d7dcde96a3a0e128a0cff34ec20d)

### Reproduction Steps

Let a marine get a hugger in their face
Bane him before infetation
Check marine heath after hugger let go of marine's face

**Comment by Al-1ce** [comment]
Can't find anything about `bane` in the code. You mean Banish?

**Comment by Lumipharon** [comment]
Not a bug, this would also be super cheese.
