### ISSUE TITLE
Grilles are invisible since their icon_state is set to "grille" despite grille not being an actual icon name

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#11694]
### Description

The actual grille icon_state names are grille0, grille1, and so forth

### Test Merges

doesn't matter

### Reproduction Steps

1. Make or find a grille
2. It's invisible

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/206340853-5486ac85-0b40-4b3e-9372-ec4f770cac8d.png)
![image](https://user-images.githubusercontent.com/24631139/206341027-0622b7fd-a736-4161-8408-d7fb8d1575a8.png)

**Comment by RipGrayson** [comment]
This is a me problem since I last adjusted grilles, I'll try to have a fix in by tomorrow if I have time.
