### ISSUE TITLE
Loadout vendors don't save clothing.

### ISSUE THREAD

**Issue by Araulius** [tgstation/TerraGov-Marine-Corps#11707]
### Description

save loadout, vend loadout

saved loadout, vended everything except my clothes

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [18298](https://scrubby.melonmesa.com/round/18298)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [6f9b6fe53ea910089986bab1c0441042167faf4b](https://github.com/tgstation/TerraGov-Marine-Corps//commit/6f9b6fe53ea910089986bab1c0441042167faf4b)
The following pull requests are currently test merged:
[#11637: 'Adds TGUI Say aka. new chatbox for text' by SplinterGP at commit d22e060a09](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11637)
[#11697: 'Sentinel Redesigned' by lKiseki at commit 8e0268c78b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11697)
[#11701: 'Removes juggling NO MOB VARS edition' by Waselon at commit 31704a6163](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11701)

Local commit: 6d510ba923fc3169f1a1809c4bf2ac6acefe1d21
Server tools version: 5.2.3

### Reproduction Steps

1. vend standard kit from marine vendor, not from clothing vendor
2. save loadout
3. load loadout
4. scream

### Screenshots

https://cdn.discordapp.com/attachments/500801682058379265/1051632185393811567/TerraGov_Marine_Corps_2022-12-11_16-49-58.mp4

video linked in tgmc discord

**Comment by Xander3359** [comment]
- Which clothing item failed to dispense?
- Is this on HVH or Nuclearwar/crash?
- Is this still reproducible today?
