### ISSUE TITLE
Decap synth is stuck unable to leave body

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#11732]
### Description

Apparently getting decapped lets you still talk and you're stuck as the head. Unfortunately this is literally worse than dying because now you're now stuck forever unable to obs or anything at all without even radio unless you ghost, which DNRs you regardless of having no defib timer.

### Test Merges

[#11637: 'Adds TGUI Say aka. new chatbox for text' by SplinterGP at commit d22e060a09](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11637)
[#11697: 'Sentinel Redesigned' by lKiseki at commit 8e0268c78b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11697)

### Reproduction Steps

Step 1 die

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/208255710-ee91e3fe-9923-41a4-a9ab-f6da884eddcd.png)

**Comment by private-tristan** [comment]
![url](https://user-images.githubusercontent.com/54422837/208270614-36c9f164-f0c0-494b-bbfc-be1a12bea42a.jpg)

**Comment by private-tristan** [comment]
https://user-images.githubusercontent.com/54422837/208270686-d34f21cf-8a4e-48a8-ae1a-51a041d081d6.mp4

**Comment by FIXTHERADBOXPLEASE** [comment]
Intended behavior. Synths aren't actually dying when their heads are cut off. Watch Alien(s).

**Comment by Losenis** [comment]
Not intended, no changelog so far of it from back when this did kill synths.

**Comment by Al-1ce** [comment]
> Intended behavior. Synths aren't actually dying when their heads are cut off. Watch Alien(s).

It is definitely not intended.
