### ISSUE TITLE
Xeno Gasses do not expand when inside Marine Gasses

### ISSUE THREAD

**Issue by shelteredfreak** [tgstation/TerraGov-Marine-Corps#11775]
### Description

I'll start off by saying, I surely hope this isn't going to be a Todd Howard "it's not a bug, it's a feature" moment where it is seriously suggested that marines use smokes and Tfoot to cancel out other gasses. There really needs to be a way for gasses to expand inside of gasses so every single time that a Defiler tries to gas in a cloak nade, or a Boiler globs a FOB but gets stopped by a cloak nade, it doesn't just cancel out and waste time and plasma.

Seriously. I don't think this should be a thing.

### Test Merges

The following pull requests are currently test merged:
[#11624: 'TGMC Christmas 2022' by RipGrayson at commit d791d2007c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11624)
[#11758: 'Throwpass refactor' by Lumipharon at commit 6d9d01f0c9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11758)
[#10418: 'Changes shrike's abilities and base health' by Losenis at commit c096bcad4f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10418)

### Reproduction Steps

1. Make Defiler
2. Make an Unga with a smoke nade of any kind.
3. Trigger smoke nade
4. Use Defiler gas and attempt to gas inside smoke nade.
5. Gas starts at point of interval
6. Gas does not expand past point
7. Defiler left wide open.

or Option B:
1. Make Boiler
2. Make Unga with a smoke nade of any kind.
3. Trigger smoke nade.
4. Launch and land glob in smoke nade.
5. Glob starts at point of landing.
6. Glob does not expand past point.
7. Boiler plasma and time wasted.

**Comment by Lumipharon** [comment]
This is a feature. Some gases have a flag that let's them stack, most do not.

**Comment by shelteredfreak** [comment]
Why? Is this supposed to be an intentional strategy? Are marines SUPPOSED to gas wall to counter gas attacks? Or was it just decided that Xenos aren't supposed to have gasses that spread.

**Comment by Al-1ce** [comment]
> Why? Is this supposed to be an intentional strategy? Are marines SUPPOSED to gas wall to counter gas attacks? Or was it just decided that Xenos aren't supposed to have gasses that spread.

The idea is that you can use the transparent smoke grenades to counter boiler gas. It's been a feature for ages. Very much intended.
