### ISSUE TITLE
Hydrocannon on flamers don't spawn with loadouts

### ISSUE THREAD

**Issue by KerbalCitizen** [tgstation/TerraGov-Marine-Corps#11776]
### Description

I expected my flamer loadout to spawn a flamer with a hydrocannon, but it didn't have a hydrocannon attached. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [18518](https://scrubby.melonmesa.com/round/18518)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [b5edde37ff51d50bc2a4f73a5370d0f4c6d4abe3](https://github.com/tgstation/TerraGov-Marine-Corps//commit/b5edde37ff51d50bc2a4f73a5370d0f4c6d4abe3)
The following pull requests are currently test merged:
[#11624: 'TGMC Christmas 2022' by RipGrayson at commit d791d2007c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11624)
[#11758: 'Throwpass refactor' by Lumipharon at commit 6d9d01f0c9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11758)
[#10418: 'Changes shrike's abilities and base health' by Losenis at commit c096bcad4f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10418)

Local commit: df1e94435186d046d29ccae1ff3c8780c0a0fbbc
Server tools version: 5.2.3

### Reproduction Steps

1. Get flamer, it starts with hydrocannon
2. Wear it on suit storage or back slot
3. Make loadout
4. When naked, use your loadout
5. Flamer from loadout lacks the hydrocannon

**Comment by Al-1ce** [comment]
This is recent. Wasn't happening 2 weeks ago.
