### ISSUE TITLE
Drop pods aren't working for theseus ship on big red

### ISSUE THREAD

**Issue by pilotmans** [tgstation/TerraGov-Marine-Corps#11799]
### Description

Ground map: Big red

Ship Map: Theseus

i get the cords to drop pod right outside fob due to no one setting the alamo cycle, but it says "CANNOT LAUNCH THERE AREA IS DEEP UNDERGROUND". The thing is everywhere else on the map said this except roofed areas which just said what they normally say.

8 people were waiting for the alamo to come up due to drop pods not working.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [18595](https://scrubby.melonmesa.com/round/18595)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [83ac5bccc59a65f53f2a5848fbbfeaf7a754ffe5](https://github.com/tgstation/TerraGov-Marine-Corps//commit/83ac5bccc59a65f53f2a5848fbbfeaf7a754ffe5)
The following pull requests are currently test merged:
[#10418: 'Changes Shrike's abilties, buffs speed.' by Losenis at commit 93f000c4ad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10418)
[#11721: 'Xeno buff of the year (Pre-shutter mazing ability)' by MLGTASTICa at commit 48e45a4fe7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11721)
[#11765: 'King rework - revived' by Lumipharon at commit 4aab63e9d0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11765)
[#11726: 'Ports Delta Station' by RipGrayson at commit 962d846c3c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11726)
[#11598: 'Adds the AGLS-37' by Pariah919 at commit be7117c451](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11598)

### Reproduction Steps

1.Go into drop pods whilst ground map is big red and ship map is Theseus

2. Now try to launch anywhere on the map

### Screenshots

![drop pods are broken](https://user-images.githubusercontent.com/117348971/209602423-e26668db-b624-4035-a7bb-c389dfaa9354.PNG)

**Comment by Lumipharon** [comment]
issue resolved, part of delta TM.
