### ISSUE TITLE
Suicide vest explosion deals less damage diagonally

### ISSUE THREAD

**Issue by Ragecrabbo** [tgstation/TerraGov-Marine-Corps#11808]
### Description

For as long as vest has been around it has dealt its devastate damage in a plus shape rather than in every tile around the player, as a result its damage can vary wildly from 1shotting even the third tier castes to dealing about half of a runner's health from simply being positioned diagonally from your target, which happens more often than not in the chaotic WASD gameplay of TGMC. Considering the one-use style gameplay suicide vest has and the wildly different damage numbers between diagonally blowing a xeno vs cardinally blowing it i propose changing the explosion devastate radius to be around the vester rather than in a plus shape.

### Test Merges

Irrelevant, this has been around for as long as vest has

### Reproduction Steps

1.Put beans around you in a circle at point blank range
2.Activate vest
3.Watch xenos placed diagonally take considerably less damage
4.Cry because you just nuggeted yourself without being able to kill an injured T1 xeno

### Screenshots

https://user-images.githubusercontent.com/85963263/209724863-55e5e0a8-647d-4c71-9a61-015acaa596bd.mp4

https://user-images.githubusercontent.com/85963263/209726991-12a004c2-e39b-440d-bb4a-b1f24f205858.mp4

**Comment by Lumipharon** [comment]
Not a bug. Explosion distances are calculated in cardinal directions, not diagonals. So range 1 = the tile you're on, range 2 = the 4 steps out from that turf, etc. You can see the same thing with grenades, so standing diagonal from them means you can avoid the blast more easily.
