### ISSUE TITLE
Plasma Cutter Can delete Mech

### ISSUE THREAD

**Issue by SpookGoop** [tgstation/TerraGov-Marine-Corps#11819]
### Description

Title

### Test Merges

Round ID: [18644](https://scrubby.melonmesa.com/round/18644)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [d9c4099afa97ad187c7a26120c3e78e0e4fc3660](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d9c4099afa97ad187c7a26120c3e78e0e4fc3660)
The following pull requests are currently test merged:
[#10418: 'Changes Shrike's abilties, buffs speed.' by Losenis at commit 93f000c4ad](https://github.com/tgstation/TerraGov-Marine-Corps//pull/10418)
[#11721: 'Xeno buff of the year (Pre-shutter mazing ability)' by MLGTASTICa at commit 48e45a4fe7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11721)
[#11765: 'King rework - revived' by Lumipharon at commit bf412ff294](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11765)
[#11726: 'Ports Delta Station' by RipGrayson at commit e60301bd74](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11726)
[#11598: 'Adds the AGLS-37' by Pariah919 at commit be7117c451](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11598)

Local commit: 4f55c05f16b87395d532e88de15b76c79cd9229f

### Reproduction Steps

Grab plasma cutter
Walk to mech
Click, delete

### Screenshots

https://cdn.discordapp.com/attachments/978348083597410354/1058075405657055402/image.png
https://cdn.discordapp.com/attachments/978348083597410354/1058075426817327154/image.png

**Comment by lbnesquik** [comment]
Sounds like a feature to me.

**Comment by Tailiik** [comment]
Simple, it's not a bug it's a feature, give a xeno caste a plasma cutter

**Comment by Naaanii** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/11821
