### ISSUE TITLE
Resin walls spontaneously generating snow turf on Ice Colony

### ISSUE THREAD

**Issue by Anonmare** [tgstation/TerraGov-Marine-Corps#1181]
## Reproduction: Has happened on various rounds now. Essentially, if you clear out snow , resin it and put a resin wall on top of it and then destroy the resin wall - The exact same tile of snow will magically re-appear underneath it. This only happens to tiles that originally had snow on them, tiles that began the round already clear are unaffected.

**Comment by Alterist** [comment]
duplicate of #1023
