### ISSUE TITLE
MOOC goes to OOC

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#11840]
### Description

I press on keybind for MOOC to talk in MOOC, only to be using OOC instead.

### Test Merges

https://github.com/tgstation/TerraGov-Marine-Corps/pull/11637

### Reproduction Steps

1. Use keybind for MOOC.
2. Actually talking in OOC.
3. Go to OOC tab for MOOC.
4. Talk in MOOC.
5. guh

### Screenshots

https://user-images.githubusercontent.com/6610922/210155664-a70eb941-a24a-4438-b1fe-077877e628c8.mp4

**Comment by psykzz** [comment]
Fixed by #11841
