### ISSUE TITLE
Crusher can fling marines into fog

### ISSUE THREAD

**Issue by Luxyboo** [tgstation/TerraGov-Marine-Corps#11857]
### Description

title says all

### Test Merges

[#11765: 'King rework - revived' by Lumipharon at commit 9e120b6d71](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11765)
[#11726: 'Ports Delta Station' by RipGrayson at commit 7e1dea5613](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11726)
[#11598: 'Adds the AGLS-37' by Pariah919 at commit be7117c451](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11598)

### Reproduction Steps

1. be crusher
2. fling marine while standing in fog

### Screenshots

https://i.imgur.com/OQ6g50l.png

**Comment by FIXTHERADBOXPLEASE** [comment]
Could be fixed by letting marines on the wrong side of the fog walk out of it.

**Comment by coldironwarrior** [comment]
closed by #12763; other xeno abilities still circumvent
