### ISSUE TITLE
Tanks are literally invincible.

### ISSUE THREAD

**Issue by SaveVatznick** [tgstation/TerraGov-Marine-Corps#1188]
## Reproduction:
A tank with a specific loadout was completely invincible. It was able to sustain around two full minutes of sitting near-still in a swarm of attacking xenomorphs including an elder Queen, two Ravagers, and five to six other xeno castes without any outward signs of damage (Sprites appeared undamaged). It also survived a full charge from a Xeno Crusher, who reported that its sprite was briefly damaged before updating to be completely unharmed. I am unsure whether the parts themselves functioned as if they were damaged or if the parts still functioned as if they were at 100%. I am also unsure as to whether this issue is specific to this tank loadout.

Here is an examination of the tank after it took its beating.
"A giant piece of armor with a big gun, you know what to do. Entrance in the back. 
There is a heavily damaged Snowplow installed on the armor slot. 
There is a heavily damaged Treads installed on the treads slot. 
There is a heavily damaged TOW Launcher installed on the secondary slot. 
There is a damaged Overdrive Enhancer installed on the support slot. 
There is a heavily damaged LTAA-AP Minigun installed on the primary slot."

None of the parts, despite this description, displayed any damage.

**Comment by David-Stormwell-TGCM** [comment]
I think this might be a Sprite bug, Because it Also Happened to me once, It showed all the guns looking a little beat up but fine, When I tried to fire nothing happened, So When I examined it nothing was on/ everything was destroyed

**Comment by Rohesie** [comment]
#773

**Comment by DominikPanic** [comment]
Casued by a testmege, but fixed
