### ISSUE TITLE
Vended bottles of Chemicals can't be vended from Chemical fridges after put in (Including Lemoline), as they are mistaken for Chem Master bottles of that same chemical.

### ISSUE THREAD

**Issue by CCorvet** [tgstation/TerraGov-Marine-Corps#11893]
### Description

Ditto to above
This seems to be, because the Spawned in bottles are mistaken for chem master bottles of same chemical. The lack of count change is a weird irregularity though.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [18850](https://scrubby.melonmesa.com/round/18850)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [9091e0acca3033b982bdabbe10ec9091a89c5f15](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9091e0acca3033b982bdabbe10ec9091a89c5f15)
The following pull requests are currently test merged:
[#11598: 'Adds the AGLS-37' by Pariah919 at commit 2a5abae096](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11598)
[#11829: 'Repair refactor/QOL' by Lumipharon at commit 95e05613a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11829)
[#11726: 'Ports Delta Station' by RipGrayson at commit 7e1dea5613](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11726)
[#11765: 'King rework - revived' by Lumipharon at commit 9e120b6d71](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11765)

Local commit: aacbb86a992ba21e62eb64dea446ba16850e9358
Server tools version: 5.2.3

### Reproduction Steps

1. Spawn as medical researcher.
2. Go to Chemistry.
3. Put your lemoline in the fridge while you do something.
4. Try to get it out to make something.
5. Cry as its eaten by the fridge and mocking you.

### Screenshots

![image](https://user-images.githubusercontent.com/36166722/211225239-4656b17c-b3cc-469d-979c-6dab02a1a158.png)
![image](https://user-images.githubusercontent.com/36166722/211225244-2c95fa4d-0ce9-4ff5-a5d1-4831cc9d584d.png)
Vending doesnt work
![image](https://user-images.githubusercontent.com/36166722/211225253-67441edc-68e2-4c01-8b7c-341a6d23b927.png)
Added bottle from chem master, count doesnt change, nor is a new item added
![image](https://user-images.githubusercontent.com/36166722/211225271-9ce8bbf2-b929-4066-884a-56a1d01d581a.png)
When you vend now, you get back the chem master chemical bottle

**Comment by QualityVan** [comment]
Are non-lemo things being returned from the fridge without issue?

**Comment by CCorvet** [comment]
Did some testing. It seems to be that its a case of spawned in bottles of chems (like researchers start with, can be vended from nanotrasen med) are the ones that can't be vended.

This is because they are mistaken for the chem bottles from the chem master. What i mean, is the chem master ones work fine. But when trying to vend from the fridge, it tries to vend the chem master one, even if a spawned in one is there. It for some reason doesnt increase the count in the fridge when you have one of each though? Heres screens for what i mean


![image](https://user-images.githubusercontent.com/36166722/211225057-4fe425cc-bb31-484c-bc45-05c0a497d895.png)
![image](https://user-images.githubusercontent.com/36166722/211225069-9822afed-ce7e-45ce-ab25-114df6bf4390.png)
![image](https://user-images.githubusercontent.com/36166722/211225078-649bb5c0-9213-43e7-9de7-86852a43eb4d.png)
