### ISSUE TITLE
Admins are unable to play music via Play-Internet-Sound verb

### ISSUE THREAD

**Issue by Andromalis** [tgstation/TerraGov-Marine-Corps#11896]
### Description

Music should be playing after pasting and accepting the link (and after clicking through some more menu popups) but you instantly get this instead:

```
Youtube-dl URL retrieval FAILED: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
    video_id, player_url, s
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "c:\python36\lib\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'sa'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Test Merges

Round ID: [18866](https://scrubby.melonmesa.com/round/18866)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [9091e0acca3033b982bdabbe10ec9091a89c5f15](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9091e0acca3033b982bdabbe10ec9091a89c5f15)
The following pull requests are currently test merged:
[#11598: 'Adds the AGLS-37' by Pariah919 at commit 2a5abae096](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11598)
[#11829: 'Repair refactor/QOL' by Lumipharon at commit 95e05613a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11829)
[#11726: 'Ports Delta Station' by RipGrayson at commit 7e1dea5613](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11726)
[#11765: 'King rework - revived' by Lumipharon at commit 9e120b6d71](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11765)

Local commit: aacbb86a992ba21e62eb64dea446ba16850e9358
Server tools version: 5.2.3

### Reproduction Steps

1. Type Play and press space then select the Play Internet Sound verb from the dropdown list
2. Paste a random youtube URL and press Enter
3. Observe the abovementioned wall of text appear in the text box

### Screenshots

![obraz](https://user-images.githubusercontent.com/35076994/211197921-6238f8f4-9a19-418a-8715-819d5d5a3ff3.png)

**Comment by Andromalis** [comment]
07.02.2023 17:17 Polish time the music player has worked atleast once

**Comment by TiviPlus** [comment]
Host issue
