### ISSUE TITLE
Flamethrower hydro cannon doesn't extinguish self anymore

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#11928]
### Description

When lit on fire, it is tradition of a flamethrower marine to aim at wall to self extinguish with hydro cannon. Not anymore.

### Test Merges

#[11728](https://github.com/tgstation/TerraGov-Marine-Corps/pull/11728)

### Reproduction Steps

1. Get lit on fire
2. Turn on hydro cannon
3. Shoot wall with hydro cannon to self extinguish
4. Still on fire

### Screenshots

https://user-images.githubusercontent.com/6610922/212404394-e0a9213f-9f29-49bf-9c57-12fa30a42193.mp4

**Comment by novaepee** [comment]
ironic, you can extingish others but not yourself
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.tenor.co%2Fimages%2F231e2f67bc42bbfcff592d58f0e9517e%2Fraw&f=1&nofb=1&ipt=75ebbbd7a035dc59424e3adbbf26f2a6861bed1d5d5dd095d7fc98785b06a3ef&ipo=images

**Comment by Lumipharon** [comment]
Not a bug.
