### ISSUE TITLE
Defender Charge from Fortify fails to activate.

### ISSUE THREAD

**Issue by shelteredfreak** [tgstation/TerraGov-Marine-Corps#11972]
### Description

This has been happening to me for a while but I always just stopped playing Defender when it pissed me off.

I pretty much know exactly why it's happening, but I seriously don't think this should happen.

If you spam the ability for Charge directly after Fortifying as Defender, it will do the windup then fail to activate. I am 90% sure this is because changing Crest states causes a downtime on all abilities similar to resting. Like a short cooldown. But this is especially irritating since the windup will happen but then you won't charge, leaving you to just be a sitting duck because you can't cancel the windup while fortified.

Preferably either make it so the charge will come out as soon as you fortify, or make sure that the ability can't be set into windup if it won't activate. Probably by making Fortify/Lower Crest cancel all windups or something.

Extra, don't read if you don't care:
Making changing Crest states cancel windups would likely massively improve Defenders survivability since it would prevent Defenders from always being punished for activating windups. Defender is very clearly a stun heavy caste in combat, armor does not get you far when most bullets sunder or penetrate. So being sent to death simply because of a windup doesn't sound exactly fair.

I kinda would like to see that old PR for Defender by Losenis to come back somehow, because Defender really hasn't been touched in ages and needs a touchup of some sort. 

### Test Merges

The following pull requests are currently test merged:
[#11715: 'Howitzer removed from roundstart, reworked some shells, added mustard shell.' by Pariah919 at commit 7d66e523d4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11715)
[#11721: 'Xeno buff of the year (Pre-shutter mazing ability)' by MLGTASTICa at commit 44e73e0c2f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11721)
[#11824: 'Adds new pain, gored, preburst and scream sounds, courtesy of The God Of Clowns.' by Calyxman at commit a896e2d825](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11824)
[#11885: 'GPMG/MMG Buff' by Pariah919 at commit a4ff766e8f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11885)
[#11934: 'Introduces the Style Line of equipment' by lKiseki at commit bb0c2e278a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11934)
[#11878: 'Heavy Minigun and Dual AC are now not-hardpoint only (and necessary emplaced gun price changes)' by maikilangiolo at commit d930c74c9d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11878)
[#11802: 'Integrates throwing knives into the autofire system.' by Xander3359 at commit 8d070e6d53](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11802)

### Reproduction Steps

1. Select Defender
2. Fortify while spamming right click (or whatever yours is) to Charge
3. Watch the windup happen
4. Charge does not come out
5. Be left sitting there, dick out, stuck in fortify for all the marines to point, laugh, and shoot at.

### Screenshots

I would probably just put pictures of the amount of times I've died to this, but there would be too many

**Comment by Xander3359** [comment]
I wasn't able to reproduce this, if you run into it again, please open a issue with more detailed reproduction steps.
