### ISSUE TITLE
Primordial Warrior's empowered ability outline wont go away.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#11997]
### Description

Read title, something broke the icon updates on the ability and keeps it permanently shown as empowered. 

### Test Merges

This was happening before the action icon PR, so I doubt the TM was the cause.
#11937 
Other testmerges in question aren't relevant pretty sure.
Round ID: [19159](https://scrubby.melonmesa.com/round/19159)

### Reproduction Steps

1. Get primordial
2. Do 2 abilities
3. Forever stuck

### Screenshots

https://user-images.githubusercontent.com/24631139/213885691-418cd588-3034-49b9-8052-2c83d7d79393.mp4

**Comment by krutoi2000** [comment]
I had the same issue. Fix it pls

**Comment by coldironwarrior** [comment]
fixed; maybe by #14942
