### ISSUE TITLE
Belt Harness no longer fucking works

### ISSUE THREAD

**Issue by FIXTHERADBOXPLEASE** [tgstation/TerraGov-Marine-Corps#12008]
### Description

It doesn't.

### Test Merges

None.

### Reproduction Steps

1. Put two guns on both slots, without mag harnesses.
2. Wear a belt harness.
3. Have your guns uselessly drop to the floor, meaning it's absolutely useless.

**Comment by QualityVan** [comment]
If you need instructions on how to use the belt harness, check out the enclosed instruction book.

**Comment by Tailiik** [comment]
It's not broken, it was changed by an engineer main who was salty xenos melted his plasma cutter. Hold gun (or plasma cutter) in hand, click belt harness with gun. It doesn't magically magharn any gun you drop, you have to manually link a gun to it now.

**Comment by FIXTHERADBOXPLEASE** [comment]
Well that's fucking useless for the intended purpose then.
The only reason anyone ever used it was to let two guns strap at once without mag harnesses. What the fuck is the point of the current version?

**Comment by metalyc** [comment]
Instead of being angry about game changes, perhaps we can suggest a way to solve this issue, such as allowing the belt harness to equip to more than one weapon?

**Comment by Xander3359** [comment]
This is not a bug. There is a warning that you have to attach a gun to the belt harness before it works. Diagnostic: Skill issue.
