### ISSUE TITLE
wraith can go out in the sea to swim part 2 the reckoning

### ISSUE THREAD

**Issue by Aporhtonoma** [tgstation/TerraGov-Marine-Corps#12036]
### Description

I expected to not be able to go out in the sea and have free access to fob in the prison station map but I was able

### Test Merges

Round ID: [19326](https://scrubby.melonmesa.com/round/19326)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [14692e7e321c316d9d5e87cef93d138af1883f91](https://github.com/tgstation/TerraGov-Marine-Corps//commit/14692e7e321c316d9d5e87cef93d138af1883f91)
The following pull requests are currently test merged:
[#11802: 'Integrates throwing knives into the autofire system.' by Xander3359 at commit 8d070e6d53](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11802)
[#11946: 'Xenomorphs EORD respawn' by hyper2snyper at commit 353a7a5311](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11946)
[#12009: 'Adds a new Marine gun- The Magnum' by Pariah919 at commit 8662599608](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12009)
[#11999: 'Spatial grid port' by Lumipharon at commit 6c71a7720d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11999)
[#11715: 'Howitzer removed from roundstart, reworked some shells, added mustard shell.' by Pariah919 at commit 7d66e523d4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11715)

### Reproduction Steps

1.Banish 1 of the 2 shutters in the little sea bridge(picture included)
2.walk out YOU ARE FREE
3.(optional) place a portal for easy access and virtually infinite gateways to freedom

### Screenshots

LOCATION :
![Screenshot (2398)](https://user-images.githubusercontent.com/101722867/215300362-aeda0854-4f12-443e-a54f-c725635ae21d.png)
shutter before disaster happens:
![Screenshot (2401)](https://user-images.githubusercontent.com/101722867/215300454-f4103c35-4565-445b-bdba-cbf518ef7b9a.png)
shutter after disaster happens:
![Screenshot (2400)](https://user-images.githubusercontent.com/101722867/215300426-a79858a5-1c25-4c82-8236-5c6dfb453a08.png)
the disasterous effects if this is not fixed:
![detriments of ignoring this](https://user-images.githubusercontent.com/101722867/215300484-583f89bd-db27-40ce-b56c-93265d260f8e.png)

**Comment by RipGrayson** [comment]
This can no longer happen, I just forgot to close this issue when I fixed it
