### ISSUE TITLE
Flare sprite takes up entire tile, even if visually they don't

### ISSUE THREAD

**Issue by Jalopkomit18** [tgstation/TerraGov-Marine-Corps#12051]
### Description

If you mouse over a tile with a flare on it, on the bottom left it will say you've moused over the flare even if your cursor is on the tile or something else. This also applies to flares that have burnt out. This makes it impossible to other objects on the same tile as the flare until you pick up the flare.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [19369](https://scrubby.melonmesa.com/round/19369)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [3b69ac4a11bae567be623821b7bd77aa1e512bef](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3b69ac4a11bae567be623821b7bd77aa1e512bef)
The following pull requests are currently test merged:
[#11802: 'Integrates throwing knives into the autofire system.' by Xander3359 at commit 8d070e6d53](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11802)
[#11946: 'Xenomorphs EORD respawn' by hyper2snyper at commit 353a7a5311](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11946)
[#12009: 'Adds a new Marine gun- The Magnum' by Pariah919 at commit e6c435e530](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12009)
[#11721: 'Xeno buff of the year (Pre-shutter mazing ability)' by MLGTASTICa at commit c5d8c9ad97](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11721)

Local commit: a5a1cc5739e028c2f2631388d84a7f4c1e053c86
Server tools version: 5.2.3

### Reproduction Steps

1. Throw flare on tile with another object on it.
2. Try to pick up or interact with object that isn't flare.
3. Fail because it thinks you are clicking on flare sprite even when you are not

**Comment by lbnesquik** [comment]
Can't reproduce on a local server.

BYOND Version: 514.1585
Server revision compiled on: 2023-01-16
Master commit: [09ffe3fc9fc9e257b27e9e5528416207f6ef5cab](http://127.0.0.1:52819/commit/09ffe3fc9fc9e257b27e9e5528416207f6ef5cab)

**Comment by CCorvet** [comment]
Can reproduce in gameplay, is annoying.

**Comment by Ragecrabbo** [comment]
Can confirm this happening, alt clicking works but is an annoying way to get around the issue

**Comment by Xander3359** [comment]
I have experienced this as well in-game, If you can get more detailed reproduction steps it would help me significantly.
Things such as:
Which direction are you throwing the flare from?
Are you throwing the flare? Dropping a lit flare? Shooting it from flare gun?
Is it flares that get grabbed from xenos and moved?
Is it flares marines pick up and throw again?

If it can't be consistently reproduced, it's hard to find the problem in code.
