### ISSUE TITLE
Body Scanner consoles do not bring up the UI when clicked on

### ISSUE THREAD

**Issue by CCorvet** [tgstation/TerraGov-Marine-Corps#12088]
### Description

Ditto
Seems to have been the case for a while, just no one reported it and its no problem thanks to health analyzers

### Test Merges

Round ID: [19467](https://scrubby.melonmesa.com/round/19467)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [a7d366db9cfa0aab4fc79e99f871d0661f0d18ea](https://github.com/tgstation/TerraGov-Marine-Corps//commit/a7d366db9cfa0aab4fc79e99f871d0661f0d18ea)
The following pull requests are currently test merged:
[#11802: 'Integrates throwing knives into the autofire system.' by Xander3359 at commit 8d070e6d53](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11802)
[#11946: 'Xenomorphs EORD respawn' by hyper2snyper at commit 353a7a5311](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11946)
[#12009: 'Adds a new Marine gun- The Magnum' by Pariah919 at commit acb1b24f44](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12009)
[#11999: 'Spatial grid port' by Lumipharon at commit 06687ac483](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11999)
[#12058: 'Nerfs Shields melee/acid resistances and shield melee coverage overall' by Pariah919 at commit 92ae655e6e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12058)

Local commit: b190388b9add40a122b5c606f6dce97df7259a74
Server tools version: 5.2.3

### Reproduction Steps

1. Go to medbay.
2. Click on body scanner console, doesn't matter whether there is a body inside or not.
3. Cry as UI does not pop up.

**Comment by Xander3359** [comment]
https://user-images.githubusercontent.com/66163761/221997214-937d665f-3b94-4092-86b4-f9630f3bd6cf.mp4

Works just fine.
