### ISSUE TITLE
RO's pistol doesn't take special ammo speedloaders.

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#12086]
### Description

The R-44 SAA revolver is a roundstart item for the Req Officer and starts with 6 speedloaders, 1 of which is "PW-MX" and another one "Marksman". Try as you might, you can't actually load this ammo in the revolver from the speedloaders, you gotta put the ammo in hand from the speedloaders AND THEN load it into the gun.

### Test Merges

The following pull requests are currently test merged:
[#11802: 'Integrates throwing knives into the autofire system.' by Xander3359 at commit 8d070e6d53](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11802)
[#11946: 'Xenomorphs EORD respawn' by hyper2snyper at commit 353a7a5311](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11946)
[#12009: 'Adds a new Marine gun- The Magnum' by Pariah919 at commit acb1b24f44](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12009)
[#11999: 'Spatial grid port' by Lumipharon at commit 06687ac483](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11999)
[#12058: 'Nerfs Shields melee/acid resistances and shield melee coverage overall' by Pariah919 at commit 92ae655e6e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12058)

### Reproduction Steps

1. Empty R44 revolver
2. Open cylinder
3. Try to put PW-MX/Marksman ammo into it, fail
4. put revolver on ground
5. click on speedloader with empty hand while it is in other hand to retrieve ammo
6. you can put this retrieved ammo into the revolver.. but not when it's on the speedloader??

**Comment by Tailiik** [comment]
Speedn'tloader
