### ISSUE TITLE
Hive Status Bluescreening itself

### ISSUE THREAD

**Issue by metroid1310** [tgstation/TerraGov-Marine-Corps#12172]
### Description

I expected to be able to see Hive Status to see how Xenos were doing, but instead every time I attempt to open it, "NTOS" bluescreens. It told me to send the text to Github and the issue seemed a bit persistent (within the one round that happened while I was trying).

Reproduction steps are uncertain, will be the things I did that I feel have any remote chance of being pertinent

### Test Merges

Round ID: [19660](https://scrubby.melonmesa.com/round/19660)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [3ed58f204862c328213544d44ce5b009afa5fdea](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3ed58f204862c328213544d44ce5b009afa5fdea)
The following pull requests are currently test merged:
[#11946: 'Xenomorphs EORD respawn' by hyper2snyper at commit 353a7a5311](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11946)
[#12068: 'Adds a knee mortar' by Pariah919 at commit d058a4680c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12068)
[#11856: 'Refactor gun modifier calculations and some related stuff' by Lumipharon at commit 83362ce940](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11856)
[#12000: 'Jaeger update' by Lumipharon at commit edd5258b54](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12000)

Local commit: 772c97f69a33a0f99275b0f0892b86fc827f529a
Server tools version: 5.2.3

### Reproduction Steps

1. I observed
2. Went to Valhalla, left Valhalla
3. Decided not to play, disconnected
4. Closed all BYOND/Dreamseeker programs that tried to keep running
5. Reconnected later, clicked Hive Status, Hive Status always bluescreened when I opened it
6. Reconnect again, Hive Status still bluescreening
7. Spawned as Xeno, Hive Status still bluescreening

### Screenshots

![image](https://user-images.githubusercontent.com/43509288/218622617-f4623fe5-e1c7-4631-95d7-dddd935d4019.png)

**Comment by metroid1310** [comment]
Someone else said their Hive Status was also broken after I started to play, but this apparently wasn't affecting _everybody_
![image](https://user-images.githubusercontent.com/43509288/218636030-a59c1b29-b1df-4dd6-93fc-685e3c62ec90.png)
![image](https://user-images.githubusercontent.com/43509288/218635611-f565a073-acfb-4e85-8be8-953495ccf089.png)

**Comment by Arturlang** [comment]
Impossible to diagnose unless someone bothers to get the exact revision, compile TGUI, look at minified TGUI to find the exact line that bork'd, that'd only tell us what broke, but not how, that's probably due to a runtime or something, TGUI is a nightmare to investigate

**Comment by Al-1ce** [comment]
Just press F5 on the broken tab. Yes, seriously. It's that easy.
