### ISSUE TITLE
Game Preferences is Broken

### ISSUE THREAD

**Issue by Otterwatch** [tgstation/TerraGov-Marine-Corps#12242]
### Description

You try to press the button to setup character/Game Preferences and it does nothing. The old fix for it giving you the ntos error does not work either. I had 10 people at least who had this problem during the end of the round. It was Ice Colony round ID 19906 which lasted two hours. The round ended before I could investigate further. It works at the start of the next round.

### Test Merges

[#11946: 'Xenomorphs EORD respawn' by hyper2snyper at commit 353a7a5311](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11946)
[#12168: 'healing kit refactor' by TiviPlus at commit 71748ae37d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12168)
[#12235: ' Moves end round info to its own panel, second try' by RipGrayson at commit 7e758873c2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12235)

### Reproduction Steps

1. Click on Character Setup/Game Preferences
2. Watch as it does nothing.

### Screenshots

![game prefs](https://user-images.githubusercontent.com/77871802/221435755-404bd74d-1fed-4f1a-b693-01777a7c22f2.PNG)

**Comment by TiviPlus** [comment]
Unable to reproduce
