### ISSUE TITLE
Can no longer repair multiple barricades at the same time

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#12378]
### Description

The intended behavior at #11312 seems to have been broken by what I suspect is #11829. It also broke plasteel barricade multirepair, which goes even farther back than the former. You are now forced to repair barricades one at a time, and there doesn't seem to be any changelog or PR that'd imply this is intended behavior.

### Test Merges

[#12200: 'Adds more loadouts to EORD' by carlarctg at commit 527d1bf109](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12200)

### Reproduction Steps

Go to Valhalla as engi
Grab mats
Make cades
Damage them a bit
Try to repair them at the same time
Be unable to, text "busy" pops up

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/224339094-5082c1d5-b2e3-4cf5-a673-eec32029046d.png)

**Comment by Xander3359** [comment]
Pretty sure this is intended.

**Comment by Losenis** [comment]
I can't find any changelog that goes "you can no longer repair multiple cades at once"
