### ISSUE TITLE
Often times on snow maps, Plasma cutters will drain twice per wall removal as it removes snow with the wall

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#12442]
### Description

As weeds now grow over snow, when you remove a wall that was placed over snow, itll remove the wall and the weed under it, causing double drain. 

I know this has happened before the current TM though, but I wasn't exactly sure how to replicate it then.

### Test Merges

Round ID: [20188](https://scrubby.melonmesa.com/round/20188)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [36e91d701bf0d850f25837c6fa5a2dbefd4b8994](https://github.com/tgstation/TerraGov-Marine-Corps//commit/36e91d701bf0d850f25837c6fa5a2dbefd4b8994)
The following pull requests are currently test merged:
[#12312: 'Normal smoke extinguishes fire' by Lumipharon at commit cc741af89b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12312)
[#12381: 'Makes snow weedable and removes the slowdown associated with walking on it + guts fake snow and adds real snow to Gelida' by ivanmixo at commit 084e0a2266](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12381)

Local commit: fc5fe87abe5a4dd11137c8a4ee07eb67fa82438b
Server tools version: 5.2.3

### Reproduction Steps

1. Plant a resin weed on snow (or a potentially a tile that starts with snow)
2. Place a resin wall on that tile
3. PC that resin wall
4. Notice how it drains your PC twice, and snow appears for half a second beneath the wall before being removed

### Screenshots

![image](https://user-images.githubusercontent.com/120620754/225484976-2c00d8f6-be01-401c-9a36-4aadf98c2fe9.png)

**Comment by chizzy376** [comment]
Issue is fixed, close it?
