### ISSUE TITLE
MAJOR ISSUE WITH DEPLOYABLES

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#12488]
### Description

You can turn deployables into other deployables. I'm unsure as to which ones work with which ones, but I've turned an HSG-102 into a dispenser. I couldn't store anything in it, but it gave me the red healing beam. Attempting to access its inventory gave me another HSG-102, but it was the same one regardless, as throwing it away and attempting to access the same inventory drew the same one back to me

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20260](https://scrubby.melonmesa.com/round/20260)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [97c094f6aa6ebf245d1317bc04b4079f8a9b6450](https://github.com/tgstation/TerraGov-Marine-Corps//commit/97c094f6aa6ebf245d1317bc04b4079f8a9b6450)
The following pull requests are currently test merged:
[#12312: 'Normal smoke extinguishes fire' by Lumipharon at commit cc741af89b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12312)
[#12475: 'Adds a new lowpop (Crash) map, Desparity.' by chizzy376 at commit edfe828317](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12475)
[#12478: 'Kills pocket var for good + loadout fix' by Lumipharon at commit 4ef4f6f49d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12478)
[#12450: 'Makes xeno structures care about which hive made it' by ivanmixo at commit 5f47dfe952](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12450)

Local commit: 04bb0199fd1640c79a7c42f9f1ea595d94f4bcf6
Server tools version: 5.3.2

**Comment by Xander3359** [comment]
What the fuck. Can you give reproduction steps please.

**Comment by Ridgyaxe** [comment]
Oh yeah, forgot to say, if you want reproduction steps, DM Quint 'Bad Luck' Hawkings on Discord in TGMC
