### ISSUE TITLE
Cant pick up ship weapons whit the riply and the ship doesnt recognise installed stuff

### ISSUE THREAD

**Issue by gustufus** [tgstation/TerraGov-Marine-Corps#125]
i cant pick up ship weapons whit the riply but i can pick up modules and the sentry turrets but the ship doesnt recognise the turrets

**Comment by Rohesie** [comment]
Will keep open because these items should have a larger than 32x32 hitbox defined through `bound_height`/`bound_width`.

**Comment by DominikPanic** [comment]
Fixed in #217
