### ISSUE TITLE
Hunter can disguise as tracker shell blood drip

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#12501]
### Description

As title says, this makes him basically invisible AND UNCLICKABLE.
i hate it

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20288](https://scrubby.melonmesa.com/round/20288)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [4c73d395a0d004c8ef0cffd092eff0a602249ec9](https://github.com/tgstation/TerraGov-Marine-Corps//commit/4c73d395a0d004c8ef0cffd092eff0a602249ec9)
The following pull requests are currently test merged:
[#12312: 'Normal smoke extinguishes fire' by Lumipharon at commit cc741af89b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12312)
[#12475: 'Adds a new lowpop (Crash) map, Desparity.' by chizzy376 at commit 40689ea70f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12475)
[#12200: 'Adds more loadouts to EORD' by carlarctg at commit f278836c02](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12200)
[#12474: 'Icon organisation part I' by Lumipharon at commit d9d21daf7b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12474)

Local commit: 1e8655399fbf673ad97a776b7aeb36fede508700
Server tools version: 5.3.2

### Reproduction Steps

1. primo hunter
2. have tracker shell shoot you
3. disguise as the blood splatter that you dripped

**Comment by Lumipharon** [comment]
A tale as old as time.

The hunter becomes the hunted.
Then the hunted because a tiny drip, making the hunted hunter back into a hunter hunting a hunter who thought they were the hunter but are now the hunted again.
