### ISSUE TITLE
Marines can get abducted into fog

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#12616]
### Description

Any caste with a blink or a special throw move can do this.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20503](https://scrubby.melonmesa.com/round/20503)
BYOND Version: 515.1604
Server revision compiled on: 
Master commit: [ac56f43309c2ba24213b24fd70b7a72ce7246bda](https://github.com/tgstation/TerraGov-Marine-Corps//commit/ac56f43309c2ba24213b24fd70b7a72ce7246bda)
The following pull requests are currently test merged:
[#12584: 'Adds minimap drawing' by TiviPlus at commit 957675a705](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12584)

Local commit: 925e61c433d25affcf115c0798d9156308ba1ae6
Server tools version: 5.7.3

### Reproduction Steps

1. Play crusher (Or wraith, woyer also works iirc)
2. Stand on fog with help intent
3. Click marine with crest toss adjacent to you
4. They get tossed into the fog and can't ever get back out

**Comment by Xander3359** [comment]
Duplicate Issue https://github.com/tgstation/TerraGov-Marine-Corps/issues/11857

**Comment by chizzy376** [comment]
> Duplicate Issue #11857

Just goes to show that nobody has fixed it yet

**Comment by JackTheJackhammer** [comment]
https://user-images.githubusercontent.com/77555989/233492504-5dbd9277-0102-4aff-84ee-d8cbcd491444.mp4

Video of it
