### ISSUE TITLE
Rail Light Bug

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#1264]
## Testmerges:
Not caused by a testmerge. 
## Reproduction:

Put a rail light on your gun, and then put the gun in your suit storage. The bug here is, when you take the gun back out of your suit storage, the rail light stops providing light despite still being on.

**Comment by DominikPanic** [comment]
This no longer seems to be an issue, feel free to reopen with reproduction steps if you encounter it again
