### ISSUE TITLE
Impact hud tablet doesn't work for the HOWITZER

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#12651]
### Description

The tablet found in the ~~mortar and howitzer crate that previously used to show you a live feed of where your shot hit just defaults to viewing your mortar/howitzer without the "tracking munition in air" part, which makes it literally useless~~

The HOWITZER's impact hud tablet is set to track the MORTAR instead of the HOWITZER.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20563](https://scrubby.melonmesa.com/round/20563)
BYOND Version: 515.1604
Server revision compiled on: 
Master commit: [cfbc729d76e6706b6ac26b9cf8d7856e201d2927](https://github.com/tgstation/TerraGov-Marine-Corps//commit/cfbc729d76e6706b6ac26b9cf8d7856e201d2927)
The following pull requests are currently test merged:
[#12560: 'Utilizes ?. a lot more where applicable' by ivanmixo at commit 47b782be5a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12560)

Local commit: 90273a542524e88086364b43e2b299fbdf7be87c
Server tools version: 5.8.0

### Reproduction Steps

1. vend howitzer
2. grab impact hud tablet
3. go groundside, open the tablet ui
4. shoot the howitzer
5. tablet doesn't swap view to the impact zone because it's linked to mortar

### Screenshots

**Comment by QualityVan** [comment]
There was a recent fix to impact tablet, is this still happening?

**Comment by chizzy376** [comment]
This was fixed by a pr
