### ISSUE TITLE
Loadout Issue

### ISSUE THREAD

**Issue by RaveShadows** [tgstation/TerraGov-Marine-Corps#12683]
### Description

For medical researcher job.
You can save loadout, but you cannot equip or load into it.
-This might be put on back burner but my new friend said he really hated that it never loaded in had to constantly rekit every around and be on ground.

Now I know argument to counter is that he dose not need to be on the ground and the marines can just fulton it but most MR's tend to be on the groundside as back up paramedic while researching dead xeno corpses. 

### Test Merges

1: in loadout machine in the server

### Reproduction Steps

1: make custom Researcher loadout
2: save it in the loadout vendor box
3: try to load in your kit.

**Comment by Xander3359** [comment]
I'm requesting video footage, because I know from experience that this is not the case.
