### ISSUE TITLE
Clicks don't seem to be properly checking if the user is restrained.

### ISSUE THREAD

**Issue by Ghommie** [tgstation/TerraGov-Marine-Corps#1276]
## Testmerges: 
None, was testing on a local branch, click code left untouched.

## Reproduction:
1. Be handcuffed
2. Click stuff (pick a machete, knock windows, use tools etc.)
3. See how it generally works, minus on a couple extravagant cases.

Leaving this as an issue report instead of trying to fix it myself as I weren't responsible of the click refactor and may be wrong on its cause, but I strongly suppose it may be a few lines going amiss concerning `RestrainedClickOn()`:
[/tg/13](https://github.com/tgstation/tgstation/blob/bc2161d5545b78da593967e9800b236f253e7efd/code/_onclick/click.dm#L116)
[TGMC](https://github.com/tgstation/TerraGov-Marine-Corps/blob/8ce530ee48b0c39dc4a70987d0450e28feec1be8/code/_onclick/click.dm#L102)

**Comment by DominikPanic** [comment]
I wonder why you were suddenly testing being restrained

**Comment by Ghommie** [comment]
Coincidence, I were testing hypersleepers for the Xth time and retrieved a pair of handcuffs from the brig console, after respawning myself, after cryoing as a MAA, honest.

**Comment by DominikPanic** [comment]
Suuuuure :smirk: :smiling_imp:
