### ISSUE TITLE
Nanites don't give tox

### ISSUE THREAD

**Issue by Jalopkomit18** [tgstation/TerraGov-Marine-Corps#12841]
### Description

Both on the wiki and in the code, nanites should give you tox when healing. However currently does not do this.

### Test Merges

erver-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20848](https://scrubby.melonmesa.com/round/20848)
BYOND Version: 515.1604
Server revision compiled on: 
Master commit: [0125ae9dbe65da0c109b747c69a818a441032153](https://github.com/tgstation/TerraGov-Marine-Corps//commit/0125ae9dbe65da0c109b747c69a818a441032153)
The following pull requests are currently test merged:
[#12648: 'Hivelord's new ability: Recycler Redux' by novaepee at commit 767df6fa85](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12648)
[#12595: 'Mounted AC rework' by Pariah919 at commit 4452489500](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12595)
[#12735: 'Smokening' by Lumipharon at commit 36daaf9b91](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12735)
[#12580: 'Adds SG-62 Target Rifle, a new SG gun with an underbarreled spotting rifle.' by Pariah919 at commit f31cb292b0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12580)
[#12584: 'Adds minimap drawing' by TiviPlus at commit 53ee122e36](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12584)

Local commit: 7f50896df7e5cd96fae28e2bc3dda36a8dc3f083

### Reproduction Steps

1. get nanites
2. burn or slap yourself
3. Get healed by nanites
4. No tox damage though

**Comment by Arctrooper8** [comment]
Even if it's a bug toxin damage would honestly make nanites completely unusable do to the fact that the main toxin healing chem is dylovene which has the very rough side effect of causing your stamina to not regenerate. It'd leave only those with access to stuff such as Hyroline (corpsmen) as the only people able to realistically use nanites. The blood balancing is already good enough I feel and it'd probably be best to just get rid of the toxin damage stuff.

**Comment by Xander3359** [comment]
What? You only get tox in the initial adaptation phase of the nanites (When you inject yourself for the first time)
You aren't supposed to get any toxin from nanites once you pass this phase.

**Comment by BlueHNT** [comment]
> What? You only get tox in the initial adaptation phase of the nanites (When you inject yourself for the first time) You aren't supposed to get any toxin from nanites once you pass this phase.

You get tox once your nanites are low aswell. It gets pretty annoying on top of replenishing your blood every 5 seconds.

**Comment by coldironwarrior** [comment]
closed by #14857
