### ISSUE TITLE
Prison Hangar Doors Bugged

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#1285]
## Reproduction:

Basically, the 3 tiles to the right of the main blast door tile are able to be walked through. They don't block movement. Which means people or xenos can fling themselves off into space. Now, this is the RESEARCH hangar ones, not the ones at LZ1, those are working properly to block movement. 
![Blast Door](https://user-images.githubusercontent.com/29074600/56088365-34a17500-5e4d-11e9-9254-28f111337f4a.png)

**Comment by Zostroll** [comment]
Huh you can ovi on the very var north west bit
