### ISSUE TITLE
Can't shoot crit xenos in water

### ISSUE THREAD

**Issue by Jalopkomit18** [tgstation/TerraGov-Marine-Corps#12881]
### Description

Had an encounter where a xeno got crit in water, and none of the 5+ marines around it could shoot it. I tried to PB it too and that didn't work. I'm not sure if its the same when a xeno gets stunned or rests, if its the same with marines, or if its the same with lava. 
#12864
### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20950](https://scrubby.melonmesa.com/round/20950)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [28a3de077d047097f8558ab8801ebcc095366a40](https://github.com/tgstation/TerraGov-Marine-Corps//commit/28a3de077d047097f8558ab8801ebcc095366a40)
The following pull requests are currently test merged:
[#12595: 'Mounted AC rework' by Pariah919 at commit 4452489500](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12595)
[#12846: 'Makes the AI able to fire and aim railguns' by RipGrayson at commit 179e4531cf](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12846)
[#12848: 'Divides the critical structures by hive + fixes pinpointer harddel' by ivanmixo at commit 86ef545463](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12848)
[#12580: 'Adds SG-62 Target Rifle, a new SG gun with an underbarreled spotting rifle.' by Pariah919 at commit 9b6034e23b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12580)
[#12752: 'Impact Particle Effects' by tyeagg at commit b4a177c8f1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12752)

Local commit: b240d02e58b20018934ae41daa67954c01fe132a
Server tools version: 5.12.0

### Reproduction Steps

1. Go to LV river.
2. Crit a xeno in river
3. Can't shoot it anymore

**Comment by Jalopkomit18** [comment]
It does happen on marines resting in water. I think it may be something with the overlay, because when I aimed to the left most part of the marine's body, it hit. But the right half of the body just displayed river when mousing over

**Comment by isotope436** [comment]
this happens with any living mob that is in a state other than standing when in water it doesnt matter which

**Comment by Lumipharon** [comment]
This actually applies to all mobs, in all states.

I can't figure out the actual cause, but the water alpha mask is causing a specific section of the mob sprite to be unclickable.
