### ISSUE TITLE
Writing responses that are too long in mhelps gets you barred from being a mentor for the rest of the round

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#12947]
### Description

You can get muted by doing your job too well, lol. I hope I don't have to explain why that's a galaxy level of jank.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21087](https://scrubby.melonmesa.com/round/21087)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [56b2d7a380a518c970c11175aa526620825e50d5](https://github.com/tgstation/TerraGov-Marine-Corps//commit/56b2d7a380a518c970c11175aa526620825e50d5)
The following pull requests are currently test merged:
[#12908: 'Platform rework' by Lumipharon at commit e05eb53b77](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12908)

Local commit: 449e6501896252299f2206274dd1a26fa8645af9
Server tools version: 5.12.0
ICCG Davor Sultani says, "Reload with."

### Reproduction Steps

1. get mhelp, claim it
2. write long and good response to it
3. You have exceeded the spam filter. An auto-mute was applied. You do not have sufficient rights to do that. You require one of the following flags: +BAN. You have been muted from adminhelps and PMs.
4. try to claim any other mhelp from now on
5. Error: You are unable to use admin PMs (muted).
6. Error: You are unable to use admin PMs (muted).
7. Error: You are unable to use admin PMs (muted).
8. Error: You are unable to use admin PMs (muted).

**Comment by ClosetedSkeletonGH** [comment]
Can confirm, ive also had this happen
