### ISSUE TITLE
If firing at a king and they use the stone ability, your shots will go haywire

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#12944]
### Description

This seems pretty consistent, Ill be firing at a king and holding down M1 on their character, they go into the stone ability and the eye pops up, then either when it pops up, or after it goes away, my shots will start going everywhere but the king, including at times having me fire backwards.

This causes a lot of FF and I do not think this is intended.

I have noticed this particularly through scopes but Im pretty sure its not just with scopes

### Test Merges

Round ID: [21075](https://scrubby.melonmesa.com/round/21075)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [1bc4be21a00c4bfa1031f377622cc502c6e05a76](https://github.com/tgstation/TerraGov-Marine-Corps//commit/1bc4be21a00c4bfa1031f377622cc502c6e05a76)
The following pull requests are currently test merged:
[#12865: 'Floodlight Rework' by tyeagg at commit 2222bd53d5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12865)
[#12819: 'Allow POs/anyone with access to select what dropship they want to use + ports automatic mobile port sizes' by mc-oofert at commit 7cc7bbd281](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12819)

Local commit: 7919b00e1ff76d31d03d73f1fc4df207b3ec8870
Server tools version: 5.12.0

### Reproduction Steps

1. Be fighting king
2. Be shooting at king
3. King activates freeze ability
4. see error

or

1. be fighting king
2. king uses freeze ability
3. start shooting at king
4. when the ability goes away, notice how shots go haywire

### Screenshots

Partially relevant:
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/41b8b166-6897-4078-9955-833d44c4c6a7)

**Comment by BlueHNT** [comment]
That sounds intended.

**Comment by ClosetedSkeletonGH** [comment]
> That sounds intended.

I dont think it is at all cause it wasn't like my shots going random, but just caused me to start firing south (straight into another marine)

**Comment by ivanmixo** [comment]
Closed in #13168
