### ISSUE TITLE
Ghetto teleportation

### ISSUE THREAD

**Issue by Zostroll** [tgstation/TerraGov-Marine-Corps#1294]
## Testmerges:
Not test merge related.

## Reproduction:
If you move a roller bed at an angle it will move the bed but not move the person you can do this for an unlimited amount of tiles. Then if you move the bed again in a non angle direction they will "teleport" to the roller bed. This can be done across z-levels. I showed @Rohesie so they can attest to it.

**Comment by DominikPanic** [comment]
Very, very ancient bug, so ancient that in fact is a feature at this point

**Comment by Shadow-Quill** [comment]
An annoying one, though.
