### ISSUE TITLE
The tranq bullets do nothing.

### ISSUE THREAD

**Issue by Zostroll** [tgstation/TerraGov-Marine-Corps#1295]
## Reproduction:
The tranq bullets you get in the spec ops crate do nothing.

**Comment by Ghommie** [comment]
From my past experience, tranquilizer munitions were pretty much a noob bait and wouldn't reliably put people to sleep, but apply eye blur, stutter and a handful of drowsyness. I assume this is still an issue either ways.

**Comment by DominikPanic** [comment]
Did you actually reproduce them doing nothing? Because if their effect is just weak that is not a bug but a balancing concern

**Comment by DominikPanic** [comment]
From what I've seen the effects do work, they're just weak. So it's not a bug but more of a balance issue.
