### ISSUE TITLE
Sentry duplication bug

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#12971]
### Description

Deploying anything with a dispenser on your off-hand causes a visual glitch of whatever you've deployed and allows you to duplicate that by just clicking it and deploying it again, instead of just deploying the item normally.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21115](https://scrubby.melonmesa.com/round/21115)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [0394fddcb702371f88c8b5e1e9b19402457197e7](https://github.com/tgstation/TerraGov-Marine-Corps//commit/0394fddcb702371f88c8b5e1e9b19402457197e7)
The following pull requests are currently test merged:
[#12846: 'Makes the AI able to fire and aim railguns' by RipGrayson at commit 8312a53f5f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12846)
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12954: 'Fixes the self destruct' by DeltaFire15 at commit 31686911b1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12954)
[#12819: 'Allow POs/anyone with access to select what dropship they want to use + ports automatic mobile port sizes' by mc-oofert at commit 61a5268a94](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12819)

Local commit: eea9fa1fa3b37a7a5fa9163f3e45fc323aff5d76
Server tools version: 5.12.0

### Reproduction Steps

1. Get a provisions dispenser on your left hand
2. Get any deployable (sentry, HSG etc) on your right hand
3. Switch to left hand and attempt to put down the deployable
4. If it works you now have a glitched deployable on the ground
5. Click it and it'll be duplicated into your hand, which you can then deploy and click, deploy and click until you've filled the map with 50 sentries.

### Screenshots

A video can illustrate this better: https://streamable.com/4oyzf6

**Comment by isotope436** [comment]
it should be stated this works with any deployable that can fit into the dispencer and also allows you to make sentry guns work like HSGs and HSG's work like sentry guns
