### ISSUE TITLE
Cape bug with coloring 

### ISSUE THREAD

**Issue by Sirsnek15** [tgstation/TerraGov-Marine-Corps#13029]
### Description

Both the capes and the kama have the same bug for me and some other players. Coloring the main and the accent works completely fine, but when either are attached, the accent for the capes and the main for the kama, turn to pitch black and ignore any color you choose for them when you wear them. I have seen other people with working capes** and I'm guessing those are from saved to loadouts but I'm not sure.

In the screenshots I have provided, the two pictures of the kama and the two pictures of the cape are from the same kama and cape.

### Test Merges

[#12846: 'Makes the AI able to fire and aim railguns' by RipGrayson at commit 8312a53f5f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12846)
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12819: 'Allow POs/anyone with access to select what dropship they want to use + ports automatic mobile port sizes' by mc-oofert at commit 980df05e68](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12819)
[#12951: 'Tfoot smoke eats xeno smoke' by Lumipharon at commit 162c6c4a9a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12951)
[#12990: 'Autocannon rework MK2' by Pariah919 at commit 75d34f1c10](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12990)

### Reproduction Steps

Grab a cape.
Change the accent color to ANY COLOR (other than black).
put the cape on the uniform.
wear the uniform.
Your mob sprite's cape now has pitch black accents instead of the chosen color.

Grab a kama.
Change the main color to ANY COLOR (other than black).
put the kama on the uniform.
wear the uniform.
Your mob sprite's kama now has pitch black main color instead of the chosen color.

### Screenshots

![yellowaccents](https://github.com/tgstation/TerraGov-Marine-Corps/assets/90616411/24c7aba9-0980-470a-b239-d57a676bfe9d)
![greykama](https://github.com/tgstation/TerraGov-Marine-Corps/assets/90616411/14098fee-b8df-4894-85db-c3eca617a5ab)
![blackkama](https://github.com/tgstation/TerraGov-Marine-Corps/assets/90616411/1cbe0a2c-6cd6-4ad7-b5be-901af6364e78)
![blackaccents](https://github.com/tgstation/TerraGov-Marine-Corps/assets/90616411/9d2cb459-a0f1-4d2b-a1a0-95861e7c57ab)

**Comment by Lumipharon** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/13017
