### ISSUE TITLE
giga fucked damage las machinegun 

### ISSUE THREAD

**Issue by Luxyboo** [tgstation/TerraGov-Marine-Corps#13113]
### Description

issue with damage being way to high on lasmachine gun

### Test Merges

Round ID: [21395](https://scrubby.melonmesa.com/round/21395)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [418f24d643bb30bf9cf1ab744d1ec80b691e0d04](https://github.com/tgstation/TerraGov-Marine-Corps//commit/418f24d643bb30bf9cf1ab744d1ec80b691e0d04)
The following pull requests are currently test merged:
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12964: 'TGUI-ify the strip menu' by ivanmixo at commit c8e5c1c9a1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12964)
[#12995: 'Laser rework' by Lumipharon at commit 27c0719c18](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12995)
[#12893: 'Acid refactor + Acid buff against flares' by Zar000 at commit c67872f686](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12893)
[#13078: 'Command TTS volume is increased' by TiviPlus at commit 19b300e1ce](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13078)

### Reproduction Steps

1. get las machinegun
2. set gun to burst
3. press space bar
4. fire the gun and while its firing switch to charge mode
5. now you have a gun that nearly one shots everything

**Comment by chizzy376** [comment]
Didn't even get credited for finding this smh

**Comment by Lumipharon** [comment]
Fixed
