### ISSUE TITLE
Dropping or using holsters deletes magazines for underbarrels

### ISSUE THREAD

**Issue by Colfer1** [tgstation/TerraGov-Marine-Corps#13119]
### Description

I expected my ammo to be in my underbarrels, and its not. By holster I mean things like the shoulder holster, equipping them to your back, and suit slot works fine.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21419](https://scrubby.melonmesa.com/round/21419)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [120607bf772e0b839412f37d6d626436d3519eb5](https://github.com/tgstation/TerraGov-Marine-Corps//commit/120607bf772e0b839412f37d6d626436d3519eb5)
The following pull requests are currently test merged:
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12964: 'TGUI-ify the strip menu' by ivanmixo at commit c8e5c1c9a1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12964)
[#12995: 'Laser rework' by Lumipharon at commit d0c4fe9d47](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12995)
[#12893: 'Acid refactor + Acid buff against flares' by Zar000 at commit c67872f686](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12893)
[#12434: 'Portable reagent dispenser' by XElectricX at commit 22341f2645](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12434)

Local commit: fdbf9f1227e7d411da4604c346b7cdd89a33906f
Server tools version: 5.12.1

### Reproduction Steps

Put a plasma pistol with an underbarrel shotgun into the shoulder holster, it will lose shotgun shells or put them into your hand
Drop any weapon with an underbarrel, it will either delete the underbarrel magazine or put it into your hand
Underbarrel grenade launchers eject their grenades and drop them into your hand

**Comment by FosterGrime-Heymynameslouie** [comment]
seems to be caused by https://github.com/tgstation/TerraGov-Marine-Corps//pull/12434
