### ISSUE TITLE
dropping a gun with with an UBF causes the mini-incen tank to vanish

### ISSUE THREAD

**Issue by bluezorua** [tgstation/TerraGov-Marine-Corps#13134]
### Description

When you drop a weapon with an underbarrel flamer, the mini-incenerator tank inside the UBF dissapears

### Test Merges

[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12964: 'TGUI-ify the strip menu' by ivanmixo at commit c8e5c1c9a1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12964)
[#12995: 'Laser rework' by Lumipharon at commit b4a58b8906](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12995)
[#12434: 'Portable reagent dispenser' by XElectricX at commit 22341f2645](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12434)
[#13118: 'Automedicals have new sounsd' by Pariah919 at commit d01ec097fb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13118)
[#12893: 'Acid refactor + Acid buff against flares' by Zar000 at commit c67872f686](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12893)
[#13095: 'Quickbuild Rework 2023' by RipGrayson at commit 4ce7da1f1f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13095)

### Reproduction Steps

1. Get a gun, in my case it was a laser rifle with a mag harness
2. put in an UBF
3. put in a mini-incinerator tank
4. hold your gun
5. either press your drop keybind or get knocked down by a xeno
6. look at your gun (and hear the flamer disconnect sound)

**Comment by Lumipharon** [comment]
fix was merged
