### ISSUE TITLE
Being south of alamo while it's crash landing from hijack makes you disappear

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#13149]
### Description

Check attached video, I don't even know what happened

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21479](https://scrubby.melonmesa.com/round/21479)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [9e3ba5bdca0e1d675894f66da8026e648e240f0e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9e3ba5bdca0e1d675894f66da8026e648e240f0e)
The following pull requests are currently test merged:
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12995: 'Laser rework' by Lumipharon at commit b4a58b8906](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12995)
[#13095: 'Quickbuild Rework 2023' by RipGrayson at commit 4ce7da1f1f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13095)
[#13106: 'Silo scaling' by Lumipharon at commit 88aa066a4d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13106)
[#13132: 'gun appearance flags' by tyeagg at commit af4370098c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13132)
[#13136: 'Minimap improvement' by Lumipharon at commit c98605ab6a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13136)

Local commit: 125fa8ea7133dc23be9931ca89642a9de87e5ac6
Server tools version: 5.12.1

### Reproduction Steps

1. Check attached video, I don't even know what happened

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/dbd64ba5-7197-46d7-a3bf-580d12c82851

**Comment by ClosetedSkeletonGH** [comment]
Have had the same happening to me but 3 tiles out from the west. The area for these is way too large

**Comment by Lumipharon** [comment]
Not a bug, its intended. There are areas around all the doors that are cleared out to prevent them from getting trapped in. You uh, really shouldn't stand near a crash landing ship.

**Comment by chizzy376** [comment]
Absolutely outrageous claims, this is a completely unneccesary qdel

**Comment by Strayed-Raven** [comment]
God I wish marines could body block xenos.

**Comment by chizzy376** [comment]
> Not a bug, its intended. 

Absolutely not, there is no indicator. This is an issue, reopen this.

**Comment by TiviPlus** [comment]
Stop spamming notifs this is intended behaviour, whether it is good behaviour is unrelated to issue reports
