### ISSUE TITLE
Debris element creates a gorillion runtime issues

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#13144]
### Description

When turfs are 'replaced' by another turf, they're not actually replaced in the true sense, which means any existing element is there there. This means any changing of turfs tries to apply the debris element to something that always has it, causing issues at init, game start and whenever shuttles move.

### Test Merges

NA

### Reproduction Steps

NA

**Comment by TiviPlus** [comment]
CC @tyeagg

**Comment by ivanmixo** [comment]
Resolved in #13270
