### ISSUE TITLE
Xray rifle turning invisible 

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#13157]
### Description

basically if you link a X-ray laser rifle to a TX-powerpack it turns the gun invisible because it has no linked sprite basically making it go NULL.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21495](https://scrubby.melonmesa.com/round/21495)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [8c9ec5766d6abd96435409964344c5db1abd50cf](https://github.com/tgstation/TerraGov-Marine-Corps//commit/8c9ec5766d6abd96435409964344c5db1abd50cf)
The following pull requests are currently test merged:
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12995: 'Laser rework' by Lumipharon at commit b4a58b8906](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12995)
[#13095: 'Quickbuild Rework 2023' by RipGrayson at commit 4ce7da1f1f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13095)
[#13106: 'Silo scaling' by Lumipharon at commit 88aa066a4d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13106)
[#13132: 'gun appearance flags' by tyeagg at commit af4370098c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13132)
[#13136: 'Minimap improvement' by Lumipharon at commit c1c72870af](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13136)

Local commit: 57eb7529e96995563b8d4ddcd22389cb5a29e66d
Server tools version: 5.12.1

### Reproduction Steps

grab x-ray laser rifle
attach to TX powerpack
magic gun

**Comment by Lumipharon** [comment]
fixed
