### ISSUE TITLE
Turning auto unload off on rocket launchers gives you infinite ammo

### ISSUE THREAD

**Issue by prrrki** [tgstation/TerraGov-Marine-Corps#13176]
### Description

By turning off automatic unload, the rocket stays in when you fire it, and it seems to not change into a consumed one. Thus, you can unload the rocket manually and use it again as if it was never fired.

### Test Merges

[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12995: 'Laser rework' by Lumipharon at commit b4a58b8906](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12995)
[#13095: 'Quickbuild Rework 2023' by RipGrayson at commit 4ce7da1f1f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13095)
[#13106: 'Silo scaling' by Lumipharon at commit 88aa066a4d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13106)
[#13136: 'Minimap improvement' by Lumipharon at commit c1c72870af](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13136)
[#13155: 'pride month special' by tyeagg at commit 403ec53387](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13155)

### Reproduction Steps

1. get any rocket launcher that ejects shells when used
2. turn off automatic unload
3. shoot the rocket
4. unload the rocket, which is now unspent
5. put the rocket back in
6. you can now use the same rocket again

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/77093430/35029b0e-fad6-4d2e-903a-39aeda0441b5

**Comment by Lumipharon** [comment]
fixed
