### ISSUE TITLE
PO - Dropship Control Bubble Access Issue

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#1318]
As a Pilot you cannot access Dropship Control area in the hangar which kind of misses the point if you are supposed to control a dropship and its not Shipside, leaving that you have to take a long route around the ship to top deck to reach CIC and then call the ship back.

**Comment by DominikPanic** [comment]
@Alterist

**Comment by Rohesie** [comment]
Access should be defined in code, not map.

**Comment by Alterist** [comment]
> Access should be defined in code, not map.
Time for a massive map edit then, as nearly every door on the theseus has it's access varedited

**Comment by Rohesie** [comment]
Yep, we are doing small changes, one at a time, but in the long run it's one big change.
