### ISSUE TITLE
If you hold alt while clicking on your gun, it enables saftey

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#13227]
### Description

If you are holding alt while clicking on your gun, it enables saftey. There is 0 way to disable this nor do I believe its intended as saftey is widely unused.

This has been why saftey gets set at what seemed like random intervals

### Test Merges

Round ID: [21627](https://scrubby.melonmesa.com/round/21627)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [57f8e7e6a181f55479d7e05e1136a82e9435aa75](https://github.com/tgstation/TerraGov-Marine-Corps//commit/57f8e7e6a181f55479d7e05e1136a82e9435aa75)
The following pull requests are currently test merged:
[#13106: 'Silo scaling' by Lumipharon at commit 88aa066a4d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13106)
[#13136: 'Minimap improvement' by Lumipharon at commit 491112e1b8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13136)
[#13173: 'Quickbuild Rework' by RikuTheKiller at commit 6aee878fdd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13173)
[#13145: 'new crosshair and mouse icons' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#12927: 'Flamethrower Rework 2' by tyeagg at commit cdf4353a20](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12927)

Local commit: 1004950bfc627426fcd26220076aa3d530007d82
Server tools version: 5.12.1

### Reproduction Steps

1. grab gun
2. hold alt and click on it
3. notice a popup for saftey being set

**Comment by TellyLsc** [comment]
That's the original way to toggle-safety (outside of the toggle-safety verb) from CM, it's not a bug, if you want to remove attachment you need an empty active hand and alt click the gun instead of the gun on active hand.

**Comment by isotope436** [comment]
this is not a bug

**Comment by ivanmixo** [comment]
Not a bug, make a pr to disable this if its a huge issue
