### ISSUE TITLE
Xenos can queue up multiple miner slashes

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#13235]
### Description

You can save more than 50% of your time by spamming LMB.

The marine equivalent of this (Spamming resist to queue up multiple removals of senti stacks) was removed as that was a bug, so I assume this is too.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21645](https://scrubby.melonmesa.com/round/21645)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [96e9fa1e680e04275d188cfc34ff440e19dc42b7](https://github.com/tgstation/TerraGov-Marine-Corps//commit/96e9fa1e680e04275d188cfc34ff440e19dc42b7)
The following pull requests are currently test merged:
[#13106: 'Silo scaling' by Lumipharon at commit 88aa066a4d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13106)
[#13136: 'Minimap improvement' by Lumipharon at commit 491112e1b8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13136)
[#13173: 'Quickbuild Rework' by RikuTheKiller at commit 6aee878fdd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13173)
[#13145: 'new crosshair and mouse icons' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#12927: 'Flamethrower Rework 2' by tyeagg at commit cdf4353a20](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12927)
[#13170: 'More immersive caves' by Lumipharon at commit d8aee41849](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13170)
[#13214: 'Probably fixes the lobby runtimes' by ivanmixo at commit 98c29b59e3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13214)

Local commit: a91d26dcf1b2aef65475de1d8b74e8bc1c21f0a7
Server tools version: 5.12.1

### Reproduction Steps

1. Spam left click as xeno on a fixed miner
2. Magically destroy it faster for some reason

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/c4ab265b-4b4a-4869-b6a0-83fe1f8264b8

**Comment by ivanmixo** [comment]
Not a bug
