### ISSUE TITLE
No Underwear

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#13257]
### Description

I set my gender to object and expected...well okay I had no expectations and my expectations were still not met. Setting gender to 'other' or 'object' causes you to spawn with no underwear. Not a major issue. Probably related to #12361
Also it defaults genders of other and object to male, visibly. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21681](https://scrubby.melonmesa.com/round/21681)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [3eccd33558707a7c5d82719c492fa16b39a1f2e2](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3eccd33558707a7c5d82719c492fa16b39a1f2e2)
The following pull requests are currently test merged:
[#13173: 'Quickbuild Rework' by RikuTheKiller at commit 6aee878fdd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13173)
[#13145: 'new crosshair ' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#13170: 'More immersive caves' by Lumipharon at commit d8aee41849](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13170)
[#13239: 'Buffs FUN dramatically' by Lumipharon at commit 624966389f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13239)

Local commit: f833b3e19d4ec83d56de9bedb5f12eb144f7b734
Server tools version: 5.12.1

### Reproduction Steps

1. Character slot
2. Set gender to other or object. 
3. Go Commando
4. Let it all hang out
5. Air it out like you're at one of those weird festivals

**Comment by SilencedMP5A5** [comment]
feature
