### ISSUE TITLE
Jumping breaks rouny agility

### ISSUE THREAD

**Issue by DiscordWizard** [tgstation/TerraGov-Marine-Corps#13326]
### Description

I jumped once because I accidentally binded the jump key to my hide key, and after doing a boune I was unable to go under tables or over window frames normally anymore. Respawning me as a new rouny fixed this issue, but jumping broke it again.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21787](https://scrubby.melonmesa.com/round/21787)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [d3ddd6f176986a1c674567083f9031f323ecf2fd](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d3ddd6f176986a1c674567083f9031f323ecf2fd)
The following pull requests are currently test merged:
[#13145: 'new crosshair ' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#13170: 'More immersive caves' by Lumipharon at commit d8aee41849](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13170)
[#13226: 'Primo bull loses speed upon direction change mid charge' by ivanmixo at commit 4b91d30def](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13226)
[#13258: 'Pillar of Spring Summer 2023 Remodel' by novaepee at commit 53379a37c3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13258)
[#13233: 'Lagmoor Digsite© 2: Electric Boogaloo | Minor Map Changes' by Overdrive659 at commit 78d38c0b2f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13233)
[#13305: 'cooler cooler explosions now using particles' by tyeagg at commit 6ac15dc465](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13305)
[#13318: 'HYPERSCALE RETURNS!' by hyper2snyper at commit 38b8b12764](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13318)

Local commit: c79bb66845aaf326ccaf2bd6c5cbb7af876fa2fc
Server tools version: 5.12.6

### Reproduction Steps

1. Become runner
2. Jump
3. Despair as most of your movement options are crippled

**Comment by Lumipharon** [comment]
fixed
