### ISSUE TITLE
Using leap as runner breaks agility

### ISSUE THREAD

**Issue by DiscordWizard** [tgstation/TerraGov-Marine-Corps#13345]
### Description

Using your pounce ability on runner breaks your agility, whether you land it or not. After use, only jumping seems to fix it, forcing you to do a little bounce on people you tackle to survive.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21822](https://scrubby.melonmesa.com/round/21822)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [8a07df765668b264a8a5a2f57614bab41dded0b1](https://github.com/tgstation/TerraGov-Marine-Corps//commit/8a07df765668b264a8a5a2f57614bab41dded0b1)
The following pull requests are currently test merged:
[#13145: 'new crosshair ' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#13226: 'Primo bull loses speed upon direction change mid charge' by ivanmixo at commit 4b91d30def](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13226)
[#13258: 'Pillar of Spring Summer 2023 Remodel' by novaepee at commit 53379a37c3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13258)
[#13233: 'Lagmoor Digsite© 2: Electric Boogaloo | Minor Map Changes' by Overdrive659 at commit 78d38c0b2f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13233)
[#13305: 'cooler cooler explosions now using particles' by tyeagg at commit f4e6ca4b1d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13305)
[#13318: 'HYPERSCALE RETURNS!' by hyper2snyper at commit 6dbdca8786](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13318)
[#13288: 'Refactors floor code' by Lumipharon at commit 57b6796652](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13288)
[#13304: 'Refactor flags_pass' by Lumipharon at commit 6023c941cd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13304)

Local commit: 96bacf36ed26a931c7b1703ad70bdaa8f38f6c6e
Server tools version: 5.12.6

### Reproduction Steps

1. Join as runner
2. Leap at anyone or anything
3. Watch as you can't go over tables and window frames anymore

**Comment by Lumipharon** [comment]
fixed
