### ISSUE TITLE
Can't throw items into the req pit anymore

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#13359]
### Description

You used to be able to throw items into the req hole a few days ago in order to remove clutter from req.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21858](https://scrubby.melonmesa.com/round/21858)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [d6faa6864257cbfcd8ae9cb84eda283bcf318c96](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d6faa6864257cbfcd8ae9cb84eda283bcf318c96)
The following pull requests are currently test merged:
[#13145: 'new crosshair ' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#13226: 'Primo bull loses speed upon direction change mid charge' by ivanmixo at commit 4b91d30def](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13226)
[#13258: 'Pillar of Spring Summer 2023 Remodel' by novaepee at commit 53379a37c3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13258)
[#13305: 'cooler cooler explosions now using particles' by tyeagg at commit d28caeac40](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13305)
[#13318: 'HYPERSCALE RETURNS!' by hyper2snyper at commit a77061c7da](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13318)
[#13304: 'Refactor flags_pass' by Lumipharon at commit 058f077f82](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13304)

Local commit: d89e19878acb47d78faec24a0bc4505747878dc1
Server tools version: 5.12.6

### Reproduction Steps

1. Lower lift
2. Try to throw item in
3. can't

**Comment by Lumipharon** [comment]
fixed
