### ISSUE TITLE
General Circuit Board Issues

### ISSUE THREAD

**Issue by Isy232** [tgstation/TerraGov-Marine-Corps#1340]
When you use a multitool on a general circuit board and set it to APC and then use the multitool again to set it to none it turns into a circuit board (Makeshift PSU) which can no longer be changed. It also drops from your hand when you do this.

![circuit error 2](https://user-images.githubusercontent.com/41198990/56515142-3205e600-6505-11e9-9beb-809df07232da.png)

![Circuit Error](https://user-images.githubusercontent.com/41198990/56514743-1d751e00-6504-11e9-86b2-15368f2def92.png)
.

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1281
