### ISSUE TITLE
Terra Experimental cell field charger does not dispense its content

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#13402]
### Description

I want to recharge my Terra Experimental standard batteries from the charger, but the charger cannot vent

### Test Merges

[#13145: 'new crosshair ' by tyeagg at commit 896f172491](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13145)
[#13226: 'Primo bull loses speed upon direction change mid charge' by ivanmixo at commit 4b91d30def](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13226)
[#13123: 'Shrike primo rework - Psychic Vortex' by Scarlet-Oduko at commit 0697346eb6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13123)
[#13116: 'Adds an AI controllable powerloader drone' by RipGrayson at commit 4612cb2547](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13116)
[#13394: 'tile fix' by Lumipharon at commit fc115d16ab](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13394)

### Reproduction Steps

1. Put a Terra Experimental standard battery inside Terra Experimental cell field charger
2. Dispense Terra Experimental standard battery from Terra Experimental cell field charger
3. nada

**Comment by chizzy376** [comment]
You didn't wrench it down or it was in an area with no power.
