### ISSUE TITLE
Powerloader can't be repaired with welding tool

### ISSUE THREAD

**Issue by Altrezz** [tgstation/TerraGov-Marine-Corps#13405]
### Description

Let me repair it like Mech can be repaired.

### Test Merges

AGLS?

### Reproduction Steps

1. Damage powerloader
2. Pick up Welding tool
3. Put on your welding goggles/mask
4. Be disappointed

### Screenshots

![tmbrwlf](https://github.com/tgstation/TerraGov-Marine-Corps/assets/138340169/b4bf44ef-8b25-4d82-b1a0-2ca67b0ce571)

**Comment by lbnesquik** [comment]
Confirmed. 
BYOND Version: 515.1632
Server revision compiled on: 2024-03-14
Master commit: [c6007d9da747cbbdf557a2c195733f9645452fb0](http://127.0.0.1:55776/commit/c6007d9da747cbbdf557a2c195733f9645452fb0)
