### ISSUE TITLE
Human Doctors spawn without clothes 

### ISSUE THREAD

**Issue by Redrover1760** [tgstation/TerraGov-Marine-Corps#13427]
### Description

That doctors spawn with clothes and lemoline bottles. It is likely based off a robotic PR.

### Test Merges

[#13226: 'Primo bull loses speed upon direction change mid charge' by ivanmixo at commit 4b91d30def](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13226)
[#13116: 'Adds an AI controllable powerloader drone' by RipGrayson at commit 4612cb2547](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13116)
[#13014: 'Queen bulwark' by TiviPlus at commit 75f6e04626](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13014)
[#13420: 'Fixes sentry guns' by ivanmixo at commit f290fdc0a6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13420)
[#13421: 'Plasteel cade fix' by Lumipharon at commit fffcfa9584](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13421)
[#12946: 'Plasma guns' by TiviPlus at commit d1a2e7c4c4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12946)
[#13425: 'Cave fixes' by Lumipharon at commit e50e0c8768](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13425)

### Reproduction Steps

1. Spawn as a medical doctor as a human
2. Awaken, you have half of the gear you expected, including no lemoline bottles, or medical related pouches.

### Screenshots

![What even happened](https://github.com/tgstation/TerraGov-Marine-Corps/assets/39284090/f5c5ed33-f094-459e-84da-e78d061b892f)

**Comment by Kapu1178** [comment]
What's the bug? This is clearly intended!
