### ISSUE TITLE
Recharging TE batteries love disappearing

### ISSUE THREAD

**Issue by veterath** [tgstation/TerraGov-Marine-Corps#13451]
### Description

When the recharging battery ejects from the gun via you taking it out or it running out of ammo, it will turn invisible when manually taken out and flat out deleted when ejected via lack of ammo.

### Test Merges

The following pull requests are currently test merged:
[#13123: 'Shrike primo rework - Psychic Vortex' by Scarlet-Oduko at commit 50e2038c96](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13123)

### Reproduction Steps

No clue, sorry.

**Comment by Lumipharon** [comment]
Can't reproduce at all
