### ISSUE TITLE
Dropship camera bug

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1346]
## Testmerges:

None

## Reproduction:

There's only 1 camera avaliable in dropship camera controls. Not sure if this is mapping or code issue.

Alamo - 
![изображение](https://user-images.githubusercontent.com/34478337/56600602-bf2e6500-6601-11e9-82eb-63c5cb5306ef.png)

Normandy - 
![изображение](https://user-images.githubusercontent.com/34478337/56600614-c6ee0980-6601-11e9-8a49-a2c2183ca669.png)

**Comment by Rohesie** [comment]
Mapping issue, they share `c_tag` (probably unset, thus `null`). Each should have a unique one.

**Comment by Rohesie** [comment]
They seem to have the same `c_tag`
Possibly a race condition in `/obj/machinery/camera/autoname/New()`
