### ISSUE TITLE
Ghosts with toggle darkness doesn't show other ghosts

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#1347]
## Testmerges:

Round ID: 349
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 9181d475a698fbc68f97695ec1e551095f8d0dd8
The following pull requests are currently test merged:
#1334: 'Removes neuro for queen, replaces by sticky.' by Ketrai at commit f247848544
#1335: 'Prison Fix/Edit' by Alterist at commit 3767eff0c2
#1336: 'Fixes #1318 Hanger Access' by Alterist at commit 24b19530c5
#1338: 'updated order talk sprites, changed focus to be a crosshair instead of !' by Jalordon at commit accc06e6ef
#1312: 'Add automatic takeover for SSD xenos' by psykzz at commit 8135abe860
#1319: 'Fixes another runtime' by DominikPanic at commit e8a4287770
#1315: 'Fixes possible runtimes for people loading in too fast' by DominikPanic at commit 7df2531a2f
#1316: 'Fixes stack recipes on most floor turfs' by DominikPanic at commit 5eb56a5f6d
#1310: 'Made the xeno queen locator more consistent' by Ghommie at commit 750fd4dfc2
#1306: 'Fixes synths being affected by defiler stings.' by Ghommie at commit 85c2135561
#1339: 'Refactors languages to the /tg/ standard' by DominikPanic at commit 83bdb387ff
#1343: 'Moves boiler smoke set up away from New()' by Ghommie at commit d25d97d7ec
#1342: 'Cuter help intents' by grinkgo at commit d08887c559

## Reproduction:

Ghost, then toggle darkness. You can't see other ghosts.

**Comment by DominikPanic** [comment]
It's not a bug but a feature unfortuantely.

**Comment by Zostroll** [comment]
It is a bug.

**Comment by DominikPanic** [comment]
It actually is intended by the code, whether it's  desirable is another thing though.

**Comment by Ketrai** [comment]
Ideally both are seperate toggles.

**Comment by Rohesie** [comment]
It is an ancient bug, so to speak. It will take a bit to fix it.

**Comment by DominikPanic** [comment]
It is not a bug.

**Comment by Rohesie** [comment]
Fair enough, this is a feature we don't really have.
