### ISSUE TITLE
Gun Cabinets have no open sprite

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#13486]
### Description

You open them and their sprite doesn't change, it stays closed visually.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22171](https://scrubby.melonmesa.com/round/22171)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [7fc0c02171373a3bd088e69d2ded600035f565c2](https://github.com/tgstation/TerraGov-Marine-Corps//commit/7fc0c02171373a3bd088e69d2ded600035f565c2)
The following pull requests are currently test merged:
[#13123: 'Shrike primo rework - Psychic Vortex' by Scarlet-Oduko at commit 50e2038c96](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13123)
[#13409: 'The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)' by XSlayer300 at commit d66e525e4b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13409)

Local commit: dea825765387f76277563e8176ebb22e1a2d940b
Server tools version: 5.12.7

### Reproduction Steps

1. Open gun cabinet

**Comment by coldironwarrior** [comment]
fixed
