### ISSUE TITLE
Valk fracture stabilization remains even after valk module is removed

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#13493]
### Description

If you break a bone while using valk, then remove the valk, the broken bones are still stabilized after you put the armor back on, I'm unsure if you need to just take off the valk and it already works as I've only tested it with breaking a bone and THEN removing it.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22192](https://scrubby.melonmesa.com/round/22192)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [d0d0461690932ab49fd253c712b21e6a4f69d88f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d0d0461690932ab49fd253c712b21e6a4f69d88f)
The following pull requests are currently test merged:
[#13123: 'Shrike primo rework - Psychic Vortex' by Scarlet-Oduko at commit 50e2038c96](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13123)
[#13409: 'The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)' by XSlayer300 at commit 9bae97f5a6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13409)
[#13481: 'Update TGUI' by forestbbbbbbb at commit 7467bd248c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13481)

Local commit: a467b73a1786f7e82ab6baa84cac0ae699341652
Server tools version: 5.13.2

### Reproduction Steps

1. Attach valk to armor
2. Wear armor
3. (might be optional) break a bone
4. take off armor and remove valk
5. put armor back on
6. bones are still stabilized

### Screenshots

https://streamable.com/pkzp93
(will expire in 2 days)

**Comment by Texicos** [comment]
3 years it took them to realize
