### ISSUE TITLE
People who set DNR show up on minimap as revivable

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#13541]
### Description

whichever PR fixed suicides showing up as revivable caused this.

im 99% sure all DNR's show up as revivable until they become "unrevivable" from the 5 minutes waits as it is more often than not now that a revivable body is not actually revivable.

### Test Merges

Round ID: [22277](https://scrubby.melonmesa.com/round/22277)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [c489d3fe69bba1ef821bbd819451d1d1096c3bbc](https://github.com/tgstation/TerraGov-Marine-Corps//commit/c489d3fe69bba1ef821bbd819451d1d1096c3bbc)
The following pull requests are currently test merged:
[#13409: 'The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)' by XSlayer300 at commit 9bae97f5a6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13409)
[#13014: 'Queen bulwark' by TiviPlus at commit 75f6e04626](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13014)
[#13524: 'Revert "Purges some dead throw code"' by Lumipharon at commit 00a1d5d09b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13524)

### Reproduction Steps

1. Be a human with a headset
2. Die through non-suicide action
3. Respawn as something else (Valhalla mob, xeno, anything else...?)
4. Outside observers will see your mob as revivable on the tacmap until the full 5 minute DNR timer has elapsed (longer if cocooned)

alternatively

1. rescue a revivable body on the minimap
2. go to defib them
3. notice as it says theyve set DNR
4. die because you were busy rescuing a DNR body

**Comment by Lumipharon** [comment]
Yeah I've heard of this bug but have yet to actually see it. I need the specific circumstances under which someone is showing on the map incorrectly (easier for admins to check)

**Comment by coldironwarrior** [comment]
More specific steps in #13623
