### ISSUE TITLE
entering into the robotic cradle has a chance to qdelete mob occupants

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13560]
### Description

entering into the robotic cradle as a robot seeking to fix integrity damage will sometimes result in the mob occupant being qdeleted.

unsure of what causes one to become deleted versus not.

discord convo initially reporting the issue https://discord.com/channels/498569646014857217/504094319075131402/1131740068789362799

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22357](https://scrubby.melonmesa.com/round/22357)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [8f501b9154e3f24694fef25423e6a03d52ff89a2](https://github.com/tgstation/TerraGov-Marine-Corps//commit/8f501b9154e3f24694fef25423e6a03d52ff89a2)
The following pull requests are currently test merged:
[#13409: 'The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)' by XSlayer300 at commit 9bae97f5a6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13409)
[#13504: 'TTS updates: Xeno TTS, new robo/vending voice version, pitch settings, etc' by TiviPlus at commit e537749333](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13504)
[#13426: 'Adds a HUD text timer for both hive collapse and nuke' by Arturlang at commit e26d1ba018](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13426)
[#13515: 'Adds 2 new tadpole models' by XANAv2 at commit d98aa86a61](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13014: 'Queen bulwark' by TiviPlus at commit 75f6e04626](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13014)

Local commit: 175171b556b7acb29624232806cc0e5dc7b890a0
Server tools version: 5.13.2

### Reproduction Steps

1. be robot
2. get psydrained or cocooned
3. gain integrity loss
4. be revived through defibrillation
5. go shipside to fix integrity loss by entering the robotic cradle
6. enter into the cradle
7. you are qdel'ted
8. have others come try and help remove you by right click > eject occupant on the cradle
9. they eject nothing and receive the error that the "patient has expired"
10. also the cradle becomes permanently unusable for the round

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/d7b07789-4b70-485b-b8f5-e84bc5d45475

**Comment by Lumipharon** [comment]
should be fixed
