### ISSUE TITLE
entering the autodoc as a delimbed robot with some damage causes you to become stuck in the autodoc as it loops through brute damage repair post-limb replacement

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13576]
### Description

i figured that getting in the autodoc when it's on automatic mode as a robot to get a limb replaced would replace the limb, do any additional damage fixing procedure, then eject me.

what i got instead was a limb replacement, and then perpetually stuck in the autodoc while it ran through the process of trying to do damage fixing while never repairing the damage, and i had to be ejected by someone else.

yeah, anyways, as for why this matters, i suppose:
robots currently can't sleep, so surgery isn't super viable for limb replacements.
you can pick between the autodoc or the cradle for a limb replacement. the cradle works fine at repairing damages and replacing limbs. the autodoc ends up perpetually stuck on the step of trying to fix damages. i would imagine if the cradle is meant as a flat replacement for the autodoc, that robots would be unable to use the autodoc at all. if this isn't the case and they're supposed to be interchangeable for surgical procedures, then i'd expect the autodoc to work at actually restoring damages on robot occupants.

this could pose an issue on lowpop rounds/crash/groundside medbays specifically, as there's no way for a robot to exit the autodoc in such a scenario without outside help, and i don't think it'd be really intuitive to most players that you'd have to be 100% health BEFORE you can enter and use the autodoc for limb replacement, lest you wind up stuck.

### Test Merges

BYOND Version: 514.1589
Server revision compiled on: 2023-07-25
Master commit: [c194d42f06dde4bd91b15f23eee2e6b0b602060c](http://127.0.0.1:51517/commit/c194d42f06dde4bd91b15f23eee2e6b0b602060c)
Local commit: 7466c82956112590554f98628818cd497d422462

### Reproduction Steps

1. be a robot
2. get delimbed and acquire damage (tested with brute specifically)
3. go to an autodoc to get your limb replaced
4. get in the autodoc while it is set to automatic
5. wait for limb replacement, which will work
6. wait as the autodoc then moves into repairing damage
7. keep waiting as it cycles through endless "The autodoc medical system whirrs and clicks as it stitches flesh together." messages
8. never get ejected until someone else comes by and can eject you
9. check health at the end of the process and notice that nothing was repaired

**Comment by Lumipharon** [comment]
should be fixed
