### ISSUE TITLE
Sometimes when plasmacutting walls on ship, you'll get an invisible but tangible wall after cutting one

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#13579]
### Description

After plasma cutting a wall on ship (seemingly at random, sometimes corners, sometimes inner walls) you will get a random wall that you have cut and turned into a plating, but still acts like a solid wall. (although if memory servers correct, shooting it doesnt damage it and you cant PC it again)

### Test Merges

The following pull requests are currently test merged:
[#13409: 'The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)' by XSlayer300 at commit 9bae97f5a6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13409)
[#13426: 'Adds a HUD text timer for both hive collapse and nuke' by Arturlang at commit 5f28c76d1d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13426)
[#13515: 'Adds 2 new tadpole models' by XANAv2 at commit d98aa86a61](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13566: 'Lawanka Outpost' by Barnet2 at commit caf133f50f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13566)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22381](https://scrubby.melonmesa.com/round/22381)
BYOND Version: 515.1608
Server revision compiled on: 
Master commit: [5fac8559677775d813fe94d457b3680a47738f09](https://github.com/tgstation/TerraGov-Marine-Corps//commit/5fac8559677775d813fe94d457b3680a47738f09)
The following pull requests are currently test merged:
[#13409: 'The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)' by XSlayer300 at commit 9bae97f5a6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13409)
[#13426: 'Adds a HUD text timer for both hive collapse and nuke' by Arturlang at commit 5f28c76d1d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13426)
[#13515: 'Adds 2 new tadpole models' by XANAv2 at commit d98aa86a61](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13566: 'Lawanka Outpost' by Barnet2 at commit caf133f50f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13566)

Local commit: e844ee2d1a5c2b2fff7d809f27303fe5300ab48a
Server tools version: 5.13.2

### Reproduction Steps

1. Go to POS (although im 90% sure it happens on more ships)
2. Start PC'ing walls down around prep (although its happened in many more locations)
3. notice as you eventually hit a wall that just becomes an invisible but solid wall after being cut

**Comment by ClosetedSkeletonGH** [comment]
just replicated last round with the wall that has the APC on it in PoS SD, except it was shot down with guns, not using a PC

**Comment by ivanmixo** [comment]
There definitely is something fuck with walls shipside. Admin deletion sometimes fails for some weird reason. Definitely needs to be looked into.
