### ISSUE TITLE
Tunnels broken on Ice Colony

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1360]
## Testmerges:

Round ID: 354
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 4f97e3ffba2c73cf2303e5470151bec6a2b8407c
The following pull requests are currently test merged:
#1146: 'Hunter and Warrior Balance Tweak' by Surrealaser at commit 2f16071846
#1334: 'Removes neuro for queen, replaces by sticky.' by Ketrai at commit d535067c17
#1336: 'Fixes #1318 Hanger Access' by Alterist at commit 1c2d8783a1
#1338: 'updated order talk sprites, changed focus to be a crosshair instead of !' by Jalordon at commit accc06e6ef
#1319: 'Fixes another runtime' by DominikPanic at commit e8a4287770
#1315: 'Fixes possible runtimes for people loading in too fast' by DominikPanic at commit 7df2531a2f
#1316: 'Fixes stack recipes on most floor turfs' by DominikPanic at commit 5eb56a5f6d
#1306: 'Fixes synths being affected by defiler stings.' by Ghommie at commit ab76f35097
#1339: 'Refactors languages to the /tg/ standard' by DominikPanic at commit 81a61da2b5
#1343: 'Moves boiler smoke set up away from New()' by Ghommie at commit d25d97d7ec
#1355: 'Adds sprites for different nade boxes' by MoXuT0 at commit 65ca398686
#1352: 'Fixes powerpack inhand icon' by MoXuT0 at commit a15eb0f09a
#1351: 'Add more stats for start of round observers' by psykzz at commit 0beab33239

## Reproduction:

![tunnel_snake](https://user-images.githubusercontent.com/34478337/56691899-a9946a80-66e9-11e9-86d8-3e1218829f41.png)

**Comment by DominikPanic** [comment]
This is a mapping issue as other maps work @Alterist
