### ISSUE TITLE
unlimited stam

### ISSUE THREAD

**Issue by isotope436** [tgstation/TerraGov-Marine-Corps#13609]
### Description

unable to figure out whats causing it (however it happens whenever i leave medbay entering via evac [dunno if evac is the cause]) but for some odd reason stamina just randomly stops draining getting pounced attacked killed or sprite reset doesnt fix it and nothing medical wise like synap effects it iv had it happen 4 times now (playing the beta version of byond) and still havent figure out whats causing it.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22407](https://scrubby.melonmesa.com/round/22407)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [18234ea39061e24d73ad1f4af79578c7c8b9f6b0](https://github.com/tgstation/TerraGov-Marine-Corps//commit/18234ea39061e24d73ad1f4af79578c7c8b9f6b0)
The following pull requests are currently test merged:
[#13426: 'Adds a HUD text timer for both hive collapse and nuke' by Arturlang at commit 5920d2033d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13426)
[#13515: 'Adds 2 new tadpole models' by XANAv2 at commit d98aa86a61](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13566: 'Lawanka Outpost' by Barnet2 at commit 954a509008](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13566)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit db08a8f1ef](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13594: 'Normalises stagger/slowdown recovery back to previous values' by ivanmixo at commit f87f775631](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13594)

Local commit: 177cac2cf82510acca49171cc17352cf9e1acda1
Server tools version: 5.13.4

(might be off since it hasnt happened this round)

### Reproduction Steps

unaware

**Comment by coldironwarrior** [comment]
Fixed by #13611
