### ISSUE TITLE
Cannot change underwear

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#13614]
### Description

my immersion

I want bra and panties, but instead I get funny the grey shirt and brief.

### Test Merges

[#13426: 'Adds a HUD text timer for both hive collapse and nuke' by Arturlang at commit 5920d2033d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13426)
[#13515: 'Adds 2 new tadpole models' by XANAv2 at commit d98aa86a61](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13566: 'Lawanka Outpost' by Barnet2 at commit 954a509008](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13566)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit db08a8f1ef](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13594: 'Normalises stagger/slowdown recovery back to previous values' by ivanmixo at commit f87f775631](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13594)

### Reproduction Steps

1. Choose bra and panties
2. Spawn
3. Get not bra and panties

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/2e83ca4e-04c7-4c1a-b977-50d098af1927

**Comment by lbnesquik** [comment]
Did you use to be able to? Because if yes, that might have been my PR breaking it.

**Comment by ivanmixo** [comment]
Done in the revert
