### ISSUE TITLE
Getting trailblazed as hivemind instant kills you 

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#13635]
### Description

This one was pretty hilarious, its reproduction steps will make it clear since theres no other way to describe it other than them.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22460](https://scrubby.melonmesa.com/round/22460)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [692448ad6aefba23611c274b6b68293ccaaa740e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/692448ad6aefba23611c274b6b68293ccaaa740e)
The following pull requests are currently test merged:
[#13426: 'Adds a HUD text timer for both hive collapse and nuke' by Arturlang at commit eaacb35297](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13426)
[#13515: 'Adds 2 new tadpole models' by XANAv2 at commit 314c2a0a18](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13566: 'Lawanka Outpost' by Barnet2 at commit 7aafde85d0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13566)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 12643528fa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13594: 'Normalises stagger/slowdown recovery back to previous values' by ivanmixo at commit f87f775631](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13594)
[#13123: 'Shrike primo rework - Psychic Vortex' by Scarlet-Oduko at commit 9c0ec8d6a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13123)
[#13483: 'Adds SG-62 Target Rifle, a new SG gun with an underbarreled spotting rifle. MK2' by Pariah919 at commit 0426e338ef](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13483)
[#13627: 'Fix orbit menu' by TiviPlus at commit 49ed42662a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13627)

Local commit: 5a6d0dd4ee74bc87336a695aa7e24140bfeadcc4
Server tools version: 5.13.4

### Reproduction Steps

1. Be hivemind
2. Get a trailblazer nade stuck you 
3. As soon as it goes off, because of your contact with fire, you and the connected trailblazer are teleported to your core
4. because of the fire, your core is nearly instantly destroyed along with any other structure you go over
5. See bug as you instantly die and laugh your ass off

**Comment by coldironwarrior** [comment]
fixed by #13796?
