### ISSUE TITLE
Theseus mapping issues

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1363]
## Testmerges:

None.

### I'll just list every known issue and will continue to add more if I find them.

Shutters are poddoors have broken dirs. These are not only instances.

![dir](https://user-images.githubusercontent.com/34478337/56695636-30e5dc00-66f2-11e9-82c9-3ed7610cb63d.png)
![moredir](https://user-images.githubusercontent.com/34478337/56695678-43f8ac00-66f2-11e9-88b0-ba9ce8eb3a92.png)

Captain's mess and field commander's mess are empty.

![cap](https://user-images.githubusercontent.com/34478337/56695748-71ddf080-66f2-11e9-8903-ae9b093f038f.png)
![fc](https://user-images.githubusercontent.com/34478337/56695756-799d9500-66f2-11e9-88b2-bde63eb95e49.png)

Cameras have also their dir fucked up. Same shit, not only instances.

![raz](https://user-images.githubusercontent.com/34478337/56695781-8c17ce80-66f2-11e9-8f43-b97f00150610.png)
![dva](https://user-images.githubusercontent.com/34478337/56695799-9508a000-66f2-11e9-8477-b9f8a5642fb2.png)

Random decal in hangar below crate.

![decal](https://user-images.githubusercontent.com/34478337/56695867-cbdeb600-66f2-11e9-9e04-dee659ba735a.png)

Also hangar.

![ripley](https://user-images.githubusercontent.com/34478337/56695920-f597dd00-66f2-11e9-8be4-398d84d0e350.png)

And there's this guy. Random sink in hallway above bar.

![boi](https://user-images.githubusercontent.com/34478337/56695940-05afbc80-66f3-11e9-8b4b-7117370fd697.png)

**Comment by Rohesie** [comment]
Thanks, this is very useful.
