### ISSUE TITLE
SOM doesn't have any underwears

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#13634]
### Description

Spawn in for HvH as a human, but no more underwear.

### Test Merges

#13426
[Adds a HUD text timer for both hive collapse and nuke](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13426) by [@Arturlang](https://github.com/Arturlang)
Commit: [eaacb35](https://github.com/tgstation/TerraGov-Marine-Corps/commit/eaacb352971d2ef3687e201fb104c9b80faec8f7)
#13515
[Adds 2 new tadpole models](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13515) by [@XANAv2](https://github.com/XANAv2)
Commit: [314c2a0](https://github.com/tgstation/TerraGov-Marine-Corps/commit/314c2a0a1813903d42ad9bb4d3b17dc5a139e8aa)
#13566
[Lawanka Outpost](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13566) by [@Barnet2](https://github.com/Barnet2)
Commit: [7aafde8](https://github.com/tgstation/TerraGov-Marine-Corps/commit/7aafde85d05a4f12223ed5d2da99b23efc909214)
#13546
[Port tg statpanel](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13546) by [@forestbbbbbbb](https://github.com/forestbbbbbbb)
Commit: [1264352](https://github.com/tgstation/TerraGov-Marine-Corps/commit/12643528fad70e659de8fcd8bdc653ac8f8d2b82)
#13594
[Normalises stagger/slowdown recovery back to previous values](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13594) by [@ivanmixo](https://github.com/ivanmixo)
Commit: [f87f775](https://github.com/tgstation/TerraGov-Marine-Corps/commit/f87f775631a4564b043fdde26d0a889b08aae751)
#13123
[Shrike primo rework - Psychic Vortex](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13123) by [@Scarlet-Oduko](https://github.com/Scarlet-Oduko)
Commit: [9c0ec8d](https://github.com/tgstation/TerraGov-Marine-Corps/commit/9c0ec8d6a010be72f76404d17d4e4048c5a5d440)
#13483
[Adds SG-62 Target Rifle, a new SG gun with an underbarreled spotting rifle. MK2](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13483) by [@Pariah919](https://github.com/Pariah919)
Commit: [0426e33](https://github.com/tgstation/TerraGov-Marine-Corps/commit/0426e338efa70fbbd7626a12c725892f68040a46)

### Reproduction Steps

1. round starts in any hvh mode
2. spawn in as SOM
3. no underwear

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/95d52053-30dd-4c4e-b246-7bfb1d0d9eeb

**Comment by Arctrooper8** [comment]
TGMC sex update
