### ISSUE TITLE
Chatting breaks at times

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#13642]
### Description

Per title.

I have an associated runtime:
`proc name: send speech (/mob/living/send_speech)`
`src: [MOB NAME OMITTED] (/mob/living/carbon/human)`
`src.loc: the dirt floor (108,83,2) (/turf/open/floor/plating/ground/snow/layer1)`
`call stack:`
`[MOB NAME OMITTED] (/mob/living/carbon/human): send speech("So polite.", 7, [MOB NAME OMITTED] (/mob/living/carbon/human), "default", /list (/list), /datum/language/common (/datum/language/common), null, "So polite.", /list (/list))`
`[MOB NAME OMITTED] (/mob/living/carbon/human): say("So polite.", null, /list (/list), 1, /datum/language/common (/datum/language/common), 0, null)`
`Speech Controller (/datum/controller/subsystem/speech_controller): process single say([MOB NAME OMITTED] (/mob/living/carbon/human), "so polite", "say_verb")`
`Speech Controller (/datum/controller/subsystem/speech_controller): fire(0)`
`Speech Controller (/datum/controller/subsystem/speech_controller): ignite(0)`
`Master (/datum/controller/master): RunQueue()`
`Master (/datum/controller/master): Loop(2)`
`Master (/datum/controller/master): StartProcessing(0)`
`(This error will now be silenced for 10 minutes)`

### Test Merges

#13426 
#13515
#13566
#13546
#13123
#13483
#13627 
#13604
#13622

### Reproduction Steps

Unknown thus far.

**Comment by Lumipharon** [comment]
should be fixed
