### ISSUE TITLE
ai cant use overwatch consoles to jump to a marine's vision

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13706]
### Description

title

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22610](https://scrubby.melonmesa.com/round/22610)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-04T20:31:52+00:00
Master commit: [36f369eb04775c14381a379b5222199ea66b6b3e](https://github.com/tgstation/TerraGov-Marine-Corps//commit/36f369eb04775c14381a379b5222199ea66b6b3e)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit 9ba79cc544](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13672: 'World Initialization Refactor' by ivanmixo at commit 29eaeda2df](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13672)
[#13191: 'New Tier 3 caste: Behemoth' by lKiseki at commit e902c68a0f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13191)

Local commit: 73f3bce3d685fc8d1660835d7eeb929ceb8ea9af
Server tools version: 5.13.4

### Reproduction Steps

1. be ai
2. log in to squad overwatch console
3. click button for name of marine on console to jump to camera view of them
4. you can't

**Comment by lbnesquik** [comment]
This is a correct issue, but you do have 2 ways to find some marine via cameras.
