### ISSUE TITLE
Railgunning is possible on crash

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#13743]
### Description

Crash, a gamemode where the shipside support is groundside and eliminates most shipside mechanics (OB's, Req, etc etc) has railgun

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22675](https://scrubby.melonmesa.com/round/22675)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-09T11:04:30+00:00
Master commit: [0d88ccd2c0a5e2305fdeea8f4fa45887c0e722eb](https://github.com/tgstation/TerraGov-Marine-Corps//commit/0d88ccd2c0a5e2305fdeea8f4fa45887c0e722eb)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit c40c569c8d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 9cb28c470c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13740: 'Dynamic sprite revert for SOM and ICC pouches' by Sanuki357 at commit 778a152668](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13740)

Local commit: 2bb99ba1328f319df46dcaa87e759e6380738d73
Server tools version: 5.13.4

### Reproduction Steps

1. Be a role that gets tac binos
2. Set your tac binos to railgun
3. Railgun on crash (MY IMMERSION)

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/e5a855a8-2139-4feb-92ca-7069832029e6)

**Comment by lbnesquik** [comment]
The real question is whether this is an issue or not. I don't think it was explicitly intended, but I am not sure if it is the biggest of issues?

**Comment by coldironwarrior** [comment]
closed by #14523
