### ISSUE TITLE
you can ride vehicles across space tiles

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13785]
### Description

you can ride vehicles across space tiles; including mechs
you maintain full control over movement when doing so

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22753](https://scrubby.melonmesa.com/round/22753)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-13T08:08:42+00:00
Master commit: [73af0539acdbc130ebfbae10d68e1c12374226ce](https://github.com/tgstation/TerraGov-Marine-Corps//commit/73af0539acdbc130ebfbae10d68e1c12374226ce)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit c1587b8f60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 1d5bc8ce60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13758: 'Fixes jobs not scaling if nobody readies up + fix a thing I broke' by ivanmixo at commit 47fc2dd7f7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13758)
[#13626: 'Slumbridge' by chizzy376 at commit 43748212ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)

Local commit: https://github.com/tgstation/TerraGov-Marine-Corps/commit/688034a1c452d411be6c5dd9506f8b21bd9c935e
Server tools version: 5.13.4

### Reproduction Steps

1. be marine
2. get in a vehicle
3. drive across space

**Comment by chizzy376** [comment]
This isn't limited to vehicles you can freely walk on space tiles as anyone and anything. Xeno, marine, ai droid, vehicle or not.

**Comment by coldironwarrior** [comment]
> This isn't limited to vehicles you can freely walk on space tiles as anyone and anything. Xeno, marine, ai droid, vehicle or not.

im aware.
this behavior seems unintuitive, hence bug report.

**Comment by coldironwarrior** [comment]
closed bc intentional
