### ISSUE TITLE
standing in a cold shower while having quick clot in you won't fix internal bleeding

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13788]
### Description

i was told it was a feature that you could take some quick clot and stand in under a cold shower to fix internal bleeding; i did this for 30 minutes but the internal bleeding never fixed

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22761](https://scrubby.melonmesa.com/round/22761)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-13T08:08:42+00:00
Master commit: [73af0539acdbc130ebfbae10d68e1c12374226ce](https://github.com/tgstation/TerraGov-Marine-Corps//commit/73af0539acdbc130ebfbae10d68e1c12374226ce)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit c1587b8f60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 1d5bc8ce60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13758: 'Fixes jobs not scaling if nobody readies up + fix a thing I broke' by ivanmixo at commit 47fc2dd7f7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13758)
[#13626: 'Slumbridge' by chizzy376 at commit 43748212ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)

Local commit: 688034a1c452d411be6c5dd9506f8b21bd9c935e
Server tools version: 5.13.4

### Reproduction Steps

1. have internal bleeding
2. wrench a showerhead so it is cold
3. take a quick clot pill
4. get under shower
5. stay there
6. check for internal bleeding and see that it continues to persist
7. repeat taking quick clot and various burn meds
8. keep checking for internal bleeding
9. notice you still have internal bleeding after a prolonged period of time

### Screenshots

i have like 22 minutes of video but the file is way too large to upload; this is a screenshot from the end of the 30 minutes where i tried this, partially empty pill bottles included 
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/1431a4ad-de18-47f2-be88-4d142eedd030)

**Comment by chizzy376** [comment]
You need to sleep while being cold

**Comment by coldironwarrior** [comment]
editing to reflect the actual issue, which is not that IB doesn't get fixed but rather that the scanner doesn't update for some reason !
