### ISSUE TITLE
TE powerpack can be used as fuel for volkite weapons

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#13781]
### Description

As title says. This means that a marine can pick up a som gun and get infinite ammo for it from the clothing vendor.

(This isn't "xope" when this issue is fixed I won't have to remove the VX32 charger spawn from slumbridge SOM base)

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22753](https://scrubby.melonmesa.com/round/22753)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-13T08:08:42+00:00
Master commit: [73af0539acdbc130ebfbae10d68e1c12374226ce](https://github.com/tgstation/TerraGov-Marine-Corps//commit/73af0539acdbc130ebfbae10d68e1c12374226ce)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit c1587b8f60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 1d5bc8ce60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13758: 'Fixes jobs not scaling if nobody readies up + fix a thing I broke' by ivanmixo at commit 47fc2dd7f7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13758)
[#13626: 'Slumbridge' by chizzy376 at commit 43748212ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)

Local commit: 688034a1c452d411be6c5dd9506f8b21bd9c935e
Server tools version: 5.13.4

### Reproduction Steps

1. Use a TE powerpack like you would on a laser gun but instead use it on a /obj/item/weapon/gun/energy/lasgun/lasrifle/volkite/charger/standard
2. You can use it despite the two technologies being completely different

**Comment by Looking4bros** [comment]
Did this get fixed? I wasn't able to recreate it in Valhalla or a test server. Only thing i can get it to do is charge their Volkite cells, which doesn't sound like the complaint.

**Comment by chizzy376** [comment]
This got fixed
