### ISSUE TITLE
boilers can shoot gas through the standard TAD windows

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13797]
### Description

boilers can shoot their gas globs through the standard TAD model window

it functions as dense for marines though

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22761](https://scrubby.melonmesa.com/round/22761)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-13T08:08:42+00:00
Master commit: [73af0539acdbc130ebfbae10d68e1c12374226ce](https://github.com/tgstation/TerraGov-Marine-Corps//commit/73af0539acdbc130ebfbae10d68e1c12374226ce)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit c1587b8f60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13546: 'Port tg statpanel' by forestbbbbbbb at commit 1d5bc8ce60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13546)
[#13758: 'Fixes jobs not scaling if nobody readies up + fix a thing I broke' by ivanmixo at commit 47fc2dd7f7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13758)
[#13626: 'Slumbridge' by chizzy376 at commit 43748212ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)

Local commit: https://github.com/tgstation/TerraGov-Marine-Corps/commit/688034a1c452d411be6c5dd9506f8b21bd9c935e
Server tools version: 5.13.4

### Reproduction Steps

1. be a boiler
2. see a standard tad model
3. stand in front of tad cockpit
4. store globule
5. root
6. bombard while aiming into the tad with a straight shot through the front window
7. observe

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/114c8900-a44d-4beb-a4ee-8de92e1be093)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/29965103/fc79922e-7adb-402b-a5e9-51f7dc242ff1)

**Comment by iforgotmeword** [comment]
Marines can also shoot pass them

**Comment by iforgotmeword** [comment]
Wait no “STILL” 
#12167
