### ISSUE TITLE
trying to place ID cards and dogtags on the shipside memorial no longer works

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#13806]
### Description

i hoped to be able to take a tag off a dead marine and place it on the memorial on the ship so that it would add their name to the memorial

no interaction happens and the tag stays in your hand. the memorial doesn't update or anything.

this has been broken for a while; at least since early june.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22799](https://scrubby.melonmesa.com/round/22799)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-15T08:03:29+00:00
Master commit: [5e28c93215e15791b89f57a3176a78a55a6e3c13](https://github.com/tgstation/TerraGov-Marine-Corps//commit/5e28c93215e15791b89f57a3176a78a55a6e3c13)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13308: 'New Xenomorph : Baneling' by Zar000 at commit c1587b8f60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13308)
[#13626: 'Slumbridge' by chizzy376 at commit 43748212ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)
[#13767: 'Scout ammo changes' by Lumipharon at commit 97965d4a3c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13767)
[#13799: 'Probably fixes AI biospam' by RipGrayson at commit 04a592b595](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13799)

Local commit: 13e1c9499b255dcb94f6db968ef03994c64786fd
Server tools version: 5.13.4

### Reproduction Steps

1. find permadead marine
2. remove their tag
3. take it to the shipside memorial slab
4. click the slab with the tag
5. nothing happens

**Comment by Lumipharon** [comment]
Caused by #12964 which made it impossible to retrieve the actual dogtag item, it never worked with the ID itself.

**Comment by ivanmixo** [comment]
The mast should be refactored to accept IDs
