### ISSUE TITLE
Invisible in EORD

### ISSUE THREAD

**Issue by MrTCo1** [tgstation/TerraGov-Marine-Corps#13833]
### Description

If you are in a thermal tarp before EORD starts, when you're teleported you remain invisible while being able to interact as if you weren't

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [22869](https://scrubby.melonmesa.com/round/22869)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-19T01:33:04+00:00
Master commit: [402b1e9e783f8beef3ab3ad14cc7f337252070f7](https://github.com/tgstation/TerraGov-Marine-Corps//commit/402b1e9e783f8beef3ab3ad14cc7f337252070f7)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13626: 'Slumbridge' by chizzy376 at commit 15fa90eca3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)
[#13801: 'Un-unfuns blood regen and adds more to it' by Sebbe9123 at commit 51103c845b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13801)
[#13191: 'New Tier 3 caste: Behemoth' by lKiseki at commit 030d18bf30](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13191)

Local commit: 1b60d64e41fd386a372e8c5fe95e2436fa22d123
Server tools version: 5.13.4

### Reproduction Steps

1. Enter thermal tarp prior to EORD
2. Wait to be teleported
3. You're now invisible, and able to interact if you weren't

### Screenshots

![image_2023-08-19_145211062](https://github.com/tgstation/TerraGov-Marine-Corps/assets/142560265/46ee11b3-4608-4426-a508-5e7a539e956a)

**Comment by Looking4bros** [comment]
This is essentially because when the player is forceMove'd from their position in the tarp, they are still in the list of things inside the tarp. I'm not sure how to make it check " if (player.loc != bodybag); open()
i don't know how words work.
