### ISSUE TITLE
Remove stealthjack

### ISSUE THREAD

**Issue by honorconner** [tgstation/TerraGov-Marine-Corps#13868]
You all know its stupid as hell.
Hijack should only be possible with all 3 disks corrupted

**Comment by honorconner** [comment]
alternatively hijack should have a 2-3 minute timer in between starting to hijack and the actual takeover so marines have a chance to actually retake the ship and not just immediately lose and be forced into a delaylien situaion because of a bald engineer, or bad sentry placement

**Comment by lbnesquik** [comment]
This is not a feature request board, soooo, it's probably going to get taken out back.

**Comment by Tailiik** [comment]
Cope

**Comment by ivanmixo** [comment]
no :)
