### ISSUE TITLE
OOC messages with emojis no longer send

### ISSUE THREAD

**Issue by chesse20** [tgstation/TerraGov-Marine-Corps#13871]
### Description

I tried to send OOC messages with the 💀 emoji. Instead nothing showed up in OOC. The 🐕 and 🧽 emojis also dont work so im assuming most if not all emojis dont work

### Test Merges

Round ID: [22960](https://scrubby.melonmesa.com/round/22960)
BYOND Version: 515.1610
Server revision compiled on: 2023-08-24T01:00:03+00:00
Master commit: [9f43d60792a593cd258e3fa241a2faab5d0b5aec](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9f43d60792a593cd258e3fa241a2faab5d0b5aec)
The following pull requests are currently test merged:
[#13515: 'Adds 2 new tadpole models updating: to make grief poles less griefy' by XANAv2 at commit e52d05bff0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13515)
[#13626: 'Slumbridge' by chizzy376 at commit ef51e983c1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13626)

Local commit: a9af8ca661938920f135b59b8c686afb02e762eb

### Reproduction Steps

1. Use the OOC verb or the gui version.
2. Use Windows+. to open up the emoji window
3. type the name of your favorite emoji and then click it
4. Emoji goes into the window where you are typing your message
5. Send Message
6. Check chat and your OOC message does not appear

**Comment by lbnesquik** [comment]
I have no trouble sending emoji via the method of typing them out. I'm not sure if direct emoji was ever really supported.
