### ISSUE TITLE
Minions and Spawners breaks the new xenomorph respawn que

### ISSUE THREAD

**Issue by Mechswordsman** [tgstation/TerraGov-Marine-Corps#13918]
### Description

If you build spawners, it will cause player xenos to not get respawns.  As in, there being 40+ living marines groundside in a round, with only 4 living, active player xenos, no larva, with two silos, and 9+ people in the xenomorph que for over ten minutes.

### Test Merges

The following pull requests are currently test merged:
[#13543: 'Personal statistics' by XElectricX at commit dfeee12246](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13543)
[#13615: 'Maturity Removal (Part of the Xeno Rework)' by Barnet2 at commit 1d532ff1ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13615)
[#13660: 'Nuke war spawn rework' by TiviPlus at commit 662dc4bdf5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13660)
[#13910: 'New Warcries: TGMC Edition' by XSlayer300 at commit 6cba28d8a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13910)
[#13914: 'TGS Arachne' by AzonStarfall at commit cbe6a6d15c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13914)

### Reproduction Steps

Build spawners in a game. Watch xeno larva gen become non existant.

**Comment by coldironwarrior** [comment]
fixed as #13660 was closed
