### ISSUE TITLE
DChat doesn't show ghost messages.

### ISSUE THREAD

**Issue by veterath** [tgstation/TerraGov-Marine-Corps#13929]
### Description

Title. Only happens on TGMC and not any other server

### Test Merges

#13543
[Personal statistics](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13543) by [@XElectricX](https://github.com/XElectricX)
Commit: [dfeee12](https://github.com/tgstation/TerraGov-Marine-Corps/commit/dfeee12246da54c5f5fed91cc715954199a52d8c)
#13910
[New Warcries: TGMC Edition](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13910) by [@XSlayer300](https://github.com/XSlayer300)
Commit: [6cba28d](https://github.com/tgstation/TerraGov-Marine-Corps/commit/6cba28d8a0a87c163d678fa5b6fa94c8f9bc411e)
#13914
[TGS Arachne](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13914) by [@AzonStarfall](https://github.com/AzonStarfall)
Commit: [f0707f0](https://github.com/tgstation/TerraGov-Marine-Corps/commit/f0707f0e6882360bc6d343feb3c96f12240d150d)
#13615
[Maturity Removal (Part of the Xeno Rework)](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13615) by [@Barnet2](https://github.com/Barnet2)
Commit: [b8e78e9](https://github.com/tgstation/TerraGov-Marine-Corps/commit/b8e78e95d9e0970f9b3091a148aec61d18a90922)
#13925
[Adds a xeno respawn timer](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13925) by [@Barnet2](https://github.com/Barnet2)
Commit: [e6305ba](https://github.com/tgstation/TerraGov-Marine-Corps/commit/e6305ba4017d57ff1726da6116fc112f79a1a148)

### Reproduction Steps

le shrug

**Comment by veterath** [comment]
I uh...i'm retarded

dont ask!

**Comment by coldironwarrior** [comment]
can't reproduce
