### ISSUE TITLE
Big Red: raditation sign not aligned

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#1396]
## Testmerges:

Round ID:  378 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 14b403925e683a7e2fe4d34e8698eec605a84b6b 
The following pull requests are currently test merged: 
#1386: 'Makes purrbation slightly less evil.' by DominikPanic at commit 2ff82918e6 
#1383: 'Fixes the take over admin verb' by DominikPanic at commit d2deeb8c08 
#1384: 'Fixes the fully_replace_character_name proc' by DominikPanic at commit bcca8e2584 
#1385: 'VV improvements: rotate, varedit updates, link to VV'd object' by DominikPanic at commit 0810db695e 
#1382: 'Fixes wounds overlays' by MoXuT0 at commit c2371311ad 
#1381: 'Auto-9 Magazine Fix' by InterroLouis at commit 0da5fe9f2e 
#1380: 'purges another reference to predaliens.' by Ghommie at commit 55db615ff7 
#1377: 'Buffing neuro smoke again just a very little.' by Ghommie at commit 964ada5325 
#1376: 'updates older beret sprites, gives the CSE superior welding googles.' by Ghommie at commit a8665ad9d5 
#1372: 'Refactor queen follow topics' by psykzz at commit a2729c2a9a 
#1373: 'Moves game preference verb to preferences' by psykzz at commit b2713b8b6f 
#1369: 'Updating and cleaning up reagents outside of chemistry_reagents.' by Ghommie at commit 991e968cc0 
#1371: 'Refactors /say code to /tg/ standard' by DominikPanic at commit c5c0d0e650 
#1328: 'Refactor screech into screech_act' by psykzz at commit d51de357e7 
#1364: 'Fixes APC's examine() and update_icon().' by Ghommie at commit 86f3a7b166 
#1367: 'Tweaks on xeno sting and larval growth serum.' by Rohesie at commit 10331c7a4b 
#1370: 'Resist time lowered, clean and refactor.' by Rohesie at commit f93a389e30 
#1365: 'Adds more directions to the ghost sprite.' by DominikPanic at commit b769cfd9f6 
#1374: 'Two new admin verbs: "Check Contents" and "Randomize Name"' by DominikPanic at commit 5462c0a3c1 
#1379: 'Adds more SDQL2 admin wrappers' by DominikPanic at commit f3593f4786 
#1388: 'Makes the chat loading smoother' by DominikPanic at commit 670b6ec879 

Local commit: 50daee578fa9280338e044996a0aee441d0db4ff 
Server tools version: /tg/station 13 Server v3.2.6.2 

## Reproduction:

Within the lambda lab anomoly lab

![image](https://user-images.githubusercontent.com/1134201/56855507-fe312300-693f-11e9-8058-d142e290f03f.png)

**Comment by DominikPanic** [comment]
All sings are like this most likely due to bad init or map placement
