### ISSUE TITLE
[BOUNTY] right clicking on helmet, suit, and webbing to take item out

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#13980]
Feature: title. Similar to how you can right click on pouch, backpack, and belt to get the right most item to retrieve it. Likely balance issue since it's removing one click from getting item from helmet, suit, and webbing.

Commission: $20.

Making this issue as par order from ivan: 
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/577f702c-ff28-47d5-9022-e92d950fb992)

Additional commission: $20 to alt+right click to retrieve the **LEFT most** item from belt, backpack, pouch, helmet, suit, and webbing. ADDITIONAL $20 to put in a new feature in light of alt+right click

New feature:
1) Have item on hand
2) See storage item sprite (belt, backpack, pouch, helmet, suit, or webbing)
3) Left click storage item sprite with item on hand to put item on **LEFT most** side of storage OR right click storage item with item on hand to put item on **RIGHT most** side

Not sure about the keybind for pulling out the left most side of storage from new feature. **Priority is right clicking on helmet, suit, and webbing to take item out.**

**Comment by spookydonut** [comment]
Not a bug report, see the template when you try to make a feature request:
> Feature requests are not handled in the repository. The best place to discuss these ideas would be on the #dev-general of the TGCM discord, or
this thread on /tg/station 13 forums: https://tgstation13.org/phpBB/viewtopic.php?f=65&t=20995
