### ISSUE TITLE
Bioscan Xeno Count Is Heavily Inaccurate

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#13991]
### Description

The xeno bioscan is supposed to have a somewhat small margin of error of 3, however it seems to currently be much higher than that.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23348](https://scrubby.melonmesa.com/round/23348)
BYOND Version: 515.1610
Server revision compiled on: 2023-09-18T20:39:16+00:00
Master commit: [fdd6daa281c6d680e6f380cf6d9eb986601f5324](https://github.com/tgstation/TerraGov-Marine-Corps//commit/fdd6daa281c6d680e6f380cf6d9eb986601f5324)
The following pull requests are currently test merged:
[#13914: 'TGS Arachne' by AzonStarfall at commit c4d9765d1c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13914)
[#12961: 'Adds puppeteer, a T2 xeno' by mc-oofert at commit c061a6e745](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12961)
[#13787: 'Adds a deployable spear trap, and a spike trap.' by Xander3359 at commit db8027992b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13787)
[#13963: 'Gun Smoke Particles' by tyeagg at commit 675a0e48a2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13963)
[#13965: 'Mostly redoes the CAS UI' by TiviPlus at commit 7f405181d9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13965)
[#13973: 'Fix xeno spawns not counting towards autobalance' by forestbbbbbbb at commit ac0027195a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13973)

Local commit: 8120783e9dbd10318b585309f37c8e8cd62925ba
Server tools version: 5.16.0

### Reproduction Steps

1. Have some xenos spawn in
2. Be an observer
3. Wait for the bioscan notice
4. See the report for how many xenos there are
5. Check the hive status
6. Notice there are not nearly as many xenos as reported

### Screenshots

![TerraGov Marine Corps 9_20_2023 2_52_37 PM](https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/b237981e-0769-4c37-a55e-5f882e33967a)

![TerraGov Marine Corps 9_20_2023 2_52_39 PM](https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/1f42a790-0e4e-4255-b7db-7bd433cd6045)

**Comment by Lumipharon** [comment]
it picks up minions as well.
