### ISSUE TITLE
Pepperballs affect rav

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#14041]
### Description

see title

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23474](https://scrubby.melonmesa.com/round/23474)
BYOND Version: 515.1610
Server revision compiled on: 2023-09-27T23:39:47+00:00
Master commit: [4b9f5d954c77672921c9b4014a97aa4bcb4c157f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/4b9f5d954c77672921c9b4014a97aa4bcb4c157f)
The following pull requests are currently test merged:
[#14024: 'Campaign part 2' by Lumipharon at commit 929645d3d9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)

Local commit: 6fe9e708ec864b0c3dd8198a0b3398945b202c81
Server tools version: 5.16.0

### Reproduction Steps

1. be rav
2. get shot by pepperball
3. fury gone
4. whiff endure because no fury
5. xope and xeethe

**Comment by dopamiin0** [comment]
Not a bug; pepperballs are intended to remove all resources, not just plasma.

**Comment by Xander3359** [comment]
Not a bug, please close as resolved.
