### ISSUE TITLE
the AGLS says it cant be rotated

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#14058]
### Description

title 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23520](https://scrubby.melonmesa.com/round/23520)
BYOND Version: 515.1610
Server revision compiled on: 2023-09-30T12:08:01+00:00
Master commit: [d15a99bb8f61fe31a58ca9347202f74cc1d46fff](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d15a99bb8f61fe31a58ca9347202f74cc1d46fff)
The following pull requests are currently test merged:
[#14024: 'Campaign part 2' by Lumipharon at commit 6a757c7805](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)
[#13989: 'Cleanup of device.dmi and items.dmi ' by Blundir at commit 500099e44e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13989)

Local commit: 9fd678038c065799db2f3e09e3170e5f1def7113
Server tools version: 5.16.0

### Reproduction Steps

1. Buy AGLS
2. set up AGLS
3. click to your right/left
4. gun rotates
5. create xope

**Comment by QualityVan** [comment]
Apparently this is an error with the desc not having been updated for changes on the PR that added the AGLS. It's supposed to be able to rotate, at least currently.

**Comment by Wirpy** [comment]
It's not supposed to be able to be rotated? Why?

**Comment by iforgotmeword** [comment]
It has 4X scope aka its off screen explosives spam letting it turn would make nearly impossible to group up and push a cades areas it also soft counters boilers

**Comment by yyzsong** [comment]
well here's the real issue then
