### ISSUE TITLE
opening and closing your minimap while in a pipe makes you unable to open the minimap again

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#14068]
### Description

broke minimap; thought i'd be able to see it in pipe or out of pipe.
i can open minimap in pipe once and close it, then i'm unable to see minimap at all after that.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23543](https://scrubby.melonmesa.com/round/23543)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-01T21:19:50+00:00
Master commit: [a831945c74989370a26b02a008b4bc24ce609074](https://github.com/tgstation/TerraGov-Marine-Corps//commit/a831945c74989370a26b02a008b4bc24ce609074)
The following pull requests are currently test merged:
[#14024: 'Campaign part 2' by Lumipharon at commit 545df1cea6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)
[#13989: 'Cleanup of device.dmi and items.dmi ' by Blundir at commit 500099e44e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13989)

Local commit: bc0497da45a899fae544f1e4706fc6c222795942
Server tools version: 5.16.0

### Reproduction Steps

1. be a xeno that can ventcrawl
2. ventcrawl
3. open minimap while in vent
4. close minimap while in vent
5. try to re-open minimap
6. emerge from vent and try to re-open minimap

**Comment by Lumipharon** [comment]
Should be fixed in the campaign pr now
