### ISSUE TITLE
acid on-tile as someone petrified by king ability still effects the person

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#14075]
### Description

title; thought petrify worked as an admin-invincibility thing to prevent all damage but i still see people screaming and reporting getting hurt by acid on-tile with them when they're petrified

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23566](https://scrubby.melonmesa.com/round/23566)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-03T03:55:10+00:00
Master commit: [27f760774ca84856bcd890adb62c6f532136f4a2](https://github.com/tgstation/TerraGov-Marine-Corps//commit/27f760774ca84856bcd890adb62c6f532136f4a2)
The following pull requests are currently test merged:
[#14024: 'Campaign part 2' by Lumipharon at commit 33fbe34e94](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)
[#14023: 'Adding multiple balance features in Gelida IV: Xenomorph Edition' by novaepee at commit bc8f5577a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14023)

Local commit: 488d959e5e5e9aca6602abed78643e58fbc28512
Server tools version: 5.16.0

### Reproduction Steps

1. be marine
2. get petrified by king
3. boiler, spitter, prae acid-spit on the tile you're on

**Comment by Lumipharon** [comment]
Are you sure? Petrify applies godmode so you don't take damage. Something will still cause emotes or red flashes etc on your sprite though, but you shouldn't actually get hurt.

**Comment by coldironwarrior** [comment]
probably just the audio cues, and havent seen anything to support since i opened. going to close.
