### ISSUE TITLE
valhalla spawns now have no access

### ISSUE THREAD

**Issue by DaTruRiZZoB** [tgstation/TerraGov-Marine-Corps#14072]
### Description

if you spawn as a role such as engineer you don't have access to that door

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23554](https://scrubby.melonmesa.com/round/23554)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-02T20:53:41+00:00
Master commit: [1012947e97c11f7a86c16ff70dd22749388d9c3f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/1012947e97c11f7a86c16ff70dd22749388d9c3f)
The following pull requests are currently test merged:
[#14024: 'Campaign part 2' by Lumipharon at commit 4e578c7a66](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)
[#14023: 'Adding multiple balance features in Gelida IV: Xenomorph Edition' by novaepee at commit bc8f5577a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14023)

Local commit: 8ceccadf71b3abbd191c0f7fa67d5a8c5e064b7e
Server tools version: 5.16.0

### Reproduction Steps

1. spawn as a job in valhalla
2. try to access your assigned vendors/door
3. cry

**Comment by RipGrayson** [comment]
I tried to replicate this yesterday and couldn't. All vendors and doors seemed to work fine.

**Comment by DaTruRiZZoB** [comment]
then this was fixed by a pr closing this
