### ISSUE TITLE
Dying As Baneling In Valhalla Causes Xeno Respawn Timer to Reset

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#14081]
### Description

Dying as a baneling in Valhalla without a pod using the detonate ability causes the xeno respawn timer to reset to 5 minutes.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23581](https://scrubby.melonmesa.com/round/23581)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-04T13:57:20+00:00
Master commit: [dc3e9e317f8739a881a079a9cfceb713483d552b](https://github.com/tgstation/TerraGov-Marine-Corps//commit/dc3e9e317f8739a881a079a9cfceb713483d552b)
The following pull requests are currently test merged:
[#14023: 'Adding multiple balance features in Gelida IV: Xenomorph Edition' by novaepee at commit bc8f5577a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14023)
[#13969: 'Adds roundstart heavy weapon rotation.' by Pariah919 at commit ac90767205](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13969)

Local commit: 43ce4ceee9962dccf7b39d0498a01b9b95ef59c2
Server tools version: 5.16.0

### Reproduction Steps

1. Go to xeno Valhalla
2. Become a baneling
3. Detonate without a pod
4. Notice your xeno respawn timer was reset.

**Comment by lbnesquik** [comment]
Baneling
