### ISSUE TITLE
Using tac vest causes decap while wearing headband

### ISSUE THREAD

**Issue by irRegularGuy646** [tgstation/TerraGov-Marine-Corps#14096]
### Description

headbands have decap protection. the tac vest isn't supposed to decap through decap protection.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23620](https://scrubby.melonmesa.com/round/23620)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-06T00:37:58+00:00
Master commit: [6acaa34439f2ae9713066d74768953f8ab109d44](https://github.com/tgstation/TerraGov-Marine-Corps//commit/6acaa34439f2ae9713066d74768953f8ab109d44)
The following pull requests are currently test merged:
[#14023: 'Adding multiple balance features in Gelida IV: Xenomorph Edition' by novaepee at commit bc8f5577a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14023)
[#13969: 'Adds roundstart heavy weapon rotation.' by Pariah919 at commit e0c2f8f076](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13969)
[#14024: 'Campaign part 2' by Lumipharon at commit bd6428bcb9](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)

Local commit: f6eaa9f59a8be8415d2ea23cd3386de0fa4bbeb3
Server tools version: 5.16.0

### Reproduction Steps

1. Wear a tac vest and a vivid red headband
2. detonate the tac vest
3. get removed from the round

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/71989367/b1840b01-c5bd-48c9-b732-c43363cb3bb5)

**Comment by Lumipharon** [comment]
you're not getting decapped, you're getting gibbed.

**Comment by irRegularGuy646** [comment]
the tac vest isn't supposed to gib though? i remember being revived after popping the vest a bunch of times before.
