### ISSUE TITLE
Freelancer Veteran Loadout spawns empty.

### ISSUE THREAD

**Issue by TheUSSWatercooler** [tgstation/TerraGov-Marine-Corps#14117]
### Description

A Freelancer Veteran loadout spawns empty in EORD, unsure past that.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23667](https://scrubby.melonmesa.com/round/23667)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-09T02:14:02+00:00
Master commit: [1ab6e881c0c24998daa4c95ec06a976b4518af77](https://github.com/tgstation/TerraGov-Marine-Corps//commit/1ab6e881c0c24998daa4c95ec06a976b4518af77)
The following pull requests are currently test merged:
[#13969: 'Adds roundstart heavy weapon rotation.' by Pariah919 at commit e0c2f8f076](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13969)
[#14024: 'Campaign part 2' by Lumipharon at commit d314c48ee3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14024)
[#14102: 'Hyperscales Guns: Take 3' by hyper2snyper at commit b7a31ae336](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14102)

Local commit: 1cea843e13419654f5da4402f52c9c4d9c24a093
Server tools version: 5.16.0

### Reproduction Steps

1. Enter EORD
2. Spawn as a Freelancer Veteran
3. See you have no gun, a mostly empty backpack.
4. Die.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/110517775/04dc83aa-3391-410d-9401-93795dfbdb0d)

**Comment by Xander3359** [comment]
So what's happening here is that, there is a baseline loadout for freelancers, which is what has the clothes and the backpack, after the baseline is given out, you are given your gun and grenades and the rest of your stuff.
IDK why EORD is spawning you with this, since it should be selecting 1 of the 3 actual loudouts.

**Comment by Lumipharon** [comment]
fixed
