### ISSUE TITLE
Heavy Weapons MRLS selection vends two systems instead of one.

### ISSUE THREAD

**Issue by TheUSSWatercooler** [tgstation/TerraGov-Marine-Corps#14133]
### Description

The vendor has two systems to dispense, which is normal from what I can tell.
However, when you dispense one, it forms as both an item and the already deployed version, so 2 systems for 1.

Sadly did not get a screenshot.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23689](https://scrubby.melonmesa.com/round/23689)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-10T02:26:15+00:00
Master commit: [1a5a5174e2e1586cd64c58c0e2bbb1a49ae848ac](https://github.com/tgstation/TerraGov-Marine-Corps//commit/1a5a5174e2e1586cd64c58c0e2bbb1a49ae848ac)
The following pull requests are currently test merged:
[#13969: 'Adds roundstart heavy weapon rotation.' by Pariah919 at commit e0c2f8f076](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13969)
[#14102: 'Hyperscales Guns: Take 3' by hyper2snyper at commit b7a31ae336](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14102)
[#14099: 'Runner changes: quality of life and refactoring' by lKiseki at commit e074895079](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14099)
[#14023: 'Adding multiple balance features in Gelida IV: Xenomorph Edition' by novaepee at commit bc8f5577a0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14023)
[#14108: 'TTS update' by vvvv-vvvv at commit d622f9172a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14108)

Local commit: 5ff706f4f8dc9c160afe5c5e7f98f3b7e18b4eb7
Server tools version: 5.16.0

### Reproduction Steps

1. Dispense a MRLS system
2. Realize you're holding a deployable and there's one already deployed on top of the vendor.
3. Dispense the other.
4. Have 4 MRLSs
5. profit, potentially

**Comment by vvvv-vvvv** [comment]
#14095
