### ISSUE TITLE
Dashe Armor set to medium despite being labeled as heavy

### ISSUE THREAD

**Issue by ButterChugger** [tgstation/TerraGov-Marine-Corps#14160]
### Description

Upon checking dashe armor values, it seems to be set to medium across the board. As with all heavy armor plates in Jaeger building under heavy armor sets, it states it offers 'high' protection and should be:
Soft melee armor: 50
Soft bullet armor: 70
Soft laser armor: 70
Soft energy armor: 60
Soft bomb armor: 55
Soft bio armor: 55
Soft fire armor: 55
Soft acid armor: 60

However on examining a full set of dashe, it is:
Soft melee armor: 45
Soft bullet armor: 65
Soft laser armor: 65
Soft energy armor: 55
Soft bomb armor: 50
Soft bio armor: 50
Soft fire armor: 50
Soft acid armor: 55
Also set to medium encumbrance. Just needs to be set to H pattern values or relabeled as medium armor.

### Test Merges

Round ID: [23721](https://scrubby.melonmesa.com/round/23721)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-13T00:11:27+00:00
Master commit: 23dee2cb2f632dba748b4c08d6902019ad249957
The following pull requests are currently test merged:
#13969: 'Adds roundstart heavy weapon rotation.' by Pariah919 at commit e0c2f8f076
#14108: 'TTS update' by vvvv-vvvv at commit 500ff4de7a
#13946: 'Adds custom squads' by TiviPlus at commit 42f859fd75
#14154: 'Campaign RTB stun' by Lumipharon at commit 99f807602b
#14153: 'Campaign strategic reserve tweak' by Lumipharon at commit ab915f1a83
#14152: 'Campaign status uses static data' by Lumipharon at commit 809bd1d4eb
#14148: 'explosions clear smoke' by Lumipharon at commit a9921b3d81
#14147: 'Mech stomp' by Lumipharon at commit 5b8efd1d64

### Reproduction Steps

1.Go to vendor
2. Vend and build a full dashe set
3. Compare full dashe set to standard H pattern xenonauten

**Comment by coldironwarrior** [comment]
close-able i guess since dashe has been removed. rip.
