### ISSUE TITLE
Banelings Spread fire to their pods while respawning

### ISSUE THREAD

**Issue by Blockaboo** [tgstation/TerraGov-Marine-Corps#14179]
### Description

Banelings after having sticky fire applied to them and dying will spread the fire to under their respawn pod leading to their permanent death

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23756](https://scrubby.melonmesa.com/round/23756)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-14T09:15:24+00:00
Master commit: [507a9622d9a5c7a1a82c283476b49468139274ae](https://github.com/tgstation/TerraGov-Marine-Corps//commit/507a9622d9a5c7a1a82c283476b49468139274ae)
The following pull requests are currently test merged:
[#13969: 'Adds roundstart heavy weapon rotation.' by Pariah919 at commit e0c2f8f076](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13969)
[#13946: 'Adds custom squads' by TiviPlus at commit 42f859fd75](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13946)

### Reproduction Steps

1. have sticky fire applied to you as a baneling
2. die
3. begin respawning in your pod
4. watch fire spread to under your pod
5. die for real

**Comment by Arctrooper8** [comment]
By sticky fire do you mean the trailblaze grenade?
Potentially related to: https://github.com/tgstation/TerraGov-Marine-Corps/issues/13635

**Comment by vvvv-vvvv** [comment]
#13795
