### ISSUE TITLE
Recommended items are no longer bolded in vendors

### ISSUE THREAD

**Issue by ArcaneCarrot** [tgstation/TerraGov-Marine-Corps#1422]
## Testmerges:
#1408: 'Cocking a weapon without a mag ejects a working round' by psykzz at commit 6ae29bc587
#1394: 'The port of NanoUI itself' by DominikPanic at commit 111cb0cf78
#1375: 'Weed subsystem' by psykzz at commit 4aa68c0490
#1388: 'Makes the chat loading smoother' by DominikPanic at commit 2dd0500dba
#1370: 'Resist time lowered, clean and refactor.' by Rohesie at commit ef7dbd8b3b
#1382: 'Fixes wounds overlays' by MoXuT0 at commit 1c9a9ea9e7
#1389: '/tg/ machinery/button' by Rohesie at commit bbfe5947fc
#1201: 'Refactoring Xeno Ability Buttons' by spookydonut at commit e8199e8e16
#1368: 'Cleaning, fixing, tweaking up chemistry_reagents.' by Ghommie at commit 11addb99eb
#1417: 'Fixes delay round end verb' by DominikPanic at commit cbd9b1ee1d
#1414: 'Fixes resin walls cannibalizing weeds' by psykzz at commit 6c023d89d0
#1412: 'Reverts HPR firing sound' by Alterist at commit da92b6ca46
#1411: 'Adds the /tg/ runtime viewer' by DominikPanic at commit 024efc7b3c
#1410: 'Cleans up controller code that likely won't be used' by DominikPanic at commit 0075814f4e

## Reproduction:
Equipment vendors no longer show recommended items in bold text.
![Unga](https://user-images.githubusercontent.com/32185313/56932177-883fcf80-6a97-11e9-843a-e17dc8d8a591.PNG)

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1394
