### ISSUE TITLE
Line in wrong place on cryocell damage meter

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1425]
## Testmerges:

#1410 #1411 #1412 #1414 #1417 #1368 #1389 #1382 #1370 #1388 #1375 #1394 #1408 #1415

## Reproduction:

Look at a filled cryocell.

![image](https://user-images.githubusercontent.com/44811257/56934098-5dae4080-6ab0-11e9-8e64-3f9909584f7f.png)

**Comment by psykzz** [comment]
Caused by #1394 
Fix proposed.
