### ISSUE TITLE
Runner evasion works on PBs

### ISSUE THREAD

**Issue by DeltaFire15** [tgstation/TerraGov-Marine-Corps#14256]
### Description

Some ~~recent change~~ change from like late 2021-mid 2022 after some deduction made runner evasion work on pointblank shots, which until then have always been the countermeasure for runners that get too cocky around someone with a shotgun.
This is uh, very concerning, especially with recent runner buffs that basically make evasion duration always 4 seconds (tl;dr autoevade makes it really easy to retrigger evasion and also makes you able to true chain it, which was not possible before)

### Test Merges

Irrelevant. This is on master.

### Reproduction Steps

1. Runner evades
2. Shotgun PB runner
3. Runner evades your PB.
 4. Die.

### Screenshots

![grafik](https://github.com/tgstation/TerraGov-Marine-Corps/assets/46569814/0d4b0986-336b-4505-8ce5-6eb4ae7b1c4d)

**Comment by Lumipharon** [comment]
Evasion has never actually been hittable by PB's, I'm not sure where this myth has come from.

You can physically HIT them as your image shows, but the projectiles have never had any sort of check for them being caused by a pb or not.

**Comment by DeltaFire15** [comment]
> Evasion has never actually been hittable by PB's, I'm not sure where this myth has come from.
> 
> You can physically HIT them as your image shows, but the projectiles have never had any sort of check for them being caused by a pb or not.

No. I just tested this in a (merged) branch from 2021 I have had laying around. The bug seems to have been introduced somewhen during 2022, from some preliminary comparing to other branches.
![grafik](https://github.com/tgstation/TerraGov-Marine-Corps/assets/46569814/e09eec7d-d7b8-4c28-8048-324b4fc42159)


Reopen this issue.

**Comment by DeltaFire15** [comment]
Also here's some comments from **the author of the original PR**, indicating them getting hit was **intended**.
![grafik](https://github.com/tgstation/TerraGov-Marine-Corps/assets/46569814/704b009c-89ee-4164-921a-dc3cc204ff96)

![grafik](https://github.com/tgstation/TerraGov-Marine-Corps/assets/46569814/fb42581e-f475-42b1-9b14-de928013e341)

**Comment by Lumipharon** [comment]
Do you have an actual video of this? or stack traced how it was getting through?

The wording in the original pr implied the melee hit of pb worked, not the projectiles. again I'm fine with being wrong, I just don't see whats changed in the code that could cause that.

**Comment by DeltaFire15** [comment]
> Do you have an actual video of this? 

Sure! Here you go.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/46569814/0e711608-1a43-46c6-803f-b988d5f81cba

**Comment by Lumipharon** [comment]
thanks, could you stack trace and see whats changed?
