### ISSUE TITLE
carrier huggers get stuck when you throw them

### ISSUE THREAD

**Issue by imsxz** [tgstation/TerraGov-Marine-Corps#14255]
### Description

huggers get stuck when you bounce them off of people
@Lumipharon @Lumipharon @Lumipharon 

### Test Merges

[#13946: 'Adds custom squads' by TiviPlus at commit 42f859fd75](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13946)
[#13924: 'Tweaks widow to be more playable.' by Arturlang at commit 816af28835](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13924)
[#14192: 'throw bounce change' by Lumipharon at commit 8a5c73efa4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14192)

### Reproduction Steps

1. go carrier
2. throw hugger at person
3. its stunned or something

**Comment by Lumipharon** [comment]
My pr doesn't touch hitting living things. Also is that not how they've always worked?

**Comment by Lumipharon** [comment]
Testing this on local and I see zero difference. Just the sprite doesn't update from its thrown state immediately if it doesn't hit anything
