### ISSUE TITLE
When you are on an MMG, you are immune to gas

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#14253]
### Description

this has been obvious forever but hasnt been reported?? I just decided to bother looking through bug reports and didnt see this here??

### Test Merges

Round ID: [23888](https://scrubby.melonmesa.com/round/23888)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-20T20:57:29+00:00
Master commit: [8f96c39f058a8e51f9b1d4c12decda2f8fb39e9c](https://github.com/tgstation/TerraGov-Marine-Corps//commit/8f96c39f058a8e51f9b1d4c12decda2f8fb39e9c)
The following pull requests are currently test merged:
[#13946: 'Adds custom squads' by TiviPlus at commit 42f859fd75](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13946)
[#13924: 'Tweaks widow to be more playable.' by Arturlang at commit 816af28835](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13924)
[#14192: 'throw bounce change' by Lumipharon at commit 8a5c73efa4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14192)

Local commit: a289339586847bbf3a6c5a104ba4623ad68a2647
Server tools version: 5.16.2

### Reproduction Steps

1. get on MMG
2. get shot by boiler gas or surronded by defiler gas or have baneling gas pop on you
3. notice as youre immune to gas (Ive since forgotten if you can still rotate)

**Comment by Lumipharon** [comment]
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/a819f03b-6162-4686-a2aa-1e0fcfd10ebe)
 works for me.
