### ISSUE TITLE
A hand-held X-Fuel flamethrower tank cannot refill from the backpack X-Fuel tank

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/TerraGov-Marine-Corps#14259]
### Description

You cannot refill the X-Fuel cartridges using the backpack X-Fuel tank.

### Test Merges

N/A

### Reproduction Steps

1) Have X-Fuel backpack tank
2) Have X-Fuel reloadable tank
3) Empty the X-Fuel reloadable tank
4) Try to reload it using the backpack tank
5) Fail

**Comment by Xander3359** [comment]
This isn't a bug.
You can't refill fuel tanks from a back tank, you attach the flamer directly to the back tank.
The only way you can refuel x-fuel is by buying the large x-fuel tank you can buy from req. It's the one on wheels, not the one you can wear.

**Comment by GrayRachnid** [comment]
Sadge. Feels like you should be able to refill from them.
