### ISSUE TITLE
Ghosts can draw on the CIC map 

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/TerraGov-Marine-Corps#14290]
### Description

It's kind of funny unless you're in command when it happens

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23947](https://scrubby.melonmesa.com/round/23947)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-26T00:55:25+00:00
Master commit: [fc8e02e6677cf1d42bbfb3ccac230ca5cba42255](https://github.com/tgstation/TerraGov-Marine-Corps//commit/fc8e02e6677cf1d42bbfb3ccac230ca5cba42255)
The following pull requests are currently test merged:
[#13946: 'Adds custom squads' by TiviPlus at commit 42f859fd75](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13946)
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit 9667f76099](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14142: 'Examine tweaks - complete xeno examine, armor information' by lKiseki at commit 6c4e107aee](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14142)

### Reproduction Steps

.

**Comment by Oscari-pog** [comment]
Fuck you made the issue before I got to fuck you

**Comment by Lumipharon** [comment]
> Fuck you made the issue before I got to fuck you

Lack of punctuation opens this up to a variety of interpretations.
