### ISSUE TITLE
Ghosts can (still) draw on tacmap

### ISSUE THREAD

**Issue by Oscari-pog** [tgstation/TerraGov-Marine-Corps#14316]
### Description

Haha I make the issue this time

Ghosts can still draw on tacmap.
Did you get a whoppa?

### Test Merges

The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit 9667f76099](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14142: 'Examine tweaks - complete xeno examine, armor information' by lKiseki at commit 6c4e107aee](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14142)
[#14243: 'Hyperscale gloves 2.0' by novaepee at commit 5e3739c9ff](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14243)
[#14298: 'Adds Library disk to Big Red, hardsets ETA disk.' by Barnet2 at commit 907e309a73](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14298)
[#14262: 'Larva Queue: Now while playing Minions' by ZeWaka at commit 6df207ed13](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14262)
[#14306: 'more throwbug fixes' by Lumipharon at commit 0d35456803](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14306)
[#14247: 'New hivelord primo and xeno flowers as primo for all builders' by Waselon at commit 7c325e0559](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14247)

### Reproduction Steps

1. Go to shipside
2. Click on drawing console
3. Teleport to someone who is groundside
4. Manually open tacmap
5. Show your inner artist

### Screenshots

![obrazek](https://github.com/tgstation/TerraGov-Marine-Corps/assets/70425197/b8cc038a-fb4b-4547-a4d9-8394e97b1412)

**Comment by Lumipharon** [comment]
fixed now
