### ISSUE TITLE
Flares no longer break resin nodes

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/TerraGov-Marine-Corps#14350]
### Description

You used to be able to break resin nodes by throwing flares at them. This no longer happens.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [24036](https://scrubby.melonmesa.com/round/24036)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-31T21:47:21+00:00
Master commit: [6e076861aecba0b60fa227dae516961bdc151723](https://github.com/tgstation/TerraGov-Marine-Corps//commit/6e076861aecba0b60fa227dae516961bdc151723)
The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit 9667f76099](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14298: 'Adds Library disk to Big Red, hardsets ETA disk.' by Barnet2 at commit 907e309a73](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14298)
[#14262: 'Larva Queue: Now while playing Minions' by ZeWaka at commit 2f3163d432](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14262)
[#14247: 'New hivelord primo and xeno flowers as primo for all builders' by Waselon at commit 7c325e0559](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14247)

Local commit: 04996c9eb2da1bbc1ee0a9685b7a273159fde713
Server tools version: 5.16.4

### Reproduction Steps

1. Get flare
2. Light flare
3. Throw flare at resin node

**Comment by GrayRachnid** [comment]
nevermind it works now??

**Comment by GrayRachnid** [comment]
no it doesn't i'm gaslighting myself

**Comment by GrayRachnid** [comment]
it's inconsistent

**Comment by lbnesquik** [comment]
Seems to be the case.
