### ISSUE TITLE
Non queen has purple chat

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#1436]
## Testmerges:

Round ID:  393 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 33f9fcd6d6fee8150d81c4c06fad12efdc3b9886 
The following pull requests are currently test merged: 
#1432: 'sublime users dont have access to dm langserver' by spookydonut at commit bb26a990b7 
#1431: 'Makes Past Scan Interface ~Fancy~' by Shadow-Quill at commit ef53030923 
#1430: 'Fixes camera autoname bug' by psykzz at commit b302d6a853 
#1429: 'Fixes double message on cloak deactivation' by MoXuT0 at commit 8f98ab6374 
#1367: 'Tweaks on xeno sting and larval growth serum.' by Rohesie at commit 10331c7a4b 
#1345: 'Refactors special abilities to use signals' by spookydonut at commit 9192c087f8 
#1218: 'Tank Tweak/Rebalance - TESTED' by Surrealaser at commit 5d4778c173 
#1416: 'Fixes Xeno healing without a queen present' by psykzz at commit ed4474e444 

Local commit: 3b03bb29dd18a73ffd6885bdfffa2e66af463081 
Server tools version: /tg/station 13 Server v3.2.6.2 

## Reproduction:

Not really sure how to, but the runner spoke pretty much the same time as a queen, could be a race condition

![image](https://user-images.githubusercontent.com/1134201/57037528-4d809780-6c4f-11e9-88ec-188a277b8d94.png)

**Comment by DominikPanic** [comment]
So far unable to been reproduced, if it doesn't happen again I guess we could write it off as a TM issue

**Comment by DominikPanic** [comment]
Feel free to re-open with reproduction steps
