### ISSUE TITLE
abilities that fling mobs, when used to throw a mob into a wall, deal a flat 25 damage that ignores armor

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#14360]
### Description

undocumented change, so i assume unintentional from throwcode fixes

### Test Merges

Round ID: [24064](https://scrubby.melonmesa.com/round/24064)
BYOND Version: 515.1610
Server revision compiled on: 2023-11-01T01:31:03+00:00
Master commit: [761b6bfa57857a68feea353a3c0bed7a7e61a6e5](https://github.com/tgstation/TerraGov-Marine-Corps//commit/761b6bfa57857a68feea353a3c0bed7a7e61a6e5)
The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit 9667f76099](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14298: 'Adds Library disk to Big Red, hardsets ETA disk.' by Barnet2 at commit 907e309a73](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14298)
[#14262: 'Larva Queue: Now while playing Minions' by ZeWaka at commit 2f3163d432](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14262)
[#14247: 'New hivelord primo and xeno flowers as primo for all builders' by Waselon at commit 7c325e0559](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14247)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit 5cd0914184](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)

Local commit: dd49b3a9286daaa8cdaec0f1e6ae5e163bbf331f
Server tools version: 5.16.4

### Reproduction Steps

probably easiest to see this at work with xeno abilities used on marines, but might apply to other stuff like grenade or pod explosions, jetpacking into walls, etc.
1. be a xeno with an ability to throw marines (shrike's psychic fling, in this case)
2. use psychic fling on a marine with a trajectory that sends them into a wall
3. ghost, i guess
4. check mob variables on the marine
5. they will acquire a flat 25 brute damage from being flung into the wall

**Comment by ZeWaka** [comment]
defenders and beetles were also taking damage from using their own charge

**Comment by Lumipharon** [comment]
fixed
