### ISSUE TITLE
Disposal pipe issues in Arachne's medical

### ISSUE THREAD

**Issue by TheUSSWatercooler** [tgstation/TerraGov-Marine-Corps#14377]
### Description

Putting stuff into the eastern surgical room's disposal unit causes it to be shot out of the one in the main lobby, south of the autodoc.
Vice versa, too.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [24107](https://scrubby.melonmesa.com/round/24107)
BYOND Version: 515.1610
Server revision compiled on: 2023-11-03T17:37:17+00:00
Master commit: [f37c30d2972af252da5d9bd15ae9ad38f6ccf1b9](https://github.com/tgstation/TerraGov-Marine-Corps//commit/f37c30d2972af252da5d9bd15ae9ad38f6ccf1b9)
The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14298: 'Adds Library disk to Big Red, hardsets ETA disk.' by Barnet2 at commit 907e309a73](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14298)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit 8d52de95a2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14155: 'Increases resin wall bullet armor' by coldironwarrior at commit 096a86a2fe](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14155)

Local commit: ca97d398e5b81d3408ba8eb1becb7b8171923f98
Server tools version: 5.16.4

### Reproduction Steps

1. Put shrapnel/junk into disposal unit after surgery
2. Wait as it turns on
3. Watch as shit gets launched out the other bin.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/110517775/de12378c-281f-4fef-9305-12ed4aeb54b9)

**Comment by coldironwarrior** [comment]
fixed by #15050
