### ISSUE TITLE
Fire overlay doesnt clear off xenos after extinguishing self

### ISSUE THREAD

**Issue by Oscari-pog** [tgstation/TerraGov-Marine-Corps#14375]
### Description

I expect to not be a shining beacon to marine bullets after I extinguish myself
Probably caused by this PR: https://github.com/tgstation/TerraGov-Marine-Corps/pull/14366 - was there even a testmerge of this PR beforehand?

### Test Merges

The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14298: 'Adds Library disk to Big Red, hardsets ETA disk.' by Barnet2 at commit 907e309a73](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14298)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit 8d52de95a2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14155: 'Increases resin wall bullet armor' by coldironwarrior at commit 096a86a2fe](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14155)

### Reproduction Steps

1. Get set on fire
2. Extinguish self
3. Forever stuck with emissive fire on you

**Comment by vvvv-vvvv** [comment]
#14373

**Comment by Oscari-pog** [comment]
Why no merge

**Comment by Oscari-pog** [comment]
Resolved via merge now
