### ISSUE TITLE
XENOS CAN NOT DANCE THIS IS NOT A DRILL

### ISSUE THREAD

**Issue by drawsstuff** [tgstation/TerraGov-Marine-Corps#1437]
XENOS CAN NOT USE THE DANCE EMOTE
## Testmerges:
#1416: 'Fixes Xeno healing without a queen present' by psykzz at commit ed4474e444
#1218: 'Tank Tweak/Rebalance - TESTED' by Surrealaser at commit 5d4778c173
#1367: 'Tweaks on xeno sting and larval growth serum.' by Rohesie at commit 10331c7a4b
#1429: 'Fixes double message on cloak deactivation' by MoXuT0 at commit 8f98ab6374
#1430: 'Fixes camera autoname bug' by psykzz at commit b302d6a853
#1431: 'Makes Past Scan Interface ~Fancy~' by Shadow-Quill at commit ef53030923
#1432: 'sublime users dont have access to dm langserver' by spookydonut at commit bb26a990b7
#1426: 'Ports /tg/ telecomms code' by DominikPanic at commit 6807cf82c6

## Reproduction:
1. Be a warrior
2. *dance
3.*cry

**Comment by drawsstuff** [comment]
I HAVE JUST LEARNED THIS ATROCITY IS INTENDED BEHAVIOR, I REPEAT, **INTENDED**!!

I will not be closing this ISSUE, though it may not be a bug, it bugs me so significantly that I'm going to have to resort to dabbing.

**Comment by DominikPanic** [comment]
10/10
