### ISSUE TITLE
Kwik-E-Quip vendors are too aggressive

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#14417]
### Description

See title.

if you access a Kwik-E-Quip loadout while you already have a backpack on, that backpack and its contents are deleted

if you access a Kwik-E-Quip loadout while you have a jumpsuit with a cloak on, your jumpsuit is deleted but the cloak sprite stays on your sprite

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [24179](https://scrubby.melonmesa.com/round/24179)
BYOND Version: 515.1610
Server revision compiled on: 2023-11-06T20:22:06+00:00
Master commit: [4eb97bf6f1e9e1bd93eff4ab59d748a162660b33](https://github.com/tgstation/TerraGov-Marine-Corps//commit/4eb97bf6f1e9e1bd93eff4ab59d748a162660b33)
The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit 8d52de95a2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14155: 'Increases resin wall bullet armor' by coldironwarrior at commit 096a86a2fe](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14155)

Local commit: ac35b1c23f44fb41b44a144088cc329f89ac5b22
Server tools version: 5.17.1

### Reproduction Steps

1. Equip a backpack and a jumpsuit with a cloak
2. vend a Kwik-E-Quip loadout
3. your backpack will be completely gone
4. your sprite will now have a cloak affixed to it (you can get rid of the cloak sprite somehow but I'm not sure how)

**Comment by QualityVan** [comment]
Should be fixed by the commit that mentioned it, comment if either's still happening.
