### ISSUE TITLE
beating heeart goes clank

### ISSUE THREAD

**Issue by Dikozda** [tgstation/TerraGov-Marine-Corps#14448]
### Description

beating hearts sometimes go clank

### Test Merges

[#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14393: 'Flare Rebalance: Removes infinite flares and adds a flare crate to req' by KrabSpider at commit 0bf22a2d60](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14393)
[#14378: 'Bump rust-g to 3.0.0' by vvvv-vvvv at commit d01a959374](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14378)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit a98df94476](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14389: 'Gorger Feast is AOE + lower cooldown' by Xander3359 at commit 22ada19c83](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14389)

### Reproduction Steps

either spawn a new heart or go to the chapel in Valhalla before it despawns
listen to the clank

### Screenshots

[2023-11-14 23-54-04.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/12964904/5117c15b-4314-4283-b20b-6b9c67e16649)

**Comment by chizzy376** [comment]
bro posted a 36 hour video
