### ISSUE TITLE
Rejuvenate bugged

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#1447]
![c3b6541a465e41af3bb1694617ad410a](https://user-images.githubusercontent.com/42041276/57118369-403fd780-6d39-11e9-86b3-239f17a607f0.png)

## Testmerges:

#1440: 'Fixes queen being unable to launch the shuttle' by DominikPanic at commit 3c4d5ea12e
#1439: 'Fixes the evil squad change console' by DominikPanic at commit b325cd58ca
#1367: 'Tweaks on xeno sting and larval growth serum.' by Rohesie at commit 10331c7a4b
#1426: 'Ports /tg/ telecomms code' by DominikPanic at commit 36a2270f0a
#1435: 'Adjust lighttube position to sit better on walls' by psykzz at commit 8f321f57ee
#1438: 'Reduces job datum instance creation, fixes ERT ranks' by DominikPanic at commit 1d0f62dde9
#1445: 'Adds sounds for flashlights and flares' by MoXuT0 at commit 94b18a19b8
#1446: 'Adds sounds for writing on paper and using stamps' by MoXuT0 at commit f01e31ff50

This looks like a issue in master.

## Reproduction:

Have someone suicide and ghost out. Rejuvenate them.

**Comment by DominikPanic** [comment]
Unable to reproduce
https://puu.sh/DngOP/7ae6c99cdd.mp4
