### ISSUE TITLE
Dnr marine hiding revivable marine

### ISSUE THREAD

**Issue by chizzy376** [tgstation/TerraGov-Marine-Corps#14495]
### Description

You can be completely hidden from corpsmen if you happen to die and be buried below a dnr person on the same tile

### Test Merges

The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14378: 'Bump rust-g to 3.0.0' by vvvv-vvvv at commit d01a959374](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14378)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit a98df94476](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14389: 'Gorger Feast is AOE + lower cooldown' by Xander3359 at commit 22ada19c83](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14389)
[#14403: 'Adjusts harvester chemicals' by Xander3359 at commit 8e7e6b92a1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14403)
[#14310: 'Squad transfer tablet' by TiviPlus at commit 1dfae7478d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14310)
[#14472: 'Automatic TGS DMAPI Update' by github-actions[bot] at commit 08dd9a2e67](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14472)

### Reproduction Steps

1. Get two dead marines, one revivable, the other not (both with headsets so they show up on tacmap)
2. Bring both marines on the same tile
3. If the dnr marine ends up above the revivable marine in the tile, you won't be able to see the revivable marine. Tacmap only shows the red cross and health hud only shows the skull of the dnr marine

**Comment by Lumipharon** [comment]
Not a bug, but would be a good QOL fix.
