### ISSUE TITLE
Lascarbine Scatter mode does not fully hit crit xenos

### ISSUE THREAD

**Issue by 74delta** [tgstation/TerraGov-Marine-Corps#14505]
### Description

Recently there was a change to make multiround weapons like buckshot, flech, etc hit downed xenos.

Scatter lascarbine was left out so even on PB it misses all but the primary beam.

### Test Merges

TMs
#14258: 'Reverts Hyperscale 3' by lKiseki at commit 1011e0710d
#14261: 'Adds Beginner loadouts.' by Xander3359 at commit a98df94476
#14389: 'Gorger Feast is AOE + lower cooldown' by Xander3359 at commit 22ada19c83
#14403: 'Adjusts harvester chemicals' by Xander3359 at commit 28eda31a93
#14310: 'Squad transfer tablet' by TiviPlus at commit 1dfae7478d
#14442: 'Add area specific sound enviroments and adds reverb to caves' by Dikozda at commit 4c01a18835

### Reproduction Steps

Wield lascarbine
Use scatter mode
Try to PB crit xenomorph.

### Screenshots

![image-172](https://github.com/tgstation/TerraGov-Marine-Corps/assets/136781916/0ced5ec6-15d7-4bbe-a805-1747f341e8fb)

**Comment by vvvv-vvvv** [comment]
#12799
