### ISSUE TITLE
chemrette packet invis+extra room

### ISSUE THREAD

**Issue by TGCMbetcher** [tgstation/TerraGov-Marine-Corps#14516]
### Description

I expected for it to not go invisible
It went invisible and had an extra 7 slots
I highly doubt its a new thing considering the number of people who used them when they first came out could be counted on one hand since theyre infinitely worse than a gas mask and pills but take a pillbottle slot
They also eventually disappeared from the storage slot

### Test Merges

[#14258: 'Reverts Hyperscale 3' by lKiseki at commit 1011e0710d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit a98df94476](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14389: 'Gorger Feast is AOE + lower cooldown' by Xander3359 at commit 22ada19c83](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14389)
[#14403: 'Adjusts harvester chemicals' by Xander3359 at commit 28eda31a93](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14403)
[#14310: 'Squad transfer tablet' by TiviPlus at commit 1dfae7478d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14310)
[#14442: 'Add area specific sound enviroments and adds reverb to caves' by Dikozda at commit d86619b04d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14442)

### Reproduction Steps

Buy chemrettes
Buy second chemrettes
Put more chemrettes into the first to get the right mix you want
End up with an invisible packet and 7 more slots than you though you would have

![Untitled](https://github.com/tgstation/TerraGov-Marine-Corps/assets/76980366/cec5c51d-5ee8-4ac0-be38-b83135537caf)

**Comment by TGCMbetcher** [comment]
Now that I think about it its probably because there are sprites for certain amounts that are inside but its going over the intended amount so there is no sprite for that number and it shows blank

**Comment by Lumipharon** [comment]
fixed
