### ISSUE TITLE
Lasers can fire through hull glass

### ISSUE THREAD

**Issue by ClosetedSkeletonGH** [tgstation/TerraGov-Marine-Corps#14538]
### Description

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/120620754/37c37e77-2a07-4637-8405-90c197f11341)

As can be seen in this photo, this is a pretty crash exclsuive problem as marines can sit behind hull glass and camp important spots depending on where the cantebury lands

### Test Merges

Round ID: [24432](https://scrubby.melonmesa.com/round/24432)
BYOND Version: 515.1610
Server revision compiled on: 2023-11-24T05:09:55+00:00
Master commit: [22c0b2c8e45bd244110375c01a3d77f4b4bfb6c4](https://github.com/tgstation/TerraGov-Marine-Corps//commit/22c0b2c8e45bd244110375c01a3d77f4b4bfb6c4)
The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit 1011e0710d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14261: 'Adds Beginner loadouts.' by Xander3359 at commit 151d79a4c6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14261)
[#14389: 'Gorger Feast is AOE + lower cooldown' by Xander3359 at commit 22ada19c83](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14389)
[#14310: 'Squad transfer tablet' by TiviPlus at commit a15b308705](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14310)
[#14442: 'Add area specific sound enviroments and adds reverb to caves' by Dikozda at commit d86619b04d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14442)
[#14488: 'Do after fix' by Lumipharon at commit 024a184d2c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14488)

Local commit: 6b40da6bc396d9eccdfc623abb0132261e68f175
Server tools version: 5.18.2

### Reproduction Steps

1. play crash
2. go to the front of the ship
3. notice as lasers can fire through unmeltable, unremovable, undestroyable glass

**Comment by coldironwarrior** [comment]
not really a bug

**Comment by chizzy376** [comment]
It's glass
lasers are supposed to go through glass?

**Comment by efzapa** [comment]
whos gonna tell him lasers are literally just focused light beams

**Comment by Lumipharon** [comment]
Not a bug.
