### ISSUE TITLE
Defenders can move dead bodies with abilities

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#14589]
### Description

Defenders can move dead bodies by hitting them with tail sweep or centrifugal force.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [24533](https://scrubby.melonmesa.com/round/24533)
BYOND Version: 515.1610
Server revision compiled on: 2023-12-02T23:04:12+00:00
Master commit: [f1cd21f7fd87eba913cd88e5d1498ba4998f9d3d](https://github.com/tgstation/TerraGov-Marine-Corps//commit/f1cd21f7fd87eba913cd88e5d1498ba4998f9d3d)
The following pull requests are currently test merged:
[#14310: 'Squad transfer tablet' by TiviPlus at commit a15b308705](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14310)
[#14442: 'Add area specific sound enviroments and adds reverb to caves' by Dikozda at commit d86619b04d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14442)
[#11624: 'TGMC Christmas 2023 [IDB IGNORE]' by RipGrayson at commit a6419e9c13](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11624)

Local commit: abe66e7e28ed0afc7810559624a714628be72d5c
Server tools version: 5.18.2

### Reproduction Steps

1. Go defender
2. Kill a marine
3. Use tail sweep or centrifugal force next to their body
4. Watch as they get knocked back

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/71583ec8-e7ea-43fa-838b-bc09fdddc113

**Comment by Lumipharon** [comment]
Fixed as far as I am aware.
