### ISSUE TITLE
Warrior Freeze Ups On Lunge Still Exists

### ISSUE THREAD

**Issue by usnpeepoo** [tgstation/TerraGov-Marine-Corps#14588]
### Description

this has been a very very longstanding bug (i recall dealing with it from 2021, 2022, and now this year too) although it has become a lot rarer with bug fixes, it's still an issue.
on lunging, there's a chance you might freeze up/have your keys locked and be unable to move at all.  I've attached 2 streamable videos where this bug occurs twice in the same round.
https://streamable.com/o6m5qv (first time this happened in the round)

https://streamable.com/cunjq3 (the lunge immediately after, same bug and it caused me to die)

### Test Merges

m/a couldnt make this report when tm's were active (github lockdown)

### Reproduction Steps

1: lunge
2: slash, punch, do whatever
3: your lunge is now let go, attempt to run off
4: can't move at all

**Comment by Lumipharon** [comment]
try hit something repeatedly. You cannot hit them 500 times per second.
In the case of warrior, this is the movement delay. You're essentially stacking the normal movement delay with another movement delay instantly (and often diagonal move delay which is higher) so suddenly your next move takes noticably longer than normal to happen.
