### ISSUE TITLE
Whitespace appearing before messages

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1458]
## Testmerges:

Round ID:  408 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 0c9fba1e2cf843f651e43af6216028f85cd58b98 
The following pull requests are currently test merged: 
#1375: 'Weed subsystem' by psykzz at commit 2dee44a436 
#1426: 'Ports /tg/ telecomms code' by DominikPanic at commit 6a4448f479 
#1440: 'Fixes queen being unable to launch the shuttle' by DominikPanic at commit 3c4d5ea12e 
#1439: 'Fixes the evil squad change console' by DominikPanic at commit b325cd58ca 
#1438: 'Reduces job datum instance creation, fixes ERT ranks' by DominikPanic at commit 1d0f62dde9 
#1445: 'Adds sounds for flashlights and flares' by MoXuT0 at commit 94b18a19b8 
#1446: 'Adds sounds for writing on paper and using stamps' by MoXuT0 at commit f01e31ff50 
#1337: 'Use SSdirection for queen locator' by psykzz at commit 1b9904585a 
#1444: 'Adds sounds for cigs, lighters and matches' by MoXuT0 at commit 914653f9d6 
#1453: 'Fixes req elevator crates falling down' by DominikPanic at commit f3f105cede 
#1452: 'Fixes lasgun underbarrel attachments' by DominikPanic at commit 5615bcfe87 
#1451: 'Fixes EORD shuttle windows' by DominikPanic at commit 27a642cce7 
#1450: 'Fixes xeno tunnels' by DominikPanic at commit d603fd6327 
#1449: 'Fixes medibots not injecting custom chems' by DominikPanic at commit e5acfad9c2 
#1448: 'Fixes rejuvenate HUD graphical issues' by DominikPanic at commit 943fa317a2 

## Reproduction:

This includes both radio and regular talk.

![yes](https://user-images.githubusercontent.com/34478337/57166311-6b422e00-6e02-11e9-9361-b8608b609f7c.png)

**Comment by DominikPanic** [comment]
As was discussed in #coding this is likely a client-side issue (since for the people it was also the same way on /tg/, it may take time for the relevant files due to caching to update.) regardless, I'm leaving this up for some time.

**Comment by DominikPanic** [comment]
Seems to be alright now
