### ISSUE TITLE
FleckTex Hardsuit Armour does not save their secondary colour on loadouts.

### ISSUE THREAD

**Issue by TellyLsc** [tgstation/TerraGov-Marine-Corps#14603]
### Description

Title.

### Test Merges

#11624: 'TGMC Christmas 2023 [IDB IGNORE]' by RipGrayson at commit ad84823f1a 
#14258: 'Reverts Hyperscale 3' by lKiseki at commit c50038e215 

### Reproduction Steps

1. Right click your chestpieces/leg plates/arm plates/helm with facepaint.
2. Colour the secondary piece into whatever.
3. Put them into the exoskeleton and wear it.
4. Save loadout
5. Vend that loadout, watch as the "shoe" part of the leg plate default to drab colour, same for "webbing" part of the chestplate or the "center" part of the helmets. Dunno what the armpiece secondary colour is supposed to change since I don't see anything changing.

**Comment by coldironwarrior** [comment]
fixed by #14629
