### ISSUE TITLE
1 second delay after clicking vend on "Marine Food and Drinks Vendor" vendor window before the item vends.

### ISSUE THREAD

**Issue by TellyLsc** [tgstation/TerraGov-Marine-Corps#14635]
### Description

Title.

### Test Merges

[#11624: 'TGMC Christmas 2023 [IDB IGNORE]' by RipGrayson at commit 7e8cbf6fe2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11624)
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit c50038e215](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14618: 'tgui 5.0' by vvvv-vvvv at commit 059ea93977](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14618)

### Reproduction Steps

1. Find a Marine Food and Drinks Vendor.
2. Click it to open the vendor UI.
3. Click vend on an item.
4. Wait a solid second until the item vends into your hand instead of instantly.

**Comment by Lumipharon** [comment]
Either fixed or never happened.
Unless you're confusing it with the hot drink vendor, where the delay is muh immersion, as it makes the drink.

**Comment by TellyLsc** [comment]
> Either fixed or never happened. Unless you're confusing it with the hot drink vendor, where the delay is muh immersion, as it makes the drink.

Seems to be related to the CHRISTMAS merge, it's gone now yeah.
