### ISSUE TITLE
67mm Rocket cannot fit in explosive pouch

### ISSUE THREAD

**Issue by OogaBoogaBunga** [tgstation/TerraGov-Marine-Corps#14633]
### Description

Codex says it can hold all 67mm rockets. Attempting to put it in gives "X shell is too long for this the explosive pouch" 
Either this was nerfed and description was not changed or it was meant to fit but some weird size change bugged it. 

### Test Merges

Not relevant

### Reproduction Steps

1. Take any 67mm rocket
2. Try to put in explosive pouch
3. Get cant fit message

### Screenshots

![screenshot](https://github.com/tgstation/TerraGov-Marine-Corps/assets/125516046/004322cc-2663-4020-be4e-b3dd44b5450a)

**Comment by Lumipharon** [comment]
Its an issue with the codex. It seems to just pull all subtypes of rocket, even ones that exceed the weight class. Likely this will effect the codex entry of many items.

The fix would be to make the codex actually check max weight class of the storage item.
