### ISSUE TITLE
Drones can not evolve into queen

### ISSUE THREAD

**Issue by drawsstuff** [tgstation/TerraGov-Marine-Corps#1465]
## Testmerges:
#1375: 'Weed subsystem' by psykzz at commit 2dee44a436
#1426: 'Ports /tg/ telecomms code' by DominikPanic at commit 7731de04a7
#1440: 'Fixes queen being unable to launch the shuttle' by DominikPanic at commit 3c4d5ea12e
#1439: 'Fixes the evil squad change console' by DominikPanic at commit b325cd58ca
#1438: 'Reduces job datum instance creation, fixes ERT ranks' by DominikPanic at commit 1d0f62dde9
#1445: 'Adds sounds for flashlights and flares' by MoXuT0 at commit 94b18a19b8
#1446: 'Adds sounds for writing on paper and using stamps' by MoXuT0 at commit f01e31ff50
#1337: 'Use SSdirection for queen locator' by psykzz at commit 1b9904585a
#1444: 'Adds sounds for cigs, lighters and matches' by MoXuT0 at commit 914653f9d6
#1453: 'Fixes req elevator crates falling down' by DominikPanic at commit f3f105cede
#1452: 'Fixes lasgun underbarrel attachments' by DominikPanic at commit 5615bcfe87
#1451: 'Fixes EORD shuttle windows' by DominikPanic at commit 27a642cce7
#1450: 'Fixes xeno tunnels' by DominikPanic at commit d603fd6327
#1449: 'Fixes medibots not injecting custom chems' by DominikPanic at commit e5acfad9c2
#1448: 'Fixes rejuvenate HUD graphical issues' by DominikPanic at commit 943fa317a2

## Reproduction:
1. Start with no queen.
2. Have your queen die.
3. Try to evolve into the new queen.
4. Fail.
5. Wait five minutes as intended.
6. Still cant evolve.

Detailed information:

Map: LV
Number of queens before bug occurred: 1
Number of queens total before the round ended: 3
Number of times the bug occurred: 2
Roundtype: Distress

**Comment by Rohesie** [comment]
Can you expand on the conditions?
How many queens were there? What message did they get exactly?

**Comment by drawsstuff** [comment]
From what I can see, the issue comes about if there is no roundstart queen, and later a drone tries to evolve.

**Comment by DominikPanic** [comment]
Have you encountered this issue again?

**Comment by DominikPanic** [comment]
Seems to be alright after a lot of the game code refactors.
