### ISSUE TITLE
Lockable Locker Icons Don't Update

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1466]
## Reproduction:

1) Unlock a locker.
2) Lock the locker.
3) Smush your sight grapes upon the screen to see how the little green strip did not turn red.

**Comment by Ghommie** [comment]
Couldn't reproduce this bug. It may be a spriting issue with very unnoticeable differences between their icon states or a mistyped locked var on a certain secure closet subtype. Could you specify which closet did you encounter this issue on?

**Comment by Shadow-Quill** [comment]
I've noticed it (so far) on the CMO and anesthesia lockers.

**Comment by DominikPanic** [comment]
Were you able to reproduce this issue?
