### ISSUE TITLE
Televac Beacons Don't Announce

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1467]
## Testmerges:

#1375 #1426 #1440 #1439 #1438 #1445 #1446 #1337 #1444 #1453 #1452 #1451 #1450 #1449 #1448

Probably #1426.

## Reproduction:

1) Televac someone.
2) Observe no glaringly obvious message about teleporting.

**Comment by DominikPanic** [comment]
That was fixed right after in #1426
