### ISSUE TITLE
SG-85 Ammo bins aren't showing up in the req console

### ISSUE THREAD

**Issue by Notamaniac** [tgstation/TerraGov-Marine-Corps#14696]
### Description

SG-85 ammo bins aren't showing up in the weapons tab in the req console

### Test Merges

[#11624: 'TGMC Christmas 2023 [IDB IGNORE]' by RipGrayson at commit 1f2a444987](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11624)
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit c50038e215](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)
[#14618: 'tgui 5.0' by vvvv-vvvv at commit 984f58f327](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14618)
[#14671: 'Riptide' by chizzy376 at commit 519de54b2d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14671)
[#14624: 'New Gorger Primordial Ability: Oppose' by yyzsong at commit 12b6cbf8cb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14624)
[#14670: 'Nerfs scout rifle sunder, buffs penetration' by ivanmixo at commit 2d94c854eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14670)

### Reproduction Steps

1. Go to req console
2. No SG-85 ammo bin :(

### Screenshots

![no ammo bins](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/c489ccc3-9401-4043-b2e6-f2118d08e30b)

**Comment by Lumipharon** [comment]
should  be fixed.
