### ISSUE TITLE
Autoinjectors cannot be injected into hyposprays and beakers

### ISSUE THREAD

**Issue by OogaBoogaBunga** [tgstation/TerraGov-Marine-Corps#14728]
### Description

What the title says. Unless this was a balance change I dunno about.

### Test Merges

[#14671: 'Riptide' by chizzy376 at commit 6738c51087](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14671)
[#14624: 'New Gorger Primordial Ability: Oppose' by yyzsong at commit 12b6cbf8cb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14624)
[#14670: 'Nerfs scout rifle sunder, buffs penetration' by ivanmixo at commit 2d94c854eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14670)
[#14653: 'Adds Plasma Guns MJP EDITION (Cannon/Rifle)' by Pariah919 at commit 8253094648](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14653)

### Reproduction Steps

1. Hold autoinjector in one hand, and hold beaker or hypospray in the other
2. Click empty beaker/hypospray with autoinjector hand
3. Nothing happens

**Comment by QualityVan** [comment]
Should be fixed by #14733
