### ISSUE TITLE
The Future of TGMC & TGStation

### ISSUE THREAD

**Issue by n3tis** [tgstation/TerraGov-Marine-Corps#14754]
The year is 2045. The southern /tg/station lives under GREYTIDE RULE. All maintainer males are sissified. Maintainer women live to serve TIDE KINGS in vast reproduction facilities. Welcome to /tg/station's TIDE FUTURE.

Kyle Spier remembers life before the revolution – before the government-issued hormones, the sissy wigs, frilly lingerie, and mandatory chastity. He lives on the war-torn outskirts of Saint Seattle Washington, where he hides his beautiful blonde step-sister Time-Green from the clutches of the brutal New Greytide army. 

As musclebound soldiers in grey prowl the countryside searching for fertile coder women, Kyle will stop at nothing to protect sweet Time-Green's weed stash. In his black beard, flirty shitting ass, and hot piss, Kyle gives his tender weed to a gang of pitiless tider alpha soldiers: the ultimate act of courage and sacrifice. But is Kyle prepared for the overwhelming demonstration of refactoring and feature removals? The encounter brings him face-to-face with his worst fears… and his most unspeakable fantasies. 

Acclaimed author and pro greytide Whitney Ryan presents a tantalizingly political vision of the future. Her powerful, vivid, fly-on-the-wall passages of three-on-one interracial man-on-man action push the boundaries of sensual fiction. The GREY KINGS have their way with Kyle's weed stash, blowing and dragging and cursing through one of the hottest weed scenes in the history of the genre. And interspersed throughout the sizzling prose, a suspenseful narrative full of imaginative world-building unfolds. 

Experience the true power of grey bulls in black jackboots. Prepare to pay the ultimate reparations. Explore the mind-bending world of GREYTIDE FUTURE, the first book in Whitney Ryan’s brand new series.

**Comment by n3tis** [comment]
You can find more information about the book here: [click](https://imgur.com/a/qB4Lplx)

**Comment by n3tis** [comment]
You can read the book [here.](https://controlc.com/7b5c37c2)

**Comment by Lumipharon** [comment]
Bro.

**Comment by n3tis** [comment]
This wasn't completed Lumipharon. This is still a WIP.

**Comment by mdhollow** [comment]
i think kyle needs god and a SI
