### ISSUE TITLE
AMR / SR-26 target marker mode BUG

### ISSUE THREAD

**Issue by AusarAtkin** [tgstation/TerraGov-Marine-Corps#14758]
### Description

When you shoot the SR-26 in non laser/target mode it will continue to toggle the mode to deactivate. IF you only shoot it in target/laser mode it will not break.

### Test Merges

Round ID: [25045](https://scrubby.melonmesa.com/round/25045)
BYOND Version: 515.1610
Server revision compiled on: 2024-01-04T00:11:37+00:00
Master commit: [b79a22d446ead66b45f73f2661038fc62e51f26f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/b79a22d446ead66b45f73f2661038fc62e51f26f)
The following pull requests are currently test merged:
[#14671: 'Riptide' by chizzy376 at commit f52f41df25](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14671)
[#14624: 'New Gorger Primordial Ability: Oppose' by yyzsong at commit 12b6cbf8cb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14624)
[#14670: 'Nerfs scout rifle sunder, buffs penetration' by ivanmixo at commit 2d94c854eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14670)
[#14653: 'Adds Plasma Guns MJP EDITION (Cannon/Rifle)' by Pariah919 at commit ad2232de05](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14653)
[#14716: 'Behemoth 2: Now with more caffeine' by lKiseki at commit a204af22e0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14716)
[#14687: 'New automedical sounds' by Pariah919 at commit 662f359689](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14687)

Local commit: 1076806c6fcf192391def2015cd4262146ef337f
Server tools version: 6.0.1

### Reproduction Steps

1. Grab a SR-26 and Zoom/Aim it
2. Shoot it without toggling on target/laser mode
3. Then it will continuously deactivate target/laser mode when you're in zoom/aim mode
4. This prevent the gun from ever using the target/laser mode ever.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/135410935/eaa8acb7-e223-4a94-b905-a902a18dd607)

**Comment by Lumipharon** [comment]
Fixed, forgot to link.
