### ISSUE TITLE
hypospray labels dont show in storage

### ISSUE THREAD

**Issue by JoeHammad1844** [tgstation/TerraGov-Marine-Corps#14782]
### Description

in hand its fine but in storage it aint there

### Test Merges

maybe caused by #14757

### Reproduction Steps

1. be corpsman
2. vend hypospray belt

### Screenshots

how am i supposed to tell between kelotane, combat mix, imialky and hypervene in combat? or isotonic and tricord
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/130668733/343e4f5c-db12-4de8-b8d2-80f93ce8407c)

**Comment by Xander3359** [comment]
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/15b97744-4c65-4404-8560-c0a178b8dbb5)
This issue is outdated, it has been resolved somewhere around the update icon PR.
