### ISSUE TITLE
Synths cant put themselves in the robotic cradle.*

### ISSUE THREAD

**Issue by 74delta** [tgstation/TerraGov-Marine-Corps#14788]
### Description

*Without assistance, as per the title synths can only enter the robotic cradle with aid, unlike robots who can do it without help.

### Test Merges

#14767
#14623
#14716
#14653
#14670
#14624
#14671

### Reproduction Steps

1 walk up to robotic cradle as synth
2 either click+drag yourself into it or try to enter via the dropdown menu
3 denied

**Comment by DeltaFire15** [comment]
Unsure what the intent of cradle was here.

If you try to enter yourself, it ONLY allows robots, which synths aren't.
If someone else puts you in, it allows anyone non-organic, aka robots AND synths.

Not entirely certain which one of the two is intended.

**Comment by Lumipharon** [comment]
its shitcode. THere (was) a fix pr up, but the owner seemed to have given up on fixing the pr.
