### ISSUE TITLE
Cannot hear Storm Siren

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#14805]
### Description

I expect to hear storm siren when dangerous storm is on. Instead I don't hear the siren.

### Test Merges

[#14670: 'Nerfs scout rifle sunder, buffs penetration' by ivanmixo at commit 2d94c854eb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14670)
[#14653: 'Adds Plasma Guns MJP EDITION (Cannon/Rifle)' by Pariah919 at commit ad2232de05](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14653)
[#14716: 'Behemoth 2: Now with more caffeine' by lKiseki at commit ceaa08a837](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14716)
[#14767: 'Port update_appearance, alternative_appearance and ssvisoverlays' by ivanmixo at commit 629440d618](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14767)

### Reproduction Steps

1. Be in one of the maps that have dangerous storm like Big Red.
2. See in text that dangerous storm is coming.
3. No siren.
4. See marines die. 
5. lel

**Comment by Lumipharon** [comment]
You sure you have the sound on? I forget but I'm 99% sure its one of the sound setting toggles

**Comment by novaepee** [comment]
funny sound setting toggles
