### ISSUE TITLE
Combat Robot can't equip stuff into pocket slots

### ISSUE THREAD

**Issue by ChangLing** [tgstation/TerraGov-Marine-Corps#14823]
### Description

I (as a combat robot, while wearing the combat robot armor suit mount and heavy armor), removed my pocket items that I equipped via the roundstart equipment vendor, and was unable to put them back into the slot.  It was a tool pouch and a flare pouch, but I tried with a bktt pouch from the surplus vendors as well.  Could not put them into the pocket slot.

### Test Merges

Round ID: [25219](https://scrubby.melonmesa.com/round/25219)
BYOND Version: 515.1626
Server revision compiled on: 2024-01-15T04:27:46+00:00
Master commit: [633e7a22e88b8b35df06238414d90e4d81afbadf](https://github.com/tgstation/TerraGov-Marine-Corps//commit/633e7a22e88b8b35df06238414d90e4d81afbadf)
The following pull requests are currently test merged:
[#14716: 'Behemoth 2: Now with more caffeine' by lKiseki at commit ceaa08a837](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14716)
[#14822: 'Bunch of weird runtimes that broke one round then never happened again' by ivanmixo at commit 1e07667a46](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14822)
[#14820: 'Campaign: Various small tweaks loadout/perk tweaks' by Lumipharon at commit 728e992d13](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14820)

Local commit: abfea1aed34b9899139e82563cd837a332c6b50d
Server tools version: 6.1.2

### Reproduction Steps

Play a Combat Robot.
Vend some gear from the roundstart vendor that I don't remember the name of right now.
Equip your armor suit mount, your armor, and like, a pocket or something.
Remove the pocket.
Try to re-equip the pocket?

### Screenshots

![pocketless robot](https://github.com/tgstation/TerraGov-Marine-Corps/assets/4385689/c5948056-3404-4fa9-bda6-5b3ff1c85115)

**Comment by lbnesquik** [comment]
Can't reproduce.

BYOND Version: 515.1630
Server revision compiled on: 2024-03-20
Master commit: [ff5edca869e2da944e5d8ef05a72f9df5a3560f2](http://127.0.0.1:52879/commit/ff5edca869e2da944e5d8ef05a72f9df5a3560f2)
Local commit: cc1e97e4655be9020e5af21a1dfa802c54092666
