### ISSUE TITLE
Some xeno knockdowns/stuns ignore magharnesses

### ISSUE THREAD

**Issue by Aroliacue** [tgstation/TerraGov-Marine-Corps#14885]
### Description

After the latest changes to magharnesses, some knockdowns (so far definitely Puppeteer's knockdown) causes you to drop your gun entirely, even if it has a magharness and your suit slot's empty.

### Test Merges

Round ID: [25339](https://scrubby.melonmesa.com/round/25339)
BYOND Version: 515.1626
Server revision compiled on: 2024-01-21T20:33:45+00:00
Master commit: [266cdf5f49f15f22c46d6154b8e0dd73dc8f50cc](https://github.com/tgstation/TerraGov-Marine-Corps//commit/266cdf5f49f15f22c46d6154b8e0dd73dc8f50cc)
The following pull requests are currently test merged:
[#14850: 'chat style changes' by Neocloudy at commit 91fce7d484](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14850)
[#14880: 'Fixes certain click interactions' by Xander3359 at commit d89106da81](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14880)

Local commit: 518fe027815308d9d111ed5a0167f261379a7169
Server tools version: 6.1.2

### Reproduction Steps

1) Hold magharness gun, with suit on and suit slot empty (Gun in video: Laser Carbine, Magharness/bayonet/Gyroscopic Stabilizer)
2) Get knocked down by certain caste abilities (In video: Whatever knockdown Puppeteer has)
3) Observe as magharness doesn't work, cry

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/96730930/dca495d0-66bd-4826-a06e-4d600fdae055

**Comment by Aroliacue** [comment]
The video will upload eventually...........

**Comment by Lumipharon** [comment]
should be fixed as the pr was reverted.
