### ISSUE TITLE
Quick Building your Tile Instantly Deletes the Resin

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/TerraGov-Marine-Corps#14903]
### Description

Expected behaviour: The resin will build on your tile.

Pressing m2 on your own tile (Or was it sprite?) with quickbuild will place the wall then instantly delete it at the same time, deleting weeds and also making quick build clunky.

### Test Merges

#14880 
The bug is almost certainly from there, and was first noticed when that PR was test merged.

### Reproduction Steps

1. Spawn as a builder xeno
2. Secrete resin wall on your own tile/sprite

**Comment by Lumipharon** [comment]
should be fixed as the pr was reverted
