### ISSUE TITLE
Martini Belt broken

### ISSUE THREAD

**Issue by revelation-8468** [tgstation/TerraGov-Marine-Corps#15013]
### Description

The Martini Henry belt no longer has a sprite, and also cannot actually be used - I cannot put any items into it, nor can I click on it with the martini henry ammo packets to put ammo in.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [25614](https://scrubby.melonmesa.com/round/25614)
BYOND Version: 515.1626
Server revision compiled on: 2024-02-04T22:47:36+00:00
Master commit: [ddc98bea7dc0beb443a43abd7c9fea458c1416aa](https://github.com/tgstation/TerraGov-Marine-Corps//commit/ddc98bea7dc0beb443a43abd7c9fea458c1416aa)
The following pull requests are currently test merged:
[#14942: 'Warrior changes - minor reworks and rebalancing' by lKiseki at commit 1cfe22d05a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14942)
[#14960: 'Revert "Fix flamer back tank disconnecting with magharness"' by Barnet2 at commit 96299cda55](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14960)
[#14975: 'SMG-45 HP->Squashhead, new sound' by Pariah919 at commit afc29b307d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14975)
[#14957: 'Fancy announcements (again)' by Neocloudy at commit c3ab34677a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14957)
[#15005: 'Reduce time dilation from chat window messages' by MrStonedOne at commit 4b87b60f3d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15005)

### Reproduction Steps

1: Access the Marine Clothing vendor
2: Vend a Martini Henry ammo belt
3: :(

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/77151005/3132e55e-5a0a-4459-b6b8-b8508b79ed3a)

**Comment by Zangeiti** [comment]
literally unplayable
