### ISSUE TITLE
Pillar of Spring open pipe

### ISSUE THREAD

**Issue by AwkwardStereo** [tgstation/TerraGov-Marine-Corps#15029]
### Description

There's a pipe just jutting out open so any shipside xeno that can vent crawl gets a free unsealable hole that hardly anyone knows about except the shipside xeno players

### Test Merges

this shit doesn't matter

### Reproduction Steps

go to pillar of spring engineering lobby
pull up the floor tile under the photocopier
observe an oversight

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/35969040/cd7243e8-0a17-4e93-a558-d10e41f0cf71)

**Comment by Lumipharon** [comment]
99% sure someone cope removed a vent there because it was hard to spot, but then left the pipe leading to it. aylmao.
