### ISSUE TITLE
Limb support should be a component of the suit

### ISSUE THREAD

**Issue by Jalleo** [tgstation/TerraGov-Marine-Corps#1504]
https://github.com/tgstation/TerraGov-Marine-Corps/blob/master/code/modules/clothing/suits/suit_procs.dm
https://github.com/tgstation/TerraGov-Marine-Corps/blob/master/code/modules/organs/limbs.dm#L833

I think this is only used by maybe the B18 armor and ninjasuit. Can anyone confirm this?

**Comment by Ghommie** [comment]
I quite doubt the latter is even still lingering around at this point, but still a special code snowflake nevertheless.

**Comment by DominikPanic** [comment]
Feel free to share your suggestions in #dev-general on our Discord or in the forum thread, but github is for bug reports only
