### ISSUE TITLE
You can't take off ID tag through "Retrieve info tag"

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1505]
## Testmerges:

Round ID:  427 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 8f6f023ca0d67d630abf675be8754f9ca6ce003d 
The following pull requests are currently test merged: 
#1495: 'Ports /tg/ emote datums' by DominikPanic at commit 40ff1434e1 
#1493: 'New Shuttle Subsystem + escapepods' by spookydonut at commit 1e90e760cb 
#1496: 'Potentially fixes #1479' by DominikPanic at commit b7365970c7 
#1497: 'Fixes drones being unable to transfer plasma' by DominikPanic at commit 37ffc4f706 
#1455: 'G8 pouch tweaks' by MoXuT0 at commit 0857f7a9ae 
#1375: 'Weed subsystem' by psykzz at commit d49596a3ab 
#1452: 'Fixes lasgun underbarrel attachments' by DominikPanic at commit f475952556 
#1492: 'Wire datum port' by DominikPanic at commit c7dc1083c4 
#1494: 'Makes Rifle Mag Names Match the Rifles' by Alterist at commit 3328b262b3 
#1501: 'Fixes possible observer null name due to admin transformation' by DominikPanic at commit 7759c3b5f5 
#1500: 'Fixes general circuit board interactions' by DominikPanic at commit 29c8cc6723 
#1499: 'Fixes RPG reloading issues' by DominikPanic at commit 90c9d58222 
#1498: 'Fixes invisible scope buttons' by DominikPanic at commit 75e5e245a1 

## Reproduction:

Only clicking straight on ID works.

![изображение](https://user-images.githubusercontent.com/34478337/57258974-af356d00-7066-11e9-93bc-83a53bc274d7.png)

**Comment by DominikPanic** [comment]
You can't take off marine dogtags (the actual ID card), only retrieve the info tag with it, that is intended. Unless this report is about something else.

**Comment by Ghommie** [comment]
What said above, except this is pratically awful design from our ancestors, "fixing" this would be fairly easy anyway since what's actually preventing you to process that heinousity is a an if check followed by early return.

**Comment by MoXuT0** [comment]
It’s not about ID aka dog tags itself, rather info tag that you can take off corpses and deliver to memorial stone, you can’t take them by clicking «Retrieve info tag»

**Comment by Ghommie** [comment]
Ok, then this is an issue.e
