### ISSUE TITLE
Flak 88 spawns 2 Flaks, only one is real.

### ISSUE THREAD

**Issue by Teragenic** [tgstation/TerraGov-Marine-Corps#15169]
### Description

Flak 88 when vended spawns 2 flak 88s. One in hand and one on the vendor. 

### Test Merges

N/A 

### Reproduction Steps

Vend flak 88

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/67575979/371f2326-5715-4b5e-b06a-ac864ff06e0b)

**Comment by lbnesquik** [comment]
Ghost Division

**Comment by coldironwarrior** [comment]
Duplicate of #14095
Related to #14133
