### ISSUE TITLE
CPR doesn't work.

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#1526]
## Reproduction:

1) Attempt CPR on a oxy-damaged person.
2) Miss the mouth and end up shaking them.

**Comment by Ghommie** [comment]
CPR currently only work on people in critical condition (-50% to -99% health), bad design shared by all servers which could need a change, but not a bug issue unless proven otherwise.

**Comment by Shadow-Quill** [comment]
People were unable to perform CPR on me as I was suffocating (unconscious&taking damage due to oxydamage)

**Comment by DominikPanic** [comment]
Both CPR while oxydamaged and while regularly damaged are working were working, please provide the steps for reproduction.

https://puu.sh/Dq1ri/5096accad6.mp4
https://puu.sh/Dq1nZ/43fc0934b0.mp4

**Comment by Shadow-Quill** [comment]
I had internal bleeding, and so had low blood.

As I was suffocating because of this, I asked someone to CPR me. They said they couldn't.

I had QC and likely Dex in me.

**Comment by DominikPanic** [comment]
Low blood reacts with oxy damage differently, that is intended.

**Comment by Shadow-Quill** [comment]
Ah, okay.
