### ISSUE TITLE
Roomba can cause items to get stuck on screen

### ISSUE THREAD

**Issue by dallaszzz** [tgstation/TerraGov-Marine-Corps#15304]
### Description

As the title says

### Test Merges

The following pull requests are currently test merged:
[#14615: 'Revamps the Alamo with doublewide seats and enchanced player visibility' by ClosetedSkeletonGH at commit 0cf5fd1a4e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14615)
[#15283: 'adjusted values of larmor and vlarmor' by 74delta at commit e9f43a180f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15283)
[#15147: 'Attacking a resin wall channels the next attack' by Xander3359 at commit 6632451c8f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15147)
[#15292: 'Revert "Add 2 night vision goggle sets"' by Xander3359 at commit d03438c5df](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15292)
[#15212: 'Projectile code cleanup' by Lumipharon at commit 8517f2227e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15212)

### Reproduction Steps

1 open a container with items inside on the ground
2 let roomba destroy it

**Comment by Lumipharon** [comment]
afaik xander fixed this
