### ISSUE TITLE
Emperor's Guardsmen grenade attachments don't start loaded.

### ISSUE THREAD

**Issue by Rushnagar** [tgstation/TerraGov-Marine-Corps#1533]
Okay calm down with the preset issue style here.

Bug:
Guardsmen laserguns start with grenade attachments on the underbarrel, but they have 0 ammo and are completely useless. They should start loaded.

Alternatively, I'd attach bayonets to the damn thing. Nothing more lore-fitting than charging into the enemy with bayonets for the Emprah.

**Comment by DominikPanic** [comment]
This is not a bug - all weapons start with underbarrel attachments empty, that is intended.

Suggestions should go either on #dev-general in our Discord or in the official forum suggestions thread.
