### ISSUE TITLE
If the king disappears while marines are petrified, they are petrified forever

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#15336]
### Description

See title

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [26066](https://scrubby.melonmesa.com/round/26066)
BYOND Version: 515.1626
Server revision compiled on: 2024-03-08T20:45:52+00:00
Master commit: [dcaaf4b22950df0df8e8b3c0c8d4cfa72982f54f](https://github.com/tgstation/TerraGov-Marine-Corps//commit/dcaaf4b22950df0df8e8b3c0c8d4cfa72982f54f)
The following pull requests are currently test merged:
[#14615: 'Revamps the Alamo with doublewide seats and enchanced player visibility' by ClosetedSkeletonGH at commit 0cf5fd1a4e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14615)
[#15283: 'adjusted values of larmor and vlarmor' by 74delta at commit e9f43a180f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15283)
[#15147: 'Attacking a resin wall channels the next attack' by Xander3359 at commit 6632451c8f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15147)
[#15292: 'Revert "Add 2 night vision goggle sets"' by Xander3359 at commit d03438c5df](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15292)
[#15280: 'Boiler gas is now transparent, AP on direct hit increased slightly and gas radius increase' by Barnet2 at commit 834ea09933](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15280)

Local commit: a28f50d8e9d381c764985761cbe18e47373cd583
Server tools version: 6.4.0
[(F)](http://127.0.0.1:50915/tmp12372/browseroutput.html?src=[mob_3237];track=[mob_3218]) 

### Reproduction Steps

1. Be king
2. Petrify marines
3. Die
4. marines petrified for eternity
5. laugh in dchat

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65325586/af2ee42e-39c0-4028-a5ad-03cdc5b7988c)

**Comment by yyzsong** [comment]
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65325586/bfe4b8c2-d131-4e51-a1bb-b2bd6a984beb)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/65325586/f115a8d7-66fe-4cd9-9164-54af909c7dfe)
Second pic is after mack spawned in as king and re-petrified them. When they un-petrified, they could walk and be damaged, but couldn't act.

**Comment by ju45he** [comment]
I was the Teal SL pillarman, I went onto EORD with my rock and survived like 1/3rd of it before multiple people teamed against my defensless ass.
