### ISSUE TITLE
you can build things under banish portals

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15358]
### Description

title. probably most egregious when a wraith banishes a Person, then a xeno that can trap people builds a trap on the same tile before the person returns

### Test Merges

Round ID: [26081](https://scrubby.melonmesa.com/round/26081)
BYOND Version: 515.1626
Server revision compiled on: 2024-03-11T20:34:57+00:00
Master commit: [f0006b59880e4b0617187d486f4fe1da4cc61e90](https://github.com/tgstation/TerraGov-Marine-Corps//commit/f0006b59880e4b0617187d486f4fe1da4cc61e90)
The following pull requests are currently test merged:
[#14615: 'Revamps the Alamo with doublewide seats and enchanced player visibility' by ClosetedSkeletonGH at commit 0cf5fd1a4e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14615)
[#15147: 'Attacking a resin wall channels the next attack' by Xander3359 at commit 6632451c8f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15147)
[#15292: 'Revert "Add 2 night vision goggle sets"' by Xander3359 at commit d03438c5df](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15292)
[#15280: 'Boiler gas is now transparent, AP on direct hit increased slightly and gas radius increase' by Barnet2 at commit 834ea09933](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15280)
[#15340: 'Projectile fixes' by Lumipharon at commit 4d940edffd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15340)

Local commit: e737063f4ea469b671d87ff45140922cd6280e14
Server tools version: 6.4.0

### Reproduction Steps

1. banish someone
2. have a drone put down an acid well
3. person returns
4. instant acid cloud/hug/whatever

**Comment by coldironwarrior** [comment]
it just seems odd and inconsistent now that #14606 is merged because humans also have density but they don't put mobs on banish portals out

**Comment by ivanmixo** [comment]
This is not a bug. It's also not inconsistent due to none of the examples you listed having density.
