### ISSUE TITLE
wraiths can infinitely loop crushers to max charge speed causing permanent screenshake

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15356]
### Description

wraiths can loop crushers so they reach maximum speed but then they keep going with the screenshake effects and because portals aren't dependent on anything to be sustained, they can just keep causing screenshake forever if someone feeds crusher plasma

less bug and more "please put a cap on duration so people dont throw up or have a seizure". or just make portal sets require plasma to stay open, i dunno.

### Test Merges

Round ID: [26079](https://scrubby.melonmesa.com/round/26079)
BYOND Version: 515.1626
Server revision compiled on: 2024-03-11T20:34:57+00:00
Master commit: [f0006b59880e4b0617187d486f4fe1da4cc61e90](https://github.com/tgstation/TerraGov-Marine-Corps//commit/f0006b59880e4b0617187d486f4fe1da4cc61e90)
The following pull requests are currently test merged:
[#14615: 'Revamps the Alamo with doublewide seats and enchanced player visibility' by ClosetedSkeletonGH at commit 0cf5fd1a4e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14615)
[#15147: 'Attacking a resin wall channels the next attack' by Xander3359 at commit 6632451c8f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15147)
[#15292: 'Revert "Add 2 night vision goggle sets"' by Xander3359 at commit d03438c5df](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15292)
[#15280: 'Boiler gas is now transparent, AP on direct hit increased slightly and gas radius increase' by Barnet2 at commit 834ea09933](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15280)
[#15340: 'Projectile fixes' by Lumipharon at commit 4d940edffd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15340)

Local commit: e737063f4ea469b671d87ff45140922cd6280e14
Server tools version: 6.4.0

### Reproduction Steps

1. wraith sets up two portals to loop
2. crusher runs into them
3. crusher keeps looping until hitting screenshake effects
4. keep going if you want

**Comment by Lumipharon** [comment]
ruled as not a bug
