### ISSUE TITLE
Revivable bodies overlay under DNR ones

### ISSUE THREAD

**Issue by Xander3359** [tgstation/TerraGov-Marine-Corps#15375]
### Description

Dragging a revivable corpse on to the same tile as one that is DNR makes the DNR hud overlay on top of the revivable one.

### Test Merges

irrelevant

### Reproduction Steps

1. Have a DNR corpse
2. Have a revivable corpse
3. Drag the revivable corpse on to the DNR one
4. Skull overlay is placed on top.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/760c7bd5-3d1c-460f-9ada-0420045d4c4e)

https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/5e0f517e-188b-47f5-8a47-aac689f1686b

**Comment by Lumipharon** [comment]
Annoying, but not a bug. If a body is over another body, its hud icons are over as well.
