### ISSUE TITLE
you can spawn as a synth with bad eyesight

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15406]
### Description

fascinating!
normal eyesight since ur eyes are machines and not flesh orbs subject to degradation
probably happens bc synth is just a subspecies of human

### Test Merges

BYOND Version: 515.1626
Server revision compiled on: 2024-03-16T03:52:09+00:00
Master commit: [706a26d8cf9627369ae965c287500758d2eb5360](https://github.com/tgstation/TerraGov-Marine-Corps//commit/706a26d8cf9627369ae965c287500758d2eb5360)
The following pull requests are currently test merged:
[#15147: 'Attacking a resin wall channels the next attack' by Xander3359 at commit 6632451c8f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15147)
[#15340: 'Projectile fixes' by Lumipharon at commit 4d940edffd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15340)
[#15301: 'Glasses and goggles can be activated properly again' by XElectricX at commit 11276083ae](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15301)

Local commit: 61b42a6b3472d6ce9f3d4e76f515de68a1504805
Server tools version: 6.4.0

### Reproduction Steps

1. open your character customization prefs and set your eyesight to "bad"
2. spawn in as a synth
3. your eyesight is, in fact, "bad"

**Comment by Lumipharon** [comment]
how's this a bug? If you choose to have faulty eyes uh... good for you I guess?
