### ISSUE TITLE
Cloak and scoping is broken.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1542]
Scout and Sniper scopes and binos appear to have broken. And cloaks don't appear to work anymore.

Testmerges of the round were #1538: 'Mends a little smoke runtime.' by Ghommie at commit 9697fe7f32
#1518: 'synth repair' by grinkgo at commit 7eec013e35
#1186: 'Sort of porting nowadays /tg/station do_after, do_mob and progress bars.' by Ghommie at commit 83a9f06e28
#1537: 'Fixes automute runtimes' by DominikPanic at commit 1f7fcaa3f5
#1536: 'Makes the change gamemode admin verb better.' by DominikPanic at commit c268049ccf
#1535: 'Adds more in-round logging tools' by DominikPanic at commit e1a2602dfd
#1530: 'Tweaks the human inventory strip screen' by DominikPanic at commit 68bcad2b64
#1529: 'Fixes secure closet icon states' by DominikPanic at commit 0bb2c0ad54
#1528: 'Makes the "Edit Appearance" admin verb better' by DominikPanic at commit 37ad1adf4a
#1524: 'Adds code to stop showing typing icon when logged out' by Baby1991 at commit 2123f7693e
#1520: 'Purges borg code' by DominikPanic at commit 19c9c7cca8
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit 31c3a0cff8

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1540
