### ISSUE TITLE
cannot select unit amounts to pour

### ISSUE THREAD

**Issue by Aporhtonoma** [tgstation/TerraGov-Marine-Corps#15426]
### Description

try to use a beacker to select how much you will pour from it
nothing happens

### Test Merges

Round ID: [26199](https://scrubby.melonmesa.com/round/26199)
BYOND Version: 515.1626
Server revision compiled on: 2024-03-19T20:23:36+00:00
Master commit: [d38ce58f9b04b58bcb888bfeaaca717afa5a291a](https://github.com/tgstation/TerraGov-Marine-Corps//commit/d38ce58f9b04b58bcb888bfeaaca717afa5a291a)
The following pull requests are currently test merged:
[#15301: 'Glasses and goggles can be activated properly again' by XElectricX at commit 11276083ae](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15301)
[#15404: 'Sentry fix and code improvements' by Lumipharon at commit fbef14960e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15404)

Local commit: 3750c09ef6ed2658d9706373a5bda8ed0d768370
Server tools version: 6.4.0

### Reproduction Steps

get a beacker
use it
nothing happens

**Comment by Xander3359** [comment]
You have to right click it.
