### ISSUE TITLE
Wirecutters and hacking

### ISSUE THREAD

**Issue by cofecofe3** [tgstation/TerraGov-Marine-Corps#1543]
Found interesting bug - when you hacking without skill (if you CL, for example) you can don't wait end of using wirecutters on the cable - just put it back and cable cutted.

**Comment by cofecofe3** [comment]
With multitool pulsing isn't working. But with mend is working too.

**Comment by Ghommie** [comment]
Gave a quick look to #1186 which was TM'd at the time and found no proof that was the source of this issue, Lakiller.

**Comment by cofecofe3** [comment]
Anyway isn't critical problem I guess, just reported for bug
