### ISSUE TITLE
Optical meson scanner is borked

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1544]
## Testmerges:

Round ID:  453 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: b8085a3cf707548b6e45002157931b2a6b5e1ec3 
The following pull requests are currently test merged: 
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit f05e158652 
#1520: 'Purges borg code' by DominikPanic at commit 19c9c7cca8 
#1524: 'Adds code to stop showing typing icon when logged out' by Baby1991 at commit 2123f7693e 
#1528: 'Makes the "Edit Appearance" admin verb better' by DominikPanic at commit 37ad1adf4a 
#1529: 'Fixes secure closet icon states' by DominikPanic at commit 0bb2c0ad54 
#1530: 'Tweaks the human inventory strip screen' by DominikPanic at commit 68bcad2b64 
#1535: 'Adds more in-round logging tools' by DominikPanic at commit e1a2602dfd 
#1536: 'Makes the change gamemode admin verb better.' by DominikPanic at commit c268049ccf 
#1537: 'Fixes automute runtimes' by DominikPanic at commit 1f7fcaa3f5 
#1186: 'Sort of porting nowadays /tg/station do_after, do_mob and progress bars.' by Ghommie at commit 83a9f06e28 
#1518: 'synth repair' by grinkgo at commit 7eec013e35 
#1538: 'Mends a little smoke runtime.' by Ghommie at commit 9697fe7f32 

## Reproduction:

It doesn't show up turfs like it should, Green overlay also stays if you turn it off.

![изображение](https://user-images.githubusercontent.com/34478337/57551028-a3042500-7370-11e9-9169-db71b59bff85.png)

**Comment by Alterist** [comment]
As far as i know the mesonness of it was removed intentionally in CM, it should be discussed if it should be given to engineers and such. The overlay bit is a bug
