### ISSUE TITLE
nigthshade flower effects stack and can make sprites entirely invisible

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15444]
### Description

title
wowza! one-time use? not sure.

happened in round D: 26234 to at least the queen

### Test Merges

Round ID: [26235](https://scrubby.melonmesa.com/round/26235)
BYOND Version: 515.1626
Server revision compiled on: 2024-03-22T21:46:47+00:00
Master commit: [28cb45603260630394df3346428bb69e27370a25](https://github.com/tgstation/TerraGov-Marine-Corps//commit/28cb45603260630394df3346428bb69e27370a25)
The following pull requests are currently test merged:
[#15405: 'Standardizes flags to all use (flag_name)_flags' by Xander3359 at commit ed05b6d231](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15405)
[#14910: 'Adds the "Toggle Seethrough" component from TGStation to xenos' by Xander3359 at commit 18aa72e559](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14910)

Local commit: d70761febb0e8bb6f5bad92bf1026429ef37db68
Server tools version: 6.4.0

### Reproduction Steps

1. plant nightshade
2. plant nightshade
3. plant nightshade
4. ...
5. wait
6. use nightshade
7. use nightshade
8. use nightshade
9. you can't be seen

**Comment by Vincent983** [comment]
I tested it in valhalla, and it seems that nightshade doesn't cause this, what DOES cause it is toggling see-through on yourself I think?

**Comment by Vincent983** [comment]
also, if you use hunter illusions while see-through self is toggled, your clones come out invisible too

**Comment by coldironwarrior** [comment]
will close since it doesnt reflect the issue being the self-see-through and bug fix will be up shortly
