### ISSUE TITLE
"Dispenser All" on cryo storage only dispenses guns

### ISSUE THREAD

**Issue by Xander3359** [tgstation/TerraGov-Marine-Corps#15443]
### Description

- Click dispense all thinking everything will dispense
- Only guns come out

### Test Merges

.

### Reproduction Steps

- Make roomba pick up various items
- Go to cryo and click "Dispense All"
- Only guns appear

**Comment by Lumipharon** [comment]
test your prs dfjsdhfskjdnf

**Comment by lbnesquik** [comment]
Aoeugh, I'll get on this. It worked before I tried to get smart about my code.

**Comment by lbnesquik** [comment]
Right, I'll PR my fix soon, but the MRE's get lost because the roomba PR now tries to unload things first. So the game puts the MRE's into the containers area, and the MRE components into the other category.

**Comment by coldironwarrior** [comment]
fwiw it's always emptied pill bottles and stored them separate as container and the 16 pills inside of them

**Comment by lbnesquik** [comment]
> fwiw it's always emptied pill bottles and stored them separate as container and the 16 pills inside of them

That issue predates both of our PR's. I reverted to 1 month ago, and it still did that. Should probably get a fix sometimes.
