### ISSUE TITLE
Say code is buggy

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#1545]
## Testmerges:

Round ID:  453 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: b8085a3cf707548b6e45002157931b2a6b5e1ec3 
The following pull requests are currently test merged: 
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit f05e158652 
#1520: 'Purges borg code' by DominikPanic at commit 19c9c7cca8 
#1524: 'Adds code to stop showing typing icon when logged out' by Baby1991 at commit 2123f7693e 
#1528: 'Makes the "Edit Appearance" admin verb better' by DominikPanic at commit 37ad1adf4a 
#1529: 'Fixes secure closet icon states' by DominikPanic at commit 0bb2c0ad54 
#1530: 'Tweaks the human inventory strip screen' by DominikPanic at commit 68bcad2b64 
#1535: 'Adds more in-round logging tools' by DominikPanic at commit e1a2602dfd 
#1536: 'Makes the change gamemode admin verb better.' by DominikPanic at commit c268049ccf 
#1537: 'Fixes automute runtimes' by DominikPanic at commit 1f7fcaa3f5 
#1186: 'Sort of porting nowadays /tg/station do_after, do_mob and progress bars.' by Ghommie at commit 83a9f06e28 
#1518: 'synth repair' by grinkgo at commit 7eec013e35 
#1538: 'Mends a little smoke runtime.' by Ghommie at commit 9697fe7f32 

Local commit: 1a4c45b12953503da8303131fc14c78c25cc30c9 
Server tools version: /tg/station 13 Server v3.2.6.2 

## Reproduction:

Can't repo 100%, but generally some text is missing from the client but seen by others, and queen messages are rolling over to the next person.

**Comment by DominikPanic** [comment]
So far I haven't seen anything like that, please do include the steps to reproduction after you learn them.

**Comment by ondrej008** [comment]
I'm quite sure this a BYOND thing, as it happens on all SS13 servers, tg, bay, TGMC, FTL13, DS13, Leben, etc.

**Comment by ondrej008** [comment]
Basically you try to say something, you do it correctly, people see it, but it isn't in your chat log, so to you it looks like you said nothing

**Comment by DominikPanic** [comment]
Seems like it didn't happen again.
