### ISSUE TITLE
smoke grenades produce smoke where you are, instead of where the grenade is

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#1549]
TMs:
#1538: 'Mends a little smoke runtime.' by Ghommie at commit 9697fe7f32
#1518: 'synth repair' by grinkgo at commit 7eec013e35
#1186: 'Sort of porting nowadays /tg/station do_after, do_mob and progress bars.' by Ghommie at commit 83a9f06e28
#1537: 'Fixes automute runtimes' by DominikPanic at commit 1f7fcaa3f5
#1536: 'Makes the change gamemode admin verb better.' by DominikPanic at commit c268049ccf
#1535: 'Adds more in-round logging tools' by DominikPanic at commit e1a2602dfd
#1534: '[s] Fixes protected lists being able to be shown and edited' by DominikPanic at commit f52ad5ba3e
#1530: 'Tweaks the human inventory strip screen' by DominikPanic at commit 68bcad2b64
#1529: 'Fixes secure closet icon states' by DominikPanic at commit 0bb2c0ad54
#1528: 'Makes the "Edit Appearance" admin verb better' by DominikPanic at commit 37ad1adf4a
#1524: 'Adds code to stop showing typing icon when logged out' by Baby1991 at commit 2123f7693e
#1520: 'Purges borg code' by DominikPanic at commit 19c9c7cca8
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit 5859c7cd81

happens with normal smokes and cloaksmoke, whether throwing or launching

**Comment by Ghommie** [comment]
Yea, I'm fixing it.

**Comment by DominikPanic** [comment]
Fixed in #1551
