### ISSUE TITLE
you can extend the range of hivelord resin spit (not glob) by observing another xeno

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15543]
### Description

title
not that

### Test Merges

BYOND Version: 515.1633
Server revision compiled on: 2024-03-31
Master commit: [41dfae2cb3d87aee99b6340934bb50c0275154d8](http://127.0.0.1:53976/commit/41dfae2cb3d87aee99b6340934bb50c0275154d8)

### Reproduction Steps

1. be hivelord
2. set resin spit ability to active
3. observe another xeno
4. with no objects blocking your line of fire, target something around the other xeno
5. watch resin spit go far

**Comment by Lumipharon** [comment]
Not a bug, although likely not specifically intended
