### ISSUE TITLE
crushers can use rapid advance while dragging someone to (maybe) get extra critdrag tile distance before the marine dies from oxyloss

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15549]
### Description

title
not actually sure if it's considered a bug or not?
other charge abilities like defender charge drop anyone you're dragging behind you at the tile you started the charge on, so i guess i expected crusher to function the same. but i could also see it being a T3 special

how i think it works is that you can critdrag a marine and rapid advance with them grabbed. when you do this, because the ability is displacement, the tile calculation is done at the end, so the marine gets all the critdrag calculation stuff applied at the end of the rapid advance, which means you can move them your 4 tiles before any critdrag calculation comes into play.

### Test Merges

been in for a while, not super relevant

### Reproduction Steps

1. be crusher
2. crit someone
3. grab that guy
4. rapid advance in a direction away from marines
5. most likely they then get hit with whopping critdrag calc and die instantly upon you finishing the ability, instead of maybe 1 or 2 or 3 tiles into the path of the drag

**Comment by Lumipharon** [comment]
Not a bug, in the same vein that xenos can throw marines in crit around as well
