### ISSUE TITLE
you can activate boiler bombard while observing another xeno which allows you to extend the range of your bombard beyond what you can normally see

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15542]
### Description

title
uh, not that

### Test Merges

BYOND Version: 515.1633
Server revision compiled on: 2024-03-31
Master commit: [41dfae2cb3d87aee99b6340934bb50c0275154d8](http://127.0.0.1:53976/commit/41dfae2cb3d87aee99b6340934bb50c0275154d8)

### Reproduction Steps

1. be a boiler
2. stand in some direction around another xeno
3. observe them
4. use your zoom ability
5. the other xeno will serve as the center point of your zoom range, not you
6. dig for bombard
7. target for bombard
8. bombard something

### Screenshots

i have a video but it's too big

**Comment by Lumipharon** [comment]
not a bug
