### ISSUE TITLE
Holo cards do not display on a person

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/TerraGov-Marine-Corps#15586]
### Description

Holo cards which can be assigned by people with a MedHUD do not show up on the person's icon. Its listed as being set in the examination screen, but does not show it.

### Test Merges

Round ID: [26474](https://scrubby.melonmesa.com/round/26474)
BYOND Version: 515.1626
Server revision compiled on: 2024-04-04T01:13:51+00:00
Master commit: [c5118f280897281737b996268d4e4b995628464a](https://github.com/tgstation/TerraGov-Marine-Corps//commit/c5118f280897281737b996268d4e4b995628464a)
The following pull requests are currently test merged:
[#15509: 'Enables Assault Crewmen' by TiviPlus at commit 22dcb56581](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15509)
[#15505: 'Tank vendor' by TiviPlus at commit 9694891cd5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15505)
[#15563: 'Silo calc fix' by Lumipharon at commit 538c2a701e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15563)

### Reproduction Steps

1. Find somebody to put a triage card on.
2. Select a card (any card)
3. Apply the card
4. The person does not visibly have the card on their person.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/85206687/48047a8f-f8d6-43a7-a999-a8070aa6da47)
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/85206687/6aee6065-d578-4edb-bd68-4ceb29e56177)

**Comment by lbnesquik** [comment]
The scan is actually for, uh, body scanners! If someone went into a scanner, it will show something there.

**Comment by Derpguy3** [comment]
> The scan is actually for, uh, body scanners! If someone went into a scanner, it will show something there.

I'm a bit late, whoops. 
The holocards are assigned by people for the use of triage. If somebody is body scanned, it shows up where the "No scan report" would be.
