### ISSUE TITLE
Tank's shell rack and machine gun ammo box can be destroyed with a plasma cutter.

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#15593]
### Description

Title

### Test Merges

The following pull requests are currently test merged:
[#15509: 'Enables Assault Crewmen' by TiviPlus at commit 22dcb56581](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15509)
[#15505: 'Tank vendor' by TiviPlus at commit 9694891cd5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15505)
[#15563: 'Silo calc fix' by Lumipharon at commit 538c2a701e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15563)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [26493](https://scrubby.melonmesa.com/round/26493)
BYOND Version: 515.1626
Server revision compiled on: 2024-04-06T17:59:52+00:00
Master commit: [9f0da10505b7c8a8afa6bacb3d4534fb7b8c57c6](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9f0da10505b7c8a8afa6bacb3d4534fb7b8c57c6)
The following pull requests are currently test merged:
[#15509: 'Enables Assault Crewmen' by TiviPlus at commit 22dcb56581](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15509)
[#15505: 'Tank vendor' by TiviPlus at commit 9694891cd5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15505)
[#15563: 'Silo calc fix' by Lumipharon at commit 538c2a701e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15563)

Local commit: 3679059d4fd444f1679e39f3b87ddb1cdb5c0208
Server tools version: 6.4.0

### Reproduction Steps

1. Get a plasma cutter
2. Get into a tank
3. Hit the shell rack/machine gun ammo box with an active pc
4. Remove the rack/box, deleting any items in them

**Comment by Lumipharon** [comment]
this was fixed afaik
