### ISSUE TITLE
Tank multitile rotation code occasionally shits its pants and decides that its treads are made out of a living xenomorph, which it teleports in from somewhere else?

### ISSUE THREAD

**Issue by Tailiik** [tgstation/TerraGov-Marine-Corps#15602]
### Description

When you look at this in slow motion it's pretty obvious _what_ is happening, but good luck figuring out why lmao

[Slowmo video honk](https://imgur.com/a/vwO8iv8)

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 26509
BYOND Version: 515.1626
Server revision compiled on: 2024-04-08T00:32:46+00:00
Master commit: [ffa91d9cd768967abf972ceb9a1b487d21fe0f32](https://github.com/tgstation/TerraGov-Marine-Corps//commit/ffa91d9cd768967abf972ceb9a1b487d21fe0f32)
Server tools version: 6.4.0

### Reproduction Steps

1. Be a xenomorph
2. Look suspiciously like a tank tread
3. Become one with the machine

**Comment by Lumipharon** [comment]
should be fixed, was an issue with connect loc
