### ISSUE TITLE
Surplus Armor Vendor List screws up on going through different tabs

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#15623]
### Description

I was just perusing the armor lists as a spatial agent shipside Pillar of Spring, when I noticed that each list was suddenly starting to gain a Jaeger Mk.1 Infantry Helmet to the top of the list. And that it was growing every time I cycled through the list. Additionally, restocking the vendor causes it to disappear for a moment

### Test Merges

[#15603: 'SOM raiding base mission' by Lumipharon at commit 37737fde64](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15603)

### Reproduction Steps

1:Go to armor vendor
2: Vend something
3:Restock it, watch it poof for a moment

1:Go to armor vendor
2:Click on the different jaeger lists a few different times 
3:Find that the infantry helmet is now taking up several spots

### Screenshots

![infantryhelmet](https://github.com/tgstation/TerraGov-Marine-Corps/assets/44854487/0a9fbb3d-9ab6-4d21-9f3a-3b7ca30ffb72)

https://github.com/tgstation/TerraGov-Marine-Corps/assets/44854487/215cf629-235f-404b-b710-52085ad29a26

https://github.com/tgstation/TerraGov-Marine-Corps/assets/44854487/4e7e3111-95ae-4261-a64e-93de65e70051

**Comment by Lumipharon** [comment]
dup issue, its a tgui bug due to 2 or more entries with the same name
