### ISSUE TITLE
having "send order" keybinded allows you to use it at any time in any marine role

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#15659]
### Description

title
same as the previous order mark bug thing

### Test Merges

not relevant

### Reproduction Steps

1. keybind "send order"
2. spawn as squaddie
3. spam orders

**Comment by Lumipharon** [comment]
Why the fuck were NONE of these protected

**Comment by coldironwarrior** [comment]
> Why the fuck were NONE of these protected

at the very least, i tried the hold/focus/move order stuff and THOSE were protected lol
