### ISSUE TITLE
Clanging noise in pillar of spring bathroom

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#15666]
### Description

There's a constant clanging noise coming from the pillar of spring's bathroom

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [26603](https://scrubby.melonmesa.com/round/26603)
BYOND Version: 515.1626
Server revision compiled on: 2024-04-15T21:27:27+00:00
Master commit: [c2aee640c0ab2d310ac1b44d4f3f1ffde7be1f31](https://github.com/tgstation/TerraGov-Marine-Corps//commit/c2aee640c0ab2d310ac1b44d4f3f1ffde7be1f31)
The following pull requests are currently test merged:
[#15652: 'Valhalla xenos are of the xeno faction' by ivanmixo at commit 9a762b94df](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15652)
[#15612: 'Bring back banelings as minions' by BraveMole at commit 8eae3f7817](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15612)

Local commit: 934a36c8d61f3146b806938623b1fa7a9cee084d
Server tools version: 6.4.0

### Reproduction Steps

1. Get on the pillar of spring
2. Go to the bathroom
3. Hear a clanging noise
4. It won't stop

**Comment by RipGrayson** [comment]
Is this clanging near pods or staff bunks?
