### ISSUE TITLE
Flare  throw ignores queen fire immumity

### ISSUE THREAD

**Issue by Ketrai** [tgstation/TerraGov-Marine-Corps#1566]
## Reproduction:

1. get a flare grenade.

2. get a queen.

3. throw a lit flare grenade at a queen, watch them catch fire.

Flare throw uses some kind of snowflake check that seems to bypass queen immumity. Allowing you to light them on fire despite their full immumity. If a flamethrower can't do it, a flare shouldn't either.

**Comment by Ghommie** [comment]
these sort of immunities checks should always be running inside IgniteMob(), not outside. :pensive:

**Comment by DominikPanic** [comment]
Could be intended or not, we'll wait for Surrs input.

**Comment by Surrealaser** [comment]
Intended. They're supposed to be fire resistant, not proof, in the first place.
