### ISSUE TITLE
Can cade on alamo

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#15696]
### Description

The TG crafting pr removed various building checks, among them the checks that stop you from cading on the alamo.
I assume there's probably other things that are broken atm, not just that.

### Test Merges

NA

### Reproduction Steps

NA

**Comment by lbnesquik** [comment]
And why don't we allow it? Alamo is already weak and underused currently.

**Comment by QualityVan** [comment]
#15701
