### ISSUE TITLE
Audible Emotes Bug

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#1570]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 463
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 3af7941fdb65ab2c9c2bff10b7f3f4a560ca6909
The following pull requests are currently test merged:
#1552: 'Fixes otherwordly sound spamming.' by Ghommie at commit c9c84c5f0f
#1564: 'Possibly fixes another runtime' by DominikPanic at commit cb3dd612ac
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit b2ac34218b
#1563: 'Fixes evil emote runtime' by DominikPanic at commit dcef2d0a4b
#1562: 'Fixes Rohesie's runtime' by DominikPanic at commit 42704c3436
#1561: 'Fixes an ancient init runtime' by DominikPanic at commit 1ea06746e4
#1559: 'Fixes the RPG being unable to shoot different ammo types.' by DominikPanic at commit 5e11be6046
#1568: 'Fixes a race condition init runtime' by DominikPanic at commit 524ae62dee

Local commit: 11203a5ea106c31a814dc1fa74a6313099b9e922
Server tools version: /tg/station 13 Server v3.2.6.2
## Reproduction:

Just do any audible emote at all, and you'll see. The cooldown is on by default and never goes off. Also using *help tries to do all the audible emotes all at once and spams your chat with the audible emote cooldown message.

**Comment by DominikPanic** [comment]
Fixes in latest commit of #1563
