### ISSUE TITLE
Crafting anything while behind a cade returns "something is in the way"

### ISSUE THREAD

**Issue by Lauwma** [tgstation/TerraGov-Marine-Corps#15726]
### Description

Trying to craft anything while behind a cade doesn't work. This means in order to do corner cades (cades facing 2 directions on the same tile) you are forced to unscrew unwrench then drag the cade on the same tile as the other then rotate it, which is very much longer than the intended way.

### Test Merges

Round ID: [26720](https://scrubby.melonmesa.com/round/26720)
BYOND Version: 515.1626
Server revision compiled on: 2024-04-25T16:52:28+00:00
Master commit: [4f0fa7a472c3e1372dcc762f6570f3c23e0198bb](https://github.com/tgstation/TerraGov-Marine-Corps//commit/4f0fa7a472c3e1372dcc762f6570f3c23e0198bb)
The following pull requests are currently test merged:
[#15682: 'Smooth move update' by Lumipharon at commit a1f2eeb30e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15682)
[#15693: 'Removes the ability to build cades on tadpoles, adds a new mapping helper and flag' by Wisemonster at commit 7257aeeff2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15693)
[#15694: 'Removes minimum pop from Transport Crewmen' by Wisemonster at commit aa5314de1a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15694)

Local commit: 92c414f45397704eb9634e2fee31d614c9740970
Server tools version: 6.4.0

### Reproduction Steps

Go behind a cade
try to craft
Doesn't work

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/32490372/4dd69f68-5d1e-4ea2-a802-b5d9259aa583)

**Comment by lbnesquik** [comment]
Confirmed
