### ISSUE TITLE
Cades can be dragged onto the tadpole

### ISSUE THREAD

**Issue by Victor239** [tgstation/TerraGov-Marine-Corps#15746]
### Description

Cades can still be put on the tadpole.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [26746](https://scrubby.melonmesa.com/round/26746)
BYOND Version: 515.1626
Server revision compiled on: 2024-04-27T12:25:12+00:00
Master commit: 6d48411c72a6a6a8ae2796293839dcbb993b68c1
The following pull requests are currently test merged:
#15682: 'Smooth move update' by Lumipharon at commit a1f2eeb30e
#15693: 'Removes the ability to build cades on tadpoles, adds a new mapping helper and flag' by Wisemonster at commit cd0924c97e
#15694: 'Removes minimum pop from Transport Crewmen' by Wisemonster at commit aa5314de1a

Local commit: 317d4ab53f9cbb587bcc861584cb1573868d03a5
Server tools version: 6.4.0

### Reproduction Steps

- Construct cade
- Unanchor it
- Drag it onto tadpole

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/12621257/b0c8e782-46cf-444f-bdf2-05d8cd9a4e0d)

**Comment by Admiral-Gigaton** [comment]
still cant anchor it, but you can just put crates behind them and anchor those to basically do that job (then jump onto crates and be free of all issues)

**Comment by Lumipharon** [comment]
not a bug, also for what its worth, unanchored cades have much lower coverage
