### ISSUE TITLE
Xenos can slash own queen and destroy eggs

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1574]
## Testmerges:

Round ID:  466 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 3af7941fdb65ab2c9c2bff10b7f3f4a560ca6909 
The following pull requests are currently test merged: 
#1568: 'Fixes a race condition init runtime' by DominikPanic at commit 524ae62dee 
#1559: 'Fixes the RPG being unable to shoot different ammo types.' by DominikPanic at commit 5e11be6046 
#1561: 'Fixes an ancient init runtime' by DominikPanic at commit 1ea06746e4 
#1562: 'Fixes Rohesie's runtime' by DominikPanic at commit 0dc8c48482 
#1563: 'Fixes evil emote runtime' by DominikPanic at commit 51d4ef746c 
#1564: 'Possibly fixes another runtime' by DominikPanic at commit cb3dd612ac 
#1552: 'Fixes otherwordly sound spamming.' by Ghommie at commit c9c84c5f0f 
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit b2ac34218b 

## Reproduction:

Not sure if admemery or something actually fucked up.

![queenrogue](https://user-images.githubusercontent.com/34478337/57575850-31ed6c00-745b-11e9-8d76-2f8bd8758e3d.png)
![hhhhhh](https://user-images.githubusercontent.com/34478337/57575858-6f51f980-745b-11e9-9b9c-39ab7fe26203.png)

**Comment by DominikPanic** [comment]
This issue was caused by bad admin varedits
```
[2019-05-12 05:20:27.225] ### VarEdit by RipGrayson/(Zam Avaeana): /datum/hive_status/normal hivenumber=normal_hive => Corrupted
```
```
[2019-05-12 05:18:55.778] ### VarEdit by RipGrayson/(Zam Avaeana): /mob/living/carbon/Xenomorph/Crusher/mature hivenumber=normal_hive => corrupt
```
