### ISSUE TITLE
Xenos grabbing someone grabbing something else breaks things

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#15787]
### Description

Xenos grabbing other players is really buggy at the moment, causing xenos to be frozen in place and dropping the blue grab icon onto the ground (breaking whoever dropped it from grabbing things). Unsure if this only happens with xenos against other xenos, or against humans as well.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [26820](https://scrubby.melonmesa.com/round/26820)
BYOND Version: 515.1633
Server revision compiled on: 2024-05-02T09:46:55+00:00
Master commit: [afd78d252603d45679cd99739ba5a0e0a1aed8d4](https://github.com/tgstation/TerraGov-Marine-Corps//commit/afd78d252603d45679cd99739ba5a0e0a1aed8d4)
The following pull requests are currently test merged:
[#15682: 'Smooth move update' by Lumipharon at commit 873531b2e7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15682)
[#15647: 'Health analyzer update' by Neocloudy at commit 2d0d76cec0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15647)

Local commit: 9288afa6d3d33fa4faa7f50ee5af9c7781b087d8
Server tools version: 6.5.0

### Reproduction Steps

1. Be a xeno
2. See a xeno grabbing something
3. Try to grab them
4. Success
5. Get stuck in place, unable to move or really do anything along with the other xeno

**Comment by Lumipharon** [comment]
smooth move pr updated
