### ISSUE TITLE
Tank repeatedly teleports xenos to it 

### ISSUE THREAD

**Issue by Victor239** [tgstation/TerraGov-Marine-Corps#15799]
### Description

https://streamable.com/4vxy0v Ravager gets teleported to tank twice in a row (apologies for the recording being poor, it wasn't covering the whole screen for some reason)

### Test Merges

Round ID: [26845](https://scrubby.melonmesa.com/round/26845)
BYOND Version: 515.1633
Server revision compiled on: 2024-05-04T11:25:50+00:00
Master commit: f3f8624c2c2a6d75eb2a06e1fa63e03af36e127f
The following pull requests are currently test merged:
#15682: 'Smooth move update' by Lumipharon at commit ac6d5e9d27
#15647: 'Health analyzer update' by Neocloudy at commit 2d0d76cec0
#15783: 'Adds the CPC (Clone Personnel Carrier) module' by Lumipharon at commit d437ba89f6

Local commit: 85fd690a2e69568149099d36e852f404238b2008
Server tools version: 6.5.0

### Reproduction Steps

?

**Comment by Lumipharon** [comment]
why didn't this close?
