### ISSUE TITLE
Sprite Click no Longer Shoots a Burst with Melee

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/TerraGov-Marine-Corps#15800]
### Description
Clicking xeno (or human) sprites with ar11 used to melee and shoot shots at them, usually called a "point blank" or pb. I'm not sure exactly when this broke but as of round 26845 it is broken. You can mimic the effect still with directional attack since it will attack and burst, but separately, so not great.

EDIT: It doesn't work with these guns, leading me to think this is actually intentional, but its odd that they can all still fit bayonets and ar11 is basically just a normal rifle compared to the rest:
ar55
ar11
sr127
mg60
mg42
mg27
pepperball
flamethrower
### Test Merges

I don't think these affected it but: 
[#15682: 'Smooth move update' by Lumipharon at commit ac6d5e9d27](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15682)
[#15647: 'Health analyzer update' by Neocloudy at commit 2d0d76cec0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15647)
[#15783: 'Adds the CPC (Clone Personnel Carrier) module' by Lumipharon at commit d437ba89f6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15783)

### Reproduction Steps

1. Set self to harm intent
2. Get an AR-11
3. Click a xeno sprite

**Comment by Lumipharon** [comment]
These guns don't have the pb flag
