### ISSUE TITLE
Tank/APC is taking an excessive amount of damage from behemoth's stomp and primal wrath earth pillar

### ISSUE THREAD

**Issue by Wisemonster** [tgstation/TerraGov-Marine-Corps#15824]
### Description

Tanks and APCs are taking an excessive amount of damage from behemoth's stomp, earth pillar while in primal wrath, and getting hit by 3 rocks from a charge, dealing over 300 hundred damage if the stomp hits the middle of the tank while they are on top of it, over 800 damage for the primal wrath earth pillar and the charged rocks. 

### Test Merges

Round ID: [26908](https://scrubby.melonmesa.com/round/26908)
BYOND Version: 515.1633
Server revision compiled on: 2024-05-08T21:26:00+00:00
Master commit: [36c15c6577e90f1950e57301ef8ae0ea8d687e43](https://github.com/tgstation/TerraGov-Marine-Corps//commit/36c15c6577e90f1950e57301ef8ae0ea8d687e43)
The following pull requests are currently test merged:
[#15682: 'Smooth move update' by Lumipharon at commit ac6d5e9d27](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15682)
[#15647: 'Health analyzer update' by Neocloudy at commit 818ad1507e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15647)
[#15783: 'Adds the CPC (Clone Personnel Carrier) module' by Lumipharon at commit bcabb5fabf](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15783)
[#15814: 'Minimap code fix' by Lumipharon at commit 3e8f304d2b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15814)
[#15805: 'Meridian Riptide (Attempt #2 Electric Boogaloo)' by chizzy376 at commit 760d94d423](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15805)
[#15626: 'adds in Pyrogen Xenomorph Caste' by MLGTASTICa at commit 1cb1abc93f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15626)

Local commit: 817e740cac9e7c3588c1307c8ccec4463b907de8
Server tools version: 6.5.0

### Reproduction Steps

1. Be a behemoth
2. Find a tank/apc
3. Either jump on top of the middle of it, or set up 3 rocks facing it
4. Stomp, call the earth pillar, or charge the rocks
5. Watch the tank/apcs health disappear, or in the case of the apc, the whole thing disappear

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/c534c587-269c-40f6-93b7-0a9961f369af

**Comment by Lumipharon** [comment]
This isn't a bug. Behemoth simply has a TWENTY TIMES damage mult against vehicles for whatever reason.
