### ISSUE TITLE
Arachne Medbay Sleeper Borked

### ISSUE THREAD

**Issue by Araulius** [tgstation/TerraGov-Marine-Corps#15897]
### Description

expected to be able to place marine inside, and access scanner console

what ended up happening was marine disappeared, sleeper sprite appeared to not close, and the console didn't register there was anybody inside

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [27028](https://scrubby.melonmesa.com/round/27028)
BYOND Version: 515.1633
Server revision compiled on: 2024-05-18T09:40:21+00:00
Master commit: [71f5cacb1a6252d80768866b6180a43538d12cca](https://github.com/tgstation/TerraGov-Marine-Corps//commit/71f5cacb1a6252d80768866b6180a43538d12cca)
The following pull requests are currently test merged:
[#15682: 'Smooth move update' by Lumipharon at commit 7782067652](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15682)
[#15783: 'Adds the CPC (Clone Personnel Carrier) module' by Lumipharon at commit 3be0cc5806](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15783)
[#15839: 'Ports Kutjevo Refinery' by RipGrayson at commit 527e670355](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15839)

Local commit: 7ca9f1e9b03036f70d09751a23f156286f73ac75
Server tools version: 6.5.0

### Reproduction Steps

place marine inside
attempt to access console
marine has to resist out to appear again

**Comment by CoastalCookie** [comment]
![Screenshot (127)](https://github.com/tgstation/TerraGov-Marine-Corps/assets/87195459/0a53e353-9ec8-4c00-b03b-04942c27453a)
This bug is quite bad... Once put a marine inside it and lost track i was lucky he resisted out of it otherwise he would have been permanently dead

**Comment by mrhugo13** [comment]
![StrongDMM_2024-08-12_14-16-15](https://github.com/user-attachments/assets/862b36dd-1b22-4673-9e79-7fc7d7a73b02)

The DIR variable for these objects, which determines which direction they point towards, were 1 for sleeper console and 2 for the body scanner when they both should be 4 (facing east)

Here's the reference for BYOND DIR variables and which directions they point towards
![firefox_2024-08-12_14-09-12](https://github.com/user-attachments/assets/dcce6b1e-7b48-49b1-a79d-03e439b4ca75)

Mapping fix for PR as I write.
