### ISSUE TITLE
DCing or losing while dead DNRs you, but if you reconnect it doesn't unDNR you

### ISSUE THREAD

**Issue by PibeCantina** [tgstation/TerraGov-Marine-Corps#15911]
### Description

Well, i lost connection while alive, come back and i am dead, no biggy, but i am also DNR'd when i clearly didnt DNR and it was beyond me.

### Test Merges

#15783 at 3be0cc5, #15839 at 527e670, #15737 at 31e3257

### Reproduction Steps

Lose connection
Die
Reconnect
Or
Die
Lose connection
Reconnect

**Comment by Admiral-Gigaton** [comment]
after a certain amount of time, you go completely DNR. your corpse rots, cant be defib, and is also when the puppeteers can turn you into a minion. normal game function, not a bug, just happens. you can see this happen in real time with the little indicator above a corpse, where it goes from yellow, to red, to a skull. skull means rotted too much, red means you got seconds to revive, and yellow means fresh corpse.

read corpsman/guide to medicine or any of that jazz, it explains it

**Comment by PibeCantina** [comment]
> after a certain amount of time, you go completely DNR. your corpse rots, cant be defib, and is also when the puppeteers can turn you into a minion. normal game function, not a bug, just happens. you can see this happen in real time with the little indicator above a corpse, where it goes from yellow, to red, to a skull. skull means rotted too much, red means you got seconds to revive, and yellow means fresh corpse.
> 
> read corpsman/guide to medicine or any of that jazz, it explains it

I know, I am saying that you DCing does not respect this and just makes you unrevivable even if you were gone for 30 seconds
If you die, click the reconnect button, wait 10 seconds and come back, you are unrevivable

**Comment by Admiral-Gigaton** [comment]
> > after a certain amount of time, you go completely DNR. your corpse rots, cant be defib, and is also when the puppeteers can turn you into a minion. normal game function, not a bug, just happens. you can see this happen in real time with the little indicator above a corpse, where it goes from yellow, to red, to a skull. skull means rotted too much, red means you got seconds to revive, and yellow means fresh corpse.
> > read corpsman/guide to medicine or any of that jazz, it explains it
> 
> I know, I am saying that you DCing does not respect this and just makes you unrevivable even if you were gone for 30 seconds If you die, click the reconnect button, wait 10 seconds and come back, you are unrevivable

aaah, yeah thats ass, hope this gets fixed quickly

**Comment by mkvrs** [comment]
(this is intended)

**Comment by Zangeiti** [comment]
> (this is intended)
is it really intended in case you disconnect due to a bad connection or your client crashed?

**Comment by CoastalCookie** [comment]
> > (this is intended)
> 
> is it really intended in case you disconnect due to a bad connection or your client crashed?

Yes
A solution to this is by staying inside your body while dead
If you disconnect while inside your body it will stay revivable but it will give the error "soul is almost departed"
