### ISSUE TITLE
Users are able to use macros such as "rest" to bypass checks such as entering or being inside a vent.

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#1592]
## Testmerges:

Round ID: 474
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 5c0c4281810834ea8a80f7a6ea69464c6f35ad4c
The following pull requests are currently test merged:
#1577: 'Runner balance tweaks' by Rohesie at commit cff6a9abc4
#1578: 'Xenos now break barrels properly.' by DominikPanic at commit e5729fcae4
#1580: 'Gives CLF leader ammo.' by DominikPanic at commit ed36f0c78b
#1556: 'adding tox bottles to med vendors' by Ghommie at commit 4c9591202f
#1568: 'Fixes a race condition init runtime' by DominikPanic at commit 524ae62dee
#1561: 'Fixes an ancient init runtime' by DominikPanic at commit 1ea06746e4
#1563: 'Fixes evil emote runtime' by DominikPanic at commit 51d4ef746c
#1564: 'Possibly fixes another runtime' by DominikPanic at commit cb3dd612ac
#1552: 'Fixes otherwordly sound spamming.' by Ghommie at commit c9c84c5f0f
#1540: 'Ports SSinput from /tg/' by DominikPanic at commit d44234fc0b

## Reproduction:

Set a macro for "rest", enter a vent, toggle it.

**Comment by DominikPanic** [comment]
It's not about macros, you can use rest while anywhere.
