### ISSUE TITLE
you can walk over cades if you're on a high thing

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#15931]
### Description

See title.
`

### Test Merges

Unsure :3

### Reproduction Steps

1. Stand on a window frame adjacent to a barricade
2. move into the barricade
3. phazon.jpeg
4. get shot to death because you can't phase back through

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/65325586/cb070744-a470-4926-a1fb-aadaa6d1f96c

**Comment by Lumipharon** [comment]
This is intended
