### ISSUE TITLE
Pulling out a gun removes the light from the raillight

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1593]
Pulling a gun out from suit storage removes the light given by a rail light. Real annoying as survivor.

**Comment by psykzz** [comment]
Can't seem to reproduce this issue - https://streamable.com/wapck

I believe this is the relevant code path.
https://github.com/tgstation/TerraGov-Marine-Corps/blob/master/code/modules/projectiles/updated_projectiles/gun_helpers.dm#L170-L177

**Comment by DominikPanic** [comment]
I was also unable to reproduce it last time when tried, so unless you provide the exact steps we can't fix it. That's why the last issue report was closed.

**Comment by Pariah919** [comment]
I uh pulled it out of suit storage after putting it there and the light didn't work anymore. Always happens to me when doing using one.

**Comment by DominikPanic** [comment]
How did you pull it out? If it happens always, you should be able to reproduce it locally and send a video.

**Comment by DominikPanic** [comment]
Were you able to reproduce it?

**Comment by DominikPanic** [comment]
No reproduction steps provided.
