### ISSUE TITLE
Crusher's Rapid Advance doesn't activate if you click widescreen tiles.

### ISSUE THREAD

**Issue by belltop1** [tgstation/TerraGov-Marine-Corps#15939]
### Description

Clicking the 2 furthest tiles on either the left or right of your screen will cause rapid advance to not work. 
[https://cdn.discordapp.com/attachments/504094319075131402/1244881834479714314/forward_advance_doesnt_work_with_widescreen.mp4?ex=6656ba0e&is=6655688e&hm=f8dce924ca3ae3ac55bbe2131751384c7942db7cc2a50fc8f51b93dcd36919e3&](url)

### Test Merges

[#15839: 'Ports Kutjevo Refinery' by RipGrayson at commit 527e670355](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15839)

### Reproduction Steps

Above.

**Comment by Lumipharon** [comment]
pretty sure it just has a max range of 7

**Comment by Lumipharon** [comment]
Yeah, it has a max range, working as intended.
