### ISSUE TITLE
Cas engine overlays don't work properly.

### ISSUE THREAD

**Issue by Helg2** [tgstation/TerraGov-Marine-Corps#15991]
### Description

The overlay on the right engine is croped, if you raise it's layer in-game via VV to 3.1 from 3, it will fix itself. No idea why.

### Test Merges

N/A

### Reproduction Steps

Turn on cas, see croped engine overlays.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/93882977/e48c4e49-28ca-4f76-926a-cbf7df30142d)

**Comment by Lumipharon** [comment]
I believe Helg2 fixed this.

**Comment by Helg2** [comment]
Doubt I did.
