### ISSUE TITLE
Swiping red alert from Valhalla alerts the ship

### ISSUE THREAD

**Issue by Crystal9156** [tgstation/TerraGov-Marine-Corps#16010]
### Description

Expected red alert to not make the ship have a panic attack.

### Test Merges

Server revision compiled on: 2024-06-05T15:33:51+00:00

### Reproduction Steps

Go to Valhalla
Swipe red with someone
Laugh as shipside red alert starts

**Comment by CoastalCookie** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/assets/87195459/b732b3c9-c344-48ec-9cec-233e5301168e

A clip of this happening

**Comment by RipGrayson** [comment]
Fixed here, https://github.com/tgstation/TerraGov-Marine-Corps/pull/16015
