### ISSUE TITLE
Synth cannot jump due to "loss of breath"

### ISSUE THREAD

**Issue by HenryOfSkalitz** [tgstation/TerraGov-Marine-Corps#16032]
### Description

Loss of breath occurs when Marine is low on Stamina, preventing jump spams. it does not affect Xenos (they do not breathe), yet it prevents ANY jump from Synths due to them lacking Stamina in general. They cannot jump in any circumstance, and pressing button gives you the "Catch your breath!" line. Inability for Synths due to them lacking stamina seems like a bug, not a feature.

### Test Merges

None of them are related, and yet here's screenshot

https://prnt.sc/BjBKSnmn7G6Z

### Reproduction Steps

1. Be any form of Synth. TGMC Standart Synth is used in this example.

2. Press the Jump button.

3. Observe the error message you cannot resolve.

### Screenshots

https://prnt.sc/L4G6V5q1HnUn

**Comment by CoastalCookie** [comment]
Synths count as a robot and as such cannot jump

**Comment by Ragecrabbo** [comment]
Not a bug but definately needs a better message for combat robots/synths

**Comment by catmanpop** [comment]
"Your leg servos does not allow you to Jump!"

**Comment by Lumipharon** [comment]
yeah its a message issue, not a bug.
