### ISSUE TITLE
Geothermal generators not working

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/TerraGov-Marine-Corps#16035]
### Description

Fixing gens and toggling them on usually results in them ramping up to a green icon or whatever, this time the gens never gave power after being toggled, they kinda stayed "off". APC on off didnt change anything. Done on LV759

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [27331](https://scrubby.melonmesa.com/round/27331)
BYOND Version: 515.1633
Server revision compiled on: 2024-06-07T08:47:32+00:00
Master commit: [20ceee974122d07f55c84a4366a24795a42758de](https://github.com/tgstation/TerraGov-Marine-Corps//commit/20ceee974122d07f55c84a4366a24795a42758de)
The following pull requests are currently test merged:
[#15936: 'Vali Spear: The Return' by Barnet2 at commit 1a7a153ce1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15936)
[#15935: 'New Map: LV-759' by RipGrayson at commit 60601df921](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15935)
[#15926: 'Defibrillator refactor, NPCs/disconnected players rework' by Neocloudy at commit 635cde74a4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15926)

Local commit: 68a53529c76b0bd75587ded0e1b45cb5950d907a
Server tools version: 6.5.0

### Reproduction Steps

1. Fix the generators
2. Toggle them on

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17058929/ca128128-988a-4825-ac20-27202cb090ad)

**Comment by Helg2** [comment]
Perhaps there weren't any wires?

**Comment by CoastalCookie** [comment]
Seems like the thermo gens don't actually turn on at all only their sprite

**Comment by mrhugo13** [comment]
Okay so i checked this out and theres a few things that's causing this issue that can be more plainly explained with this screenshot of an LV-759 tile with a geotherm generator on it
![StrongDMM_2024-08-12_13-38-23](https://github.com/user-attachments/assets/eae9d403-7b6f-41d1-a51b-1775055ccf8f)

First and foremost, there is no actual cable under the generators for them to connect to the map's powergrid with.
Second, that floor tile, ``/turf/open/floor/urban_plating`` is not actually the standard plating tile which is used for wiring/pipes/disposals, meaning that you have to first crowbar this urban plating floor tile so you can put a power cable under it (hence why you couldn't add power cables when you tried)
Thirdly, for the other sets of generators there weren't also any power cables near them at all.
And finally fourthly, the SMES on this map were not wired to any power cables (and therefor neither the powergrid) either.

Mapping fix for a PR as I'm writing.
