### ISSUE TITLE
shrike fling works on marines that are frozen from king's ability

### ISSUE THREAD

**Issue by coldironwarrior** [tgstation/TerraGov-Marine-Corps#16051]
### Description

shrikes can fling marines trapped in stone from whatever the one king ability is

expected not that

### Test Merges

Round ID: [27369](https://scrubby.melonmesa.com/round/27369)
BYOND Version: 515.1633
Server revision compiled on: 2024-06-09T21:04:34+00:00
Master commit: [6de2c557250c0070cf559dd9c0d03fcd81ff3e1d](https://github.com/tgstation/TerraGov-Marine-Corps//commit/6de2c557250c0070cf559dd9c0d03fcd81ff3e1d)
The following pull requests are currently test merged:
[#15936: 'Vali Spear: The Return' by Barnet2 at commit 1a7a153ce1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15936)
[#15935: 'New Map: LV-759' by RipGrayson at commit 7e680d40da](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15935)
[#15926: 'Defibrillator refactor, NPCs/disconnected players rework' by Neocloudy at commit df4c8c9f1a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15926)
[#15965: 'Bull rework part 2' by Clay500z at commit a453830d29](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15965)
[#16049: 'Mostly buffs xenos across the board, nerfs speed' by Kuro020 at commit 88e97391e4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16049)

Local commit: 3d5bce32bd24fb29fcd65b2cb601f6c3e0ad57ac
Server tools version: 6.5.0

### Reproduction Steps

1. be marine
2. get turned into stone
3. shrike walks up and flings you to hell
4. die

**Comment by Lumipharon** [comment]
you can throw rocks, all xeno throw abilities work.
