### ISSUE TITLE
Stamina-Killing Stunlock (Young Defender) for more than 6s (as a One-tap.)

### ISSUE THREAD

**Issue by Redstonize** [tgstation/TerraGov-Marine-Corps#16065]
### Description

This happened twice during the same round.

Suddenly lose ALL your stamina right before and get stunned for 9 or 10s, single Tail Swipe.

Dragged away while One-Tapped.

Did not incurr ANY chemical fuck-up or internal damage (no organ damage), was full health according to MedHud's, no toxins present.
Screen was not blurry, not seeing colors.

Seems to have incurred **EXCESSIVE INSTANT** Stamina damage right before it. 
Other Xenos nowhere near him at the time. (or a least seemed)

![Capture d’écran 2024-06-12 003431](https://github.com/tgstation/TerraGov-Marine-Corps/assets/5296592/0a7c205a-51f8-4ede-a5cf-0a272c4e4abe)

Average ping: 50ms

Round ID 27409.

### Test Merges

The following pull requests are currently test merged:
[#15936: 'Vali Spear: The Return' by Barnet2 at commit 1a7a153ce1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15936)
[#15935: 'New Map: LV-759' by RipGrayson at commit b0f1b15423](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15935)
[#15926: 'Defibrillator refactor, NPCs/disconnected players rework' by Neocloudy at commit df4c8c9f1a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15926)
[#15965: 'Bull rework part 2' by Clay500z at commit a453830d29](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15965)
[#16049: 'Mostly buffs xenos across the board, nerfs speed' by Kuro020 at commit 0a7e01bbaa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16049)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [27410](https://scrubby.melonmesa.com/round/27410)
BYOND Version: 515.1633
Server revision compiled on: 2024-06-10T22:56:37+00:00
Master commit: [4c11b0a9b3ce13bf244210009f774bc0065bc58d](https://github.com/tgstation/TerraGov-Marine-Corps//commit/4c11b0a9b3ce13bf244210009f774bc0065bc58d)
The following pull requests are currently test merged:
[#15936: 'Vali Spear: The Return' by Barnet2 at commit 1a7a153ce1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15936)
[#15935: 'New Map: LV-759' by RipGrayson at commit b0f1b15423](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15935)
[#15926: 'Defibrillator refactor, NPCs/disconnected players rework' by Neocloudy at commit df4c8c9f1a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15926)
[#15965: 'Bull rework part 2' by Clay500z at commit a453830d29](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15965)
[#16049: 'Mostly buffs xenos across the board, nerfs speed' by Kuro020 at commit 0a7e01bbaa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16049)

Local commit: 2654873528649ff167f91d5156e34ca22be2c50e
Server tools version: 6.5.0

### Reproduction Steps

>Be me. Use heavy armor and energy shoold svalinn. Use MedHud to see health.

>Run into a single Young Defoonder.
>Tail swipe, can't get back up.
­>Dragged away 50ft.
>Come back, full health.
>Tail swipe. Gets dragged 20 tiles while RESIST (stunned) Get murdered by other xeno as you're down.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/5296592/1df9f3b4-d1a0-4889-aa4e-1755d563cf09)

**Comment by Redstonize** [comment]
I can assess that lasted about 10s both times, no other xenos around.
Can't fight back even though I'm NOT sleeping, just stunned.

Did not do the "get up, second swipe" bul**, It was one-tap all the way.
Second defender came in to get his assist while I was 50 meters deep in the maze.

**Comment by Lumipharon** [comment]
tailsweep does stamina damage. Kuro's buffs have buffed the stamina damage. If they had autobalance on, this could increase stamina damage even more significantly. If your stam was already low due to running/jumping etc, this could conceivably blast you straight into stam stun.

**Comment by Redstonize** [comment]
Nope. It was a Young Defender so it's definitely not primo. I would have seen it if it did two tailspins. The picture shows a different xeno, but by that time I was already in the maze after a solid 10s dragging session. Never even got the chance to get up, though I was awake.

**Comment by Redstonize** [comment]
Does Stamina crit even have the same on mob effect as their Tail Swipe ?

**Comment by Redstonize** [comment]
Or is it just lasting longer than 7-8s ?

**Comment by Lumipharon** [comment]
it doesn't crit. it just stuns you for 1 second, but if you keep having stam damage it will refresh. However even with what I stated above, this is impossible without external help from other xenos, even in the worst conditions possible.

**Comment by Redstonize** [comment]
Well then you should ask them how TF they did it. I sure would like to know.

**Comment by Wisemonster** [comment]
> Nope. It was a Young Defender so it's definitely not primo. I would have seen it if it did two tailspins. The picture shows a different xeno hitting in, but by that time I was already in the maze after a solid 10s dragging session. Never even got the chance to get up, though I was awake.

We got rid of maturity, young just means they haven't reached a certain hour time on that caste, not that they weren't primo.

**Comment by Redstonize** [comment]
Right now we can't get footage cause people aren't catching the fact that it was a single Defender doing ONE stun and then permalocks me by just "draggin" for 15 or more tiles, without doing any other reasonable stuff to make it work.

**Comment by Redstonize** [comment]
Like, is there a cheat somewhere ? Some kind of code mod that could make that work.. ? I.S.f. as there's NO way a stun can last this long without programmed intervention...

**Comment by Redstonize** [comment]
And yes, I'm refering to cheats.
