### ISSUE TITLE
Resin holes can be hidden under sprites. Same with claymores.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1608]

**Comment by psykzz** [comment]
Not a bug

**Comment by Rohesie** [comment]
Yes and no. Not exactly intended, but at the same time not very easy to fix, because if you increase the layer of resin holes you can hide stuff under them.
Maybe changing the layer of a filled resin hole to be on top of other objects?

**Comment by DominikPanic** [comment]
It is indended and I would consider it a feature, since everyone expects the behavior and hiding things has been a neat strategy.
