### ISSUE TITLE
Weeds aren't adding themselves to SSweeds on init, instead are adding them on DESTROY, likely causing QDEL issues. 

### ISSUE THREAD

**Issue by chaoko99** [tgstation/TerraGov-Marine-Corps#1612]
https://github.com/tgstation/TerraGov-Marine-Corps/blob/255df31d491df125bff4b489a51fe17b142fdc6e/code/modules/cm_aliens/weeds.dm#L29

From here to the end of the proc.

**Comment by Rohesie** [comment]
@psykzz

**Comment by psykzz** [comment]
This is intended, add_weeds takes the turf and the parent and ignores the weed itself.
SSweeds is only for weeds that need to be created, nothing else.

**Comment by DominikPanic** [comment]
This looks like you may have misread the purpose of the subsystem, though feel free to open up a larger discussion about it in our #coding channel.
