### ISSUE TITLE
Vents and scrubbers are invisible under weed

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1613]
## Testmerges:

Round ID:  506 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: b0addb74d0b9f4169006a5743621ab1c08037b5c 
The following pull requests are currently test merged: 
#1596: 'Inspection on the little smoke runtime.' by Ghommie at commit 31870a2326 
#1598: 'Update weight storage runtime fix' by Rohesie at commit 09c40070f4 
#1600: 'Add ghost hud & alerts from TG' by psykzz at commit d51fa6ca4f 
#1597: 'Ports tool_act' by Jalleo at commit 137d7c918e 
#1604: 'Fixes people not being able to respond to IRC admin PMs' by DominikPanic at commit b4c45cd7d2 
#1551: 'Fixing smoke nades and buffing phosphorus smoke.' by Ghommie at commit da49786000 
#1605: 'Smartgun resprite' by MoXuT0 at commit 30fab39b0b 

## Reproduction:

Lurking in vents seems fine, problem is vents are hard to spot without right-clicking every tile or knowing where they are.

![ass](https://user-images.githubusercontent.com/34478337/57988126-025de580-7a93-11e9-8ef8-5a19b701bc74.png)

**Comment by Rohesie** [comment]
Layer issue.

**Comment by DominikPanic** [comment]
> 
> 
> Layer issue.

*plane issue. The layers are correct.
