### ISSUE TITLE
Highlighted Text On Seperate Line in Announcement Messages

### ISSUE THREAD

**Issue by Runian** [tgstation/TerraGov-Marine-Corps#16174]
### Description

Expected: An announcement message where only the specific word/text is highlighted.
What happened: An announcement message where the specific word/text is given its own line as if there was a line break before and after it.

### Test Merges

[#15935: 'New Map: LV-759' by RipGrayson at commit 539ac2bde4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15935)
[#16001: 'Boiler Tweaks' by Barnet2 at commit 06af187fb4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16001)
[#16114: 'Desant fix' by Lumipharon at commit b8a986e73d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16114)
[#16118: 'Revert "Light interior fix"' by TiviPlus at commit c93913a1a2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16118)
[#15961: 'Opt-in squad radio TTS' by breadhunt at commit f30d58307b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15961)
[#16087: 'More chat style updates - new announcement colors, admin announcement changes, and more' by Neocloudy at commit b36594a998](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16087)
[#16097: 'Tank balance' by Lumipharon at commit 150ef270ee](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16097)

### Reproduction Steps

1. Use Text Highlights
2. Have these as the hightlighted words: "ai, mini, vert, subvert, mini, ark, shaffer, william, hive, hivemind, mortar, shells, Remote targeting set by"
3. Get announcement that features one of the words.
4. Look at announcement; it is not looking good.

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/30399783/d8ec1bc7-b56a-480f-880b-579f60123846)

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/30399783/a54b2134-baa7-49bf-87a4-309fcce466c6)

**Comment by Neocloudy** [comment]
this shall be probably fixed on next server update, please close :D
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/88008002/43c33634-f51c-452d-ace1-15fd7dc5d16e)

**Comment by CoastalCookie** [comment]
> this shall be probably fixed on next server update, please close :D
> 
> ![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/88008002/43c33634-f51c-452d-ace1-15fd7dc5d16e)
> 
> 

You should have made the pr manually close it... people open issues and then forget about them 

cause 90% of these issues are not maintained or even checked if they are valid to this day

**Comment by Runian** [comment]
oh. i have a button, whoops
