### ISSUE TITLE
Afterimages on runner pounce is clickable, and will block your clicks(slashes) after pouncing on a marine.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#16204]
### Description

Read above.

### Test Merges

Doesn't matter, none touch visual after images.

### Reproduction Steps

1. Pounce a guy, seems to happen more often if savage is off or on cooldown
2. Try to click them, seethrough wont save you here.
3. You stare at your own afterimage.

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/24631139/57061360-ac38-43fb-a429-ed7607d66562

**Comment by CoastalCookie** [comment]
While this obviously is a bug wouldn't it be nice for a balance perspective to make this a "feature"?
Otherwise runners can almost instantly slash a marine no?

**Comment by Lumipharon** [comment]
fixed
