### ISSUE TITLE
Can't join Valhala

### ISSUE THREAD

**Issue by nigtmoth** [tgstation/TerraGov-Marine-Corps#16216]
### Description

Tried to join Valhala but the menu keeps closing

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [27725](https://scrubby.melonmesa.com/round/27725)
BYOND Version: 515.1633
Server revision compiled on: 2024-07-01T00:05:53+00:00
Master commit: [7ef611ddd9b3ba7ad56e743ac3d2cf1a5fd54a3b](https://github.com/tgstation/TerraGov-Marine-Corps//commit/7ef611ddd9b3ba7ad56e743ac3d2cf1a5fd54a3b)
The following pull requests are currently test merged:
[#16001: 'Boiler Tweaks' by Barnet2 at commit 01bfeb77c5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16001)
[#15961: 'Opt-in squad radio TTS' by breadhunt at commit ae6aaa8dce](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15961)
[#16154: 'Adds Retrograde Sentinel Strain' by Notamaniac at commit d3b01c3331](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16154)
[#16082: 'Melee attacks no longer lock inputs' by Xander3359 at commit f1b9f0c981](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16082)
[#16165: 'Off-hand shooting' by Lumipharon at commit d3f7271a3f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16165)

Local commit: e76a7537aae18f0d3989634c0f990f30aebe8244
Server tools version: 6.5.0

### Reproduction Steps

1. Die as a Xenomorph
2. Decide to try out things in Valhala
3. Click Marine or Xenomorph the selection menu
4. Menu closes upon clicking a faction
5. Restart game
6. Still happens

### Screenshots

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/99149395/d83f2ebe-ffcc-47a8-a30b-28b12505a0cb)

**Comment by Hardly3D** [comment]
Going DNR seems to fix it

**Comment by Lumipharon** [comment]
this was fixed, forgot what pr
