### ISSUE TITLE
Runner still stares at their afterimage.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#16289]
### Description

Lumi's pr didn't fix it.

### Test Merges

![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/24631139/8acc4151-e229-474c-86fa-e348431a5f7a)

Tivi also said this if it helps ig. 
![image](https://github.com/tgstation/TerraGov-Marine-Corps/assets/24631139/553297b0-18af-4902-bc5b-0813744d255a)

### Reproduction Steps

1. Pounce
2. Try to slash
3. Stare at yourself.

### Screenshots

https://github.com/tgstation/TerraGov-Marine-Corps/assets/24631139/6c951a75-57ca-4853-bfcc-eb2148ffa6d0

**Comment by Ragecrabbo** [comment]
Skill issue
