### ISSUE TITLE
Teleport runtime

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#1631]
## Testmerges:

Round ID: 513
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 57045e70970150ddc33564fe427b05aa20de79c6
The following pull requests are currently test merged:
#1600: 'Add ghost hud & alerts from TG' by psykzz at commit 617471aaa4
#1596: 'Inspection on the little smoke runtime.' by Ghommie at commit 31870a2326
#1623: 'Balance tweaks.' by Rohesie at commit bc93d71d05
#1628: 'Warrior lunges grab humans in their offhand' by psykzz at commit e4b5114079
#1627: 'fixes weeds' by spookydonut at commit 1e4416a9be

## Reproduction:

Verb used: Ghost > Teleport.

```
[07:11:32] Runtime in unsorted.dm, line 927: Cannot read null.z
proc name: params2turf (/proc/params2turf)
usr: Trevorious/(Ellie 'Coffee' Weaver)
src: null
call stack:
params2turf("15:26,9:9", null, Trevorious (/client))
(/obj/screen/click_catcher): Click(null, "mapwindow.map", "icon-x=474;icon-y=265;left=1;s...")
Trevorious (/client): Click( (/obj/screen/click_catcher), null, "mapwindow.map", "icon-x=474;icon-y=265;left=1;s...")
```

**Comment by psykzz** [comment]
I don't believe this is the right runtime, this seems to happen when clicking aftering the teleport to null space.

**Comment by DominikPanic** [comment]
This is a race condition click runtime.

**Comment by DominikPanic** [comment]
Haven't seen this happen since. Will keep this open meanwhile. Possible it could have been fixed as a side effect in anothre PR.
