### ISSUE TITLE
Mech Pilots can be shocked/stunned when walking into an electrified door with mech

### ISSUE THREAD

**Issue by Aroliacue** [tgstation/TerraGov-Marine-Corps#16332]
### Description

Walking into an electrified door while in a mech will shock you through the mech and stun you for the usual duration (5-10 seconds)

What you expected to happen:
Just some sparks

What happened instead:
![image](https://github.com/user-attachments/assets/8822bbff-4bcc-4368-9eb2-95e8db670d3f)

### Test Merges

Round ID: [27952](https://scrubby.melonmesa.com/round/27952)
BYOND Version: 515.1633
Server revision compiled on: 2024-07-12T04:26:09+00:00
Master commit: [55c89f241d16706d6c78f83568fa2cc08a447b90](https://github.com/tgstation/TerraGov-Marine-Corps//commit/55c89f241d16706d6c78f83568fa2cc08a447b90)
The following pull requests are currently test merged:
[#16162: 'Attempts to give marines a trickling economy with stimulus on crash' by Ldip999 at commit d31802296e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16162)
[#16154: 'Adds Retrograde Sentinel Strain' by Notamaniac at commit 0c0b86ac5f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16154)

Local commit: 0a335331b54ba703b5383cd97ba08a9c1ccf52d8
Server tools version: 6.6.0

### Reproduction Steps

1) Electrify a door
2) Get in a mech
3) Walk into it
4) Get shocked

**Comment by lbnesquik** [comment]
That's actually very funny
