### ISSUE TITLE
Lighting issues 

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#1635]
## Testmerges:

#1627: 'fixes weeds' by spookydonut at commit 1e4416a9be
#1628: 'Warrior lunges grab humans in their offhand' by psykzz at commit e4b5114079
#1623: 'Balance tweaks.' by Rohesie at commit bc93d71d05
#1596: 'Inspection on the little smoke runtime.' by Ghommie at commit 31870a2326
#1600: 'Add ghost hud & alerts from TG' by psykzz at commit 79c5853e1a

## Reproduction:

LV624

See image below, Marine and Ghost HUD icons/slots dark when in darkness. 

https://i.imgur.com/YNIaNRj.png

and

![Bad lighting](https://user-images.githubusercontent.com/47805468/58363261-3bf96c80-7e56-11e9-9102-fd3bef7f6ab5.png)

Maybe not related but there was also LoS issues on the nexus shutters that had been closed then opened. It was blocking LoS when they were in the open state.

**Comment by Mr-Worth** [comment]
Additional problem probably related, when xeno dark vision is turned off the screen blanks out completely no matter the light level.

**Comment by Rohesie** [comment]
![dreamseeker_2rr9AdvwFm](https://user-images.githubusercontent.com/42041276/58363433-72e17980-7e7a-11e9-8536-6ea16d0cda88.png)
Relevant

**Comment by Rohesie** [comment]
No runtimes associated.

**Comment by Menshin** [comment]
Planes.

**Comment by DominikPanic** [comment]
The HUD is for @psykzz to fix but the lightning is mine. I'll have a look sometimes

**Comment by psykzz** [comment]
Fixed in latest #1600 
![image](https://user-images.githubusercontent.com/1134201/58368330-59c0e300-7ee3-11e9-9e6c-e267584473a7.png)
