### ISSUE TITLE
Ghost orbit after log out

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#1636]
Noticed as Roh logged out last night. After logging out the ghost stayed, not sure if that is intentional or not. It stayed orbiting for the whole round.

![Ghost Ghost](https://user-images.githubusercontent.com/47805468/58363816-f7260380-7e5e-11e9-9781-9cbad9e90c48.png)

## Testmerges:
#1633: 'Power runtime fixes' by Rohesie at commit c8bd365350
#1600: 'Add ghost hud & alerts from TG' by psykzz at commit 79c5853e1a
#1596: 'Inspection on the little smoke runtime.' by Ghommie at commit 31870a2326
#1623: 'Balance tweaks.' by Rohesie at commit bc93d71d05
#1628: 'Warrior lunges grab humans in their offhand' by psykzz at commit e4b5114079
#1627: 'fixes weeds' by spookydonut at commit 1e4416a9be
#1632: 'Fixing `New()` runtimes' by Rohesie at commit 1b2ff53b78

**Comment by DominikPanic** [comment]
That is intended. When you log out, your mob doesn't get deleted.
