### ISSUE TITLE
[Crash] Explosives can damage through fog

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#16413]
### Description

See title. This can injure xenos and xeno buildings to the point of their destruction

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [28231](https://scrubby.melonmesa.com/round/28231)
BYOND Version: 515.1633
Server revision compiled on: 2024-07-29T01:44:28+00:00
Master commit: [9c9bd13cb732f9436c7985ad4c91732da7d4b693](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9c9bd13cb732f9436c7985ad4c91732da7d4b693)
The following pull requests are currently test merged:
[#16162: 'Attempts to give marines a trickling economy with stimulus on crash' by Ldip999 at commit d31802296e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16162)
[#16282: 'Adds rappel to tadpole (again)' by breadhunt at commit e245fe1501](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16282)
[#16406: 'Patrol point fix (for campaign)' by Lumipharon at commit 135a1bde9e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16406)
[#16400: 'Timeshift bugfix' by Lumipharon at commit 248807333b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16400)

Local commit: 9261ac9a530c3b369d52cbd0a9c9e961f33783c9
Server tools version: 6.6.1

### Reproduction Steps

1. Throw grenade at fog
2. Our Resin silo 1 at North Western Caves (X: 37, Y: 100) is under attack! It has 930/1000 Health remaining.

**Comment by Lumipharon** [comment]
fog is nondense now, so is excluded from explosion block calcs.

Fix means it needs an explosion block value, and for explosions to not check for density.
