### ISSUE TITLE
Req platform does not send up crates when used.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1644]
The following pull requests were test merged:
#1588: 'Removal of OLD mech code (POWER LOADERS ARE VEHICLE CODE!)' by Jalleo at commit ebb82639f5
#1596: 'Inspection on the little smoke runtime.' by Ghommie at commit 31870a2326
#1502: 'Killing some machines Part 1' by Jalleo at commit 20b13f0a01
#1519: 'convert ert shuttles to use new shuttle subsystem and ert refactoring' by spookydonut at commit 6a1e49e0d8

**Comment by Pariah919** [comment]
![image](https://user-images.githubusercontent.com/46353991/58435166-09c55600-8074-11e9-948a-f773c32778ae.png)
Crates still show up as approved.

**Comment by Rohesie** [comment]
Possibly related runtime:
```
proc name: bucketJoin (/datum/timedevent/proc/bucketJoin)
src: Timer: -1 (\[0x21008a78]), TTR... (/datum/timedevent)
call stack:
Timer: -1 (\[0x21008a78]), TTR... (/datum/timedevent): bucketJoin()
Timer: -1 (\[0x21008a78]), TTR... (/datum/timedevent): New(/datum/callback (/datum/callback), 12, 0, null)
addtimer(/datum/callback (/datum/callback), 12, 0)
the retractable railing (/obj/machinery/door/poddoor/railing): open()
the supply shuttle (/obj/docking_port/mobile/supply): register()
Shuttle (/datum/controller/subsystem/shuttle): action load(Base Shuttle Template (/datum/map_template/shuttle/supply), the dock13 (/obj/docking_port/stationary/supply/reqs))
the dock13 (/obj/docking_port/stationary/supply/reqs): load roundstart()
Shuttle (/datum/controller/subsystem/shuttle): initial load()
Shuttle (/datum/controller/subsystem/shuttle): Initialize(726654)
Master (/datum/controller/master): Initialize(10, 0, 1)
```

**Comment by DominikPanic** [comment]
@Rohesie Was this TM related or does this happen on any round?

**Comment by Rohesie** [comment]
That was on a local test, so not TM related.

**Comment by spookydonut** [comment]
This was broken by #1521 @DominikPanic because is_blocked_turf was changed to return TRUE if the turf was NOT blocked.

**Comment by spookydonut** [comment]
> 
> 
> Possibly related runtime:
> 
> ```
> proc name: bucketJoin (/datum/timedevent/proc/bucketJoin)
> src: Timer: -1 (\[0x21008a78]), TTR... (/datum/timedevent)
> call stack:
> Timer: -1 (\[0x21008a78]), TTR... (/datum/timedevent): bucketJoin()
> Timer: -1 (\[0x21008a78]), TTR... (/datum/timedevent): New(/datum/callback (/datum/callback), 12, 0, null)
> addtimer(/datum/callback (/datum/callback), 12, 0)
> the retractable railing (/obj/machinery/door/poddoor/railing): open()
> the supply shuttle (/obj/docking_port/mobile/supply): register()
> Shuttle (/datum/controller/subsystem/shuttle): action load(Base Shuttle Template (/datum/map_template/shuttle/supply), the dock13 (/obj/docking_port/stationary/supply/reqs))
> the dock13 (/obj/docking_port/stationary/supply/reqs): load roundstart()
> Shuttle (/datum/controller/subsystem/shuttle): initial load()
> Shuttle (/datum/controller/subsystem/shuttle): Initialize(726654)
> Master (/datum/controller/master): Initialize(10, 0, 1)
> ```

unrelated, that runtime is an out of memory bug
