### ISSUE TITLE
You can still see everything around you when going crit 

### ISSUE THREAD

**Issue by GhostPlayer6942** [tgstation/TerraGov-Marine-Corps#16440]
### Description

going crit as still lets you see everything around you. 

I also feel like the "taking damage" red flash doesnt work, im not too sure about that but something feels off about it.

### Test Merges

[#15961: 'Squad radio TTS' by breadhunt at commit fd2840fa91](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15961)
[#16343: 'Flags' by Lumipharon at commit 8fba42ac61](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16343)

### Reproduction Steps

Be a xeno (or marine)
Go crit
See as if not crit

**Comment by GhostPlayer6942** [comment]
yea ok im 100% confident that the red flash to tell you youre being shot is broken

**Comment by QualityVan** [comment]
Fixed by #16436
