### ISSUE TITLE
Defender "Fortify" ability & nades

### ISSUE THREAD

**Issue by manufacturedinhome** [tgstation/TerraGov-Marine-Corps#16454]
### Description

Using FORTIFY you should be immovable, that is not the case when you have a nade tossed at you. Easily flung and depending on the map, flung into a kill zone or lava.

### Test Merges

Was not known issue at the time.

### Reproduction Steps

Toss nade at DEFENDER xeno whist in his FORTIFY state.

**Comment by Lumipharon** [comment]
Fortify works fine, testing live.
