### ISSUE TITLE
Cooldown limitations on automated loadout vendor

### ISSUE THREAD

**Issue by iansdoor** [tgstation/TerraGov-Marine-Corps#16500]
So with req given out endless ammo and guns and also you are able to reload your marine loadout. A person can do this infinite amount of times over. There is just something wrong with this.
![Screenshot_796](https://github.com/user-attachments/assets/61ca8eba-b0f3-423a-8a17-7a8ad91746b1)

**Comment by ivanmixo** [comment]
There is infact, nothing wrong with this
