### ISSUE TITLE
Pyrogen tornadoes can go through FOB shutters

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#16560]
### Description

Per title.

### Test Merges

#16504, #15961, #16557

### Reproduction Steps

1. Be a Pyrogen.
2. Stand in front of FOB shutters.
3. Attempt to use the Fire Storm ability while aiming for a tile that is behind the shutters.
4. Watch as fire tornadoes just go through.

**Comment by WoodenTucker** [comment]
its funny
