### ISSUE TITLE
Emptying sandbag deletes the first emptied sandbag

### ISSUE THREAD

**Issue by TellyLsc** [tgstation/TerraGov-Marine-Corps#16606]
### Description

Find stacks of filled sandbags, right click to empty it as per description.
Notice that the empty sandbags under you are less bags than it should've been.

### Test Merges

Round ID: [30765](https://scrubby.melonmesa.com/round/30765)
BYOND Version: 515.1633
Server revision compiled on: 2024-09-29T02:59:52+00:00
Master commit: [e43a5e5eecbb29d70391d062e887f06708f8b77c](https://github.com/tgstation/TerraGov-Marine-Corps//commit/e43a5e5eecbb29d70391d062e887f06708f8b77c)
The following pull requests are currently test merged:
[#16557: 'Aim mode replacement' by Lumipharon at commit e4a8424c04](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16557)
[#16515: 'Bluesummers Wreck Site [NEW MAP]' by blackdav123 at commit 6ff020e07a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16515)
[#16572: 'Lower xeno ratio' by Lumipharon at commit 717aa87dd2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16572)
[#16542: 'Dancer Praetorian Strain' by Runian at commit 63ab00cbed](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16542)
[#16600: 'Temporary hotfix for stripmenu equipping' by ivanmixo at commit ae12f47463](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16600)
[#16605: 'Revert "Makes xenomorph health/sunder healing, evo progress, maturity, and plasma regen scale based on delta_time/second_per_tick"' by lKiseki at commit b92579906c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16605)

Local commit: 45ba67220ee0ff9b9e3400562dd147ccb66829f2
Server tools version: 6.9.0

### Reproduction Steps

Find stacks of filled sandbags, right click to empty it as per description.
Notice that the empty sandbags under you are less bags than it should've been.

**Comment by Arturlang** [comment]
my bug, will fix
