### ISSUE TITLE
Moths appear as some human monstrosity with wings.

### ISSUE THREAD

**Issue by AIIAmoth** [tgstation/TerraGov-Marine-Corps#1662]
## Testmerges:
#1637, #1596, #1519, #1626, #1652 

## Reproduction:
Be a moth, simply by spawning one in via DEBUG or transforming you/someone else into a Moth via Player Panel.
![bald moth](https://user-images.githubusercontent.com/42506823/58530268-1fd63200-81ac-11e9-874b-eb26231957d6.png)

**Comment by DominikPanic** [comment]
Fixed in #1653
