### ISSUE TITLE
Select Equipment menu does not apply ID/Jobs/Skills/Radios/Weapons/etc.

### ISSUE THREAD

**Issue by blackdav123** [tgstation/TerraGov-Marine-Corps#16628]
### Description

The select equipment admin verb (the one with tgui, not the ancient Rank and Equipment menu) does not apply IDs/Jobs/Skills/Radios making it not very useful for spawning survivors and other jobs that need these things.

Certain roles have things and others do not. 

- Survivors will spawn with all of their equipment except for IDs and radios, and also do not get their skills.
- Most loadouts in the General tab do not receive most of their equipment, including guns, ids, radios, pouches, and anything in containers.
- Job loadouts such as ERTs and shipside roles receive all of their equipment, but without any skills and with blank ID cards.

### Test Merges

n/a

### Reproduction Steps

1. Use Select Equipment verb
2. Apply a loadout
3. No skills/jobs/etc!

**Comment by Lumipharon** [comment]
Is the select equipment menu, not select job menu.
