### ISSUE TITLE
Sentries don't actually turn off when undeployed

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#16668]
### Description

What is says on the tin. If a sentry is undeployed (i.e. inside a sentry deploy system, not just an item),  they are still fully functional.
The only thing stopping them from firing in the past was that they'd simply continuously runtime. After that was fixed, they now function normally while inside their little egg.

### Test Merges

NA

### Reproduction Steps

NA

**Comment by Helg2** [comment]
Amazing
