### ISSUE TITLE
Plasma cannon shatter sends xenos flying

### ISSUE THREAD

**Issue by blackdav123** [tgstation/TerraGov-Marine-Corps#16778]
### Description

Shatter mode on the plasma cannon sends xenos flying 5 tiles.

### Test Merges

[#16674: 'squad/Radio TTS fix' by Lumipharon at commit 240cead51c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16674)
[#16662: 'TTS order announcements/hivemind' by TiviPlus at commit 6d5402d1e8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16662)
[#16504: 'Metnal Mining Operation (REVIVAL)' by PibeCantina at commit 0de0b521e6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16504)
[#16717: 'Rebalances Crash' by blackdav123 at commit fd1a60c83a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16717)
[#16711: 'Xeno Mutations/Personal Upgrades' by Runian at commit d546f19fc7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16711)
[#16725: 'Adds new marine race: Prototype Supersoldier' by TiviPlus at commit 25f3edbbde](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16725)
[#16664: 'Adds bloodthirster Rav strain' by TiviPlus at commit f4c00e22c5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16664)

### Reproduction Steps

1. Spawn defiler
2. Select shatter mode on plasma cannon
3. Enjoy

### Screenshots

https://github.com/user-attachments/assets/cfb7c01b-a6aa-4502-a1e5-06a82abb75d5

**Comment by Woker2004** [comment]
I sure love the part where plasma cannon gets another feature that launches xenos multiple tiles
