### ISSUE TITLE
Reindeer gloves breaks hands

### ISSUE THREAD

**Issue by CoastalCookie** [tgstation/TerraGov-Marine-Corps#16847]
### Description

When you open a present you have the possibility of getting reindeer gloves
These gloves use the same code as zombie claws it seems as such you can't drop them nor can they be removed

### Test Merges

[#16662: 'TTS order announcements/hivemind' by TiviPlus at commit 6d5402d1e8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16662)
[#16504: 'Metnal Mining Operation (REVIVAL)' by PibeCantina at commit 1c8b65aecd](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16504)
[#16761: 'Crash: Marines only add job points if xenos are under balanced' by Runian at commit 72dcb783e2](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16761)
[#16820: 'TGMC Christmas 2024' by RipGrayson at commit 0d8e755422](https://github.com/tgstation/TerraGov-Marine-Corps//pull/16820)

### Reproduction Steps

Open christmas present
Get reindeer glove
Can't use the hand you have them in

### Screenshots

![Screenshot (2)](https://github.com/user-attachments/assets/2a748815-532d-4431-9aa3-b6d1cbfc5f31)

**Comment by CoastalCookie** [comment]
I would test and reproduce it...
But i can't even build the code without it giving a error and dying.

**Comment by ivanmixo** [comment]
Fix this for next christmas PR, otherwise these aren't in the game, test merged PR issue on PR that wasn't intended on being merged. Please leave these as comments on the relevant PRs in the future.
