### ISSUE TITLE
Monkey speech issues.

### ISSUE THREAD

**Issue by Ghommie** [tgstation/TerraGov-Marine-Corps#1686]
## Testmerges:
Local test, none.

## Reproduction:
Take over a monkey mob, try to talk smack, no chat message, no speech bubble pop up. emote messages probably unaffected (only tried *me successfully).

Runtime:
```
[2019-05-30 14:46:01.577] runtime error: type mismatch: "chimpers" |= /list (/list)
 - 
[16:46:32] Runtime in say.dm,116: type mismatch: "chimpers" |= /list (/list)
  usr: Ghom/(monkey (778))
  usr.loc: (Hallway Starboard (173, 76, 3))
```
@DominikPanic.

**Comment by DominikPanic** [comment]
Monkeys are not even supposed to be playable.

**Comment by Ghommie** [comment]
Yea, they are definitely not. But that's not an excuse for a squallid lack of maintenance of this, amongst other stuff, we definitely don't want.

**Comment by DominikPanic** [comment]
Should just be removed altogether tbh

**Comment by Ghommie** [comment]
...yeeeeeeeeeep.
