### ISSUE TITLE
Monkey mask overlay issue.

### ISSUE THREAD

**Issue by Ghommie** [tgstation/TerraGov-Marine-Corps#1687]
## Testmerges:
Local test, none. Pretty sure this one has been around ever since before DMCA as I noticed this oddity long time ago, someone even did a shitcode trick on facehuggers code to circumvert it at the time.

## Reproduction:
Equip a standard gas mask on a monkey. Then remove it. Look at how the mask overlay will still lingers around.
Dunno if this too applies to the back slot as I didn't check.

**Comment by DominikPanic** [comment]
Just another reminder to purge monkey code tbh
