### ISSUE TITLE
Hotkey bugs

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#1725]
Players were reporting that TAB was not switching them to default hotkeys.
Xeno player reported that they could not change intents with new hotkeys.
## Testmerges:

(Didn't copy, most recent set of test merges from Rounds 536 and 537)

## Reproduction:
Unknown, did not experience it. 

![runtimes broken](https://user-images.githubusercontent.com/47805468/58745182-7ccb2580-8402-11e9-9a67-3be0dcae1ee4.PNG)

I have runtime logs from part way through one of the rounds but I don't know if they are sanitized and can be posted publicly. Leads ping me on discord if you need them from me.

**Comment by DominikPanic** [comment]
@psykzz

**Comment by DominikPanic** [comment]
Fixed in latest commit of #1700
