### ISSUE TITLE
You can see through walls as xeno, HUD issues

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1741]
## Testmerges:

Round ID:  538 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: abb4fb833ba4bccbfb5f75d9427b31543c248cd6 
The following pull requests are currently test merged: 
#1694: 'm39 on back' by Rohesie at commit 275aa8c733 
#1740: 'Fixes Alt walking and Ctrl facing' by psykzz at commit 59d55215f8 
#1732: 'Slight hud refactor to /tg/ standard' by DominikPanic at commit 7023ce06c1 
#1731: 'Improves launch pod error handling' by DominikPanic at commit 9405910430 
#1730: 'A few more silicon fixes and camera interaction changes' by DominikPanic at commit 09617bc9c7 

## Reproduction:

Lobby > join as xeno > larva > this. Hud is gone except human sprite at corner and hands however I could still click invisible parts of hud to enable/disable night vision.

![aaaa](https://user-images.githubusercontent.com/34478337/58832267-40dcce00-8657-11e9-93c8-eedc6841a58a.png)

Also limb selection at bottom corner doesn't have consistent colours. Some parts are dark-red, other just regular red.

![aaaaaaa](https://user-images.githubusercontent.com/34478337/58832448-9f09b100-8657-11e9-8f39-a66d0673545b.png)

**Comment by DominikPanic** [comment]
The xeno sight one is intended.
