### ISSUE TITLE
You can't bind keybinds or use the old pg up and pg down hotkey to swap hands.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1745]
The following pull requests were test merged:
#1694: 'm39 on back' by Rohesie at commit 275aa8c733
#1740: 'Fixes Alt walking and Ctrl facing' by psykzz at commit 59d55215f8
#1732: 'Slight hud refactor to /tg/ standard' by DominikPanic at commit 7023ce06c1
#1731: 'Improves launch pod error handling' by DominikPanic at commit 9405910430
#1730: 'A few more silicon fixes and camera interaction changes' by DominikPanic at commit 09617bc9c7

**Comment by DominikPanic** [comment]
@psykzz
