### ISSUE TITLE
Xeno acid spit does nothing

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1747]
## Testmerges:

Round ID:  540 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: abb4fb833ba4bccbfb5f75d9427b31543c248cd6 
The following pull requests are currently test merged: 
#1694: 'm39 on back' by Rohesie at commit 275aa8c733 
#1740: 'Fixes Alt walking and Ctrl facing' by psykzz at commit 59d55215f8 
#1732: 'Slight hud refactor to /tg/ standard' by DominikPanic at commit 7023ce06c1 
#1731: 'Improves launch pod error handling' by DominikPanic at commit 9405910430 
#1730: 'A few more silicon fixes and camera interaction changes' by DominikPanic at commit 09617bc9c7 

## Reproduction:

Spitted like 5-6 times at marines left at round end, it did nothing. Only acid puddle damaged them.

![aaaaaa](https://user-images.githubusercontent.com/34478337/58835755-77b6e200-865f-11e9-8dcb-dfa49b250099.png)

**Comment by Rohesie** [comment]
Were you trying to spit someone laying on the ground?

**Comment by MoXuT0** [comment]
On ground and standing, spits just did nothing. Engie was placing a cade and I click right on him. Nothing happened.

**Comment by psykzz** [comment]
I watched this from an admin POV there was damage. Amelia ran as soon as the spit landed, they took about 20% visible health damage (seen by the ghost hud).

(Talking about the first spit done, after that i didn't continue to follow)

**Comment by MoXuT0** [comment]
Need to test it more because in next round on LV I was fighting queen and she dealt no damage at all with acid spits. Gonna try out spitter and see if this still an issue.

**Comment by psykzz** [comment]
Tested this locally, Spit directly on a human doesn't hit them, however if you shoot past the human it does hit.

The damage i saw, was from standing on the spit.

**Comment by DominikPanic** [comment]
Spitting directly should hit, confirming this as a bug
