### ISSUE TITLE
dir 4 and 8 swapped for security cameras

### ISSUE THREAD

**Issue by KwinOriginal** [tgstation/TerraGov-Marine-Corps#1783]
## Reproduction:

If you put dir = 8 on military-grade cameras, they will be shifted to the right (not left, like intended) and vice-versa for the 4. This may cause some confusion.

**Comment by DominikPanic** [comment]
Dir 8 = west, you want it facing west and being on the wall to the right.
Dir 4 = east, you want it facing east and being on the wall to the left.

**Comment by KwinOriginal** [comment]
If that's the case, then it's wrong with 1 and 2
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.06.19, 12:39, LaKiller8 <notifications@github.com> schrieb:
Dir 8 = west, you want it facing west and being on the wall to the right.
Dir 4 = east, you want it facing east and being on the wall to the left.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tgstation/TerraGov-Marine-Corps/issues/1783?email_source=notifications\u0026email_token=ALMZBGCO2HIU5PGTK6LWFNTPZI3GJA5CNFSM4HVTHLVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXFPCOA#issuecomment-499839288",
"url": "https://github.com/tgstation/TerraGov-Marine-Corps/issues/1783?email_source=notifications\u0026email_token=ALMZBGCO2HIU5PGTK6LWFNTPZI3GJA5CNFSM4HVTHLVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXFPCOA#issuecomment-499839288",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DominikPanic** [comment]
You're right, in the .DMI they are swapped.
