### ISSUE TITLE
Following the AI doesn't follow the AI Eye

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#1794]
## Testmerges:
Server-Side Code Modifications:  https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm 

Round ID:  548 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 95c0c76d030d682ade96f07daedbae825f3ffe20 
The following pull requests are currently test merged: 
#1791: 'Fixes being unable to interact with camera computers' by DominikPanic at commit e487c67968 
#1786: 'Fixes camera orientation' by DominikPanic at commit 440aa6cdf1 
#1788: 'Fixes a fingerprint runtime.' by DominikPanic at commit e33efa41c0 
#1789: 'Fixes layers of items related to actions' by DominikPanic at commit 1bb8cfae5a 
#1694: 'm39 on back' by Rohesie at commit 275aa8c733 
#1757: 'Adds new firing sounds for some weapons' by MoXuT0 at commit 3e26b4e17c 
#1758: 'Adds more explosion sounds' by MoXuT0 at commit 67c096955e 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit 3f86655d11 
#1770: 'Adds imaginary friends for the mentors.' by DominikPanic at commit 9b229a079a 
#1790: 'Fixes latejoining' by DominikPanic at commit fedc54fc8f 
#1792: 'Fixes more bad do_afters' by DominikPanic at commit 99609558d8 

Local commit: 5b182e0067fee73447d2d1bfa439b9cb4bbd7404 
Server tools version: /tg/station 13 Server v3.2.6.2 
## Reproduction:

When an AI speaks
The follow mechanic goes to the mob, not the AI Eye.

**Comment by DominikPanic** [comment]
Does this work differently on /tg/?

**Comment by DominikPanic** [comment]
Just checked, it does
