### ISSUE TITLE
Weeds show up under walls and window frames

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1819]
## Testmerges:

Round ID:  557 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 73f07c774ab876e36061dc3edbee9de002517054 
The following pull requests are currently test merged: 
#1815: 'Makes the pod launcher logging better.' by DominikPanic at commit ce68163d5c 
#1809: 'Another missed do_after' by DominikPanic at commit aab233539d 
#1810: 'Fixes an admin runtime.' by DominikPanic at commit 553c1083ad 
#1803: 'Makes the AI unable to interact with dropship doors.' by DominikPanic at commit 511e0a1b48 
#1804: 'Cleans up some dirty perspective modifications' by DominikPanic at commit 78e7ed6c21 
#1798: 'Fixes ghost forms not saving properly' by DominikPanic at commit fa0adbfd21 
#1799: 'Makes admins able to fully rename any mobs via VV, not just /living' by DominikPanic at commit 7843329b5f 
#1800: 'Fix new player references' by psykzz at commit 346ba64455 
#1801: 'Adds round IDs to the note panel.' by DominikPanic at commit fcc3d440bc 
#1796: 'Following the AI will now follow the eye as an observer' by DominikPanic at commit cdd73e1343 
#1770: 'Adds imaginary friends for the mentors.' by DominikPanic at commit c7d03f47ba 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit 3f86655d11 
#1758: 'Adds more explosion sounds' by MoXuT0 at commit 67c096955e 
#1757: 'Adds new firing sounds for some weapons' by MoXuT0 at commit ac896e083a 
#1694: 'm39 on back' by Rohesie at commit 275aa8c733 
#1789: 'Fixes layers of items related to actions' by DominikPanic at commit 1bb8cfae5a 
#1791: 'Fixes being unable to interact with camera computers' by DominikPanic at commit bde43cddee 
#1797: 'Fixes AI death state' by DominikPanic at commit c2dba365f1 
#1808: 'Combines the rank/equipment/squad admin verbs, slight PP tweaks' by DominikPanic at commit 8995384498 
#1807: 'Adds a varset_callback to reduce the proc amount' by DominikPanic at commit 77560e603f 
#1805: 'Adds a slight delay to watchlists to prevent join race condition' by DominikPanic at commit 4d45a3604e 
#1814: 'Makes AI report verbs more modular.' by DominikPanic at commit 0ac09beb93 
#1813: 'Set the ghost notification for detpack the user' by psykzz at commit 22c2dc6de8 
#1812: 'Fixes airlock welding' by DominikPanic at commit 050cd10e76 
#1811: 'Ensure we save keybindings after all changes' by psykzz at commit 87c79e176e 
#1817: 'Gives B18 tacticool gloves' by MoXuT0 at commit 8715b3a537 
#1816: 'Fixes blood overlay for boots, adds different icon for pyro boots' by MoXuT0 at commit 3b44ed3f99 

## Reproduction:

L A Y E R S

![layers](https://user-images.githubusercontent.com/34478337/59151912-917f6d00-8a43-11e9-8f85-7bd1c4228b0e.png)

**Comment by DominikPanic** [comment]
@spookydonut This is likely related to #1627 since walls are now on a different plane.
