### ISSUE TITLE
You can put items in storage at any range

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1823]
## Testmerges:

Round ID:  558 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 570746f4029952fac6860993e2b11e1b817bbeac 
The following pull requests are currently test merged: 
#1816: 'Fixes blood overlay for boots, adds different icon for pyro boots' by MoXuT0 at commit 3b44ed3f99 
#1817: 'Gives B18 tacticool gloves' by MoXuT0 at commit 8715b3a537 
#1811: 'Ensure we save keybindings after all changes' by psykzz at commit 87c79e176e 
#1812: 'Fixes airlock welding' by DominikPanic at commit 050cd10e76 
#1813: 'Set the ghost notification for detpack the user' by psykzz at commit 22c2dc6de8 
#1814: 'Makes AI report verbs more modular.' by DominikPanic at commit 0ac09beb93 
#1805: 'Adds a slight delay to watchlists to prevent join race condition' by DominikPanic at commit 4d45a3604e 
#1807: 'Adds a varset_callback to reduce the proc amount' by DominikPanic at commit 77560e603f 
#1808: 'Combines the rank/equipment/squad admin verbs, slight PP tweaks' by DominikPanic at commit 8995384498 
#1789: 'Fixes layers of items related to actions' by DominikPanic at commit 1bb8cfae5a 
#1694: 'm39 on back' by Rohesie at commit 275aa8c733 
#1757: 'Adds new firing sounds for some weapons' by MoXuT0 at commit ac896e083a 
#1758: 'Adds more explosion sounds' by MoXuT0 at commit 67c096955e 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit 3f86655d11 
#1801: 'Adds round IDs to the note panel.' by DominikPanic at commit fcc3d440bc 
#1804: 'Cleans up some dirty perspective modifications' by DominikPanic at commit 78e7ed6c21 
#1803: 'Makes the AI unable to interact with dropship doors.' by DominikPanic at commit 511e0a1b48 
#1810: 'Fixes an admin runtime.' by DominikPanic at commit 553c1083ad 
#1809: 'Another missed do_after' by DominikPanic at commit aab233539d 
#1815: 'Makes the pod launcher logging better.' by DominikPanic at commit ce68163d5c 
#1820: 'Fixes a sleeper runtime' by DominikPanic at commit 7c2d968741 
#1818: 'Fixes a to_chat runtime.' by DominikPanic at commit 8cd7553b01 
#1538: 'Mends a not-so-little race condition smoke runtime on rockets & co.' by Ghommie at commit d8e3156a0d 

## Reproduction:

Pick up something you can equip/place in storage > open any box > press hotkey for equip > storage now won't close if get far away from it and you can place items inside.

![изображение](https://user-images.githubusercontent.com/34478337/59152024-61d16480-8a45-11e9-8f6d-e1379f5984cd.png)

**Comment by DominikPanic** [comment]
A video would be absolutely lovely, can't seem to reproduce it locally. Or a more detailed description.

**Comment by MoXuT0** [comment]
Alright, I'll explain on pack of cigarettes. Get near pack > grab one cigarette > make sure you have place to equip it to (pouch or whatever) > press hotkey for equip > cigarette should be now equiped or placed in storage > open any storage you have, for example helmet > it will now show you both storages and you can place cigarette  back inside at any range.
