### ISSUE TITLE
generators require tools in a specific order, but don't stop you from using the wrong tool

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#1827]
1. weld ye generator
2. wrench ye generator
2.5. "You start repairing the generator's tubing and plating..."; progress bar of magic appears
3. bar completes
4. jack all happens, feel bad as you realise you used the wrong tool

**Comment by DominikPanic** [comment]
more of a QoL thing than a bug

**Comment by Rohesie** [comment]
If it's giving wrong information it's kind of a bug.

**Comment by DominikPanic** [comment]
REeeeeeeeeeeeeeeeeeeee
