### ISSUE TITLE
Smoke runtime:

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#1840]
## Testmerges:

Round ID: 564
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 1f41d021f0c09096b5cd0fc3027c5dbd846bc632
The following pull requests are currently test merged:
#1832: 'Fixes a race condition xeno action runtime' by DominikPanic at commit b555b20626
#1807: 'Adds a varset_callback to reduce the proc amount' by DominikPanic at commit 77560e603f
#1816: 'Fixes blood overlay for boots, adds different icon for pyro boots' by MoXuT0 at commit 3b44ed3f99
#1817: 'Gives B18 tacticool gloves' by MoXuT0 at commit 8715b3a537
#1812: 'Fixes airlock welding' by DominikPanic at commit 050cd10e76
#1814: 'Makes AI report verbs more modular.' by DominikPanic at commit 0ac09beb93
#1805: 'Adds a slight delay to watchlists to prevent join race condition' by DominikPanic at commit 4d45a3604e
#1808: 'Combines the rank/equipment/squad admin verbs, slight PP tweaks' by DominikPanic at commit 8995384498
#1789: 'Fixes layers of items related to actions' by DominikPanic at commit 1bb8cfae5a
#1757: 'Adds new firing sounds for some weapons' by MoXuT0 at commit ac896e083a
#1758: 'Adds more explosion sounds' by MoXuT0 at commit 67c096955e
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit 3f86655d11
#1801: 'Adds round IDs to the note panel.' by DominikPanic at commit fcc3d440bc
#1804: 'Cleans up some dirty perspective modifications' by DominikPanic at commit 7d2c9639b3
#1803: 'Makes the AI unable to interact with dropship doors.' by DominikPanic at commit 511e0a1b48
#1810: 'Fixes an admin runtime.' by DominikPanic at commit 553c1083ad
#1815: 'Makes the pod launcher logging better.' by DominikPanic at commit ce68163d5c
#1820: 'Fixes a sleeper runtime' by DominikPanic at commit 7c2d968741
#1818: 'Fixes a to_chat runtime.' by DominikPanic at commit 8cd7553b01
#1538: 'Mends a not-so-little race condition smoke runtime on rockets & co.' by Ghommie at commit d8e3156a0d
#1825: 'Standarizing pills init.' by Ghommie at commit a13facf4ae
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f
#1831: 'Fixes a race condition launching humans into nullscape on nesting' by DominikPanic at commit 732de572e7
#1830: 'Fixes frustrating repairs of generators.' by DominikPanic at commit bcff745e46
#1839: 'Fixes admin ghosts not being properly deleted allowing for duplication' by DominikPanic at commit c826b0b292
#1837: 'Fixes AI interaction with certain machines' by DominikPanic at commit 292906d1f3
#1834: 'Xenos do not keep the skills of previous lives anymore.' by DominikPanic at commit eb275460a8

## Reproduction:

```
[03:45:03] Runtime in smoke.dm, line 98: Cannot execute null.effect smoke().

proc name: apply smoke effect (/obj/effect/particle_effect/smoke/proc/apply_smoke_effect)
src: the smoke (/obj/effect/particle_effect/smoke/xeno/neuro)
src.loc: null
call stack:
the smoke (/obj/effect/particle_effect/smoke/xeno/neuro): apply smoke effect(null)
the smoke (/obj/effect/particle_effect/smoke/xeno/neuro): process(20)
Objects (/datum/controller/subsystem/processing/obj): fire(0)
Objects (/datum/controller/subsystem/processing/obj): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
````

**Comment by DominikPanic** [comment]
@Ghommie
