### ISSUE TITLE
Hunter Ghost alert is tiny

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#1871]
## Testmerges:

Round ID:  574 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 5a882e74600e6669ffa869d2563495b33d38f380 
The following pull requests are currently test merged: 
#1868: 'Cleans up unused or shit mob procs' by DominikPanic at commit 2a0e86c453 
#1869: 'Slight unused or bad object code cleanup' by DominikPanic at commit 2965c46f6a 
#1861: 'You can no longer rest in vents.' by DominikPanic at commit 2e0e6e9727 
#1850: 'Makes sure 99% of attack_hands have proper parent logic.' by DominikPanic at commit e51d009142 
#1851: 'Makes sure 99% of Topic calls have proper parent logic' by DominikPanic at commit 7edeca1afd 
#1855: 'Allows boiler left click to bombard again.' by DominikPanic at commit 23dece7327 
#1857: 'Fixes being able to cheese with tank weapon switching.' by DominikPanic at commit c7d48059e5 
#1858: 'Fixes prae acid being able to spray through walls' by DominikPanic at commit e0887850c8 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8d36 
#1863: 'Fixes an issue with storage insertion' by DominikPanic at commit fc68851c48 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit 3f86655d11 
#1810: 'Fixes an admin runtime.' by DominikPanic at commit 553c1083ad 
#1815: 'Makes the pod launcher logging better.' by DominikPanic at commit d8a3bed9d8 
#1825: 'Standarizing pills init.' by Ghommie at commit 459ac7a9de 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1866: 'Ports cinematics from /tg/' by DominikPanic at commit c20b8ebe4f 
#1865: 'Adds species into the edit appearance menu' by DominikPanic at commit 618e20f4c4 
#1864: 'Makes the admin equipment menu take one less click' by DominikPanic at commit 15f6540b11 
#1769: 'Xeno Shrike' by Rohesie at commit f408154a73 

Local commit: 3236dc3e79ee8bad6586afefb1979b0c51eb7b7f 
Server tools version: /tg/station 13 Server v3.2.6.2 
## Reproduction:

![image](https://user-images.githubusercontent.com/1134201/59300831-0a6f0680-8c88-11e9-97f7-3645e64436bf.png)

**Comment by Rohesie** [comment]
That is an issue on how 48x48 sprites are done.

**Comment by MoXuT0** [comment]
I believe it also applies to any xeno with 48x48 sprite.

![tiny](https://user-images.githubusercontent.com/34478337/59534875-2842a280-8ef8-11e9-840a-4a4a4754d6e4.png)

**Comment by Rohesie** [comment]
It is a sprite issue that will require the xenos to be modified to match the pattern of the queen, or any other we decide on.
