### ISSUE TITLE
Microwaves not to working at all.

### ISSUE THREAD

**Issue by uomo91** [tgstation/TerraGov-Marine-Corps#1920]
## Testmerges:

REPO: Merging PRs #1900, #1901, #1902, #1903, #1769, #1866, #1829, #1825, #1815, #1810, #1766, #1860, #1851, #1850, #1869, #1868, #1876, #1888, #1886, #1905...

## Reproduction:

During the third round of testing last night, June 12th 2019, while playing on LV I noticed that microwaves seem not to work at all. We had just disembarked from the dropship and I had made my way into the small canteen/bar place just to the West. Having forgotten to eat before departing the station I had a small bit of hunger, so I took two donk pockets from the counter and put them in the microwave. I could not open the GUI for the microwave at all (thus, unable to turn it on), and further, when I examined the microwave it stated its contents were empty, presumably meaning these donk pockets were sent to the tear in the fabric of reality.

Unable to reproduce locally, microwaves seem to make donk pockets just fine provided you only put one of them in, else produces a burnt mess, told this is intended behavior. However, there is some visual buggyness with the buttons in the GUI, pictured below.
https://i.imgur.com/t3Oiyll.png

**Comment by Rohesie** [comment]
This is how microwaves used to work in the old days, child of summer.

**Comment by francinum** [comment]
Many of the non-central combat features have mostly been left to rot and ignored by the previous team of maintainers, so some bugginess is to be expected. Once we clean up some central balance issues we can start repairing these sorts of bugs.

**Comment by Rohesie** [comment]
Visual buginess on the UI aside, this is exactly how old microwaves work: if you do a right single recipe combo you'll get a single valid food item back. If you do anything else you'll get a burned mess.

**Comment by DominikPanic** [comment]
The visual one is a bug though
