### ISSUE TITLE
stop pulling keybind is broken

### ISSUE THREAD

**Issue by spookydonut** [tgstation/TerraGov-Marine-Corps#1926]
should be !M.pulling

street cred to @qwertyquerty for finding this

**Comment by spookydonut** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/blob/baec3a6a230f6e8536439a990b8cb06b1f87fc13/code/datums/keybinding/mob.dm#L60

**Comment by qwertyquerty** [comment]
bruh wheres muh street cred
