### ISSUE TITLE
Dropship console planetside does nothing

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1940]
## Testmerges:

Round ID:  592 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 131b5fa45d687ea374c5d9c82c7a5f6de74ca341 
The following pull requests are currently test merged: 
#1932: 'Removes the clown survivor.' by DominikPanic at commit 0a3e74977e 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit e6adbfa46a 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8d36 
#1866: 'Ports cinematics from /tg/' by DominikPanic at commit 8015f0d6d8 
#1868: 'Cleans up unused or shit mob procs' by DominikPanic at commit 5f07c493f9 
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e 
#1900: 'Xeno devour refactor' by Rohesie at commit 75f5655bf7 
#1918: 'Fixes Theseus map issues' by DominikPanic at commit a475d0cd98 
#1921: 'Fixes Prison Station visual issues' by DominikPanic at commit ed58fbbb92 
#1922: 'Fixes ice colony visual issues' by DominikPanic at commit 9734b542d0 
#1924: 'Fixes LV visual map issues' by DominikPanic at commit 3436f883ce 
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31 
#1851: 'Makes sure 99% of Topic calls have proper parent logic' by DominikPanic at commit 158d558eb6 
#1850: 'Makes sure 99% of attack_hands have proper parent logic.' by DominikPanic at commit fb9929c9b2 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1902: 'Fixes explosions deleting worn items' by DominikPanic at commit c5521256ac 
#1930: 'Fixes stop pulling keybind' by DominikPanic at commit 7a0dfc4866 
#1929: 'Fixes a few view visual issues' by DominikPanic at commit a89a4558f5 
#1928: 'Admin level tweaks' by DominikPanic at commit 9e2c24b61c 

## Reproduction:

Only clicking can be heard, nothing pops out.

**Comment by DominikPanic** [comment]
`/obj/machinery/computer/shuttle_control` is not coded in @spookydonut

**Comment by spookydonut** [comment]
Working as intended basically.
