### ISSUE TITLE
Cow gets deleted from crate if you break it as xeno

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1950]
## Testmerges:

Round ID:  593 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: c2477e9afa700c6c6e531d3272f7b01e5865536f 
The following pull requests are currently test merged: 
#1934: 'Changes the PO slots to 2' by DominikPanic at commit 124379d3f2 
#1938: 'Possibly fixes some qdeling issues' by DominikPanic at commit 3c33a2bee2 
#1937: 'Facehuggers won't attach to someone on fire' by psykzz at commit 96b10b2d58 
#1935: 'Fixes another attackby runtime' by DominikPanic at commit 95217cb283 
#1936: 'Fixes another timer issue' by DominikPanic at commit 8c1726269b 
#1932: 'Removes the clown survivor.' by DominikPanic at commit 0a3e74977e 
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit e6adbfa46a 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8d36 
#1868: 'Cleans up unused or shit mob procs' by DominikPanic at commit 5f07c493f9 
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e 
#1900: 'Xeno devour refactor' by Rohesie at commit 75f5655bf7 
#1921: 'Fixes Prison Station visual issues' by DominikPanic at commit ed58fbbb92 
#1922: 'Fixes ice colony visual issues' by DominikPanic at commit f265f85aee 
#1924: 'Fixes LV visual map issues' by DominikPanic at commit 3436f883ce 
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31 
#1851: 'Makes sure 99% of Topic calls have proper parent logic' by DominikPanic at commit 158d558eb6 
#1850: 'Makes sure 99% of attack_hands have proper parent logic.' by DominikPanic at commit 2cce1bdd96 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1930: 'Fixes stop pulling keybind' by DominikPanic at commit 7a0dfc4866 
#1929: 'Fixes a few view visual issues' by DominikPanic at commit a89a4558f5 
#1928: 'Admin level tweaks' by DominikPanic at commit 9e2c24b61c 
#1939: ' Improve SSdirection assignments' by psykzz at commit 854f70873f 
#1946: 'Fixes turret locking issues.' by DominikPanic at commit b408300f2d 
#1945: 'Fixes barricade repair issues' by DominikPanic at commit edfa9a7151 

## Reproduction:

Every single round on LV random cow gets deleted by xenos. God know how many LV rounds there were and how many cows got deleted. They are not just dying, they're getting vanquished into abyss where only darkness exists. Thousands of cows keep wandering abyss looking for marines to rescue them. But they won't come, evil xenos always get the crate first condemning another cow to endless wandering. Please fix it for all those cows.
 
![cowded](https://user-images.githubusercontent.com/34478337/59538385-3a294300-8f02-11e9-8855-b981e66c821e.png)

**Comment by Rohesie** [comment]
This is horrible!
