### ISSUE TITLE
Turret lights go off randomly.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#1953]
The following pull requests were test merged:
#1945: 'Fixes barricade repair issues' by DominikPanic at commit edfa9a7151
#1946: 'Fixes turret locking issues.' by DominikPanic at commit b408300f2d
#1939: ' Improve SSdirection assignments' by psykzz at commit 854f70873f
#1928: 'Admin level tweaks' by DominikPanic at commit 9e2c24b61c
#1929: 'Fixes a few view visual issues' by DominikPanic at commit a89a4558f5
#1930: 'Fixes stop pulling keybind' by DominikPanic at commit 7a0dfc4866
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f
#1850: 'Makes sure 99% of attack_hands have proper parent logic.' by DominikPanic at commit 2cce1bdd96
#1851: 'Makes sure 99% of Topic calls have proper parent logic' by DominikPanic at commit 158d558eb6
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31
#1924: 'Fixes LV visual map issues' by DominikPanic at commit 3436f883ce
#1922: 'Fixes ice colony visual issues' by DominikPanic at commit f265f85aee
#1921: 'Fixes Prison Station visual issues' by DominikPanic at commit ed58fbbb92
#1900: 'Xeno devour refactor' by Rohesie at commit 75f5655bf7
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e
#1868: 'Cleans up unused or shit mob procs' by DominikPanic at commit 5f07c493f9
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8d36
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit e6adbfa46a
#1932: 'Removes the clown survivor.' by DominikPanic at commit 0a3e74977e
#1936: 'Fixes another timer issue' by DominikPanic at commit 8c1726269b
#1935: 'Fixes another attackby runtime' by DominikPanic at commit 95217cb283
#1937: 'Facehuggers won't attach to someone on fire' by psykzz at commit 96b10b2d58
#1938: 'Possibly fixes some qdeling issues' by DominikPanic at commit 3c33a2bee2
#1934: 'Changes the PO slots to 2' by DominikPanic at commit 124379d3f2
#1949: 'Fixes razorwire deletion issues' by DominikPanic at commit e5ac44a28e
#1947: 'Fixes microwave interface issues' by DominikPanic at commit 5ecc51348a

**Comment by DominikPanic** [comment]
Seems to be a processing issue, I'll look into it SoonTM
