### ISSUE TITLE
Taking off your uniform doesn't drop your armor.

### ISSUE THREAD

**Issue by DominikPanic** [tgstation/TerraGov-Marine-Corps#196]
Yes, I introduced this bug, I'll fix it in the near future hopefully. Such is the coder life.

**Comment by Alterist** [comment]
put the required_under back, but make it just use the clothing/under/ parent instead of specific jumpsuits

**Comment by MrStonedOne** [comment]
The repo has moved to https://github.com/tgstation/TerraGov-Marine-Corps

**Comment by MrStonedOne** [comment]
Nevermind

**Comment by DominikPanic** [comment]
Fixed in #216
