### ISSUE TITLE
Synth can't access APCs

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#1977]
## Testmerges:

#1964 #1955 #1956 #1957 #1959 #1960 #1962 #1963 #1967 #1969 #1970 #1966 #1965 #1931 #1945 #1946 #1930 #1829 #1905 #1876 #1868 #1860 #1766 #1937 #1938 #1949 #1947 #1973 #1972

## Reproduction:

As a synth, when I attempted to access the APC just east of prison engineering, it gave me the message "You slot your fingers into the APC interface and siphon off some of the stored charge for your own use." Other APCs I had interacted with previously worked fine. This incident only happened after I restored external power.

**Comment by DominikPanic** [comment]
lmao this is what I get for using /tg/code

**Comment by DominikPanic** [comment]
Anyway will likely fix after lighting since that will allow us to use good machine and area code.
