### ISSUE TITLE
Can't dismantle APC properly

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1983]
## Testmerges:

Round ID: 601
BYOND Version: 512.1464
Server revision compiled on:
Master commit: e3be108
The following pull requests are currently test merged:
#1955: 'Fixes #1941' by spookydonut at commit 2aa71bc
#1956: 'Fixes an ERT timer runtime' by DominikPanic at commit b9a3913
#1957: 'fixes queen calldown bug' by spookydonut at commit 1059407
#1958: 'Adds AI eye capability to the overwatch consoles' by DominikPanic at commit 6c9a2c8
#1959: 'Gives the AI manifest, allows it to interact with more machines.' by DominikPanic at commit 71e8fac
#1960: 'Fixes largecrate smashing' by DominikPanic at commit 5e3067d
#1962: 'Allows opening links in chat again' by DominikPanic at commit 5463485
#1963: 'Allows users to easily check jobban reason, possibly fixes bad output' by DominikPanic at commit cf80630
#1967: 'Ports holopad talk, slightly cleans up say code' by DominikPanic at commit dec4e4c
#1969: 'Ports the outfit manager, allowing for json loading' by DominikPanic at commit c2d6704
#1970: 'Fixes asset topic sanity' by DominikPanic at commit 61bc200
#1966: 'Balance changes to the GAL9' by psykzz at commit cfa2f58
#1965: 'Add extra attachments to the ERT shuttles.' by psykzz at commit 58b7e6f
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81b
#1945: 'Fixes barricade repair issues' by DominikPanic at commit 8a5faeb
#1946: 'Fixes turret locking issues.' by DominikPanic at commit b408300
#1939: ' Improve SSdirection assignments' by psykzz at commit 854f708
#1930: 'Fixes stop pulling keybind' by DominikPanic at commit 5e001be
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfa
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab
#1868: 'Cleans up unused or shit mob procs' by DominikPanic at commit 5f07c49
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8
#1766: 'LOS Reduces screech effectiveness' by psykzz at commit e6adbfa
#1937: 'Facehuggers won't attach to someone on fire' by psykzz at commit 96b10b2
#1938: 'Possibly fixes some qdeling issues' by DominikPanic at commit 3c33a2b
#1949: 'Fixes razorwire deletion issues' by DominikPanic at commit e5ac44a
#1947: 'Fixes microwave interface issues' by DominikPanic at commit 5ecc513
#1973: 'Fixes admin rename logging' by DominikPanic at commit e42f2d1
#1972: 'Makes the forceMove in EORG INVOKE_ASYNC to help with lag' by DominikPanic at commit da07d3f

## Reproduction:

If APC is broken, you can't dismantle it. It get stuck on place where you either hit it and nothing happens or it just says "Close APC first".

**Comment by DominikPanic** [comment]
Related to #1977 but not a duplicate
