### ISSUE TITLE
Flares don't produce light

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#1992]
## Testmerges:

Round ID:  605 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 3fae3cc59fd522ce0bac1716ef539143ca4c1523 
The following pull requests are currently test merged: 
#1986: 'Fix ghost alpha for admin made ghosts' by psykzz at commit d62b7de9bf 
#1987: 'Checks if /tg/ regression fixes elusive runtime' by DominikPanic at commit e9e7e2590b 
#1980: 'Xeno content check on regurgitate' by Rohesie at commit c7210c2e34 
#1964: 'Lighting controller port from /tg/' by DominikPanic at commit 5a6dcb177f 
#1967: 'Ports holopad talk, slightly cleans up say code' by DominikPanic at commit dec4e4c709 
#1969: 'Ports the outfit manager, allowing for json loading' by DominikPanic at commit c2d6704da2 
#1970: 'Fixes asset topic sanity' by DominikPanic at commit 61bc200a9c 
#1966: 'Balance changes to the GAL9' by psykzz at commit cfa2f58e5d 
#1965: 'Add extra attachments to the ERT shuttles.' by psykzz at commit 8f82aa7b85 
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81be49 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31 
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8d36 
#1938: 'Possibly fixes some qdeling issues' by DominikPanic at commit 3c33a2bee2 
#1973: 'Fixes admin rename logging' by DominikPanic at commit e42f2d1989 
#1972: 'Makes the forceMove in EORG INVOKE_ASYNC to help with lag' by DominikPanic at commit da07d3feae 
#1982: 'Fixes aheal not getting rid of larva' by DominikPanic at commit 4b4f74d179 

## Reproduction:

![изображение](https://user-images.githubusercontent.com/34478337/59567705-cad65f00-9079-11e9-9225-02f0862fa0f1.png)

**Comment by DominikPanic** [comment]
Fixes in latest commit of #1964
