### ISSUE TITLE
Keybinding for ravager's second wind doesn't work

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2002]
## Testmerges:

Round ID:  607 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: be767315f22f980180dc20b88df9f8956de4e611 
The following pull requests are currently test merged: 
#1986: 'Fix ghost alpha for admin made ghosts' by psykzz at commit d62b7de9bf 
#1987: 'Checks if /tg/ regression fixes elusive runtime' by DominikPanic at commit e9e7e2590b 
#1980: 'Xeno content check on regurgitate' by Rohesie at commit c7210c2e34 
#1964: 'Lighting controller port from /tg/' by DominikPanic at commit d2ebe4ffdd 
#1967: 'Ports holopad talk, slightly cleans up say code' by DominikPanic at commit dec4e4c709 
#1969: 'Ports the outfit manager, allowing for json loading' by DominikPanic at commit c2d6704da2 
#1970: 'Fixes asset topic sanity' by DominikPanic at commit 61bc200a9c 
#1966: 'Balance changes to the GAL9' by psykzz at commit cfa2f58e5d 
#1965: 'Add extra attachments to the ERT shuttles.' by psykzz at commit 8f82aa7b85 
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81be49 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31 
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 4df5be8d36 
#1938: 'Possibly fixes some qdeling issues' by DominikPanic at commit 3c33a2bee2 
#1973: 'Fixes admin rename logging' by DominikPanic at commit e42f2d1989 
#1972: 'Makes the forceMove in EORG INVOKE_ASYNC to help with lag' by DominikPanic at commit da07d3feae 
#1982: 'Fixes aheal not getting rid of larva' by DominikPanic at commit 4b4f74d179 
#1995: 'Fixes xeno hud not showing dead humans' by MoXuT0 at commit e5c1fe1851 
#1994: 'Fixes initial marine shuttle launch cooldown.' by DominikPanic at commit e83eee205d 

## Reproduction:

Bind ravager's second wind for any button (H for me) > click it > nothing happens.

**Comment by DominikPanic** [comment]
@psykzz

**Comment by MoXuT0** [comment]
Cooldown is also broken

**Comment by psykzz** [comment]
This doesn't work because it requires you to click someone, a keybind can't trigger that click. Needs some more thought.

**Comment by Rohesie** [comment]
How come? Second wind has no external target.

**Comment by psykzz** [comment]
Sorry you are 100% right i was looking at the other ravager skills that were not working, and made the comment at like 3am.
Ill look into this more.

**Comment by Rohesie** [comment]
hehe
