### ISSUE TITLE
Chemical Grenades

### ISSUE THREAD

**Issue by LittleFrenchFuck** [tgstation/TerraGov-Marine-Corps#2045]
## Reproduction:

As I said on discord, there seems to be a problem with chem nades. These would include: Explosive Nades doing a little poof and then only leaving the floor tile on which they were detonated dirty, Smoke Nades not having an effect such as Space Drugs and Nades with only the reagents in them such as acid not hurting or not having any effect at all.
I think that should be all.

**Comment by DominikPanic** [comment]
`Nades with only the reagents in them such as acid not hurting or not having any effect at all.`
This may be intended

**Comment by DominikPanic** [comment]
1. Exploside nades work fine https://puu.sh/DUvaf/7a770dd36d.mp4
2. Smoke nades also seem to work fine https://puu.sh/DUvfB/c12d81856a.mp4
3. Is intended for balance purposes
