### ISSUE TITLE
Ammo boxes can't be refilled with the new extended SMG mags

### ISSUE THREAD

**Issue by DominikPanic** [tgstation/TerraGov-Marine-Corps#205]
Yet another thing I coded poorly and will have to fix. FeelsBadMan.

**Comment by MrStonedOne** [comment]
The repo has moved to https://github.com/tgstation/TerraGov-Marine-Corps

**Comment by MrStonedOne** [comment]
Ignore me

**Comment by DominikPanic** [comment]
Fixed in #215
