### ISSUE TITLE
Bast doors on LV

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#2081]
## Testmerges:

#2074: 'Cooldown fix and cleanup' by Rohesie at commit 28011dfa6d
#2055: 'Jump to Area ugly hack' by Rohesie at commit cad0bfc89b
#1987: 'Checks if /tg/ regression fixes elusive runtime' by DominikPanic at commit e9e7e2590b
#1964: 'Lighting controller port from /tg/' by DominikPanic at commit eb0ae3b90b
#1966: 'Balance changes to the GAL9' by psykzz at commit cfa2f58e5d
#1965: 'Add extra attachments to the ERT shuttles.' by psykzz at commit 8f82aa7b85
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81be49
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 8f6d7dc56a
#2004: 'HUD improvements.' by Rohesie at commit e554838437
#2048: 'Adds sounds for hud and binoculars, reduces volume of some very loud ones' by MoXuT0 at commit e2fa60dba7
#1769: 'Xeno Shrike' by Rohesie at commit 7bb8d2384c
#1904: 'Implements classic and hotkey keybinds' by psykzz at commit ae180eb84e

## Reproduction:

The blast doors on the Nexus are not allowing vision to pass through. I saw it once before weeks ago but not recently. I think it is the blast doors not updating when they are crowbar'd open but I am not sure if it related to the new light.

![inside nexus](https://user-images.githubusercontent.com/47805468/59981663-d5ce4980-95bb-11e9-8a53-210cb2e9bb65.PNG)
![nexus door](https://user-images.githubusercontent.com/47805468/59981664-d5ce4980-95bb-11e9-8e64-569b6aa8a23b.PNG)
![Outside nexus](https://user-images.githubusercontent.com/47805468/59981665-d5ce4980-95bb-11e9-9476-99cc2a738a4d.PNG)

**Comment by MoXuT0** [comment]
Happens with all blast doors I've seen so far

**Comment by psykzz** [comment]
This seems to be related to dynamic lighting between zones that have it on and off.

**Comment by MoXuT0** [comment]
If I remember correctly, it was an issue before lightning refactor. Maybe it got something to do with density/opacity not updating properly.

**Comment by Rohesie** [comment]
This is not present on master:
![1](https://user-images.githubusercontent.com/42041276/60062530-fd163b00-96cf-11e9-8493-9e55b2f74a5f.png)
![2](https://user-images.githubusercontent.com/42041276/60062535-030c1c00-96d0-11e9-878b-fcffe72839b1.png)
Thus: #1964
