### ISSUE TITLE
Landing light on LV don't produce light

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2083]
## Testmerges:

Round ID:  624 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: cd265db711da1fb8063767ccb7a93107a58201eb 
The following pull requests are currently test merged: 
#2074: 'Cooldown fix and cleanup' by Rohesie at commit 28011dfa6d 
#2055: 'Jump to Area ugly hack' by Rohesie at commit cad0bfc89b 
#1987: 'Checks if /tg/ regression fixes elusive runtime' by DominikPanic at commit e9e7e2590b 
#1964: 'Lighting controller port from /tg/' by DominikPanic at commit eb0ae3b90b 
#1966: 'Balance changes to the GAL9' by psykzz at commit cfa2f58e5d 
#1965: 'Add extra attachments to the ERT shuttles.' by psykzz at commit 8f82aa7b85 
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81be49 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31 
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 8f6d7dc56a 
#2004: 'HUD improvements.' by Rohesie at commit e554838437 
#2048: 'Adds sounds for hud and binoculars, reduces volume of some very loud ones' by MoXuT0 at commit e2fa60dba7 
#1769: 'Xeno Shrike' by Rohesie at commit 7bb8d2384c 
#1904: 'Implements classic and hotkey keybinds' by psykzz at commit ae180eb84e 

## Reproduction:

Forgot to screenshot that, but will get one eventually. They are turned on but no light around them.

**Comment by Rohesie** [comment]
#1964
