### ISSUE TITLE
PMCs lack the skills required to be competent ERT

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#2144]
They don't seem to have the required skills
SG didn't have SG skill along with other issues.

These were manually spawned in via admin panel, which could've caused issues.

**Comment by DominikPanic** [comment]
This is an admin mistake
```
10:28 PM] LaKiller8 | Thomas Echard: did you set their skills or did you just select equipment?
[10:28 PM] AIIA: Just equipment.
```
