### ISSUE TITLE
notes don't show apostrophes correctly

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#2150]
![image](https://user-images.githubusercontent.com/20996272/60375403-00c3fd80-9a01-11e9-81e9-6adec1a004ac.png)
![image](https://user-images.githubusercontent.com/20996272/60375410-03beee00-9a01-11e9-9193-50cf9975fe8e.png)

literally
unplayable
@DominikPanic

**Comment by DominikPanic** [comment]
I was this close to just closing this.
