### ISSUE TITLE
occasionally people have job "Xenomorph" on overwatch

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#2165]
![image](https://user-images.githubusercontent.com/20996272/60390515-574c3d00-9ad0-11e9-9d24-7e5dddb1d84a.png)
Lacy is the SSD marine on the left side of the picture.

**Comment by DominikPanic** [comment]
Can you give it a more descriptive title please?

**Comment by DominikPanic** [comment]
Would I be asking too much if I wanted steps for reproduction?

**Comment by factoryman942** [comment]
you would, considering that I have no idea how to reproduce it
if it helps it was on the squad OW console.
It's possible that they woke up, immediately ghosted then got pulled into a larva or something, but 
¯\_(ツ)_/¯
