### ISSUE TITLE
AI eye and Ladders

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#2183]
AI clicking on a ladder sends the AI mainframe mob not AI eye mob.

## Testmerges:

#2172: 'Slight access code cleanup, a few admin equip panel tweaks' by DominikPanic at commit 009818ceed
#2174: 'Hopefully fixes the pref saving bad output runtime' by DominikPanic at commit 1c39b3b17b
#2125: 'Signals Episode 7 The Signals Awaken' by spookydonut at commit 093786f62d
#2162: 'Allows the queen to override shuttle lockdown' by DominikPanic at commit 5b1d6a9102
#2161: 'Makes the AI playable.' by DominikPanic at commit 07aecda827
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81be49
#2169: 'Fixes some more mind dirtyness' by DominikPanic at commit fc3f913956
#2168: 'Fixes dropship interface visual issue' by DominikPanic at commit cf072bf4eb
#2163: 'A slight photo refactor' by DominikPanic at commit e480199a01
#1685: 'Xeno armor refactor' by Rohesie at commit ac0c10b48f
#2179: 'Fixes a floor runtime' by DominikPanic at commit 27e67887b8
#2178: 'Hopefully fixes the reboot issues' by DominikPanic at commit f9708591ee
#2177: 'Yet another do_after runtime' by DominikPanic at commit 5a95b74db4
#2180: 'Removes var-edits from nanomeds' by Rohesie at commit c4f7922042

**Comment by DominikPanic** [comment]
Lmao
