### ISSUE TITLE
game thinks you're DNR if you move out of your corpse

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#2184]
round 649
If I moved out of my corpse, I could see my hud icon in ghost view as a lightning bolt for a second, then it turned to a skull. Going back in and out made the icon swap between the two, and an attempt to defib me while I was outside of my body said I was DNR and didn't give me the prompt to move back to my body because someone was trying to defib.
testmerges #2172 #2174 #2125 #2162 #2161 #1931 #2169 #2168 #2163 #1685 #2179 #2178 #2177 #2180

**Comment by Rohesie** [comment]
Started a PR to fix this, thinking it was a HUD issue, but this is about there no longer being a reference to the ghost in the dead mob. The `ckey` and `mind` references are erased when someone ghosts, and the `mind` one was the old method to link both.
I'll wait for @DominikPanic to give his input. We'll see what kind of solution he wants for this.

**Comment by DominikPanic** [comment]
The mind reference should get erased when someone ghosts, otherwise a lot of quirky behavior will happen and people will show up as xenos. If they are not DNR their mind.current variable will still point to the non-ghost body.
