### ISSUE TITLE
You can't put an unspent sniper round (M42A) back into its mag

### ISSUE THREAD

**Issue by Nickkoranda** [tgstation/TerraGov-Marine-Corps#2194]
If you cycle the bolt on your M42A and retrieve your bullet off the ground you can't put it back into a magazine, it's prompts with the error of "These are not the same rounds, better not mix them up"

**Comment by DominikPanic** [comment]
How did you manage to cycle the bolt? I can't seem to do it in-game.

**Comment by Rohesie** [comment]
Can't seem to cock it either. Normally it would be through unique-action, but in this case it's overwritten.

**Comment by InterroLouis** [comment]
Mmhmm. Figured it out. If you use the unload-weapon verb to unload an M42A without a magazine in it, it generates a stackable single bullet that can't be loaded back into the magazine.

**Comment by factoryman942** [comment]
@DominikPanic close this?
