### ISSUE TITLE
Medkits won't fit into medkit pouches.

### ISSUE THREAD

**Issue by vzhegalov** [tgstation/TerraGov-Marine-Corps#2221]
## Reproduction:

Try to put advanced medkint into medkit pouch. Get "The medkit pouch cannot hold the first-aid kit as it's a storage item of the same size."

The following pull requests were test merged
#2161: 'Makes the AI playable.' by DominikPanic at commit 7c76228
#2174: 'Hopefully fixes the pref saving bad output runtime' by DominikPanic at commit 1c39b3b
#2203: 'Increases lasgun slowdown while wielded' by MoXuT0 at commit 91c9198
#2205: 'Adds sounds for pod doors' by MoXuT0 at commit 2b9034f
#2207: 'Service pistol balance patch' by MoXuT0 at commit 35ddb82
#2211: 'Storage rebalance' by MoXuT0 at commit 4e118aa
#2214: 'Life() cleanup and microoptimizations' by DominikPanic at commit 4d3a965
#2210: 'Converts all attack animations to the new proper type' by DominikPanic at commit 2982dc4
#2201: 'Fixes being unable to click on darkness' by DominikPanic at commit 94a1075
#2215: 'Fixes ASL radio for real' by DominikPanic at commit aae182b

**Comment by Pariah919** [comment]
The following pull requests were test merged
#2161: 'Makes the AI playable.' by DominikPanic at commit 7c76228123
#2174: 'Hopefully fixes the pref saving bad output runtime' by DominikPanic at commit 1c39b3b17b
#2203: 'Increases lasgun slowdown while wielded' by MoXuT0 at commit 91c9198bd0
#2205: 'Adds sounds for pod doors' by MoXuT0 at commit 2b9034f32f
#2207: 'Service pistol balance patch' by MoXuT0 at commit 35ddb82737
#2211: 'Storage rebalance' by MoXuT0 at commit 4e118aa8ab
#2214: 'Life() cleanup and microoptimizations' by DominikPanic at commit 4d3a9655f3
#2210: 'Converts all attack animations to the new proper type' by DominikPanic at commit 2982dc4a3f
#2201: 'Fixes being unable to click on darkness' by DominikPanic at commit 94a1075a9b
#2215: 'Fixes ASL radio for real' by DominikPanic at commit aae182b995
