### ISSUE TITLE
Moving against airlocks doesn't automatically open them

### ISSUE THREAD

**Issue by Rushnagar** [tgstation/TerraGov-Marine-Corps#2235]
## Testmerges:

#2208: 'First part of the mob code cleanup - cooldown framework' by DominikPanic at commit df45493a9f
#2229: 'Disarming C4 with a multitool' by Eskjjlj at commit 397863c704
#2228: 'Feedback for joining as larva.' by Rohesie at commit 5ffdf9d4cb
#2223: 'A different medkit size fix' by DominikPanic at commit ebec5e44ae
#2215: 'Fixes ASL radio for real' by DominikPanic at commit aae182b995
#2210: 'Converts all attack animations to the new proper type' by DominikPanic at commit 2982dc4a3f
#2214: 'Life() cleanup and microoptimizations' by DominikPanic at commit eabe5dddee
#2211: 'Storage rebalance' by MoXuT0 at commit f5ddb6b0ce
#2161: 'Makes the AI playable.' by DominikPanic at commit 3e6f392538
#2220: 'Removes unused implant code, fixes CL implanter' by DominikPanic at commit 45e0614662
#2217: 'Fixes duplicate pipe causing warnings on ice' by DominikPanic at commit e96b5b0654
#2216: 'Fixes EORD ghost runtimes' by DominikPanic at commit fc01571efc
#2227: 'Fixes teleporter attack_hand runtime' by DominikPanic at commit 84b2976dde
#2226: 'Improves admin input sanitization' by DominikPanic at commit 74efda0ad6
#2197: 'Fire() refactor part I: Non-projectile gun attachables handled by CTRL+Click' by Rohesie at commit f1fe514ffa
#2233: '.45 Ammo box' by Hughgent at commit 81179c1f21

## Reproduction:

You have to click them.

**Comment by DominikPanic** [comment]
Was TM related, shouldnt happen again (if it does ping me and i'll eat my shorts)
