### ISSUE TITLE
Typing indicator doesn't go away if you get stunned/knocked out while typing

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2238]
## Testmerges:

Round ID:  657 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 291d79988c28dead09cc30cc39fc1a1744ae685d 
The following pull requests are currently test merged: 
#2234: 'Adds action buttons for voting' by DominikPanic at commit bf683d6828 
#2229: 'Disarming C4 with a multitool' by Eskjjlj at commit 397863c704 
#2228: 'Feedback for joining as larva.' by Rohesie at commit 5ffdf9d4cb 
#2223: 'A different medkit size fix' by DominikPanic at commit ebec5e44ae 
#2215: 'Fixes ASL radio for real' by DominikPanic at commit aae182b995 
#2210: 'Converts all attack animations to the new proper type' by DominikPanic at commit 2982dc4a3f 
#2214: 'Life() cleanup and microoptimizations' by DominikPanic at commit eabe5dddee 
#2211: 'Storage rebalance' by MoXuT0 at commit f5ddb6b0ce 
#2161: 'Makes the AI playable.' by DominikPanic at commit 3e6f392538 
#2220: 'Removes unused implant code, fixes CL implanter' by DominikPanic at commit 45e0614662 
#2217: 'Fixes duplicate pipe causing warnings on ice' by DominikPanic at commit e96b5b0654 
#2216: 'Fixes EORD ghost runtimes' by DominikPanic at commit fc01571efc 
#2227: 'Fixes teleporter attack_hand runtime' by DominikPanic at commit 84b2976dde 
#2226: 'Improves admin input sanitization' by DominikPanic at commit 74efda0ad6 
#2233: '.45 Ammo box' by Hughgent at commit 81179c1f21 

## Reproduction:

Try to type something > get knocked out > typing indicator doesn't go away now

![dreamseeker_AXCb3IPt1X](https://user-images.githubusercontent.com/34478337/60774118-3d39dc80-a118-11e9-8722-aecbc56aff30.png)

**Comment by DominikPanic** [comment]
That is intended since the dialogue boxes doesn't get closed either

**Comment by MoXuT0** [comment]
But you can’t close that dialogue box after you get knocked out, typing indicator will stay forever
