### ISSUE TITLE
Fire doesn't do anything while you're just standing on it.

### ISSUE THREAD

**Issue by Rushnagar** [tgstation/TerraGov-Marine-Corps#2244]
## Reproduction:

1.Step on a fire tile
2.Don't move. Just resist.
3.When all fire stacks are out, you'll be fine. There is no need to move off the fire.

This makes fire OBs useless at killing aliens. Even a sentinel inside the radius could survive it.

**Comment by DominikPanic** [comment]
Fixed in #2261
