### ISSUE TITLE
Game Panel’s create object doesn’t work (RU-branch)

### ISSUE THREAD

**Issue by Fray2** [tgstation/TerraGov-Marine-Corps#2255]
## Reproduction: 
https://media.discordapp.net/attachments/479387873574125606/599307273486991361/c09ca6b7-4165-49ca-86c9-ea31204ebe3e.gif

**Comment by DominikPanic** [comment]
Works fine here
https://puu.sh/DS0Kb/bb6daee5eb.png

**Comment by DominikPanic** [comment]
Seems to be a bug of another codebase, unrelated to anything we did. You should report it on your repo since the issue is not present here.
