### ISSUE TITLE
Pressing E on gloves (possibly other clothing) puts it in storage, not in the free clothing spot

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#2272]
## Reproduction

1) Remove gloves from hands
2) Press E.
3) Cry as you necrotize the 15th chest in a row because your gloves didn't go on your hands.

**Comment by DominikPanic** [comment]
That is intended

**Comment by Rohesie** [comment]
This only happens if the storage is open.
It would be quite troublesome to pack things in a storage through E if they went to your pockets or any slot available on your body.
