### ISSUE TITLE
Bad output in save_character()

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#2281]
## Testmerges:

Master commit: 8328c50b8b56613d49a1b2cce18fd0b425c122c2
#2275: 'Fixes a world status runtime' by DominikPanic at commit 33510751d9
#2276: 'Fixes the Ice Colony landing zones' by DominikPanic at commit 9b4285bd8f
#2248: 'Allows admins to set a custom tip of the round' by DominikPanic at commit 73bd9c6935
#2266: 'Fixes some keybinding issues' by DominikPanic at commit e13948fec8
#2264: 'Buckle parent logic' by Rohesie at commit 1bc389af0f
#2246: 'LV blockers rework' by Rohesie at commit 49632b1983
#2250: 'Admin round-start tweaks' by DominikPanic at commit 6e431cc7f2
#2252: 'Fixes the release object verb' by DominikPanic at commit 3273337c62
#2256: 'Imaginary friend fixes' by DominikPanic at commit 01d04a8f76
#2242: 'Buffs Selling Xenomorph corpses' by Spyroshark at commit 0e03668730
#2208: 'First part of the mob code cleanup - cooldowns' by DominikPanic at commit dab5f90199
#2260: 'Fixes blood overlay issues' by DominikPanic at commit 8acd19783d
#2268: 'Fixes mulebot wire runtime' by DominikPanic at commit d0f010ff90
#2267: 'Another do_after runtimes' by DominikPanic at commit 47f7a6c597
#2269: 'Attachment ammo runtimes' by Rohesie at commit 50fe261324
#2274: 'Fixes a HUD runtime' by DominikPanic at commit a3a553ab69
#2273: 'Fixes a vote runtime' by DominikPanic at commit 9637069f33
#2271: 'Fixes pocket equip issues' by DominikPanic at commit 4bad049e66
#2277: 'Fixes a camera runtime' by DominikPanic at commit 508da14d7e
#2279: 'Stack fixes' by Rohesie at commit 32b6749003

## Reproduction:

```
[04:11:14] Runtime in preferences_savefile.dm, line 397: bad output
proc name: save character (/datum/preferences/proc/save_character)
usr: Husky Husk/(Husky Husk)
usr.loc: (start area (8, 8, 1))
src: /datum/preferences (/datum/preferences)
call stack:
/datum/preferences (/datum/preferences): save character()
/datum/preferences (/datum/preferences): process link(Husky Husk (/mob/new_player), /list (/list))
Husky Husk (/client): Topic("_src_=prefs;preference=eyecolo...", /list (/list), null)
```

**Comment by DominikPanic** [comment]
i wanna reee so hard

**Comment by DominikPanic** [comment]
Time to ask Lummox since I have no fucking idea.
