### ISSUE TITLE
Operating tables can't connect patients to anaesthetic

### ISSUE THREAD

**Issue by Anonmare** [tgstation/TerraGov-Marine-Corps#2311]
## Testmerges:
#2224: '[READY]Makes reagents use typepaths instead of IDs' by DominikPanic at commit b9c3866653 
#2246: 'LV blockers rework' by Rohesie at commit 49632b1983 
#2264: 'Buckle parent logic' by Rohesie at commit 1bc389af0f 
#2196: 'Adds weed decay' by psykzz at commit 050512562d 
#2128: 'Full auto' by Rohesie at commit a7c9451b2e 
#2303: 'Adds faction based roundend sounds' by DominikPanic at commit 8ea6ee9358 
#2302: 'Fixes keybinding prefs for players who played here previously' by DominikPanic at commit 957243576e 
#2301: 'Fixes vote action runtime' by DominikPanic at commit f0ba482387 
#2300: 'Fixes HUD updating runtimes' by DominikPanic at commit c453545379 
#2299: 'Removes removed config.txt entry' by DominikPanic at commit 8b68553d1c 

## Reproduction: 
Place patient on table with anaesthetic tank, attempt to connect patient to table - no results.

**Comment by DominikPanic** [comment]
See if it happens next round, then report here again please.

**Comment by DominikPanic** [comment]
Was a temporary reagents bug, fixed in #2224
