### ISSUE TITLE
Suit light bug

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2313]
## Testmerges:

Round ID:  707 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 4e094486951a54825bdc79b5c3acf2cae20aacef 
The following pull requests are currently test merged: 
#2128: 'Full auto' by Rohesie at commit 279a5fd4a5 
#2360: 'Fixes a null in player list if the player disconnects at a bad time' by DominikPanic at commit fe50c5d9e5 
#2357: 'Fixes a gun action runtime' by DominikPanic at commit 96acd02108 
#2353: 'Fixes some topic interaction issues' by DominikPanic at commit 49a36fb0a8 
#2347: 'Fixes ghost pulling' by DominikPanic at commit 7b47892c84 
#2349: 'Fixes elite drones and carriers' by DominikPanic at commit d837bb1c05 
#2350: 'Fixes observer crossed mouse squeaking' by DominikPanic at commit 140e4ba2cd 
#2337: 'Fixes lobby countdown when admin sets it before startup' by DominikPanic at commit a323765aaf 
#2338: 'Fixes a zone select runtime' by DominikPanic at commit 30cacc29a1 
#2336: 'Makes some fax fields optional' by DominikPanic at commit 0a99ce3376 
#2306: 'Battle rifle balance tweaks' by MoXuT0 at commit c286e12984 
#2301: 'Fixes vote action runtime' by DominikPanic at commit f0ba482387 
#2196: 'Adds weed decay' by psykzz at commit f0533e68bb 
#2264: 'Buckle parent logic' by Rohesie at commit 1bc389af0f 
#2246: 'LV blockers rework' by Rohesie at commit 49632b1983 
#2224: 'Makes reagents use typepaths instead of IDs' by DominikPanic at commit 5bee0a730d 
#2333: 'Weapon/Magazine Caliber Fix' by InterroLouis at commit 3fef03fdfc 
#2310: 'Clarifies the hotkey preference name, removes obsolete SSinput things' by DominikPanic at commit 7f1596ed36 
#2352: 'Fixes simple window deconstruction' by DominikPanic at commit c1b5891fce 
#2354: 'Fixes overwatch eye layer issues' by DominikPanic at commit d1f0942443 
#2358: 'Removes emergency shutter admin message' by DominikPanic at commit d1b19143cc 
#2363: 'Fixes graceful shutdown pinging for real' by DominikPanic at commit 3b12902235 
#2362: 'Adds additional null protection from /tg/' by DominikPanic at commit e58f5b6112 
#2361: 'Fixes plasmacutter interactions' by DominikPanic at commit 7c509c5688 
#2366: 'Fixes a slight access issue' by DominikPanic at commit 7b1dba02eb 

## Reproduction:

Find dead body > try to slash it to disable lights > light goes out but lamp icon doesn't update

![изображение](https://user-images.githubusercontent.com/34478337/61597220-7ee97d80-ac16-11e9-9761-8254be692947.png)

**Comment by DominikPanic** [comment]
It does not work with every single dead body. Please ahelp ingame next time this happens since there is specific stuff being broken.

**Comment by MoXuT0** [comment]
Ok, I will. Tested this on B18, freelancers and UPP, could slash them indefinetly.

**Comment by MoXuT0** [comment]
Multiple slashes are gone for now, I've updated issue just because I don't want to create simillar new one, Also there's fuckery when you get hugged, you need to click twice to reactive suit light. It shows as turned on but doesn't produce any light when you get hugged.

**Comment by MoXuT0** [comment]
Basically icon doesn't update with luminocity 

![изображение](https://user-images.githubusercontent.com/34478337/61597387-e6a0c800-ac18-11e9-8a11-c810ac4b2c75.png)

**Comment by DominikPanic** [comment]
Copy, can you update the title?
