### ISSUE TITLE
Light Sticks.

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#2331]
## Testmerges:

Don't think it's from a testmerge, also testmerging has had some issues lately. 
## Reproduction:
Try to plant a light stick on the ice colony map. Fail because they don't work. Please fix.

**Comment by DominikPanic** [comment]
Surprisingly this is not a bug as the code for this has never existed here (I looked at the history of the lightstick file, even in the initial commit it didn't support this)
