### ISSUE TITLE
Admins should be able to choose ERT

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#2334]
From @Rohesie 

> Little request, and feel free to deny it:
Add an option for admins to be able to choose the kind of ERT they want to send?
Would require something like this:
```
/datum/game_mode/proc/activate_distress(chosen_call)
	picked_call = chosen_call || get_random_call()
```

**Comment by DominikPanic** [comment]
This is not a bug.
