### ISSUE TITLE
APCs lock themselves after opening their panel with crowbar

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2341]
## Testmerges:

Round ID:  698 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 6a6c3c0af106180230f28d6dd217e9c252f24e68 
The following pull requests are currently test merged: 
#2335: 'Allow admins to set a distress beacon when sending' by psykzz at commit 5067be0378 
#2336: 'Makes some fax fields optional' by DominikPanic at commit 0a99ce3376 
#2326: 'Cleans up rav rage decay' by psykzz at commit 938dc8de72 
#2329: 'Fixes plasmacutter battery removal' by DominikPanic at commit 1b81dc235c 
#2312: 'Add human / xeno count to distress beacons for admins' by psykzz at commit 46e4d1b0e8 
#2314: 'Removes Big Red cameras' by DominikPanic at commit e161dc7355 
#2306: 'Battle rifle balance tweaks' by MoXuT0 at commit c286e12984 
#2307: 'Adds ammo counters to most spec weapons and launchers' by MoXuT0 at commit a9b8a22c8a 
#2300: 'Fixes HUD updating runtimes' by DominikPanic at commit c453545379 
#2301: 'Fixes vote action runtime' by DominikPanic at commit f0ba482387 
#2196: 'Adds weed decay' by psykzz at commit 050512562d 
#2264: 'Buckle parent logic' by Rohesie at commit 1bc389af0f 
#2246: 'LV blockers rework' by Rohesie at commit 49632b1983 
#2224: 'Makes reagents use typepaths instead of IDs' by DominikPanic at commit 091e838b4c 
#2320: 'Ammo datum cleanup and runtime fix' by Rohesie at commit 20325ee3b0 
#2333: 'Fixes Issue #2194' by InterroLouis at commit d7136e24eb 
#2325: 'Fixing the runtime for ssdirection' by psykzz at commit 2ac4a1503b 

## Reproduction:

Unlock apc cover > crowbar it > close it > it's now locked and you have to manually unlock it again.

**Comment by DominikPanic** [comment]
Intended upon closing
`coverlocked = TRUE //closing cover relocks it`
