### ISSUE TITLE
Overwatch camera still appears under weeds

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2346]
## Testmerges:

Round ID: 698
BYOND Version: 512.1464
Server revision compiled on:
Master commit: 6a6c3c0
The following pull requests are currently test merged:
#2335: 'Allow admins to set a distress beacon when sending' by psykzz at commit 5067be0
#2336: 'Makes some fax fields optional' by DominikPanic at commit 0a99ce3
#2326: 'Cleans up rav rage decay' by psykzz at commit 938dc8d
#2329: 'Fixes plasmacutter battery removal' by DominikPanic at commit 1b81dc2
#2312: 'Add human / xeno count to distress beacons for admins' by psykzz at commit 46e4d1b
#2314: 'Removes Big Red cameras' by DominikPanic at commit e161dc7
#2306: 'Battle rifle balance tweaks' by MoXuT0 at commit c286e12
#2307: 'Adds ammo counters to most spec weapons and launchers' by MoXuT0 at commit a9b8a22
#2300: 'Fixes HUD updating runtimes' by DominikPanic at commit c453545
#2301: 'Fixes vote action runtime' by DominikPanic at commit f0ba482
#2196: 'Adds weed decay' by psykzz at commit 0505125
#2264: 'Buckle parent logic' by Rohesie at commit 1bc389a
#2246: 'LV blockers rework' by Rohesie at commit 49632b1
#2224: 'Makes reagents use typepaths instead of IDs' by DominikPanic at commit 091e838
#2320: 'Ammo datum cleanup and runtime fix' by Rohesie at commit 20325ee
#2333: 'Fixes Issue #2194' by InterroLouis at commit d7136e2
#2325: 'Fixing the runtime for ssdirection' by psykzz at commit 2ac4a15

## Reproduction:

Forgot to take a picture but camera still appears under weeds.

**Comment by DominikPanic** [comment]
Please take a picture. It does not do that for me.

**Comment by DominikPanic** [comment]
https://puu.sh/DVj63/43abc79f11.png

**Comment by MoXuT0** [comment]
![изображение](https://user-images.githubusercontent.com/34478337/61584792-7467af00-ab56-11e9-80a2-af4031b72624.png)

**Comment by MoXuT0** [comment]
![изображение](https://user-images.githubusercontent.com/34478337/61584794-7c275380-ab56-11e9-85fb-d551fac4a64a.png)

**Comment by DominikPanic** [comment]
Unless you tell me the exact steps to reproduce that I can't fix it, since it works 100% fine for me.

**Comment by MoXuT0** [comment]
Are you using AI or overwatch console?

**Comment by MoXuT0** [comment]
It only works for main overwatch console for me.

**Comment by DominikPanic** [comment]
Only the main console? Let's see.
