### ISSUE TITLE
Crates empty when picked up

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#2383]
## Testmerges:

#2378 #2368 #2128 #2306 #2301 #2196 #2264 #2246 #2224 #2333 #2310 #2354 #2361 #2366 #2370

## Reproduction:

Filled a crate with supply manifests. When I picked it up with a powerloader, it picked up the crate but left the supply manifests

**Comment by DominikPanic** [comment]
@Rohesie
