### ISSUE TITLE
Keybinding hotkeys don't respect chatmode unless the chat bar is specifically highlighted

### ISSUE THREAD

**Issue by Anonmare** [tgstation/TerraGov-Marine-Corps#2399]
## Testmerges:
#2394: 'Bipod, and scatter rework, attachment refactor' by Rohesie at commit 661df86ed2 
#2224: 'Makes reagents use typepaths instead of IDs' by DominikPanic at commit c0e0c19ef2 
#2333: 'Weapon/Magazine Caliber Fix' by InterroLouis at commit 3fef03fdfc 
#2387: 'Fixes synthetic blind and deafness issues' by DominikPanic at commit bf47614d9d 
#2390: 'Fixes largecrate issues' by DominikPanic at commit 5f59e5017c 
#2396: 'Fixes a queen calldown issue' by DominikPanic at commit ed09e6e8d8 
#2397: 'Fixes facehugger description' by DominikPanic at commit 06c303ab6c 
#2398: 'Fixes some light slashing issues' by DominikPanic at commit 5b5ad3fef2 
#2361: 'Fixes plasmacutter interactions' by DominikPanic at commit bb67a5ea4f 
#2310: 'Clarifies the hotkey preference name, removes obsolete SSinput things' by DominikPanic at commit a41e09e608 
#1780: 'Gamemode: Crash (name pending)' by psykzz at commit 0ebe1de0c3 

## Reproduction:
Switch to chatmode and try to type any of the hotkeys without having the chatbar specifically highlighted, cry when you forget that you haven't selected the chatbar and accidentally IC in OOC because you hit O. In addition, the Escape key is no longer clearing the verb in the chat bar.

**Comment by DominikPanic** [comment]
@psykzz
