### ISSUE TITLE
Evil Doctor Locks Local Marine In Tiny Medbay [Crash Gamemode]

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#2426]
## Testmerges:

#1780

## Reproduction:

Marines spawn in medical bay, without access to escape. They shall forever be trapped there.
[*Evil Doctor Intensifies*]

**Comment by DominikPanic** [comment]
@psykzz

**Comment by DominikPanic** [comment]
Still hasn't been fixed, will close when it is.

**Comment by DominikPanic** [comment]
Fixed in #1780
