### ISSUE TITLE
Plating appears below resin walls after destroying them

### ISSUE THREAD

**Issue by MoXuT0** [tgstation/TerraGov-Marine-Corps#2429]
## Testmerges:

Round ID:  732 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: bce84cdcd22736ad8aefd2ec76df9e3d3a55dca8 
The following pull requests are currently test merged: 
#2428: 'Fixes focus chat mode' by DominikPanic at commit 771920b5da 
#2420: 'Replaces TerraGov poster icon with proper one' by MoXuT0 at commit 4e6ac0e816 
#2424: 'Cleans up a lot of commented out code' by DominikPanic at commit 0213598ba6 
#2395: 'Effects refactor' by spookydonut at commit b3bf474202 
#2409: 'Regress xeno ability' by Rohesie at commit aad2a9a625 
#2361: 'Fixes plasmacutter interactions' by DominikPanic at commit ee8ac39cf9 
#2333: 'Weapon/Magazine Caliber Fix' by InterroLouis at commit 3fef03fdfc 
#2224: 'Makes reagents use typepaths instead of IDs' by DominikPanic at commit ad20c0764d 
#2128: 'Full auto' by Rohesie at commit 50fd9728f5 

## Reproduction:

There's maybe more shit, like some tiles on Big Red that weren't weedable before turf update. 

![изображение](https://user-images.githubusercontent.com/34478337/61982230-b84e2e80-b004-11e9-939e-7ac8ed6a4d2c.png)

**Comment by MoXuT0** [comment]
Same shit on LV

![изображение](https://user-images.githubusercontent.com/34478337/61984055-7bd20100-b00b-11e9-8a34-88c1be1651d9.png)

**Comment by DominikPanic** [comment]
Yep it's a turf problem with baseturfs. I know the cause and fix.
