### ISSUE TITLE
Map for Ice colony doesn't work

### ISSUE THREAD

**Issue by Kuro-ai** [tgstation/TerraGov-Marine-Corps#2437]
## Reproduction:

When I open the SL map for Ice colony I receive a white screen with the following message.
From /tg/station 13 Wiki
Jump to: navigation, search 
There is currently no text in this page. You can search for this page title in other pages, or search the related logs, but you do not have permission to create this page. 

Retrieved from "https://tgstation13.org/wiki/TGMC/images/1/18/Map_icecolony.png"

**Comment by DominikPanic** [comment]
This has now been fixed externally
