### ISSUE TITLE
Ravager/Defiler registered signals don't go off

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#2447]
## Testmerges:
None: local server pulled from master today

## Reproduction:
-Be either a ravager or a defiler

-To replicate the ravager, slice a human when in harm intent: notice that the rage meter isn't increased by 7.5

-To replicate the defiler, toggle the neuroinjectors and attempt to disarm or harm intent a human; notice how 50 plasma isn't used and nothing injected

COMSIG_XENOMORPH_ATTACK_HUMAN doesn't seem to work, or register signal borked

No varedits, admin spawned in centcom

**Comment by DominikPanic** [comment]
@psykzz
