### ISSUE TITLE
Can't put SSDs in hypersleep chambers

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#2488]
## Testmerges:

#2483 #2482 #2478 #2475 #2465 #2361 #2128 #2462 #2461 #2379 #2473 #2471 #2470 #2468 #2467 #1780 #2476 #2481 #2480 #2479 #2485

## Reproduction:

1) Grab SSD.
2) Attempt to put them into a hypersleep chamber.
3) Cry as you failed ~~like you've done with everything else.~~

**Comment by psykzz** [comment]
This is related to https://github.com/tgstation/TerraGov-Marine-Corps/pull/2379 and is intended behaviour.

Admins should cryo clientless mobs not players.

**Comment by DominikPanic** [comment]
This is not a bug.

**Comment by Rohesie** [comment]
To clarify, we are discussing how to deal with cryo in the future and changes will end up happening.
The standard behavior is not yet fully decide.
