### ISSUE TITLE
SG able to fire out of Termal dampening tarp

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#2515]
## Testmerges:

#2484: 'smoking is cool, right?' by grinkgo at commit 45d1db5b6f
#2514: 'Fixes 2 slight interface issues' by DominikPanic at commit 5f0ab24571
#2507: 'Fixes prayer logging' by DominikPanic at commit ed15df8611
#2508: 'Very minor turf code cleanup' by DominikPanic at commit d17719e99a
#2509: 'Fixes some more shutter orientation on big red' by DominikPanic at commit 6d34155b6c
#2510: 'Fixes Lamarr runtime' by DominikPanic at commit b6816b803c
#2511: 'APC shock based on percent charge' by psykzz at commit 61cbce2b0e
#1780: 'Gamemode: Crash (name pending)' by psykzz at commit 8cf9c05b73
#2379: 'Add some dragover QOL' by psykzz at commit 7790e829f8
#2128: 'Full auto' by Rohesie at commit 17a24636e5
#2361: 'Fixes plasmacutter interactions' by DominikPanic at commit 9cb69d24b7
#2506: 'Reworks the automute system add a message weight option' by DominikPanic at commit b0fb71d7f8
#2505: 'Small xeno takeover refactor' by Rohesie at commit 761cda2c38
#2495: 'Adds camera tracking to the overwatch console' by DominikPanic at commit 1740a08a8e

## Reproduction:

SG on Canturbury was able to fire from inside a tarp on the final holdout.

**Comment by DominikPanic** [comment]
Unable to reproduce on master, most likely related to full auto @Rohesie

**Comment by Rohesie** [comment]
Was it on autofire mode?

**Comment by Mr-Worth** [comment]
I believe so

**Comment by Rohesie** [comment]
Fixed here:
https://github.com/tgstation/TerraGov-Marine-Corps/pull/2128/commits/d21c22709b9f375a90c7c767669ef0efbb6b5cda
