### ISSUE TITLE
you can't build multiple cades on a corner

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#2518]
i'm not sure why nobody made an issue for this in the last n months, but you can't build multiple cades on the same tile (to make a corner). You have to build one off the corner, then unanchor it and drag it into the right place.

**Comment by DominikPanic** [comment]
This has been fixed, can you reproduce it on latest master?

**Comment by DominikPanic** [comment]
https://puu.sh/E0o3n/1024a0352b.mp4
just tested, it's working fine
