### ISSUE TITLE
cloaks can be kept equipped with different armour

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#2519]
Cloaks require you to wear scout/sniper armour (depending on which cloak) before you can equip them. If you equip them with scout armour then change to a different type of armour, you can keep the cloak and it still works. Either this should be prevented, or equipping the cloak over any armour should be allowed.

**Comment by Rohesie** [comment]
Honestly I see no need for the restriction.

**Comment by DominikPanic** [comment]
A bug since the actual interaction that should work doesn't, though I'm also implementing your suggestion in that PR Roh.
