### ISSUE TITLE
humans don't go in body bags

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#2526]
observe this human:
![image](https://user-images.githubusercontent.com/20996272/62400896-cf4ace80-b578-11e9-945a-d42f1b09fb94.png)
It has been stripped of all equipment, yet it refuses to go in the bag.
Clickdragging it to the bag is also ineffective.

TMs:
#2523: 'Fixes give mob mind issues' by DominikPanic at commit ff1301f724 
#2524: 'Fixes xeno join admin logs' by DominikPanic at commit ec7dfd2af0 
#2502: 'Makes you deaf while unconscious' by Maciekkub at commit 3da9b9bfdb 
#2520: 'Allows the AI to use the autodoc' by DominikPanic at commit 98c50afac5 
#2521: 'Adds an easy spatial agent verb' by DominikPanic at commit 3d8f9bf5b8 
#2522: 'Clothing restriction changes' by DominikPanic at commit 7eb6b3a5ca 
#2514: 'Fixes 2 slight interface issues' by DominikPanic at commit 5f0ab24571 
#2507: 'Fixes prayer logging' by DominikPanic at commit ed15df8611 
#2508: 'Very minor turf code cleanup' by DominikPanic at commit d17719e99a 
#2509: 'Fixes some more shutter orientation on big red' by DominikPanic at commit 6d34155b6c 
#2510: 'Fixes Lamarr runtime' by DominikPanic at commit b6816b803c 
#2379: 'Add some dragover QOL' by psykzz at commit ef4c534f4b 
#2128: 'Full auto' by Rohesie at commit fd0e583099 
#2361: 'Fixes plasmacutter interactions' by DominikPanic at commit 9cb69d24b7 
#2506: 'Reworks the automute system add a message weight option' by DominikPanic at commit b0fb71d7f8 
#2495: 'Adds camera tracking to the overwatch console' by DominikPanic at commit 1740a08a8e 
#1780: 'Gamemode: Crash (name pending)' by psykzz at commit d0020b14a7

**Comment by DominikPanic** [comment]
@Rohesie Can confirm this is happening

**Comment by Rohesie** [comment]
Unable to reproduce it on the live server:
![1](https://user-images.githubusercontent.com/42041276/62403494-f1862180-b563-11e9-8e27-35c23a6886ca.png)
![2](https://user-images.githubusercontent.com/42041276/62403495-f1862180-b563-11e9-8927-2c4c7a0823fb.png)

**Comment by DominikPanic** [comment]
Try a dead body

**Comment by Rohesie** [comment]
That was a dead body. Bodybags don't accept living nor revivable dead bodies.

**Comment by DominikPanic** [comment]
Bodybags are especially for dead bodies, and the one I was trying it was one of the colonists.

**Comment by Rohesie** [comment]
Yea, they are for unrevivable dead bodies. I'll test it on a dead colonist later. They may be registering as revivable for some reason.

**Comment by factoryman942** [comment]
I think this is part of it
https://github.com/tgstation/TerraGov-Marine-Corps/blob/d60abb6df8a749e672bfe74eaeffe24f1124fa0d/code/game/objects/items/bodybag.dm#L127-L128

https://github.com/tgstation/TerraGov-Marine-Corps/blob/a7b95f4a8961456cc13294b00038a77e2d04cf5b/code/game/objects/items/defibrillator.dm#L172-L174

 check_tod being false means they're unrevivable, but if it's false then the if will be true, so it won't let them be stored in the bag. I think. Maybe.
~~naturally I removed the ! from the check and it did fuck all so ehhhh~~
@Rohesie @DominikPanic
