### ISSUE TITLE
Can't build tables in Canterbury

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#2547]
## Testmerges:

#2543 #2544 #2361 #2502 #2537 #2495 #2128 #1780 #2546 #2545

## Reproduction:

I can't set up the table parts into the table. Error message tells me "No. This area is needed for the dropship."

**Comment by DominikPanic** [comment]
@Rohesie bug or not?

**Comment by Rohesie** [comment]
This is not my doing. It's CM code.
It's not a bug, but it's a behavior that could be discussed on whether remove or not.
I don't have strong opinions yet.

**Comment by DominikPanic** [comment]
Not a bug is all I needed to hear :p 
Sorry, thought that this was related to the building changes you did.
