### ISSUE TITLE
Add the ability to manipulate a marine for Shrek.

### ISSUE THREAD

**Issue by Bob46-2** [tgstation/TerraGov-Marine-Corps#2580]
Shrek, in the psionic capture of a marine, must stand still, making him defenseless and forcing him to hunt alone. My idea is to give Shrek the ability to manipulate a marine's body and use it as a meat shield, for example, or to take full control and make him shoot his comrades.

**Comment by DominikPanic** [comment]
I guess that you mean shrike, regardless this is for bug reports only, if you have a suggestion for a feature you should use #dev-general
