### ISSUE TITLE
Medevac stretchers copy themselves instead of folding when dragged into you

### ISSUE THREAD

**Issue by DiscordWizard** [tgstation/TerraGov-Marine-Corps#26]
Instead of folding up like someone would expect from a stretcher, you get a neat new folded stretcher in your hand, without any penalties, issues or cooldowns except for not being able to remove the original stretcher. You can basically cover the map in stretchers from a single one.

**Comment by DominikPanic** [comment]
Fix in this PR: https://github.com/tgstation/TerraGov-Marine-Corps/pull/21
