### ISSUE TITLE
Follow-predator word [predator talk sound effect]

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#263]
Big Red round of 31 december
Follow predator word .
A result on screenshot:
Joselyn Heckendora (follow) says, "It was one time fucking thing, it was to remove his 150 burn damage"
[predator talk sound effect]
![predator-follow- predator talk sound effect](https://user-images.githubusercontent.com/45321263/50551572-aafddb00-0c93-11e9-9c5d-ba399da07627.png)

**Comment by DominikPanic** [comment]
It was actually a predator, dressed exactly as a marine. This was an event run by AIIA.
