### ISSUE TITLE
How to increase picking of Alien role. [Ancients get ULTIMATE ABILITY(Dota-style)]

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#264]
Younglings can do only basics.
Every mature alien learns new ability and minor buffs.
Elite aged aliens learn moderate skills and buffs.
Ancients should have the ULTIMATE ABILITY 
More time required to grow = more stronger ability.
Example. Ancient crusher learns how to crush walls, girders or overthrow corpses over window frames by throwing people.
Now crusher "throw corpse" ability is too weak. Cant even overthrow corpse over window frames

**Comment by Monikawales** [comment]
Basic rule: every time alien changes age, so every time it learns new skill or changing abilities type, or replacing it with powerful skills. Ancients always learn ultimate ULTIMATE ABILITY(s)

**Comment by PantasTheDank** [comment]
I don't think we neee to buff the xenos...

**Comment by DominikPanic** [comment]
You should post this in either #dev-general on our Discord or in the dedicated forum suggestions thread: https://tgstation13.org/phpBB/viewtopic.php?f=65&t=20995
