### ISSUE TITLE
Dislocated stationary map objects

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2650]
## Testmerges: #2646, #2128, #2642, #2626, #2599, #2553, #2364, #2645, #2570, #2635, #2477, #2647

No reproduction, i walked in and see them being in a place they shouldn't be
+ Sink upon pointing points to the wall
![sink](https://user-images.githubusercontent.com/30427887/63200322-1d83c580-c081-11e9-8d20-c8dbdbde89f1.png)
![light](https://user-images.githubusercontent.com/30427887/63200325-21afe300-c081-11e9-8fa6-3dc9b54ea0f6.png)

**Comment by DominikPanic** [comment]
https://puu.sh/E64sG/deda54e785.png
