### ISSUE TITLE
clicking titles in chat as AI doesn't follow w/ camera

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#2654]
## Testmerges:

#2648 #2647 #2477 #2635 #2570 #2645 #2364 #2553 #2599 #2626 #2642 #2128 #2646 #2649

## Reproduction:

Clicking on someone's title e.g. "PO," "Syn," "CPT," returns with a message saying "Target is not on or near any active cameras on the station." I assume it's technically doing what it's intended to do since "PO" isn't a player's name. Nonetheless it's prob better to either disable the titles from being clickable or make it so it properly procs the camera follow.

**Comment by DominikPanic** [comment]
The titles are not followable, it's the reference to a player mob. So yes it is a bug, but your assumption is wrong

**Comment by grinkgo** [comment]
> The titles are not followable, it's the reference to a player mob. So yes it is a bug, but your assumption is wrong

lit

**Comment by DominikPanic** [comment]
Works fine for me, please give exact steps for reproduction
https://puu.sh/E64mp/e6cd62fa4c.png

**Comment by DominikPanic** [comment]
No additional information has been provided
