### ISSUE TITLE
You are able to open crates and lockers while grabbing

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2658]

**Comment by DominikPanic** [comment]
Can't seem to be able to reproduce this one locally
https://puu.sh/E64NS/f782acf681.mp4

**Comment by Maciekkub** [comment]
I might have phrased myself wrong
Step 1: Grab a locker/crate
Step 2: Click on a container

**Comment by DominikPanic** [comment]
Unable to reproduce https://puu.sh/E8HRW/b7ab228cca.mp4

**Comment by Maciekkub** [comment]
Unless it's a feature, you can open crates and it seems only crates while your current hand is the one you are grabbing something with so it displays a huge UPGRADE on it, but you cannot close it the same way you opened it.

**Comment by DominikPanic** [comment]
Get me a video, please.

**Comment by Maciekkub** [comment]
https://gyazo.com/cb7980b9a72aa1c47f099d6bd219ed43
As you can see in the video provided, i ca open the crate while on UPGRADE but cannot close it, meanwhile on an empty hand i can do both
