### ISSUE TITLE
Backpack Inventory overlaps other inventory slots

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#2663]
## Testmerges:

Round ID:  841 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 67dc9945d9c52a8f5d6295993f4f2a09aa3057e2 
The following pull requests are currently test merged: 
#2648: 'Makes changelog less laggy' by DominikPanic at commit 4462d3e94c 
#2647: 'Removes focus chat' by DominikPanic at commit 288dd8ae44 
#2477: 'The Rise of the ST' by Maciekkub at commit 406caa21db 
#2635: 'Adds a boot knife to basic marine sets.' by grinkgo at commit 92e7307464 
#2570: 'Object attack damage rework' by DominikPanic at commit 14b672eaab 
#2645: 'Makes the pizza ERT admin only' by DominikPanic at commit 4e8f3e3978 
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45 
#2553: 'Insight into storage runtime' by DominikPanic at commit efda667a8a 
#2599: 'Fixes a runtime when clicking with null turf in the clickcatcher' by DominikPanic at commit cb635f75c8 
#2626: 'Boiler Bombard Time "rebalance"' by DalekThePerson at commit 7a3380ad0a 
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit 924df531e7 
#2128: 'Full auto' by Rohesie at commit 462996e5da 
#2646: 'AI fix' by DominikPanic at commit 6713e868ca 
#2649: 'Fixes a few autodoc runtimes' by DominikPanic at commit 7304e1f143 

## Reproduction:
1. Do something
2. Open backpack 
3. Then open another pack
4. Notice the other pack overlays the backpack

**Comment by DominikPanic** [comment]
Can't reproduce it without exact steps, works fine locally https://puu.sh/E64Mc/1d1a8ac6d3.mp4

**Comment by DominikPanic** [comment]
No additional information has been provided
