### ISSUE TITLE
Binoculars change your viewpoint as if they were you character

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2675]
## Testmerges:

None that I know of, this may just be an inate bug.

## Explanation:

This bug allows you to transfer your main viewpoint from on top of your character to a pair of binoculars. These binoculars now act as your centre of vision even if your character moves, like moving your ghost about while using the "observe" verb on somebody. (Also, it might disrupt some visual affects like NV or HUDs but I don't have steps to reproduce those, and they might as well go in a separate bug report.)

## Reproduction:

The tools you will need are a pair of binoculars (any will work fine, but I used tactical bino's on CAS mode) and a cargo trolley. Not a train, a trolley. One you can buckle onto and put a key in and stuff. The head of a train.

1: First, you'll want to take your binoculars in hand and buckle yourself to a trolley. Make sure that you can "drive" the trolley.

2: Second, peer through the binoculars just like normal.

3: Third, move. You'll exit binocular view but you'll be moving via the trolley.

4: Fourth, drop or throw the binoculars. Move around, and you should see that your view will be disjointed from your character sprite.

To cancel the bug, it's even simpler.

1: First, unbuckle from the trolley. That's it! View should return to normal once you move at least one tile.

## Effects:

Just like the explanation, it allows you to change your viewpoint to what is basically an object, allowing for remote camera viewing.

However, I've done a bit of field testing, and I've concluded that this is actually quite broken. You can throw the binoculars, and the dynamic vision will treat the binoculars as your eyes instead of your sprite. This will let you stay behind a wall while looking at what's on the other side, at the cost of having to stay close to the binos and not being able to see the front side of the wall.

This won't change where you fire from or do actions from, however. It will only affect your view.

**Comment by DominikPanic** [comment]
@psykzz
