### ISSUE TITLE
turret durablity is broken 

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#2678]
## Testmerges:

The following pull requests are currently test merged:
#2653: 'Fixes washing grabs' by DominikPanic at commit d53e109048
#2662: 'Fixes the AI name on latejoin' by DominikPanic at commit 9a09730ef7
#2664: 'Fixes bucket overfilling' by DominikPanic at commit e5c8b51fb1
#2665: 'Fixes floating sinks' by DominikPanic at commit cdf9de2088
#2666: 'Removes big red pipe cheesing' by DominikPanic at commit 4787225b72
#2648: 'Makes changelog less laggy' by DominikPanic at commit 582ad1530e
#2647: 'Removes focus chat' by DominikPanic at commit 70131f63d6
#2477: 'The Rise of the ST' by Maciekkub at commit 406caa21db
#2635: 'Adds a boot knife to basic marine sets.' by grinkgo at commit 92e7307464
#2570: 'Object attack damage rework' by DominikPanic at commit 14b672eaab
#2645: 'Makes the pizza ERT admin only' by DominikPanic at commit 4e8f3e3978
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45
#2553: 'Insight into storage runtime' by DominikPanic at commit efda667a8a
#2599: 'Fixes a runtime when clicking with null turf in the clickcatcher' by DominikPanic at commit cb635f75c8
#2626: 'Boiler Bombard Time "rebalance"' by DalekThePerson at commit 7a3380ad0a
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit fbb314f083
#2128: 'Full auto' by Rohesie at commit 462996e5da
#2646: 'AI now automatically gets unachored on crash' by DominikPanic at commit d70f1ff624
#2649: 'Fixes a few autodoc runtimes' by DominikPanic at commit 7304e1f143

How to reproduce?
Step 1
Shoot a turret.
Step 2 
Note the fact you can't seem to note the condition of it dropped nor blowtorch it
Step 3 
Shoot it more
Step 4 
See in amasement as it dissappears from existence

What could cause it?
Probably the obj damage refractor but when I pmed lak he told me he was tired

**Comment by DominikPanic** [comment]
Fixed in latest commit of #2570
