### ISSUE TITLE
APC repair seems to be broken

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#2681]
The test merges that round were...

#2644: 'New Kitchen and Toiler sink sprites from TG' by Alterist at commit 0d7ec1f283
#2671: 'Adds some holopads around the Theseus' by grinkgo at commit 8f075e6baa
#2676: 'Fixes dropship verb on nondistress' by DominikPanic at commit db855fc89d
#2661: 'Pushing code fixes' by DominikPanic at commit a1310756a9
#2668: 'Makes extended unvoteable' by DominikPanic at commit 8dfa6bca30
#2669: 'Fixes soap attacking' by DominikPanic at commit edabeff863
#2670: 'This PR will make you laugh' by DominikPanic at commit 385577f186
#2672: 'Better aghost log' by DominikPanic at commit 2879baff04
#2653: 'Fixes washing grabs' by DominikPanic at commit d53e109048
#2662: 'Fixes the AI name on latejoin' by DominikPanic at commit 9a09730ef7
#2664: 'Fixes bucket overfilling' by DominikPanic at commit e5c8b51fb1
#2665: 'Fixes floating sinks' by DominikPanic at commit cdf9de2088
#2666: 'Removes big red pipe cheesing' by DominikPanic at commit 4787225b72
#2648: 'Makes changelog less laggy' by DominikPanic at commit 582ad1530e
#2647: 'Removes focus chat' by DominikPanic at commit 70131f63d6
#2477: 'The Rise of the ST' by Maciekkub at commit 406caa21db
#2635: 'Adds a boot knife to basic marine sets.' by grinkgo at commit 8dba752d6d
#2570: 'Object attack damage rework' by DominikPanic at commit 5af050c09e
#2645: 'Makes the pizza ERT admin only' by DominikPanic at commit 4e8f3e3978
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45
#2553: 'Insight into storage runtime' by DominikPanic at commit efda667a8a
#2599: 'Fixes a runtime when clicking with null turf in the clickcatcher' by DominikPanic at commit cb635f75c8
#2626: 'Boiler Bombard Time "rebalance"' by DalekThePerson at commit 7a3380ad0a
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit b4046711c7
#2128: 'Full auto' by Rohesie at commit 462996e5da
#2646: 'AI now automatically gets unachored on crash' by DominikPanic at commit d70f1ff624
#2649: 'Fixes a few autodoc runtimes' by DominikPanic at commit a385c2607d
#2674: 'Makes some object mob verbs living instead' by DominikPanic at commit 0aaefb677e
#2673: 'Fixes main overwatch console' by DominikPanic at commit c5b4bd0a40
#2679: 'Balance patch - marine weapons nerf.' by Rohesie at commit 5dcd0b43ce

Steps 1-Try to repair APC
Step 2-It'll get bugged around the terminal replacement part.

**Comment by DominikPanic** [comment]
Bugged in what way?

**Comment by DominikPanic** [comment]
Managed to fully deconstruct and reconstruct a broken APC, so unless you provide more info this is working as intended https://puu.sh/E6evL/53d2256840.png
