### ISSUE TITLE
Dual wield Laser + smg 2-handed (with any weapon, claymores etc)

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#27]
1
![image](https://user-images.githubusercontent.com/45321263/48986521-5c56a180-f127-11e8-83c0-c74f2c2652b3.png)

2
![image](https://user-images.githubusercontent.com/45321263/48986524-71333500-f127-11e8-99fc-01b34c434acd.png)

**Comment by Surrealaser** [comment]
Addressed in recent lasgun update.
