### ISSUE TITLE
Deployed shotgun ammo boxes can be moved.

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#2724]
## Testmerges: 

None, Master

## Reproduction:

Vend a Shotgun ammo box, the 100 round ones, any type. 
Deploy it on the ground so that you can take ammo out.
click it with an open hand to take ammo out.

The box will move(slide) onto your tile after the ammo handful spawns in your hand.

![image](https://user-images.githubusercontent.com/45076386/63225597-2b2b6f00-c197-11e9-9776-d545611c91d8.png)

![image](https://user-images.githubusercontent.com/45076386/63225600-31215000-c197-11e9-8d35-945cda1502ac.png)

**Comment by DominikPanic** [comment]
Unable to reproduce this https://puu.sh/E8HPx/1eeabfcb91.mp4

**Comment by Rohesie** [comment]
Current master: https://i.imgur.com/BqFEDf8.gifv
Vend the box from req, click on the box, it will travel to you.
