### ISSUE TITLE
Weeds taking damage after deletion

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#2741]
## Testmerges:

Round ID: 874
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 9e86e70d53f470d192a2c32f8c379d5791984ea7
The following pull requests are currently test merged:
#2643: 'Pseudo-pixel projectiles' by Rohesie at commit bcc8504701
#2679: 'Balance patch - marine weapons nerf.' by Rohesie at commit d008a90fff
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit 3541fbd902
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45
#2477: 'The Rise of the ST' by Maciekkub at commit d54db15f70
#2647: 'Removes focus chat' by DominikPanic at commit eef3223efc
#2618: 'Wolvesnotbear' by psykzz at commit 4789840dff
#2726: 'Improve the UI of the marine vendors' by psykzz at commit dc819f73d7
#2739: 'Allow only one SL for crash' by psykzz at commit ecd725fd48

## Reproduction:

```
[22:00:57] Runtime in obj_defense.dm, line 3: The weeds taking damage after deletion
proc name: take damage (/obj/proc/take_damage)
src: the weeds (/obj/effect/alien/weeds)
src.loc: null
call stack:
the weeds (/obj/effect/alien/weeds): take damage(70, "brute", "", 1, null, 0)
the weeds (/obj/effect/alien/weeds): ex act(3)
do explosion(the plating (61,89,2) (/turf/open/floor/plating/icefloor/warnplate), 0, 0, 3, null, 1, 0, 4)
world: ImmediateInvokeAsync("some_magic_bullshit", /proc/do_explosion (/proc/do_explosion), the plating (61,89,2) (/turf/open/floor/plating/icefloor/warnplate), 0, 0, 3, null, 1, 0, 4)
explosion(the plating (61,89,2) (/turf/open/floor/plating/icefloor/warnplate), 0, 0, 3, null, 1, 0, 4)
the fueltank (/obj/structure/reagent_dispensers/fueltank): explode()
the fueltank (/obj/structure/reagent_dispensers/fueltank): flamer fire act(10, 50)
the fire (/obj/flamer_fire): process(20)
Objects (/datum/controller/subsystem/processing/obj): fire(0)
Objects (/datum/controller/subsystem/processing/obj): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by DominikPanic** [comment]
I require more information

**Comment by Rohesie** [comment]
We'll have to see if it happens again.
