### ISSUE TITLE
keybinding_quickequip signal runtime

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#2743]
## Testmerges:

Round ID: 874
BYOND Version: 512.1464
Server revision compiled on:
Master commit: 9e86e70
The following pull requests are currently test merged:
#2643: 'Pseudo-pixel projectiles' by Rohesie at commit bcc8504
#2679: 'Balance patch - marine weapons nerf.' by Rohesie at commit d008a90
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit 3541fbd
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6
#2477: 'The Rise of the ST' by Maciekkub at commit d54db15
#2647: 'Removes focus chat' by DominikPanic at commit eef3223
#2618: 'Wolvesnotbear' by psykzz at commit 4789840
#2726: 'Improve the UI of the marine vendors' by psykzz at commit dc819f7
#2739: 'Allow only one SL for crash' by psykzz at commit ecd725f

## Reproduction:

```
[23:23:33] Runtime in component.dm, line 192: bad index
proc name: SendSignal (/datum/proc/_SendSignal)
usr: David Stormwell/(Theodore Fiscina)
usr.loc: (Abandoned Thunderdome (23, 36, 1))
src: Theodore Fiscina (as Unknown) (/mob/living/carbon/human/species)
src.loc: the floor (23,36,1) (/turf/open/floor)
call stack:
Theodore Fiscina (as Unknown) (/mob/living/carbon/human/species): SendSignal("keybinding_quickequip", /list (/list))
quick_equip (/datum/keybinding/human/quick_equip): down(David Stormwell (/client))
David Stormwell (/client): keyDown("E")
```

**Comment by DominikPanic** [comment]
Still needs more information as this doesn't happen every time

**Comment by DominikPanic** [comment]
Also considering this is in the thunderdome, I heavily suspect badminery being involved.

**Comment by DominikPanic** [comment]
Confirmed related to admin pressing buttons
