### ISSUE TITLE
Cryo Console Items Bug

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#2744]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 874
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 9e86e70d53f470d192a2c32f8c379d5791984ea7
The following pull requests are currently test merged:
#2643: 'Pseudo-pixel projectiles' by Rohesie at commit bcc8504701
#2679: 'Balance patch - marine weapons nerf.' by Rohesie at commit d008a90fff
#2642: 'Chat subsystem optimization plus a fallback solution' by DominikPanic at commit 3541fbd902
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45
#2477: 'The Rise of the ST' by Maciekkub at commit d54db15f70
#2647: 'Removes focus chat' by DominikPanic at commit eef3223efc
#2618: 'Wolvesnotbear' by psykzz at commit 4789840dff
#2726: 'Improve the UI of the marine vendors' by psykzz at commit dc819f73d7
#2739: 'Allow only one SL for crash' by psykzz at commit ecd725fd48

Local commit: 69210990a5211df4ff713b2c5081bcfe86374eec
Server tools version: /tg/station 13 Server v3.2.6.2
## Reproduction:
Have someone with items that have inventory of their own cryo. Pill bottles will be filed separately from all their individual pills, MRE components separate from the MREs themselves, that sort of thing.

**Comment by DominikPanic** [comment]
@Ghommie
