### ISSUE TITLE
Using Acid Spray as Spitter or Praetorian targetting through walls causes it to not fire.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#2746]
## Reproduction:
Use acid spray through a wall or with an obstacle.
It should be like acid spit and just go where ever you're aiming, however it just gives you a message telling you it can't shoot there and doesn't fire.
Likely cause is:
#1858

**Comment by DominikPanic** [comment]
This is intended
