### ISSUE TITLE
Neurotoxin still remains in your body after the EORD warp.

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2747]
## Testmerges:

None.

## Explanation:

Everybody knows that if you stay in your body, while dead, before the match is over, you won't spawn into the EORD as a random UPP. You'll spawn in with your regular body, completely ahealed, just like any other marine or xeno that was still alive.

However, if you were previously blinded before dying completely, usually I assume from eye damage or neurotoxin, you will still be blind in the EORD, even if you get completely healed.

## Reproduction:

Step 1: Die. Preferably by aggressive neurospit and then a good hearty slasihng.

Step 2: Wait until the EORD. Make sure you are in the body that god neurospitted.

Step 3: Spawn into the EORD Arena in your body. You'll most likely be blind.

## Effects:

It makes you blind in the EORD. Self explanatory.

**Comment by DominikPanic** [comment]
Can you provide more details and a screenshot of the blindness itself, please?

**Comment by CoreFlare** [comment]
I'm done some field testing, and I've come to a conclusion.

It's not blindness itself that persists. It's neurotoxin.

Neurotoxin isn't removed from your body by the heal at the EORD.

I'll adjust the bug report accordingly.

**Comment by CoreFlare** [comment]
## Testmerges:

None.

## Explanation:

Everybody knows that if you stay in your body, while dead, before the match is over, you won't spawn into the EORD as a random UPP. You'll spawn in with your regular body, completely ahealed, just like any other marine or xeno that was still alive.

However, if your body has neurotoxin in it before the EORD, and you spawn in it, you will still have that neurotoxin even if you get completely healed by the EORD warp.

## Reproduction:

Step 1: Die. Make sure you have a shit ton of neurospit in your body before you die.

Step 2: Wait until the EORD. Make sure you are in the body that god neurospitted.

Step 3: Spawn into the EORD Arena in your body. You'll most likely be high on neuro.

## Effects:

It just means that Neurotoxin persists into the EORG.
