### ISSUE TITLE
Resin silo spawns are not uniquely named

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#2758]
## Testmerges:

Server-Side Code Modifications:  https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm 

Round ID:  883 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: 5d0eced05915f93f732d8a6931ffe7ced69dad32 
The following pull requests are currently test merged: 
#2750: 'Removes a frustrating warning when using acid spray' by DominikPanic at commit 3dda5ba631 
#2751: 'Fixes shotgun spelling issue' by DominikPanic at commit ea53fe36a0 
#2726: 'Improve the UI of the marine vendors' by psykzz at commit dc819f73d7 
#2618: 'Wolvesnotbear' by psykzz at commit 4789840dff 
#2647: 'Removes focus chat' by DominikPanic at commit eef3223efc 
#2477: 'The Rise of the ST' by Maciekkub at commit d54db15f70 
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45 

Local commit: 047a144fdafec8dc5ce7aee500832315613ee944 
Server tools version: /tg/station 13 Server v3.2.6.2 

## Reproduction:

Resin silo spawns are not uniquely named
When you try to spawn, only one option is available.

**Comment by Rohesie** [comment]
I distinctly remember adding the area they spawn in to their name and PRing that to your crash branch. Weird.
