### ISSUE TITLE
Purple sac doesn't always emit sound when hit

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2763]
## Reproduction:
I took out a knife, N5 Night Raider something along hte lines of this, sniped those purple sacs with it and to my surprise, sometime there was no sounds at all, sometimes only couple hits emitted a sound.

**Comment by DominikPanic** [comment]
It's any objects, since the part that is failing is the playsound proc itself, after fucking around with it for a fair bit (including the open channel thing /tg/ is doing), I was unable to fix this

**Comment by DominikPanic** [comment]
@Ghommie Any idea?

**Comment by Ghommie** [comment]
Any runtime on the matter?

**Comment by DominikPanic** [comment]
Zero runtimes, easily reproducible on master, everything triggers correctly when I added debug messages, but the sound just doesn't play
