### ISSUE TITLE
Reinforced Girders Bug

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#2778]
## Reproduction:

Smash a reinforced girder with something until it is destroyed, watch in amazement as a reinforced WALL replaces the girder magically.

**Comment by Rohesie** [comment]
That happened on Big Red's LZ 1. Could also be a wall under the girder.

**Comment by DominikPanic** [comment]
Unable to reproduce https://puu.sh/E8VHz/4e5bbfb073.mp4
