### ISSUE TITLE
Wire cutting runtime

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#2779]
## Testmerges:

Round ID: 892
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: c4d01da8263d8cee4c223950df7f8fe1c04c2a8f
The following pull requests are currently test merged:
#2777: 'Stuff the AI will like (hopefully not broken this time)' by grinkgo at commit a15672e3ad
#2775: 'Adds the reason to adminban relay' by DominikPanic at commit 92052bb9d1
#2776: 'Fixes shotgunbox issues' by DominikPanic at commit e308177e77
#2773: 'Fixes and slightly cleans up wielding code' by DominikPanic at commit ead60b4d8b
#2643: 'Pseudo-pixel projectiles' by Rohesie at commit d74b458648
#2752: 'Patches up an issue with storage items and cryo.' by Ghommie at commit 4d566c1923
#2755: 'Roundstart xenos start at max upgrade' by psykzz at commit 070cd9899f
#2757: 'Allow bullets to pass the fog barriers' by psykzz at commit 49a56593c8
#2750: 'Removes a frustrating warning when using acid spray' by DominikPanic at commit ab21275de9
#2751: 'Fixes shotgun spelling issue' by DominikPanic at commit ea53fe36a0
#2726: 'Improve the UI of the marine vendors' by psykzz at commit dc819f73d7
#2647: 'Removes focus chat' by DominikPanic at commit eef3223efc
#2477: 'The Rise of the ST' by Maciekkub at commit d54db15f70
#2364: 'Support emoji and emoji picker.' by DeadLineSS13 at commit 6e9a5c6a45
#2766: 'Alert xenos when nuke is set' by psykzz at commit 92718898da
#2772: 'Smartgun aimslowdown' by Rohesie at commit b679d4f49a
#2734: 'New, More distinct B18 sprite' by Metroidlover at commit 523900e73e

## Reproduction:

```
[05:56:33] Runtime in _wires.dm, line 152: Cannot read null.mind
proc name: cut (/datum/wires/proc/cut)
src: /datum/wires/mulebot (/datum/wires/mulebot)
call stack:
/datum/wires/mulebot (/datum/wires/mulebot): cut("Receive")
/datum/wires/mulebot (/datum/wires/mulebot): cut random()
Mulebot (#3) (/obj/machinery/bot/mulebot): bullet act(the minigun bullet (/obj/item/projectile))
Mulebot (#3) (/obj/machinery/bot/mulebot): do projectile hit(the minigun bullet (/obj/item/projectile))
the minigun bullet (/obj/item/projectile): scan a turf(the floor (25,79,2) (/turf/open/floor/tile/dark/brown2))
the minigun bullet (/obj/item/projectile): projectile batch move(3)
the minigun bullet (/obj/item/projectile): process(2)
Projectiles (/datum/controller/subsystem/processing/projectiles): fire(0)
Projectiles (/datum/controller/subsystem/processing/projectiles): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by DominikPanic** [comment]
Fixed in #2784
