### ISSUE TITLE
Two-tile emergency shutters don't block view properly

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#2820]
## Reproduction:

1) Close a two-tile emergency shutter.
![image](https://user-images.githubusercontent.com/44811257/64054614-82452280-cb4d-11e9-9dd8-a7ca97b7c825.png)
![image](https://user-images.githubusercontent.com/44811257/64054622-8709d680-cb4d-11e9-9df8-88b21080363d.png)

**Comment by DominikPanic** [comment]
I haven't been able to reproduce this one locally

**Comment by Rohesie** [comment]
Could you provide the object path of these shutters, or where to find them?
