### ISSUE TITLE
Dead human still has a pulse

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/TerraGov-Marine-Corps#2826]
## Testmerges:
Round ID:  946 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: c2862d6f94028f8efc34581d8cb4ae35c19bc88d 
The following pull requests are currently test merged: 
#2821: 'Fixes a sound runtime' by DominikPanic at commit 76f205e490 
#2736: 'Movespeed mod and datum charge/crushing' by Rohesie at commit 48826a261c 
#2797: 'Reduces the roundstart notransform lock time' by DominikPanic at commit 83b60755ef 
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051 
#2795: '[WIP] Pillar of Spring' by grinkgo at commit ff2a5ef8af 
#2823: 'Fixes powerloader clamp runtimes' by DominikPanic at commit df72aa5602 
#2825: 'Incoming mentorhelps now have a different sound' by DominikPanic at commit ec8dfe9057 
#2819: 'New PFC armor sprites and new squad color armor markings' by Metroidlover at commit be5cc9c6fa 
#2814: '[W.I.P] Interaction rework' by DominikPanic at commit 25fad0c659 

## Reproduction:
I found a dead body, shift clicked him and he had a pulse but he was actually dead. https://cdn.discordapp.com/attachments/187232844119015435/617464760925159424/Capture_decran_296.png

**Comment by DominikPanic** [comment]
If you find one in-game DM me or ahelp, this seems to be an edge case.
