### ISSUE TITLE
Planting Eggs Underneath Objects

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#2828]
## Testmerges:
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 949
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: c2862d6f94028f8efc34581d8cb4ae35c19bc88d
The following pull requests are currently test merged:
#2821: 'Fixes a sound runtime' by DominikPanic at commit 76f205e490
#2736: 'Movespeed mod and datum charge/crushing' by Rohesie at commit 48826a261c
#2797: 'Reduces the roundstart notransform lock time' by DominikPanic at commit 83b60755ef
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051
#2795: '[WIP] Pillar of Spring' by grinkgo at commit ff2a5ef8af
#2823: 'Fixes powerloader clamp runtimes' by DominikPanic at commit df72aa5602
#2825: 'Incoming mentorhelps now have a different sound' by DominikPanic at commit ec8dfe9057
#2819: 'New PFC armor sprites and new squad color armor markings' by Metroidlover at commit be5cc9c6fa
#2814: '[W.I.P] Interaction rework' by DominikPanic at commit 5f3a5d6e68

Local commit: 4c5cfbf50171dbb11b3322ba9556335a64ab82a3
Server tools version: /tg/station 13 Server v3.2.6.2
## Reproduction:
The issue here is xenos being able to plant eggs underneath obscuring objects. Mainly at this point, trees. You can't see the egg unless you right click the exact tile(which is usually difficult to do since right clicking the tree tends to get you the base tile of the tree), you can't shoot the egg without seeing it. Basically we just need to...make the eggs layer over everything, like we did to mines.

**Comment by DominikPanic** [comment]
@Rohesie What do you think?

**Comment by drawsstuff** [comment]
I've seen this used to great effect but wouldn't mind seeing it go. Carrier traps exist for a reason.

**Comment by Alterist** [comment]
I feel like the trees I coded in are causing this issue, is there a way to make the tree semi-transparent?

**Comment by Rohesie** [comment]
3/4 perspective and objects larger than 32x32 are an issue, and not a trivial one.
By something behind it you mean specifically an egg, or anything?
The tree could react to a signal on the turf directly north of it, on `Entered()` and reduce the alpha if needed. Or produce a visual object or overlay to signal there's something behind it.
But again, not trivial.
