### ISSUE TITLE
Objects that can have items put in them destroy the items if the object is destroyed.

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2840]
## Testmerges:

None.

## Explanation:

Read above. Self explanatory, you can delete items if they are put into a destructable object. My favourite is the fax machine.

## Reproduction:

There should be multiple ways to reproduce this, but I'll list the one I used.

Step 1: Find a fax machine. It doesn't matter if it's powered or not.

Step 2: Put an ID or piece of paper in there. It doesn't matter which, and you can even do both. They'll be destroyed anyway.

Step 3: Take your trust M5 Survival Knife and knife that sucker to death. Once it's destroyed, the ID and/or paper will be gone with it.

## Effects:

People like me get salty, write bug reports like this, and end up losing their ID.

**Comment by DominikPanic** [comment]
That is intended for 99% of things, the only exceptions should be explicitly defined.
