### ISSUE TITLE
Voting tabs not closing

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#2847]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 954
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: 2f606a139203b3d12372488232b77b9964fb99a4
The following pull requests are currently test merged:
#2814: '[W.I.P] Interaction rework' by DominikPanic at commit c51c1067fa
#2819: 'New PFC armor sprites and new squad color armor markings' by Metroidlover at commit be514ffff9
#2825: 'Incoming mentorhelps now have a different sound' by DominikPanic at commit ec8dfe9057
#2823: 'Fixes powerloader clamp runtimes' by DominikPanic at commit df72aa5602
#2795: '[WIP] Pillar of Spring' by grinkgo at commit ff2a5ef8af
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051
#2797: 'Reduces the roundstart notransform lock time' by DominikPanic at commit 83b60755ef
#2821: 'Fixes a sound runtime' by DominikPanic at commit 76f205e490
#2695: 'YeeHaw cowboy time, it's a lever action rifle' by Hughgent at commit 68493c4f40
#2834: 'SMG ammunition naming change ' by Maciekkub at commit 755c863cb8
#2832: 'Fixes hunter stealth attack issues' by DominikPanic at commit 2359322ef7
#2829: 'Fix xeno minor conditions' by psykzz at commit ec50e91de4
#2838: 'Fixes being able to take over aghosted xenos' by DominikPanic at commit 0b4b2099cd
#2837: 'Fixes aSL not having orders available' by DominikPanic at commit 337dbcbc74
#2836: 'Fixes ship map reference name replace' by DominikPanic at commit 8939e68868
## Reproduction:
1. Start a vote of some sort (Only worked with groundmap vote for me so I don't know if it works for other votes too).
2. Try to close the tab.

**Comment by DominikPanic** [comment]
Fixed in #2814
