### ISSUE TITLE
Being nested, dead and in your body doesn't teleport you to the EORD.

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2862]
## Testmerges:

None.

## Explanation:

Read title. If you are simultaneously nested, dead, and in your body when the round ends, you won't be teleported to the EORD.

## Reproduction:

Step 1: Get nested by a xenomorph, preferably in hardcrit.

Step 2: Die to hardcrit.

Step 3: Be in your body at the end of the round, while still nested, and dead.

You won't be teleported to the EORD.

## Effects:

Read above.

Oh, and I write bug reports like these.

## Disclaimer:

If this does not work on your end if you are testing this, then it may be due to entering your body that is both nested and dead at the same time the EORD spawn happens. This has only happened once to me, and I'll update information in comments if it happens again.

**Comment by DominikPanic** [comment]
Unable to reproduce locally.

**Comment by CoreFlare** [comment]
It might be something to do with re-entering the body the moment the spawn happens. I'll have to test it more, so for now issue closed.
