### ISSUE TITLE
Blood-stained Marine combat boots are invisible on person.

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2864]
## Testmerges:

None.

## Explanation:

Read title.

## Reproduction:

Step 1: Wear some blood-stained marine combat boots.

OR

Step 1: Wear some marine combat boots.

Step 2: Walk in some blood or a dead body or something.

Both of these methods should produce this bug.

## Effects:

Makes it look like you're barefoot with bloody feet.

**Comment by DominikPanic** [comment]
Also unable to reproduce locally.
https://puu.sh/Edu3d/4b915b33c8.png

**Comment by CoreFlare** [comment]
Huh. I'll try and see if it's a client side issue.

**Comment by Henriquekill9576-taken** [comment]
I think it needs to have a knife in it
