### ISSUE TITLE
Opening another container while looking in a spec kit causes the two to overlap.

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#2866]
## Testmerges:

None.

## Explanation:

Just as it sounds. They interfaces overlap each other, although this usually works better with 

## Reproduction:

Step 1: Get a spec kit. The one I used for this is the Scout Shotgun kit.

Step 2: Open the kit. Make sure not to take anything out, or only take out one item. It doesn't work if it goes from Red, to Yellow, to Grey again. Make sure it's overstocked with items to the point where if you try to put one in it doesn't fit.

Step 3: Open another container, my favourite is your suit storage. The two interfaces should overlap.

## Effects:

Makes menu navigation annoying if the two overlap and you can't press the collapse button easily because an item is in the way.

**Comment by DominikPanic** [comment]
Also unable to reproduce locally
https://puu.sh/Edu9d/c43fa509db.gif
