### ISSUE TITLE
Broken APCs

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#2874]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 969
BYOND Version: 512.1464
Server revision compiled on: 
Master commit: af101065fb31c1fb136b0d637a0b490ba4c7976d
The following pull requests are currently test merged:
#2833: 'Removes MP skill and tank access from PMC' by Maciekkub at commit 40ac2c25dc
#2854: 'Changes the Integrated Storage to hold a gun.' by Hughgent at commit fb2887bfe8
#2853: '4 Helmet Storage Slots' by Aurelien3189 at commit b7d267ebaf
#2852: 'Small M39 Mags' by Aurelien3189 at commit ca3b2fd1fb
#2814: 'Interaction rework' by DominikPanic at commit 77f44adfe3
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051
#2870: 'Fixes adminwho without mentors' by DominikPanic at commit b3972144b9
#2869: 'Removed Queen screech's screen shake for xenomorphs' by GhostAvenger at commit 2e690ea617
#2871: 'Fixes flares not burning weeds' by DominikPanic at commit 3a1797b7be
#2873: 'Youtubedl tweaks' by DominikPanic at commit c7d3d30e29

Local commit: 5c248207238750795b9dd61593762ffb955e3744
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. Screwdriver an APC
2. Try to mess around with the wires, pulsing and cutting won't work

**Comment by Henriquekill9576-taken** [comment]
Apparently that bug is on every machine that has wires

**Comment by DominikPanic** [comment]
Fixed in latest commit of #2814
