### ISSUE TITLE
Ghosts are able to flip tables

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#2878]
## Testmerges:
#2833: 'Removes MP skill and tank access from PMC' by Maciekkub at commit 40ac2c25dc
#2854: 'Changes the Integrated Storage to hold a gun.' by Hughgent at commit fb2887bfe8
#2853: '4 Helmet Storage Slots' by Aurelien3189 at commit b7d267ebaf
#2852: 'Small M39 Mags' by Aurelien3189 at commit ca3b2fd1fb
#2814: 'Interaction rework' by DominikPanic at commit 77f44adfe3
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051
#2870: 'Fixes adminwho without mentors' by DominikPanic at commit b3972144b9
#2869: 'Removed Queen screech's screen shake for xenomorphs' by GhostAvenger at commit 2e690ea617
#2871: 'Fixes flares not burning weeds' by DominikPanic at commit 3a1797b7be
#2873: 'Youtubedl tweaks' by DominikPanic at commit c7d3d30e29

## Reproduction:
As the title says, ghosts are able to flip tables. This was noticed during EORD but I was able to replicate it on the ship (Theseus) and on the planet map (LV624)

**Comment by DominikPanic** [comment]
Fixed in latest commit of #2814
