### ISSUE TITLE
Widnow frames unclimbable

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#2889]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 978
BYOND Version: 512.1479
Server revision compiled on: 
Master commit: 7fa72f08f7cc64aa74ab7c7cde6a77088f1bfa43
The following pull requests are currently test merged:
#2880: 'Fixes even more fog cheesing' by DominikPanic at commit fb3f9c2f22
#2881: 'Fixes invisible shoes' by DominikPanic at commit e669bae409
#2854: 'Changes the Integrated Storage to hold a gun.' by Hughgent at commit fb2887bfe8
#2853: '4 Helmet Storage Slots' by Aurelien3189 at commit b7d267ebaf
#2852: 'Small M39 Mags' by Aurelien3189 at commit ca3b2fd1fb
#2814: 'Interaction rework' by DominikPanic at commit 7571a15d5f
#2782: 'Fulton extraction devices' by Rohesie at commit f989905051
#2870: 'Fixes adminwho without mentors' by DominikPanic at commit b3972144b9
#2869: 'Removed Queen screech's screen shake for xenomorphs' by GhostAvenger at commit 2e690ea617
#2871: 'Fixes flares not burning weeds' by DominikPanic at commit 3a1797b7be
#2873: 'Youtubedl tweaks' by DominikPanic at commit c7d3d30e29
#2872: 'Rage no longer ticks down or gives damage resist' by factoryman942 at commit 111f9fbdec
#2886: 'Cleans up workaround for fixed compiler bug' by DominikPanic at commit ac62e7d856
#2885: 'Fixes goonchat line height for IE8' by DominikPanic at commit 065d31ecce
#2884: 'Cleans up combat defines' by DominikPanic at commit 03e473ce7b
#2882: 'Fixes more sound runtimes' by DominikPanic at commit 7838fbfaae

Local commit: ce06e73b71339db021496e38666705ca11fbaeed
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Simply try to climb a window frame (only did that as a beno, dunno if it doenst work for humans too

**Comment by DominikPanic** [comment]
Fixed in latest commit of #2814
