### ISSUE TITLE
More synth reviving bugs

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#2895]
## Testmerges:

#2890 #2880 #2881 #2854 #2853 #2852 #2814 #2782 #2870 #2869 #2871 #2873 #2872 #2886 #2885 #2884 #2882 #2894 #2892 #2891

## Reproduction:

I died to acid. Got rezzed by defib. My vision still blurry tho and my health indicator said I was still dead.
![dreamseeker_2019-09-08_19-43-15](https://user-images.githubusercontent.com/49525951/64496778-a81da600-d276-11e9-9e3c-73f909d67094.png)

**Comment by DominikPanic** [comment]
There is more to it, trying to replicate this exact scenario didn't yield any results
https://gyazo.com/28a6b6a61aeae8a54edf9b39180e167f

**Comment by Rohesie** [comment]
Has this happened again?
