### ISSUE TITLE
Weird ammobox interaction

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2896]
## Testmerges:
#2890, #2880, #2881, #2854, #2853, #2852, #2814, #2782, #2870, #2869, #2871, #2873, #2872, #2886, #2885, #2884, #2882, #2883, #2894, #2892, #2891

## Reproduction:
I clicked "Z" while holding the extended M41A1 pulse rifle ammo box and it dropped on the ground open, although my hand, whilst empty, was still occupied and i was unable to use it until i dropped the empty hand

**Comment by DominikPanic** [comment]
Unable to reproduce, please provide exact steps or a video
https://puu.sh/EffaQ/91297a1b4f.mp4

**Comment by Maciekkub** [comment]
It is difficult to reproduce but managable, spawn an ammobox, pick it up, switch active hands, click on the ammobox in your other hand, it moves to your active hand now, use the action button, it drops on the ground - Now there should be a phantom of it in one of your hands, you are able toa ttack yourself with it and other interactions and upon dropping it will shove towards you, or teleport. Can't provide a video because it is overmy gyazo limit and doesn't capture the entire scene, if still unable to reproduce i'll make-do and provide one
