### ISSUE TITLE
Interaction spam

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2897]
## Testmerges:

#2890, #2880, #2881, #2854, #2853, #2852, #2814, #2782, #2870, #2869, #2871, #2873, #2872, #2886, #2885, #2884, #2882, #2883, #2894, #2892, #2891...
## Reproduction:
You can spam interactions such as putting barbed wire on a cade or dismantle table pretty much with the speed of light massing multiple instances of the dismantling at once

**Comment by DominikPanic** [comment]
This is how the system is intended to work, it's the exact same on /tg/.

**Comment by Rohesie** [comment]
We had this solved by putting a `if(user.active) return` most of the time.
I'm out of the loop here, but wouldn't that be feasible?
