### ISSUE TITLE
Paladin pump shotgun sprite

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2898]
## Testmerges:

#2890, #2880, #2881, #2854, #2853, #2852, #2814, #2782, #2870, #2869, #2871, #2873, #2872, #2886, #2885, #2884, #2882, #2883, #2894, #2892, #2891...

## Reproduction:
The sprite is the same for both holding it in one hand as well as two hand

**Comment by DominikPanic** [comment]
@Alterist PR'd this sprite so I'll leave it for them to decide if that was intended or not

**Comment by Alterist** [comment]
it was intended, but it was really just me being lazy
