### ISSUE TITLE
Table interactions on harm intent

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2899]
>

## Testmerges:

#2890, #2880, #2881, #2854, #2853, #2852, #2814, #2782, #2870, #2869, #2871, #2873, #2872, #2886, #2885, #2884, #2882, #2883, #2894, #2892, #2891...

## Reproduction:

If you attempt to put something on a table when you are on harm intent you shall put it as well as punch the table

**Comment by DominikPanic** [comment]
Unable to reproduce, please provide more details
https://puu.sh/Eff9J/1843ccdc9a.mp4

**Comment by Maciekkub** [comment]
https://gyazo.com/077f4b43b55e5119eb78c93958099366
Seems to be the case only certain items, because multitool didn't work but the wrappers in the video did
