### ISSUE TITLE
Doubled equipment for offered mobs

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2900]
## Testmerges:

#2890, #2880, #2881, #2854, #2853, #2852, #2814, #2782, #2870, #2869, #2871, #2873, #2872, #2886, #2885, #2884, #2882, #2883, #2894, #2892, #2891...
## Reproduction:
If you take an offered mob you can use all the items again, your vendor points are at the max, you can take new clohtes and so on, even if you have them on you already

**Comment by DominikPanic** [comment]
Considering that this is an admin only action, and that equipment is tied to the mobs mind that may no longer be present in the mob being taken over (which is most likely the reason they were offered in the first place), I'll say this is intended.

Plus, spec kits cannot be duplicated this way anyway, and the body you are taking over may be in various stages of fucked up or missing gear, so it's a nice bonus.
