### ISSUE TITLE
Hypospray menu 

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/TerraGov-Marine-Corps#2901]
## Testmerges:

#2890, #2880, #2881, #2854, #2853, #2852, #2814, #2782, #2870, #2869, #2871, #2873, #2872, #2886, #2885, #2884, #2882, #2883, #2894, #2892, #2891...

## Reproduction:

Everytime you open the hypospray menu it brings you the dosage amount menu up, even though you don't click it

**Comment by DominikPanic** [comment]
Fixed in latest commit of #2814
