### ISSUE TITLE
Speedloaders don't fit in helmets.

### ISSUE THREAD

**Issue by Fireiy** [tgstation/TerraGov-Marine-Corps#2917]
With the helmet change, helmets can now fit pistol magazines and smg magazines. However, speedloaders do not fit.

## Reproduction: 
Attempt to put speedloaders into helmets.

**Comment by DominikPanic** [comment]
Currently the code does what it's supposed to, and the PR doesn't mentioned speedloaders being affected.

Thus, this makes it not a bug. But feel free to make a change anyway.
