### ISSUE TITLE
You can melt things and hit them threw containment shutters

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#2918]
## Testmerges:
The following pull requests are currently test merged:
#2854: 'Changes the Integrated Storage to hold a gun.' by Hughgent at commit d4e710315c
#2764: 'Round end after xenos defuse the nuke' by psykzz at commit 4ab8e489ec
#2911: 'Oh well' by DominikPanic at commit 15ed422138
#2905: 'Viable Non-standard weapons' by Aurelien3189 at commit f6f81dfa71
#2877: 'Improved ERT Spawn Messages' by XSlayer300 at commit bcf917ffef

## Reproduction:
1. Launch a round.
2. walk up as bean to a containment shutter
3. press alt+click
4. you can now melt and attack any non containment shutter object.

**Comment by GhostAvenger** [comment]
I have experimented with this, but there are some objects you still cannot melt if I remember correctly, such as main LZ1 doors at LV, and some doors on other maps as well.

**Comment by Rohesie** [comment]
You can only melt meltable things next to you. That is the intended behavior.
Are you saying you should not be able to melt things under a shutter?
