### ISSUE TITLE
You can hijack the dropship while it is moving.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#2935]
I'm guessing this is caused by the shuttle refactor. But it makes evacuation basically impossible since the queen can just call it back down and meme all your marines. 
Should probably be removed.
Anyways. The step to reproduce are these.

1. When you meet the requirements to call down the DS you can move it while it is moving. 
2. So call it down while the marines are evacuating the planet.
3. The marines can now never leave the planet and are basically sitting ducks from this point onwards.

**Comment by CoreFlare** [comment]
Found this out on round 1045, we had just escaped on the Alamo but they called it back down. I'm guessing they called it back down once it had launched, as when I tried to use the console again after they called it a hijack was detected. We were able to launch via the console on the shuttle, though.

**Comment by CoreFlare** [comment]
Turns out that you can do it on both sides. Marines can call it back too from the console on the Theseus. Guess Marines aren't doomed, although they better not abuse it.
