### ISSUE TITLE
CMO ID issues

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#2959]
## Testmerges:

#2956 #2944 #2945 #2946 #2948 #2941 #2922 #2914 #2764 #2938 #2952 #2954 #2955 #2939

## Reproduction:

CMO is unable to open gun cabinets, such as those in their armory or on the Canterbury.

**Comment by grinkgo** [comment]
I might just fix this by replacing varedited gun cabinets with good versions.

**Comment by Rohesie** [comment]
That'd be a good fix.
