### ISSUE TITLE
Window barricade jump.

### ISSUE THREAD

**Issue by Locating** [tgstation/TerraGov-Marine-Corps#2968]
![barricade glitch](https://user-images.githubusercontent.com/20954280/65379084-47d03080-dc88-11e9-9a7c-89759332f3b2.JPG)

## Reproduction:

I was playing an ancient runner, I ran into a broken window that led to a barricade, which caused me to jump the barricade, but not back out.

**Comment by Rohesie** [comment]
We couldn't reproduce this. Let's see if it happens again.

**Comment by Rohesie** [comment]
This one is very obscure, and we'll have to see it happen again.
