### ISSUE TITLE
'Hjacked' Dropship can be forced to land on desired location mid flight.

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#2973]
Decided to test the controls as AI and apparently the controls of Alamo are not locked out during hijack, meaning people can force the Xenos to crash on planet. While it is already made against the rules to do so the lone idea that such problem exists leaves opportunity for people to abuse it.

**Comment by Spyroshark** [comment]
Adding onto this bug, the Alamo can also be launched by the AI after it has crash landed on the Theseus
