### ISSUE TITLE
Queen way too fat

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#2979]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 1079
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: 87a2b63d0d6aed35c5a2044021422cad9048bebe
The following pull requests are currently test merged:
#2970: 'Fixes init issues' by Rohesie at commit 91664b7995
#2940: 'Armor resprite 2: Electric Boogaloo' by Metroidlover at commit 0513546ce6
#2965: 'Removes the stray pixel on the slash animation' by Spyroshark at commit a9bb19e622
#2966: 'Performance test on bullet_act related procs' by Rohesie at commit 9107c35b55
#2964: 'Density cleanup' by Rohesie at commit d0e8cc1207
#2941: 'Xeno bull' by Rohesie at commit 27af7b99ca
#2952: 'Crash xeno numbers patch' by Rohesie at commit 87646c1d9b
#2955: 'Runtime fixes.' by Rohesie at commit d13084d36a
#2960: 'Nerfs the Queen's screech ability' by Spyroshark at commit 61130d4eaf
#2764: 'Round end after xenos defuse the nuke' by psykzz at commit 4ab8e489ec

Local commit: 629f4b65418d8c99e47baea8ec9c9c8e17ac9a26
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Try to climb a ladder as a queen

**Comment by Rohesie** [comment]
Can't reproduce.
Can you provide more info?

**Comment by davidchan13** [comment]
She got them thicc egg bearing hips.

**Comment by Rohesie** [comment]
Queens can use ladders just fine, so this no longer happens.
