### ISSUE TITLE
Intercom in AI core for general comms during Tcoms outtage.

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#2983]
Intercoms work as substitute for communication during situations when main Tcomms are offline. They are everywhere but not in AI core which is forced to relay solely on Announcement system that has delays while Intercoms should be a part of AI core to assist with matters and speed up communication.

**Comment by Rohesie** [comment]
This is not a bug. Feel free to add this, it's very easy to do, and a good suggestion.
