### ISSUE TITLE
Sometimes the New Player Options window doesn't go away

### ISSUE THREAD

**Issue by Spyroshark** [tgstation/TerraGov-Marine-Corps#2992]
## Testmerges:
#2986, #2980, #2981, #2764, #2964, #2966, #2970, #2977, #2984, #2988, #2987, #2990

## Reproduction:

Sometimes when I click to join the game, the "New Player Options" window doesn't go away once i'm in the game. I'm not that sure what circumstances this issue happens under since it seems to happen randomly, but I only see it when late-joining into the round.

(This is the window i'm talking about)
![please fix this bug](https://user-images.githubusercontent.com/35285914/65469320-0cbf3000-de35-11e9-880b-c2d711c93794.PNG)

**Comment by Rohesie** [comment]
Will need a specific way to reproduce it to fix it.
Else can't do much about it.

**Comment by Spyroshark** [comment]
I’ll test a bit on a local server and see if I can figure out exactly what keeps causing this.
