### ISSUE TITLE
Dropship sentry stays active when it's sentry deployment system is destroyed

### ISSUE THREAD

**Issue by Spyroshark** [tgstation/TerraGov-Marine-Corps#2993]
## Testmerges:
#2986, #2980, #2981, #2764, #2964, #2966, #2970, #2977, #2984, #2988, #2987, #2990 

## Reproduction:
Break the sentry deployment system as a xenomorph. When it breaks, the turret will still be in place, and function without it. if the Dropship takes off when the turret system is destroyed, the disconnected sentry will stay where it is, and function just fine despite the dropship not being there.
![turretbug](https://user-images.githubusercontent.com/35285914/65470135-efd82c00-de37-11e9-94ca-b7b4f8ce4e1d.PNG)
![turretbug2](https://user-images.githubusercontent.com/35285914/65470137-f1a1ef80-de37-11e9-9542-5e62bc32ee88.PNG)

**Comment by Rohesie** [comment]
Kind of makes sense?

**Comment by Rohesie** [comment]
Fair enough.

**Comment by Rohesie** [comment]
Does this still happen?
