### ISSUE TITLE
We can get out of the Alami mid-transit

### ISSUE THREAD

**Issue by n0rm4ld3f4ult** [tgstation/TerraGov-Marine-Corps#2994]
## Testmerges:

#2986 #2980 #2981 #2764 #2964 #2966 #2970 #2977 #2984 #2988 #2987 #2990 

## Reproduction:

1. Go to the Alamo
2. Stay in the doors, where the shutters are located
3. Launch Alamo
4. Exit Alamo 

Possible solution to the problem: Invisible walls.

**Comment by psykzz** [comment]
This is technically fixed via #3526.
When you leave the Alamo, you'll instantly die.
