### ISSUE TITLE
Dropship LZ landing lights and sounds not activating before dropship lands

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#2995]
Noticed when synth was crushed as dropship was landing on Ice Colony. There were no sounds or lights when the dropship landed. 

## Testmerges:
#2986: 'Wall armor: resistant walls' by Rohesie at commit 3005c79f2f
#2980: 'Revolver runtime fix' by Rohesie at commit 61bc0ed7e7
#2981: 'Xeno ability destroy fix' by Rohesie at commit 0fe381fe9a
#2764: 'Round end after xenos defuse the nuke' by psykzz at commit 4ab8e489ec
#2964: 'Density cleanup' by Rohesie at commit d0e8cc1207
#2966: 'Performance test on bullet_act related procs' by Rohesie at commit eb2617f753
#2970: 'Fixes init issues' by Rohesie at commit 91664b7995
#2977: 'Hijacks /client/click() to return focus to the input bar, Fixes FC dropping input.' by francinum at commit 6d9bba6cde
#2984: 'Rogue shots fixes' by Rohesie at commit eb4b998d45
#2988: 'Fixes another hallucination runtime' by Rohesie at commit 5f57a0b9b5
#2987: 'Undamageable atmospheric stuff' by Rohesie at commit e7226eab5a
#2990: 'Crash xeno evolution' by Rohesie at commit 4f33681960

## Reproduction:
Call dropship, Stand in middle of LZ, Try and avoid dropship crushing you.

**Comment by Mr-Worth** [comment]
While writing this issue the DS landed next to my observer, it does seem that it makes noise but the lights do not flash.

**Comment by Rohesie** [comment]
Fixed by adding the ripple effects.
