### ISSUE TITLE
PMC armor sprite bug

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#3006]
## Reproduction:

M4 PMC armor looks like this https://gyazo.com/f566a78dc322c2beac7a4725039fbda7 at least on ice colony's PMC lockers (full examination: https://gyazo.com/611e4b93919efafafeff3a8e1a05a0dd )

**Comment by Rohesie** [comment]
Fixed in latest commit of #3005
