### ISSUE TITLE
You can hide eggs under crates.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#3032]
Why aren't these layered over everything anyway???
Testmerges were
#3025: 'ice lz1 unshrunk' by spookydonut at commit 610c80af6a
#3026: 'Fixes a crate runtime' by Rohesie at commit af8ba969b4
#3022: 'New, harder to see, resin traps' by Metroidlover at commit 4c597ae8a8
#3020: 'More armor and no more Squad markings on armor' by Metroidlover at commit 5d02a2cad5
#3014: 'neuro*0.8' by factoryman942 at commit 709a86a365
#3005: 'Map-dependent armor and gun sprite variants' by Rohesie at commit 942ded2a20
#2996: 'Ovi removal and abilities rework' by Rohesie at commit 5bd5864114
#2764: 'Round end after xenos defuse the nuke' by psykzz at commit 97499d0121
#3015: 'gives acid AMMO_EXPLOSIVE' by factoryman942 at commit 9153fe70f0
#3016: 'Buffs base marine glove melee protection.' by Pariah919 at commit f267f8023b
#3023: 'Ripple test' by Rohesie at commit 5a0444ab85
#3018: 'Changes the shrike's abilities' by Spyroshark at commit 61beaed6db
#3024: 'Resin silos.' by Rohesie at commit 291a0846c7
#3021: 'Ravagers now gain rage on slashing humans; no more rage gained from taking damage' by ma44 at commit a704d26896
#3019: 'Bandannas and Goggles' by Metroidlover at commit e034aef375
#3028: 'Fix call down dropship on crash' by psykzz at commit 2c5620a6d6
HOW TO REPRODUCE
1.Plant an egg
2.Push a crate or some other covering thing over it like grabbing a body and putting it over an egg
3. Congratulations you now have a practically uncounterable better than resin hole trap because of the fact that nobody will probably expect this.

**Comment by Hughgent** [comment]
As per current master.
`Structures.layer = BELOW_OBJ_LAYER (2.98)`
`xeno_egg.layer = MOB_LAYER (4)`
This is above the `ABOVE_LYING_MOB_LAYER (3.9)`

I think this is closed.
