### ISSUE TITLE
If you throw a gun that has a mag harness, that gun can never be used to PB anything again

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/TerraGov-Marine-Corps#3036]
## Testmerges:

None tested locally from the current master
## Reproduction:

1. Mag harness a gun that can PB
2. Try to PB something to see it works
3. Now throw the gun and let it snap back to you
4. Now try to PB something
5. Realize that no matter what you try, that gun can no longer PB

**Comment by Rohesie** [comment]
Interesting bug, certainly related to gun flags.

**Comment by Hughgent** [comment]
Attempted to recreate. And was successful.

However, as I left the window open to code dive, the weapon in questions (a M37 Shotgun) was able to PB again after a short time.

**Comment by Rohesie** [comment]
Mag harness is old code. Could use a refactor.

**Comment by psykzz** [comment]
I checked this locally with latest master and can suicide (which checks pointblank code).
Is there another way i can repro?

https://streamable.com/egs8o

**Comment by Hughgent** [comment]
@psykzz 
My attempts at the time were to spawn a xeno, then PB it with a shotgun.

**Comment by psykzz** [comment]
Tested this again today and can't repro.

**Comment by MacBlaze1** [comment]
this should be closed because it is unreproducible
