### ISSUE TITLE
crusher stops charging at windoors

### ISSUE THREAD

**Issue by Fikou** [tgstation/TerraGov-Marine-Corps#3039]
## Reproduction:

1. be crusher
2. start charging
3. go to a windoor
4. stop charging to open it instead of crushing it

this combined with #3035 makes windoors hilarious against xenos

**Comment by Rohesie** [comment]
The Crusher charge deals between 60 and 168 damage to `ON_BORDER` objects it meets.
If it fails to destroy them, it stops and bumps them.
Windoors have 150 health.
When bumped, they open.

The mechanics are working fine, the issue here is how much damage is being dealt to this piece of machinery.

**Comment by Rohesie** [comment]
Not a bug.
