### ISSUE TITLE
Survivor spawn on LV broken

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#3040]
## Reproduction:

Try to spawn as a survivor on LV in medical, you will be stuck there since there is no power to pen the shutters, it should look something like this https://gyazo.com/8bce314c0e080b04390477c303756929

**Comment by Pariah919** [comment]
can't you just crowbar out?

**Comment by Henriquekill9576-taken** [comment]
> can't you just crowbar out?

no

**Comment by Rohesie** [comment]
Badly placed spawn.

**Comment by KwinOriginal** [comment]
Moved it and made a PR

**Comment by Rohesie** [comment]
Not sure I understand the question.
We have to open PRs to make code changes, and we need to do that to fix bugs.

**Comment by Rohesie** [comment]
Fixed by #3044
