### ISSUE TITLE
Ability to laze does not go away when binos are not equipped

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#3055]
## Testmerges:
#3033: 'Adds belt harnesses' by Spyroshark at commit 854f6761ae
#3031: 'B18 no longer let's you have hair sticking out' by Metroidlover at commit 8f5a279a72
#3021: 'Ravagers now gain rage on slashing humans; no more rage gained from taking damage' by ma44 at commit a704d26896
#3023: 'Shuttle ripple effect icon' by Rohesie at commit 5a0444ab85
#2764: 'Round end after xenos defuse the nuke' by psykzz at commit 97499d0121
#2996: 'Ovi removal and abilities rework' by Rohesie at commit fb51686366
#3022: 'New, harder to see, resin traps' by Metroidlover at commit 4c597ae8a8
#3046: 'Adds and changes Voice SFX' by Spyroshark at commit f8574cb7e2
#3049: 'fixes a bug with the box of 45 caliber mismatch' by Hughgent at commit 1419623976
#3018: 'Changes the shrike's abilities' by Spyroshark at commit eab5c07403
#3020: 'More armor and no more Squad markings on armor' by Metroidlover at commit d4ea97c2bb
#3048: 'HPR Rework' by Metroidlover at commit 7a93986d30
#3005: 'Map-dependent armor and gun sprite variants' by Rohesie at commit 942ded2a20

## Reproduction:

Be a human.
Equip Binos
Crtl-click to laze
Throw binos away
Laze again because you are superman

**Comment by Rohesie** [comment]
I can't reproduce this locally.
If I use binocs I can laze, but if I throw them away I can no longer.
What am I missing here?
