### ISSUE TITLE
SSD Larva + Broken Xeno Evo

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#3063]
SSD larvas don't auto reburrow and the Xeno evolution is broken, the animation of evolution is applied but successful evo does not, it matters little if there is a spot available or not.

**Comment by spookydonut** [comment]
what PRs?

**Comment by Urthrem** [comment]
It was during the first round of the test 2 days ago. I don't remember which PRs exactly but I think admin that was present then did fix it or at least found way to work around it. Sorry I do not remember the details.

**Comment by Rohesie** [comment]
Is this still happening?

**Comment by Rohesie** [comment]
Re-open the issue if it happens again.
