### ISSUE TITLE
Error Icon M39 Holster Rig with M39

### ISSUE THREAD

**Issue by DeadLineSS13** [tgstation/TerraGov-Marine-Corps#3066]
## Reproduction:

https://media.discordapp.net/attachments/500801682058379265/631208651444715520/scrnshot1.png

**Comment by Rohesie** [comment]
This is fixed, isn't it?

**Comment by DeadLineSS13** [comment]
I don’t know but belts have error image.

**Comment by Rohesie** [comment]
In latest master? All belts? Can you provide more info?

**Comment by Rohesie** [comment]
No answer, I assume it's fixed.

**Comment by factoryman942** [comment]
@Rohesie https://discordapp.com/channels/498569646014857217/500801682058379265/640600158983159820
