### ISSUE TITLE
Corrupted Xeno eggs spawn Regular hive Huggers

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/TerraGov-Marine-Corps#3068]
## Testmerges:

None responsible

## Reproduction:

1. Plant or otherwise come across a Corrupted Xenomorpth egg
2. Open the egg
3. Realize the hugger is not a corrupted one and the larva that bursts will go to the default hive.

**Comment by Urthrem** [comment]
Can confirm this as Shrike player that cooperated with Corrupted Shrike and shared hosts with. Every corrupted egg spawned normal hugger leading to all xenos being born as normal ones.
