### ISSUE TITLE
Imaginary Friend will give you a black screen if you try to use it without having had a body at any previous point

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/TerraGov-Marine-Corps#3069]
## Testmerges:
#3059: 'Defender Armor Rebalancing' by Tupinambis at commit dd450a9688
#3005: 'Map-dependent armor and gun sprite variants' by Rohesie at commit 942ded2a20
#3058: 'Increases the bonus to larva growth speed when a host is nested.' by Isy232 at commit 72f4f6beb3
#3021: 'Ravagers now gain rage on slashing humans; no more rage gained from taking damage' by ma44 at commit a704d26896
#3023: 'Shuttle ripple effect icon' by Rohesie at commit 5a0444ab85
#2764: 'Round end after xenos defuse the nuke' by psykzz at commit 97499d0121
#3022: 'New, harder to see, resin traps' by Metroidlover at commit 4c597ae8a8
#3046: 'Adds and changes Voice SFX' by Spyroshark at commit f8574cb7e2
#3018: 'Changes the shrike's abilities' by Spyroshark at commit eab5c07403
#3038: 'Burrowed larva and larva now count towards xenomorph evolution tier and queen calculation' by ma44 at commit 6a89e23ae0
#3061: 'Hyperzine rebalance mk2' by jroinc at commit c1f43baed4
#3048: 'HPR Rework' by Metroidlover at commit 7a93986d30
#3065: 'readds snowsuits to ice survivor spawns' by spookydonut at commit 464f467b2e
#3064: 'Stops resin sacs and resin holes being placed on the same turf' by spookydonut at commit 44bba4dcc0
#3047: 'm43 lens attachments' by Hughgent at commit d05c020b80
## Reproduction:

1. Observe
2. try to imaginary friend someone
3. Stare into the void
4. Cancel the imaginary friend and find your ghost properly equipped but somehow at the cryo pods

**Comment by Rohesie** [comment]
Between 2 and 3, were you given the option to select a target by ckey or mob?

**Comment by Metroidlover** [comment]
You are, after that you get black screened with the buttons in the top left and that's it

**Comment by Rohesie** [comment]
I couldn't replicate it locally.
Can you try replicating when you play again, and see if there are no more variables involved?
