### ISSUE TITLE
Canterbury south ship turret blocks south shutter button

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#3093]
Unmovable turret blocks the button allowing xenos to melt a single shutter and abuse the turret mechanics, slowly tearing away defences.

**Comment by Rohesie** [comment]
Is this related to #3072 ?

**Comment by Urthrem** [comment]
I think so? New turret placement blocks current placement of the button that cannot be accessed giving the xenos ability to abuse the idea of destroying a single shutter to break through south of the ship.

**Comment by Rohesie** [comment]
Fixed by #3072
