### ISSUE TITLE
[BYOND 513] Runtimes and errors.

### ISSUE THREAD

**Issue by DeadLineSS13** [tgstation/TerraGov-Marine-Corps#3112]
## Errors
Clamp proc and arctang.
## Runtimes
Plane.
Charset (https://github.com/tgstation/TerraGov-Marine-Corps/blob/6dbc29b80c8123a008039d41b0f31386804e5767/code/datums/browser.dm#L76 , https://github.com/tgstation/TerraGov-Marine-Corps/blob/6dbc29b80c8123a008039d41b0f31386804e5767/code/modules/nano/nanoui.dm#L375)
P.S. List will update at least detecting errors. I will give debug log when I have time.

**Comment by spookydonut** [comment]
513 isnt supported and this report is obsolete
