### ISSUE TITLE
Examining a xeno that's upgraded naturally have their codex not updated

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#3117]
## Testmerges:
#3076 #3058 #3088 #3100 #3096 #3111 #3110 #3109 #3105 #3029

## Reproduction:
Go from larva to any caste
Wait until maturity
Examine self, open up codex
See codex showing you stats for a young [caste] instead of say matured [caste]

**Comment by Hughgent** [comment]
Limitation of the codex.

Once a client uses the codex on a thing, especially if it is a generated codex, the codex entry is stuck.

Another client observing the same thing, but at a later point, will get an updated codex entry.
