### ISSUE TITLE
B18 helmet gets yeeted into oblivion when you explode

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#3121]
## Reproduction:

1. Place a B18 helmet on your head
2. Explode yourself (preferably with SADAR)
3. Watch as it dissapears

**Comment by Hughgent** [comment]
Helmets only have standard `obj/ex_act()`

Cannot reproduce otherwise.

**Comment by Rohesie** [comment]
It requires total devastation range.
