### ISSUE TITLE
No buttons

### ISSUE THREAD

**Issue by Max-023** [tgstation/TerraGov-Marine-Corps#3130]
## Testmerges:
The Pillar PR

## Reproduction:
Spawn as any command role or the CL late and then cry because both CiC and the NT office are locked with no way in.

Additionally, add lock buttons to the Alamo on the outside that pilots and officers can access. Being locked out without any way in is problematic.

**Comment by Rohesie** [comment]
Comment about issues related to the Pillar of Spring in its PR, please:
https://github.com/tgstation/TerraGov-Marine-Corps/pull/3043
