### ISSUE TITLE
Span Classes are showing up where they shouldn't.

### ISSUE THREAD

**Issue by francinum** [tgstation/TerraGov-Marine-Corps#315]
code/modules/admin/verbs/randomverbs.dm#L574
`command_announcement.Announce("<span class='warning'> New update available at all communication consoles.</span>", customname, new_sound = 'sound/AI/commandreport.ogg')`
Announce does not support HTML, It was changed from /red in PR #296

**Comment by DominikPanic** [comment]
@spookydonut

**Comment by spookydonut** [comment]
goonchat ignores \red so i dont know what the answer is here

**Comment by francinum** [comment]
It shouldn't matter, I have no idea why it had that to begin with, Announce() has it's own span class set internally.

**Comment by DominikPanic** [comment]
Anyway I fixed it with my admin rework PR (no span anymore)
