### ISSUE TITLE
Survivors when ghosting get randomized names instead of the one they played with.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#3151]
## Testmerges:

Whatever was tmed last test.

## Reproduction:

1. Spawn as survivor
2. Die or something.
3. Ghost.

You should get a new name when you ghost and type in d-chat instead of the actual name you started with.

**Comment by Hughgent** [comment]
Is this a feature request?

Normal behavior is to keep whatever name you had when alive in D-Chat.

This is why you often get several queens in D-Chat on the Xeno side.

**Comment by spookydonut** [comment]
This isn't for feature requests

**Comment by Rohesie** [comment]
This is not a feature request, it's a bug.
When a survivor ghosts, the name of the ghost is not the one of the survivor. Issues with mind code.

**Comment by psykzz** [comment]
Reported as no longer happening
https://discordapp.com/channels/498569646014857217/500801682058379265/713789738187882578
