### ISSUE TITLE
Pillar of Spring Escape Shuttle

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/TerraGov-Marine-Corps#3166]
In a recent round, after attempting to use the escape shuttle with two humans onboard, it exploded.

## Reproduction:

1. Enable evacuation, attempt to use the Pillar of Spring's escape shuttle.
2. Blow up.

**Comment by Rohesie** [comment]
We shouldn't have bought those in that bulk discount...

**Comment by spookydonut** [comment]
Mapper goofed making escape shuttle subtype
