### ISSUE TITLE
Multitools are broken

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/TerraGov-Marine-Corps#3168]
Attempting to pulse a wire in vending machines will print the 'You need a multitool!' message.

## Testmerges:

#3142 #3158 #3162 #3163 #3164 #3133 #3159 #3152 #3149 #3147 #3148 #3136 #3157 #3120 #3088

## Reproduction:

Attempt to pulse a wire in a vending machine.

**Comment by spookydonut** [comment]
multitools didnt have `tool_behaviour = TOOL_MULTITOOL`
