### ISSUE TITLE
Ancient Defender lunge not working

### ISSUE THREAD

**Issue by Ciket** [tgstation/TerraGov-Marine-Corps#3182]
## Reproduction:
Become an Ancient Defender in any circumstance. You can select lunge, but you cannot use it.

**Comment by Fikou** [comment]
you need to target a marine to use it

**Comment by Ciket** [comment]
Nope, doesn't work

**Comment by Ciket** [comment]
Odd, last time I tried it didn't work. Well this was a waste.
