### ISSUE TITLE
Ventcrawling while rested softlocks you

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3239]
You can neither move nor get out of the vent, requiring admin intervention.

**Comment by Rohesie** [comment]
How did you enter the vent while resting?

**Comment by terranaut1** [comment]
I was on top of it, rested and alt-clicked it, deciding I'd rather ventcrawl than sit there. I do not remember if I started the ventcrawling in the delay between where you click on the rest action button and you actually start resting or if it was after but that's easily tested.

**Comment by GravitronBlue** [comment]
I've done this before, and I recall escaping the softlock using I think the rest from the IC menu to stand up again, allowing normal ventcrawl movement.
