### ISSUE TITLE
Pillar of Spring APC issues

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/TerraGov-Marine-Corps#3240]
In a recent round, seconds before the dropship crashed, I deconned the APC in the requisition office with the intent to rebuild right after. However, I kept getting the message 'this area already has an APC.' when I tried to place the new APC frame on the same wall.

## Testmerges:

#3120 #3236 #3200 #3232 #3217 #3237

## Reproduction:

Take down the requisition's office APC.
Attempt to place a APC frame.

**Comment by spookydonut** [comment]
lol metagaming?
