### ISSUE TITLE
Detector blips inaccurate when using M4RA scope

### ISSUE THREAD

**Issue by CoreFlare** [tgstation/TerraGov-Marine-Corps#3258]
## Testmerges:

None.

## Explanation:

Motion detector blips show up inaccurately when using the M4RA scope. Unknown if it has the same effect on other scopes, will update with relevant information after sufficient testing.

## Reproduction:

Step 1: Pick the Scout set from the Spec vendor. All you need is the M4RA, ammo, and a motion detector. For my test, I used the scout detector, in my helmet.

Step 2: Set it to blip on Short Range mode. Unknown if this works on further ranges, since I'm reporting this the moment I found it.

Step 3: Wield the M4RA and use the scope function. If there is something in the vicinity that'll send off a blip, the visual aid (A green, red, cyan or blue circle) will not be on the target.

**Comment by CoreFlare** [comment]
Update: Only for the M4RA scope. Unsure if it works on other scopes of the same type.

**Comment by David-Stormwell** [comment]
Pretty sure it's for anything in which you zoom out of such as binoculars or scopes.

**Comment by CoreFlare** [comment]
No, for things like the M42A scope, rail scope and binoculars, the detector blips are accurate. It's only for the M4RA scope, and might be true for mini-rail scopes as well.

**Comment by jroinc** [comment]
Seems like more of a feature than a bug, honestly.

How are you reading the motion-detector when sighted-in on the rifle?

**Comment by Hughgent** [comment]
Not a bug, intended feature. Here is the code from the motion detector item.
```
		var/c_view = user.client.view
		var/view_x_offset = 0
		var/view_y_offset = 0
		if(c_view > 7)
			if(user.client.pixel_x >= 0) view_x_offset = round(user.client.pixel_x/32)
			else view_x_offset = CEILING(user.client.pixel_x/32, 1)
			if(user.client.pixel_y >= 0) view_y_offset = round(user.client.pixel_y/32)
			else view_y_offset = CEILING(user.client.pixel_y/32, 1)
```

a scopes zoom changes the user.client.view. As it increases past 7 the motion detector gets more and more inaccurate. 

If you can provide some screenshots of this in action only happening for the m4ra, and not happening for any other zoom based item, that would be greatly appreciated. Video would be even better.

**Comment by CoreFlare** [comment]
Ah, here we go. Finally got some proof of it happening. This is on the M4RA.
https://i.imgur.com/fK8HnaF.png
If this is intended, god help me.

**Comment by CoreFlare** [comment]
For clarification, the green circles are horribly offset. I made a diagram showing the dislocation, if it helps.
https://i.imgur.com/wvJRCFZ.png

**Comment by Hughgent** [comment]
oh yeah that makes a bit more sense.

This is because your view points is pushed forward when you scope in. As such the blips are shown on top of what you see based on where your mob is. If you were at your normal point of view, everything would line up. But now you're 'offset' by seven tiles or whatever the scope zoom amount is.
