### ISSUE TITLE
Xeno Abilities do not work at all if you have an egg in your hand

### ISSUE THREAD

**Issue by BurgerLUA** [tgstation/TerraGov-Marine-Corps#3265]
# Reproduction:

1. Be Shrike.
2. Nopop so you're literally the only shrike.
3. Try to fight 2 marines, both with shotguns.
4. Misclick a dropped egg.
3. Have egg in your hand.
4. Try middle mouse clicking.
5. Literally nothing works.
6. Low HP because you're being assaulted by shotguns expecting your unrelenting force for throw abilities to work.
7. Drop egg.
8. Abilities now work.
9. Doesn't matter because you're dead now.

**Comment by Rohesie** [comment]
I'm not entirely sure this is unintended.
