### ISSUE TITLE
Making weeds on weed tiles deletes them

### ISSUE THREAD

**Issue by Arturlang** [tgstation/TerraGov-Marine-Corps#3269]
## Testmerges:
#3260: 'Resin Traps, Goo, and Eggs are destroyed if the resin tile below them is also destroyed.' by BurgerLUA at commit 20710b3ec4
#3262: 'Minigun Buff' by BurgerLUA at commit 7aeab38eb8
#3245: 'Xeno firefighters' by Rohesie at commit 0be11913ce
#3243: 'Respawn and no repeated names' by Rohesie at commit 93e434ba3d
#3103: 'Stamina' by Rohesie at commit 70d7fe1af0
#3246: 'Fixes ventcrawling when resting' by Rohesie at commit 91c89758af
#3248: 'HUD fix' by Rohesie at commit 21b89c47e0
#3251: 'Reworks the Canterbury Cream Egg Shuttle' by BurgerLUA at commit 8ea24bea9b
#3266: 'Shuttle fixes' by Rohesie at commit d38454e528
#3259: 'Gives AK47 burst to carbine' by Aurelien3189 at commit 6405dd8e92

**Comment by Arturlang** [comment]
Seems to possibly only happen as shrike?

**Comment by BurgerLUA** [comment]
The bug is caused when you place a node over already existing resin. Since the resin gets deleted, so does the node.
