### ISSUE TITLE
Stun abilities and explosions go threw containment shutters. And you can melt/crush items under them.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#3319]
## Testmerges:

The following pull requests are currently test merged:
#3256: '(Re)Adds a new shotgun scout specialization role.' by BurgerLUA at commit 7bc58dc0d2
#3308: 'Removes hit and run from runner' by Kuro-ai at commit a2a28eec83
#3299: 'Lowers runners speed by 0.1.' by Isy232 at commit 3928b46e15
#3295: 'Nerfs permastun memes' by Kuro-ai at commit 87d3244755
#3282: 'AFK, Respawn and Game tab tweaks' by Rohesie at commit 0f8d8af061
#3284: 'Minor APC cleanup' by Rohesie at commit 53d2fff134
#3300: 'Crash coefficient' by Rohesie at commit c6b87f066d
#3298: 'Warrior Agility Damage Nerf And A New Var' by Isy232 at commit 9f0981104a
#3307: 'Supply shuttle runtime fixes' by Rohesie at commit fd694947d7
#3302: 'Move delay from wearing B18 armor increased from +100% to +115%' by BurgerLUA at commit ec52df60ed
#3313: 'Xeno action runtime fix' by Rohesie at commit 2bcc701d2c
#3312: 'Fire bugfix' by Rohesie at commit 6dc26865f9
#3311: 'Fixes bad signals' by Rohesie at commit 0984e6b866
#3310: 'Fixes xenos not on the main ground being deleted on hijacks' by Rohesie at commit afc3731fc0
#3314: 'Louder DropShip Takeoff Sound' by Isy232 at commit 4005486c73
#3315: 'Headset camera runtime fix' by Rohesie at commit bdd145e5fc
## Reproduction:
FOR STUNNING.
1.Select your ranged indirect stun that doesn't require clicking and LoS like fling.
2. Use it.
3. If your AoE is far enough you can stun marines threw the walls.

FOR MELTING
1. Select melting ability.
2. Alt+Click
3. Melt the wall.

FOR CRUSHING
1. Get crusher.
2. Charge to wall.
3. It'll hit the wall.

Explosions go threw as well. Get a fuel tank and spit threw it.

**Comment by jroinc** [comment]
Everything seems reasonable there except the explosions. Both sides can interact with shit on the shutter.

The shrike fling's the only iffy one and it's not THAT big of a deal, but if you have an idea to fix it...

**Comment by Isy232** [comment]
Crusher stomp stuns people making cades on the other side.

**Comment by Fikou** [comment]
same thing applies to fog, you can hit xenos/resin silos that are under a fog tile to destroy them

**Comment by spookydonut** [comment]
Working as intended, repo steps dont produce any unintended behaviour
