### ISSUE TITLE
Hunters can have an insane multiplier, above what is the "maximum"

### ISSUE THREAD

**Issue by Toxici11i** [tgstation/TerraGov-Marine-Corps#3328]
## Reproduction:
http://prntscr.com/pvleya

This somehow occurs when stealthing, going into vents, unstealthing, pouncing at other xenos, unsure how exactly it occurs, but it happened while fucking about

**Comment by Toxici11i** [comment]
also, small value. I reached 3.75x before

**Comment by Rohesie** [comment]
Hunter sneak attack bonus needs to be removed.

**Comment by Toxici11i** [comment]
you can abuse this bug to get a 3x multiplier, and instantly kill marines if you aim for head

**Comment by Hathkar** [comment]
This can probably be closed, since hunters don't have a a multiplier anymore.
