### ISSUE TITLE
AI can see the entire battlefield without static.

### ISSUE THREAD

**Issue by BurgerLUA** [tgstation/TerraGov-Marine-Corps#3344]
Yeah I thought this was a feature at first but when I started seeing inside interiors, I started to get suspicious. Basically if I fuck around with multicam hard enough, switching between z-levels and whatnot, I can sometimes managed to remove the static, which allows me to see anywhere on the map where there is light.

![image](https://user-images.githubusercontent.com/8602857/68735984-450d0000-0594-11ea-9451-40c4340d183e.png)
![image](https://user-images.githubusercontent.com/8602857/68735988-46d6c380-0594-11ea-8681-653f639dd904.png)
![image](https://user-images.githubusercontent.com/8602857/68735990-48a08700-0594-11ea-94c2-44087c20bda2.png)

**Comment by BurgerLUA** [comment]
Honestly make this into a feature cause AI is pretty useless on missions.

**Comment by ArcaneCarrot** [comment]
Spy sat time boys

**Comment by Rohesie** [comment]
Needs steps to reproduce.

**Comment by BurgerLUA** [comment]
> Needs steps to reproduce.

It's unreliable but it can occur.

1. Set a multicamera on the main ship's z-level.
2. Set a multicamera on the surface z-level.
3. Repeatedly go back and forth between the two.
4. ????
5. Profit.

Step 4 might involve one of the camera's position being in a dropship area. I notice that sometimes it resets when a dropship takes off.

**Comment by terranaut1** [comment]
I play a fuckton of AI on /tg/ and that bug exists there too. I don't know what causes it but it sometimes happens when you jump around/refresh ie. when switching to a cam directly, tracking or changing z-level instead of just moving the camera eye around. It goes away after a while too, again not sure what causes it.
