### ISSUE TITLE
Mesons and Overwatch

### ISSUE THREAD

**Issue by ghost** [tgstation/TerraGov-Marine-Corps#3345]
While wearing mesons and using the Overwatch cameras, it's possible to get rid of the static and darkness, and be able to see the entire map.

## Reproduction:

1. Wear Optical Meson Scanners.
2. Start watching a marine's cam, you might need to try multiple times to get rid of the overlays.

**Comment by Hughgent** [comment]
Cannot Reproduce in it's entirety.

Camera says. `update_remote_sight()` user.sight = SEE_SELF|SEE_MOBS|SEE_OBJS|SEE_TURFS|SEE_BLACKNESS

Mesons say. vision_flags = SEE_TURFS|SEE_OBJS

As such, wearing mesons and using the camera allows the person using the camera to not see darkness, but the static is still there from things outside of camera range.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
