### ISSUE TITLE
ID Computer produces infinite(?) passenger cards when used

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/TerraGov-Marine-Corps#3346]
Attempting to use the ID console after inserting an ID will just produce a seemingly unlimited amount of nameless passenger cards when used. It doesn't bring up the UI, it'll just place the new ID inhand, with the only way to get the original ID out via the eject ID verb.

## Reproduction:

1. Insert a ID capable of modding access into the console.
2. Put another ID card in the console.
3. Use the console, check hand.

**Comment by Rohesie** [comment]
That is intended. The ID card console is made for survivors to get cards. There is no other functionality currently.
