### ISSUE TITLE
SMEs dont have the option to max the output/input

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#3351]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 1857
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 8e4526c919728b154f6fc17037ef36d3a279ee63
The following pull requests are currently test merged:
#3338: 'Changes DMR a bit' by Kuro-ai at commit 71dc59d781
#3309: 'Unga juice nerf and chem additions' by jroinc at commit 5f2480cbac
#3336: 'Makes the Biogenerator just a prop item' by psykzz at commit 8d4fb48e4e
#3327: 'Keybind tweaks' by Rohesie at commit c94987b37d
#3301: 'Spitting anything (acid spit, slowdown spit, boiler spit) as a Xeno slows you down for a short time.' by BurgerLUA at commit 4f2d7d6a06
#3331: 'Shotgun spread tweaks' by Rohesie at commit 79e232ada1
#3322: 'Larval toxin changes' by jroinc at commit 8fcbd4ccd7
#3282: 'AFK, Respawn and Game tab tweaks' by Rohesie at commit 0f8d8af061
#3317: 'Powerpack reload fix' by Rohesie at commit 94ea9ae133
#3335: 'Fixes Carrier being able to drop 10 huggers in a group of marines in about a second' by terranaut1 at commit 3b1f915c04
#3342: 'Nerfs Meme guns' by Pariah919 at commit 7e64608173
#3343: 'Legacy chat support re-enabled' by Rohesie at commit cf2744d5e1
#3347: 'Xeno ERT fix' by Rohesie at commit 30bf90503c
#3340: 'fixes m39 belt sprite issue' by Hughgent at commit 626d05cd4f
#3339: 'Multi Carrier trap fix' by Hughgent at commit 799ae42b7f

Local commit: 66d957d697c5da388b154475e0913890a0714b3a
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. Go over to any SME and try to change the output or input

**Comment by Rohesie** [comment]
This looks like an unfinished port.
Is that the case, @spookydonut , or is it a bug?

**Comment by Hughgent** [comment]
On the Theseus, the main upper deck SMES. There isn't a button to adjust the input and output.

There are buttons for charge mode and output mode, being Auto/Off and On/Off respectively.

**Comment by spookydonut** [comment]
no screenshot = no fix

**Comment by Henriquekill9576-taken** [comment]
@spookydonut https://gyazo.com/2b16967160c908da3705d368c3827c99

**Comment by spookydonut** [comment]
icons arent loading, theres meant to be buttons
