### ISSUE TITLE
PMC Lead's M4A1 BR bug

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#3361]
Title, can't load new AP magazines you are given as a PMC Lead.

## Testmerges:

#3359 #3358 #3347 #3343 #3342 #3335 #3282 #3322 #3331 #3327 #3354 #3352 #3350 #3305 #3353 #3357

## Reproduction:

Go PMC lead, take out magazine, try to put in a new one from your magazine pouch, haven't explored with other magazines yet.

**Comment by Rohesie** [comment]
Looks like a consequence of the gun repathing.

**Comment by Hughgent** [comment]
Cannot reproduce on current master with the PMC spawned magazines. The ones in their ammo pouch.

however, I do see that this PMC pulse rifle will only take their AP magazine, the old style. As such they will have 'supply' issues with TGMC based weaponry.
