### ISSUE TITLE
Autodoc yeets people into oblivion when destroyed

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#3368]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 1894
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 6215a912803ea6de76a8c14fd9ec657dab2c6d25
The following pull requests are currently test merged:
#3365: 'Headless reviving fix' by Rohesie at commit d272c34f2b
#3309: 'Unga juice nerf and chem additions' by jroinc at commit 8a004ee9ad
#3359: 'Feedback fixes' by Rohesie at commit 9f7f293c81
#3358: 'New attack animations' by Rohesie at commit 830a069366
#3347: 'Xeno ERT fix' by Rohesie at commit 30bf90503c
#3343: 'Legacy chat support re-enabled' by Rohesie at commit cf2744d5e1
#3335: 'Fixes Carrier being able to drop 10 huggers in a group of marines in about a second' by terranaut1 at commit 2ddd76d46c
#3282: 'AFK, Respawn and Game tab tweaks' by Rohesie at commit 35dbc16c2d
#3331: 'Shotgun spread tweaks' by Rohesie at commit 79e232ada1
#3327: 'Keybind tweaks' by Rohesie at commit 5eef94e7f7
#3350: 'Better disk spawns' by BurgerLUA at commit 3310fff6f2
#3305: 'Converts marine gloves to greyscale' by Mark9013100 at commit e31450e24c
#3357: 'Adds a New Map: Desert Outpost AKA "Dessert"' by BurgerLUA at commit 2dfd3028d7
#3363: 'm81 grenade launcher fix' by terranaut1 at commit 2a7537e0cb

Local commit: 00f2f76880168279a1d7509d6f587f3304fbbc8a
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. Get inside an autodoc
2. Get it destroyed by either making a crusher ram on it, acid it and etc
3. Watch as your character goes to the shadow wealm

**Comment by Rohesie** [comment]
Seems pretty realistic to me.

**Comment by terranaut1** [comment]
A locker being acided supposedly ejects the mob rather than deleting it. Should we aim for consistency, whichever way, here?

**Comment by Henriquekill9576-taken** [comment]
A locker ejects mobs just fine, the autodoc doesn't

**Comment by Hughgent** [comment]
the Autodoc is not a locker.

**Comment by Rohesie** [comment]
Yea, I was kidding. It should eject the mob, maybe do some damage, but not delete it.
