### ISSUE TITLE
Mag Harness Just Sometimes Doesn't Work

### ISSUE THREAD

**Issue by BurgerLUA** [tgstation/TerraGov-Marine-Corps#3376]
## Testmerges:

#3366 #3367 #3365 #3358 #3335 #3331 #3327 #3350 #3305 #3357 #3363 #3370 #3372 #3371 #3375 #3374

## Reproduction:

Given this server's excellent decision to make xeno combat stun based combat, I experienced some sort of glitch with the mag harness. Me and the boys were up against several xenos who were literally stunlocking us and throwing us around (HUNTER, RUNNER, SHRIKE, RAVAGER) and I lost my mag-harness gun in the mix despite the mag harness being a mag harness.

**Comment by Rohesie** [comment]
Do ask an admin to check the runtimes if this happens again. As it this, this is a pretty vague report without a reliable reproduction method.

**Comment by BurgerLUA** [comment]
> Do ask an admin to check the runtimes if this happens again. As it this, this is a pretty vague report without a reliable reproduction method.

I've seen the mag harness in action and for a single tick it appears on the ground. I suspect that it is this way so you can throw the weapon, and I bet you, without even looking at the code, that it uses a timer or spawn or something to check if the user is on the same tile in the next frame.

**Comment by terranaut1** [comment]
You'd be wrong because throwing the weapon away just puts it back in your storage anyway (which I consider poor interaction but that's another problem).

**Comment by spookydonut** [comment]
No repro steps included.
