### ISSUE TITLE
SERIOUS IMBALANCE with re-nesting Deifler abulity "Defile"

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#338]
It was a 3+ year ago problem
When aliens re-nest marines then use Defile ability, then put infected marines back to nest.
MAKING "Ashamed, you reconsider bullying the poor, nested host with your stinger." USELESS

Must have to remove a way to defile nested hosts.

**Comment by Monikawales** [comment]
Also Defile ability works on dead marines and synths

**Comment by Monikawales** [comment]
Major problem to understand how ability "neurotoxic" works.
Should have a better description 
example
"Defiler injects neuro on claw or tackle/throttle. Neuro causes pain and slowly stuns"

**Comment by Ghommie** [comment]
Guidelines for bug reports have been introduced days ago to make things easier, you should follow them even if you partly lack english knowledge. Also #283

**Comment by DominikPanic** [comment]
You should either use #balance on our Discord or the official forums, github is for bug reports only.
