### ISSUE TITLE
Pillar of Spring Hanger podlocks are meltable 

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#3382]
## Reproduction:

![Xenos can melt podlocks to space](https://user-images.githubusercontent.com/47805468/68988592-b0eaa500-07ee-11ea-85d8-f4b30a960d25.PNG)

As it says in the title, hanger podlocks are meltable which allows xenos access to space.

**Comment by TiviPlus** [comment]
Crushers can also destroy these shutters.

Crusher should not can into spess

**Comment by terranaut1** [comment]
Is there a reason there's no rwalls/hull under those shutters like around the LZs? I understand that realistically the hangar needs to be openable to space for a hangar to serve its purpose but we don't need it here.

**Comment by Rohesie** [comment]
The shutters should have the indestructible and unacidable flags.
