### ISSUE TITLE
Different shuttles can target the same designation

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3393]
In a round just now a regularly called ERT, during the alien hijack of Alamo, crashed into the Alamo after it landed on the Pillar at Hangar 2, gibbing some aliens.

## Testmerges:

#3380 #3379 #3377 #3366 #3367 #3335 #3327 #3350 #3305 #3357 #3387 #3386 #3294

## Reproduction:

Hijack Alamo
Call ERT
Send ERT to same place
Shenanigans

Suggested fix: Seperate the landing zones or have a check to see if a shuttle is already en-route or parked there and then disable that LZ
I'm not sure if I have time and the skill to do it myself.

We can of course just accept this as feature as it's unlikely to happen often, is kinda comical and not unrealistic but I thought I'd bring it up.

**Comment by Rohesie** [comment]
There should be a check already. This is an implementation bug.

**Comment by spookydonut** [comment]
> 
> 
> There should be a check already. This is an implementation bug.

This is a mapping error where docking ports are overlapping

**Comment by spookydonut** [comment]
No screenshot = no fix
