### ISSUE TITLE
Weird bug causing ghosts things to break.

### ISSUE THREAD

**Issue by Isy232** [tgstation/TerraGov-Marine-Corps#3395]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 1966
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 903a449f2ea09efd9836b934e2d58368a168718b
The following pull requests are currently test merged:
#3380: 'Rocket Buff, I guess' by InterroLouis at commit 3412260fc9
#3379: 'Nerfs queen speed' by Kuro-ai at commit 6d7376c5ca
#3377: 'Removed intentional "cooldowns" for interacting with storage and items' by BurgerLUA at commit 509946a52a
#3366: 'Properly Buffs/Nerfs the LMG' by BurgerLUA at commit 81e7bcb63b
#3367: 'Adds the T-18 and T-12 for PFCs' by Kuro-ai at commit bbcf03960b
#3335: 'Fixes Carrier being able to drop 10 huggers in a group of marines in about a second' by terranaut1 at commit 1b10563272
#3327: 'Keybind tweaks' by Rohesie at commit f862acf95f
#3350: 'Better disk spawns' by BurgerLUA at commit 3310fff6f2
#3305: 'Converts marine gloves to greyscale' by Mark9013100 at commit c5d0d4e15e
#3357: 'Adds a New Map: Desert Outpost AKA "Dessert"' by BurgerLUA at commit dac9beeba1
#3387: 'Adds B17' by Kuro-ai at commit ab548db548
#3386: 'destroyed machinery now dumps its contents on its turf' by terranaut1 at commit c8ab9506df
#3294: 'Prison variants and SG/SL resprites' by Kuro-ai at commit e9502baf2d

Local commit: e545382f8b14ea7dbc9b078dd60ee69e52287716
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

To be honest, I have no idea. Too much was going on at the moment and everything just suddenly broke. Perhaps by showing you what broke you can figure it out.

What broke:
- Some sprites turned into 2x2 black boxes, I think it was the queens, some glass shards were on it.
- My sprite is constantly falling and is also layering behind other things.
- Deadchat isnt working, OOC is however
- Reconnecting is not fixing the issue
- Ghost tab is gone
- None of the ghost abilities on the HUD work.
- Unable to examine things through right click or shift click.
- Multiple people are reporting having this issue.
- Clicking on the little follow things in the chatbox when dead is working however.

![](https://cdn.discordapp.com/attachments/500801682058379265/645703436830244928/unknown.png)

**Comment by Rohesie** [comment]
This sounds a lot like badmins breaking the game.
Let's see if it happens again without intervention.
