### ISSUE TITLE
M39B2 Submachine cannot be loaded.

### ISSUE THREAD

**Issue by Eonoc** [tgstation/TerraGov-Marine-Corps#3418]
The M39B2 submachinegun accepts no types of M39 ammo, not even the one that was just taken out of the gun. 
David mentioned the PMC battle rifle is the same.

### **Locating stuff:**
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 2016
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 5b7dbb68690451d9f2454d0b3d1d8bd173ec4b3b
The following pull requests are currently test merged:
#3415: 'Dripping component processes instead of timer-loops' by Rohesie at commit de7f0e2dda
#3413: 'Grenade launcher and similar shoot through MMB instead of ctrl+click' by Rohesie at commit acc4f48fa3
#3404: 'moves 2 crash/ert shuttle locations on the pillar' by terranaut1 at commit b85fd1a9f1
#3405: 'Fix powerpacks not using their sprite' by Kuro-ai at commit 3c392084b6
#3406: 'small bugfixes' by terranaut1 at commit 9c620151b2
#3386: 'destroyed machinery now dumps its contents on its turf' by terranaut1 at commit c8ab9506df
#3327: 'Keybind tweaks' by Rohesie at commit bce0a21d51
#3335: 'Fixes Carrier being able to drop 10 huggers in a group of marines in about a second' by terranaut1 at commit 1b10563272
#3399: 'Xeno armor/health rebalance' by Kuro-ai at commit 691ac35b64
#3409: 'Pillar Of Spring Poddoor Change/Fix' by Hughgent at commit 28fce27e72
#3407: 'Fixes invisible prison pyro helmet' by Kuro-ai at commit 98e91a05b2
#3414: 'More darkmode tweaks' by Rohesie at commit 3d91879127

Local commit: eb64aa65a2bbc1133170821bbbb7cab946efb9d9
Server tools version: /tg/station 13 Server v3.2.6.2

### **Reproduction:**
Get M39B2. Unload it. Try to reload it with that same mag. Doesn't work. Try reloading it with every other type of mag. Doesn't work.

**Comment by Hughgent** [comment]
#3408 should fix this for the SMG.
