### ISSUE TITLE
Spatial Agent has no night-vision.

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#343]
It can't help in places without light.
Instead of giving it NVG, giving the mob night vision might be better.

**Comment by Ghommie** [comment]
Or simply give them x-ray vision. I'm unsure about the intrinsic night vision option as it could be hacky without some refactor, be it already coded or not.

**Comment by DominikPanic** [comment]
No glasses can do that as it's a mob variable.

**Comment by Rohesie** [comment]
The verb is currently gone, right?

**Comment by DominikPanic** [comment]
Yes the admin verb associated is currently gone.
