### ISSUE TITLE
Chem Nade bug

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#3431]
## Testmerges:
 #3428 #3290 #3426 #3427 #3424 #3416 #3415 #3413 #3386 #3414 #3279 #3423 #3420 #3429 #3430

## Reproduction: 
Try to put a beaker inside of a grenade casing, doesn't work.
Asked in Discord, Hugh said it might have to do with breakers being repathed.

**Comment by jroinc** [comment]
I'll take a look at it soon.

**Comment by Hughgent** [comment]
David didn't put wires on his chem nades.

**Comment by jroinc** [comment]
Issue lies between monitor and chair.

oof

~~need some kelotane for that burn?~~
