### ISSUE TITLE
UGL bug

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#3432]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 2067
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: a39204e923ea3dfdd82a19a50bd7913440bc8699
The following pull requests are currently test merged:
#3428: 'Xeno rulers can only crack open the dropship doors if they are inside of it, or if they are all closed' by Rohesie at commit 9c31b0241a
#3290: 'Rambo Survivors' by Isy232 at commit ffe60dc651
#3426: 'Text fixes on being shot fixes' by Rohesie at commit 043b19dcb3
#3427: 'Human armor fixes against item attacks' by Rohesie at commit 097146fa30
#3424: 'Plasmacutter and light tweaks and bug fixes' by Rohesie at commit 4b5e30413d
#3416: 'Shrike slowdown' by Rohesie at commit 1745654e92
#3415: 'Dripping component processes instead of timer-loops' by Rohesie at commit 1a6d5d4eee
#3414: 'More darkmode tweaks' by Rohesie at commit 3d91879127
#3279: 'Adds a Specialist Melee Class + Acid Tweaks' by BurgerLUA at commit 0717a4d7b0
#3423: 'Game mode tweaks' by Rohesie at commit 1cdc37dc1f
#3429: 'Removes the broken Defender Lunge' by Rohesie at commit 02947833b2
#3430: 'Fire and Snow interactions' by psykzz at commit 08ebbe0a68
#3413: 'Grenade launcher and similar shoot through MMB or shift+click, instead of ctrl+click' by Rohesie at commit 8d0ffa1050

Local commit: a3a8a6defe7a67c01d6814c2e156edfc9055eff1
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Use a UGL with something like a lasgun or an AR, or the M4RA, then try it with a DMR.  You'll notice that the fire delay when you shoot them is faster on the faster guns and slower on the slower guns, so with things like the lasgun you can poop out 2 grenades almost instantly.

**Comment by David-Stormwell** [comment]
This can be used to the same effect with a masterkey, if you put a masterkey attachment on a carbine it will fire all 3 shots instead of just one buckshot shell

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
