### ISSUE TITLE
ERT (especially PMC) needs a armor passover

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#3433]
## Testmerges:
None

## Reproduction:
Spawn in as a ERT and notice how different the armor is compared to marines
Marine armor got changed in #3270 , PMC armor is definitely weird as say a PMC smartgunner can have 85 + 10% chest armor but less protection especially on gloves and boots due to the PR. Gonna need a passover over the values to the tune of the mentioned pr

**Comment by spookydonut** [comment]
Not a bug
