### ISSUE TITLE
Crusher unable to break a cade from behind by ramming

### ISSUE THREAD

**Issue by Henriquekill9576-taken** [tgstation/TerraGov-Marine-Corps#3443]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 2084
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 5fe80df799f7457fe990153979e05c595515c0bf
The following pull requests are currently test merged:
#3437: 'Makes Desert More "Mortar Friendly"' by BurgerLUA at commit 1ba75208ff
#3435: 'M240-T to use spec skill' by InterroLouis at commit 2861dfa4b9
#3428: 'Xeno rulers can only crack open the dropship doors if they are inside of it, or if they are all closed' by Rohesie at commit 9c31b0241a
#3290: 'Rambo Survivors' by Isy232 at commit ffe60dc651
#3416: 'Shrike slowdown' by Rohesie at commit 1745654e92
#3415: 'Dripping component processes instead of timer-loops' by Rohesie at commit 1a6d5d4eee
#3414: 'More darkmode tweaks' by Rohesie at commit 3d91879127
#3423: 'Game mode tweaks' by Rohesie at commit 1cdc37dc1f
#3429: 'Removes the broken Defender Lunge' by Rohesie at commit 02947833b2
#3430: 'Fire and Snow interactions' by psykzz at commit 08ebbe0a68
#3413: 'Grenade launcher and similar shoot through MMB or shift+click, instead of ctrl+click' by Rohesie at commit 8d0ffa1050
#3439: 'Removes sneak attack bonus damage from hunter' by BurgerLUA at commit 2aff2d60ea
#3391: 'clothing_tint component' by spookydonut at commit e72e7d9c5c

Local commit: 1b2b4a1f1c5a56acf2bc93ce0e7e41afb7001fc4
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. As crusher, charge into a barricade from behind
2. Watch as it does 0 damage to it

**Comment by BurgerLUA** [comment]
I've seen this happen with tables too.

**Comment by spookydonut** [comment]
ha okay I know why this is happening
