### ISSUE TITLE
Xenos can insta evolve without a shrike/queen

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#3446]
## Testmerges:
#3439 #3413 #3430 #3429 #3423 #3414 #3415 #3416 #3290 #3428 #3435 #3437 #3444 #3442 #3403

## Reproduction:
Have start of round with less than 8 xenos (seen in this scenario, could happen with above 8) seems to check for evolves after a queen/shrike is evolved so yikes

**Comment by psykzz** [comment]
Do you mean its not checking evolution requirements?
