### ISSUE TITLE
You can over fill shotgun ammo belts (and possibly other belts/containers)

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/TerraGov-Marine-Corps#347]
If you use a shotgun ammo box on a shotgun ammo belt, it'll put all the shells it has in the belt, regardless of if all the shells will put the belt over its limit.

Step 1) Fill up a shotgun ammo belt till the UI goes yellow.
Step 2) Grab a full shotgun ammo box of any kind and click the belt.
Step 3) Carry 4 more handfuls of shells than you should be able to.

**Comment by ma44** [comment]
Can confirm

**Comment by Ghommie** [comment]
UI going yellow means it's **almost** full, right? If so I know what to fix it then.
