### ISSUE TITLE
Hivelord's Resin Walker ability does not function correctly.

### ISSUE THREAD

**Issue by XElectricX** [tgstation/TerraGov-Marine-Corps#3504]
## Reproduction:

1. Evolve into Hivelord.
2. Weed some areas.
3. Use Resin Walker.
4. Move.
5. Resin walker deactivates itself even if you are on weeds.

Hivelord is crippled into being permanently slow because Resin Walker stops working whenever you move. I believe it might be because of #3403 because it started happening around when it was merged.

**Comment by spookydonut** [comment]
yep #3403 broke it
