### ISSUE TITLE
Unable to join as Round-start Xeno on Crash (Might be on distress as well, not tested)

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#3534]
## Testmerges:

#3530: 'Deprecated shuttle proc' by Rohesie at commit 60e7257c5b 
#3528: 'Makes tree transparent if important objects are hiding behind them.' by nemvar at commit 80eba66db3 
#3505: 'Shield component' by Rohesie at commit 5e6ef28689 
#3512: 'Fixes marines being able to bypass the SD shutters' by Rohesie at commit 9f3656825a 
#3513: 'Distress resin silos' by Rohesie at commit 30457818ee 
#3499: 'Fluff sprites' by Rohesie at commit 0d076799a4 
#3529: 'Xeno MouseDrop fix' by Rohesie at commit 8688f30c62 
#3516: 'Bullet ping fix' by Rohesie at commit 01f96c8592 
#3532: 'Item storage runtime fix' by Rohesie at commit 0baaea3bc3 
#3531: 'Bumps the nuke up a few layers' by nemvar at commit 2669c10e3a 
#3533: 'Scout cloak tweak' by Rohesie at commit 39512e45f3 

## Reproduction:

Have xenomorph. xeno queen, and xeno when unrevivable set to yes. Set all marine roles to No/Never. Ready up for roundstart, and get the message "You have failed to qualify for any job you desired. " when the round starts up.

**Comment by Rohesie** [comment]
Were other xeno players selected? There is a maximum number of xenos at roundstart.

**Comment by TiviPlus** [comment]
Can confirm no xenos seemed to spawn when one person readied up with two burrowed

**Comment by Hathkar** [comment]
> 
> 
> Were other xeno players selected? There is a maximum number of xenos at roundstart.

No, there were zero players selected.

**Comment by XElectricX** [comment]
Can confirm this bug. Tried to be xeno when only one other player was playing. Was not granted xeno at round start but could join as burrowed larva right after,

**Comment by Rohesie** [comment]
I'm reworking the job selection backend, so hopefully this will be fixed along.

**Comment by psykzz** [comment]
The job rework has been in a while and this doesn't seem to still be a problem.
Please comment if im wrong
