### ISSUE TITLE
Welding helmet HUD toggle button does not work

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#3537]
As the title says. Using the HUD toggle button does not toggle the helmet states. However, using the `Adjust welding mask` verb in the objects tab does make it work. 

## Testmerges:

#3533: 'Scout cloak tweak' by Rohesie at commit 39512e45f3
#3531: 'Bumps the nuke up a few layers' by nemvar at commit 2669c10e3a
#3532: 'Item storage runtime fix' by Rohesie at commit 0baaea3bc3
#3516: 'Bullet ping fix' by Rohesie at commit 01f96c8592
#3529: 'Xeno MouseDrop fix' by Rohesie at commit 8688f30c62
#3505: 'Shield component' by Rohesie at commit 5e6ef28689
#3528: 'Makes tree transparent if important objects are hiding behind them.' by nemvar at commit 80eba66db3
#3530: 'Deprecated shuttle proc' by Rohesie at commit 60e7257c5b

## Reproduction:

Noticed in Round 2367 which was a Crash round on Desert Outpost
Tested in Thunderdome 
Tested `/obj/item/clothing/head/welding` and `/flipped` as well as `/obj/item/clothing/glasses/welding` and `/flipped`
Spawned using game panel

The glasses worked fine from the HUD button and objects verb but the helmet only worked with the verb

**Comment by psykzz** [comment]
Bit late, but the action button is working fine for me right now.
I assume this got fixed along the way.

![image](https://user-images.githubusercontent.com/1134201/80479271-ae1be080-8946-11ea-96a7-e1c0f71d3c4e.png)
