### ISSUE TITLE
marines can wire the canterbury into the planet grid

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3548]
not exactly a bug but definitely unintended behavior, it's really garbage for gameplay

**Comment by XElectricX** [comment]
Shut up xeno main.

**Comment by terranaut1** [comment]
Go fix Engineering you lazy lout, if you don't think an unassailable and endless source of global power xenos can't stop is good game design then you're wrong

**Comment by TiviPlus** [comment]
Either way gens need to be indestructible too if someone decides to fix this to stop crushers destroying the gens at roundstart

**Comment by XElectricX** [comment]
SS13 is a game that rewards you for thinking outside the box. Crushers being able to destroy generators is good gameplay. So is connecting your ship's power to the colony. It has it's own advantages and disadvantages compared to fixing engineering generators. The ship's generator is neither endless nor perfect either.

**Comment by Rohesie** [comment]
We'd need to make wires destructible by xenos following that logic, but that'd be terrible for marines.

**Comment by terranaut1** [comment]
One solution would be to have the Canterbury a smidge more power than it consumes, or have the fuel rod run out faster. Electric said its not endless and I don't know the code but I've certainly never seen it run out

**Comment by XElectricX** [comment]
I wouldn't mind if xenos could pry apart floor tiles and destroy wires. Always thought it was weird they couldn't.

**Comment by adamkad1** [comment]
remove crusher ability to crush gens then

**Comment by psykzz** [comment]
This has been addressed, the cant doesn't have enough power to run the autodoc let alone the rest of the planet.
