### ISSUE TITLE
Xeno acid spray stun can be avoided by walking to the tile the spray just landed on from the tile it's going to land on.

### ISSUE THREAD

**Issue by jeesmies** [tgstation/TerraGov-Marine-Corps#3551]
Exactly what is said in the title. This causes the funny issue where a marine can walk "through" an acid spray, even the praetorian one, and keep shooting at the xeno when he should be stunned. Not only does this not make any sense, it also poses a pretty tremendous balance issue, where a marine can completely ignore a spitter caste's most powerful attack while moving towards it. In my specific scenario this caused the death of an elder praetorian, which lead to a spiraling downfall for the xeno side.

The round number where it can be seen happening is 2397.

I *think* the nuke on TG station has something preventing you from walking through the explosion, but one fix I can think of would be to increase the time the acid spray stuns from just impact to the impact and the time it takes until the next impact.

## Reproduction:

To reproduce it, simply try to hit the timing of walking off the tile between the spray landing on the tile next to you and the tile you're on.

**Comment by MacBlaze1** [comment]
this is not an actual bug because this involves an incredible amount of luck and good timing to perform

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.

although, acid splatter has been refactored lately.
