### ISSUE TITLE
Dragging person to autodoc makes doctors fumble

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#3559]
## Reproduction:
1) Grab patient.
2) Click on autodoc.
3) Instant in.

Then,

1) [Optional] Grab patient.
2) Click-drag patient to autodoc.
3) Cry as you fumble with an unfamiliar motion.

**Comment by TiviPlus** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/issues/3638 related
