### ISSUE TITLE
Synths can be reviived with no head

### ISSUE THREAD

**Issue by adamkad1** [tgstation/TerraGov-Marine-Corps#3560]
## Testmerges:
#3552: 'Reduce hunter knockdown from max of 6 secs to 0.5' by psykzz at commit 4aae1fe4ee
#3553: 'Removes M4RA double damage button (burst mode) (again)' by adamkad1 at commit 76075f1748
#3549: 'Move the xeno hive on icy caves' by psykzz at commit cbfefa2d7d
#3535: 'Some balance changes to attachments' by Kuro-ai at commit 5ea45c2784
#3541: 'Speed up larva growth' by psykzz at commit 24962dfe1f
#3546: 'Buff xeno rested healing' by psykzz at commit af87467409
#3545: 'Small buff to xeno contruction' by psykzz at commit 4f0182dec7
#3544: 'Add Fax on bioscan' by psykzz at commit 5b20905867
#3540: 'Harness check cleanup' by psykzz at commit 5159052ed5
#3550: 'Increase larvas worth points of a spec' by psykzz at commit 1ec78b7cad
#3554: 'Updated acid spray processing' by psykzz at commit f1d96ca604

## Reproduction:

Havent done it myself but probally aquire headless synth, fix them, defib them, profit?

https://i.imgur.com/npPR3DR.png  heres a pic

**Comment by TiviPlus** [comment]
As the decapitated Synth in the picture, it was, in fact, fix, defib, profit. Interestingly I couldn't wear any headgear either but I assume that that is intended. If I had to guess this might be an oversight of https://github.com/tgstation/TerraGov-Marine-Corps/pull/3365

**Comment by adamkad1** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/issues/3562 related to this as its the same round

**Comment by psykzz** [comment]
This is intended there is a surgury that can reattach the head later.
