### ISSUE TITLE
Decapitated Synths head is invisible

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#3562]
## Testmerges:
#3552: 'Reduce hunter knockdown from max of 6 secs to 0.5' by psykzz at commit 4aae1fe
#3553: 'Removes M4RA double damage button (burst mode) (again)' by adamkad1 at commit 76075f1
#3549: 'Move the xeno hive on icy caves' by psykzz at commit cbfefa2
#3535: 'Some balance changes to attachments' by Kuro-ai at commit 5ea45c2
#3541: 'Speed up larva growth' by psykzz at commit 24962df
#3546: 'Buff xeno rested healing' by psykzz at commit af87467
#3545: 'Small buff to xeno contruction' by psykzz at commit 4f0182d
#3544: 'Add Fax on bioscan' by psykzz at commit 5b20905
#3540: 'Harness check cleanup' by psykzz at commit 5159052
#3550: 'Increase larvas worth points of a spec' by psykzz at commit 1ec78b7
#3554: 'Updated acid spray processing' by psykzz at commit f1d96ca

## Reproduction:
Map was LV and I got decapitated by a defiler in Nexus. The resulting head was invisible in the inventory and on the ground and I had to right click every tile to find it.
![Nosprothead](https://user-images.githubusercontent.com/57223640/70846181-fa162f00-1e56-11ea-9d50-ea6c9411b48b.PNG)

**Comment by mrhugo13** [comment]
Tested this in a local server,
![dreamseeker_2019-12-14_14-21-32](https://user-images.githubusercontent.com/17747087/70849310-22188900-1e7d-11ea-884e-3caaece96c89.png)
The one that i spawned, it showed the icon, the other one which i chopped off a synth which i spawned, did not show the icon.
