### ISSUE TITLE
M42A with laser sight can yeet anyone through unbreakable yet transparent (multiple) objects

### ISSUE THREAD

**Issue by Teaika** [tgstation/TerraGov-Marine-Corps#3574]
## Testmerges:
#3571 #3570 #3535 #3553 #3561 #3567 

## Reproduction:
1. Get an M42A rifle with attached laser scope.
2. Find an unbreakable yet transparent tile(canterbury cockpit window), find a xeno behind it.
3. Mark a xeno with target marketer and shoot him. Bam! Bullet goes right through the window. Or multiple windows.

**Comment by Hughgent** [comment]
it IS a super armor piercing bullet. I guess the hole it leaves in the 'transparent objects' is super tiny.

I don't see a big issue with this existing.

**Comment by Rohesie** [comment]
This is a bug, not intended behavior.
