### ISSUE TITLE
Bugs about bugs

### ISSUE THREAD

**Issue by drawsstuff** [tgstation/TerraGov-Marine-Corps#358]
~~-Boiler Acid spray no longer stuns like god intended~~
~~-Picking up an item covered in boiler acid is enough to kill any marine that touches it, sending them to crit and ultimately death in less than a minute~~
~~-Boiler's acid globs don't make gas, ever.~~
-Boiler's "Non-lethal" Neurotoxin actually kills marine quicker by poisoning than acid burns would
~~-Huggers do not attach to face if you hold it.~~
~~-Huggers do not attach to face if you try to place it on a face~~
~~-Huggers do not attach to face if the host if you try to place it, even if the host is: Nested, Wearing no masks, Knocked out, Laying down, injured, perfectly healthy, on death's door, dead, or any other reasonable thing that might cause this mind-boggling bullshit~~
~~-Huggers sometimes don't die. Ever. Not even to like bullets or fire.~~
~~-Simple Mobs don't die, ever~~
~~-Crusher's can crush almost any made man barricade, except for actual barricades~~
-When a drone gives another caste 50 units of plasma, it's actually usually over that amount by 200
-Sometimes melting things doesn't melt things, especially melted things, which causes melting nothing
-Lag spikes kills crusher charges
-Despite desperate efforts, setting the queen on fire does not actually hurt the queen. The queen can be standing in fire, red, blue, or green, and not take any damage as long as she stays still and basts in the flames like some kinda salamander.
-Corrupted queens steal non-corrupted larva, which corrupted queens can then kill, basically destroying an entire nest's worth larva in one go.
~~-You can perma-stun a marine to death as long as you have a table nearby. Xenos and marines can do this. Xenos are of course, immune.~~
~~-Grabbing a xeno stuns you longer than if that very same xeno tackled you onto the ground. Even if said xeno is a Crusher.~~
-Xeno blood sometimes glows in the dark.
-Xeno blood can not be melted.
-Xeno glow-in-the-dark blood especially can't be melted.
~~-Larva that don't get a roundstart sit there, forever. They never burrow and are later shot to death.~~
~~-Marines possess an uncanny knowledge of their surroundings and where they've been taken to while they cry for help ratting out the entire hive's location, while in a stomach that is very opaque and not a glow in the dark fun house.~~
-Marines bodies have the uncanny ability to instantly rot the second after they die, in a marvel of science that suggests they are already .1% mold. This is not an issue until the fact that it means the marine you were eating as a xeno kicked the bucket and your senses immediately warn you about the rot.
-Marines that die while being transported in the stomach of a xeno are not thrown out instantly but rather stay for a full 3 minutes despite the logic above
-Spitting a marine out while in a vent causes fun things such as: Instant death, slow death, no death, trapped forever syndrome, magical teleportation, and the entire vent system sometimes ceasing to work at all, forever. 
-Walls without weeds act like walls with weeds if weeds weeded walls before round start, making xenos very confused as to WHERE THE DAMN DOORS GO
-Despite doors being weaker than walls, they take longer for xenos to tear down than walls, even ones made by hivelords
-You can make robot babies with defilers
-You can make corpse babies with defilers
~~-Defilers can not vent crawl by alt clicking a vent~~
~~-Carriers cant either.~~
-Xenos crushed under tanks can get up from under said tank, and destroy it, which destroys the tank and traps the xeno forever
-Any acid placed on the tank is instantly deleted 1 secound after it dare touch the shiny steel of xeno-purging technology
-None of the tunnels on ice work
-The tunnels on ice cant be connected
~~-Making pyro-spec's set themselves on fire is still possible, and still deadly.~~
-The Queen can still place eggs and do things next to her if she's overwatching another xeno entirely half way across the map
~~-Infinite un-enable rounds can be achieved by breaking a window to space as a runner and running out before the shutters close~~
-Xenos can be trapped by having shutters close on them, leading to [never ending storiiieeeesssss](https://www.youtube.com/watch?v=Gf1WT8VEZxk)

**Comment by drawsstuff** [comment]
> ` -Crusher's can crush almost any made man barricade, except for _actual barricades_`
> What barricades are we speaking about here?
METAL ONES
THE ONES YOU SEE MADE EVERY ROUND
> ` -Sometimes melting things doesn't melt things, especially melted things, which causes melting nothing`
> Huh? This requires better explanation.
Sometimes melting things doesnt melt things. This might include melting an already melting object, which makes acid floor puddles that cling to nothing.
> ` -Xeno blood can not be melted.`
> Why would you want to melt any kind of blood?
Because IT GLOWS AND THE DARK

**Comment by Rohesie** [comment]
Ah, crushers damage those barricades with their charge, same as walls. They are designed with more stopping power than a flipped table or a rack. It's also more of a balance decision than a realism one. Also one we inherited from CM.

` Sometimes melting things doesnt melt things. This might include melting an already melting object, which makes acid floor puddles that cling to nothing.`
You mean that you can acid an already acided item and it will break the acid process?

`Because IT GLOWS AND THE DARK`
Ah, CM bug we inherited. Some light sources don't properly delete. Annoying bug to hunt for, but yea, it's there.

**Comment by DominikPanic** [comment]
```-Marines possess an uncanny knowledge of their surroundings and where they've been taken to while they cry for help ratting out the entire hive's location, while in a stomach that is very opaque and not a glow in the dark fun house.```
Unless it's a 100% black overlay marines will be able to tell, even if it's just 3x3 squares.

**Comment by DominikPanic** [comment]
```-Carriers cant either.```
Intended.

**Comment by DominikPanic** [comment]
```
-Infinite un-enable rounds can be achieved by breaking a window to space as a runner and running out before the shutters close```
It will always end thanks to the need of a Queen. But I agree, these should have an invisible barrier before dropping once the windows are destroyed.

**Comment by DominikPanic** [comment]
@drawsstuff Could you keep the list updated?

**Comment by Rohesie** [comment]
We can edit it ourselves as well.

**Comment by DominikPanic** [comment]
Since people are starting to report similar bugs and most of these were likely fixed I'll be closing this, ideally you should create 1 bug report per bug so it's easier for us and others to track.
