### ISSUE TITLE
Xenos and free evolutions

### ISSUE THREAD

**Issue by jjpark-kb** [tgstation/TerraGov-Marine-Corps#3582]
## Testmerges:

#3577: 'Gun rebalance, Mostly DMR' by David-Stormwell at commit f7fd363a58
#3573: 'Meson Rebalance' by Hathkar at commit 1cbba84f79
#3572: 'Update flame turfs for incen grenades' by psykzz at commit 3b53693dbb
#3566: 'adds remote FOB construction' by terranaut1 at commit ef65be279b
#3212: 'Suit Autodoc component' by spookydonut at commit 09e573a582
#3580: 'Species dummies' by Rohesie at commit 86ea5a75ea
#3581: 'Remove idle processing for machines' by psykzz at commit 2317a46085

## Reproduction:

Note that I am not sure if this is exactly how to do it. It occured on Round ID: 2531.

Conditions: No round start shrike on distress.

1) Join a caste that is not drone through the resin silos.
2) Evolve...?

**Comment by TiviPlus** [comment]
Intended and not a bug. See:https://github.com/tgstation/TerraGov-Marine-Corps/pull/3140

**Comment by ma44** [comment]
Related to #3446
