### ISSUE TITLE
ammohud for pump shotguns shows the last shot you fired, not what's currently chambered

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#3587]
1. get a pump shotgun
2. put 3 buckshot rounds in, then 3 flechette rounds
3. start firing
4. after firing the flechette rounds and pumping again (which chambers the first buckshot round) the ammo HUD still shows the flechette icon

also, if you spawn a new shotgun from a vendor and put **any** kind of ammo in, it'll always show the **slug** icon in hud until you fire it

**Comment by Hughgent** [comment]
step 1.
```diff
/obj/item/weapon/gun/shotgun/get_ammo_type()
+	if(in_chamber)
+		return list(in_chamber.ammo.hud_state, in_chamber.ammo.hud_state_empty)
	if(!ammo)
		return list("unknown", "unknown")
	else
		return list(ammo.hud_state, ammo.hud_state_empty)
```

step 2.
```diff
	pump_notice(user)
	playsound(user, pump_sound, 25, 1)
	recent_pump = world.time
	if(in_chamber) //Lock only if we have ammo loaded.
		pump_lock = TRUE
+		
	return TRUE
```
Just below that `pump_lock = TRUE` have it update the users hud. but heck if I know how.

**Comment by Hughgent** [comment]
figured it out.
