### ISSUE TITLE
Can no longer build things over weed nodes.

### ISSUE THREAD

**Issue by XElectricX** [tgstation/TerraGov-Marine-Corps#3610]
## Testmerges:

#3605: 'Add more space near the blue disk generator' by psykzz at commit 4dcf5a8c54
#3543: 'Job refactor' by Rohesie at commit 2e119b0ce0
#3600: 'Unlock airlocks on hijack' by Rohesie at commit b3a1082eb4
#3601: 'Fixes semi-eternal deafness' by Rohesie at commit c0c1429cd2
#3606: 'allow lamps to be broken' by psykzz at commit 115df990d8
#3608: 'Drone salving' by Rohesie at commit 8701f7c7e2
#3604: 'SL Buff and PMC SG nerf' by David-Stormwell at commit 1bf0f2710c
#3603: 'Crash logs' by Rohesie at commit 20798b7c64
#3592: 'New mob: Xeno Hivemind' by psykzz at commit 497df02ad3
#3609: 'Turns View into a string' by Rohesie at commit 1a398b7f44

## Reproduction:

1. Be a xeno that can build.
2. Try to build anything (wall, door, nest, resin) over a weed node.
3. Game will tell you that something is already built there. Previously you could build over weed nodes resulting in the node being deleted. This pretty much ruins building for xenos.

**Comment by psykzz** [comment]
This is intended, but will take this as balance feedback.
