### ISSUE TITLE
Cargo drops broken

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#363]
We had `var/obj/structure/closet/crate/C = locate() in current_squad.drop_pad.loc` but #72 modified it to this:
```
var/obj/C = locate() in current_squad.drop_pad.loc //This thing should ALWAYS exist.
    if(!C.can_supply_drop) //Can only send vendors and crates
        C = null
```
The problem is that the location has these contents, and locate() always picks the first:
```
contents = /list (2) 
1 [0x200b59c] = /obj/structure/supply_drop/bravo 
2 [0x200b59d] = /obj/structure/closet/crate/bravo
```
That means it will always check the drop pad itself and conclude it can't drop it.

**Comment by DominikPanic** [comment]
Fixed in #380
