### ISSUE TITLE
Marine ID tag not working

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#3630]
## Testmerges:

#3616: 'Adds the Heat lens to the M43 lasgun' by Hughgent at commit c1ddc60011
#3619: 'New Crash landing spots' by Hathkar at commit 93b4c6701d
#3603: 'Crash logs' by Rohesie at commit 4f9f80ec05
#3543: 'Job refactor' by Rohesie at commit 7f73dc7046
#3620: 'Crusher Armor nerf' by TiviPlus at commit 5e74823c4e
#3596: 'Adds in QuikDeploy:tm: barricades' by ma44 at commit dee7d97a17
#3566: 'adds remote FOB construction' by terranaut1 at commit 97a7285dd7

## Reproduction:

Try to use a Dog tag on any vending machine to buy a item, it will display this message: Error: Unable to access your account. Please contact technical support if problem persists.

**Comment by Rohesie** [comment]
ID tags lost their bank accounts, but the CLs have them.
Which vending machines do you feel they should have access to?

**Comment by David-Stormwell** [comment]
Cigarette machine at least

**Comment by Rohesie** [comment]
Fixed that by simply giving every marine (not to synths) a bank account in the last commits of the job refactor.
