### ISSUE TITLE
Xenos can cryo marines

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#3638]
## Testmerges:

#3634, #3637, #3631, #3635, #3633

## Reproduction:
As a xeno, take a SSD human and drag their sprite into a cryostasis chamber. You will then put in the human and they will be cryod properly.

**Comment by TiviPlus** [comment]
It seems the Issue is that when you drag/drop someone, it treats it as the person being drag/dropped doing the action themselves and means that the checks are run for the person being drag/dropped which also leads to things like https://github.com/tgstation/TerraGov-Marine-Corps/issues/3559

**Comment by David-Stormwell** [comment]
Not sure if this is related but a ghost can drag a mob to disposals.

**Comment by psykzz** [comment]
> Not sure if this is related but a ghost can drag a mob to disposals.

Fixed in #3692
