### ISSUE TITLE
Auto-Fire still doesn't work

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#3669]
## Testmerges:
#3633 #3607 #3668 #3658

## Reproduction:
Use Auto-fire, proceed to not use it because it doesn't work and it's just normal semi auto

**Comment by Rohesie** [comment]
This is related to TGS being unable to update the submodule. The code works fine.

**Comment by Rohesie** [comment]
Do check if this is still a thing when you test.

**Comment by David-Stormwell** [comment]
This was fixed, I suggest closing it
