### ISSUE TITLE
Can't follow a team more than once

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#3672]
## Reproduction:

1) Follow a xeno via any method.
2) Repeat #1, see how it doesn't work.
3) Follow a human, then a xeno.
4) Follow a human twice to see how *that* doesn't work.

**Comment by psykzz** [comment]
Is this as an observer / ai / hivemind?

**Comment by Shadow-Quill** [comment]
Observer, though the reproduction is still iffy. Hivemind seems to work fine, though i don't know about the AI

**Comment by psykzz** [comment]
This was fixed in a component update.
