### ISSUE TITLE
AI can't use common radio

### ISSUE THREAD

**Issue by grinkgo** [tgstation/TerraGov-Marine-Corps#3695]
## Testmerges:

#3691 #3678 #3607 #3665 #3686 #3690 #3689 #3694

## Reproduction:

Not sure when this started happening, but the AI can't use the ";" prefix for common. I can hear the common channel though, just not talk in it. All other channels work as intended.

**Comment by Toxici11i** [comment]
AI will also get automuted for stating their laws
