### ISSUE TITLE
ERT ammo rigs mysteriously filled by AI

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#3698]
![image](https://user-images.githubusercontent.com/20996272/77835593-232ca800-7146-11ea-9293-fa560c49fd3d.png)
:thinking:

**Comment by TiviPlus** [comment]
Issue is related to ert renaming/equipping

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
