### ISSUE TITLE
Ravager's eviscerating charge is not working as intended according to Surreal

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#371]
![image](https://user-images.githubusercontent.com/18253120/51758422-3d26b280-208b-11e9-99fb-98478fd28e61.png)

Mostly here so I can remind myself to fix this dang thing

## Reproduction:

What is expected to happen: Bonus damage from rage is applied to first marine; the ravager continues charging forward, slicing and knocking marines asides like a crusher charge

What actually happens:
![image](https://user-images.githubusercontent.com/18253120/51758459-5a5b8100-208b-11e9-9a63-5dc72374c80d.png)
If the middle human gets pounced on; it will also hit the top marine, as the ravager is actually thrown and uses mostly default throwing code, meaning when it hits the middle human, it still has momentum to still hit the top human because it 'bounces'.

**Comment by DominikPanic** [comment]
Is this fixed in #469 ?

**Comment by Rohesie** [comment]
Yes, it is.
