### ISSUE TITLE
If a hunter stealths while it's the last xeno alive, it will end the round.

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#373]
## Testmerges:
Most likely irrelevant because it happened about a week ago with me and happened again today

## Reproduction:
Be the last living xenomorph
Activate the stealth ability as a hunter

This should probably admin message the admins so they know it's happening in case the hunter is actually delaying the round

**Comment by Rohesie** [comment]
This along with xenos being in vents are explicit exceptions that will make the round end, but it can be discussed if it's interesting or not for the game.

I wouldn't mind removing the exceptions, but let's get more opinions.

**Comment by DominikPanic** [comment]
We can put it to the vote, this is not a bug though.
