### ISSUE TITLE
Xenomorph Alt-click interactions with spawn shutter

### ISSUE THREAD

**Issue by MissingMyTextures** [tgstation/TerraGov-Marine-Corps#3738]
Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 3201
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: a2cd141cd0ce8c012a927a1636b2802f6df45c2b
The following pull requests are currently test merged:
#3727: 'Icy caves rework' by KwinOriginal at commit b077dc90af
#3715: 'Tac Binocs now can direct the railgun.' by Hughgent at commit 632c639755
#3665: 'Adds a digustingly-countless amount of new names to the namelists' by XSlayer300 at commit 3364645af2
#3607: 'Adds in requisition tablet for Crashed' by ma44 at commit ae0abdc0fd
#3702: 'Armor Update 3.0' by Kuro-ai at commit dd43dfa3c0
#3726: 'Makes survivor armor have no slowdown and fixes a weird typo' by Pariah919 at commit c9bae314ad
#3725: 'Buff xeno evolution/maturity based on stored larva' by psykzz at commit fd243bae74
#3724: 'Fix corrupted xeno eggs spawning regular hive huggers' by psykzz at commit 67078a5930
#3723: 'Fix being able to move an active bomb' by psykzz at commit 1cd1d1b47f
#3718: 'Vendor switcherino' by KwinOriginal at commit 10583a50a2
#3729: 'Crusher stomp no longer has an AOE' by Pariah919 at commit eeb508ffac
#3730: 'Fixes synth name resetting' by psykzz at commit 7faf8268ec
#3733: 'Fixes AI speaking into ;' by psykzz at commit ce92911b9a
#3732: 'Lowers crusher charge knockdown/stun' by Mouseofthecake at commit 54f1d33814
#3731: 'Lowers crusher bullet armor by 4 for all but young' by Mouseofthecake at commit 21270a34b0
#3717: 'Chem rework v2' by jroinc at commit 810e0da513

Local commit: 13f863783756463023b51fb8c45e79cc181cef85
Server tools version: /tg/station 13 Server v3.2.6.2

 Reproduction:

As a xenomorph if you are a caste that can acid walls and such you can Alt-click then cover things on acid that are under the marine spawn shutters if done to a wall this creates the hole which can be seen via alt-click too this allows you to drag your xenomorph sprite onto the hole allowing you to pass through the shutters before they open, also, I'm unsure if this works with window frames too which might or might not allow you to vault them into a shutter

This is possible to be seen especially well in the LV624 map in which there are walls in between each fence section those walls being able to be affected by acid which is where i found the bug initially and there might be other maps with similar walls.

**Comment by David-Stormwell** [comment]
I've suggest in #mapping channel to make 2 wide shutters
