### ISSUE TITLE
Ravager Rage related issues

### ISSUE THREAD

**Issue by ma44** [tgstation/TerraGov-Marine-Corps#375]
## Testmerges:
None; no current pr effects ravagers except the fix bugs pack by surreal, which shouldn't interfere with rage that much

Some issues
-Negative apply_damage() **removes** rages due to it being negative damage
-Some things directly call adjustFireLoss or adjustBruteLoss, which doesn't increment, refresh or get influenced by rage damage reduction or other rage mechanics
-Fire resistance by rage isn't capped; you can get negative fire reduction, this means that fire stacks can heal you and reduce rage because negative damage also reduces rage
-On the topic of fire stacks, fire stacks actually doesn't bookmark and doesn't increase/decrease rage due to the fact it uses adjustFireLoss(), which does nothing to the ravager's rage. 
~~-Damage reduction from rage happens **after** armor calculation, which may make some marines wonder why all of their bullets aren't being absorbed but doing little to no damage as well as making ravagers think their squishy as hell with their 20 armor deflection but are actually tanking hits. Making damage reduced by rage before damage reduction is applied is like with the warding change~~
Not a bug by surreal

**new**
Ravager's Ravage uses Move(), meaning if you used this vertical to barricades, it can be used to bypass them if the ability makes you go vertical to the next turf behind cades, should be using throwing probably so it gets blocked properly 

## Reproduction:
Experiencing the above and noticing weird stuff

**Comment by Surrealaser** [comment]
-Damage reduction from rage happens after armor calculation, which may make some marines wonder why all of their bullets aren't being absorbed but doing little to no damage as well as making ravagers think their squishy as hell with their 20 armor deflection but are actually tanking hits. Making damage reduced by rage before damage reduction is applied is like with the warding change

Intended. Other stuff is getting fixed.

**Comment by DominikPanic** [comment]
Is this fixed already possibly? #366

**Comment by Surrealaser** [comment]
@DominikPanic these issues should be fixed so far as I know.
