### ISSUE TITLE
Hivemind killable via eye

### ISSUE THREAD

**Issue by Tasald** [tgstation/TerraGov-Marine-Corps#3762]
Master commit: 3be5917dac211b95fe924ca404957367a0895f09
The following pull requests are currently test merged:
#3715: 'Tac Binocs now can direct the railgun.' by Hughgent at commit 8bcfa81baf
#3739: 'Add the concept of sundering' by psykzz at commit 655f01babf
#3742: 'Fixes ai xenos targeting hiveminds and other xenos at long distances, structure/door interaction fixed' by ma44 at commit 3db21d86b2
#3744: 'Xeno AI expansion' by ma44 at commit efe31bc557
#3748: 'Singing' by TiviPlus at commit a87e9905b8
#3750: 'Fixes pistol rig not holding other pistols' by grinkgo at commit 0298b7ab6a
#3751: 'Placed AI nodes, fixed some messy things' by KwinOriginal at commit 7513fe9f51
#3754: 'Adds Whiskey Outpost json file.' by MerryweatherLost at commit dd449ddf99
#3747: 'M56D IFF adding' by Pariah919 at commit d407620d13
#3732: 'Lowers crusher charge knockdown/stun' by Mouseofthecake at commit 54f1d33814
#3717: 'Chem rework v2' by jroinc at commit a2c393b808
#3607: 'Adds in requisition tablet for Crashed' by ma44 at commit ae0abdc0fd
#3753: 'DataMiner' by Hughgent at commit 159ce1e3a8
#3752: 'Updates scout/sniper cloak's descriptions' by Mouseofthecake at commit 2c4e22868c
#3749: 'You will now cool down when putting you get put out' by TiviPlus at commit 0f63d499b1
#3756: 'Crusher charge damage nerf' by Pariah919 at commit 492e54d87d
#3757: 'Vapor and Tyson Remastered' by MerryweatherLost at commit 1325781978
#3746: 'Phosphorus nades' by TiviPlus at commit 370b2c78ff
#3759: 'Sectoid ERT with shuttle map fix' by Spyroshark at commit 25e4c203bc

Local commit: 14a12564e947b9058a43c7cd192e2d27b5145552
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Play as hivemind in a round, then go observe a det pack astleast. 

Don't know if other stuff works but I died to a detpack on desert outpost as the hivemind 'eye', not the node that was way in the back of the map and still alive.

**Comment by psykzz** [comment]
This was fixed in #3849
