### ISSUE TITLE
Major Larva Infection Prema death bug

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#3767]
## Testmerges:

#3715 #3739 #3742 #3744 #3748 #3750 #3751 #3754 #3747 #3732 #3717 #3607 #3753 #3752 #3749 #3756 #3757 #3746 #3759

## Reproduction:

Become infected with a larva, then die while in that span of time, instead of having a normal defib timer the game will assume you are prema dead and display a skull and for some unknown reason and you cannot be defibed.

**Comment by psykzz** [comment]
I couldn't reproduce this 
![image](https://user-images.githubusercontent.com/1134201/79027732-3a778680-7b85-11ea-887a-ddf09216392c.png)

**Comment by David-Stormwell** [comment]
It still happens quite often, there might be a thing I'm missing

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
