### ISSUE TITLE
Game Preferences while not in Lobby

### ISSUE THREAD

**Issue by IzzaBinS33n** [tgstation/TerraGov-Marine-Corps#377]
Oy i was just playing and whenever im not in the lobby screen I cant change any of my preferences when i go to OOC then Game Preferences and when i click anything it doesn't read it. I don't know if this is a bug or feature but i think its a bug in my opinion hope to fix soon so that when i die i can change my prefs and not be in lobby just to do it.

**Comment by DominikPanic** [comment]
Sometimes the other window appears under the main one due to how bad the code is, are you sure the things don't appear nor save at all?
