### ISSUE TITLE
Use every tank "Object" word after chestburst and dead Inside a tank. Spawned larva is stuck under tank

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#378]
![image](https://user-images.githubusercontent.com/45321263/51782114-4029ad80-2134-11e9-8fea-f8cba105a37b.png)

**Comment by Monikawales** [comment]
Every tank "Object" word is availible to use

**Comment by Monikawales** [comment]
Rotate word works only once then need to swap seats

**Comment by DominikPanic** [comment]
@Ghommie You should approach it from the larva perspective - if you burst while inside of something, you should pop out, to prevent most issues that we can't think of right now.

**Comment by Ghommie** [comment]
Yes, that should be right for it to automatically attempt exit.

**Comment by DominikPanic** [comment]
Fixed
