### ISSUE TITLE
Tank gun shooting using binoculars instead of artillery module

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#379]
I didn't test it a lot so I don't know arty module accuracy.
Cannon using a binoculars shoots different tiles then I have clicked.
Cannon rounds hit marines when they stand close and hit barricades when 2+ layers of barricades.
The main problem is using a binoculars while gunner seat. Artillery module is unused because people man a gunner seat using binoculars.

**Comment by Ghommie** [comment]
So so, What happens there is the binocuars processing handle_click instead of the tank. Though I need to make sure the WIP works.

**Comment by Monikawales** [comment]
Still works.
1. Start entering driver or gunner seat
2. Swap hands.
3. Activate binoculars

**Comment by DominikPanic** [comment]
Fixed
