### ISSUE TITLE
The queen can pilot the dropship on Whiskey Outpost, leading to hilarity

### ISSUE THREAD

**Issue by drawsstuff** [tgstation/TerraGov-Marine-Corps#3790]
## Testmerges:

#3787 #3648 #3744 #3748 #3749 #3751 #3754 #3759 #3760 #3774 #3775 #3778 #3717 #3607 #3665 #3786 #3783 #3777 #3765 #3763 #3742 #3715 #3782

## Reproduction:

1. Become a queen on whiskey outpost, through any means
2. Make your way to the dropship
3. Pilot the dropship

### Notes:
After calling the dropship, several of the following happened:

- The Queen who sent the dropship was sent to nullspace
- The dropship became unable to be sent by marines (Xenos untested)
- The alert that the dropship was crashing into the station played twice

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
