### ISSUE TITLE
Codex doesn't list attachies

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3791]
## Testmerges:

#3787 #3648 #3744 #3748 #3749 #3751 #3754 #3759 #3760 #3774 #3775 #3778 #3717 #3607 #3665 #3786 #3783 #3777 #3765 #3763 #3742 #3715 #3782

MJP says Hugh is to blame for this

**Comment by Hughgent** [comment]
hah
```
/atom/proc/get_specific_codex_entry()
	if(SScodex.entries_by_path[type])
		return SScodex.entries_by_path[type]
```

because I used the path's it's only giving the path instead of the generated option.
