### ISSUE TITLE
Distress Beacons don't send when admin approved early

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3797]
## Testmerges:

#3772 #3788 #3787 #3648 #3744 #3751 #3754 #3759 #3774 #3775 #3717 #3607 #3786 #3777 #3765 #3742 #3715 #3782 #3793 #3796

## Reproduction:

1. Player calls Distress Beacon
2. Admin clicks Random
3. Nothing happens

Works normally when you just let the timer run out, producing a random ERT.
Responding with at least XRT specifically also works fine.

[06:51:17] Runtime in emergency_call.dm, line 76: Cannot modify random.mob_max.
proc name: activate distress (/datum/game_mode/proc/activate_distress)
usr: ckey removed/(mob removed)
usr.loc: (Combat Information Center (121, 111, 3))
src: Distress Signal (/datum/game_mode/infestation/distress)
call stack:
Distress Signal (/datum/game_mode/infestation/distress): activate distress("random")
the communications console (/obj/machinery/computer/communications): Topic("src=\[0x2003c68];operation=dis...", /list (/list))
Dimosek (/client): Topic("src=\[0x2003c68];operation=dis...", /list (/list), the communications console (/obj/machinery/computer/communications))
Dimosek (/client): Topic("src=\[0x2003c68];operation=dis...", /list (/list), the communications console (/obj/machinery/computer/communications))

**Comment by psykzz** [comment]
Was fixed by #3812
