### ISSUE TITLE
You cannot build barricades on grass

### ISSUE THREAD

**Issue by Jalleo** [tgstation/TerraGov-Marine-Corps#3838]
## Testmerges:
None that matter
## Reproduction:
Due to a change in https://github.com/tgstation/TerraGov-Marine-Corps/pull/1203 the barricades are not able to be constructed on grass or other non normal open/floor turf.
Examination of the code before and after would reveal that they were buildable on grass or even in the river as it is still on the CM13 codebase.
https://github.com/tgstation/TerraGov-Marine-Corps/blame/dc5cedb1fe8903e7abcca24c43423b32702fb157/code/game/objects/items/stacks/stack.dm#L226

**Comment by MacBlaze1** [comment]
spooky says not a bug
