### ISSUE TITLE
Larva do not die after being downed

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#3856]
## Testmerges:

#3809: 'Alamo Surgery Table Attachment' by Hathkar at commit adeadf43c4
#3822: 'Removes squad coloring from gloves' by Mark9013100 at commit b956a355dc
#3823: 'Coffee/water rework and minor chem changes' by jroinc at commit aa82a4b11d
#3831: 'Xeno caste changes, mostly buffs.' by Pariah919 at commit ad7f8afede
#3818: 'Sundering and a lot of gun changes.' by Pariah919 at commit 933e58b2af
#3786: 'Makes platforms more destructible' by TiviPlus at commit 310cea22e1
#3829: 'BC changes' by Pariah919 at commit acc9271904
#3607: 'Adds in requisition tablet for Crashed' by ma44 at commit ae0abdc0fd
#3777: 'Research Outpost Map' by Isy232 at commit 8b3c69df5b
#3849: 'Fixes hivemind dying to explosions' by psykzz at commit 639a4f12be
#3848: 'Make hiveminds right clickable again' by psykzz at commit 7ab91230b8
#3843: 'Crayon cleanup' by psykzz at commit 86e2cbf1d1
#3854: 'Fix explosion not actually creating fires' by psykzz at commit 0fcf6746e8
#3853: 'Fix alamo crash not happening' by psykzz at commit ee0a797b91
#3852: 'Fix the canterbury launching before confirming the launch' by psykzz at commit 7f68e8594e

## Reproduction:

Noticed a few times the past round that larva would get downed, shot many times, and not gib/die. Looked at the VV on one and it had a brute damage of ~55 but nothing too crazy. I have tested it in the thunderdome by shooting spawned in larva and the same thing happens. 

It looks like it is maxing at 60 brute damage and not going higher.

**Comment by psykzz** [comment]
I wonder if this is related to https://github.com/tgstation/TerraGov-Marine-Corps/pull/3849, will need to look at larva code

**Comment by henriquekill9576** [comment]
was going to report this now but you already did so
have some pics
https://gyazo.com/0ebee2b6bf76ec011389e45a7b0d11fe
https://gyazo.com/76affc70c5e277b79a17bb060bf961a1
