### ISSUE TITLE
(Admin tools) Active players reported as 15 minutes inactive

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#3865]
## Testmerges:
#3857: 'Xeno Bump Attack toggled on by Default' by BobSlim at commit c7f7bbe42c
#3858: 'Smartgunners get helmets in their boxes' by Pariah919 at commit 5d621a6fbc
#3849: 'Fixes hivemind dying to explosions' by psykzz at commit 639a4f12be
#3777: 'Research Outpost Map' by Isy232 at commit e96246ce08
#3607: 'Adds in requisition tablet for Crashed' by ma44 at commit ae0abdc0fd

## Reproduction:

I am not sure how it is happening. But I have only noticed it within the last ~2-3 weeks

Looking at OOC logs of the people it is not consistently 15 minutes after a relog/disconnect. I will collect more info when I see it next.

**Comment by Mr-Worth** [comment]
On further investigation it looks like DS transit is causing mobs to loose their mind or something and count as DC'd. Attached is a picture of the mob OOC log from the reportedly AFK player. The automated report happened 15 minutes after that. The client OOC log does not show the disconnects.
![DS Soulstealer](https://user-images.githubusercontent.com/47805468/79525451-b9524080-8017-11ea-8f05-f36ba4039602.png)

**Comment by David-Stormwell** [comment]
To touch on this, I'm pretty sure it just happens if someone logs out then logs back in.
