### ISSUE TITLE
Bad spirte on double barrel shotgun

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#3882]
## Testmerges:

#3874: 'Mines can now be melted by xenos' by psykzz at commit 54ab3188ca
#3876: 'Removes unused attachments from distress, adds the T-19 stock to distres.' by Pariah919 at commit f8bb4b69be
#3878: 'Adds a spare post to the M56D box' by Pariah919 at commit e98561b386
#3880: 'Powerloader skill increases to RO, CE, Combat Engineers, and early model synths; RO can now flash marines' by XElectricX at commit 10b782a285
#3830: 'Las rifle' by Hughgent at commit 640c8f59e0
#3864: 'Neurotoxin improved for capture mechanics, altered overdose' by BobSlim at commit d69ba7f093
#3868: 'Removes QFA from handguns, adds gyro to handguns and scopes to rifles.' by Pariah919 at commit 42da26c9c3
#3607: 'Adds in requisition tablet for Crashed' by ma44 at commit ae0abdc0fd
#3777: 'Research Outpost Map' by Isy232 at commit e96246ce08
#3873: 'Adds Imi,Alky and tricord pill bottles to marinemed' by Pariah919 at commit 40efd3d5e0
#3871: 'Boiler glow green/yellow based on ammo' by BobSlim at commit f21d5b31aa

## Reproduction:

![image](https://user-images.githubusercontent.com/1134201/79643163-8fc12280-8199-11ea-83b8-e66ec3e0e589.png)

**Comment by Hughgent** [comment]
What's the icon_state say?

**Comment by psykzz** [comment]
It was in the image but it said `dshotg`
