### ISSUE TITLE
Spatial Agent creation runtime on becoming, stopping being and becoming a a spatial agent again

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#3897]
## Testmerges:

master
## Reproduction:

[18:19:49] Runtime in unsorted.dm, line 37: Found a reference to an undeleted mind in mob/Destroy()
proc name: stack trace (/datum/proc/stack_trace)
usr: *no key*/(Charles Kern)
usr.loc: (Hangar (58, 24, 3))
src: Charles Kern (/mob/dead/observer)
src.loc: the floor (58,24,3) (/turf/open/floor/mainship)
call stack:
Charles Kern (/mob/dead/observer): stack trace("Found a reference to an undele...")
Charles Kern (/mob/dead/observer): Destroy(0)
Charles Kern (/mob/dead/observer): Destroy(0)
qdel(Charles Kern (/mob/dead/observer), 0)
TiviPlus (/client): Spatial Agent()

**Comment by psykzz** [comment]
Fixed #4011
