### ISSUE TITLE
Scope LOS bug

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#3907]
## Testmerges:#
#3877 #3900 #3887 #3888 #3884 #3889 #3873 #3777 #3607 #3830 #3894 #3901

## Reproduction:
When you click on something which you cannot see, such as past a boiler gas cloud you will shoot in a random direction such as to the right of you instead of shooting ahead.

**Comment by XElectricX** [comment]
Confirming this also works on my own repo. Was using binoculars and clicking any dark boxes will make you look in a different direction. Doesn't seem to be a pattern in what direction you turn to.

**Comment by psykzz** [comment]
Fixed in #4006
