### ISSUE TITLE
Marine role point vendors do nothing

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3920]
as topic, you can't select gear from them, the list is just empty
occurs at least for medic vendors on sulaco and pillar, possibly others

## Testmerges:

The following pull requests are currently test merged:
#3835: 'Fixed thermite recipe' by IEatRox at commit e3649a3ab6
#3902: 'Rebalance the ridiculous cargo prices, add new items to the list' by XElectricX at commit 3924486d85
#3908: 'Xeno Aging Tweak' by InterroLouis at commit 842cec51b1
#3916: 'Runechat port [DNM]' by psykzz at commit 7be4699aa1
#3911: 'Refactor xenomorph throw_impact()' by spookydonut at commit 54d2cf3822
#3912: '[DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles' by spookydonut at commit 5717eabb53
#3891: 'Sulaco changes ' by Timmeye at commit a9730343df

**Comment by Pariah919** [comment]
it's probably related to tgui changes made by spooky

**Comment by terranaut1** [comment]
@spookydonut mind checking that out

**Comment by psykzz** [comment]
Fixed in #3932
