### ISSUE TITLE
Deaf people can see runechat

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#3929]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 3467
BYOND Version: 513.1508
Server revision compiled on: 
Master commit: 6c4d9f562769a1e7a8ffdebec82bc0616b75fe51
The following pull requests are currently test merged:
#3891: 'Sulaco changes ' by Timmeye at commit 8b5730298f
#3912: '[DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles' by spookydonut at commit 5717eabb53
#3911: 'Refactor xenomorph throw_impact()' by spookydonut at commit 54d2cf3822
#3916: 'Runechat port [DNM]' by psykzz at commit 7be4699aa1
#3908: 'Xeno Aging Tweak' by InterroLouis at commit 842cec51b1
#3902: 'Rebalance the ridiculous cargo prices, add new items to the list' by XElectricX at commit 3924486d85
#3835: 'Fixed thermite recipe' by IEatRox at commit e3649a3ab6
#3910: 'Binocular buffs' by XElectricX at commit a34f02739c
#3607: 'Adds in requisition tablet for Crashed' by ma44 at commit ae0abdc0fd
#3742: 'Fixes ai xenos targeting hiveminds and other xenos at long distances, structure/door interaction fixed' by ma44 at commit 40d1c3559d
#3926: 'SO and Captain skills update' by Ghostboy1217 at commit 10d1ba77e2
#3924: 'Does changes to the fire rate/damage of the BR.' by Pariah919 at commit 2bbe189fd7

Local commit: 20ee681b91fd392a23966c7522b0a1df64422186
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. Get deaf by something (Queen screech for example)
2. Watch as you are able to read runechat from other people or even yourself

**Comment by ma44** [comment]
Inb4 reading lips

**Comment by psykzz** [comment]
Fixed in #3916 @ commit 1e4e0e85323ceef00a2ac54b70d77f7d25426f54
