### ISSUE TITLE
Landing zones can still be accessed by small xenos before containment shutters are lifted

### ISSUE THREAD

**Issue by GLACoding** [tgstation/TerraGov-Marine-Corps#3961]
## Testmerges:

#3950 #3902 #3916 #3936 #3941 #3942 #3944 #3924 #3926 #3607 #3912 #3891 #3931 #3935 #3938 #3937 #3940 #3927 #3955 #3953 #3952

## Reproduction:

1. Find a containment shutter that has a wall beneath it
2. Use alt click on a containment shutter to view all objects on the tile
3. Use strong acid on the wall to create a hole
4. Any small xeno can now ctrl click the hole to pass through to the LZ

**Comment by David-Stormwell** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/issues/3738
This has already been reported a few times now

**Comment by psykzz** [comment]
As David said already reported in the other PR. Closing for that one
