### ISSUE TITLE
You can have more than 4 specs/smartgunners at a time.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#3987]
## Testmerges:
Not sure. Seems to have been happening for a while now.

## Reproduction:
Step 1. Get enough specs/SGs to fill up all the squads.(4)
Step 2. For some reason after enough people join you should get more slots for SGs and Specs. Not sure why.

**Comment by TiviPlus** [comment]
Wasnt this made to scale with pop specifically so we could have more than 4

**Comment by Pariah919** [comment]
Pretty sure it's supposed to only be 1 per squad. Or 4 for the entire marine force.

**Comment by psykzz** [comment]
Nah this is intended.

**Comment by Pariah919** [comment]
that's dumb but sure
