### ISSUE TITLE
Punches don't get logged into FFATTACK

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#3988]
as title, they're just in ATTACK, making it more difficult to check for FF stuff

**Comment by terranaut1** [comment]
upon further inspection its only shots that are logged, melee weapons or things like disarms arent logged either. probably more of a feature request than a bug, i suppose

**Comment by psykzz** [comment]
This was fixed in https://github.com/tgstation/TerraGov-Marine-Corps/pull/3994
