### ISSUE TITLE
Orbitting is offset to the left

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#4003]
## Testmerges:

Round ID: 3547
BYOND Version: 513.1508
Server revision compiled on: 
Master commit: be5a77b219f1de34ebf068b6aa1f76317f036fce
The following pull requests are currently test merged:
#3974: 'soft/hard armor' by Rohesie at commit 84361b8f08
#3985: 'Command Armor Buff' by Max-023 at commit ab8bca6742
#3996: 'Adds grenade pouches.' by Pariah919 at commit c8b24e54f9
#3912: '[DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles' by spookydonut at commit 59398405dd
#3976: 'Adds the M-22 bayonet (knife), and redoes shoe storage while at it' by Pariah919 at commit b2a9a52c52
#3936: 'Chem rework mk3 the nerfening' by jroinc at commit 70382e4445
#3916: 'Runechat port [DNM]' by psykzz at commit e977b775d5
#3981: '/tg/ explosions' by Rohesie at commit 73b44f6d4c

## Reproduction:
As a ghost orbit anything
Orbitting is offset left by about 16pixels

Example orbitting the red door
![image](https://user-images.githubusercontent.com/1134201/81324050-4f650e00-908e-11ea-8978-8c5274928d5a.png)

**Comment by Rohesie** [comment]
This seems to be true on all /tg/ servers, even old codebases.
I wonder if it was a change on BYOND things.
