### ISSUE TITLE
Headcoder color is practically unreadable on darkmode

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#4026]
## Testmerges:
#4025: 'Support draw_mode for internal storage' by psykzz at commit 4680a18cee
#3996: 'Adds grenade pouches.' by Pariah919 at commit b589a60dc9
#3912: '[DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles' by spookydonut at commit 59398405dd
#3976: 'Adds the M-22 bayonet (knife), and redoes shoe storage while at it' by Pariah919 at commit d0b39823df
#3916: '[REMOVE THIS] Runechat port [DO NOT TEST MERGE]' by psykzz at commit e977b775d5
#4024: 'should fix shuttle explosions' by spookydonut at commit e05782c949
#4017: 'Hivelord can build on nearby turfs again' by XElectricX at commit 6c16c46c49
#4014: 'Better flamer refueling methods and a standard flamer buff' by XElectricX at commit 3b2856e3da
#4001: 'Halves frenzys effects' by Pariah919 at commit 7534a81446
#3998: 'autoshotgun changes' by Pariah919 at commit d6255e8778
#3975: 'Finally removes stealth_router' by spookydonut at commit c0b406396d
#4023: 'Disables ship explosions during crashes [TEST MERGE]' by psykzz at commit 2aa7217bdb

## Reproduction:
1.Have the headcoder on, or give yourself the rank or something.
2. Turn on dark mode.
3.Have eyerape trying to look at the color

![image](https://user-images.githubusercontent.com/46353991/81485399-a2ab9d80-9201-11ea-9b2a-cbe98d485c2b.png)

**Comment by psykzz** [comment]
I thought people just ignored me
