### ISSUE TITLE
Destroyed girders block acid spray.

### ISSUE THREAD

**Issue by Ketrai** [tgstation/TerraGov-Marine-Corps#404]
Slashed open girders completely block acid spray from going through. The marine counterpart, flames, however... does not. It feels inconsistent and should probably reproduce.

Steps to reproduce :

1. be boiler/spitter
2. slash open a wall, then the girder.
3. try and spray through the girder, your spray will magically get absorbed.

**Comment by DominikPanic** [comment]
Related: #126 
Behavior should be consistent with both.
