### ISSUE TITLE
tank can sometimes become blocked by it's own hitbox

### ISSUE THREAD

**Issue by francinum** [tgstation/TerraGov-Marine-Corps#407]
## Testmerges:
#320: 'Xeno Balance Tweak' by Surrealaser at commit 337022eccc 
#367: 'Re-ports Xeno Sprites + General Cleanup' by Alterist at commit e1e7920e10 
#368: 'Brig Overhaul' by Jimminian95 at commit 107a1456f0 
#384: 'Adds a new anti-Brute medication called "Meralyne."' by Lainwright-Lazuli at commit 96e5936f21 
#385: 'Temporary Music PR (don't close me Qustinnus)' by DominikPanic at commit 24afbf25db 
#388: 'Lasguns can light cigarettes now' by Surrealaser at commit 9b62cf0407 
#394: 'Fixes larva being unable to go drone after queen's death.' by Ghommie at commit ecdd2ad78f 
#395: 'Quickfixes a few tarps problems.' by Ghommie at commit 201b32c879 
#397: 'Fixes simple mobs being catatonic and unkillable.' by Ghommie at commit d0145632c7 
#382: 'Admin Tweaks' by DominikPanic at commit a37b1ac6e4 
#366: 'Bug Fix Pack - 1-25-2019' by Surrealaser at commit 72c75fecb4 
#219: 'Flare and Impact DP Grenade Types Added' by Surrealaser at commit f054548692 
#123: 'Big Red' by Rohesie at commit 6e9c81f8c1 

Doesn't seem relevant however.

Generates a strange invisible hitbox object in front of the door, preventing use.

**Comment by DominikPanic** [comment]
Seems fixed. Feel free to report again if it persists.
