### ISSUE TITLE
Neurotoxin can destroy barricades

### ISSUE THREAD

**Issue by XElectricX** [tgstation/TerraGov-Marine-Corps#4072]
## Testmerges:

#4062: 'Smartgunner fires slower and harness is removed. Sunder is a bit more.' by Pariah919 at commit bfca4aa3bc
#3912: '[DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles' by spookydonut at commit c2400e24d4
#4063: 'Crusher charge does 25 *1/2/3 instead of 10 *1/2/3' by Pariah919 at commit c99e68bc67
#4065: 'Reqs TGUI' by spookydonut at commit 1d0f4e236d
#4056: 'Update webmaps' by psykzz at commit 1731f7bfe6
#4048: 'Unpowered Doors Opened by Xenos Quickly' by BobSlim at commit ecb46c0cc3
#4047: 'you can refill mags with other mags' by BobSlim at commit 7a94343e78
#4046: '"Shotgun Shell Pouch/Belt" can be refilled with any magazines (with loose ammo)' by BobSlim at commit ccbfb1c7f5
#4028: 'Fixes explosions happening at the same time as crash' by Rohesie at commit e626733fec
#4014: 'Better flamer refueling methods and a standard flamer buff' by XElectricX at commit b7485566db
#3998: 'autoshotgun changes' by Pariah919 at commit a54543ca6a
#3933: 'United Space Lepidoptera' by Sibg at commit f0be01ca74
#4067: 'Stamina regen nerf' by Rohesie at commit d856b1a9ce
#4050: 'Queen no longer scales horrifically badly. Has slightly less peak melee damage. Spits faster.' by Pariah919 at commit 8940fb9df8

## Reproduction:

1. Be Sentinel
2. Spit at barricades.

![](https://cdn.discordapp.com/attachments/500801682058379265/711244243263553626/unknown.png)

**Comment by jroinc** [comment]
Tested, young sentinel spit VS metal cade = 45 damage.

**Comment by Hughgent** [comment]
will likely be fixed by #4096

**Comment by psykzz** [comment]
This was fixed by #4096 as per @Hughgent's comment
