### ISSUE TITLE
Get Server Logs produces an error

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#411]
https://i.imgur.com/EqAGWBT.png

**Comment by DominikPanic** [comment]
That's intended and supposed to be there, this isn't the verb producing the error.
In world.dm:
`	GLOB.config_error_log = GLOB.world_manifest_log = GLOB.sql_error_log = GLOB.world_href_log = GLOB.world_runtime_log = GLOB.world_attack_log = GLOB.world_game_log = "data/logs/config_error.[GUID()].log" //temporary file used to record errors with loading config, moved to log directory once logging is set`
