### ISSUE TITLE
AI download message repeats itself

### ISSUE THREAD

**Issue by MacBlaze1** [tgstation/TerraGov-Marine-Corps#4124]
## Testmerges:
![image](https://user-images.githubusercontent.com/33578623/82958163-6a82b980-9f7a-11ea-8387-719f65db8ac1.png)

## Reproduction:

have an AI download into the core during a round.
![image](https://user-images.githubusercontent.com/33578623/82958049-1bd51f80-9f7a-11ea-87e4-6682ece6c222.png)

**Comment by psykzz** [comment]
Just tested this with latest and its not happening.
Closing. Feel free to poke me again if its still happening.
