### ISSUE TITLE
Bull and crusher can ram AND slash people who are prone.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#4127]
## Testmerges:
#4122: 'Survivor armor now has bio protection' by Pariah919 at commit 343ed09013
#4123: 'Makes carrier trap more visible' by Kuro-ai at commit dedd192f62
#4121: 'Specs are gone, reduced to ashes. Everyone can now use spec weapons effectively.' by Pariah919 at commit 8f0db3918e
#4118: 'Changes the Assault Rifle and carbine firing sound' by Kuro-ai at commit 03f0adb6a9
#4069: 'Add a new evolution UI' by psykzz at commit 24bed67dbb
#4095: 'Screech is more effective at point blank and screen edge, goes threw walls at *2 instead of *7..' by Pariah919 at commit 70864c0d8a
#3931: 'Modular armor' by psykzz at commit 6a4b3f188a
#3912: '[DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles' by spookydonut at commit c2400e24d4
#4028: 'Fixes explosions happening at the same time as crash' by Rohesie at commit e626733fec
#4014: 'Better flamer refueling methods and a standard flamer buff' by XElectricX at commit b7485566db
#4120: 'Improve job panel' by psykzz at commit 7d093d2e45
#4114: 'Ports TG smartcables' by spookydonut at commit d4ed0f78df
#4125: 'lets boilers make bombs whenever they're not zoomed' by terranaut1 at commit 02a9ad79e3

## Reproduction:
1. Be a bull or crusher.
2. Turn on bump slash (else you need literally pro gamer reaction time to do this.)
3. Ram someone while on harm intent.
4. If they are prone, you will slash them and ram them.

**Comment by MacBlaze1** [comment]
close this, bump slashing will be an irrelevant issue and so will this due to directional slashing

**Comment by Chaznoodles** [comment]
This is gone, due to bump no longer triggering on people who are lying down.

@TiviPlus
