### ISSUE TITLE
Tank-Stunned xenos dont take damage from flames

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#424]
## Testmerges:
Confirmed last 3 rounds

**Comment by Monikawales** [comment]
People stopped picking flamer I think this bug still exist

**Comment by DominikPanic** [comment]
@Ghommie Did your PR perhaps fix this?

**Comment by Ghommie** [comment]
Maybe, thought this might be something to do with the fire code. Got to check.

**Comment by DominikPanic** [comment]
@Menshin Perhaps this one's rather for you

**Comment by DominikPanic** [comment]
This seems to be fixed, was able to set aflame a tank-stunned xeno, and he kept getting damaged by the flame.
