### ISSUE TITLE
tail2 and tail3 emotes display "roars!" in text chat instead of "swipes its tail"

### ISSUE THREAD

**Issue by Lobachevskiy** [tgstation/TerraGov-Marine-Corps#4244]
Use *tail2 or *tail3. It plays the tail swipe sound, but in the chat it says "X roars!". *tail and *tail1 work fine.

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 3925
BYOND Version: 513.1508
Server revision compiled on: 
Master commit: 8aa472077dd0226140ceeb1f11dc29c0204121a9
The following pull requests are currently test merged:
#4231: 'Better admin controls over FF' by psykzz at commit 8fb628a7c9
#4234: 'Fix APC in hanger security on ice colony' by psykzz at commit f678834a02
#4235: 'Machine pistol now pistol sized, less ammo in mags' by XElectricX at commit f9f515396d
#4236: 'Buffs sunder recovery while resting' by psykzz at commit ea1d5b77a5
#4211: 'Buffs barricades ' by MacBlaze1 at commit dfffa6c9cf
#4218: 'Map fixes for Sulaco and Pillar' by XElectricX at commit 53fa6b5a83
#4028: 'Fixes explosions happening at the same time as crash' by Rohesie at commit e626733fec
#4203: 'Sentry Health Buff' by InterroLouis at commit 3d68bd86c8
#4241: 'Remove some orbit debugging' by psykzz at commit 67049e4e53
#4242: 'Fix empty count for round end' by psykzz at commit ce5ed9ad74

Local commit: b256813efd8520303bce6ad8efc8791e1241cc95
Server tools version: /tg/station 13 Server v3.2.6.2

**Comment by psykzz** [comment]
Should be fixed with the above PR.
