### ISSUE TITLE
Ai will slash in ways it shouldnt be able to slash

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#4267]
## Testmerges:

The following pull requests are currently test merged:
#4247: 'Fix xeno emotes' by psykzz at commit dd1262e4e4
#4249: 'Fixes exploding evac shuttles' by psykzz at commit 82d1a65c42
#4251: 'AI can no longer near mobs on turfs they can't see' by psykzz at commit eeb7ac4ed2
#4253: 'Fixes admin away messages' by psykzz at commit 80ba510514
#4254: 'Fix id card computer' by psykzz at commit 94af35b814
#4255: 'Stop xenos vent dragging marines past fog' by psykzz at commit 2c8adcc6b8
#4256: 'Improve autodoc' by psykzz at commit 3a155580c9
#4257: 'Fix orbit offsets' by psykzz at commit c7cc6442df
#4245: 'Fixes Defiler stats' by Mouseofthecake at commit 8e7cbb72f4
#4246: 'Reduce amount of extra SG slots' by XElectricX at commit 23779c7710
#4242: 'Fix empty count for round end' by psykzz at commit ce5ed9ad74
#4241: 'Remove some orbit debugging' by psykzz at commit 2d3a1a7b06
#4203: 'Sentry Health Buff' by InterroLouis at commit 3d68bd86c8
#4028: 'Fixes explosions happening at the same time as crash' by Rohesie at commit e626733fec
#4218: 'Map fixes for Sulaco and Pillar' by XElectricX at commit 53fa6b5a83
#4211: 'Buffs barricades ' by MacBlaze1 at commit dfffa6c9cf
#4235: 'Machine pistol now pistol sized, less ammo in mags' by XElectricX at commit f9f515396d
#4252: 'Fixes some autodoc issues' by psykzz at commit fb5a3fe51b
#4265: 'Fix razorwire entangle bug' by spookydonut at commit 1da0b01d40
#4264: 'fixes the IS module to be like a satchel' by MacBlaze1 at commit 68ace87d80
#4262: 'gives combat engineers proper engineering access' by MacBlaze1 at commit 2f9b48a6b0
#4260: 'Adds the T-70 grenade launcher ' by Pariah919 at commit edbcdb7bc4

## Reproduction:

-Ai will slash through cades, unlike normal xenos
-AI can slash diagonally through walls, in this example picture the AI was slashing people inside medbay where the IV is
![image](https://user-images.githubusercontent.com/57223640/85171624-a6eec000-b26f-11ea-911f-3ba5b8fa3566.png)

**Comment by Iamgoofball** [comment]
That's a lot of fucking testmerges

**Comment by Hughgent** [comment]
@ma44 this ones on you if anyone.

**Comment by BraveMole** [comment]
Fixed i think? Also lel, not a good first issue at all
