### ISSUE TITLE
Hivemind can enter LZs via diagonal movement 

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#4274]
Seen on LV624, LZ1, going through the tile currently being acided in the screenshot but presumably works anywhere with similar turf conditions. 
![image](https://user-images.githubusercontent.com/48527763/85206180-83378280-b320-11ea-820f-6b00518d83e1.png)

**Comment by MacBlaze1** [comment]
mapping error
