### ISSUE TITLE
Hivemind missing secrete resin button/ability

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4280]
## Testmerges:

#4273: 'Add crash nuke cinematic' by psykzz at commit 9307414251
#4266: 'Revert "Load shuttles in transit level"' by psykzz at commit 0f88776496
#4255: 'Stop xenos vent dragging marines past fog' by psykzz at commit 2c8adcc6b8
#4257: 'Fix orbit offsets' by psykzz at commit c7cc6442df
#4246: 'Reduce amount of extra SG slots' by XElectricX at commit 23779c7710
#4028: 'Fixes explosions happening at the same time as crash' by Rohesie at commit e626733fec
#4218: 'Map fixes for Sulaco and Pillar' by XElectricX at commit 53fa6b5a83
#4211: 'Buffs barricades ' by MacBlaze1 at commit dfffa6c9cf
#4235: 'Machine pistol now pistol sized, less ammo in mags' by XElectricX at commit f9f515396d
#4262: 'gives combat engineers proper engineering access' by MacBlaze1 at commit 2f9b48a6b0
#4260: 'Adds the T-70 grenade launcher ' by Pariah919 at commit c998caa37a
#4269: 'More balance changes to cargo orders, better stuff available to order' by XElectricX at commit 851e2ec349
#4275: 'Allow admins to find and orbit mindless mobs' by psykzz at commit ae76ef7fce
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit ec9c9069fe
#4272: 'New camera console' by psykzz at commit 9e750e7e88
#4271: '513.1526 is now stable' by spookydonut at commit fea6733297

## Reproduction:
Evolve into a hivemind, mature so that you should be able to select and place resin. Marvel as you are lacking the button to actually place it.

**Comment by Hughgent** [comment]
Please demonstrate with a screenshot or close this issue.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
