### ISSUE TITLE
Bypassing req elevator railing

### ISSUE THREAD

**Issue by AbsoluteJerry** [tgstation/TerraGov-Marine-Corps#4297]
## Reproduction:

Have someone throw you into the empty space over the railing, or you can aggressive grab (by the neck) and drag them over the railing to you.

**Comment by David-Stormwell** [comment]
This was a feature once, where if you where thrown into that space you would go into disposals, although that feature hasn't been maintained recently.

**Comment by BraveMole** [comment]
Feature
