### ISSUE TITLE
Able to repeatedly remove jaegar armor parts for negative armor and SUPER FAST MOVEMENT

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4299]
## Reproduction:

Apply armor to jaegar, spam crowbar it out while it's on the ground.
Marvel at your -300% armor and Sanic movement speed.

**Comment by ATH1909** [comment]
how fast is "Sanic movement speed"?

**Comment by MacBlaze1** [comment]
> how fast is "Sanic movement speed"?

woah ATH is here? Also yeah this is bad, -300 is bad when the armor is like heavy at 65 armor, medium and 50 or something and light at 40, heavy would be the most speed

**Comment by MacBlaze1** [comment]
confirmed real
