### ISSUE TITLE
Invisible Razorwire

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4300]
## Testmerges:

#4211: 'Buffs barricades ' by MacBlaze1 at commit dfffa6c9cf
#4218: 'Map fixes for Sulaco and Pillar' by XElectricX at commit 53fa6b5a83
#4269: 'More balance changes to cargo orders, better stuff available to order' by XElectricX at commit d680040e87
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit be962cc455
#4290: 'brings the construction skill in line with other time reducing skills' by MacBlaze1 at commit e0d21e5307

## Reproduction:

Multiple reports of razorwire, electrified and not, becoming invisible. Unsure of the cause.

**Comment by psykzz** [comment]
When this happens next can you check VV to see if the icon_state has changed

**Comment by David-Stormwell** [comment]
On a Prison round there was reports of invisible resin walls as well.

**Comment by Hughgent** [comment]
Please demonstrate with a screenshot or close this issue.
