### ISSUE TITLE
TGUI for req consoles show nothing on the list for orders

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#4314]
![image](https://user-images.githubusercontent.com/24631139/85650007-197bf780-b6d7-11ea-860e-f7f2e7c70841.png)

## Reproduction:

1. Walk up to the console
2. Use the console
3. See there's nothing in the order category
4. Profit

**Comment by spookydonut** [comment]
Your client hasn't loaded tgui properly, clear your cache and make sure assets are loading for you and your windows is up to date.
