### ISSUE TITLE
Xeno Healing rates while in crit

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4337]
## Testmerges:
#4308: 'Makes the M56D smartgun into a whole deployable item' by MacBlaze1 at commit 36124fb928
#4309: 'Add gesture based callouts for humans' by psykzz at commit 2f3ea272a7
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14
#4305: 'Experimental mob processing smoothing' by spookydonut at commit 07b900d728
#4301: 'Adds pill packets, and tricordazine pill packets to the first aid kit pouch.' by Pariah919 at commit 26df452f15
#4270: 'Adds directional slashing and removes bump slashing from xenomorphs' by MacBlaze1 at commit 71fe4460b8
#4328: 'Fixes instant take over of deleted xenos' by psykzz at commit 9e3b8448e6
#4327: 'Nerf T1 Xenos on crash' by psykzz at commit befa855825
#4269: 'More balance changes to cargo orders, better stuff available to order' by XElectricX at commit 70db303350

## Reproduction:

147[12:46:28] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 165, 2) (NEWHP: -67.9575) in North Caves (139, 165, 2)
146[12:46:28] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 165, 2) (NEWHP: -24.81) in North Caves (139, 165, 2)
145[12:46:28] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 165, 2) (NEWHP: -24.81) in North Caves (139, 165, 2)
144[12:46:28] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been attacked by InterroLouis/(Harry Cowper) with [T-18 carbine (Wielded)] (INTENT: HARM) (DAMTYE: BRUTE) (RAW DMG: 20) (NEWHP: -24.81) in North Caves (139, 165, 2)
143[12:46:22] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (141, 163, 2) (NEWHP: -19.5585) in North Caves (141, 163, 2)
142[12:46:22] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (141, 163, 2) (NEWHP: -19.5585) in North Caves (141, 163, 2)
141[12:46:16] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 163, 2) (NEWHP: -32.8585) in North Caves (139, 163, 2)
140[12:46:16] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 163, 2) (NEWHP: -14.953) in North Caves (139, 163, 2)
139[12:46:16] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 163, 2) (NEWHP: -0.310486) in North Caves (139, 163, 2)
138[12:46:15] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North Caves (139, 163, 2) (NEWHP: -0.310486) in North Caves (139, 163, 2)
137[12:46:14] ProbablyBilly/(Ancient Carrier (256)) (North Caves (139, 166, 2))
has been shot by InterroLouis/(Harry Cowper) with [rifle bullet] in North East Caves (143, 163, 2) (NEWHP: 15.975) in North East Caves (143, 163, 2)

Pretty sure the carrier was under healing pheromones, but still. Other xenos also seem to be healing far faster than they should.

**Comment by Hughgent** [comment]
This might be a combination of Healing and Warding working in tandem.

Please give us an update or close this issue.
