### ISSUE TITLE
Unable to use the new follow/orbit menu on larva

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4346]
## Testmerges:

#4269: 'More balance changes to cargo orders, better stuff available to order' by XElectricX at commit 70db303350
#4308: 'Makes the M56D smartgun into a whole deployable item' by MacBlaze1 at commit efd4636d12
#4309: 'Add gesture based callouts for humans' by psykzz at commit 2f3ea272a7
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14
#4305: 'Experimental mob processing smoothing' by spookydonut at commit 07b900d728
#4328: 'Fixes instant take over of deleted xenos' by psykzz at commit 9e3b8448e6
#4327: 'Nerf T1 Xenos on crash' by psykzz at commit befa855825
#4320: 'Fix shuttle bugs' by spookydonut at commit 2cdd70aefa

## Reproduction:

Open the follow menu, click on a larva, watch as you don't orbit them.

**Comment by Hughgent** [comment]
Please update this issue or close it.

**Comment by Hathkar** [comment]
Just re-tested this on the master commit.

Spawned in 4 larva, opened the follow menu as a ghost, clicked on all the larva.
Was unable to follow any of them, both when they were maturing and when fully matured.

If I had to guess, it would have something to do with larva names changing as they mature.
