### ISSUE TITLE
Being dead halts all larva progress. 

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#4379]
## Testmerges:
#4335 #4378 #4347 #3648 #4354 #4277 #4305 #4320 #4308 #4370 #4355

## Reproduction:
Kill a marine, then all of the larva progress is halted until he is revived.
Problem is that it encourages the meta of "Kill me until you can deal with the larva" which can be a bad habit.

**Comment by Pariah919** [comment]
If you want to solve this add more ways to slow larva progression or add stasis bags to the DS.

**Comment by psykzz** [comment]
> If you want to solve this add more ways to slow larva progression ~~or add stasis bags to the DS.~~

**Comment by Denthamos** [comment]
Its hardly a bad habit considering current larval progression and the amount of stuns xenos have at their disposals to keep marines contained until they burst, including even simple tackle spamming which stamina stuns.

**Comment by Hughgent** [comment]
if I am reading this right. Larva do process in 'dead' marines but not 'dead dead' marines.

```
	if(affected_mob.stat == DEAD)
		if(ishuman(affected_mob))
			var/mob/living/carbon/human/H = affected_mob
			if(check_tod(H)) //Can't be defibbed.
				var/mob/living/carbon/xenomorph/larva/L = locate() in affected_mob
				L?.initiate_burst(affected_mob)
				STOP_PROCESSING(SSobj, src)
				return FALSE
```
