### ISSUE TITLE
Pinpointers unable to locate disks while on recovery mode

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4391]
## Testmerges:

#4335: 'CPR the dead' by Rohesie at commit 2706262c38
#4354: 'Revert "513.1526 is now stable"' by MrStonedOne at commit 4f69d94d8f
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14
#4305: 'Experimental mob processing smoothing' by spookydonut at commit 07b900d728
#4320: 'Fix shuttle bugs' by spookydonut at commit 2cdd70aefa
#4376: 'Fixes damage multipliers not applying to additional projectiles ' by MacBlaze1 at commit b26ca94a5f
#4384: 'Adds the TL-84 pfc flamer, adds a marine flamer backpack and removes the outdated M240-T' by Pariah919 at commit 06dfd47e7f

## Reproduction:

Chosen target signal too weak. Choose another.

Get an advanced pinpointer, right click to change settings to Disk Recovery Mode. Tried to track all the disks, and none were detected

**Comment by Hughgent** [comment]
```
/obj/item/pinpointer/proc/set_target(mob/living/user)
	if(!length(tracked_list))
		to_chat(user, "<span class='warning'>No traceable signals found!</span>")
		return
	target = input("Select the item you wish to track.", "Pinpointer") as null|anything in tracked_list
	if(QDELETED(target))
		return
	var/turf/disk_loc = get_turf(src)
	if(target.z != disk_loc.z)
		to_chat(user, "<span class='warning'>Chosen target signal too weak. Choose another.</span>")
		target = null
		return
```

It appears that when you attempted to do this, there were no disks on your z level. 

Please replicate this issue or close it.
