### ISSUE TITLE
Some sacs on LO won't take melee damage.

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#4408]
## Testmerges:
#4401: 'Reduces the volume of the hmg by 10%' by psykzz at commit f415c9e44f
#4320: 'Fix shuttle bugs' by spookydonut at commit 2cdd70aefa
#4305: 'Experimental mob processing smoothing' by spookydonut at commit 07b900d728
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14
#4354: 'Revert "513.1526 is now stable"' by MrStonedOne at commit 4f69d94d8f
#4392: 'Adds a loooot more xeno wound sprites' by TiviPlus at commit cca56f66f0
#4406: 'Re-PR of xeno wounds' by TiviPlus at commit e4f44a4ecd

## Reproduction:
1. Hit some sacs.
2. Some appear to simply not take melee damage. Not sure why.

Round ID was 4176.

**Comment by davidchan13** [comment]
![bc09d957b50e570530609facb7bf1bd2](https://user-images.githubusercontent.com/12998418/86542212-4bf8d200-bed9-11ea-953c-70dbbd7da390.png)
Sacs, Eggs and nearly all Resin Objects from that round had unusually high resistance to melee and bullet damage. The above picture is one egg soaking 20+ shots. Walls were seemingly immune to damage as well, as I used over 100 rounds from a GPMG at point blank range and examined the wall, to see it was _SLIGHTLY_ damaged.

**Comment by Hathkar** [comment]
I went and dug up the logs for this round. Looks like a var edit of soft armor affected EVERYTHING instead of one object.

It's safe to close this.

**Comment by TiviPlus** [comment]
Adminbus wins again
