### ISSUE TITLE
Able to paint targets with binoculars through cameras

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4440]
## Testmerges:

#4412: 'Chat and RuneChat Preferences' by Rohesie at commit e923c84f07
#4416: 'Misc hard del fixes and cleanup' by Rohesie at commit bcc0eef4d1
#4305: 'Experimental mob processing smoothing' by spookydonut at commit 07b900d728
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14
#4406: 'Re-PR of xeno wounds' by TiviPlus at commit e4f44a4ecd
#4425: 'CM windows' by Rohesie at commit 2f8ce42724

## Reproduction:

Use an overwatch/camera console with binocs in your hand. Use them to paint OBs and railgun strikes. This works through normal cameras and armor mounted cameras.

**Comment by psykzz** [comment]
Fixes in #4453
