### ISSUE TITLE
Endless Bioscans from ARES

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4463]
## Testmerges:

https://github.com/tgstation/TerraGov-Marine-Corps//pull/4349

## Reproduction:

Ares did about 50 bioscans in a row, had to end the round to make it stop. No idea what caused it.
Round ID: 4236

**Comment by neohenry** [comment]
https://www.youtube.com/watch?v=EZFpE7e_58s

memes

**Comment by psykzz** [comment]
Fixes in #4485
