### ISSUE TITLE
Huggers not dying

### ISSUE THREAD

**Issue by psykzz** [tgstation/TerraGov-Marine-Corps#4477]
## Testmerges:

Round ID: 4256
BYOND Version: 513.1526
Server revision compiled on: 
Master commit: fcb2d1455936e316c578e410108701c73f8fcca4
The following pull requests are currently test merged:
#4450: 'Revolvers can now do tricks' by TiviPlus at commit a2d4829890
#4432: 'Mining drill rebalance' by Hathkar at commit 4590c59b6f
#4355: 'More Mining Drill Locations' by Hathkar at commit a5dbdc4202
#4349: 'Modular helmet binocs' by TiviPlus at commit 49302c5e18
#4344: 'Adds the mirage grenade' by TiviPlus at commit a3ace7af83
#4389: '(most) Shotguns can now not be fired without being wielded.' by Pariah919 at commit 5587180fa0
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14

## Reproduction:

Not sure, found them this way.

![image](https://user-images.githubusercontent.com/1134201/87235440-1752b200-c3d4-11ea-9a99-e0dfdd1c00f7.png)

**Comment by psykzz** [comment]
```
This is a alien. It is a tiny item.
It has some sort of a tube at the end of its tail.
The codex has relevant information available.
The alien seems to be asleep.
```

**Comment by TiviPlus** [comment]
Been happening for a while, happens when a carrier evolves or devolves, it should probably just delete the huggers instead of dropping

**Comment by TiviPlus** [comment]
No longer happens
