### ISSUE TITLE
Weed and xeno walls have very low contrast

### ISSUE THREAD

**Issue by collinlunn** [tgstation/TerraGov-Marine-Corps#4486]
When on the default xeno light setting, and in darkness, it is difficult to visually identify xeno walls that are on weeds. This can make it difficult for xenos to see well and strains the player's eye.

Example picture:
![cf1fa3b706ab1da85131b5254fc151bc](https://user-images.githubusercontent.com/60152240/87360225-e33bd600-c526-11ea-9ae3-fe3424358583.png)

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
