### ISSUE TITLE
Tarp overlook

### ISSUE THREAD

**Issue by namjay1170** [tgstation/TerraGov-Marine-Corps#4492]
![ede49d9050ebc5eecd329bbc1f991bc4](https://user-images.githubusercontent.com/22186889/87436213-9517e880-c5a1-11ea-9665-ba1f8ea86010.png)

a fix partially exists
https://github.com/tgstation/TerraGov-Marine-Corps/pull/4381
just needs tm

however its unknown if hivemind still uncovers you due to 
https://github.com/tgstation/TerraGov-Marine-Corps/pull/4326

**Comment by psykzz** [comment]
This is fixed in #4326
