### ISSUE TITLE
Mounted Smartguns Shoot Themselves

### ISSUE THREAD

**Issue by halitosisman** [tgstation/TerraGov-Marine-Corps#4499]
## Testmerges:

#3905 #4411 #4448 #4467 #4475 #4495 #4496 #4432 #4355

## Reproduction:

Deploy a mounted smartgun just behind or just in front of a barricade on the Sulaco and start firing it.

Every time it fires I saw a message saying the gun itself got hit by a bullet. Eventually the gun destroyed itself.

**Comment by psykzz** [comment]
This looked to be related to the tank pr #3905 
Tivi is aware.

**Comment by TiviPlus** [comment]
was resolved in 3905
