### ISSUE TITLE
Computer Barricades

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4506]
## Testmerges:

#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 8bd8fb214f
#4467: 'dropped code pixel shifted items will retain their pixel shifts' by Hughgent at commit e5f7f72b0c
#3905: 'Vehicle Framework [Review Ready]' by TiviPlus at commit e655a76523

## Reproduction:

Place a computer frame, add the circuit board to it. Enjoy your acid-proof barricade.

**Comment by Hughgent** [comment]
Unable to replicate. I am able to 'walk through' this incomplete computer frame.

**Comment by Hathkar** [comment]
Let me be more clear.
All ``obj/machinery/computer`` are acid proof.
A few of those are also indestructible, and able to be deconstructed and moved around.
The ones I found were immune to all damage are 

- shuttle
- marine_card
- squad_changer
- intel_computer
- cryopod

Out of those, the ones that can be deconstructed/moved around are

- cryopod
- intel_computer
- marine_card
