### ISSUE TITLE
Shuttle Turrets are not firing anything

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#4526]
## Testmerges:
 #4523 #4524 #4498 #4510 #4515 #4487 #4467 #3905 #4520

## Reproduction:
Let a Canterbury **or Alamo dropship** turret fire at a xeno, no projectile will fire out of it.

**Comment by XSlayer300** [comment]
Seen the Alamo's dropship turrets firing blanks.

**Comment by Hughgent** [comment]
Out of curiosity, at what point in the round was this blank firing happening? How much time had elapsed?

**Comment by XSlayer300** [comment]
Somewhere during the 13:00 mark, during that round the marines are evacuating. Atleast that is what I saw so far.

**Comment by Hughgent** [comment]
I saw another report about this on the discord, was that also around this point in the round?

Reason being is that these things have an internal battery of 20000 and they just might run out.

**Comment by Hughgent** [comment]
@TiviPlus If you would be so kind, your PR about the tanks #3905 is doing `generate_bullet()` in a weird way. Please investigate if turrets are broken after your tank fires some rounds.

**Comment by InterroLouis** [comment]
@Hughgent They'd fixed it already but the PR hadn't been updated on the TM. Also I tested if turrets break after the tank fires some rounds, and they don't. It was entirely because of the lack of update from the point where sentries were broken to the point where they were fixed.

**Comment by psykzz** [comment]
This is fixed in #3905
