### ISSUE TITLE
MarineMed Doesn't Vend Imidazoline Pill Bottles

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4527]
## Testmerges:

#4520: 'Fix xeno deathtimers' by psykzz at commit f7d5b86bcd
#3905: 'Vehicle Framework [Review Ready]' by TiviPlus at commit c6d880b899
#4467: 'dropped code pixel shifted items will retain their pixel shifts' by Hughgent at commit e5f7f72b0c
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 66f8ddcaef
#4515: 'Shipside Skills Update' by David-Stormwell at commit 1a2f01321b
#4510: 'Nerfs the DMR/BR/SNIPER damage. Nerfs BR/Bolt action rifle damage' by Pariah919 at commit ade104dae4
#4498: 'Ff' by Pariah919 at commit 446960134c
#4524: 'New Defender ability: Regenerate skin' by psykzz at commit 8e047e2438
#4523: 'Add new Rav ability: Ignore Pain' by psykzz at commit ab9b88d0e8
#4518: 'Creates new entrances into self destruct on sulaco' by psykzz at commit cc137b6b66

## Reproduction:

Go up to a MarineMed, click Imidazoline pill bottle, watch as the count decreases by one, but vends nothing.

**Comment by psykzz** [comment]
![image](https://user-images.githubusercontent.com/1134201/87860117-ad399000-c932-11ea-98f7-db1a21adb171.png)

We have some serious corruption going on...?

**Comment by psykzz** [comment]
It even has mob verbs 

![image](https://user-images.githubusercontent.com/1134201/87860132-d6f2b700-c932-11ea-9536-40cb2cbb8dc8.png)

**Comment by psykzz** [comment]
I think this was a one time issue with some data corruption going on.

**Comment by psykzz** [comment]
![image](https://user-images.githubusercontent.com/1134201/87985243-2bcd3380-cad3-11ea-9e36-cee087b05291.png)
