### ISSUE TITLE
Stacking multiple cades in one spot using the fob drone

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#4543]
## Testmerges:
#4511 #4503 #4501 #4533 #4528 #4530 #4522 #3905 #4467 #4487 #4524 #4523 #4518 #4531 #4519

## Reproduction:

1. Go to a fob drone pick any LZ
2. Spam click the build cade option metal and/or plasteel
3. Multiple metal/plasteel cade in one tile
(May work with turrets if anyone cares enough to ask another engineer with em to buy two sentry vouchers and place them in one spot)

**Comment by MacBlaze1** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/blob/4ba637a15a946541b73e65aaffb88f73110e42b3/code/modules/mining/remote_fob/remote_fob_actions_misc.dm guess what someone forgot to add, a busy check
