### ISSUE TITLE
Crew Manifest errors

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#455]
## Testmerges:

#426 #443 #442 #440 #439 #438 #437 #435 #434 #433 #432 #429 #422 #419 #368 #367 #446 #451 #448 #219

## Reproduction:

![o4url3h](https://user-images.githubusercontent.com/42041276/52030441-0d4e3380-24ff-11e9-93f5-99287889dfe1.png)

**Comment by DominikPanic** [comment]
RA sure is fun. This is intented but I realize how fucking terrible this is so I'll fix it.
