### ISSUE TITLE
Take Over mob missing from right click menu and player panel

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4559]
## Testmerges:

#4511: 'readds armor variance, does FF changes' by Pariah919 at commit 8915d52088
#4501: 'Flamer Nerf (Take 2 and softer)' by mrhugo13 at commit 9fc83a1295
#4533: '88mod no longer has a damage mukt, nerfed pistol armor piercing pen, slightly higher fire delay on 88mod' by Pariah919 at commit c9a05fe7e8
#4530: 'Add bump slash tracking vs normal attacks' by psykzz at commit d14f4b769d
#4522: 'adds the ts-34 double barrel shotgun, replacing the one marines get in the req vendor ((NOT PFC))' by Pariah919 at commit f40dae8f05
#3905: 'Vehicle Framework [Review Ready]' by TiviPlus at commit edb7b0c9d5

## Reproduction:

See title.

**Comment by rhomm-dev** [comment]
was wondering about this one too, but it is intentional, see changelog (can now just mouse drag ghosts onto mobs)

2020-07-20:
spookydonut:
  - admin: replaced take over mob verb with drag ghost to mob to change ckeys
  - admin: improved spawn verb

**Comment by Hathkar** [comment]
Ehhhh, I liked having the option in the menus.
With the new system I have to ghost over to the mob instead of right click or PP from across the map.

**Comment by spookydonut** [comment]
Drag your ghost onto the mob.

**Comment by Hathkar** [comment]
Or you can just leave us the right click option AND the ghost option. Sometimes it's faster to right click the mob if I'm already in a mob.
