### ISSUE TITLE
Instant respawn after hivemind death

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#4563]
## Testmerges:
 #3905, #4522, #4530, #4533, #4501, #4511, #4518, #4552, #4548, #4544, #4534, #4532

## Reproduction:
![image](https://user-images.githubusercontent.com/24631139/88178491-0ff59900-cc5d-11ea-869a-c923faa2cf1b.png)
 1. Be a hivemind
 2. Marine finds your core
 3. Deletes you for existing in this plane of existence
 4. Find that the respawn timer is off cool down already

**Comment by Hughgent** [comment]
@Surrealaser I believe you are intimately familiar with how hivemind works at this point. Is there any insight you could provide here?
