### ISSUE TITLE
Marine Stamina, and Disarm spam

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#4568]
In the last game, one xeno kept multiple marines down with disarm spam, without needing to use nests, just running back and forth over said multiple marines, keeping them in place until they burst.

I propose one of two things to occur, as personally, it makes me want to suicide if I become the larva.

One, have marines regen stamina at a progressively faster rate the more they're disarmed, they'll eventually get up.

Two, disarming marines now deals O2 damage if the marine has no stamina left, meaning that if you continuously disarm spam them, you will eventually just straight up kill them. After all, you are 'throttling' them, implying that you're choking them out.

Yes, this is a salt post, but it's a salt post that's gained salt over every round.

**Comment by Pariah919** [comment]
lmao

**Comment by neohenry** [comment]
I was the Shrike at that round that used infinite tackles to ensure that xenos get the captured needed.

I used this to counter against marine's opportunity to sucidenade. If you want to suicide as a larva, then that's reportable.

**Comment by jroinc** [comment]
Get fucked?

One- Marines gain stamina much faster if they're damaged. 20 stamina/tick below "50" stamina, 4/tick above. HOWEVER, to actually allow marines to be disabled, there's a 3-second C/D before you regen stamina after taking stamina damage. That was put in place after marines physically could not be disarmed by T1's no matter what.

Yes, you can be permacrit by an ayy taking 5 minutes of it's time. You lost when they first stamcrit you and dragged you off, sorry but you're dead. How they kill you is up to them.

Two- No. Capturing is an essential mechanic currently, even if it makes marines sad. Remove capturing and we can see what we can do to remove larva (but then you'll just be dead so yeah).

**Comment by davidchan13** [comment]
Until xenos have a way to reliably prevent suicide nading, this is going to be the meta because nests are so shitty. Stasis bags are better at containing marines since they stun the marine upon resisting out of them, where as nests let a marine pull out a rifle/nade the second they unnest and go rambo. And since marines killing themselves can kill the larva, tackle spamming is vital to ensure they get something of value out of the time they spent capturing.
