### ISSUE TITLE
Req console in Sulaco is not responding

### ISSUE THREAD

**Issue by neohenry** [tgstation/TerraGov-Marine-Corps#4594]
## Testmerges:

#4540  
#4511 
#3905 
#4551 
#4561 
#4583 
#4582 

Req supply drop console PR

## Reproduction:

![image](https://user-images.githubusercontent.com/6610922/88472233-7ed52b00-cec5-11ea-8feb-60017a280740.png)

Cannot use "Launch supply drop" even when beacon is active.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
