### ISSUE TITLE
Cannot Place Mortars

### ISSUE THREAD

**Issue by halitosisman** [tgstation/TerraGov-Marine-Corps#4662]
## Testmerges:

#4658 #4660 #4661 #4645 #4616 #4618 #4652

## Reproduction:

Try to place a mortar in LZ1 on LV624. Get a message saying that you can't place the mortar here.

**Comment by TiviPlus** [comment]
Where was this? Some areas disallow mortars

**Comment by halitosisman** [comment]
![spot](https://user-images.githubusercontent.com/35907379/89719921-cd3cfc00-d992-11ea-9303-867e14b2b8d6.png)

**Comment by Hathkar** [comment]
Unable to reproduce.

https://i.imgur.com/pVACky8.png
