### ISSUE TITLE
Crushers can unreliably instabreak r-walls exactly 15 tiles charging into it

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#4674]
## Testmerges:
#4652 #4616 #4660 #4658 #4664

## Reproduction:
1.Get an R-wall
2.Line up 15 tiles away from it
3.Charge right in (you will roar just before hitting the wall)
4.Unreliably kills the r-wall instantly

Because Github doesn't support MOV files like discord does i'll just link the discord post for the video i made
https://discordapp.com/channels/498569646014857217/500801682058379265/742191972856627220

**Comment by Hughgent** [comment]
r-walls are not truly invincible
