### ISSUE TITLE
Buckle Code making people unstunnable

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4686]
## Reproduction:

Buckle yourself to a chair. Get stunned while buckled, and then have the buckled object get destroyed. You'll be standing upright, unable to be knocked down or nested. I've also seen people being able to shoot and use items while "stunned".

**Comment by Hughgent** [comment]
@TiviPlus 
```
/atom/movable/proc/unbuckle_mob(mob/living/buckled_mob, force = FALSE)
	if(!isliving(buckled_mob) || buckled_mob.buckled != src || (!(buckle_flags & CAN_BUCKLE) && !force))
		return
	. = buckled_mob
	buckled_mob.buckled = null
	buckled_mob.glide_modifier_flags &= ~GLIDE_MOD_BUCKLED
	buckled_mob.reset_glide_size()
	buckled_mob.anchored = initial(buckled_mob.anchored)
	if(buckle_lying != -1)
		REMOVE_TRAIT(buckled_mob, TRAIT_FLOORED, BUCKLE_TRAIT)
	buckled_mob.clear_alert("buckled")
	LAZYREMOVE(buckled_mobs, buckled_mob)

	UnregisterSignal(buckled_mob, COMSIG_LIVING_DO_RESIST)
	SEND_SIGNAL(src, COMSIG_MOVABLE_UNBUCKLE, buckled_mob, force)
	post_unbuckle_mob(.)
```
This might be more up your alley. This proc gets called for every buckled mob whenever an `atom/moveable` gets `destroy()`

The `REMOVE_TRAIT` line might be causing the issue here but I am not sure.

Your thoughts?

**Comment by Hathkar** [comment]
Looks like it. I did some some testing.
If you destroy the buckled object after stunning the person, they're stuck upright.
