### ISSUE TITLE
Invisible Razorwire when damaged

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4688]
## Reproduction:

Razorwire has been going invisible when close to breaking. I've had difficulty reproducing it in the Thunderdome, but it has happened multiple times during a round.
Happened to both regular and shocked razorwire.

https://i.imgur.com/t0Ms0Vd.png

**Comment by TiviPlus** [comment]
Please check icon and icon_state vars next time this happens

**Comment by Hughgent** [comment]
Update please
