### ISSUE TITLE
Action Bar button deleting entire Action Bar

### ISSUE THREAD

**Issue by Chaznoodles** [tgstation/TerraGov-Marine-Corps#4690]
## Testmerges: 

#4664 #4658 #4652 #4673 #4680. Unlikely to be caused by any of these.

## Reproduction: 

N/A, happens at random across the board to everyone on the server.

During a round, a random button appears on your action bar at the top of your HUD. This doesn't seem to be drawn for anything in particular. Sometimes, it's a mob, sometimes it's something else, sometimes it's an object. If this is pressed, it deletes your entire action bar and, unless you're a xenos and evolve/devolve, it doesn't return.

This has happened repeatedly, and if you search for me saying "Pressing the backpack 'toggle' deletes your entire action bar" on Discord, you'll find three specific occurrences with images over the last month or so (the ones that I've been online to mention).

![image](https://user-images.githubusercontent.com/44979174/90075123-964d4a00-dcf4-11ea-81cb-7584ff586c3b.png)

![image](https://user-images.githubusercontent.com/44979174/90075144-a107df00-dcf4-11ea-94ff-9459dfc82ec5.png)

![image](https://user-images.githubusercontent.com/44979174/90075189-b977f980-dcf4-11ea-8795-22e0d9ee02fa.png)

![image](https://user-images.githubusercontent.com/44979174/90075222-ca286f80-dcf4-11ea-8b10-665eed79a4a1.png)

**Comment by TiviPlus** [comment]
This also happens spuriously on tg, likely a asset or byond issue

**Comment by Chaznoodles** [comment]
![image](https://user-images.githubusercontent.com/44979174/95791146-a378bc00-0cd8-11eb-9c89-9d1d12d13f91.png)

It's back again.
