### ISSUE TITLE
No Voting for Crash after 30 pop

### ISSUE THREAD

**Issue by neohenry** [tgstation/TerraGov-Marine-Corps#4708]
Crash is bad in high pop. Crash kills pop after people realize that camping in the ship is bad.

People don't know that voting for Crash in high pop is bad, and yet they still vote.

![image](https://user-images.githubusercontent.com/6610922/90568088-0f6af800-e160-11ea-9250-c3cc1170804b.png)

**Comment by Texicos** [comment]
you are wrong, had a 50~ man crash game and xenos got pushed past green and blue, but stopped their escape from blue having solid play from both sides, ending in the remaining few marines leaving.

**Comment by davidchan13** [comment]
I can argue Ice, Ice Caves, Lava and Magmoor all kill pop as much if not more than crash, yet we aren't preventing people from trying those.
