### ISSUE TITLE
Tanks Minigun not reaching downed Xenos even from further distance.

### ISSUE THREAD

**Issue by Urthrem** [tgstation/TerraGov-Marine-Corps#472]
Tanks Minigun main cannon becomes useless the moment you down the xeno, making it a requirement to fire a potentially dangerous TOW or any damage dealing secondary weapon on the xeno in order to finish it off which is a bit redundant.

## Reproduction:

Shoot or stun xeno with a tank and attempt to continue to spray them with bullets, all will just fire around them.

**Comment by MoXuT0** [comment]
Same thing happens with secondary smartgun, you can’t shoot downed xenos at all.

**Comment by MoXuT0** [comment]
Pretty sure it's not ghommie's fault cuz it was seen on cm even before the leak.

**Comment by DominikPanic** [comment]
Yes but he's reworking how the tank works so I'm pointing it out to him.

**Comment by DominikPanic** [comment]
Fixed
