### ISSUE TITLE
Xeno hivemind builder can build on shuttle with no resin nearby

### ISSUE THREAD

**Issue by Denthamos** [tgstation/TerraGov-Marine-Corps#4761]
The hivemind was constantly building on the alamo shuttle while it was planetside, however no resin/weeds were visibly shown while it was planetside.  This led to it constantly walling off the shuttle, planting resin nodes, and more and marines could do nothing about it.  The hivemind seemed to be permanently in the shuttle cockpit.
## Reproduction:

The hivemind did a quick push with resin nodes and resin walls torwards the shuttle.  When it got inside the shuttle and spread resin in it, after all resin was removed it kept spreading from underneath the shuttle cockpit console area as if there was a node in the shuttle wall up there.

**Comment by Hughgent** [comment]
fixed.
