### ISSUE TITLE
Alamo crashing on mainship deletes walls

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4771]
## Testmerges:

#4729: 'Modular Mapping' by TiviPlus at commit f91172fb0b
#4763: 'buffs GL firespeed, reduces movepeed' by RenGusta at commit fe59f15c1d
#4707: 'Orbital drop pods' by TiviPlus at commit e43e710300
#4727: 'Buffs Incendiary OB fire into the same as X Fuel (Blue Fire)' by 2whatever2 at commit abdef4c5cb
#4663: 'Use unrelenting force via keybind instead of just selecting' by psykzz at commit 614c58fc09
#4647: 'Headphones' by TiviPlus at commit 6301166081
#4740: 'PSG Auto Sniper' by David-Stormwell at commit e08e6dcad5
#3909: 'Revised cloning' by psykzz at commit 73f2eae32f
#4700: 'Synth Rebalance' by Hathkar at commit 6e29cc1f89

## Reproduction:

The Alamo has consistently been deleting walls, including indestructible walls, when crashing.
https://i.imgur.com/rnPh4am.png

**Comment by TiviPlus** [comment]
Fixed since to only be to the left/right
