### ISSUE TITLE
Still get infected even when taking facehugger out of marine's face

### ISSUE THREAD

**Issue by neohenry** [tgstation/TerraGov-Marine-Corps#4782]
## Testmerges:
#4729 #4763 #4727 #4647 #4740 #4700 #4707

## Reproduction:
1) Be marine
2) Get facehugged
3) Have a fellow marine nearby you to take facehugger out of you
4) phew
5) you still shake
6) ????
7) go to doctor
8) doctor confirms that you have baby

HenriqueKill9576 confirmed it with me.

**Comment by TiviPlus** [comment]
I saw this work properly earlier, consistency issue

**Comment by XSlayer300** [comment]
Happened to me as well, results on the analyzer says "foreign objects" inside one's body instead of having a unique message saying that one is infected.

**Comment by TiviPlus** [comment]
Foreign object inside body is as intended

**Comment by Hughgent** [comment]
hugging is gone, so to speak.
