### ISSUE TITLE
Valkyrie module effects exosuit when removed

### ISSUE THREAD

**Issue by GLACoding** [tgstation/TerraGov-Marine-Corps#4784]
## Testmerges:

#4729: 'Modular Mapping' by TiviPlus at commit f91172fb0b
#4763: 'buffs GL firespeed, reduces movepeed' by RenGusta at commit fe59f15c1d
#4727: 'Buffs Incendiary OB fire into the same as X Fuel (Blue Fire)' by 2whatever2 at commit 20b88f3524
#4647: 'Headphones' by TiviPlus at commit 6301166081
#4740: 'PSG Auto Sniper' by David-Stormwell at commit e08e6dcad5
#4700: 'Synth Rebalance' by Hathkar at commit 6e29cc1f89
#4707: 'Orbital drop pods' by TiviPlus at commit ade0a1ca6d
#4634: 'Tesla gun thing' by TiviPlus at commit 33b7588d38

## Reproduction:

1. Attach valk module at start of the round
2. remove valk and attach baldurs later
3. exosuit still stabilises fractured chest

**Comment by Hughgent** [comment]
Element is not being removed from the armor upon Valkyrie detach. Hell if I know why.
