### ISSUE TITLE
Chestburster Progression freezes after death while infected

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#4785]
## Testmerges:
#4729 #4763 #4727 #4647 #4740 #4700 #4707 #4634

## Reproduction:

1. Be infected (but not during the stage where the larva is already popping out).
2. Get gunned down by another marine of your own accord.
3. Be revived.
4. You cannot chestburst anymore.

**Comment by Hughgent** [comment]
hugging is gone, so to speak
