### ISSUE TITLE
Interface buttons only respond when the mouse button is being let go of, instead of when it's being clicked on.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#4790]
## Reproduction: Click on the interface button and drag out of it, letting go after your mouse is no longer on the interface button. The button wont activate. Click and hold down the button and it wont activate, either.
![dreamseeker_9RV4aU9sbi](https://user-images.githubusercontent.com/22848292/92488189-37c4a000-f1bc-11ea-9b66-b523a7cbd1e9.png)

It may also be a problem because there is a small delay after letting go where it tells the button it let go.
This may also just be a byond problem.

**Comment by Hughgent** [comment]
This is the desired mode of operation with buttons. It allows you to have those 'second guess' moments where you have clicked something, then decided you didn't want to click it.

**Comment by MiniMeatwad** [comment]
The problem is that it has a small delay after clicking. I understand if you drag your mouse off it and then let go, but having to hold your mouse over it to wait for it to register makes it annoying.
