### ISSUE TITLE
Decapped through helmet

### ISSUE THREAD

**Issue by Texicos** [tgstation/TerraGov-Marine-Corps#4794]
## Testmerges:
#4763: 'buffs GL firespeed, reduces movepeed' by RenGusta at commit fe59f15c1d
#4727: 'Buffs Incendiary OB fire into the same as X Fuel (Blue Fire)' by 2whatever2 at commit 20b88f3524
#4647: 'Headphones' by TiviPlus at commit 6301166081
#4740: 'PSG Auto Sniper' by David-Stormwell at commit e08e6dcad5
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8

## Reproduction:
https://gyazo.com/5ba90b2e6f0da8180bacb0a144626606
Crusher stomp decapped this man through a helmet.

**Comment by Hughgent** [comment]
Please do keep an eye out for this happening a second time. Code diving doesn't seem to bring anything up that says this should happen.

**Comment by TiviPlus** [comment]
No new instances, closing
