### ISSUE TITLE
Able to evolve from a larva to tier 3/ Speeds up evo faster than normal

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#4796]
## Testmerges:
#4783 #4763 #4727 #4740 #4487 #4786

## Reproduction:
1. Evo into any caste
2. Open up the menu for your next evo
3. Regress into a larva
4. Evo from a larva to a tier 2 without waiting 120 seconds
5. Repeat the last 4 steps to become a tier 3
Video Example:
https://discordapp.com/channels/498569646014857217/500801682058379265/753580513524187162

**Comment by Chaznoodles** [comment]
I think this might bypass tier evo restrictions too, unsure.
