### ISSUE TITLE
Xeno help intent movement error

### ISSUE THREAD

**Issue by Texicos** [tgstation/TerraGov-Marine-Corps#4798]
## Testmerges:
#4783: 'Makes regenning walls slightly less bad' by TiviPlus at commit 26438e455b
#4763: 'buffs GL firespeed, reduces movepeed' by RenGusta at commit fe59f15c1d
#4727: 'Buffs Incendiary OB fire into the same as X Fuel (Blue Fire)' by 2whatever2 at commit 20b88f3524
#4740: 'PSG Auto Sniper' by David-Stormwell at commit ef4d20f88f
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8
#4786: 'Burger's Attempt at a Xeno Regeneration Nerf' by BurgerLUA at commit 7971bf02f0

## Reproduction:
As xeno, have a marine stand one tile down and one tile to the left of a wall, then try to help intent past while standing directly next to the wall. You must be moving diagonally for the error to fire.

**Comment by Hughgent** [comment]
needs pictures
