### ISSUE TITLE
TGUI Char setup break on gear customization tab on char slot 4 and above

### ISSUE THREAD

**Issue by SplinterGP** [tgstation/TerraGov-Marine-Corps#4799]
## Reproduction:

You choose the fourth or fourth+ char slot in char setup and go into gear customization tab, it will give tgUI crash, first, second and third slot works fine

**Comment by TiviPlus** [comment]
@psykzz

**Comment by Strayed-Raven** [comment]
I have the same issue but with any char slot.
![NTOS Error](https://user-images.githubusercontent.com/43433046/94030120-772de780-fd8b-11ea-85cf-1fc87231349f.png)

**Comment by Strayed-Raven** [comment]
I have the same issue. But with any Char slot.
![NTOS Error](https://user-images.githubusercontent.com/43433046/94030242-96c51000-fd8b-11ea-861d-89d9366389f7.png)

**Comment by Hughgent** [comment]
Said PR is no longer, *trumpet taps
