### ISSUE TITLE
Fuel enhancers and cooling systems are just placebo.

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/TerraGov-Marine-Corps#4801]
## Testmerges:
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 5034
BYOND Version: 513.1528
Server revision compiled on: 
Master commit: 8d4f6b8acaa7596ee755b4975aeb97d0ee569420
The following pull requests are currently test merged:
#4783: 'Makes regenning walls slightly less bad' by TiviPlus at commit 26438e455b
#4763: 'buffs GL firespeed, reduces movepeed' by RenGusta at commit fe59f15c1d
#4727: 'Buffs Incendiary OB fire into the same as X Fuel (Blue Fire)' by 2whatever2 at commit 20b88f3524
#4740: 'PSG Auto Sniper' by David-Stormwell at commit ef4d20f88f
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8
#4786: 'Burger's Attempt at a Xeno Regeneration Nerf' by BurgerLUA at commit 7971bf02f0

Local commit: 2c7dac0c3377c3b82c89b1d00b8546a83d1a9006
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:
Fuel enhancers and cooling systems are supposed to reduce timers for the dropship cycles but they do nothing currently.
Try flying the dropship with and without them. It's the same timer.

**Comment by Eskjjlj** [comment]
The laser detector doesn't seem to be doing anything either.

**Comment by Hughgent** [comment]
To note, this is a `post` shuttle system change from CM. We updated the shuttle movement system and changed the travel times to the 'amount of time it takes to fly with both upgrades installed'

So yeah it's a placebo, but it's a vestigial system anyway.
