### ISSUE TITLE
Leaving your body makes it go DNR

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#4803]
## Testmerges:
#4786 #4487 #4740 #4727 #4763 #4783

## Reproduction:
1. Die
2. Leave body
3. Your body is listed as DNR via medhud
4. Stay in your body to keep it non-DNR

**Comment by TiviPlus** [comment]
I dont see why this should be happening, might have something to do with HUD updates?

**Comment by David-Stormwell** [comment]
This still seems to happen once in a while.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
