### ISSUE TITLE
TGUI prefs character preview inconsistent loading

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#4804]
## Testmerges:

#4786 #4487 #4740 #4727 #4763 #4783
## Reproduction:
Takes a while initially, but loads instantly when switching from one tab to another (even if switching just after the menu was just opened)

@psykzz

**Comment by psykzz** [comment]
Yeah i always knew this will be problem. I dont have a solution right now.
To properly fix it i'd need a byond windows hidden that loads the preview into so its ready when you show the tabs.

The reason it fails on first load is because its loads before the `byondUI` is available.

**Comment by TiviPlus** [comment]
Alright then, byond limitation I guess
