### ISSUE TITLE
Using field strip weapon can cause you to fire your gun

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#483]
Clicking on a menu button for field strip weapon causes your gun to fire if the safety isn't on. This can lead to accidental ff when someone attempts to strip their weapon.

**Comment by Rohesie** [comment]
This happens for all clickable menus, such as voting and whatnot.

**Comment by DominikPanic** [comment]
Yeah if you double-click to select something there's a very good chance you'll shoot.

**Comment by Rohesie** [comment]
No, it happens with single clicks carrying over. Try it with the vote, for example.

**Comment by DominikPanic** [comment]
There's no easy way to solve this without a major click refactor. Welp.

**Comment by DominikPanic** [comment]
TFW Not even /tg/ click code solves this. End my suffering.

**Comment by Rohesie** [comment]
Ooof, my bones.

**Comment by ondrej008** [comment]
@DominikPanic If there is a way to get the window position and size, you could just block all clicks from that area, until the window is gone.

**Comment by DominikPanic** [comment]
Not really possible to fix, closing this
