### ISSUE TITLE
Xeno death on alamo hijack gives way more burroweds than normal

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#4856]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 5145
BYOND Version: 513.1528
Server revision compiled on: 
Master commit: 177580ba38934d7bd96f786623f6462d55a60804
The following pull requests are currently test merged:
#4768: 'Adds a recoilless rifle, bag to carry the ammo and normal rockets' by Pariah919 at commit 049753a162
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8
#4762: 'Removes queen sweep.' by Pariah919 at commit 905ad9c027
#4747: 'Newlights' by TiviPlus at commit 96805f2d5e
#4830: 'Variety Update' by XSlayer300 at commit 70c5f7bf3b
#4845: 'Scalping fix' by TiviPlus at commit e5c20c4aa3

Local commit: f09f613cc6a281044ff7b5dd0c97b5194a0861bd
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

1. Launch the alamo as a xeno (hijack)
2. Have another xeno be outside of the alamo, making it die
3. Watch as instead of receiving one burrowed, you'll get way more (tested it last round, 1 died, 6 received)

**Comment by SplinterGP** [comment]
on the test did you ahve 6 xenos ?

**Comment by henriquekill9576** [comment]
More than 6, somewhere around 10
