### ISSUE TITLE
Theseus ship core S-52 fusion reactor visuals not updating properly

### ISSUE THREAD

**Issue by Auri3l** [tgstation/TerraGov-Marine-Corps#4871]
## Testmerges:
Current server version.

## Reproduction:
![image](https://user-images.githubusercontent.com/8057918/93940869-ec6ecd80-fd35-11ea-907f-6678084f729b.png)

The reactor does not show the fuel cell level when inserted and does not update properly when turned on or off.

**Comment by Hughgent** [comment]
Cannot replicate. please update or close this issue.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
