### ISSUE TITLE
Unable to Limit Squad Marine job slots

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4873]
## Testmerges:

#4835: 'Small explosions are now animated' by TiviPlus at commit c20db56717
#4833: 'Buffs buckshots damage/slowdown, reduces it back down to 1+2 projectiles' by Pariah919 at commit 80b0f28abe
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#4768: 'Adds a recoilless rifle, bag to carry the ammo and normal rockets' by Pariah919 at commit 049753a162
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8
#4762: 'Removes queen sweep.' by Pariah919 at commit 905ad9c027
#4830: 'Variety Update' by XSlayer300 at commit 70c5f7bf3b
#4845: 'Scalping fix' by TiviPlus at commit e5c20c4aa3

## Reproduction:

ADMIN LOG: Hathkar/(Lana Kusami) (?) (JMP) (FLW) has limited the Squad Marine job.
despite this, the job still stays at unlimited.
Removing ALL job slots doesn't change marine to limited either.

**Comment by Fikou** [comment]
you cant limit the overflow role. go to job subsystem ingame and change the overflow role to something else to limit it
(maybe works with null? idk)

**Comment by Hathkar** [comment]
I used to be able to easily limit/unlimit the job slots a few weeks ago.

**Comment by BraveMole** [comment]
feature
