### ISSUE TITLE
picking up a wrenched sentry creates an extra one

### ISSUE THREAD

**Issue by terranaut1** [tgstation/TerraGov-Marine-Corps#4876]
as title
reported by a player via ticket in round ID 5183

#4835: 'Small explosions are now animated' by TiviPlus at commit c20db56717
#4833: ' reduces buckshot back down to 1+2 projectiles halved damage falloff' by Pariah919 at commit 2b056cf362
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#4768: 'Adds a recoilless rifle, bag to carry the ammo and normal rockets' by Pariah919 at commit 12d695f36f
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8
#4762: 'Removes queen sweep.' by Pariah919 at commit 905ad9c027
#4845: 'Scalping fix' by TiviPlus at commit e5c20c4aa3
#4875: 'Fixes Magmoor Crash' by mrhugo13 at commit 91fe5ac209

```
proc name: MouseDrop (/obj/machinery/marine_turret/mini/MouseDrop)
usr: SpaceLove/(Edward Shann)
usr.loc: (Ore Refinery (37, 188, 2))
src: the UA-580 Point Defense Sentr... (/obj/machinery/marine_turret/mini)
src.loc: the floor (38,189,2) (/turf/open/floor/marking/loadingarea)
call stack:
the UA-580 Point Defense Sentr... (/obj/machinery/marine_turret/mini): MouseDrop(Edward Shann (/mob/living/carbon/human), the floor (38,189,2) (/turf/open/floor/marking/loadingarea), the plating (37,188,2) (/turf/open/floor/plating/warning), "mapwindow.map", "mapwindow.map", "icon-x=15;icon-y=9;left=1;scre...")
```
i believe this is relevant, additional runtime logs available on request

**Comment by Hughgent** [comment]
@SplinterGP hey, another one for you if you like

**Comment by SplinterGP** [comment]
hi

**Comment by Surrealaser** [comment]
Was trying to fix this today; could not duplicate

**Comment by Surrealaser** [comment]
@terranaut1 Post runtimes please
