### ISSUE TITLE
No Carrier deathrattle / Xeno HUD still says carrier is alive when you have facehuggers

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#4893]
## Testmerges:
#4762 #4487 #4679 #4833 #4835 #4843 #4852 #4860 #4863 #4864 #4869 #4872 #4880 #4882

## Reproduction:
When a carrier dies (confirmed by letting it bleed out), the xeno HUD of the carrier's corpse will not disappear. The deathrattle of the carrier is not mentioned as well.

**Comment by TiviPlus** [comment]
ive noticed this usually goes hand in hand with a failed to remove from hive runtime

**Comment by XSlayer300** [comment]
It only affects when you have facehuggers on.
