### ISSUE TITLE
PP spawned Humans cannot put on headsets

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#490]
## Testmerges:

Current Master - No TM's

## Reproduction:

1. Spawn as Doctor
2. Ghost
3. Fly to Charlie prep
4. open own PP and transform into Human
5. set rank "Squad Marine"
6. set squad "Charlie"
7. go to equipment vendor and vend out the standard kit.
8. marvel as to why you can't equip the headset to your ears, but it fits in your pockets.

Please note that this isn't high priority, spawning into the world as a squad marine normally does allow you to equip your headset.

**Comment by DominikPanic** [comment]
Oh yes I know why, thanks for reporting this. Problem is with the Change Squad spawning a headset on your ear instead of properly equipping it.

**Comment by DominikPanic** [comment]
Fixed in newest commit of #446
