### ISSUE TITLE
Placing people onto dropship alamo op table and them being underneath it

### ISSUE THREAD

**Issue by lukemac58** [tgstation/TerraGov-Marine-Corps#4907]
## Testmerges:

#4869 #4852 #4843 #4835 #4833 #4679 #4487 #4762 #4903

## Reproduction:

Placing people onto the dropship operating table can sometimes lead to them being underneath the sprite.

![unknown](https://user-images.githubusercontent.com/54242556/94352451-fe65ae80-005c-11eb-8a62-0de93527f296.png)

**Comment by TiviPlus** [comment]
This seems to be related to behaviour I've noticed concerning layer, where Marine layers will sometimes get moved down

Dunno the cause but very much worthy of investigation
