### ISSUE TITLE
We gotta refactor fire code, its a utterly big mess, this is just for rembering myself and to let anyone take if to do if they want.

### ISSUE THREAD

**Issue by SplinterGP** [tgstation/TerraGov-Marine-Corps#4919]
fire/flamer code is a huge mess, we need a refactor on that thing, day that this happens we'll be all happy as it won't be a shitty big mess from CM leftovers

**Comment by Hughgent** [comment]
Don't let your dreams be dreams

**Comment by XSlayer300** [comment]
Issue solved (I think) thanks to #5567

**Comment by SplinterGP** [comment]
> Issue solved (I think) thanks to #5567

not really, just reduces a few kekws from it, fire code is still bad

**Comment by BraveMole** [comment]
I'm closing this, this is useless
