### ISSUE TITLE
peridaxon not metabolising

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#492]
papi lakiller put a peri pill in me when my lungs were broken by a tank, and for the next while I always had 10u of peri in me according to handscanner. Other drugs were removed from blood over time normally.

Testmerged: #469 #468 #465 #447 #440 #439 #367 #446 #451 #464 #459 #453 #320 #474 #368 #426 #485 #482 #480

**Comment by DominikPanic** [comment]
@Surrealaser :whip:

**Comment by Surrealaser** [comment]
> @Surrealaser :whip:

Why is this my problem?

**Comment by DominikPanic** [comment]
You were the last to touch peri code

**Comment by DominikPanic** [comment]
Fixed in #500
