### ISSUE TITLE
Pipes not visible when ventrawling

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#493]
Seen this on multilple occasions. Shown is the view of a xeno in a pipe
![c9f9176ed4c5505c93a60cb2ee463062](https://user-images.githubusercontent.com/28164826/52158955-9bdbc580-2663-11e9-804b-50adbb9cf7fe.png)

**Comment by Rohesie** [comment]
Thought this was fixed. Looks like the pipes are having issues during initialization.

**Comment by DominikPanic** [comment]
Fixed in #699
