### ISSUE TITLE
Crash Xeno-Marine spawn ratio bug

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#4937]
## Reproduction: 
2 Admins and I observed and noticed that the Xenos somehow got more pop then Marines during a Crash lava outpost round without any captures.
From what it seemed, and what we speculated the Xeno count also counts permanently dead Marines, as in the end there was 9 Xenos and right after a Xeno would die a new burrowed would spawn even though the total count of alive Marines was in-fact 7+1 CMO.
If someone could look into this in that'd be good as this effects balance quite some.

**Comment by Hughgent** [comment]
being fixed
