### ISSUE TITLE
Crusher fog fling bug.

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#4942]
## Testmerges: 
#4270 #4892 #4747 #4762 #4487 #4679 #4833 #4835 #4843 #4852 #4869

## Reproduction:
As a Crusher you can fling a Marine into the fog thus trapping him forever or until you feel merciful and fling him out.

**Comment by Wayland-Smithy** [comment]
In my experience they just nade your silo and themselves to death.
