### ISSUE TITLE
Tactical Binoculars pulling up a list of marines when right clicked

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4946]
## Testmerges:

#4869: 'LV domes and hydro roads are now modularily mapped' by TiviPlus at commit 3ceb8f4faf
#4852: 'Overlay list fix port' by TiviPlus at commit 52f0cb6099
#4843: 'Plasteel cades can be linked/code cleanup' by TiviPlus at commit be0bd64653
#4835: 'Small explosions are now animated' by TiviPlus at commit c20db56717
#4833: ' reduces buckshot back down to 1+2 projectiles halved damage falloff' by Pariah919 at commit 2b056cf362
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 125f1116d8
#4762: 'Removes queen sweep.' by Pariah919 at commit 905ad9c027
#4747: 'Newlights' by TiviPlus at commit 873c306a51
#4892: 'New distant explosion sounds + ship creaking' by TiviPlus at commit 3873c9383e
#4270: 'Adds directional slashing and removes bump slashing from xenomorphs' by MacBlaze1 at commit 5a8d6fb229

## Reproduction:

Was unable to reproduce, but it kept happening to a person even when I spawned in a new pair of binocs.

**Comment by TheLordME** [comment]
Round ID: 5664
BYOND Version: 513.1534
Server revision compiled on: 
Master commit: 5413b1da9ba0bf43bd3099d70cfc5b515bde85b4
The following pull requests are currently test merged:
#5069: 'More experimental render shenanigans' by TiviPlus at commit f01ef00a34
#5060: 'hivemind can now whisper to people' by yeeyeh at commit 66682c85a8
#5054: 'Fixes an early return suppressing keybinding/up() - Shift examine stuck begone' by Wayland-Smithy at commit 42dd21d1e0
#4954: 'Cas Airplane' by TiviPlus at commit b9ccbd026b
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#5045: 'hivemind now has a 30 second cooldown on weeding' by Pariah919 at commit 7debcb914a
#5049: 'allows engineers to repair three separate barricades at a time, but only 1 repair at a time per barricade' by MacBlaze1 at commit f413e389c8
#5082: 'Refactors glass' by TiviPlus at commit 60ec455fc5

Local commit: 4053ae8c0ff1d7cd3865b7f202afb5918b591b69
Server tools version: /tg/station 13 Server v3.2.6.2

Had the described issue upon seeing more marines with binocs, I belief even a sentinel was among them in the list

**Comment by BraveMole** [comment]
never saw that, and no other reports for a year
