### ISSUE TITLE
You can break LZ shutters before they are dropped

### ISSUE THREAD

**Issue by Kuro-ai** [tgstation/TerraGov-Marine-Corps#4951]
##Testmerges:#4270 #4892 #4747 #4487 #4679 #4833 #4835 #4843 #4852 #4869

## Reproduction:

Pick up a high rate of fire weapon (gpmg is best for this) and concentrate fire on one tile of the shutter,it will break in less than one mag creating a hole in the shutters marines can go trough before its dropped.

**Comment by Hathkar** [comment]
That was just me deleting them to screw with the marines blasting them.

**Comment by TiviPlus** [comment]
Funny
