### ISSUE TITLE
No OB text warning, this either being removed or broken.

### ISSUE THREAD

**Issue by Texicos** [tgstation/TerraGov-Marine-Corps#4978]
## Testmerges:
#4858: 'Fixes defender crest and fortify, warrior on agility mode and warding aura pheromones not affecting xenos armor. and removes deprecated var and defines related.' by SplinterGP at commit d63c943ce5
#4270: 'Adds directional slashing ' by MacBlaze1 at commit aacf02d91a
#4892: 'New distant explosion sounds + ship creaking' by TiviPlus at commit 00af5d492d
#4747: 'Newlights' by TiviPlus at commit 17ea1f587e
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#4835: 'Small explosions are now animated' by TiviPlus at commit c20db56717
#4843: 'Plasteel cades can be linked/code cleanup' by TiviPlus at commit be0bd64653
#4852: 'Overlay list fix port' by TiviPlus at commit 52f0cb6099
#4869: 'LV domes and hydro roads are now modularily mapped' by TiviPlus at commit f26fbda53c
#4954: 'Cas Airplane' by TiviPlus at commit afe0d3876b
#3905: 'Vehicle Framework [Review Ready]' by TiviPlus at commit d2f01a1cc6
#4962: 'enables hunter animation sprite that was already in files' by SplinterGP at commit ab4a3a994c

## Reproduction:
fire a OB and stand in various positions and distances from the OBs center.

**Comment by Texicos** [comment]
Can't remember it being removed but it still shows up rarely, so I believe it to be broken.

**Comment by Hughgent** [comment]
There is no text message as far as I can tell.

```
/obj/structure/orbital_cannon/proc/fire_ob_cannon(turf/T, mob/user)
	set waitfor = 0

	if(ob_cannon_busy)
		return

	if(!chambered_tray || !loaded_tray || !tray || !tray.warhead)
		return

	flick("OBC_firing",src)

	ob_cannon_busy = TRUE

	playsound(loc, 'sound/weapons/guns/fire/tank_smokelauncher.ogg', 70, 1)
	playsound(loc, 'sound/weapons/guns/fire/pred_plasma_shot.ogg', 70, 1)

	var/inaccurate_fuel = 0

	switch(tray.warhead.warhead_kind)
		if("explosive")
			inaccurate_fuel = abs(GLOB.marine_main_ship?.ob_type_fuel_requirements[1] - tray.fuel_amt)
		if("incendiary")
			inaccurate_fuel = abs(GLOB.marine_main_ship?.ob_type_fuel_requirements[2] - tray.fuel_amt)
		if("cluster")
			inaccurate_fuel = abs(GLOB.marine_main_ship?.ob_type_fuel_requirements[3] - tray.fuel_amt)
		if("plasma")
			inaccurate_fuel = abs(GLOB.marine_main_ship?.ob_type_fuel_requirements[4] - tray.fuel_amt)

	var/turf/target = locate(T.x + inaccurate_fuel * pick(-1,1),T.y + inaccurate_fuel * pick(-1,1),T.z)
	for(var/i in hearers(WARHEAD_FALLING_SOUND_RANGE,target))
		var/mob/M = i
		M.playsound_local(target, 'sound/effects/OB_incoming.ogg', falloff = 2)

	notify_ghosts("<b>[user]</b> has just fired \the <b>[src]</b> !", source = T, action = NOTIFY_JUMP)

	addtimer(CALLBACK(src, /obj/structure/orbital_cannon.proc/impact_callback, target, inaccurate_fuel), WARHEAD_FLY_TIME)

```
There is a sound played, and ghosts get some text.

**Comment by Shadow-Quill** [comment]
Not a bug?
