### ISSUE TITLE
Burnt out Burnt Matches still emit light

### ISSUE THREAD

**Issue by ilikesaying** [tgstation/TerraGov-Marine-Corps#4989]
Burnt out matches keep emitting light even when they've burnt out
## Testmerges:

#4962 #4954 #4679 #4747 #4858 

## Reproduction:

take out matchstick, strike matchbox with matchstick to light matchstick, wait for matchstick to burn out or stuff matchstick into matchbox and then drop it on the floor

![match](https://user-images.githubusercontent.com/65475697/95655981-ddba5000-0b56-11eb-9775-b299c54b53e6.PNG)

**Comment by Hughgent** [comment]
@TiviPlus This seems like it's up your neck of the woods.

**Comment by TiviPlus** [comment]
fixed in newlights
