### ISSUE TITLE
Able to Build up Speed by Running Diagonally

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#4999]
## Testmerges:

#4813: 'Chem rework mk5, the unga strikes back' by jroinc at commit 6fac175bf8
#4954: 'Cas Airplane' by TiviPlus at commit 54b88e84c0
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#4747: 'Newlights' by TiviPlus at commit 17ea1f587e
#4858: 'Fixes defender crest and fortify, warrior on agility mode and warding aura pheromones not affecting xenos armor. and removes deprecated var and defines related.' by SplinterGP at commit d63c943ce5
#4965: 'Weeds speed up xenos rather than slowing down marines' by TiviPlus at commit 93e771fd0d
#4995: 'updates ship technician role to a bit more modern standards and gives some shipside roles paygrades' by MacBlaze1 at commit 909a15ce6b
#4993: 'Replaces the M41A1 with the M412' by Pariah919 at commit 1c80c16aaf

## Reproduction:

Be a hunter (Might work with other castes, didn't test). Run diagonally. Keep running diagonally, and you'll start to build up speed. Whenever you move after that, you'll keep moving super fast.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
