### ISSUE TITLE
 Admin music option doesn't work

### ISSUE THREAD

**Issue by Aurelien3189** [tgstation/TerraGov-Marine-Corps#501]
The admin volume option seems to vanish whenever one hovers their cursor over it. Unable to toggle volume of admin played music.

Reproduction:
https://gyazo.com/1b54da461460e0db3fbd196f0be7ed71

**Comment by DominikPanic** [comment]
CSS issue, fuck CSS, issues on smaller screens. @spookydonut save me.

**Comment by DominikPanic** [comment]
As a temporary fix you can set it yourself: VV > client > chatoutput > musicvolume
