### ISSUE TITLE
ARES bioscan does not include exact location of benos on the ship

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#5018]
## Testmerges:
#4993 #4965 #4747 #4679 #4954

## Reproduction:

- Wait for a bioscan report while benos are in the ship.

![image](https://user-images.githubusercontent.com/35091844/96058280-5d308200-0ebd-11eb-9cf5-94e7a8a65921.png)

It has to do somewhere on those lines.
![image](https://user-images.githubusercontent.com/35091844/96058376-979a1f00-0ebd-11eb-8002-31fa7da3f120.png)

**Comment by Hughgent** [comment]
It picked a xeno that wasn't in an area? maybe due to some admin shenanigans?

**Comment by TiviPlus** [comment]
Nullspace xeno?

**Comment by InterroLouis** [comment]
I thought this was intentional to make it so the bioscans wouldn't reveal xeno locations in the shipside phase and or not give away the location of an infiltrating xeno.

**Comment by BraveMole** [comment]
not reproduced
