### ISSUE TITLE
Synth's bodies don't get gibbed by the alamo, or synth's heads get deleted by the alamo when crushed.

### ISSUE THREAD

**Issue by AtlasRules** [tgstation/TerraGov-Marine-Corps#5022]
## Reproduction:
1. Be a synth.
2. Be put under the alamo landing pad
3. Get gibbed by the alamo.

Your body remains intact but your head, arms and limbs are qdeled. Either make the synth get properly gibbed or make the head not get deleted.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
