### ISSUE TITLE
Hive leaders don't lose hive status nor loses dead queen pheromones

### ISSUE THREAD

**Issue by SplinterGP** [tgstation/TerraGov-Marine-Corps#5040]
## Testmerges:
#4747 #4679 #4910

## Reproduction:
have a queen, assign leaders, have queen die, the leaders still have the dead queen pheros

**Comment by Wayland-Smithy** [comment]
Can confirm this. Sometimes the star on the xeno hud glitches out too.

**Comment by Hughgent** [comment]
old issue purge, make a new issue if this still persists.
