### ISSUE TITLE
Removing facehuggers still infects you 

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#5046]
## Testmerges:
#4747: 'Newlights' by TiviPlus at commit 17ea1f587e
#4679: 'Add buildable resin silos' by psykzz at commit 373a4d7fe0
#4910: 'Jelly will properly fully protect you from fire and more fixes' by TiviPlus at commit 5e9712eefb

## Reproduction:
1. facehug marine
2.remove alien
3. alien dies and the marine is infected it seems

**Comment by zerosexualpartners** [comment]
No. Just no.

**Comment by davidchan13** [comment]
The infection isn't supposed to happen until the Facehugger dies and falls off, or so we've been told.
Removing the facehugger immediately and stabbing the hugger while it's on the ground does not prevent the infection.
