### ISSUE TITLE
Shuffle hugging still exists

### ISSUE THREAD

**Issue by SilencedMP5A5** [tgstation/TerraGov-Marine-Corps#5065]
what it says on the tin

## Reproduction:
1.
play
2.
get shufflehugged and slashed to death or dragged off and camped
2.5 
be forced to cadehug because the second you push, 2 happens
3. 
leave because that shit is cancer as fuck

**Comment by Wayland-Smithy** [comment]
_laughs in xeno_
![4DJ3Wze8sy](https://user-images.githubusercontent.com/64715958/96917109-507fd100-145d-11eb-9a42-c0b7e3d51e37.gif)
Seriously though, I am looking making keeping direct hugger hits not count their victim as stepping on them if it was the result of a shuffle.

**Comment by Wayland-Smithy** [comment]
_laughs in xeno_
![4DJ3Wze8sy](https://user-images.githubusercontent.com/64715958/96917109-507fd100-145d-11eb-9a42-c0b7e3d51e37.gif)
Seriously though, I am looking into making direct hugger hits not count their victim as stepping on them if it was the result of a shuffle.

**Comment by AtlasRules** [comment]
can confirm this, i watched a carrier do it
