### ISSUE TITLE
Aliens cant hear midi's (uncertain I didnt have others confirm it)

### ISSUE THREAD

**Issue by Jalleo** [tgstation/TerraGov-Marine-Corps#508]
## Testmerges:
No idea it was in the first round on 2nd of Feburary 2019
## Reproduction:
Join as a xeno. Admin probably playing midi after round start....
Dont hear the midi......
This is likely linked to the report that you cannot hear the midi in the lobby as a new_player

These two are probably related. I dont know TGMC/Goonchat code that well.
#501
#502

**Comment by DominikPanic** [comment]
That's intended actually, that one was played for the marines only. (admins can choose if they want to play it to everyone, xenos or marines, plus all ghosts of course)

**Comment by DominikPanic** [comment]
Anyway I'll make it display only to relevant people in #518
