### ISSUE TITLE
Defender headbutt can jump over barricade corners

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#509]
Shown is a defender using headbutt on the human to jump over a barricade.
![189f118c33a73b99803e813ef009b770](https://user-images.githubusercontent.com/28164826/52170088-72757500-2709-11e9-8b87-2237efad8cc7.png)
![c755593c9760147ccc97bad1af11a88b](https://user-images.githubusercontent.com/28164826/52170089-73a6a200-2709-11e9-8e4e-df3512920f84.png)

**Comment by DominikPanic** [comment]
@Surrealaser

**Comment by DominikPanic** [comment]
@Rohesie Not sure how to go about this rather than snowflaking adjacent

**Comment by Rohesie** [comment]
This is a deeper problem than it looks, mostly from our snowflake non-fulltile barricades.

Long-term we'll want components and then using something similar to /tg/'s `throw_at()`, with our barricades accounted for.

Short-term this can be handled for headbutt specifically. Adjacency is checked later than `step_towards()` happens, and there already exists `handle_barriers()`
