### ISSUE TITLE
Vat-growns' hairs and beards dissappear when putting an face-covering.

### ISSUE THREAD

**Issue by Dimosek** [tgstation/TerraGov-Marine-Corps#5126]

**Comment by Hughgent** [comment]
Coif
`flags_inv_hide = HIDEEARS|HIDEFACE|HIDEALLHAIR`
other coif
`flags_inv_hide = HIDEALLHAIR|HIDEEARS`
bandanna
`flags_inv_hide = HIDEFACE|HIDELOWHAIR`
