### ISSUE TITLE
Bloody boots cover the knife sprite

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#514]
The blood overlay on bloodied boots prevents you from telling if you have a knife stashed in there.

**Comment by DominikPanic** [comment]
@Arachnidnexus

**Comment by Ghommie** [comment]
The boot knife should be made into a separate overlay, which applies above the blood one.

**Comment by DominikPanic** [comment]
This ain't an easy one to solve since all items share the same "base" blood overlay (icons/effects/blood.dmi, itemblood) that just gets multiplied on the item itself. The problem is that on this particular type of shoe it is exactly over the place where the knife is.
@Arachnidnexus
