### ISSUE TITLE
Activating shield no drop and placing on your back makes it unremovable

### ISSUE THREAD

**Issue by SylvinSeik** [tgstation/TerraGov-Marine-Corps#5148]
## Testmerges:
#5083 #5124 #5111 #5049 #5141 #5089 #5144 

## Reproduction:
Alt click shield and activate no drop, put on back, cannot remove shield from back

**Comment by TiviPlus** [comment]
They shouldnt be puttable on the back in the first place

**Comment by adamkad1** [comment]
Back shields funny though

**Comment by Surrealaser** [comment]
Fixed here: https://github.com/tgstation/TerraGov-Marine-Corps/pull/5248
