### ISSUE TITLE
Underslug miniflamer attachment has almost no cooldown.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/TerraGov-Marine-Corps#5160]
Title, underslug miniflamers on guns have effectively no cooldown.

## Reproduction:

- Attach a miniflamer to your weapon ~~of choice~~ that has burst/auto (shotgun rate of fire apperantly adds a cooldown)
- Enable miniflamer and fire as much as you'd like until you run out of fuel
- Melt xenos with direct DPS because you can hit them repeatedly with fire (use an autoclicker for best results)

Outclasses actual flamethrowers at the cost of maybe some fuel capacity and special flamer canister types while letting you punish close combat xenos heavilly with fire so you can gun them down with bullets when they flee.

Testing against several ancient castes:
https://i.imgur.com/9IZtJ5f.mp4
Note the damage on the miniflamer alone, now combine that with bullet damage after and you have incredible kill potential.

>Dolth

Update: Miniflamer cooldown is apperantly tied to the rate of fire on the gun or something.

**Comment by Wayland-Smithy** [comment]
It also seems to work through walls directly adjacent too, nice.
