### ISSUE TITLE
LV jungle tree prevents interacting with any objects under it in a 3x3 area

### ISSUE THREAD

**Issue by Wayland-Smithy** [tgstation/TerraGov-Marine-Corps#5182]
## Testmerges:

N/A

## Reproduction:

1. Locate this crate behind the tree near the west LZ on LV
2. Proceed to not be able to interact with it via Left-click, Right-click, or even Alt-Click, all are overridden by the `jungle tree` and as you can see even on the most far away part of the 3x3 the status bar still reads as hovering the tree. Pain.

![6F4RwlIUl3](https://user-images.githubusercontent.com/64715958/98408701-79d85980-2026-11eb-8bd2-a3f19bd46cd7.png)
Note the cursor hovering over the crate far from the tree and what is says in the status bar at the bottom.

**Comment by SplinterGP** [comment]
tree sprote pain

**Comment by BraveMole** [comment]
PR soon fixing
