### ISSUE TITLE
Ship recycler and conveyors do nothing

### ISSUE THREAD

**Issue by Havaren** [tgstation/TerraGov-Marine-Corps#5184]
## Reproduction:

each ship has a set of conveyors and a recycler. The conveyors seem to not function at all and the recycler also does nothing. It would be nice if it worked, giving the unga a reason to actually throw things in the disposals, or even giving the ST's something else to do.

**Comment by Hughgent** [comment]
@TiviPlus what happened with your conveyor refactor?

**Comment by TiviPlus** [comment]
Staled because you didnt merge it
