### ISSUE TITLE
point blanking appeares to give you perfect accuracy

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#5189]
## Testmerges:
On my local. With a one handed shotgun and shotgun in general and a mob with negative accuracy.

## Reproduction:
1.Grab any gun and reduce the accuracy by a lot, you'll miss a ton of shots
2. Shoot anything at point blank a ton
3. You won't miss a shot.

Ideally point blanking would just give you a small boost of 10% to hit. As you are literally right in front of them and shooting them directly. But hitting every shot all the time is just dumb. May not be a bug. But it shouldn't be how it works.

**Comment by Pariah919** [comment]
https://streamable.com/uxhx3x

**Comment by adamkad1** [comment]
I dont know man, clicking something is harder than clicking their general direction, expecially if the clicked thing often moves very fast. And i imagine the marines just ram their gun into the xeno and fire, and you go miss while you got a gun right into somethings body

**Comment by TiviPlus** [comment]
This was always the intent of PB?
Feature
