### ISSUE TITLE
Weapons tab shows while ghosted

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#519]
## Testmerges:
M56D

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52171726-f7e13f80-2772-11e9-88cf-fb07a79686a6.png)

**Comment by Ghommie** [comment]
Yea, we should remember set the objects verbs to only show up to players that technically can use those functions. Good find.

**Comment by DominikPanic** [comment]
Not sure how to fix this tbh, `set src = operator` or `set src in operator` is not working.

**Comment by Ghommie** [comment]
It has to be converted into a proc with `mob/living/carbon/operator in mob_example_list(range)` as arg, in which `mob_example_list` returns a list of those dextrous enough to use it, Then add the proc to the object verbs when initialized.
