### ISSUE TITLE
Able to become permanently invisible as hunter

### ISSUE THREAD

**Issue by Hathkar** [tgstation/TerraGov-Marine-Corps#5204]
## Reproduction:
Personally I'm not sure how to reproduce this, but it has happened on accident a few times.

Also technically not invisible, alpha is still at 25.

**Comment by Surrealaser** [comment]
Fixed here: https://github.com/tgstation/TerraGov-Marine-Corps/pull/5197

**Comment by SplinterGP** [comment]
as stated above fixed
