### ISSUE TITLE
Using binos before using fob drone breaks its lights

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/TerraGov-Marine-Corps#5210]
## Testmerges:
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: [5879](https://scrubby.melonmesa.com/round/5879)
BYOND Version: 513.1534
Server revision compiled on: 
Master commit: a91db1503b0af3a8cc3a8044b6c8a646a8617c3e
The following pull requests are currently test merged:
#5187: 'gives sentinel the ability to swap to light acid spit' by Pariah919 at commit 03443fdc0b
#5172: 'Lowers shutter automatic opening to 30 minutes' by Hathkar at commit caea4c2d33
#5084: 'Bodydragging is now a 2 Second timer on nonburst humans for xenos' by TiviPlus at commit 774ec78710
#4943: 'Should allow People to make orders regardless of point cost' by Hughgent at commit 9bf3ccdba6
#5190: 'neuraline now purges mera/dermaline at a incredibly fast rate' by Pariah919 at commit 0799aba82b
#5192: 'Neuraline cost increased by 1' by Pariah919 at commit 0443e8f803

Local commit: d7277362e0c14b66de0a607f173b2466b25e2018
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:
If you use binoculars it breaks the lights when you try to use the fob drone
I tested it with tactical binos and helmet binoculars
Just use them and then try to use the FOB drone. What you'll see will be pitch darkness.
It happens anytime after you've used binos.
Say if you try your binos in prep and then 5 minutes later you go build fob for example.

**Comment by Eskjjlj** [comment]
Oh and obviously dont be wearing spatial agent sunglasses when you try to reproduce.

**Comment by Hughgent** [comment]
@TiviPlus any insight as to why this would happen with your lighting system?

**Comment by TiviPlus** [comment]
This is probably sight flags not being applied correctly

**Comment by BraveMole** [comment]
irrelevant now with new flags
