### ISSUE TITLE
Defensive Shield Glitch

### ISSUE THREAD

**Issue by Sparrowbird611** [tgstation/TerraGov-Marine-Corps#5214]
## Reproduction:

 

The defensive shield can get stuck to your back, with no way to be removed outside of admin assistance or possibly another marine ripping it off. You can do this by alt clicking the shield to activate the tether, then clicking e, which quick sheaths it on your back slot. Attempting to take it off with drag click or regular click fails, and untethering it is impossible when on your back.

 

Wasn't due to adminbus.

**Comment by Eskjjlj** [comment]
I can confirm it happens

**Comment by Surrealaser** [comment]
Fixed here: https://github.com/tgstation/TerraGov-Marine-Corps/pull/5248
