### ISSUE TITLE
Warrior cannot grab corpses at all, Lunge uses the grab delay.

### ISSUE THREAD

**Issue by joookschad** [tgstation/TerraGov-Marine-Corps#5219]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: [5888](https://scrubby.melonmesa.com/round/5888)
BYOND Version: 513.1534
Server revision compiled on: 
Master commit: a91db1503b0af3a8cc3a8044b6c8a646a8617c3e
The following pull requests are currently test merged:
#5187: 'gives sentinel the ability to swap to light acid spit' by Pariah919 at commit 03443fdc0b
#5172: 'Lowers shutter automatic opening to 30 minutes' by Hathkar at commit caea4c2d33
**#5084: 'Bodydragging is now a 2 Second timer on nonburst humans for xenos' by TiviPlus at commit 774ec78710**
#4943: 'Should allow People to make orders regardless of point cost' by Hughgent at commit 9bf3ccdba6
#5190: 'neuraline now purges mera/dermaline at a incredibly fast rate' by Pariah919 at commit 0799aba82b
#5192: 'Neuraline cost increased by 1' by Pariah919 at commit 0443e8f803
Also:
Capture Rework #5032
## Reproduction:

Warrior cannot grab corpses of dead marines, at all. 
If you try to use Lunge, it will automatically start the 2 second timer on nonburst humans.

**Comment by adamkad1** [comment]
You can grab corpses, but only with lunge. Everything else checks out. no instant grab, cant normal grab... Makes lunge just bad

**Comment by SplinterGP** [comment]
thats caused by lunge overriding grab.
