### ISSUE TITLE
Weapon Vending Bug for Corpsman, Ship Tech, and Medical Officer (other jobs untested)

### ISSUE THREAD

**Issue by Glarbog** [tgstation/TerraGov-Marine-Corps#5250]
## Reproduction:

Whenever I spawn in as a Medical Officer, Corpsman, or Ship Technician, all of the weapon vendors have greyed out non-pistol weapon magazines, and all pistol weapons; I can still vend either pistol magazines OR non-pistol weapons, but not the magazines/weapons to use what I can vend. I do not know why, but it could be an account issue; the mentor who answered my question did not know that this bug was even possible. If I were to guess it has to do with class access, account communicating with Classes, or some other variable; coding is not my specialty. This applies to all automated weapon and munition vendors, and attached will be screenshots as a Corpsman. Other vendors work as intended. I have not tested this on other classes as I haven't found myself being in the barracks as a pilot nor do I play other classes.

![image](https://user-images.githubusercontent.com/74467686/99154541-b0455280-267e-11eb-99d1-f9664e1fc7c8.png)

![image](https://user-images.githubusercontent.com/74467686/99154553-c18e5f00-267e-11eb-8c37-e1fb9f19a987.png)

![image](https://user-images.githubusercontent.com/74467686/99154559-cb17c700-267e-11eb-8dd3-0c1e1faf1f72.png)
![image](https://user-images.githubusercontent.com/74467686/99154570-df5bc400-267e-11eb-99de-4b5be865e2f4.png)
![image](https://user-images.githubusercontent.com/74467686/99154593-09ad8180-267f-11eb-88a8-daf10b2c5216.png)

**Comment by Glarbog** [comment]
Edit; the Medical Equipment vendor by and for Corpsman is also bugged, but not standard Nanomed or Marinemed vending machines
![image](https://user-images.githubusercontent.com/74467686/99154623-4f6a4a00-267f-11eb-9c5c-583bd73d7436.png)

**Comment by Hughgent** [comment]
No bug. You can click everything there.

The white/black is just a form of recommendation to the player.
