### ISSUE TITLE
Attempting to enter the "replacement character" unicode character, or any unicode character that produces that character, crashes the server.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/TerraGov-Marine-Corps#5282]
## Testmerges:
#5221 #5233 #5190 #5153 #5187 #5226 #5150

## Reproduction:
Round IDs: 6017, 6018, private server after the two
1. Try to enter the following into ooc, ic, or anything else: �
OR
1. Try to enter archaic and beautiful cuneiform script into IC
2. Watch the server instantly perish
3. Uh oh

**Comment by AffectedArc07** [comment]
Well, its definitely isolated to here, so I guess we can worry a bit less.
![image](https://user-images.githubusercontent.com/25063394/99550302-7ba10600-29b2-11eb-8dee-591e2a794199.png)

Check if you do any processing on text which could kill the server (Potentially file I:O with RUSTG [We use RUSTG for logging too but this seems to work fine])
![image](https://user-images.githubusercontent.com/25063394/99550452-a55a2d00-29b2-11eb-95e7-1c51e9003b4a.png)

**Comment by Hughgent** [comment]
Straight up, copy and pasted the � symbol to a local run master. Byond froze then crashed, no runtime, no debug message.

**Comment by Cyberboss** [comment]
This needs to be followed through the extools debugger to see where it's fucking up then
