### ISSUE TITLE
Praetorian acid spray aims randomly.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#5293]
## Reproduction:
Fire an acid spray on any tile that isn't in a straight horizontal line from you.

**Comment by Hughgent** [comment]
needs pictures

**Comment by MLGTASTICa** [comment]
Happened to me quite a few times , after initiating the spray it seems to sometimes change the spray direction to where the cursor is currently pointed instead of preserving the initial spray direction.
