### ISSUE TITLE
IB shows up on the scanner while there is no IB damage

### ISSUE THREAD

**Issue by Murgel11** [tgstation/TerraGov-Marine-Corps#5294]
## Reproduction:

 1) Give someone IB
2) Treat it with QC+

I have experienced this issue twice so far, i treat my patients with QC+ and their damage reaches 0, that means the IB should be gone but the IB remains on my scanner. Sadly i didn't have time to check if the IB still decreases their blood levels but the first time i saw that bug i think the actual IB was stopped and its just a scanner bug but i can't be sure.
![IB](https://user-images.githubusercontent.com/60823008/99828314-7636ed80-2b63-11eb-9b32-1cc1232a4315.png)

**Comment by SplinterGP** [comment]
last i checked the IB status still stay on char unless you give him a bit of bicaridine, i'll go fix that.

**Comment by Hughgent** [comment]
Still a thing?
