### ISSUE TITLE
Underslug masterkey shotgun jams the T-35 pump shotgun

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/TerraGov-Marine-Corps#5304]
Title, firing the last round from a masterkey shotgun causes the next shot from the T-35 to fire oddly and break pumping.

## Reproduction:

- Attach a masterkey shotgun to a T-35 pump shotgun.
- Load both with buckshot and pump the T-35.
- Select the masterkey and fire all 3 rounds, note how the masterkey then deselects itself.
- Attempt to fire the T-35 normally, this will simply cause the gun to *click* yet still consume the earlier pumped round.

The gun is now jammed and attempting to pump the shotgun simply says it already is, you can still fix the weapon by unloading the active round and then pumping again.

Checking varedit shows the glitched shot's projectile ending up inside the gun's contents var. This also occurs with the automatic pump combat shotgun although the pump doesn't jam.
![Jammed](https://user-images.githubusercontent.com/17460297/99891608-911b6780-2c20-11eb-90a8-42278d6f71f8.PNG)

> Hardly any point resolving this until someone bothers making the masterkey useful or until more is found related to this.

**Comment by BraveMole** [comment]
most probably fixed
