### ISSUE TITLE
Crusher icon change errors

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#5310]
## Testmerges:

Irrelevant

## Reproduction:

I have no clue whats causing this but this seems to be the cause of the recent invisible cade and item issues

Basically a crusher charge caused a barricade to change its own icon var to that of a UI obj, as well as editing appearance flags

If I had to guess it has something to do with icon updates but I'm pretty stumped as to what could be the cause

**Comment by SplinterGP** [comment]
i feel there's something borked up with icons sometimes, they just like to somehow mess themselves around, might be the same thing that causes random icons to replace button icons in example.

**Comment by TiviPlus** [comment]
This has also begun affecting mobs, a ravager turned into a human sprite

**Comment by TiviPlus** [comment]
Issue likely related to runechat images applying to the mob hearing instead of the mob that is saying

**Comment by TiviPlus** [comment]
I think this mysteriously fixed itself
