### ISSUE TITLE
You can drop pod into unbreachable map areas.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/TerraGov-Marine-Corps#5318]
Title, drop pod landing coordinates accept locations such as the groundside telecomm relay rooms and possibly the unbreachable atmos/water treatment tanks on Big Red.

### Reproduction:

- Get inside a droppod
- Browse ground webmap for coordinates of unreachable rooms
- Set drop pod for those coorinates and launch
- You are now safe from xenos, though worse dangers (admins) await you.

Late bug that I should've found and gotten attention to before the drop pod PR was merged.

> Unlike the poor fool before me, I prefer to keep my arms thank you very much.
https://i.redd.it/rm59fkcq0q061.jpg

**Comment by Hughgent** [comment]
More fool the user, droppodding should not be perfectly safe, wait for coords from the SL.
