### ISSUE TITLE
Lightning not updating

### ISSUE THREAD

**Issue by Ignies** [tgstation/TerraGov-Marine-Corps#532]
## Testmerges:

PRs #528, #531, #530, #512, #506, #123, #451, #469, #495, #503, #497, #426, #368, #367, #518, #467

## Reproduction:

A marine was reporting a bug about lightning not updating, having to retoggle his suit light everytime he picked up a flare.
The marine was wearing the M3H armor, i tested it at the thunderdome and it didn't disable the suit light, but since the lightning conditions where good i forgot to test the actual light levels.

**Comment by Surrealaser** [comment]
This is a systemic existing problem with our antiquated lighting system that needs to be refactored and replaced.

**Comment by Alterist** [comment]
should be fixed
