### ISSUE TITLE
Acid wells are indestructible

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#5320]
## Testmerges:
#5223 #5217 #5235 #5254 #5257 #5263 #5267

## Reproduction: 
Place down a acid well, as a marine there is no way to kill it, and if it's filled up good luck, because the only way to remove the acid from it is via stepping on it and taking a huge amount of toxin damage.

**Comment by TiviPlus** [comment]
fix already merged
