### ISSUE TITLE
Acid is Fuckywucky

### ISSUE THREAD

**Issue by Chaznoodles** [tgstation/TerraGov-Marine-Corps#5333]
## Testmerges:

https://github.com/tgstation/TerraGov-Marine-Corps/pull/5292/files It's this, pretty sure.

## Reproduction:
- Apply acid to an object, it's gone in 4-5 seconds.
- Apply acid to wall, it's gone before you finish aciding the wall next to it.

- You cannot override 'weaker' acids with 'stronger' acids, because all acids are working at the same pace which is SUPER FAST.
- Bang and the cade is gone
- Blink and you'll miss it
- Wall today, gone tomorrow

**Comment by SplinterGP** [comment]
Third thhing fixed
