### ISSUE TITLE
Show / hide typing indicator bugged out

### ISSUE THREAD

**Issue by Ignies** [tgstation/TerraGov-Marine-Corps#534]
## Testmerges:

#467, #518, #367, #368, #426, #497, #503, #495, #469, #451, #506, #512, #530, #531, #528, #516, #529

## Reproduction:

Open your chat window, use show/hide typing indicator with the chat window open, it will bug out and appear as if you are always typing.

**Comment by DominikPanic** [comment]
Thanks this one's on me, I'll get to it.
