### ISSUE TITLE
Sectoid ERT lacks armor and equipment

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#5343]
## Testmerges:
#5254 #5257 #5263 #5267 #5223 #5235

## Reproduction:

- Call for ERT, wait for sectoids

- They spawn without belt, armor or their NV eyes.

**Comment by Hughgent** [comment]
needs an update. proof of it happening.

**Comment by MLGTASTICa** [comment]
You are probably confusing sectoid ert with sectoid grunts ert

**Comment by davidchan13** [comment]
Sectoids are more of a meme anyways, by the source material they only deploy with wrist mounted plasma gun and nothing else.
