### ISSUE TITLE
view.dm runtime

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#5360]
## Testmerges:

#5285 #5241 #5159 #5217 #5242 #5253

## Runtime:

Runtime Viewer

<<<Refresh

[02:41:07] Runtime in view.dm, line 23: Cannot read null.x
proc name: in view range (/proc/in_view_range)
usr: Anystar1/(Kade Beach)
usr.loc: (Aerodrome Container Yard (124, 96, 2))
src: null
call stack:
in view range(Kade Beach (/mob/living/carbon/human), null)
/datum/component/automatic_fir... (/datum/component/automatic_fire): process shot()
/datum/callback (/datum/callback): Invoke()
world: PushUsr(Kade Beach (/mob/living/carbon/human), /datum/callback (/datum/callback))
/datum/callback (/datum/callback): InvokeAsync()
Timer (/datum/controller/subsystem/timer): fire(0)
Timer (/datum/controller/subsystem/timer): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

usr: VV PP FLW
usr.loc: VV JMP

**Comment by SplinterGP** [comment]
caused by target being null when proccess_shot was called.
