### ISSUE TITLE
update_icons.dm runtime

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#5361]
## Testmerges:

#5285 #5241 #5159 #5217 #5242 #5253

## Runtime:

Runtime Viewer

<<<Refresh

[02:41:07] Runtime in update_icons.dm, line 109: Cannot modify null.layer.
proc name: update wounds (/mob/living/carbon/xenomorph/proc/update_wounds)
src: the Mature Larva (307) (/mob/living/carbon/xenomorph/larva)
src.loc: null
call stack:
the Mature Larva (307) (/mob/living/carbon/xenomorph/larva): update wounds()
the Mature Larva (307) (/mob/living/carbon/xenomorph/larva): updatehealth()
/datum/callback (/datum/callback): InvokeAsync()
Timer (/datum/controller/subsystem/timer): fire(0)
Timer (/datum/controller/subsystem/timer): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by SplinterGP** [comment]
the larva seems to be deletting ?, since no src ?

**Comment by BraveMole** [comment]
fixed
