### ISSUE TITLE
component.dm runtime

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#5363]
## Testmerges:

#5285 #5241 #5159 #5217 #5242 #5253

## Runtime:

Runtime Viewer

<<<Refresh

[02:55:21] Runtime in _component.dm, line 218: Cannot read null.comp_lookup
proc name: UnregisterSignal (/datum/proc/UnregisterSignal)
src: /datum/chatmessage (/datum/chatmessage)
call stack:
/datum/chatmessage (/datum/chatmessage): UnregisterSignal(null, null)
/datum/chatmessage (/datum/chatmessage): Destroy(0)
/datum/chatmessage (/datum/chatmessage): Destroy(0)
qdel(/datum/chatmessage (/datum/chatmessage), 0)
Runechat (/datum/controller/subsystem/runechat): fire(0)
Runechat (/datum/controller/subsystem/runechat): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by TiviPlus** [comment]
Harddel related
