### ISSUE TITLE
unsorted.dm runtime

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#5365]
## Testmerges:

#5285 #5241 #5159 #5217 #5242 #5253

## Runtime:

Runtime Viewer

<<<Refresh

[02:58:48] Runtime in unsorted.dm, line 35: addtimer called with a 0 or negative wait. Converting to 0.5
proc name: stack trace (/proc/stack_trace)
usr: Overlord1234/(Overlord1234)
usr.loc: (start area (8, 8, 1))
src: null
call stack:
stack trace("addtimer called with a 0 or ne...")
addtimer(/datum/callback (/datum/callback), 0, 0, "code/modules/client/client_pro...", 769)
Overlord1234 (/client): change view("15x15")
Overlord1234 (/mob/new_player): Login()
Overlord1234 (/mob/new_player): Login()

usr: VV PP FLW
usr.loc: VV JMP

**Comment by SplinterGP** [comment]
I get that one everytime now when entering test server
