### ISSUE TITLE
Broken FaceFuckers

### ISSUE THREAD

**Issue by AdrianShepard** [tgstation/TerraGov-Marine-Corps#537]
## Testmerges:

#533 #467 #518 #367 #368 #426 #497 #503 #495 #469 #451 #506 #512 #530 #531 #528 #516 #529 #522 #124
## Reproduction:
step 1) Bring a host
step 2)watch multiple eggs open
step 3)profit
![image](https://user-images.githubusercontent.com/43182805/52187001-e57f0880-283b-11e9-9107-1f47511ac77f.png)

**Comment by Ghommie** [comment]
Should be fixed.

**Comment by DominikPanic** [comment]
Fixed in #451 I guess
