### ISSUE TITLE
CAS plane camnet runtime

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#5378]
[18:50:20] Runtime in cameranet.dm, line 175: Cannot read null.x
proc name: checkTurfVis (/datum/cameranet/proc/checkTurfVis)
usr: Iwan840/(Rei Nakano)
usr.loc: (Condor Jet (21, 71, 4))
src: Camera Net (/datum/cameranet)
call stack:
Camera Net (/datum/cameranet): checkTurfVis(null)
the marine dropship (/obj/docking_port/mobile/marine_dropship/casplane): fire weapons at(Rei Nakano (/mob/living/carbon/human), the static (/obj/effect/overlay/camera_static), "icon-x=20;icon-y=12;left=1;scr...", null, null)
CallAsync(the marine dropship (/obj/docking_port/mobile/marine_dropship/casplane), /obj/docking_port/mobile/marin... (/obj/docking_port/mobile/marine_dropship/casplane/proc/fire_weapons_at), /list (/list))
Rei Nakano (/mob/living/carbon/human): SendSignal("mob_clickon", /list (/list))
Rei Nakano (/mob/living/carbon/human): ClickOn(the static (/obj/effect/overlay/camera_static), the plating (137,92,2) (/turf/open/floor/plating/icefloor), "icon-x=20;icon-y=12;left=1;scr...")
the static (/obj/effect/overlay/camera_static): Click(the plating (137,92,2) (/turf/open/floor/plating/icefloor), "mapwindow.map", "icon-x=20;icon-y=12;left=1;scr...")
Iwan840 (/client): Click(the static (/obj/effect/overlay/camera_static), the plating (137,92,2) (/turf/open/floor/plating/icefloor), "mapwindow.map", "icon-x=20;icon-y=12;left=1;scr...")

**Comment by Hughgent** [comment]
Is this still a thing?

**Comment by TiviPlus** [comment]
I wouldn't see why not
