### ISSUE TITLE
List of features that will improve the game alot.

### ISSUE THREAD

**Issue by AdrianShepard** [tgstation/TerraGov-Marine-Corps#538]
![image](https://user-images.githubusercontent.com/43182805/52187060-47d80900-283c-11e9-9235-b99ef3d293d0.png)

**Comment by DominikPanic** [comment]
GitHub is for bugs and issue reports only, you can use either #dev-general or the official forums suggestion thread for feature requests: https://tgstation13.org/phpBB/viewtopic.php?f=65&t=20995
