### ISSUE TITLE
[BUG] Rail scope can give negative accuracy to weapons

### ISSUE THREAD

**Issue by AGasCanister** [tgstation/TerraGov-Marine-Corps#5382]
## Testmerges:
Not a testmerge bug I think

## Reproduction:
Basically when being zoomed by the rail scope you can get negative accuracy if you move 1 tile and then click the zoom button again, the first click should do nothing as it should unzoom you, but since your character mooved it unzoomed automatically and there's nothing to unzoom, but the stats the affected by it, the second click should get you zoomed.

1. Get SVD Dragunov (confirmed with this weapon) or another sniper rifle.
2. Aim with rail scope
3. Move 1 tile, you should be unzoomed
4. Click the scope hud button, first click should do ntohing
5. Click it again and check the gun details

Edit: This only happens if you unzoom it by yourself, getting pushed unzooms you correctly.
Edit2: Unwielding the weapon unzooms you correctly too, unzooming manually also works, it only breaks when moving voluntarily 

![image](https://user-images.githubusercontent.com/55928412/100526646-37401200-31cb-11eb-9562-d827e212280a.png)
Example of what you can do with this rail scope bug

**Comment by SplinterGP** [comment]
looking into
