### ISSUE TITLE
inured larva have an odd overlay

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#541]
![4093a70fa7e252499ec22d2569c49639](https://user-images.githubusercontent.com/28164826/52190185-4807e280-2803-11e9-8bfb-a0d0656b8b3b.png)

**Comment by Rohesie** [comment]
This is related to #367 I'd assume.

**Comment by DominikPanic** [comment]
@Alterist Wanna have a go at it?
