### ISSUE TITLE
Constantly Recurring Popups upon Silo View

### ISSUE THREAD

**Issue by Chaznoodles** [tgstation/TerraGov-Marine-Corps#5441]
## Testmerges:

https://github.com/tgstation/TerraGov-Marine-Corps/pull/5391 It's this.

## Reproduction:

If you hit the cancel/no option when it asks you if you want to spawn at this resin silo, you end up in an endless loop of the silo menu popping up and can't get out until you spawn as a xenos.

**Comment by TiviPlus** [comment]
@Hughgent

**Comment by Chaznoodles** [comment]
![image](https://user-images.githubusercontent.com/44979174/101671948-1f7b5000-3a4d-11eb-90d6-fcdae3bbe105.png)

If you log out and log back in to get rid of the recurring popup, it turns out you got sent to the N U L L Z O N E in the meantime
