### ISSUE TITLE
Certain Xeno stats break when going shipside

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#5454]
**Testmerges:** #5430 

**Reproduction:** Since the moment xenomorphs begin the trip shipside after a hijack; Evolve Progress, Upgrade Progress, and burrowed larvae will break in a way that makes them progress inversely, even making them go into the negatives. For burrowed larvae, this translates to infinite spawns for xenos.

Partially fixed by #5451.

**Comment by TiviPlus** [comment]
Stats were calculated based on larva amounts
