### ISSUE TITLE
Hive Status button not working until a xeno becomes Queen

### ISSUE THREAD

**Issue by Ruediger4** [tgstation/TerraGov-Marine-Corps#5464]
## Testmerges:
It may be caused by Testmerge https://github.com/tgstation/TerraGov-Marine-Corps/pull/5433 due to it's nature and how it supposedly tries to fix the same error. This time it affects all xenos until a queen is elected/rises. When that happens, all xenos can check Hive Status.

## Reproduction:
According to players, Hive Status does not work until someone volunteers and rises as Queen. A handful of Runtime errors happened, mostly regarding evolution.dm and xenoprocs.dm during Round 6340. 5433 modifies both of those.

[runtime.log](https://github.com/tgstation/TerraGov-Marine-Corps/files/5663578/runtime.log)

First time doin' a bug report so sorry if it's missing anything.

**Comment by Surrealaser** [comment]
My latest commit should fix this.
