### ISSUE TITLE
Muting deadchat doesn't work properly

### ISSUE THREAD

**Issue by BeloneX** [tgstation/TerraGov-Marine-Corps#5469]
## Reproduction:

Clicking 'Toggle Deadchat' in prefs only makes you unable to type in deadchat, you'll still see deadchat.

**Comment by Mannybrado** [comment]
this is also the case with toggling OOC.

**Comment by BeloneX** [comment]
> this is also the case with toggling OOC, probably LOOC as well.

Nope, these actually work properly.
