### ISSUE TITLE
Thermal tarp deletes itself and items

### ISSUE THREAD

**Issue by khlorghaal** [tgstation/TerraGov-Marine-Corps#5473]
## Reproduction:
Take a thermal tarp and other item and put them on the ground in the same location, activate the tarp without standing on it.  
The tarp will delete itself and the item after it turns invisible.  

## Code:
blob/master/code/game/objects/items/bodybag.dm#L372
the actions appear to require that the item's user also be its occupant, but the bodybag is taking the item as its occupant?

**Comment by SplinterGP** [comment]
does it really turn invisible or you just cant see it ?

**Comment by khlorghaal** [comment]
admin who responded ingame said the object appeared to not exist, even when given the exact tile it was on    
the entity may still be constructed, but with no way for anyone to interact with it?

**Comment by BraveMole** [comment]
Not reproduced
