### ISSUE TITLE
scope runtime error???

### ISSUE THREAD

**Issue by arkon897** [tgstation/TerraGov-Marine-Corps#5475]
## Reproduction:
round ID is 6364, my name was Duran Surik, *smiles* byond key is arkon897, my kit this round was the TL127 when i scoped my rilfe at the start of the round, i quickly discovered that auto unequipping my rifle to my suit storage was not throwing me out of my extended "scope" vision, thinking about it for a min i then drew my 45 pistol and fired it into  a wall maintaining my extended sniper vision all the while, the only odd thing my "twist" on my build was, taking lose sniper ammo and 1 mag and repacked the mag  a few times before this happened, i dont think that would effect whatever is happening but its the only "odd" thing i had done beforehand so i thought its worth a mention, oh i should probably state that movement would still throw me out of the extended vision and a mortar firing near me would shake my  vision but leave me in the extended vision, as it normally would, seemingly its only effecting when i unshoulder my rifle or auto unequip it IE i have sniper vision when i should of been forced out of it

**Comment by SplinterGP** [comment]
i'll take note and fix

**Comment by arkon897** [comment]
thanks for your time
