### ISSUE TITLE
Follow/Orbit Ghost verb closes hud when you click a name.

### ISSUE THREAD

**Issue by davidchan13** [tgstation/TerraGov-Marine-Corps#5500]
## Testmerges: 
N/A

## Reproduction:
Click Follow Verb
Click Xeno, Human or Marine button
Be annoyed when Orbit window closes whether you were done with it or not.

Title

Upstream (tgstation) behavior of Orbit window is to leave the window open when a name or object is selected, allowing ghosts to easily jump between orbitable mobs. 

For example, a xeno is reported on the ship, or a marine still on the surface delaying a hijack. 

Without knowing their name and exact location, you must click every name, reopening the follow window every time. 

There is no reason for this window to close until the ghost player chooses to close it, or ceases to be a ghost for some reason. 

If this IS intended behavior of the window, there is little reason for it function this way.

**Comment by SplinterGP** [comment]
probably intended behaviour, i'll see if i can make it not close however.
