### ISSUE TITLE
Camera mobs can right click fog of war during Firemissions to locate xenos.

### ISSUE THREAD

**Issue by davidchan13** [tgstation/TerraGov-Marine-Corps#5509]
## Reproduction: 
Launch a fire mission with Condor.
Find area Xenos are likely hiding out of sight (behind static or black areas you can't see.
Right Click and be amazed when you see Ancient Runner (Name) or find a Shrike waiting out of sight and can relay this information to marines freely.

LOS is not being respected for Condor Firemissions, treating tiles that shouldn't be targettable as still visible for any inquisitive PO who chooses to right click guess over an area to pinpoint a xenos location, certain ordinance allowing them to potentially attack mobs that should otherwise not be detectable to the Condor due to vision and line of sight.

**Comment by Chaznoodles** [comment]
Any camera can do this, including Overwatch helmet cams. You can also see speech bubbles through the static.
