### ISSUE TITLE
[BUG] Able to evolve to T2 even when calculation said no more slots for T2

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#5519]
## Reproduction:

https://youtu.be/xfgIT1Lzwsg

Not sure how to replicate this.

**Comment by SkeletalElite** [comment]
Hivestatus lies all the time about slots I've had it happen for t3 as well

**Comment by Wayland-Smithy** [comment]
Has nothing to do with Balance IMO.

There seems to exist many cases where the T2 cap appears way lower than it should be almost like T0 are not being counted even though they _are_ in the formula. Could be something to do with having a Queen and/or Hivemind active, xenos dying, or something else along the line of triggering it to update the numbers like Surr has mentioned before.

**Comment by BraveMole** [comment]
doesn't happen anymore IIRC
