### ISSUE TITLE
(Buggy Bug) You cannot walk into the same tiles as a flipped table

### ISSUE THREAD

**Issue by David-Stormwell** [tgstation/TerraGov-Marine-Corps#5531]
## Testmerges:
#5479 #5335

## Reproduction:
Flip a table, at least a reinforced one, can't walk into the tile.

**Comment by Surrealaser** [comment]
Probably a can pass refactor issue. I'll look into it after work today

**Comment by Surrealaser** [comment]
Should be fixed by the latest update to #5479
