### ISSUE TITLE
Rocket Pod sprites appear invisible when facing specific directions

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#5536]
Testmerges irrelevant.

**Reproduction:** The most common method of achieving these 'invisible rocket pods' is by using a powerloader and placing them in a specific direction (south, if I'm not mistaken). Depending on the direction, the sprite will appear invisible.

**Comment by Hughgent** [comment]
Which rocket pod?

placed where?

be very specific as to how this is recreated.

**Comment by lKiseki** [comment]
![image](https://user-images.githubusercontent.com/59634950/103452390-7105ac00-4c94-11eb-9bc1-14485211362b.png)

Right here. There's an invisible rocket pod. When we examine its variables:
![image](https://user-images.githubusercontent.com/59634950/103452399-8aa6f380-4c94-11eb-8481-c42bc95d75ad.png)

...We find it is facing south, and has no visible icon. And when it's turned around...
![image](https://user-images.githubusercontent.com/59634950/103452401-9f838700-4c94-11eb-9f95-d6d0322024c3.png)

...It reappears!

There's no method of recreation, since (apparently) it just naturally spawns like so. Just a matter of going to the Piloting Ammunition Storage in Pillar of Spring, finding the invisible rocket pod in the same spot represented in the images, and voila.
