### ISSUE TITLE
Map issues with the ship.

### ISSUE THREAD

**Issue by Jalleo** [tgstation/TerraGov-Marine-Corps#554]
## Reproduction:
Look under maint door between staff office and the room to its left (fire alarm) maint lightbulb to the left heading towards CIC somewhere is facing the wrong direction. CO office APC is on the floor. And another one or two APCs are on the floor too. I cant remember where exactly but its upper deck on that side of the ship.

**Comment by Ghommie** [comment]
I should be fixing the fire alarm/APC ones in #272. I can't really spot the maint lightbuld facing the wrong direction though, can you be more specific or post a screenie if possible?

**Comment by Shadow-Quill** [comment]
Northern lower medical is also missing a emergency shutter.
![image](https://user-images.githubusercontent.com/44811257/52307420-30923c00-2960-11e9-9ab1-4a2f14195f0d.png)

**Comment by Rohesie** [comment]
I'm not 100% positive this is not a bug with the code for double-doors, because I've seen it happen so much.

**Comment by Shadow-Quill** [comment]
Oh, there's also a missing disposals pipe right under the door leading to the recycler. (At least on the lower level, not sure about upper.)

**Comment by Alterist** [comment]
will fix

**Comment by DominikPanic** [comment]
@Alterist

**Comment by Alterist** [comment]
#980
