### ISSUE TITLE
Field Commander Vendor is fugged

### ISSUE THREAD

**Issue by MickDick1** [tgstation/TerraGov-Marine-Corps#5545]
## Testmerges:

#5517 #5479 #5335

## Reproduction:

Just look at it.

The only options available now are:

*Essentials

*Light skirmisher armor jaegar plates
*Infantry armor jaegar plates

Where is the exoskeleton?  The heavy assault/EORD plates?  etc.

A few months ago it was fine, with a proper selection.

**Comment by Hughgent** [comment]
gonna need more information and screenshots

![image](https://user-images.githubusercontent.com/45076386/103050080-026c7400-4559-11eb-8d06-15d1959ed669.png)

**Comment by MickDick1** [comment]
![FC vendor](https://user-images.githubusercontent.com/76397585/103063198-9270e480-457e-11eb-9fb1-aa772e359620.png)


I mean, that's pretty much it.  Exactly as i detailed.
