### ISSUE TITLE
Fingerprint runtime

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#5547]
[19:40:56] Runtime in atoms.dm, line 735: Invalid mob type the cautery(/obj/item/tool/surgery/cautery) when attempting to add fingerprint of type attackby.
proc name: add fingerprint (/atom/proc/add_fingerprint)
usr: EnderSub9/(Med Ike)
usr.loc: (Dropship Alamo (181, 110, 2))
src: Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable)
src.loc: the floor (181,109,2) (/turf/open/shuttle/dropship/floor)
call stack:
Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable): add fingerprint(the cautery (/obj/item/tool/surgery/cautery), "attackby", Operating Table (/obj/machinery/optable))
Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable): attackby(Operating Table (/obj/machinery/optable), the cautery (/obj/item/tool/surgery/cautery), Med Ike (/mob/living/carbon/human), "icon-x=10;icon-y=3;left=1;scre...")
Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable): attackby(Operating Table (/obj/machinery/optable), the cautery (/obj/item/tool/surgery/cautery), Med Ike (/mob/living/carbon/human), "icon-x=10;icon-y=3;left=1;scre...")
Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable): attackby(Operating Table (/obj/machinery/optable), the cautery (/obj/item/tool/surgery/cautery), Med Ike (/mob/living/carbon/human), "icon-x=10;icon-y=3;left=1;scre...")
CallAsync(Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable), /atom/proc/attackby (/atom/proc/attackby), /list (/list))
Operating Table (/obj/machinery/optable): SendSignal("atom_attackby", /list (/list))
Operating Table (/obj/machinery/optable): attackby(the cautery (/obj/item/tool/surgery/cautery), Med Ike (/mob/living/carbon/human), "icon-x=10;icon-y=3;left=1;scre...")
Operating Table (/obj/machinery/optable): attackby(the cautery (/obj/item/tool/surgery/cautery), Med Ike (/mob/living/carbon/human), "icon-x=10;icon-y=3;left=1;scre...")
Operating Table (/obj/machinery/optable): attackby(the cautery (/obj/item/tool/surgery/cautery), Med Ike (/mob/living/carbon/human), "icon-x=10;icon-y=3;left=1;scre...")
the cautery (/obj/item/tool/surgery/cautery): melee attack chain(Med Ike (/mob/living/carbon/human), Operating Table (/obj/machinery/optable), "icon-x=10;icon-y=3;left=1;scre...")
Med Ike (/mob/living/carbon/human): ClickOn(Operating Table (/obj/machinery/optable), the floor (181,109,2) (/turf/open/shuttle/dropship/floor), "icon-x=10;icon-y=3;left=1;scre...")
Operating Table (/obj/machinery/optable): Click(the floor (181,109,2) (/turf/open/shuttle/dropship/floor), "mapwindow.map", "icon-x=10;icon-y=3;left=1;scre...")
EnderSub9 (/client): Click(Operating Table (/obj/machinery/optable), the floor (181,109,2) (/turf/open/shuttle/dropship/floor), "mapwindow.map", "icon-x=10;icon-y=3;left=1;scre...")

**Comment by Hughgent** [comment]
related to #5548
