### ISSUE TITLE
OPerating table runtime

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#5548]
[19:35:18] Runtime in item_attack.dm, line 60: undefined variable /obj/item/tank/anesthetic/var/a_intent
proc name: attackby (/obj/attackby)
usr: EnderSub9/(Med Ike)
usr.loc: (Dropship Alamo (109, 168, 3))
src: Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable)
src.loc: the floor (109,169,3) (/turf/open/shuttle/dropship/floor)
call stack:
Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable): attackby(Operating Table (/obj/machinery/optable), the anesthetic tank (/obj/item/tank/anesthetic), Med Ike (/mob/living/carbon/human), "icon-x=19;icon-y=11;left=1;scr...")
Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable): attackby(Operating Table (/obj/machinery/optable), the anesthetic tank (/obj/item/tank/anesthetic), Med Ike (/mob/living/carbon/human), "icon-x=19;icon-y=11;left=1;scr...")
CallAsync(Dropship Operating Table Deplo... (/obj/structure/dropship_equipment/operatingtable), /atom/proc/attackby (/atom/proc/attackby), /list (/list))
Operating Table (/obj/machinery/optable): SendSignal("atom_attackby", /list (/list))
Operating Table (/obj/machinery/optable): attackby(the anesthetic tank (/obj/item/tank/anesthetic), Med Ike (/mob/living/carbon/human), "icon-x=19;icon-y=11;left=1;scr...")
Operating Table (/obj/machinery/optable): attackby(the anesthetic tank (/obj/item/tank/anesthetic), Med Ike (/mob/living/carbon/human), "icon-x=19;icon-y=11;left=1;scr...")
Operating Table (/obj/machinery/optable): attackby(the anesthetic tank (/obj/item/tank/anesthetic), Med Ike (/mob/living/carbon/human), "icon-x=19;icon-y=11;left=1;scr...")
the anesthetic tank (/obj/item/tank/anesthetic): melee attack chain(Med Ike (/mob/living/carbon/human), Operating Table (/obj/machinery/optable), "icon-x=19;icon-y=11;left=1;scr...")
Med Ike (/mob/living/carbon/human): ClickOn(Operating Table (/obj/machinery/optable), the floor (109,169,3) (/turf/open/shuttle/dropship/floor), "icon-x=19;icon-y=11;left=1;scr...")
Operating Table (/obj/machinery/optable): Click(the floor (109,169,3) (/turf/open/shuttle/dropship/floor), "mapwindow.map", "icon-x=19;icon-y=11;left=1;scr...")
EnderSub9 (/client): Click(Operating Table (/obj/machinery/optable), t

**Comment by Hughgent** [comment]
dropship op table has this
```
/obj/structure/dropship_equipment/operatingtable/Initialize()
	. = ..()
	if(!deployed_table)
		deployed_table = new(src)
		RegisterSignal(deployed_table, COMSIG_PARENT_ATTACKBY, /atom/.proc/attackby)//if something (like a powerloader) clicks on the deployed thing relay it
```
the signal is passing the off by one list of arguments to the parent.

it is passing the `operating table`, `item`, `user`, `then extra parameters`, in that order to `attackby`.

`attackby` is expecting the right three things in that list of four things.

`SEND_SIGNAL` sends the `src` + arguments in a list.

And this is where things get past me. This signal needs to not send the `src` to the parent.

**Comment by SplinterGP** [comment]
> dropship op table has this
> 
> ```
> /obj/structure/dropship_equipment/operatingtable/Initialize()
> 	. = ..()
> 	if(!deployed_table)
> 		deployed_table = new(src)
> 		RegisterSignal(deployed_table, COMSIG_PARENT_ATTACKBY, /atom/.proc/attackby)//if something (like a powerloader) clicks on the deployed thing relay it
> ```
> 
> the signal is passing the off by one list of arguments to the parent.
> 
> it is passing the `operating table`, `item`, `user`, `then extra parameters`, in that order to `attackby`.
> 
> `attackby` is expecting the right three things in that list of four things.
> 
> `SEND_SIGNAL` sends the `src` + arguments in a list.
> 
> And this is where things get past me. This signal needs to not send the `src` to the parent.

Use a wrapper proc
