### ISSUE TITLE
Spammy HUD runtime

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#5555]
@Surrealaser Possibly related to structures?

Happens over 500 times a round

## Testmerges:

Round ID: [6547](https://scrubby.melonmesa.com/round/6547)
BYOND Version: 513.1534
Server revision compiled on: 
Master commit: a5d939a1e2e400a1997d3e1eaaf223bf968fa842
The following pull requests are currently test merged:
#5517: 'Un-hardcodes and refactors icon drawing for update_inv(), removes hardcoded icon files' by SplinterGP at commit def0f5cb8a
#5479: 'CanPass Refactor Imported From TG' by Surrealaser at commit 95efc78059
#5335: 'Xeno Structure Partial Refactor and Improvements' by Surrealaser at commit 6a242d9daf

## Reproduction:

[18:24:37] Runtime in atom_hud.dm, line 72: bad index
proc name: remove from single hud (/datum/atom_hud/proc/remove_from_single_hud)
usr: AIIA/(Nar Nar)
usr.loc: (Sulaco Marine Prep (76, 59, 3))
src: /datum/atom_hud/simple (/datum/atom_hud/simple)
call stack:
/datum/atom_hud/simple (/datum/atom_hud/simple): remove from single hud(Sai Dominguez (/mob/living/carbon/human), Nar Nar (as Unknown) (/mob/living/carbon/human/dummy))
/datum/atom_hud/simple (/datum/atom_hud/simple): remove from hud(Nar Nar (as Unknown) (/mob/living/carbon/human/dummy))
Nar Nar (as Unknown) (/mob/living/carbon/human/dummy): remove from all mob huds()
Nar Nar (as Unknown) (/mob/living/carbon/human/dummy): Destroy(0)
Nar Nar (as Unknown) (/mob/living/carbon/human/dummy): Destroy(0)
qdel(Nar Nar (as Unknown) (/mob/living/carbon/human/dummy), 0)
get flat human icon(null, /datum/job/spatial_agent/galax... (/datum/job/spatial_agent/galaxy_red), /datum/preferences (/datum/preferences), null, /list (/list), null)
Nar Nar (/mob/camera/imaginary_friend): setup friend()
Nar Nar (/mob/camera/imaginary_friend): Login()

**Comment by Surrealaser** [comment]
@TiviPlus Not sure how it'd relate to structures; I don't see anything here that my structure refactor would really touch per the runtime you cited here. Are there any other notable runtimes?

I also didn't have any runtimes during testing of any of the structure or CanPass TMs.
