### ISSUE TITLE
Likely cause for random HUD being set to Permadead when defibbable

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/TerraGov-Marine-Corps#5556]
## Testmerges:
unrelated
## Reproduction:

[19:06:51] Runtime in defibrillator.dm, line 102: Cannot read null.current
proc name: get ghost (/mob/living/proc/get_ghost)
src: Lok Winter (/mob/living/carbon/human)
src.loc: the floor (71,53,2) (/turf/open/floor/tile/purple/whitepurple)
call stack:
Lok Winter (/mob/living/carbon/human): get ghost()
Lok Winter (/mob/living/carbon/human): med hud set status()
Lok Winter (/mob/living/carbon/human): Life(0.5, 7399)
Mobs (/datum/controller/subsystem/mobs): fire(0)
Mobs (/datum/controller/subsystem/mobs): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

18:52:52] Runtime in defibrillator.dm, line 102: Cannot read null.current
proc name: get ghost (/mob/living/proc/get_ghost)
src: Edwardina Shann (/mob/living/carbon/human)
src.loc: the floor (27,33,2) (/turf/open/floor/marking/bot)
call stack:
Edwardina Shann (/mob/living/carbon/human): get ghost()
Edwardina Shann (/mob/living/carbon/human): med hud set status()
Edwardina Shann (/mob/living/carbon/human): Life(0.5, 5757)
Mobs (/datum/controller/subsystem/mobs): fire(0)
Mobs (/datum/controller/subsystem/mobs): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
(This error will now be silenced for 10 minutes)

**Comment by Hughgent** [comment]
so uh, I guess that ghosts, upon having a person disconnect, don't remove themselves from the `GLOB.observer_list`?

**Comment by TiviPlus** [comment]
No it looks like get ghost is runtiming for some reason, so it return null instead of a ghost
