### ISSUE TITLE
sticky resin spit can be placed over acid wells

### ISSUE THREAD

**Issue by Pariah919** [tgstation/TerraGov-Marine-Corps#5574]
## Testmerges:
doesn't matter

## Reproduction:
1. put acid and fill it up
2. spit resin over it
![image](https://user-images.githubusercontent.com/46353991/103176897-1fe05d00-483b-11eb-80e7-cbe8d2f193d7.png)

**Comment by TiviPlus** [comment]
> ## Testmerges:
> doesn't matter

https://github.com/tgstation/TerraGov-Marine-Corps/pull/5335

You absolute clown

**Comment by Surrealaser** [comment]
@TiviPlus This is existing behaviour; I changed nothing. It's an easy fix via changing layering anyways.
