### ISSUE TITLE
Windoors take up an entire tile.

### ISSUE THREAD

**Issue by BeloneX** [tgstation/TerraGov-Marine-Corps#5575]
https://streamable.com/lj9q3s

**Comment by BraveMole** [comment]
I have the feeling it was not the case that long ago, could a recent PR made this?

**Comment by SplinterGP** [comment]
are you moving diagonally ?

**Comment by BeloneX** [comment]
> are you moving diagonally ?

No.

**Comment by TiviPlus** [comment]
Likeliest cause is @Surrealaser 's port of canpass

**Comment by Surrealaser** [comment]
@TiviPlus I actually just noticed this last night when testing collision for the Wraith PR.

I ran some tests, having it completely ignore the parent proc, and using the old code prior to the CanPass refactor; same issue.

**Comment by Surrealaser** [comment]
Alright got a fix

**Comment by Wayland-Smithy** [comment]
I captured it happening to me recently:
![B02bJmVMaX](https://user-images.githubusercontent.com/64715958/103334668-174c7a00-4a27-11eb-8729-d2536c6e9c5b.gif)
No diag movement or clicking involved. Just left and right movement adjacent to the windoors.

**Comment by Surrealaser** [comment]
@Wayland-Smithy yes, this was after @Hughgent 's suggested change.

I reverted it; works fine now.
