### ISSUE TITLE
Azerty keyboard lack support

### ISSUE THREAD

**Issue by BraveMole** [tgstation/TerraGov-Marine-Corps#5578]
## Reproduction:

Poor french players like me can't really play at their full potential in azerty because the characters & and é are not recognised by the keybinding window (it's the equivalant of 1 2 for qwerty keyboards). Hence we can't really shift efficiently between intents, wich leads to a lot of body blocking.

Yogstation has a cool azerty settings already done, so it's possible. If no one has a solution in mind, i'll go peek at their code to see what they done

**Comment by SplinterGP** [comment]
if you can see what yog has done for it and tell us we can add it into easily
