### ISSUE TITLE
NODROP tag prevents from equipping the item

### ISSUE THREAD

**Issue by BraveMole** [tgstation/TerraGov-Marine-Corps#5592]
## Test merge: 

Caused by a merge 2020-11-23 from a  Surrealaser PR : 
 bugfix: Fixed Shields sticking to the back due to NODROP. You can no longer equip
      NODROP items to non-hand locations.

## Reproduction:

You can't equip any item with a NODROP tag. That caused the sectoid ERT to be naked when spawning, since the forcefields they were wearing were tagged NODROP|DELONDROP. DELONDROP works as intented though

**Comment by David-Stormwell** [comment]
69th issue currently opened, congrats
