### ISSUE TITLE
Spawned into the EorG arena as a brain

### ISSUE THREAD

**Issue by DiscordWizard** [tgstation/TerraGov-Marine-Corps#560]
I spawned as a naked alpha medic, as soon as I stepped out of cryo I got murdered by moth UPP, and I ghosted before my crit self died. When the game ended and I was teleported into the arena, I ended up a literal brain on the ground. No death, nothing, just spawned a brain on the floor.

**Comment by DominikPanic** [comment]
I'm onto it

**Comment by DominikPanic** [comment]
Fixed in latest commit of #518
