### ISSUE TITLE
Tiny Command Voices in Radio

### ISSUE THREAD

**Issue by Swagile** [tgstation/TerraGov-Marine-Corps#5609]
## Reproduction:

So I have this issue where anyone with a command rank or important role such as Synth, AI, Captain, SL, RO, etc. who have BIG voices normally for everyone else are SMALL for me. Like tiny as hell. Here's an example:

https://i.imgur.com/wQ00YOA.png

This doesn't happen on the goon chat of CM, but it does on TGMC's goon chat and I have no idea why. Ive updated my BYOND, cleared cache, but it doesn't fix it.

**Comment by SplinterGP** [comment]
i'll give a check on the CSS

**Comment by TiviPlus** [comment]
maybe dark mode related

**Comment by Swagile** [comment]
ive asked in OOC as well before to see if this happens to others and they said yes

don't have a list of names sadly

turned off and on dark mode, issue still persists.

reloaded chat, turned it back off to old chat, turned it back on; issue still persists.

cleared cache as well. ill try clearing internet explorer as well i guess.

**Comment by SpaceLoveSs13** [comment]
Are you sure it's not just that the users of command radio turned their loudmode off? I think I remember having the ability to turn it off in past.

**Comment by Swagile** [comment]
> 
> 
> Are you sure it's not just that the users of command radio turned their loudmode off? I think I remember having the ability to turn it off in past.

no they all have their loud mode on.

i know because my own text, while in loud mode, is also tiny.

those without loud mode (non leadership) have normal text and its not tiny for me.

**Comment by TiviPlus** [comment]
Allegedly fixed by tgchat
