### ISSUE TITLE
The return to your body message can happen when someone completely unrealted to you is being revived

### ISSUE THREAD

**Issue by BeloneX** [tgstation/TerraGov-Marine-Corps#5627]
## Testmerges:

#5618: 'fixes a few bugs/typos and map bugs part2 (now with 3 incantations and a goat sacrifice for git)' by SplinterGP at commit 87f2110814
#5286: 'Hive Alerts for Hive Leaders and Damaged Low HP Xenos/Resin Silos' by Surrealaser at commit ab536568b8
#5342: 'Adds a roomba' by TiviPlus at commit d98040a8d3
#5604: 'CAS Ammo updates and cleanup' by TiviPlus at commit 3307fc86ab

## Reproduction:

I was a dead Runner and suddendly I was asked to return to my dead body If I wanted to be revived, which is non-sense because.

I cannot be revived as a Xeno.

My body was already sold therefore it's non-existant

OCCURED ON:
Round ID: [6669](https://scrubby.melonmesa.com/round/6669)

When I clicked jump it jumped my ghost to some random Marine getting revived.
This happened multiple times that round infact.

**Comment by Surrealaser** [comment]
That's strange; I don't think my PRs have touched on anything that would cause that sort of crossed wiring RE: revive messages.

**Comment by XSlayer300** [comment]
Happens to me as well. Even as a ghosted marine, who dieded.

**Comment by XSlayer300** [comment]
`/mob/living/proc/get_ghost()
	if(client) //Let's call up the correct ghost!
		return
	for(var/g in GLOB.observer_list)
		var/mob/dead/observer/ghost = g
		if(!ghost?.mind.current == src) //we can find undeletted ghost references in here, ghost deletting problem.
			continue
		if(ghost.client && ghost.can_reenter_corpse)
			return ghost
	return`
The problem of this is somewhere among these lines.
