### ISSUE TITLE
Synths can become braindamaged

### ISSUE THREAD

**Issue by HolisticDelight** [tgstation/TerraGov-Marine-Corps#5650]
## Reproduction:
1. Find rouny
2. Give him a chance to slash you
3. Enjoy braindamage without an actual way to fix it and even without real brain

**Comment by fernandos13** [comment]
huh... open skull.. nanopaste.. close skull.. set to go?

**Comment by mokulus** [comment]
Just checked but I was unable to deal brain damage to synthetic. Did anyone managed to reproduce it?

**Comment by KuzyXD** [comment]
Just checked. Unable to deal brain damage to synth.

**Comment by BraveMole** [comment]
Not reproduced
