### ISSUE TITLE
Xeno damage is delayed.

### ISSUE THREAD

**Issue by BeloneX** [tgstation/TerraGov-Marine-Corps#5681]
## Testmerges:

#5615: 'Nerfs machinepistol fire rate to 0.2 from 0.15' by Pariah919 at commit f208ed563e
#5342: 'Adds a roomba' by TiviPlus at commit 643d16a105
#5662: 'Revert "auxtools debugger (#5530)"' by TiviPlus at commit e64a73edb2
#5663: 'Tick allocation refactor' by TiviPlus at commit 730f28fe51

## Reproduction:

Get hit as Xeno, it won't deduct your health until like 1-3 seconds later.

**Comment by BraveMole** [comment]
You sure it is this TM? Cause that seems to point out very clearly to the tick allocation refractor commit

**Comment by TiviPlus** [comment]
Allocation was unTMed and issue persisted

**Comment by TiviPlus** [comment]
Also should be noted humans are also affected

**Comment by Surrealaser** [comment]
Issue is caused by something merged 100% per tests with the master.
