### ISSUE TITLE
Pounce causes a speed debuff in hunter, after the effect should have worn off.

### ISSUE THREAD

**Issue by Texicos** [tgstation/TerraGov-Marine-Corps#5694]
## Testmerges: 

 not caused by a testmerge, since this has been consistent for some time.

## Reproduction: Not exactly sure but it has something to do with pounce.

 After pouncing there is a chance that the speed debuff that applies right after pouncing just doesn't wear off.

**Comment by Surrealaser** [comment]
Runner doesn't actually get a speed debuff on pounce, it is immobilized for 0.5 seconds. Not sure if this is a false positive that is being confused with something else.

**Comment by BraveMole** [comment]
Not reproduced
