### ISSUE TITLE
Ghost issues

### ISSUE THREAD

**Issue by HolisticDelight** [tgstation/TerraGov-Marine-Corps#5708]
## Reproduction:
1.Die as human.
2.Become, lets imagine, xeno, die again, observe your human coprse, become stucked inside of it.

1.Die.
2.Observe CAS camera, stuck on it.

**Comment by TiviPlus** [comment]
Did you not press the observe button again to unobserve

**Comment by BraveMole** [comment]
Seems to be a lone bug case
