### ISSUE TITLE
Side Ponytail 2 hairstyle does not work

### ISSUE THREAD

**Issue by AtlasRules** [tgstation/TerraGov-Marine-Corps#5719]
## Reproduction:
1. Go into character set up
2. Try to give your character side ponytail 2
![image](https://user-images.githubusercontent.com/49167264/104365532-05cb9d80-5510-11eb-8f83-55265a87ad3d.png)

**Comment by AtlasRules** [comment]
pls

**Comment by AtlasRules** [comment]
if i have to fix this myself i will

**Comment by XSlayer300** [comment]
Done. #6089

**Comment by XSlayer300** [comment]
Aaand fixed.

**Comment by AtlasRules** [comment]
not the right sprite but eh

if i feel arsed to i'll add it under another name
