### ISSUE TITLE
You can pickup the stamina.

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#5743]
## Testmerges:
#5663 #5612 #5584 #5662 #5387 #5426 #5434 #5457 #5585

## Reproduction:

- I have not seen it in action myself, so, cannot reproduce.

![image](https://user-images.githubusercontent.com/35091844/104683498-fe83da00-5731-11eb-9fb0-25e243e0f0d5.png)

**Comment by SplinterGP** [comment]
wanst that a maptext sprite bug ?
