### ISSUE TITLE
B18 medical module body stabilization feature does not include the head

### ISSUE THREAD

**Issue by MickDick1** [tgstation/TerraGov-Marine-Corps#5747]
## Testmerges:

#5585 #5457 #5434 #5426 #5387 #5662 #5584 #5612 #5663

## Reproduction:

As per the title, the b18 medical system neglects the skull for stabilization.  Break your skull with b18 on, and it will not stabilize it.

If a lower tier module like the valk can full-body splint, it is clear nonsense that the super deluxe tin can super charged version the b18 is equipped with cannot.  

![b18 no splint da head](https://user-images.githubusercontent.com/76397585/104776223-bec7ed00-5747-11eb-9ef7-41e47e3cebcb.png)

**Comment by SpaceLoveSs13** [comment]
Since B18 Helmet is different from the armor that actually has the autodoc [codewise], one has to put entire autodoc system on helmet for head only. I might be wrong about this though since armor detects head anyway but doesn't splint[stabilize]. I will try to find a fix.
