### ISSUE TITLE
Wraith bug

### ISSUE THREAD

**Issue by BraveMole** [tgstation/TerraGov-Marine-Corps#5754]
## Testmerges:

#5240 

## Reproduction:

 When banish is used on dead xeno, the dead annoncment is played again. When used on a bursted colonist, the colonist comes back to life, still bursted though
 
 Also, please make this impossible Surr:
 
![Capture](https://user-images.githubusercontent.com/25491240/104817821-058b1500-5824-11eb-8f6d-00040a5d0a46.PNG)

I'm not sure why hot hot was abusing it, but the spam was insane

**Comment by Swagile** [comment]
Admins checked my hypothesis.

Said "dead bursted colonists" that are alive can be re-huggered.

This is bad for obvious reasons.

**Comment by Surrealaser** [comment]
Currently fixed
