### ISSUE TITLE
Monkey Cubes no longer react to water to become monkeys

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#5768]
## Testmerges:
#5240 #5585 #5457 #5434 #5662 #5663

## Reproduction:
Put monkey cube on the floor. Grab a fire extinguisher. Safety off. Spray the cube. It will not turn into a monkey.

**Comment by SkeletalElite** [comment]
Looks to me like monkey cubes specifically have to be used on a sink in order to turn them into monkeys
I'm pretty sure on TG you can just splash water on them or use a fire extinguisher but as far as I can tell that it's not even intended for that to be the case here.

**Comment by grinkgo** [comment]
> Looks to me like monkey cubes specifically have to be used on a sink in order to turn them into monkeys
> I'm pretty sure on TG you can just splash water on them or use a fire extinguisher but as far as I can tell that it's not even intended for that to be the case here.

that's weird tho bc it used to work perfectly fine using the fire extinguisher method. Idk how long ago this broke tho

**Comment by SplinterGP** [comment]
> > Looks to me like monkey cubes specifically have to be used on a sink in order to turn them into monkeys
> > I'm pretty sure on TG you can just splash water on them or use a fire extinguisher but as far as I can tell that it's not even intended for that to be the case here.
> 
> that's weird tho bc it used to work perfectly fine using the fire extinguisher method. Idk how long ago this broke tho

it was "broken" as intended to fix a bug and as far as it goes this shall stay as is, xenos were using monkey cubes from map and a water tank they'd blow or something to release wanter and get monkeys for free larva, so then sprayed water doenst make monkey cubes hatch no.

**Comment by TiviPlus** [comment]
You need to unwrap the monkey cube
