### ISSUE TITLE
TS34 not firing

### ISSUE THREAD

**Issue by TGCMbetcher** [tgstation/TerraGov-Marine-Corps#5771]
## Testmerges:

I just started using the TS34 and almost no one else Ive seen does which is why the xenos dont know you only have two shots and run away instead of going in after the second.

## Reproduction:

Get a TS34, have a xeno run back and forth in and out of PB range and be on 20%+ time dilation (dont know if that last one matters) It usually happens on weed but not always. PB the xeno and as it travels out of range nothing will happen, then it comes back in hits you again and leaves in .4 seconds and again the PB wont work. Dont worry though, if there is a marine on that square it will PB the marine even if you clicked when the xeno was on top. It will also hit every shot on the marine next to you if you attempt to shoot diagonally. 

Ive had this happen 7-8 times. Twice I was patient enough to PB it after half a dozen missed PBs and no firing of the gun. If the gun fired I would have been able to line up a second shot to deal heavy damage but it doesnt shoot. So I stand there like an idiot not doing anything for 15 seconds until I get too low and have to walk away. At this point Im going to skip PBs and just shoot past it because 40 damage isnt worth the constant misses.

**Comment by SplinterGP** [comment]
was it during wield time or one handed ?

**Comment by TGCMbetcher** [comment]
> was it during wield time or one handed ?

Neither, I would stand there for literally 10-20 seconds depending on the time. The one time I waited until I was almost crit to double spam the runner then limped away while it was in semi crit. Ive given up on PBs because the double spam will crit/almost crit alot of xenos anyway then I just pull out a revolver and pour 280 damage into them that way.

**Comment by TGCMbetcher** [comment]
I asked around nd it seems there is a PB delay on pretty much every shotguns and hunters/runners move fast enough that they can just get out of ranged before the PB. So dont PB a xeno on top of a marine because it will default to the marine instead.
