### ISSUE TITLE
Wraith can drag bodies while in phase shift. Phase shift is blocked by shutters even if they're open

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#5782]
## Testmerges:
#5663 #5662 #5434 #5457 #5585 #5240 #5714

## Reproduction:
I.
1.Phase shift
2.Drag a body
3.Be able to move a body with no slowdown
II.
1.Phase Shift
2.Try to move past FoB shutters

**Comment by Surrealaser** [comment]
Fixing this now

**Comment by Surrealaser** [comment]
To be clear, this should be fixed in the latest patch.

**Comment by TiviPlus** [comment]
Author says it fixed
