### ISSUE TITLE
Drop Pods can Land outside prison station

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/TerraGov-Marine-Corps#5812]
## Reproduction:

just drop pod in the ocean, bring space suit and las gun for memes.

**Comment by SpaceLoveSs13** [comment]
`/obj/structure/droppod/proc/checklanding(mob/user)
	var/turf/target = locate(target_x, target_y, 2)
	if(target.density)
		to_chat(user, "<span class='warning'>Dense Landing zone detected. Invalid area.</span>")
		return FALSE
	if(isspaceturf(target))
		to_chat(user, "<span class='warning'>Location outside mission parameters. Invalid area.</span>")
		return FALSE
	var/area/targetarea = get_area(target)
	if(!targetarea.outside)
		to_chat(user, "<span class='warning'>Cannot launch pod at a roofed area.</span>")
		return FALSE
	for(var/x in target.contents)
		var/atom/object = x
		if(object.density)
			to_chat(user, "<span class='warning'>Dense object detected in target location.</span>")
			return FALSE
	to_chat(user, "<span class='notice'>Valid area confirmed!</span>")
	return TRUE`

The water should be considered space tile after this pr gets merged. It was made specifically for ocean. #5777

**Comment by SkeletalElite** [comment]
Even if you can drop outside you die now so should be fixed
