### ISSUE TITLE
Hivelord Healing Infusion Aura Lasts Indefinitely if Source Hivelord Upgrades While it's Active

### ISSUE THREAD

**Issue by Surrealaser** [tgstation/TerraGov-Marine-Corps#5814]
## Testmerges:

N/A

## Reproduction:

Use Healing Infusion on a xeno and have it be active before you upgrade; it will break and its aura will last indefinitely as the reference datums are all deleted.

**Comment by SkeletalElite** [comment]
Did #5879 fix this @Surrealaser ?

**Comment by Surrealaser** [comment]
yes
