### ISSUE TITLE
Revolver Bug

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#5827]
## Testmerges:

Nope, caused by ammo packet. 
## Reproduction:

Step 1: Get your revolver, then load it using a speedloader. This is just to tell you that yes, the speedloaders aren't broken. 
Step 2: Shoot the bullets. 
Step 3: Take a handful of rounds out of a .44 ammo packet, and load them into the gun. 
Step 4: Shoot the bullets. 
Step 5: Try to load the gun with another speedloader after emptying it out. 
Step 6: Attempt step 5 again. Fail. 
Step 7: Get a speedloader and remove the rounds from it by hand. 
Step 8: Load the rounds from the speedloader into the gun. This somehow works. 
Step 9: Shoot the bullets. 
Step 10: Load a speedloader. It now works again. 

Steps 5 and 6 are the main issue here. The general gist of this bug is that the ammo from the .44 packet somehow breaks the ability to load the gun using speedloaders, until such time that you manually remove the bullets from a speedloader and use those to load the gun.

**Comment by TGCMbetcher** [comment]
I can attest to the fact that if you put them in a speedloader, load it, unload it, then reload with just the bullets, this bug does not happen.

**Comment by Cowbin** [comment]
I've had issues with revolvers before when trying to load with speedloaders and loose rounds at different points.  It makes it so that the revolver can never be reloaded with speedloaders again, even if the gun is emptied.  Not sure how exactly to reproduce it though.
