### ISSUE TITLE
M3-IS pattern marine armor light source deactivates when another light source is activating

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#584]
## Testmerges:
Example: flare using a hand
Or blowtorch activation using a hand

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52436633-d7740500-2b25-11e9-8fb0-df059db67634.png)

**Comment by Mark9013100** [comment]
This applies to all armor lights, in a sense, lights seem to cancel each other out. IE, having a gun with a rail flashlight will turn an armor light 'off'.

**Comment by Hughgent** [comment]
#880 #887 #888 #889 #890 #891 #893 #895 #860 #827 #839 #847 #844 #867 #904 #897 #894 #711 #814 #907 #906 #903 #864

Adding more to this bug report

With a rail light on a shotgun and the armor light on. I found that picking the lit rail light shotgun out of my inventory would remove all light sources from my mob. Turning the rail light on and off again would reset it to the proper rail light brightness.

Putting the shotgun back into the suit slot would leave the light properly on. It seemed to be only on the draw when lighting would be messed with.

**Comment by Alterist** [comment]
#532
