### ISSUE TITLE
mag harnesses or anything that has same effect doenst work and bug slots 

### ISSUE THREAD

**Issue by SplinterGP** [tgstation/TerraGov-Marine-Corps#5878]
## Testmerges:

The following pull requests are currently test merged:
#5457: 'Evasion Thwarted By Debuffs and Stagger/Slow Partial Refactor' by Surrealaser at commit 7086a31aa0
#5662: 'Revert "auxtools debugger (#5530)"' by TiviPlus at commit e64a73edb2
#5841: 'Complete overhaul of xenos larva generation' by BraveMole at commit d2d03cb3da

(not related, happened before)

## Reproduction:
1- have mag harness at gun or m35 harness on belt
2- get flinged or something and your gun doenst go back to suit or back slot
3- slot bugged and cant put stuff in it.

well mostly i think may be related to forced movement like shrike fling putting marine too away before it jacks in or something, no idea, but it bugs the slot needing someone to VV nuliffy it

**Comment by SpaceLoveSs13** [comment]
I havr had this before only way to fix it, which I know is to click e again, it removes the gun from gun storage and places the sprite from ground to hand. Don't know of this clarifies anything though.

**Comment by TiviPlus** [comment]
Have yet to see this happen?
