### ISSUE TITLE
Hand Labelers Don't Remove Old Labels

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#591]
## Reproduction:

1) Label something with a hand labeler.
2) Turn off the hand labeler.
3) Label that same something with a hand labeler.
4) Observe how it now says "itemname (First Label) (Second Label)", instead of relabelling as "itemname (Second Label)"

**Comment by Ghommie** [comment]
This is actually some sort of feature. But it would be nice to have a label scraper tool, yup.

**Comment by Rohesie** [comment]
Can always just use the initial name plus the new one.
