### ISSUE TITLE
One tile of sudden death bug

### ISSUE THREAD

**Issue by ZahaSanko** [tgstation/TerraGov-Marine-Corps#5950]
**Description**
I have no idea what happend, one tile on entire map was able to instantly kill you by dealing 1200 burn damage

https://www.youtube.com/watch?v=lh-8-7sxtKw&feature=youtu.be
I've changed this into meme but if you stop it at 0.00 you'll see a scan of dead dude with 1200 burn damage

**Comment by BraveMole** [comment]
Since it's pool PR, i guess it's insta death when going to space. I must have delete an area on the tile and didn't notice

**Comment by BraveMole** [comment]
fixed
