### ISSUE TITLE
Teleporting to a medic that revived after aghost + ghost + re-enter corpse click after revival 

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#597]
## Testmerges:
0:45 GMT time. Round LV.
Died as Xenia Mothammad. Used words: ghost, aghost, re-enter corpse by revival click, double aghost 2x.
Result:
Can't let go of "sticky teleported" to a medic that revived - Joseph Taggart.
WHEN BUCKED BUG HALTS

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52452454-0acd8880-2b54-11e9-991d-4e2241fd0cbd.png)

**Comment by Monikawales** [comment]
Create infinite metal from a chair with this bug if "sticky object" is a chair and use a wrenc on it.

**Comment by DominikPanic** [comment]
Could word it differently? I'm having a hard time understanding you.

**Comment by Monikawales** [comment]
> Could word it differently? I'm having a hard time understanding you.

This bug was fixed. never appear again
