### ISSUE TITLE
Character can't be right-clicked to check his information, can't interact with guns to double-hand them

### ISSUE THREAD

**Issue by AlmiraTheSeventh** [tgstation/TerraGov-Marine-Corps#598]
When i was shooting a M39 (with both of my hands) it just stopped aiming with both of them and i couldn't click to use it, i could unload and load magazines and shoot with one hand, but just that, i couldn't examinate my character (to check his clothes, basic information, etc.) it also mess up with the IC tab not letting me to speak, rest, sleep, pray, (It literally disappeared from my tabs) 

Some pictures to explain what's going on. 

![captura de pantalla 2019-02-07 18 43 49](https://user-images.githubusercontent.com/47437311/52452786-11371280-2b0a-11e9-9d68-17150e3526f1.png)
![captura de pantalla 2019-02-07 18 43 57](https://user-images.githubusercontent.com/47437311/52452787-11371280-2b0a-11e9-8139-261e335b8e65.png)
![captura de pantalla 2019-02-07 18 44 11](https://user-images.githubusercontent.com/47437311/52452793-1c8a3e00-2b0a-11e9-9de7-d186edcd4992.png)

**Comment by DominikPanic** [comment]
Thanks for reporting this, this was only an issue in the testmerge of #550 and has now been fixed
