### ISSUE TITLE
load-from-attachment menu can be brought up with nothing in your hands

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#600]
Put a shotgun in your armor slot, rifle on your back or in your hand. use load-from-attachment, which will pull up an options menu to select what gun to use it on, which includes the shotgun that is not in your hands. Selecting a gun not in your hand will fail, as a the gun must be in your hand to switch it. This makes the verb very clunk to use for switching your attachment on or off if you have multiple guns

**Comment by DominikPanic** [comment]
Thanks for reporting this, this was only an issue in the testmerge of #550 and has now been fixed
