### ISSUE TITLE
Corrosive acid takes way longer to melt walls than it previously did.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#6001]
It's likely that the cause is the new tick system, back when it was melting everything nearly instantly, it was over-scaled and now it takes way longer than it should. About 10 times longer than before the new tick system, maybe.

For example, weak acid can barely melt into SD walls before the SD goes off, even if applied as soon as the almao crashes ship-side.

**Comment by SplinterGP** [comment]
someone bother me to test the acid before the tick and afterwards

**Comment by BraveMole** [comment]
was fixed
