### ISSUE TITLE
Cas GAU Cannon double damage

### ISSUE THREAD

**Issue by Texicos** [tgstation/TerraGov-Marine-Corps#6019]
## Testmerges:
#5695: 'Neurospit Tweak: Stamina Damage Nerfed, Weak Neurogas Spawn and Neurotoxin Reagent Transfer Added' by Surrealaser at commit e691693818
#5855: 'Defiler Reagent Slash Rework' by Surrealaser at commit b0e11c56fe
#5978: 'adds tx-11' by Pariah919 at commit b543678c25

## Reproduction:
Stand under a GAU cannon blast, and move with the pattern of the strafe. It will deal double damage and instakill any xeno caught in it.

**Comment by Texicos** [comment]
aka, if you run away from cas you die, if you run into the cas you live.

**Comment by SkeletalElite** [comment]
That's just the way it works. It shoots a 1x3 area then the next 1x3 area then the next 1x3 area.

Not really a bug.

**Comment by TGCMbetcher** [comment]
IRL if you run away from a plane shooting bullets you get hit more as well, since you now have more time under the guns sight then if you ran towards. I dont see the issue with this.
