### ISSUE TITLE
Unable to use speech verbs, and stuck pulling objects

### ISSUE THREAD

**Issue by deadmomo69** [tgstation/TerraGov-Marine-Corps#602]
## Testmerges:
Master commit: ccd9465c08cee9ff3dc41513f0ae29330fa66c2c
The following pull requests are currently test merged:
#124: 'Prison Station' by Rohesie at commit 9b11fe276f
#590: 'Update Z.01.BigRed_v2.dmm' by Alterist at commit c7e6cdcdf6
#491: 'Adds a bolt action rifle' by Hughgent at commit 9de47d2aee
#550: 'click relay equipment and firearm patches.' by Ghommie at commit 38f4a46968
#561: 'Defiler Gas Change' by Surrealaser at commit 83486fe56f
#578: 'Cleanup' by Alterist at commit 6f20b1c94b
#577: 'MAC-15 Suppressor Fix' by AvalonHunter at commit f171b4cc7f
#576: 'Marshall to Marshal' by Rohesie at commit ed9c8deb13
#575: 'Should fix holocards' by Ghommie at commit 5d96c87894
#569: 'Ravager's second wind now goes onto cooldown properly.' by DominikPanic at commit ca6db6a96d
#567: 'Removes unused and old IRC bot code.' by DominikPanic at commit 32044e2823
#566: '" = not needed to compile' by Hughgent at commit 72b87e88d6
#565: 'Pyro spec now takes slight damage from walking over fire.' by DominikPanic at commit 71b9877051
#528: 'E to equip, now with being able to set your preferred slots!' by DominikPanic at commit 838f739455
#587: 'Yet Another Admin Tweaks PR' by DominikPanic at commit bcb68ebe16
#568: 'Briefing Huboxing 2.0' by DominikPanic at commit 9e488e6276

## Reproduction:
I don't know what really caused it, I was setting up an MG and mounted it for a moment, then unmounted it and when I realized I couldn't use speech such as 'say' and 'me', and I grabbed a pacman generator and I was stuck pulling it. I also noticed my IC tab was gone, and periodically appearing back again, I was also unable to examine anything.

**Comment by DominikPanic** [comment]
Thanks for reporting this, this was only an issue in the testmerge of #550 and has now been fixed
