### ISSUE TITLE
arm breaking every few seconds

### ISSUE THREAD

**Issue by TGCMbetcher** [tgstation/TerraGov-Marine-Corps#6031]
![Untitled2](https://user-images.githubusercontent.com/76980366/107853981-ed88c000-6de6-11eb-924e-9ea00d114eec.png)

## Reproduction:

Have over break threshold in the cryotank
Have RR larva and neuro
Have your arm break every 2-3 seconds

**Comment by TiviPlus** [comment]
Crunch tube is a feature I guess?
