### ISSUE TITLE
Condor God Vision

### ISSUE THREAD

**Issue by halitosisman** [tgstation/TerraGov-Marine-Corps#6041]
## Testmerges:

#6003: 'Makes the entire area of HE OB a devastating explosion' by SkeletalElite at commit 914b103bb6
#5714: 'LV map update by shiryu' by SplinterGP at commit 7bf18af681
#5855: 'Defiler Reagent Slash Rework' by Surrealaser at commit b0e11c56fe
#5695: 'Neurospit Tweak: Stamina Damage Nerfed, Weak Neurogas Spawn and Neurotoxin Reagent Transfer Added' by Surrealaser at commit e691693818
#5885: 'Fixes a bit over half of the sleeping signal handlers' by TiviPlus at commit 39d17b3fc6
#5959: 'Replace the lobby HTML window with a new lobby menu' by TiviPlus at commit b99dc54d4d
#5970: 'Pinpointer for pools' by BraveMole at commit 57fd9997f6
#5985: 'Pool pr, but for splinter, and now it's silos for some reason. ' by BraveMole at commit e0efad6801

## Reproduction:

Unfortunately, I do not have a screenshot of this. I found that as a synthetic, if I wore mesons, launched a firemission from the condor, exited the fire mission and then started another one I could get an unrestricted view of the whole map.

**Comment by SkeletalElite** [comment]
Reproduction for this bug is wrong.

This bug is very very old. Like so old it's happened on every TG server I've ever played that has camera mobs.

If someone knew how to fix it, it'd probably be gone by now

**Comment by TiviPlus** [comment]
Known byond issue
