### ISSUE TITLE
Disposals will flush you even if their pump is off/air reservoir is depleted.

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#608]
## Reproduction:

1) Turn off pump and/or flush disposal bin.
2) Enter bin.
3) Get flushed and die.

**Comment by Ghommie** [comment]
By good chance it's some grudgecode from the past, it automatically flush you whenever you step in a bin. Thanks for giving us a reason to remove that bad feature.

**Comment by Alterist** [comment]
it was intentional due to marines hiding in the disposals bin, so they made it flush no matter what

**Comment by DominikPanic** [comment]
I think if we make the bin able to hold only one marine that it can be safely removed.

**Comment by Rohesie** [comment]
Or you could remove the turn off pump option.
The concern for which this was made is still valid.
In general we don't really want people hiding into disposals.

**Comment by Ghommie** [comment]
Or having marines hiding in disposals count toward game completion.
And xenos being able to scavenge the bins to eject mobs inside.

**Comment by Rohesie** [comment]
It still creates situations that would completely fit a graytider/traitor hiding from security/valid hunters, but doesn't make as much sense in our game mode.
Forcing xenos to eject every bin in the ship, or risk an earlier game end, such as what happens with last xenos entering vents, creates either bording and dragged out situations, or anti-climatic ones.

Just remove the turning off option, really.
