### ISSUE TITLE
Tell people how to recharge Defib with medic backpack

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#6119]
## Testmerges:

Currently, an incredibly low amount of people know how to recharge the defib with the medic's backpack. It's simple. You just click and drag the defib to the backpack's sprite, and it fully recharges it. Hell, the charge in the backpack gets low enough, and the plus symbol even changes color, at the very least to yellow.
It's ridiculous how few people know about this, when the backpack says it can recharge your defib, but fails to explain how. Please include instructions onto the backpack when examining it, that tells you how to do it

**Comment by fernandos13** [comment]
thats literally THE BEST THING about that backpack and the reason i first started using it..
