### ISSUE TITLE
Can toggle safeties as a xeno with right click mode at any range.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6130]
## Testmerges:
#6086 #6122 #6128

## Reproduction:
1. Turn on right click mode
2. Right click a gun
![image](https://user-images.githubusercontent.com/24631139/108620498-8fec1780-7467-11eb-81cb-fabda91628be.png)

**Comment by Chaznoodles** [comment]
Might be related to marines being able to alt-click lockers to lock/unlock them at any range.

**Comment by mokulus** [comment]
This is because RightClick in `gun_helpers.dm` doesn't check if the person who right clicked the weapons has it in hand or is close. AI can probably remotely toggle safeties now. From what I've heard on discord, it will be fixed when rightclick changes go out.

**Comment by ilikesaying** [comment]
so this is why my shotgun's safeties were on

**Comment by BraveMole** [comment]
And people are saying right click is useless. Smh
