### ISSUE TITLE
Remove Crayon MRE's

### ISSUE THREAD

**Issue by Aurelien3189** [tgstation/TerraGov-Marine-Corps#616]
As a relic of the Low RP DMCA days, I feel like this conflicts with our current atmosphere as to paint us as "Lol, the crayon eating idiots" for anyone who joins up and finds a snack to begin the game with, not to mention that eating wax still sounds pretty gross.

It might act towards driving away some players by painting the first impression in this light, rather than showing us as a server that doesn't strictly enforce higher RP but encourages it.

Remove crayons and crayon flavouring from the MRE's, perhaps that would make breakfast more appetising for some.

**Comment by Alterist** [comment]
as the person who added them, you make a good point, but this isn't the place for suggestions like this
