### ISSUE TITLE
Marines can shoot weapons whilst being back-carried. 

### ISSUE THREAD

**Issue by UntoldTactics** [tgstation/TerraGov-Marine-Corps#6163]
## Reproduction: 
Marines can use weapons whilst being carried on someone's back, which means that you can pull stupid strats with light armor marines carrying heavy armor marines with very heavy gear, whilst moving very fast.
1. Wear light armor/no armor. 
2. Grab a marine, put them on your back.
3. Get that marine to use their gun.
4. Oh god unga turret.

**Comment by BraveMole** [comment]
Fixed
