### ISSUE TITLE
tx73 full auto

### ISSUE THREAD

**Issue by TGCMbetcher** [tgstation/TerraGov-Marine-Corps#6187]
## Testmerges:

No one uses it, who knows

## Reproduction:

Spam the change weapon mode to where it keep saying semi auto. Unique weapon action all the way around to normal again. You now shoot faster and have the red circle that lets you hold down the mouse to keep firing.

**Comment by TGCMbetcher** [comment]
Im just going to consider this a feature since no one, in the half dozen times Ive brought it up, has once commented on it. The weapon is garbage without this anyway nd its not like its particularly better this way.

**Comment by SplinterGP** [comment]
gun doenst exist in game anymore last i checked
