### ISSUE TITLE
PMC armor sprite light bug

### ISSUE THREAD

**Issue by UntoldTactics** [tgstation/TerraGov-Marine-Corps#6195]
## Testmerges:
#6128 

## Reproduction:
The PMC armor sprite defaults to light-on sprite state when you put it on, however the light is off. When you turn the light on, the vest sprite light is off and not shining, so it's the opposite of what should be intended.
1. Put on PMC armor, watch as your light is on, but your not making any light.
2. Turn light on, your light is emitting, but the vest sprite is not showing the light as on.

**Comment by BraveMole** [comment]
works fine
