### ISSUE TITLE
Plasma cutters can instakill pools and hivemind

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#6203]
Plasma cutters used on pools and hivemind proc a progress bar lasting a second or so that deletes them once complete regardless of health. Pools can be sniped in under a second even if they're at full health.

![image](https://user-images.githubusercontent.com/72712909/109446618-c6ee9a00-7a20-11eb-87e3-e3ee0d5b87e1.png)

**Comment by TGCMbetcher** [comment]
Call this a feature please

**Comment by Losenis** [comment]
Wait, it's actually intended?
