### ISSUE TITLE
Stealth hijack.

### ISSUE THREAD

**Issue by BeloneX** [tgstation/TerraGov-Marine-Corps#6226]
I'm pretty sure that it used to be that if a certain number of Marines are on the ground that the dropship can't be hijacked? Well even if it wasn't it would be a pretty important fix to make, as this is frequently used to hijack the rounds and falsify stats.

**Comment by BraveMole** [comment]
No, you can't:
- Call the ship if their is too many marines on the ground
- Capture the ship if their is too many marines on the ground

Hijacking by clicking the console when it's already on the ground, was always permitted

**Comment by BeloneX** [comment]
> No, you can't:
> 
> * Call the ship if their is too many marines on the ground
> * Capture the ship if their is too many marines on the ground
> 
> Hijacking by clicking the console when it's already on the ground, was always permitted

The latter is either broken or has a ridiculous high pop requirement.

**Comment by SkeletalElite** [comment]
> > No, you can't:
> > 
> > * Call the ship if their is too many marines on the ground
> > * Capture the ship if their is too many marines on the ground
> > 
> > Hijacking by clicking the console when it's already on the ground, was always permitted
> 
> The latter is either broken or has a ridiculous high pop requirement.

The pop requirement is only for ending the round not for hijacking.

Basically if marines on ground, you can't call the dropship
If marines are on the ground you can't end the round via drop ship capture.
If the alamo is already on the ground you can always hijack and go shipside as long as you can get to the console.
