### ISSUE TITLE
The removal of the smartgunner is absurd, people don't want it, why are you forcing it upon us

### ISSUE THREAD

**Issue by zzurge** [tgstation/TerraGov-Marine-Corps#6249]
Why would you remove something so integral to marines at a time when you are changing so much about xenos?
furthermore rather than embracing that fact you would instead close the merge post instead of facing it?

**Comment by SpaceLoveSs13** [comment]
#6241

**Comment by TiviPlus** [comment]
Issues are not a discusission platform
