### ISSUE TITLE
Wraith can go past open ice colony shutters with phase shift

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6264]
## Testmerges:
#6210 #6060 #6235 #6229 #5434

## Reproduction:
1. Phase shift
2. Go past open shutters

**Comment by SkeletalElite** [comment]
They can go past closed ones too

**Comment by TiviPlus** [comment]
@Surrealaser ?

**Comment by Surrealaser** [comment]
It's a mapping issue.
