### ISSUE TITLE
Eye damage effect happens despite welding protection if eyes hurt

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#6286]
Should you have eye damage from welding, welding module does not stop the blinding effect even if it causes zero damage (Not even sure if it cases zero damage or it actually does damage you). Until your eyes are fixed to full, you'll have the blinding effect as if welding without protection.

Specific circumstance: Forgot to turn helmet welding module on and plasma cut a wall. Stepped back, put welding module on, tried to plasma cut, still got the blinding effect. Turned the module on and off again and again and tried, still got blinded. Had adming aheal, tried plasma cutting again with welding module on, no blinding effect.

**Comment by SpaceLoveSs13** [comment]
Wait you didn't tell me then that you used plasma cutter without the module at first. It is not a bug, in fact welding module stops your eyes from gwtting further damaged but the effect stays 'cause plasma cutter does a lot of damage amd insta-blinds one.

**Comment by Losenis** [comment]
Wouldn't the blurriness of damage stay without triggering the visual effect of receiving damage when you're not actually receiving any damage? It feels like a bug because it's blinding you despite not actually being supposed to do anything to your eyes, regardless of having damage or not. It's meant to be full protection already.

**Comment by BraveMole** [comment]
the blinding effect happens after you get eye damage. Not a bug

**Comment by TiviPlus** [comment]
Correct the effect stays
