### ISSUE TITLE
Command Cloak stays equipped after undress naked

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#629]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52527528-f7005e80-2cda-11e9-9568-fcda6c8733b1.png)

**Comment by Alterist** [comment]
needs a required under

**Comment by Rohesie** [comment]
It's kind of realistic, though.

**Comment by DominikPanic** [comment]
I could easily fix it, the question is, if it's desirable.

**Comment by Rohesie** [comment]
I'd say in the interest of avoiding naked-caped marines it might be better to fix it.

**Comment by Monikawales** [comment]
Same with You must be wearing M3-S light armor to equip M68 Thermal Cloak!

**Comment by DominikPanic** [comment]
> 
> 
> Same with You must be wearing M3-S light armor to equip M68 Thermal Cloak!

That's intended and a balance decision.
