### ISSUE TITLE
Alt click on shield happens twice

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#6332]
Trying to fasten or unfasten the shield makes it do both fastening and unfastening, almost random when it might actually do it only once. Happened with shield on active hand, and empty hand active with shield on the other.

![image](https://user-images.githubusercontent.com/72712909/111017966-30619780-8395-11eb-9a45-f4ecf39e18b4.png)

**Comment by lbnesquik** [comment]
Can't reproduce that. I think this is a dud.
