### ISSUE TITLE
AI has no limit on camera vision groundside

### ISSUE THREAD

**Issue by jonathan123700** [tgstation/TerraGov-Marine-Corps#6380]
AI can see everything groundside if it is lit, like if there was a camera everywhere.
Steps to reproduce:
1. be AI.
2. follow somone groundside.
3. see everything where marines have left a flare/flashlight/any light.
toggle camera lights does not light up the map

Testmerges: 
#6284: 'New way of getting psy points, cocooning' by BraveMole at commit bd2f10340c
#6314: 'Revert "Add support for right click human actions"' by Pariah919 at commit 08f20b7a61
#6306: 'Cloak grenades only stealth marines, supplies cut in half' by Walarks at commit 83f054682f
#6313: 'Halves slowdown from wounds' by lKiseki at commit 9c986e3662
#5422: 'Carrier Rework - 4 New Hugger Types' by Surrealaser at commit a268e94bb7
#6273: 'Humans now take low oxy damage when critdragged' by breadhunt at commit d6aa4edbbc
#6335: 'Queue system to spawn as larva' by BraveMole at commit 3e72d02eae
I could not reproduce it on my own private server (for tests) running this codebase.
Sorry for the mess, my first issue here.
EDIT: AI can only track things that are in actual camera view, even if it can see them.
EDIT 2: while I was writing this it has fixed itself. weird

**Comment by SkeletalElite** [comment]
byond issue

**Comment by TiviPlus** [comment]
See above nothing we can do
