### ISSUE TITLE
You can not repair Synth as Marine or MO

### ISSUE THREAD

**Issue by davidchan13** [tgstation/TerraGov-Marine-Corps#6397]
## Reproduction: 
1) Be any role except Synth
2) Have a Synth with Burns anywhere on their body.
3) Use Wire on burnt body parts
4) Nothing happens. No message you are repairing them, no notification that limb isn't wounded. Not even attacking them with the wire regardless of intent.
5) Be annoyed that you can't repair synths who die of fire without nanopaste.

This is clearly some kind of oversight, Synths can repair their own damage but other people can not fix their burn damage with wire. The synth can use the wire on themselves, another person picks it up and tries every part of their body, will not attempt or accept repairs. 

Changing synth's pose (standing, buckled to chair, laying on floor, laying on table, buckled to OR table) does not fix or change the problem. Using different bundles of wire does not fix the problem (synth can use the same bundle to repair themselves when active)

**Comment by davidchan13** [comment]
Despite being told this was fixed, seems it still is not.

**Comment by BraveMole** [comment]
You can repair, but there is no feedback
