### ISSUE TITLE
Scanner report gets cut off in chat

### ISSUE THREAD

**Issue by golfer45** [tgstation/TerraGov-Marine-Corps#6401]
## Reproduction:
scan someone with hud mode off, more than half the time the report will be cut off around either the blood level or right before chems.

**Comment by TiviPlus** [comment]
@slotbot

**Comment by TiviPlus** [comment]
@Walarks

**Comment by golfer45** [comment]
Update: did some testing seems it won't get cut off if the marine is fine and has no chems, but as they get injured and have more chems in them the more gets cut off.

**Comment by BraveMole** [comment]
fixed IIRC
