### ISSUE TITLE
Wall lights powered regardless of power level

### ISSUE THREAD

**Issue by DerrickChamberlain** [tgstation/TerraGov-Marine-Corps#6402]
## Reproduction:

Smashed APC? APC with dead battery? APC breaker flipped off? No problem, just take a light replacer and slap a new and improved TGMC certified infinite light tube. Guaranteed to never run out of power, unless someone flicks the light switch which can and will result in the light tubes immediate termination and will require further replacement!

But no, lights will work with or without power, if you turn the lights off through the APC you can not turn them back on, if you power them off, you have to replace them as they will not turn back on.

Issue has been persistent for about a month now. I think I am the only one who noticed it but never thought to say anything until now.

**Comment by TiviPlus** [comment]
@BraveMole
