### ISSUE TITLE
Right Click script Marine side

### ISSUE THREAD

**Issue by BlueHNT** [tgstation/TerraGov-Marine-Corps#6403]
## Testmerges:
_N/A_

## Reproduction:
Play as a marine of any kind, get a weapon, turn on the script which turns off right click and is supposed to let you shoot instead, but it does absolutely nothing while just turning off right clicking. If this was meant then please close it, but I believe you are meant to be able to shoot your weapon while the script is running with the right click itself.

**Comment by TiviPlus** [comment]
This was originally unintended and fixed hopefully I get the time to make it shoot underbarrels soon ish
