### ISSUE TITLE
fuel tanks dont explode

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/TerraGov-Marine-Corps#642]
## Testmerges:
#626 #587 #618 #619 #638 #637 #636 #635 #633 #632 #625 #607 #562 #522 #491 #640 #622 #124
## Reproduction:
basically earlier today, had somebody unload a full rifle mag into a fuel tank on big red, then a synth tried to welderbomb the fueltank, but that failed too. 
The log for 'X catastrophically fails at refueling their welder' showed, but the fueltank wouldn't explode either.

**Comment by Ghommie** [comment]
My bad, I'm on it right away.
