### ISSUE TITLE
Tank able to drive into a space Prison station

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#643]
## Testmerges:
After death driver and gunner can still use tank verbs

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52541975-41054500-2dac-11e9-925d-85be9538ac0b.png)

**Comment by Ghommie** [comment]
#383 should deal with this. I could hazard saying it can even be testmerged, but better be safe than sorry as I need to finish up a couple things.
