### ISSUE TITLE
Removing someone using "Get mob" verb from Condor breaks it.

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#6440]
## Testmerges: 
Doesn't matter

## Reproduction: 
Get someone in condor, use PP of their mob and usr "get mob" somewhere else. Their mob gets transported but condor stays locked and non-interactable. Even if you delete it using shuttle manipulator and spawn new one in Debug > Spawn map - Place, Condor stays locked. 

P.S. Adding a remove pilot proc for Condor just like tanks for admins to do it easily would be great. Will only need to work while Condor is on ship.

**Comment by BraveMole** [comment]
Not a bug, that's an admin messing around
