### ISSUE TITLE
bugged belt harness

### ISSUE THREAD

**Issue by ZahaSanko** [tgstation/TerraGov-Marine-Corps#6454]
## Testmerges:

no idea

## Reproduction:

It happened to me at least two times
Shrike flings you with Unrelenting Force and your gun just doesn't go back to armor slot, even though I've had belt harness

**Comment by TGCMbetcher** [comment]
This is n issue with byond. The game thinks the gun is in the armor slot, client thinks its on the ground. You have to shove either the armor or the gun in a closet and close it then reopen to kill the bug. Which ever one is bugged. It happens on all stations its just a matter of the client lagging behind your computer or something and it registering in two spots. Ive had my gun register as someone elses gun before and when I fired that gun fired. Nothing you can do about it.

**Comment by SplinterGP** [comment]
> 
> 
> This is an issue with byond. The game thinks the gun is in the armor slot, client thinks its on the ground. You have to shove either the armor or the gun in a closet and close it then reopen to kill the bug. Which ever one is bugged. It happens on all stations its just a matter of the client lagging behind your computer or something and it registering in two spots. Ive had my gun register as someone elses gun before and when I fired that gun fired. Nothing you can do about it.

supposedly yes but doenst happen similarly on every server that has something similar, this has to do with trouble on some of our item moving procs
