### ISSUE TITLE
Negative jobs

### ISSUE THREAD

**Issue by Swagile** [tgstation/TerraGov-Marine-Corps#6525]
## Reproduction:

![image](https://user-images.githubusercontent.com/4703210/113898851-3bdc8e80-979a-11eb-8450-1888065e1bb0.png)

Click join game, see negative of a job role.

Maybe its related to a person cryoing?

**Comment by BraveMole** [comment]
Fix it yourself blue man

**Comment by Swagile** [comment]
> 
> 
> Fix it yourself blue man

if i knew what caused it specifically, sure, but its the first time i saw it :pensive:

**Comment by BraveMole** [comment]
Never happened again, i call admin abuse
