### ISSUE TITLE
Xenos evolving or upgrading messes with information about them.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#653]
## Reproduction:
Example 1 (Evo): If a Mature Spitter with leader and no plasma becomes a Young Praetorian, then the now Young Praetorian loses leader.
Example 2 (Upgrade): If a Young Praetorian with no plasma upgrades into a Mature Praetorian, the now Mature Praetorian gets plasma reset and has full plasma again.
Example 3: (Evo): If a Drone with leader becomes Queen, the now Queen keeps leader and takes up a leader spot, looks like this, and can have leader removed from their self (which doesn't do anything except free up a slot for leader) 
![dreamseeker_2019-02-10_23-44-28](https://user-images.githubusercontent.com/22848292/52549520-8d975300-2da1-11e9-90dc-23f309240d76.png)

**Comment by DominikPanic** [comment]
Example 2 is intended, the rest are valid points about leader persistence.
