### ISSUE TITLE
Adminhelp verb not returning

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#6601]
## Reproduction:
Ahelp. Then once ticket gets closed ahelp verb returns 15 minutes later or sometimes never. 

@TiviPlus pinged

**Comment by BraveMole** [comment]
I cannot replicate this in local serb, despite it happening all the time in the real serv...

A solution would be to not remove the verb when ahelping, i don't know why is this a thing even

**Comment by SpaceLoveSs13** [comment]
> A solution would be to not remove the verb when ahelping, i don't know why is this a thing even
That may work yes.

**Comment by TiviPlus** [comment]
```
/client/proc/giveadminhelpverb()
	verbs |= /client/verb/adminhelp
	deltimer(adminhelptimerid)
	adminhelptimerid = 0
```
causes the runtime on the first line of
[20:19:10] Runtime in adminhelp.dm, line 774: cannot read from list
so this looks like a byond version and the best way to fix it probably is to remove it completely or to port html stat panel

**Comment by SplinterGP** [comment]
problem circunvented by #6817
