### ISSUE TITLE
Wraith phase in tcomms

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#6602]
## Reproduction:

Be wraith, devolve, re-evolve to hivelord. Build tunnel and silo in LV TCOMMS room and Big Red. Even if LV one is right next to FOB, can be breached in and plasma cuttable, Big red one is not. Example:- 
![Screenshot_1](https://user-images.githubusercontent.com/68121607/114927184-d69a3480-9e4e-11eb-991c-f43ebfc87fed.jpg)

**Comment by DerrickChamberlain** [comment]
Could move it outside the map into space, OR, put space tiles in there, eitherway.

**Comment by DerrickChamberlain** [comment]
I feel dumb this already got fixed by making it so remote.
