### ISSUE TITLE
Defiler reagent slash injects larval too/purges neuro

### ISSUE THREAD

**Issue by Dolth** [tgstation/TerraGov-Marine-Corps#6619]
Hey, basically larval accelerant purges neurotoxin aswell, making reagent slash useless for neurotoxin. In fact, it's actually helping marines to fight off neurotoxin and preventing defiler from using neuro/reagent slash. Pretty sure that's a bug and not intended.

## Testmerges:

#6409 #6179 #6447

## Reproduction:

1. As a defiler, uses neurotoxin reagent slash.
2. As the marine, instantly scan yourself after first slash.
3. Observe neurotoxin is injected but instantly purged by larval accelerant.

**Comment by Dolth** [comment]
Forgot to add this : 
https://i.gyazo.com/9d5c992403a6e9288b158c958815f1af.png

**Comment by BorranScail** [comment]
I can vouch for this. My word has no weight, but I main Defiler.
