### ISSUE TITLE
Very minor bug - 2 cell range when removing small sentry to hand

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#662]
## Testmerges:
1 Grab sentry sprite on self
2 Push east

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52596632-d57daf00-2e61-11e9-8cd2-056a3081f629.png)

**Comment by Rohesie** [comment]
Are you saying you are able to retrieve the sentry without being adjacent?

**Comment by Monikawales** [comment]
> Are you saying you are able to retrieve the sentry without being adjacent?

Exactly
Same with Tank Driver or Gunner can stsart Exiting seats just before dust-off into Alamo door and teleported when Alamo is already gone

**Comment by DominikPanic** [comment]
Seems like do_after may not have adjacent?
