### ISSUE TITLE
No Webmap for Big Red

### ISSUE THREAD

**Issue by YaBoiFrey** [tgstation/TerraGov-Marine-Corps#6620]
## Reproduction:

As the title says, clicking on webmap and choosing ground shows no map, though the grid showing coordinates still works.

**Comment by JackTheJackhammer** [comment]
I don't think the TGMC devs are responsible for this. The webmaps are developed by another group. Heres they're discord: https://discord.com/invite/pjBpxHa

**Comment by YaBoiFrey** [comment]
oh really?  thanks

**Comment by TiviPlus** [comment]
![image](https://user-images.githubusercontent.com/57223640/116784548-168b2980-aa95-11eb-9560-eaaa8516ec74.png)
Works on my machine + this is webmap stuff
