### ISSUE TITLE
PO doesn't promoting above CWO.

### ISSUE THREAD

**Issue by AseFantome** [tgstation/TerraGov-Marine-Corps#6621]
## Reproduction:
Step 1: have more then 25h as PO.
![1](https://user-images.githubusercontent.com/57627192/115126024-d75cd300-9fd4-11eb-82e9-c6a358e67c71.PNG)
Step 2: check wiki.
![2](https://user-images.githubusercontent.com/57627192/115126072-29055d80-9fd5-11eb-89e4-210b17c4a840.PNG)
Step 3: cry.
![3](https://user-images.githubusercontent.com/57627192/115126080-42a6a500-9fd5-11eb-8992-1ec549cdd07e.PNG)

**Comment by SpaceLoveSs13** [comment]
`switch(playtime_mins)
		if(0 to 600) // starting
			new_human.wear_id.paygrade = "WO"
		if(601 to 3000) // 10 hrs
			new_human.wear_id.paygrade = "CWO"
		if(3001 to 6000) // 50 hrs
			new_human.wear_id.paygrade = "O1"
		if(6001 to INFINITY) // 100 hrs
			new_human.wear_id.paygrade = "O2"`

Wiki is not updated at all, don't trust it. ENS comes after 50hrs as you can see in the cords and LTJG at 100.

O1 = ENS 
O2 = LtJG

**Comment by AseFantome** [comment]
Thanks for info.

**Comment by AseFantome** [comment]
_25 hours of autism later_
![image](https://user-images.githubusercontent.com/57627192/119736543-88814380-be86-11eb-8179-e146545ffd59.png)
![image](https://user-images.githubusercontent.com/57627192/119736577-9636c900-be86-11eb-88ce-1f77a867de3f.png)

**Comment by AseFantome** [comment]
> `switch(playtime_mins) if(0 to 600) // starting new_human.wear_id.paygrade = "WO" if(601 to 3000) // 10 hrs new_human.wear_id.paygrade = "CWO" if(3001 to 6000) // 50 hrs new_human.wear_id.paygrade = "O1" if(6001 to INFINITY) // 100 hrs new_human.wear_id.paygrade = "O2"`
> 
> Wiki is not updated at all, don't trust it. ENS comes after 50hrs as you can see in the code and LTJG at 100.
> 
> O1 = ENS
> O2 = LtJG

_25 hours of autism later_
![image](https://user-images.githubusercontent.com/57627192/119737497-0f82eb80-be88-11eb-9508-2fa7dde274d3.png)
![image](https://user-images.githubusercontent.com/57627192/119737505-127ddc00-be88-11eb-872f-bf01085b9589.png)
Doesn't seems so. Something is definitely broken. **3001 / 60 = 50.02 =50h 1m 12s** 
May be later i'll check code and try to find reason.

**Comment by AseFantome** [comment]
'll reopen after i test something.
