### ISSUE TITLE
Cocking unloaded firearms drops an empty casing.

### ISSUE THREAD

**Issue by sunzu432** [tgstation/TerraGov-Marine-Corps#664]
## Testmerges:
#636 #655 #656 #657 #659 #562 #596 #615 #625 #633 #634 #635 #637 #638 #640 #645 #647 #646 #627 #618 #607 #124

## Reproduction:

Take any (loaded) firearm, remove the magazine, and cock it. It'll produce an empty casing instead of a usable round.

**Comment by DominikPanic** [comment]
This ain't an easy one to fix as there is no reference to caliber without a magazine which is what happens when you cock a gun with a loaded round but no magazine.
