### ISSUE TITLE
Bugs concerning the Condor

### ISSUE THREAD

**Issue by InTroubleWh** [tgstation/TerraGov-Marine-Corps#6714]
## Reproduction:

     You will be stuck in the CAS camera mode. _**And even after** you manage to separate yourself from your plane, everything you do after that?_ **their sound effects will loop** after certain intervals and depending on the order you triggered the sfx.
     Enter a cockpit then open the cockpit to let another PO in. This will force you to move to the backseat, normally you won't be able to access the UI from the backseat, it's so happen that while I was randomly clicking buttons during takeoff I was able to use the UI. (Possibly by activating either unique-action or resist in takeoff while on the backseat)

**Comment by BraveMole** [comment]
I don't understand anything about this issue
