### ISSUE TITLE
Boiler permaglow bug

### ISSUE THREAD

**Issue by Naaanii** [tgstation/TerraGov-Marine-Corps#6716]
## Testmerges:

#6608 #6591 #6447

## Reproduction:

Stack more than 2 globs and get the glow. After expending all globs, the glow remains. Unsure whether this is related to maturing or not.

**Comment by psykzz** [comment]
Unable to reproduce the default case.
https://streamable.com/7gywfh

I also stored a few matured and shot and still lost the glow.

**Comment by Losenis** [comment]
Happened to me once, though I'm unsure if it's the same kind of glowing. It was a way smaller glow than globholding somehow. I had leader as well.

**Comment by Wayland-Smithy** [comment]
Seems related to mixing glob types perhaps? Turning off night vision makes the emission a little easier to see.
![image](https://user-images.githubusercontent.com/64715958/116939317-00aa6f80-ac21-11eb-903c-0b359db19756.png)

**Comment by Wayland-Smithy** [comment]
Still trying to repro locally, but it may be an edge case having to do with being on fire when you shoot and decrease ammo below the glow threshold. Sucks I don't know from that case pictured I had it happen if loading and firing another glob fixes it.

Here's the code I think is responsible, so if for some reason the `glow < 2` check is skipped the light never turns off then the color is reset right after with the `set_light_range_power_color(glow, 4, color)` that would appear to always run regardless giving the tiny green glow as seen above that can be simulated if you manually call `set_light_on(TRUE)` on a boiler with no glow.
```cpp
// /mob/living/carbon/xenomorph/boiler/proc/update_boiler_glow()
...
	if(!light_on && glow >= 2)
		set_light_on(TRUE)
	else if(glow < 2 && !fire_luminosity)
		set_light_range_power_color(0, 0)
		set_light_on(FALSE)
	set_light_range_power_color(glow, 4, color)
```

**Comment by Naaanii** [comment]
I only noticed the bug after I exceeded 2 globs and I'm not sure whether it's a part of the issue but I did also mature from Elder to Ancient in that time as well. Will try to test and reproduce.
