### ISSUE TITLE
Warrior slowdown after lunge grabbing

### ISSUE THREAD

**Issue by Naaanii** [tgstation/TerraGov-Marine-Corps#6717]
## Testmerges:

#6608 #6591 #6447

## Reproduction:

Be Warrior. Lunge at near max range (unsure whether bug persists at close range or not) and grab marine or grab doesn't land. Warrior is now slower than normal (possibly due to grab slowdown), and repeated occurrences lead to it being rooted in place and this seems to stack. (Unsure about the stacking, but it does develop from a slowdown issue to being a straight up root.)

**Comment by DerrickChamberlain** [comment]
Keep it. So I can T-42 blast shane for missing me.
