### ISSUE TITLE
Cannot see players do *warcry rarely

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#6720]
## Testmerges:
#6608 #6591 #6447

## Reproduction:

- Do *warcry
- In the ghost's POV, the warcry can be heard but the emote text is not here.

**Comment by Swagile** [comment]
this happens sometimes when your not a ghost and the player making the warcry

i think its to do with other audio emotes; if you scream due to pain or something then warcry it just doesn't work sometimes

**Comment by BraveMole** [comment]
Most probably byond issue, won't fix
