### ISSUE TITLE
Drag clicking dead people onto hypersleep console (Not the pod the console) Cryos them

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6749]
## Testmerges:
#6706 #6360 #6608 #6464

## Reproduction:
1. Get a dead limited job (FC, Captain, Whatever)
2. Drag click on hypersleep console
3. Job slot given back for free

**Comment by MsSeraph** [comment]
Works with any job actually
Any human actually
Plus its not "for free", you've gotta put the effort to bring them back up

**Comment by InterroLouis** [comment]
This should have been mentioned in #6803 probably, so if nobody can reproduce this anymore it should be resolved.

**Comment by SplinterGP** [comment]
probably solved by #6803
