### ISSUE TITLE
Stop Sounds stops all sounds except for explosions

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#677]
## Testmerges:

#674 #654 #191 #618 #646 #671 #633 #596 #522 

## Reproduction:

if an admin song is playing, one through a YouTube link.
pressing the stop sound causes all sound to stop, semi-permanently.

I've heard only far off explosions, the incoming vote noise, since pressing that button.

**Comment by Rohesie** [comment]
Was this on the round where most sounds were broken for everyone, or on a regular round?

**Comment by DominikPanic** [comment]
OOC stop sounds should only stop the immediate sounds playing at that very moment, if it plays even 1 tick later you will hear it. Are you absolutely sure that's not what happened?

**Comment by Hughgent** [comment]
This was during the broken sound round.

However, for bug fixing purposes, that part about the far off explosions and vote noise are still true as they did happen during the no sound round.

**Comment by DominikPanic** [comment]
Yep it was because some sounds weren't using the same procs. Anyway, this was only a problem during a TM that is now fixed so I'm closing this.
