### ISSUE TITLE
Shoulder Holster not Holstering

### ISSUE THREAD

**Issue by Tristan63** [tgstation/TerraGov-Marine-Corps#6770]
## Reproduction: 
Apply shoulder holster from clothing vendor or equipment vendor to clothing slot
Put weapon into holster, any that fits.
Push "H" key which is the normal hotkey to unholster and holster from clothing accessory holsters
Realize it doesn't work
Post on TGMC GITHUB

This was tested by myself and Zack24 in the Sulaco hangar using a TX-7 and M44 SAA which, neither were able to be unholstered unless manually clicking holster on your persons. My keybinds are confirmed to have H as the holster verb, yet it doesn't appear to work correctly.

**Comment by SplinterGP** [comment]
no messages were given ?

**Comment by SpaceLoveSs13** [comment]
> no messages were given ?

Tested it with him that round. Nothing happens. Resetting or changing keybinds doesn't work either.

**Comment by TiviPlus** [comment]
Intended sorta, david did this in the holster refactor but we cant remove keybindings so
