### ISSUE TITLE
Sentry Monitor screen refreshes 2 tiles from sentry

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#683]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52731815-b3a23a80-2fcf-11e9-8dcc-a9fccdd2b94a.png)

**Comment by DominikPanic** [comment]
@Surrealaser

**Comment by Rohesie** [comment]
Lacking an `Adjacent` check.

**Comment by Shadow-Quill** [comment]
#662

**Comment by Shadow-Quill** [comment]
Not a bug, as far as I can tell. Yellow Eye (close to the object, but not within interaction range) means things update, but you can't interact with it otherwise @Rohesie

**Comment by DominikPanic** [comment]
Yep this is how it should work
