### ISSUE TITLE
Communications console is destructible by crusher, can be punched by warrior (I think) and can get screen broken.

### ISSUE THREAD

**Issue by UntoldTactics** [tgstation/TerraGov-Marine-Corps#6833]
## Reproduction: 
Run at communications console as crusher
Destroy it
OR
Punch comms console a few times as warrior.
Glass breaks.
Explosions and other damage can also break the console, it CAN be repaired but I'd argue that for how important the console is, it should be pretty much indestructible considering we have less useful consoles that can't be damaged or destroyed at all.

**Comment by SpaceLoveSs13** [comment]
Well is this a bug though? I think breaking consoles was infact intended.

**Comment by Wayland-Smithy** [comment]
> I think breaking consoles was infact intended.

Please tell that to the ID console that blocks a whole 25% of crusher lanes into CIC.

**Comment by ilikesaying** [comment]
comms console can be _**DELETED**_ by warrior punches

**Comment by BraveMole** [comment]
I don't see this as a bug? Console blocking the path are annoying for xeno, it being indestructible would be terrible
