### ISSUE TITLE
Aliens on top of walls are untargetable by turrets.

### ISSUE THREAD

**Issue by Isy232** [tgstation/TerraGov-Marine-Corps#6837]
## Testmerges:

Round ID: [8879](https://scrubby.melonmesa.com/round/8879)
BYOND Version: 513.1539
Server revision compiled on: 
Master commit: 2b9ed6928c6fb5459bb09787b10eced9330d8355
The following pull requests are currently test merged:
#6748: 'Datumized view refactor and new view settings' by TiviPlus at commit 5eab6db0f7

## Reproduction:

Be a queen

Go up to a turret

Build a resin wall under you

Turret stops shooting you.

You can still spit acid at it.

**Comment by TiviPlus** [comment]
#6837

**Comment by BraveMole** [comment]
I call this feature
