### ISSUE TITLE
Tank cannon attempts to hit Hide Buttons button when pressed. Red message: "firing arc"

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#684]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52732288-e1d44a00-2fd0-11e9-8c48-314ecaaa455e.png)

**Comment by DominikPanic** [comment]
@Ghommie If tank uses Fire() it should do an istype for screen objects
But I think this is fixed in #681

**Comment by Ghommie** [comment]
I'm handling this in #550.
