### ISSUE TITLE
Hivemind unable to track xenos

### ISSUE THREAD

**Issue by Isy232** [tgstation/TerraGov-Marine-Corps#6863]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [8916](https://scrubby.melonmesa.com/round/8916)
BYOND Version: 513.1539
Server revision compiled on: 
Master commit: 04a58a8717f8f650374e1f34ff7c938f6d535c44
The following pull requests are currently test merged:
#6748: 'Datumized view refactor and new view settings' by TiviPlus at commit 5eab6db0f7
#6804: 'Maybe make warrior lunge better[DNM]' by BraveMole at commit 4cf375ef8e
#6848: 'FF is gone[DNM]' by BraveMole at commit 0609d4220d

Local commit: 6a790f5566bd927b8d47d631e6da82d89ca94840
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Be hivemind

Open queen locator.

Click on a name.

Recieve the message "You will now track XXXX"

You dont actually track them and nothing changes.

**Comment by Wayland-Smithy** [comment]
Working as intended. You are "tracking" them but not like an AI, your tracker pointer (used to always point to the hive ruler) is now pointing their direction until you pick another target.

Funny just yesterday I was actually thinking of making the hive status buttons jump to xenos and silos for hivemind like I did for ghosts.

**Comment by SplinterGP** [comment]
not a issue
