### ISSUE TITLE
Right click & Middle Mouse Click allows aimbot.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6864]
## Testmerges:
#6748 #6804 #6848

## Reproduction:
--For Single Fire--
1. Hold right click on a person.
2. Drag it off.
3. Any further shots with single fire will always aim at that person, even if you're offscreen.

https://user-images.githubusercontent.com/24631139/118352439-02b2ed80-b594-11eb-8724-39490b5f464d.mp4

--For Auto Fire--
1. Have your target on the edge of the screen.
2. Hold right click on a person.
3. Without moving the cursor hold down left click.
4. Quickly move your mouse to the chatbox.
5. If done right it will automatically shoot towards the person you targeted. If done wrong you will shoot on their tile instead.

https://user-images.githubusercontent.com/24631139/118352676-393d3800-b595-11eb-80f1-644cd3c4fe6f.mov

**Comment by SkeletalElite** [comment]
finally a use for right click

/s

This is a byond issue I believe it also happens with middle click even before right click was a thing

**Comment by JackTheJackhammer** [comment]
Dear god

**Comment by 2whatever2** [comment]
> finally a use for right click
> 
> /s
> 
> This is a byond issue I believe it also happens with middle click even before right click was a thing

After some testing yes, mmb does the same thing too.
