### ISSUE TITLE
Silos generate larva in Hunt

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#6891]
TMs:
#6858: 'jaeger storage modules no longer slow you down' by Pariah919 at commit acf2f3a3d7
#6831: 'Theseus Remodel/Rework' by Alterist at commit 5c19b3de3f
#6804: 'Maybe make warrior lunge better[DNM]' by BraveMole at commit 24cf3e3bc6
#6748: 'Datumized view refactor and new view settings' by TiviPlus at commit 5eab6db0f7
#6860: 'Laser gun rebalance and edits DNM' by David-Stormwell at commit 17e01f5f3d
#6780: 'Chem rework mk 6 revenge of the chems' by jroinc at commit 94d0ec22a9

![image](https://user-images.githubusercontent.com/72712909/118686832-c32a1280-b7da-11eb-9026-76d441b4752b.png)

**Comment by TiviPlus** [comment]
fixed
