### ISSUE TITLE
[EU unofficial server] Minor bug - Cant get up from roller bed by yourself / graphical bug when Word "rest" buckled  roller bed

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#690]
## Reproduction:
graphical bug corpse drops "under" roller bed
![image](https://user-images.githubusercontent.com/45321263/52749284-bade3e00-2ff9-11e9-8c15-1b1a0d69d7d8.png)

**Comment by DominikPanic** [comment]
Can you reproduce it on our code?

**Comment by DominikPanic** [comment]
Feel free to re-open if you're able to reproduce it during a round here as I've never seen it before
