### ISSUE TITLE
Issue with the Plasma Pistol and DMR (An incredibly broken combo)

### ISSUE THREAD

**Issue by RougeNPS** [tgstation/TerraGov-Marine-Corps#6901]
## Testmerges:

Im not on the Discord so i cannot be sure.

## Reproduction:

Get a DMR, load a magazine into it. Get a plasma pistol, load a magazine into it, slip it into shoulder holster. Set DMR to take aim, use in hand once to hold with both hands, put in armor slot. Open shoulder holster inventory, remove plasma pistol, do not put plasma pistol into both hands, close shoulder holster inventory, firing either weapon first does not affect the outcome, press E so the plasma pistol goes back into the shoulder holster. Do not manually put it in, that prevents the bug from working. Equip the DMR and then wield it. It works with whatever scope you have, no attachments affect it in any way from what i can tell. Scoping in causes the plasma pistol fire to travel with the bullet and has the exact same range of the DMR which is absurdly large. It will fire till the plasma pistol runs out of ammo every time you fire the DMR. Replacing the ammo in the plasma pistol and then following the steps necessary makes the bug infinitely repeatable. Nothing you do with the DMR can ever prevent the bug from working, including not having it wielded.

Tested it on an explained it to Trialmin Zack (Forgot his exact ckey.) he confirmed to my knowledge that this was indeed a bug.

Unknown if this works with any other weapon other than the DMR. All i know is that it works with the DMR as i did no testing following this. 

Edit: It works regardless of gun you use. Does not fire when you fire a underbarrel grenade launcher or flamer. Wielding still does not affect whether the plasma fires or not. No attachments affect it oncesoever.

Edit 2: If you aim to prevent FF it does not affect it either.

**Comment by Wayland-Smithy** [comment]
You can find out what is testmerged with the OOC tab -> **Show Server Revision** verb, and they should also be listed when you connect to the lobby if there are any active.

**Comment by RougeNPS** [comment]
Yeah i checked that. Nothing that has been testmerged recently affects the plasma pistol. I checked.

**Comment by SplinterGP** [comment]
> 
> 
> Yeah i checked that. Nothing that has been testmerged recently affects the plasma pistol. I checked.

Test with other weapons please

**Comment by RougeNPS** [comment]
> Edit: It works regardless of gun you use.

Did so already. The rounder after i made this report. Works with every weapon with no issues as far as i can tell.

I obviously didnt test with every weapon (Since its not like i could get the ones locked behind req points.) but a good amount of them.
