### ISSUE TITLE
[EU unofficial server] Straight jacket dont work when press E keyboard

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#691]
## Reproduction:
Example: belt slot
Press E.
![image](https://user-images.githubusercontent.com/45321263/52750037-1a3d4d80-2ffc-11e9-8ab0-d9acd4756dc2.png)

**Comment by Monikawales** [comment]
Or press E to back slot

**Comment by Monikawales** [comment]
![image](https://user-images.githubusercontent.com/45321263/52750138-6ee0c880-2ffc-11e9-9237-fc37b25e4be2.png)

**Comment by Monikawales** [comment]
Cant use a weapon

**Comment by Monikawales** [comment]
Using E button able to remove straightjacket finally

**Comment by DominikPanic** [comment]
There may most likely be a PR fixing any sort of issues with E at the moment #679 
Also please make sure the issues you report are present on our code

**Comment by DominikPanic** [comment]
Most likely fixed in #679 if you encounter it on our code please report it again
