### ISSUE TITLE
Tadpole can't land on 99% of Barrenquilla

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#6926]
Everything that is not a building or LZ is counted as an invalid landing zone. This makes it so that there are VERY few spots for tadpole to land, spots that are easily walled in a minute or two by xenos causing tadpole to effectively be locked to either LZ or be unusable at all.

**Comment by Oscari-pog** [comment]
Actually just a xeno buff

**Comment by BraveMole** [comment]
Barrenq is kill
