### ISSUE TITLE
Shrike's Unrelenting Force keybinds do not work

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#6934]
## Testmerges
#6902, #6858, #6748, #6780, #6916, #6860

## Reproduction
Configure Unrelenting Force keybinds. Try using them, to no avail, because neither works.

**Comment by BraveMole** [comment]
Works fine for me?

You've tried both the activate and the selecting one?

**Comment by lKiseki** [comment]
On second try, the Unrelenting Force keybind seems to conflict with Ravager's Ignore Pain keybind _(somehow?)_, preventing it from working properly.
