### ISSUE TITLE
ASRS can't approve requests, ASRS tablet breaks ASRS computer, and doesn't let it approve requests after use (Not tested.) ASRS tablet can accept orders instead.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6950]
## Testmerges:
#6890 #6748 #6902 #6872 #6885 #6928

## Reproduction:
1. Use tablet
![image](https://user-images.githubusercontent.com/24631139/119597393-8205b400-be13-11eb-8861-c682b846d78b.png)
2. Try to approve requests on ASRS computer
3. Fail to accept any requests
4. Tablet can accept requests.

**Comment by TiviPlus** [comment]
@BraveMole

**Comment by BraveMole** [comment]
fixed
