### ISSUE TITLE
Orbit panel breaks when you send a client that joined a round to lobby.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#6951]
## Testmerges:
#6890 #6748 #6902 #6872 #6885 #6928

## Reproduction:
1. Oh no someone got qdelled and can't get his stuff back! Time to send him to lobby and fast track his gear to go play the game!
2. While you send them to lobby orbit panel stops working and gives an NTOS error.
![image](https://user-images.githubusercontent.com/24631139/119598150-fa20a980-be14-11eb-9897-d0f324e8ebc3.png)

3. When they rejoin/observe it finally fixes

PS.
Can I get a cookie for finding what breaks orbit panel

**Comment by SpaceLoveSs13** [comment]
That's weird though? Because essentially someone in lobby can't be followed.

**Comment by Wayland-Smithy** [comment]
People in the lobby can be orbited, they show up in the Dead section of the orbit panel with their ckeys for names.
