### ISSUE TITLE
Condor Rotary Cannon unmountable

### ISSUE THREAD

**Issue by T1MM5H** [tgstation/TerraGov-Marine-Corps#6996]
## Reproduction:
The Condor Rotary Cannon can be printed, but not mounted to hardpoints.

**Comment by SpaceLoveSs13** [comment]
It is not supposed to be mounted. Only rhe GAU-30 is supposed to be mounted as a railgun. Someone put the pre-installed rotary canon in the fab which is confusing many and is an issue regardless.

**Comment by SpaceLoveSs13** [comment]
It is not supposed to. The rotary cano  pre-installed and shouldn't be in the fab. The gau however can be mounted.
