### ISSUE TITLE
Synth ascends into using guns, bypassing restrictions and flexing with it

### ISSUE THREAD

**Issue by XupyprKZ** [tgstation/TerraGov-Marine-Corps#7016]
1. Have any gun that supports underslug grenade launcher or mini-flamethrower
2. Attach any of those two on your sweet gun (For experiment, a pulse rifle M412 and T-35 pump shotgun were used, with grenade launcher and flamethrower accordingly.)
3. Load and activate them
4. Press middle click
5. SYNTHS GOT A FLAMER AND CAN TOSS LETHAL NADES, KNEEL BEFORE SYNTHETICAL ASCENDANCE
6. Get banned :(
https://prnt.sc/13qh31s for small log

Note: Masterkey Shotgun is immune to synthetical code bypass, because shooting is attached to Left click, not Middle mouse

**Comment by SplinterGP** [comment]
Note: Masterkey Shotgun is immune to synthetical code bypass, because shooting is attached to Left click, not Middle mouse

thats actually because the masterkey uses the own gun firing, hence why it bugs the shotgun
