### ISSUE TITLE
M41a rifle oddities

### ISSUE THREAD

**Issue by Hughgent** [tgstation/TerraGov-Marine-Corps#702]
## Testmerges:

#674 #191 #618 #693 #701 #700 #699 #698 #695 #646 #550 #123

## Reproduction:

When I got a rifle from the equipment vendor in Alpha Prep, it came without an attached UGL.
I attached a Skeleton Stock and a Vertical Grip.
when shooting, it was single fire only. the weapon said it didn't have burst fire.
when shooting, it fired as fast as I was able to click.
when shooting on help intent, every bullet missed it's target.
![rifle bug](https://user-images.githubusercontent.com/45076386/52880459-a5ffc880-3127-11e9-8b68-85e51bc393d7.PNG)
when shooting on harm intent, bullets seemed to hit.
maybe #550 as that's to do with firearms?

**Comment by Ghommie** [comment]
That PR only affects atoms that have special click interactions and a couple firearm verbs. I don't quite see how it'd cause this to happen.

**Comment by Ghommie** [comment]
The problems seems to be withing the vendors code, not n° 550.
