### ISSUE TITLE
Cryo cells in medbay not working, and related missing items.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#704]
## Reproduction:
When medbay was re-done the cryo cells were not given oxygen canisters or a freezer, they wont work when I click on them, and the table with cryoxadone beakers no longer start with 4, but only 3.

**Comment by Surrealaser** [comment]
@MiniMeatwad they don't need oxygen or a freezer, and they should work unless someone broke them since I last worked on their code.

They also come preloaded with a good mix.

**Comment by TobiNerd** [comment]
When I moved the cryo cells I literally copy pasted them there, so nothing changed about their variables. And the cells and APC are in the correct areas.

**Comment by spookydonut** [comment]
cryocells are at a hardset low temperature.

**Comment by spookydonut** [comment]
Fixed by 
` [22d2e2b](/tgstation/TerraGov-Marine-Corps/pull/699/commits/22d2e2bbf0bac296037f79662d807d58acd22009)`
