### ISSUE TITLE
3rd & 4th Squads don't show up as an option inside overwatch consoles in PoS.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7044]
## Testmerges:
#7021 #6872 #6999 #6971 #6994 #7023 #7041

## Reproduction:
1. Go to overwatch
2. Check squad options
3. Alpha and Bravo are nowhere to be seen
![image](https://user-images.githubusercontent.com/24631139/120949839-fdeaef00-c777-11eb-9398-4444d12c3dd2.png)

**Comment by SpaceLoveSs13** [comment]
Zack...it's POS. Only two squads spawn in POS, always has been like that. It won't show the other two sqauds.

**Comment by ZephyrTFA** [comment]
> 
> 
> On Skyrat, something changed in the spawning system allocating players to squads other than the ones listed.

Why didn't you make a bug report then? 🤷

**Comment by KornFlaks** [comment]
> Why didn't you make a bug report then? 

It's so obvious I assumed it was a feature. ✅

**Comment by DerrickChamberlain** [comment]
I have seen this issue on Skyrat always two squads never appear, usually Delta and Bravo. I was on Theseus.

**Comment by DerrickChamberlain** [comment]
> Zack...it's POS. Only two squads spawn in POS, always has been like that. It won't show the other two sqauds.

It may be PoS, but look at the two marine squads. Alpha and Bravo, now look at the overwatch console..

**Comment by 2whatever2** [comment]
> Zack...it's POS. Only two squads spawn in POS, always has been like that. It won't show the other two sqauds.

I forgot about this, anyway you say only two squads spawn in PoS but having more than 2 squads is still possible in PoS as this just happened two rounds ago.  It's not specifically Alpha & Bravo only, and depends on the 1st two squads. I'll rename the issue.
![image](https://user-images.githubusercontent.com/24631139/122466175-8b85d480-cfeb-11eb-92bd-1d4876c4b16c.png)
