### ISSUE TITLE
Tadpole console can see xenos/everything when picking landing spot

### ISSUE THREAD

**Issue by Wayland-Smithy** [tgstation/TerraGov-Marine-Corps#7045]
## Reproduction:

1. Launch tadpole
2. Look at ground to pick a landing spot
3. Turn ON night vision
4. Be able to see Xenos in a pretty large viewing area with AI camera controls and vison everywhere

![dreamseeker_I0npeDRBlb](https://user-images.githubusercontent.com/64715958/120985943-f3f1cd80-c730-11eb-9f6f-4457393a7cda.png)

**Comment by BraveMole** [comment]
intended

**Comment by Wayland-Smithy** [comment]
bug not a feature

**Comment by BraveMole** [comment]
mate, if i say it's a feature, it's a feature. Cause i coded the stuff and wanted it that way.

**Comment by Wayland-Smithy** [comment]
just because you code something that does not cause errors does not mean it's bug free

**Comment by BraveMole** [comment]
Something that is intended is a feature, whether you like the feature or not.

**Comment by Wayland-Smithy** [comment]
it would be no different if I got some code in I personally intended to give xenos AI vision and nobody noticed till after the fact then I went to the issue and said "It's a feature stop complaining"

**Comment by BraveMole** [comment]
I'm not saying stop complaining, i'm staying stop pretending it's a bug when it's literally an intended feature.

**Comment by Wayland-Smithy** [comment]
> it's literally an intended feature

only according to you

**Comment by Wayland-Smithy** [comment]
I'm sure the intent was to allow the pilot to about landing on marines and seeing xenos is just a bonus you see no issue with.

**Comment by BraveMole** [comment]
I'm sure i pretty much know what was my intent when doing it better than you.

**Comment by Wayland-Smithy** [comment]
whatever mole then go get an issue janni to close this
