### ISSUE TITLE
Tank repair is not working as before. Impossible to fix any slot with wrench or welder 

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#705]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52883074-c6a53e00-317a-11e9-862c-afac9369e381.png)

**Comment by Ghommie** [comment]
I noticed that while testing the PR branch and erroneously(?) attributed this problem to my doing.
Unless the tgs bot is lying, it seems like I was wrong.

**Comment by DominikPanic** [comment]
This would greatly help to have the TM's in effect listen

**Comment by Ghommie** [comment]
I need to do some changes to hardpoints damaging/repairing later, this issue may still be relevant for now.
