### ISSUE TITLE
Tank system glitched. Destroyed all the modules but visually everything functional. Additionally fully destroyed tank is able to crush walls while crew inside.

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#706]
## Testmerges:
Tested just this 1st round of big red. 15/2/19

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52884250-7e881a80-317e-11e9-953c-be0ab1e66d76.png)

**Comment by Ghommie** [comment]
Yea, the tank system has some bad problems, I got many covered already. I need to resolve the vendors' firearms issue first due to priority.
