### ISSUE TITLE
Loadout Vendor Broke

### ISSUE THREAD

**Issue by HeyMyNameIsLouie** [tgstation/TerraGov-Marine-Corps#7118]
## Testmerges: 
#6971 #6994 #6998

## Reproduction: 
Opening the Loadout Vendor, it dosent reveal my previous saved loadouts and saving one does not appear anywhere in any of the categories.

**Comment by HeyMyNameIsLouie** [comment]
Update

Now it just gives me a Ntos blue screen

Not posting what was in the bluescreen until someone can confirm that it does not contain info like IP addresses or something and accidentally dox myself

**Comment by BraveMole** [comment]
fixed
