### ISSUE TITLE
Hivemind Eye opens resin doors when moving near them

### ISSUE THREAD

**Issue by MisterGrimm** [tgstation/TerraGov-Marine-Corps#7129]
## Reproduction:
While playing as the Hivemind caste your hivemind eye will open resin doors when you move near them. This can cause problems like incidentally opening doors for marines when the hivemind eye does not need to use resin doors.

**Comment by Wayland-Smithy** [comment]
Fixed in: #7074 Hivemind no longer opens doors by passing over them
