### ISSUE TITLE
E hotkey won't equip shotgun shells into the shotgun shell belt

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#714]
Small oversight.

**Comment by Rohesie** [comment]
Nor will small items go into helmets, such as protein bars.

**Comment by DominikPanic** [comment]
Funny you mention that since I made the necessary tags (non-holster belts and helmets) in #729 but I don't wanna mess with a separate mechanic entirely there so I'll do it in another PR.

**Comment by Rohesie** [comment]
Ammo doesn't go into belt slots either.

**Comment by DominikPanic** [comment]
Aaaand fixed (I mean technically it was fixed in the ticker PR but I made these slots to make ERT work, now I just added them to the prefs verb)
