### ISSUE TITLE
Queen recheck timer while new queen was spawned 5 minutes ago

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#717]
## Testmerges:
Last round of big red 2/16/19

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52895449-caad7c00-31cb-11e9-97c0-6d1d09322df0.png)

**Comment by Rohesie** [comment]
That's normal. It's a re-check timer after all. After it ends it will fail if the queen is still alive and things will go on as usual.

**Comment by DominikPanic** [comment]
Yep unless we made it into a dedicated subsystem that runs periodic checks, this is the best way to handle it even with this minor drawback.
