### ISSUE TITLE
Infinite fire resistance

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#7186]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9558](https://scrubby.melonmesa.com/round/9558)
BYOND Version: 514.1556
Server revision compiled on: 
Master commit: 48a6cdf27be6d1c792a4129fb2a48558350eba20
The following pull requests are currently test merged:
#6998: 'Loadout vendor V2.0' by BraveMole at commit b8e6049931
#7064: 'medium acid spit no longer has AMMO_EXPLOSIVE' by Pariah919 at commit 3dd3fe4a57
#7079: 'Acid Well Improvements' by Surrealaser at commit 21a5558a01
#7158: 'Lower the 'Vote started' sound volume' by lbnesquik at commit 5690e2e42c

Local commit: 123b3fb7d6c8d978047e173b772c4bd2b96857e6
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Kind of complicated but I'll try

1. Get a resin jelly as a xeno
2. Get another xeno to eat the jelly
3. Start eating the jelly as soon as they do
4. If you did it correctly, you will both get the fire resistance effect but the person who started to eat it after will have the effect permanently

**Comment by KornFlaks** [comment]
Sadly already fixed #7156

**Comment by henriquekill9576** [comment]
Truly sad
