### ISSUE TITLE
Chemrette Packets disappearing

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#7201]
## Reproduction:
Take any item out of a chemrette packet, and the packet sprite disappears. Alt clicking the tile the packet is on lets you see it where you'd see all the items on that tile. And you can still remove all the cigs from it.

**Comment by disappointedButNotSuprised** [comment]
I just put up a PR fixing this and also another bug with the bicard cig not showing up when lit
