### ISSUE TITLE
AI buttons be lost

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7253]
### Description

The AI buttons are not in the correct place with wide screen

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9675](https://scrubby.melonmesa.com/round/9675)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: b6bcf3a789e23bb21972d0e47eefb21f10708417
The following pull requests are currently test merged:
#7194: 'Prevent too many xeno at start' by BraveMole at commit 6fb8957760
#7142: 'combat shotgun can be fired one handed' by Pariah919 at commit 6ea7e96453
#7224: 'T-25 smartrifle' by Pariah919 at commit 23bae37578
#7108: 'Ravager Rage Ability' by Surrealaser at commit 6a23bbcd6d
#7242: 'Ravager plasma is now fury' by SplinterGP at commit 25a9574d6a

Local commit: ce09e624773db30dc60a5b71e58272394a90368f
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Be AI andl ook

### Screenshots

![image](https://user-images.githubusercontent.com/24830358/124338921-cde21080-dbaa-11eb-837c-31d6b058139b.png)

**Comment by BraveMole** [comment]
Wide screen is dead
