### ISSUE TITLE
You can blink marines past fog as wraith in crash.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7268]
### Description

How did no one literally find this. This would actually matter if anyone even played crash.

### Test Merges

#7194 #7142 #7224 #7108 #7242 #7263

### Reproduction Steps

1.Drag alive or dead marine to fog,
2.Dragblink inside
3.They stuck

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/124382233-ea8c5e80-dcf8-11eb-8fd1-f136418fb223.png)

**Comment by mrhugo13** [comment]
> How did no one literally find this.

> This would actually matter if anyone even played crash.

answered your own questiom

**Comment by Mechanelize** [comment]
No dead body dragging anymore
