### ISSUE TITLE
Instruments are broken.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7269]
### Description

Any other instrument besides the classic/non-synthesized ones have an insane amount of reverb and produce incomprehensible sounds, and the classic/non-synthesized instruments just break if the songs get too complicated and make the entire area they're in sound-less, this isn't an issue on either /tg/ or Fulpstation which use the exact same instrument system as we do.

### Test Merges

Not related.

### Reproduction Steps

Use any instrument and you'll get the issues described above.

**Comment by BraveMole** [comment]
Most probably byond issue? Although i don't remember tg instruments being so shit

**Comment by AnCopper** [comment]
> Most probably byond issue? Although i don't remember tg instruments being so shit

You're correct, instruments on /tg/station work perfectly with every instrument and any song that I give it, but here on TGMC all instruments besides the classic ones have insane reverb and complicated songs make the instruments completely freak out.

**Comment by Georgeur** [comment]
Used to happen to me.
Try updating your byond client. I'm now on 514.1554.

**Comment by AnCopper** [comment]
> Used to happen to me.
> Try updating your byond client. I'm now on 514.1554.

Tried it on multiple versions including the one you recommended, the issue persists.

**Comment by BraveMole** [comment]
> Tried it on multiple versions including the one you recommended, the issue persists.

Used to happen to me as well, and then i disabled instrument sounds and never any issue

**Comment by AnCopper** [comment]
> > Tried it on multiple versions including the one you recommended, the issue persists.
> 
> Used to happen to me as well, and then i disabled instrument sounds and never any issue


https://user-images.githubusercontent.com/82319489/128941999-bfa7bfa4-003c-4599-a8cd-e164b8842338.mp4
