### ISSUE TITLE
Overwatch jump to camera / AI jump to camera breaks when trying to use a letter on the keyboard

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7291]
### Description

Try to use the function of pressing the initial of the guy you're looking for, TGUI ntos happens when you do it.

### Test Merges

#7257 #7194 #7134

### Reproduction Steps

1. Open overwatch/be an ai.
2. Open jump-to-camera
3. Hit a letter
4. Ntos

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/124662193-0f402c00-dedb-11eb-8c70-48d185e960dd.png)

**Comment by BraveMole** [comment]
duplicate
