### ISSUE TITLE
Sprite Bug   Plasma Pistol Sprite in the loadout viewer is broken

### ISSUE THREAD

**Issue by GregTheEgg42069** [tgstation/TerraGov-Marine-Corps#7313]
### Description

as the title says

### Test Merges

Round ID: [9755](https://scrubby.melonmesa.com/round/9755)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 363e4b33e112b10d9917f18b70e1b78fa09d0ce2
The following pull requests are currently test merged:
#7164: 'Pepperball MK2' by Pariah919 at commit b75dcc9506
#7257: 'Clawed Huggers no longer suck' by Surrealaser at commit 60410e9d1e
#7194: 'Prevent too many xeno at start' by BraveMole at commit 876a265d0f
#7099: 'Hemodile Buff' by Surrealaser at commit 59be3ff081

### Reproduction Steps

1. make a loudout with the plasma pistol
2. view it
3. ????
4. profit

**Comment by Lumipharon** [comment]
Not really a bug. Loadout viewer displays the full icon, so this happens with anything animated.
