### ISSUE TITLE
Can't spawn in as pre-shutter larva on distress

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#7316]
### Description

Queued in larva queue. Reached position 1. Watched as 2 larva spawned in from the lobby despite PR #7265

### Test Merges

#7164: 'Pepperball MK2' by Pariah919 at commit b75dcc9506
#7257: 'Clawed Huggers no longer suck' by Surrealaser at commit 60410e9d1e
#7194: 'Prevent too many xeno at start' by BraveMole at commit 876a265d0f
#7099: 'Hemodile Buff' by Surrealaser at commit 59be3ff081

### Reproduction Steps

1. Queue in larva queue before shutters
2. Reach position 1
3. Watch as xenos spawn in from the lobby despite being in position 1

**Comment by Wayland-Smithy** [comment]
Yep that's my fault for not handling the cases where people join the queue with a respawn timer, or the queue is not empty.
