### ISSUE TITLE
Webmap and actual world differs

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#733]
## Testmerges:
Radio is not work

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52905225-52d16700-3248-11e9-8bcf-b2357317ff44.png)

**Comment by AffectedArc07** [comment]
Oh this is a problem on my end 
I haven't updated the renderer to use this repo instead of the CM2018 one

*Im competent I promise*

**Comment by AffectedArc07** [comment]
Fixed as of https://github.com/AffectedArc07/SS13WebMap/commit/4ad60610fb6e330acbe71ee820620fe13f87759b
