### ISSUE TITLE
Carrier traps don't die off weeds

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7330]
### Description

Read title

### Test Merges

idk doesn't matter since this was here almost a month ago outaging all other tms

### Reproduction Steps

1. Make trap
2. Weed die under it 
3. Trap stays

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/125153671-01fb9980-e188-11eb-89a3-06b60fc18342.png)

**Comment by BraveMole** [comment]
duplicate of https://github.com/tgstation/TerraGov-Marine-Corps/issues/6985

**Comment by 2whatever2** [comment]
I have no iq
