### ISSUE TITLE
Clicking with minigun has aimbot.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7332]
### Description

Click something accidentally while wielding minigun, try to cancel it by letting go of m1 while it winds up, after windup it keeps shooting without my inputs

### Test Merges

Doesn't mattter, no current tms affect this + this bug outaged tms

### Reproduction Steps

1. Click target

### Screenshots

https://user-images.githubusercontent.com/24631139/125154085-cb734e00-e18a-11eb-92fd-454b9fb7ffc3.mov

**Comment by BraveMole** [comment]
stop breaking my gun system you baffoon
