### ISSUE TITLE
Ravagers fury can be refilled by plasma transfer

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7334]
### Description

Read title

### Test Merges

#7134 #7164 #7257 #7194 #7099 #7270

### Reproduction Steps

1.Transfer plasma to rav

### Screenshots

https://user-images.githubusercontent.com/24631139/125154257-b4812b80-e18b-11eb-8e33-57ff46806515.mov

**Comment by Al-1ce** [comment]
Rav is kinda crippled without its ability to start out an attack. I don't feel like this is an issue and it actively encourages drones to support their team instead of running off doing whatever.

**Comment by 2whatever2** [comment]
> Rav is kinda crippled without its ability to start out an attack. I don't feel like this is an issue and it actively encourages drones to support their team instead of running off doing whatever.

Fury passively goes up to 60% at elder max.

**Comment by Al-1ce** [comment]
> Fury passively goes up to 60% at elder max.

That's still not enough to use all your abilities.

**Comment by 2whatever2** [comment]
> > Fury passively goes up to 60% at elder max.
> 
> That's still not enough to use all your abilities.

Charge was never able to be used with normal plasma so w/e
