### ISSUE TITLE
Masterkey attachment works while in burst mode

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7337]
### Description

Read Title

### Test Merges

Doesn't matter this bug outages tms

### Reproduction Steps

1. Get a gun with burst
2. Set it to burst
3. Turn on attachment
4. Shoot it.

### Screenshots

Ignore the talking, I was in a VC.

https://user-images.githubusercontent.com/24631139/125154572-29089a00-e18d-11eb-9501-b55be376fa0c.mov

**Comment by Georgeur** [comment]
and it fires at whatever rate the gun its attached to has. probably the same problem but I'll mention it.

1. get t42
2. attach masterkey shotgun
3. switch to automatic
4. fire
5. shoot 3 buckshot in 0.2 seconds

**Comment by BraveMole** [comment]
Fixed
