### ISSUE TITLE
Ravager can slash dead simplemobs for free fury

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7342]
### Description

Read title

### Test Merges

#7270 #7099 #7194 #7257 #7164 #7181

### Reproduction Steps

1. Get dead simplemob
2. Slash it as rav
3. 100% Fury bar

### Screenshots

https://user-images.githubusercontent.com/24631139/125176738-7413c300-e208-11eb-9b8a-a3ba6f47c77c.mov

**Comment by BraveMole** [comment]
@SplinterGP
