### ISSUE TITLE
Xenos heal both damage types at once

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7344]
### Description

Read title

### Test Merges

Doesn't matter this thing outaged all tms

### Reproduction Steps

1. Take brute damage
2. Take burn damage
3. Get healed via drone heal/etc. (even weed regen) Except hivelord heal though, it doesn't heal mixed damage both at once.
4. You heal 2x fast since the heal applies to both damages at once

### Screenshots

Left is buckshot db only, Right is buckshot db + laser carbine shotgun.

![image](https://user-images.githubusercontent.com/24631139/125177506-f69f8100-e20e-11eb-8d1f-48e91bcf4a30.png)

![image](https://user-images.githubusercontent.com/24631139/125177510-facb9e80-e20e-11eb-8995-cfe5762f7143.png)

**Comment by BraveMole** [comment]
yeah i agree, it's pretty dumb
