### ISSUE TITLE
Oxygen Tanks Last Forever

### ISSUE THREAD

**Issue by halitosisman** [tgstation/TerraGov-Marine-Corps#7355]
### Description

I expected the oxygen level in my emergency tank to go down, instead, it remained static at its original number.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9799](https://scrubby.melonmesa.com/round/9799)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: d365785b10332583fd53f3f263c0fb241c261837
The following pull requests are currently test merged:
#7181: 'Losing armor grants speed' by Wayland-Smithy at commit 64b0b0b498
#7164: 'Pepperball MK2' by Pariah919 at commit 82a7edc0d7
#7257: 'Clawed Huggers no longer suck' by Surrealaser at commit 3a7df2226b
#7194: 'Prevent too many xeno at start' by BraveMole at commit a09e59266a
#7099: 'Hemodile Buff' by Surrealaser at commit 59be3ff081
#7270: 'Fix Ã© keybind[DNM]' by BraveMole at commit ea3dd61dad

Local commit: 4c6554e4874abdb9a27d82e7d915dd9c9a32b20d
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Go to your local emergency oxygen closet. Get tank, get gas mask, equip the two, turn on the oxygen flow. Observe as the gauge on the oxygen tank does not move.

**Comment by AnCopper** [comment]
Not a bug, atmospherics is disabled here.

**Comment by BraveMole** [comment]
no one is breathing, not really a bug
