### ISSUE TITLE
Wearing mesons, and making a loadout as an SL gives medhud

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7363]
### Description

Read title

### Test Merges

#7181 #7164 #7257 #7194 #7099 #7270

### Reproduction Steps

1. Make loadout with meson
2. Vend loadout next round
3. Free medhud

### Screenshots

Bye free medhud

![image](https://user-images.githubusercontent.com/24631139/125231914-2e412280-e30e-11eb-87d0-c966a180436d.png)

**Comment by BraveMole** [comment]
Not a bug. SL have a free med hud in their essentials, and it's giving you all essentials if you only had one in your loadout

**Comment by 2whatever2** [comment]
> Not a bug. SL have a free med hud in their essentials, and it's giving you all essentials if you only had one in your loadout
@BraveMole 
Negative, there's no medhud in essentials given to SL, I tested this by making an SL Loadout without mesons goggles, and I was given 0 medhud

**Comment by BraveMole** [comment]
"Negative, there's no medhud in essentials given to SL" there is

**Comment by 2whatever2** [comment]
Bravemole made it an essential now so w/e
