### ISSUE TITLE
Research Outpost silo and fog landmarks are not in deep caves, even places that look to be deep underground

### ISSUE THREAD

**Issue by Wayland-Smithy** [tgstation/TerraGov-Marine-Corps#7379]
### Description

Induces rage when marines can just snipe silos with 0 risk, and unless xenos check every tile for a cave roof it's a nice silo builder noob trap since they can't be moved once built and if you were to see a silo spawn somewhere automatically during crash it's easy to assume that place would be a good silo spot for distress also, but it's not, in-fact it's the opposite.

### Test Merges

N/A but required lmao.

What is this new issue form junk?

### Reproduction Steps

Again this dumb form does not work for this case.

### Screenshots

![image](https://user-images.githubusercontent.com/64715958/125347607-fcc95680-e30f-11eb-87ad-4c31fe85e72a.png)
![image](https://user-images.githubusercontent.com/64715958/125350001-0a341000-e313-11eb-8b40-75ad5d46dd35.png)

**Comment by BraveMole** [comment]
RO is discontinued
