### ISSUE TITLE
Supply Consoles Broke. 

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#738]
## Testmerges:#729: 'Ports SSjob and SSticker, outfits, refactors job datums.' by DominikPanic at commit 79b3d1445f
#383: '[Ready](?) Tankcode sanitization.' by Ghommie at commit 08eb71e030
#737: 'Medevac stretcher no bucklee removal' by Shadow-Quill at commit 81eb5e6580
#734: 'Adds medbay access to lock/unlock televac beacons' by Shadow-Quill at commit f406b0323b
#730: 'Mateba and M44 belt fix' by Pariah919 at commit 291f80c14d
#711: 'Cell Destabilization Fix for No Charge + No Throw Mode Toggle' by Surrealaser at commit b4ab90b15f
#731: 'Crew console interface upgrade' by Menshin at commit 6ab5440204
#724: 'Stops people from teleporting to CC via televac.' by Shadow-Quill at commit e13af5c64b
#668: 'New CL Suit' by Hughgent at commit a5bf31c53e
#633: 'Chairs no longer rotate at the speed of light.' by Rohesie at commit f48310625d
#123: 'Big Red' by Rohesie at commit 6e9c81f8c1

## Reproduction:

Righto, the issue is that when you open the supply or requests consoles, NOTHING SHOWS UP to be orderable, crippling the marines logistically because of the inability to purchase additional specialist ammo or supplies. Please fix. Likely to do with the crew console interface upgrade, #731 
Never mind, I looked at what that changes, it's probably not it.

**Comment by Menshin** [comment]
How is that even related to #731 ?

**Comment by DominikPanic** [comment]
Fixed in latest commit of #729
