### ISSUE TITLE
POWER OUTAGES

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#739]
## Testmerges:#729: 'Ports SSjob and SSticker, outfits, refactors job datums.' by DominikPanic at commit 79b3d1445f
#383: '[Ready](?) Tankcode sanitization.' by Ghommie at commit 08eb71e030
#737: 'Medevac stretcher no bucklee removal' by Shadow-Quill at commit 81eb5e6580
#734: 'Adds medbay access to lock/unlock televac beacons' by Shadow-Quill at commit f406b0323b
#730: 'Mateba and M44 belt fix' by Pariah919 at commit 291f80c14d
#711: 'Cell Destabilization Fix for No Charge + No Throw Mode Toggle' by Surrealaser at commit b4ab90b15f
#731: 'Crew console interface upgrade' by Menshin at commit 6ab5440204
#724: 'Stops people from teleporting to CC via televac.' by Shadow-Quill at commit e13af5c64b
#668: 'New CL Suit' by Hughgent at commit a5bf31c53e
#633: 'Chairs no longer rotate at the speed of light.' by Rohesie at commit f48310625d
#123: 'Big Red' by Rohesie at commit 6e9c81f8c1

## Reproduction:

Rather shortly into the round the Delta and Charlie prep rooms run low on power, and the vendors cease functioning, making it impossible to prep without an engineer doing work on it. Seems like they're not getting power from the grid and just run down from the vendor use. And the lights. Needs fixing.

**Comment by DominikPanic** [comment]
Fixed in #301 thanks to @Menshin I believe
