### ISSUE TITLE
Carrier game tab egg storage doesn't work

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#7410]
### Description

Stored eggs into self as carrier. Watched my egg count not go up.

### Test Merges

#7377: 'Removes double healing from most xeno sources' by QualityVan at commit 84ea472f97
#7351: 'adds an iff-less heavy machinegun' by Pariah919 at commit db076f935f
#7181: 'Losing armor grants speed' by Wayland-Smithy at commit 64b0b0b498
#7257: 'Clawed Huggers no longer suck' by Surrealaser at commit 3a7df2226b
#7194: 'Prevent too many xeno at start' by BraveMole at commit a09e59266a
#7099: 'Hemodile Buff' by Surrealaser at commit 59be3ff081
#7373: 'Fixes Corrosive Acid Melt Times and Process Time Adjustment Math' by Surrealaser at commit 2f26ef06be
#7383: 'Fixes destroyed limbs also being broken' by QualityVan at commit debc9b201a

### Reproduction Steps

Be Carrier.
Lay egg.
Store inside self
Go to game tab and watch the egg count stay at zero.

**Comment by BraveMole** [comment]
removed from the game
