### ISSUE TITLE
You can fire on alamo while it starts hijacking, making xenos unable to escape your wrath.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7420]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Throw a cas flare on the alamo juust before it leaves by xenos calling it
2. Wait for xenos to launch the ship
3. Shoot upon them

////ALTERNATIVELY////

1. Tarp/hide near fob
2. Wait for xenos to launch the ship
3. Laz the dropship
4. Beg CIC to shoot OB

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/125579784-68490f4e-f15d-4fd0-b43b-fa5464c2cdef.png)

![image](https://user-images.githubusercontent.com/24631139/125580000-534103b2-201b-4f91-b2ea-691e57801156.png)

**Comment by 2whatever2** [comment]
![image](https://user-images.githubusercontent.com/24631139/125580254-66dd5309-5f09-4613-be37-047fbaad8d10.png)
![image](https://user-images.githubusercontent.com/24631139/125580304-0054ea27-e232-4bff-9988-b71a14817996.png)

**Comment by KornFlaks** [comment]
Nooo, you cant do this to me. This is a feature.

**Comment by BraveMole** [comment]
Possible solution : make alamo caves

**Comment by Ieteihowmee** [comment]
Guess you guys have to decide sooner whether or not to hijack or cap.
