### ISSUE TITLE
TP-17 and other high fire rate guns cause lag.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7436]
### Description

Dual wielding two TP-17's and firing them at a target is guaranteed to lag their Client because of the sheer amount of bullets on screen and the amount of bullets that hit them and the resulting chat spam of it, even on my decent gaming PC it caused me to be unable to move.

### Test Merges

Unrelated.

### Reproduction Steps

Get shot by a TP-17 dual wielder, your client will start to lag.

**Comment by SplinterGP** [comment]
Turn others combat log off in preferences

**Comment by BraveMole** [comment]
Not something fixeable
