### ISSUE TITLE
Rail flashlights are too easy to use compared to flares

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7438]
### Description

As it turns out, flares have some hefty competition, in the form of rail flashlights. 
As far as i can tell, pocket pistols with a flashlight are easier to hide than flares, smaller than them, smaller than normal flashlights, produces as much light and they do not ever run out. 

I've been seeing it for a couple games now, marines just throw guns with lights attached to them, and it really seems to work well for them. 

![image](https://user-images.githubusercontent.com/24830358/125731194-72f99048-3ad5-4926-ae52-4237911af635.png)

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9855](https://scrubby.melonmesa.com/round/9855)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 72bfd5ea7400cea5463a6f6a1596f4fbcddda411
The following pull requests are currently test merged:
#7383: 'Fixes destroyed limbs also being broken' by QualityVan at commit debc9b201a
#7373: 'Fixes Corrosive Acid Melt Times and Process Time Adjustment Math' by Surrealaser at commit 2f26ef06be
#7099: 'Hemodile Buff' by Surrealaser at commit 59be3ff081
#7194: 'Prevent too many xeno at start' by BraveMole at commit a09e59266a
#7257: 'Clawed Huggers no longer suck' by Surrealaser at commit 3a7df2226b
#7181: 'Losing armor grants speed' by Wayland-Smithy at commit 64b0b0b498
#7351: 'adds an iff-less heavy machinegun' by Pariah919 at commit db076f935f
#7377: 'Removes double healing from most xeno sources' by QualityVan at commit 84ea472f97
#7372: 'Reverts old MJP sentries change that literally killed sentries, with less sunder.' by SplinterGP at commit 00201d901e

Local commit: 64ca85def1da5dbb1c704b6f1a22ad1a479b400c
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Play.

**Comment by BraveMole** [comment]
You can carry hundreds of flares, you cannot carry more than a dozen gun in most cases

**Comment by joniroq** [comment]
Easy fix would be just rail lights turn off when dropped, same as armour lights

**Comment by davidchan13** [comment]
> Easy fix would be just rail lights turn off when dropped, same as armour lights

I'd prefer xenos having to interact/slash the light source like they have to slash marines killed by slashing. That or just make acid more effective.

Lights turning off on drop would be way to infuriating if you get stun spammed or get brain damage and collapse dropping the gun.

**Comment by BraveMole** [comment]
> > Easy fix would be just rail lights turn off when dropped, same as armour lights
> 
> I'd prefer xenos having to interact/slash the light source like they have to slash marines killed by slashing. That or just make acid more effective.
> 
> Lights turning off on drop would be way to infuriating if you get stun spammed or get brain damage and collapse dropping the gun.

that's a good idea.

I'll do that

**Comment by SplinterGP** [comment]
> > Easy fix would be just rail lights turn off when dropped, same as armour lights
> 
> I'd prefer xenos having to interact/slash the light source like they have to slash marines killed by slashing. That or just make acid more effective.
> 
> Lights turning off on drop would be way to infuriating if you get stun spammed or get brain damage and collapse dropping the gun.

Acid was already buffed.
