### ISSUE TITLE
Double Doors can only be pried open on one of the door tiles

### ISSUE THREAD

**Issue by py01** [tgstation/TerraGov-Marine-Corps#744]
As shown, attempting to pry open the door from the visible location fails. You must have access to the lower door section to pry it open.
![77ea790372712ee1da61ba36d481d5fa](https://user-images.githubusercontent.com/28164826/52920012-cff2ef80-32cd-11e9-9733-634af3ff43c6.png)

Reproduced this locally with no testmerges.

**Comment by DominikPanic** [comment]
Adjacent :cry:
