### ISSUE TITLE
Motion detector sees everyone as a enemy

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7447]
### Description

Oh god oh fuck

### Test Merges

#7383 #7181 #7372 #7151 #7259 #7267 #7432 #7431

### Reproduction Steps

1. Get motion sensor
2. Watch as they all blip red

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/125855963-8d365ead-0d20-4d49-a151-51215f5311ee.png)

**Comment by SplinterGP** [comment]
What role were you

**Comment by 2whatever2** [comment]
PO

**Comment by SplinterGP** [comment]
might be related with IFF issue, like removing and wearing ID card

**Comment by BraveMole** [comment]
trust no one. Also yeah, iff refactor, i'll fix when i'll do my MD refactor
