### ISSUE TITLE
You can't access ASRS as a ghost, and spatial agents can't see req points 

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7448]
### Description

ASRS ntos's on ghosts since they don't have a faction, and spatial agents have the faction netural so they can't see TerraGov points unless they get their faction VV edited

### Test Merges

Doesn't matter

### Reproduction Steps

1. Be spoopy ghots
2. Wonder how much req has
3. Can't as it doesn't let you use it.

////Spatial Agent///
1. Be admin
2. Wonder how much points req has
3. Can't tell as it shows up as 0 (Ignore the fact MC tab exists and you can just change your faction var.)

### Screenshots

Ghosts:
![image](https://user-images.githubusercontent.com/24631139/125864750-7da5519f-cf62-4fb6-b577-c506b7ed6e54.png)

Spatial Agents:
![image](https://user-images.githubusercontent.com/24631139/125864782-5a3bab2a-4ef4-42b4-932a-a4805f5d8a2c.png)

**Comment by lbnesquik** [comment]
I can confirm this issue is a thing

**Comment by BraveMole** [comment]
Not fixeable without a pretty consequent refactor, so this will stay
