### ISSUE TITLE
Tadpole seems to be buggy lately

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7456]
### Description

This issue is not quite perfect as i lack a lot of details, but simply put; i've seen a number of people say they couldn't move the tadpole. Generally as the AI. Even getting other people to try it didn't manage to make it move.

I haven't experienced the bug myself, but i can't find an issue which mention that there is a problem. I welcome anyone with more information to make another bug report.

### Test Merges

Can't tell you, the server is offline.

### Reproduction Steps

I haven't experienced the bug myself.

**Comment by BraveMole** [comment]
"Generally as the AI"

I don't think the ai can use the tadpole?

**Comment by lbnesquik** [comment]
> 
> 
> "Generally as the AI"
> 
> I don't think the ai can use the tadpole?

I meant that i mostly play AI, and that's where i hear about it. It's actually not relevant to the issue.

**Comment by BraveMole** [comment]
Related to another issue, duplicate
