### ISSUE TITLE
Getting shot a lot freezes your game.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#746]
## Reproduction:
If you get shot 13 times in a small time frame, your game freezes, this usually ends up killing queens when everyone focuses fire on them, and freezes xenos when they're being shot by say a sentry or a lot of marines. It basically forces you to die because you can't do anything about it. It seems to be caused by chat spam, which lags the game, example being if you're a ghost and you get 20 messages at the same time, your game still freezes, and every time there is a message in chat your game micro freezes. It might have something to do with the code that checks if things repeat and turns them into Example: A x100.

**Comment by Ghommie** [comment]
This is quite the drawback of goon chat, yep.

**Comment by DominikPanic** [comment]
Goonchat just revealed the flawed projectile system

**Comment by MiniMeatwad** [comment]
getting shot seems to not lag you anymore, look into this and see if this needs to be closed

**Comment by DominikPanic** [comment]
@MiniMeatwad That's because most fire messages were removed by my PR #827 . That is not a proper solution and can't be merged permanently, we're waiting on oranges/somene else to make a proper subsystem for goonchat href processing.
