### ISSUE TITLE
The AI can't be followed as a ghost

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7460]
### Description

If you try to follow the AI, you can't find them. Not their core or their eye.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9879](https://scrubby.melonmesa.com/round/9879)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 5ae96bbf1bf2979fe18549d7bbd0f0127cdda799
The following pull requests are currently test merged:
#7432: 'Hard del tracking, disabling and handling changes' by BraveMole at commit 304f738f92
#7267: 'Allows the AI to have interactions across Z levels.' by lbnesquik at commit c85d4ee82b
#7259: 'Hunter Haunt Replaced With Silence Ability' by Surrealaser at commit 7cf6342bc9
#7151: 'Fixes Right Click Mode for Xenos' by Surrealaser at commit 1632039c27
#7372: 'Reverts old MJP sentries change that literally killed sentries, with less sunder.' by SplinterGP at commit 00201d901e
#7181: 'Losing armor grants speed' by Wayland-Smithy at commit 64b0b0b498
#7383: 'Fixes destroyed limbs also being broken' by QualityVan at commit debc9b201a
#7452: '[DNM] Revert "IFF refactor"' by SplinterGP at commit 929e92cd45

Local commit: 34b4b3820bd8b81fb9b16863ba0a6f7743dc3b05
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Die
Try to find the AI. Fail.

**Comment by lbnesquik** [comment]
Slight note, you can find the AI in 'Observe' as it turns out.

**Comment by ivanmixo** [comment]
It's followable, just under NPCs in the orbit menu, for some reason.
