### ISSUE TITLE
Spatial agent verb resets respawn timer

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#7464]
### Description

If you become a spatial agent and then use the same verb to stop being a spatial agent, your respawn timer will make it as if you've been observing since the start of the round instead of just defaulting to your old timer, makes it so admins who are testing stuff have to get a timer outside of ss13 to be able to know when they can respawn, which can be a pain if you don't remember.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9880](https://scrubby.melonmesa.com/round/9880)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 5ae96bbf1bf2979fe18549d7bbd0f0127cdda799
The following pull requests are currently test merged:
#7432: 'Hard del tracking, disabling and handling changes' by BraveMole at commit 304f738f92
#7267: 'Allows the AI to have interactions across Z levels.' by lbnesquik at commit c85d4ee82b
#7259: 'Hunter Haunt Replaced With Silence Ability' by Surrealaser at commit 7cf6342bc9
#7151: 'Fixes Right Click Mode for Xenos' by Surrealaser at commit 1632039c27
#7372: 'Reverts old MJP sentries change that literally killed sentries, with less sunder.' by SplinterGP at commit 00201d901e
#7181: 'Losing armor grants speed' by Wayland-Smithy at commit 64b0b0b498
#7383: 'Fixes destroyed limbs also being broken' by QualityVan at commit debc9b201a
#7452: '[DNM] Revert "IFF refactor"' by SplinterGP at commit 929e92cd45

Local commit: 34b4b3820bd8b81fb9b16863ba0a6f7743dc3b05
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Wait a couple minutes after roundstart before ghosting
2. Use spatial agent verb in debug tab
3. Use it again to stop being a spatial agent
4. Watch as your respawn timer changes or even goes to 0 depending on how long the round went for

**Comment by BraveMole** [comment]
Fixed
