### ISSUE TITLE
Loadout tool snaps earpieces and ID's

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7467]
### Description

Be admin, make loadout, try to mass give, realize they have no aimmode since their id's are gone, and no headsets 

### Test Merges

#7432 #7267 #7259 #7151 #7372 #7181 #7383 #7452

### Reproduction Steps

1. Make loadout
2. Slap it on a guy
3. ID dissapears, same with headset

### Screenshots

Before: 
![image](https://user-images.githubusercontent.com/24631139/125998445-f54b6858-53bf-4ead-8df7-094f84604b82.png)
After: (How do I still have minimap, isn't that a headset thing)
![image](https://user-images.githubusercontent.com/24631139/125998420-2078c225-1445-4a6f-87a2-ea5b3debe9ac.png)

**Comment by BraveMole** [comment]
It saves the id and the headset as well, so it's erasing everything on those slots
