### ISSUE TITLE
Powerpacks are deleting powercells

### ISSUE THREAD

**Issue by Knightfall5** [tgstation/TerraGov-Marine-Corps#748]
## Reproduction:

 Not entirely sure on this one. The original powerpack I had worked just fine, and when I was running low on ammo I went back to the FOB, where I'd left the other. I assumed someone stole the powercell from it since it was gone, so I went and inserted another, reloaded, and went on my way. The powercell inside was gone when I needed to reload again a few minutes later, so I found another powercell and tossed it in. This one was gone shortly after as well, and after inserting a third powercell things completely bugged out.

The cell was 'inside' the powerpack, but remained in my hand, and I could toss it on the ground and drag it around, but not pick it up. Removing the cell from the powerpack teleported it to my hand. After a minute of doing this, the cell vanished from my hand, leaving my sprite holding a cell that no longer existed, and leaving both powerpacks unusable, as any attempt to interact with them gave a "There is no cell in the the M56 powerpack." message, leaving one stuck on my back.

Update: I did some experimenting in a new round, simply removing the cell and trying to stick it back in causes the bug to happen after a couple swaps. The cell either vanished while inside the powerpack, or becomes bugged and can't be interacted with on the ground. In addition, this bugs out every powerpack you are holding, the one on my back had it's cell vanish too and I never touched it after putting it on.

**Comment by DominikPanic** [comment]
Thanks Ghommie for fixing my fuckup :+1:
