### ISSUE TITLE
The HSG will keep firing sometimes on full auto

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#7492]
### Description

The heavy smartgun (both tad hsg and deployable hsg) will keep firing sometimes on fullauto when you let go of left click.

### Test Merges

#7442: 'Adds the HMG to marine vendors, HSG rebalance.' by Pariah919 at commit ca3c4e6be3
#7372: 'Reverts old MJP sentries change that literally killed sentries, with less sunder.' by SplinterGP at commit 00201d901e
#7432: 'Hard del tracking, disabling and handling changes' by BraveMole at commit c1a4728496

### Reproduction Steps

1. Grab the HSG (either the tad one or the deployable one)
2. fire it on fullauto for a few seconds
3. watch as it continues to fire when you let go of leftclick

**Comment by BraveMole** [comment]
Yeah there's a lot of sticky finger thing with it

**Comment by BraveMole** [comment]
@hyper2snyper
