### ISSUE TITLE
Pillar of Spring has a misplaced TerraGov Poster in preps

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#7500]
### Description

Per title. There is a misplaced TerraGov Poster in Smartgunner preps. I'm assuming it's meant to be on the wall.

### Test Merges

Irrelevant.

### Reproduction Steps

Irrelevant.

### Screenshots

![image](https://user-images.githubusercontent.com/59634950/126061242-6c791f1b-b39b-414c-a9be-3c4b122b07e4.png)

**Comment by BraveMole** [comment]
fixed iirc
