### ISSUE TITLE
You can't delete loadouts with loadout build tool

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7502]
### Description

I already know that it's stored in persistence subsystem, and I can delete it that way by deleting my named loadout from the list but w/e

### Test Merges

Doesn't matter

### Reproduction Steps

1. Make loadout
2. You want to delete it cus it missed something
3. Tool has no outright way to delete loadouts

### Screenshots

Le funny subsystem
![image](https://user-images.githubusercontent.com/24631139/126077043-62704d46-dc02-4a7e-9d40-b0396471609b.png)

**Comment by BraveMole** [comment]
just vv reee

**Comment by BraveMole** [comment]
Not a bug, it's a "missing" feature. And admins can vv anyway
