### ISSUE TITLE
HMG eats up evasion stacks, letting runner evade 3-4 times.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7503]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Go to hmg
2. Evade all their shots
3. ????
4. Profit

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/126077922-614d60af-f1d1-4c85-8f6f-f54a086b8de9.png)
![image](https://user-images.githubusercontent.com/24631139/126077931-de01a71f-a002-4d00-b584-f755b3cda1fe.png)
![image](https://user-images.githubusercontent.com/24631139/126077944-39bd6ed8-80dc-4e2b-a991-93214dae9967.png)
![image](https://user-images.githubusercontent.com/24631139/126077957-57003154-f77a-44c1-b94c-da838fe91cfc.png)
![image](https://user-images.githubusercontent.com/24631139/126077964-e23aab17-88ee-4088-9ac0-25ae36ea5629.png)

**Comment by BraveMole** [comment]
Don't think it's a bug, maybe a balance issue?
