### ISSUE TITLE
Dropping your gun just makes it keep firing

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7516]
### Description

This also makes IFF weapons lose IFF, as the IFF refractor takes the signal for IFF from your ID, the current mob shooting it doesn't exist so = no IFF signal.

### Test Merges

#7442 #7404 #7406

### Reproduction Steps

1. Shoot gun with autofire
2. Rest
3, It keeps firing

### Screenshots

https://user-images.githubusercontent.com/24631139/126087333-ba553c29-283f-45ba-9179-773c6516f7e1.mov

**Comment by BraveMole** [comment]
@hyper2snyper

**Comment by lbnesquik** [comment]
I like this. This should stay in it.
