### ISSUE TITLE
Minigun safety doesn't work, at all.

### ISSUE THREAD

**Issue by Al-1ce** [tgstation/TerraGov-Marine-Corps#7520]
### Description

I turned on the safety for my minigun when I wanted to smack a silo to death, but it didn't work and sprayed another nearby unga. This resulted in a domino effect from others and one dead marine.

### Test Merges

Round ID: [9915](https://scrubby.melonmesa.com/round/9915)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: f379cb347cbc88e399eef650613bbfb6cd9eae75
The following pull requests are currently test merged:
#7442: 'Adds the HMG to marine vendors, HSG rebalance.' by Pariah919 at commit ca3c4e6be3
#7404: 'Sentry Rework' by hyper2snyper at commit b63ae0ccdc
#7406: 'Super Rage Gives Ravager Bloodborne/Life Leech Slashing' by Surrealaser at commit 03c5d2d8dfare currently tested

### Reproduction Steps

[1] Equip T-100 minigun (I had the powerpack on too, that might be relevant but I doubt it)
[2] Turn on safety, innocently believing that you can break weeds or silos in peace now
[3] Hold down left click and become the man behind the slaughter

### Screenshots

![clowns](https://user-images.githubusercontent.com/71247506/126090631-aae2cee7-eafd-4a93-9fa2-1d067bd1c0e4.PNG)

**Comment by Passe2142** [comment]
![image](https://user-images.githubusercontent.com/82890915/126202562-5f4931b1-2f78-4399-a37a-4fecc695aeb5.png)

**Comment by Ieteihowmee** [comment]
Uh oh watch out I have seen people on here get reported for spam for posting picture replies!
