### ISSUE TITLE
Refresh button on the Follow TGUI menu does not work

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#7521]
### Description

As per title, it does not refresh the menu once you press the button.

### Test Merges

(Not relevant but)

#7406: 'Super Rage Gives Ravager Bloodborne/Life Leech Slashing' by Surrealaser at commit 03c5d2d8df
#7442: 'Adds the HMG to marine vendors, HSG rebalance.' by Pariah919 at commit ca3c4e6be3
#7515: 'Fixes the NTOS crash and round start text for MD and CMO' by Hekzder at commit d08ec53791

### Reproduction Steps

1. Go to the Follow/Orbit menu
2. Hit the refresh button, it does not work.
3. 
![image](https://user-images.githubusercontent.com/35091844/126115251-e08413d4-3f55-4ee8-9b62-d09f96ad530a.png)

**Comment by XSlayer300** [comment]
*cough cough*

no one worked on this... it's still broken

**Comment by jlsnow301** [comment]
```update_static_data()``` requires a usr and ui param which were not there
