### ISSUE TITLE
Extended revolvers do not fit in sidearm pouches

### ISSUE THREAD

**Issue by Georgeur** [tgstation/TerraGov-Marine-Corps#7526]
### Description

Extended revolvers do not fit in sidearm pouches. Mildly annoying.

### Test Merges

#7406
#7442 
#7515

### Reproduction Steps

1. Get a TP-44 combat revolver
2. Attach a TP-44 long barrel to it.
3. Try to put it inside of a sidearm pouch
4. Cry

### Screenshots

![cry](https://user-images.githubusercontent.com/68168644/126211017-d6b89853-bf75-46cd-a090-9ffdc0eea994.PNG)

**Comment by lbnesquik** [comment]
ISn't that a feature?

**Comment by Georgeur** [comment]
> ISn't that a feature?

pistol spam is bullshit and I hate it. 
but not letting extended revolvers in sidearm pouches is unnecessary.
you can still carry 21 pistols/revolvers on you, plus the pocket pistol in the boot. 

I want to acknowledge people who treat their gun like its worth more than its magazine.

**Comment by ivanmixo** [comment]
Uh this is fully intentional.

**Comment by Georgeur** [comment]
Thankfully the changes were reverted for revolvers. Thank you I forgot to close this.
