### ISSUE TITLE
Loadout buildmode doesn't save ID titles, names and rank

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7529]
### Description

bish bravemole

### Test Merges

doesn't matter

### Reproduction Steps

1. Use loadout tool 
2. It doesn't save ID title, name, and rank (It saves IFF signals so w/e)

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/126232916-3f1d6bb7-8e29-4ed8-b7a8-a0aaa5b17ca9.png)

**Comment by BraveMole** [comment]
Bravemole : The loadouts tool allows to save the JOB's title and rank

Zack: HUR DURR I VV'D ID IT NO SAVES

**Comment by MereWalker** [comment]
Oh neat. I was about to type this out. Thank you zack! Thank you for the hard work brave!

**Comment by 2whatever2** [comment]
> Bravemole : The loadouts tool allows to save the JOB's title and rank
> 
> Zack: HUR DURR I VV'D ID IT NO SAVES

The loadout tool doesn't save the job title, rank or name which is the issue report. VV edits are saved as per this screenshot.

![image](https://user-images.githubusercontent.com/24631139/126236805-09368bdb-a739-4f37-b3b1-c1973faf11a0.png)

bish bravemole!!!!!!!!!!!!

**Comment by BraveMole** [comment]
you have to vv the job, not the id

bish

**Comment by MereWalker** [comment]
How would i go about it? Im a pleb. I really want to make custom HVH.

**Comment by BraveMole** [comment]
Sorry mememins, this is the best that i can do. Tool is limited, but this ain't a bug
