### ISSUE TITLE
You can shoot shotguns onehanded, burst fire weapons don't respect burst delay

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7530]
### Description

Read title

### Test Merges

#7515 #7442 #7406 #7404

### Reproduction Steps

1. Shoot with t18 burst mode.
2. See that when you spam click it shoots faster than normal.
////Shotmgums////
1. Get shotmgum.
2. Shoot it onehanded.

### Screenshots

https://user-images.githubusercontent.com/24631139/126240935-f82601d6-a240-4b3e-9ac5-b41e2be7a016.mov

**Comment by BraveMole** [comment]
ZAAACK

**Comment by BraveMole** [comment]
@2whatever2 does this still exist?
