### ISSUE TITLE
cant order black market crate

### ISSUE THREAD

**Issue by jerman5** [tgstation/TerraGov-Marine-Corps#754]
## bug description:
for some reason beyond me it is impossible to order a black market crate and if i am correct that hacking the supply console is impossible 
## Reproduction:

attempt to order a black market crate

**Comment by DominikPanic** [comment]
Hacking the supply console is possible - just deconstruct it and pulse the board, that's the intended way to get access to contraband crates like that. Try that and if it doesn't work feel free to poke me again.

**Comment by jerman5** [comment]
ok

**Comment by jerman5** [comment]
so uh turns out you were right and that we just need to pulse the board

**Comment by DominikPanic** [comment]
All good, I'm closing this then ^^
