### ISSUE TITLE
The AI has no means to disable orders, leading to excessive ordering around.

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7542]
### Description

See title. I think the reason for this issue is that the CIC system was ported over, but you can leave CIC overwatch, unlike the AI.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [9941](https://scrubby.melonmesa.com/round/9941)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 0e14a72eabbe6a502002d7049329b2b49a69059b
The following pull requests are currently test merged:
#7406: 'Super Rage Gives Ravager Bloodborne/Life Leech Slashing' by Surrealaser at commit 03c5d2d8df
#7442: 'Adds the HMG to marine vendors, HSG rebalance.' by Pariah919 at commit e32ae2d3b2
#7515: 'Fixes the NTOS crash, round start text for MD and CMO, and missing hud icon for MD' by Hekzder at commit e31f3d0a69
#7404: 'Sentry Rework' by hyper2snyper at commit 5757ddac86

Local commit: 48330e97270d76fb112eb9f22f063ae73fe5724b
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Spawn as AI
Select an order
Try to alt click something 
Accidentally order people
Click an order button to unselect it
Alt click again. 
Order people again

**Comment by BraveMole** [comment]
ok but, why trying to alt click something?

**Comment by lbnesquik** [comment]
> 
> 
> ok but, why trying to alt click something?

You can see items on turfs more clearly that way. Have you never done it?

**Comment by BraveMole** [comment]
i didn't know you could alt click as ai?

and what hotckeys? i thought i removed them all

**Comment by lbnesquik** [comment]
> 
> 
> i didn't know you could alt click as ai?
> 
> and what hotckeys? i thought i removed them all

Turns out there are no hotkeys. My bad
