### ISSUE TITLE
Alamo doors qdels stuff around it, Sulaco has dropship crash zones that land in areas that cause holes to be poked into space

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7553]
### Description

I was too lazy to issue report it so here it is, dropship crash 1, and dropship crash 2 is the main offenders here.

### Test Merges

Doesn't matter

### Reproduction Steps

1. Hijack
2. Alamo crashes
3. Hive comes out of alamo
4. Some of the hive dies to space

### Screenshots

This is a placeholder screenshot until I care enough to get a screenshot of alamo actually hijacking into this area. As moving shuttles with shuttle manipulator after round end doesn't delete objects around it. So I've deleted some walls to show an example. I'll get an actual screenshot when it happens.
Landing Zone 1:
![image](https://user-images.githubusercontent.com/24631139/126414864-a556aba8-216f-458c-ad4e-e52c28572651.png)

Landing Zone 2
(The hole was patched by admins)
![image](https://user-images.githubusercontent.com/24631139/126414260-342c9cfc-98f1-42b8-bdfa-14c9ac43df34.png)

**Comment by BraveMole** [comment]
The easiest solution is to remove space killing xeno and marines, this caused way too many issues for barely any benefits

**Comment by TiviPlus** [comment]
Alamo qdel is intended space areas is not
