### ISSUE TITLE
Loadout saver gives wrong weapon

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#7555]
### Description

As smartgunner, if you save a loadout with the smartrifle, next time you use it it'll give you the smartgun and drums instead.

### Test Merges

#7406 #7442 #7404

### Reproduction Steps

Save loadout with T25. Next round, load it, it'll give you T29.

**Comment by BraveMole** [comment]
Yeah mjp broke loadout sg. Will fix when i have time
