### ISSUE TITLE
ammo hud dissapears when ammo type is changed

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#7558]
### Description

Title. Flamers lose ammo hud upon switching between fire/water. Laser weapons also lose ammo hud when switching between laser types. (videos courtesy of zack24/2whatever2)

### Test Merges

doesnt matter, this happened before the tms

### Reproduction Steps

1. equip a flamer/laser weapon
2. switch ammo type
3. cry as your ammo hud disappears

### Screenshots

https://user-images.githubusercontent.com/73626246/126421916-2e436a35-0ee5-4959-a22e-26754ad9ae0b.mov

https://user-images.githubusercontent.com/73626246/126422364-fa56f831-298c-4867-a8bd-c87b23f30c08.mov

**Comment by 2whatever2** [comment]
Chibi robo deserved better
