### ISSUE TITLE
ADMIN LOG: Couldn't start chat for Chippy.Owl/(Chippy.Owl)!

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#756]
## Testmerges:

#552: '[Ready]Refactors breath and health threshold code a bit.' by Ghommie at commit 05ccffca02
#633: 'Chairs no longer rotate at the speed of light.' by Rohesie at commit f48310625d
#668: 'New CL Suit' by Hughgent at commit a5bf31c53e
#729: 'Ports SSjob and SSticker, outfits, refactors job datums.' by DominikPanic at commit 176a1cbb9d
#731: 'Crew console interface upgrade' by Menshin at commit 6ab5440204
#734: 'Adds medbay access to lock/unlock televac beacons' by Shadow-Quill at commit f406b0323b
#742: 'Fixing the not fixed energy guns description' by Ghommie at commit b2a1b3d0c5
#743: 'Fix areas powerstate not properly updating for discrete power use' by Menshin at commit daff7db5f0
#123: 'Big Red' by Rohesie at commit 6e9c81f8c1

## Reproduction:

At the start of the round:
![ocpg0on](https://user-images.githubusercontent.com/42041276/52926264-d6a45580-3313-11e9-9981-51c56fcf5131.png)

No runtimes.

**Comment by DominikPanic** [comment]
As Wire put it, there will always be that one person for which goonchat will not work due to a variety of reasons. Are there any associated runtimes with this?
