### ISSUE TITLE
Cable cuffs and zipties don't have sprites when put on someone.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7561]
### Description

It also stays even after cuffs are removed. Aheals fix it.

### Test Merges

Doesn't matter, this outaged the tms

### Reproduction Steps

1. Get ziptie/cablecuff
2. Use on self or other person
3. Honk.dmi

### Screenshots

https://user-images.githubusercontent.com/24631139/126507439-23157e26-7df1-4a82-8d83-719beb801380.mov

**Comment by Dolth** [comment]
Can be fixed with ahealing.
