### ISSUE TITLE
the lollipop pouch from the marine vendors doesnt give lollipops

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#7580]
### Description

Title.

### Test Merges

doesnt matter

### Reproduction Steps

1. walk up the marine starting vendor
2. vend lollipop pouch
3. cry as you get no lollipops

**Comment by Al-1ce** [comment]
Why should it spawn with them? That'd be like the medkit pouch spawning with bic+kelo+etc
