### ISSUE TITLE
Zippo lighter falls to the floor when trying to get it from a cigar´s packet

### ISSUE THREAD

**Issue by AgentMA1** [tgstation/TerraGov-Marine-Corps#7582]
### Description

When i grab a zippo from my packet i expect to use it, not to let it in the floor. But guess what happens!

Minor QoL issue.

### Test Merges

#7404
#7442
#7406

### Reproduction Steps

1.grab any Cigars packet
2. grab a zippo
3. pull a cigar out and put the zippo inside
4. pull zippo out, it will drop in the floor

**Comment by BraveMole** [comment]
Fixed
