### ISSUE TITLE
Drop-Pods qdel their content when they get destroyed.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7596]
### Description

When a drop-pod gets destroyed and there is a person in it, the person gets deleted.

It should just eject you instead.

### Test Merges

Not relevant.

### Reproduction Steps

See Description.

**Comment by Glassmanner** [comment]
yep this glitch just happened to me. the second my pod hit ground it got deleted and my character got deleted. I did land right between marine fire and xenos so I think that caused the pod being deleted.
Round ID: 9994 Char name: Jason M Coomers Time was around 13:05
