### ISSUE TITLE
Rune  letter graffiti can be drawn after putting in autodoc

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#760]
## Testmerges:
1 Take a crayon Press floor to drawn a rune 
2 someone put you in autodoc
3 rune is drawn

## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52929409-60c0de00-3355-11e9-9c4e-a26fb91caabf.png)

**Comment by DominikPanic** [comment]
This may be a bug with the entire do_after, try it with similar channeled actions.

**Comment by psykzz** [comment]
Is this still possible with the recent `do_after` changes?

**Comment by DominikPanic** [comment]
Looks fixed.
