### ISSUE TITLE
Wraiths can enter OB Shutters and Escape Shuttle

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#7600]
### Description

1.Wraiths can board alamo and then go to OB Shutters, the one located front of Ob and railgun that never open and is covered by hulls. This is a completely inaccessible area and marines can't ever reach there. 

2.Wraiths can also enter into Sulaco Escape shuttles(2) and POS(1). These are still pretty much kinda inaccessible. Yes they can be entered in a very specific way but this was never intended as @Surrealaser himself removed SD access from wraith too.

### Test Merges

Not Required

### Reproduction Steps

Be wraith.
Board alamo.
Get to Ob shutters/railgun shutters.
Or,
Get inside escape shuttle.
(Both with phasing)

**Comment by Surrealaser** [comment]
Mapping issue more than anything but I will look into adding flags that make certain areas inaccessible.
