### ISSUE TITLE
Droids and drones. Oh my! (drones/droids breaking)

### ISSUE THREAD

**Issue by MereWalker** [tgstation/TerraGov-Marine-Corps#7601]
### Description

1. When buying the Unmanned remote you are given a box of 11x35mm ammo
2. When trying to use the drones/droids once linked you cant unlink or link to another drone/droid.
3. When buying any of the three droids you must use a wrench to take off an invisible turret on the droid. It also still shows up when taken off but won't fire if placed back on.
4. Drones/Droids will randomly not respond for some unknown reason.

### Test Merges

#7024: 'Unmanned vehicles can be controlled by AI + general improvements of them' by BraveMole at commit 25f6a2cd46
#7442: 'Adds the HMG to marine vendors, HSG rebalance.' by Pariah919 at commit d91ba0afc2
#7406: 'Super Rage Gives Ravager Bloodborne/Life Leech Slashing' by Surrealaser at commit 03c5d2d8df
#7491: 'LV624: LZ2 revamp plus minor cave adjustments' by RipGrayson at commit b4d4478aa4

### Reproduction Steps

1. Buy a remote get ammo
2. Link with a drone/droid
3. Buy a drone
4. It randomly happens

**Comment by BraveMole** [comment]
_When buying the Unmanned remote you are given a box of 11x35mm ammo_

Fixed 

_When trying to use the drones/droids once linked you cant unlink or link to another drone/droid._

Fixed

_When buying any of the three droids you must use a wrench to take off an invisible turret on the droid. It also still shows up when taken off but won't fire if placed back on._

fixed

_Drones/Droids will randomly not respond for some unknown reason._

I need more info on this, as an AI? as someone with remote? Was their an ai maybe stealing the control?

**Comment by MereWalker** [comment]
The drones/droids not responding. I'm not entirely sure but I think when you go out a certain amount of tiles from your body you will not be able to get a response. Sorry for being vague. The problem happened and I was not sure as to why and was unable to reproduce it.
