### ISSUE TITLE
Health Scanner Report Bugged

### ISSUE THREAD

**Issue by Alexeivichi** [tgstation/TerraGov-Marine-Corps#7608]
### Description

Health scanners not showing full details. Doesn't show brute, only shows overall brute damage. Burns not affected. Also seems to affect formatting of health scan windows(e.g Reagent reports can also show up in the same line as where value of brute damage should be). Users TiviPlus and Losenis also encountered this issue with people having "Tramadol" in their damage reports.

### Test Merges

#7024: 'Unmanned vehicles can be controlled by AI + general improvements of them' by BraveMole at commit f773141a74
#7496: 'warding doenst make you recover/die less on crit.' by SplinterGP at commit 3ed41020fe
#7491: 'LV624: LZ2 revamp plus minor cave adjustments' by RipGrayson at commit 27ef82d023

### Reproduction Steps

1) Acquire HF2 Health Scanner
2) Go heal damaged humans
3) Scan said damaged humans
4) Day ruined.

### Screenshots

![image](https://user-images.githubusercontent.com/71671162/126881822-ea1d63c8-3043-4def-8173-703b445fe504.png)

**Comment by Ridgyaxe** [comment]
![image](https://user-images.githubusercontent.com/44854487/126910334-112b2285-5cb4-4d03-95a3-ca26ba0a6b0b.png)
![image](https://user-images.githubusercontent.com/44854487/126910430-589077ba-07f3-49a3-9c68-957302a976e6.png)
