### ISSUE TITLE
Warrior punch unable to target turrets

### ISSUE THREAD

**Issue by spiderhandsmcgee** [tgstation/TerraGov-Marine-Corps#7645]
### Description

Warrior punch is supposed to knock turrets over, it instead is unable to be used on them.

### Test Merges

#7491: 'LV624: LZ2 revamp plus minor cave adjustments' by RipGrayson at commit 27ef82d023
#7496: 'warding doenst make you recover/die less on crit.' by SplinterGP at commit 3ed41020fe
#7543: 'Increases price of acid turrets to 150' by Hekzder at commit 4038290c7f
#7372: 'Reverts old MJP sentries change that literally killed sentries, with less sunder.' by SplinterGP at commit 00201d901e
#7599: 'Fix Diagonal movement speed' by Raven-Industries at commit 3270583031

### Reproduction Steps

1. Be warrior
2. Find turret
3. Try to punch it
4. Cry

### Screenshots

![cant punch turrets moment](https://user-images.githubusercontent.com/88055765/127211827-f8e077ef-78d5-427a-aed6-7f7020571eee.PNG)

**Comment by Surrealaser** [comment]
Addressing this here: https://github.com/tgstation/TerraGov-Marine-Corps/pull/7615
