### ISSUE TITLE
Ghosts seem to be able to interact with intel computers.

### ISSUE THREAD

**Issue by Rexdyer1** [tgstation/TerraGov-Marine-Corps#7646]
### Description

While observing as a ghost I noticed that I was able to click the buttons for the intel computer. I did not do it fully so I was not able to see what limits that it has. Just thought it was something that could use investigating

### Test Merges

#7404: 'Sentry Rework' by hyper2snyper at commit 8fd5ca912e
#7543: 'Increases price of acid turrets to 150' by Hekzder at commit 4038290c7f
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7613: 'Stalemate respawn buff' by BraveMole at commit 07a250413b
#7624: 'minigun buff and resprite' by Pariah919 at commit 32808e7389

### Reproduction Steps

1. go to an active intel computer
2. click on the prompt. 
3. it activates however I am not sure if it will go beyond that prompt

**Comment by ivanmixo** [comment]
It's purely visual for the ghost clicking the computer.
