### ISSUE TITLE
Cancelling evacuation apparently cancels the self destruct

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7668]
### Description

I am not 100% sure if it was linked or if someone else pressed a button, but cancelling evac cancels the SD.
Given there are no indications that this would disable the SD, it may be unintended behavior.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [10070](https://scrubby.melonmesa.com/round/10070)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 4cc9ddb693239fb56f8348040c9e0b87278f7171
The following pull requests are currently test merged:
#7624: 'minigun buff and resprite' by Pariah919 at commit 32808e7389
#7613: 'Stalemate respawn buff' by BraveMole at commit 07a250413b
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7404: 'Sentry Rework' by hyper2snyper at commit 8fd5ca912e
#7543: 'Increases price of acid turrets to 150' by Hekzder at commit 4038290c7f

Local commit: b96f60e48dfab89a78b9fe9f9cc2f48bc9803b23
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

(Not sure)
Trigger red alert
Trigger evac
Trigger SD.
Cancel evac
See SD get turned off

**Comment by Wayland-Smithy** [comment]
Does SD come back online if you trigger evac again? I feel like this is not a bug.
