### ISSUE TITLE
ERT's apparently have a tendency to poof away and ghost everyone

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7670]
### Description

I spawned as a CLF ert. Someone pressed depart. We heard engine noises, and seconds later, everyone got forced to ghost
There was no warning or anything.

I was told on discord that this happened before, but i see no issue regarding it.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [10070](https://scrubby.melonmesa.com/round/10070)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 4cc9ddb693239fb56f8348040c9e0b87278f7171
The following pull requests are currently test merged:
#7624: 'minigun buff and resprite' by Pariah919 at commit 32808e7389
#7613: 'Stalemate respawn buff' by BraveMole at commit 07a250413b
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7404: 'Sentry Rework' by hyper2snyper at commit 8fd5ca912e
#7543: 'Increases price of acid turrets to 150' by Hekzder at commit 4038290c7f

Local commit: b96f60e48dfab89a78b9fe9f9cc2f48bc9803b23
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Be CLF.
Press depart on the ERT shuttle. 
Ghost.

**Comment by BraveMole** [comment]
Doesn't happen anymore from the look of it
