### ISSUE TITLE
MAPLOAD: SD inoperable due to load order issue with Evac controller

### ISSUE THREAD

**Issue by francinum** [tgstation/TerraGov-Marine-Corps#768]
`/datum/authority/branch/evacuation` is setup in new() which is called before the Thesus is loaded, resulting in `dest_master` and `dest_rods` being null.

These must be set up at a later runlevel.

**Comment by francinum** [comment]
@spookydonut

**Comment by MrStonedOne** [comment]
would we just need to initialize shuttle earlier? is there any reason it has to initialize so late?

**Comment by DominikPanic** [comment]
Evac authority is done in world/new

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/blob/0fc0a2dfc7c79df57017f8094ce009791c619152/code/controllers/stonedmc/subsystem/atoms.dm#L26

**Comment by DominikPanic** [comment]
Oh then it's my PR fuckup since I added it to world.new, let me unfuck this

**Comment by DominikPanic** [comment]
Working fine in master, confirmed fix in latest commit of #729
