### ISSUE TITLE
Book cases are indestructible

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#769]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52980835-20ad3a00-33ed-11e9-82e4-65e8433c1457.png)

**Comment by DominikPanic** [comment]
@Ghommie

**Comment by Ghommie** [comment]
I'll be on it.

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by DominikPanic** [comment]
Should be okay now
