### ISSUE TITLE
All tank modules was destroyed by crates Ice Colony

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#770]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52982532-9d451600-33f7-11e9-9db7-510d11c2da86.png)

**Comment by Monikawales** [comment]
All except active module. And armor.

**Comment by Monikawales** [comment]
![image](https://user-images.githubusercontent.com/45321263/52983005-0d549b80-33fa-11e9-88c9-10bf8e4beba4.png)
This module cant be used yet bug. Module is bugged ant really cant be used.
(primary 0 cannon)
After crushing into crates and disappearing from modules list.

**Comment by Monikawales** [comment]
After that bug tank started to super glitch example: working but broken support artillery slot.
![image](https://user-images.githubusercontent.com/45321263/52983404-10e92200-33fc-11e9-8b31-9ff4a8e3af22.png)

**Comment by Monikawales** [comment]
Ice colony round 3 of 2/19/19

**Comment by DominikPanic** [comment]
@Ghommie

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.
