### ISSUE TITLE
Thesus cic has a tile that's space

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7700]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. walk on tile
2. die

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/127730067-dccf029d-5f6b-48e7-bb8e-c7a8dcb42a98.png)

**Comment by lbnesquik** [comment]
My theseus PR should fix it

**Comment by BraveMole** [comment]
Fixed
