### ISSUE TITLE
Boilers glow even after emptying their ammo.

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#7706]
### Description

If at any point boiler does make more than 2 ammo, they started glowing forever even after emptying their load of all ammo. If they don't, this bug doesn't occur.

### Test Merges

#7650 
#7475 
#7404 
#7210
#7618

### Reproduction Steps

1. Be boiler.
2. Store more than two globs of gas blobs.
3. Empty them all.
4. Still glow.

**Comment by BraveMole** [comment]
never observed again AFAIK
