### ISSUE TITLE
Forever speaking After revival. Didn't figure out why

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#771]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/52985625-cbc9ed80-3405-11e9-8136-61cb9398a0b7.png)

**Comment by Ghommie** [comment]
Most lgical reason is that, due limited foreseeability, the speaking bubble overlays didn't remove itself from the mob, and that this happens most around revival situations.
