### ISSUE TITLE
Fuller auto unlocked

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#7710]
### Description

https://user-images.githubusercontent.com/72712909/127752142-3e546f05-7d81-4898-bacd-8a19c11b128b.mp4

### Test Merges

#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7404: 'Sentry Rework' by hyper2snyper at commit 4ab41dfc37
#7475: 'Makes red dot sight reduce aim mode fire delay by 50%' by Walarks at commit 27d553d42d
#7650: 'Icy cave's Expansion' by vilereaver41 at commit f9fc019393
#7702: 'Checkexit & Uncross now respects dir' by TiviPlus at commit 5f2e59577b

### Reproduction Steps

1) Obtain a gun that is both capable of mounting a Red Dot SIght and can use Aim mode
2) Mount a red dot sight on it
3) Enter aim mode
4) While on aim mode field strip the red dot sight
At this specific step with the removal of the RDS, firerate increases dramatically
5) Return to step 1, since this is repeatable

**Comment by lbnesquik** [comment]
STEALING MY INTELLECTUAL CONTENT AND RECORDINGS, DISGUSTING

**Comment by Losenis** [comment]
Shouldn't have put them up for everyone to see and let us have fun killing benos with this, fucko
