### ISSUE TITLE
ICY CAVES IS 100% CAS-ABLE AND THIS MAKES ME SO UPSET HGNNGNH

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7729]
### Description

I expected the CAVES MAP which is TINY  to have MOSTLY NO CAS, BUT I GOT CAS'd ANYWAY

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [10126](https://scrubby.melonmesa.com/round/10126)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 4ebd4dd54374a127f4f36d15aa56cd0b143d65c1
The following pull requests are currently test merged:
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7702: 'Checkexit & Uncross now respects dir' by TiviPlus at commit 5f2e59577b
#7641: 'Convert a number of tochats to balloon messages' by TiviPlus at commit b883e8599c

Local commit: 7e9665b292fa17def865eb3058f87194b91d3e4e
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Get on icy caves
Get in caves
Get shot by CAS anyway

### Screenshots

![pain +_9678fef53798de21a91a93e79c306dd3](https://user-images.githubusercontent.com/24830358/127791280-c692ede4-2fb8-46e3-bae5-3710a2cd635d.png)

**Comment by Adelphon** [comment]
skill issue

**Comment by lKiseki** [comment]
lmao

**Comment by Mechanelize** [comment]
Ice not thick
