### ISSUE TITLE
Runner can go over unwired cade if they're standing ontop of a window frame

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/TerraGov-Marine-Corps#7746]
### Description

Not that important I guess but a runner can simply walk over any unwired metal or plasteel cade if they were standing ontop of a window frame, gif for reference: https://gyazo.com/0f3a82c161416d9408f7e24d6b527159

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [10147](https://scrubby.melonmesa.com/round/10147)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 1d9a13ec198ab7458469c289ed2ec9590b60f6de
The following pull requests are currently test merged:
#7618: 'King of the hill Civil War' by BraveMole at commit 4623530c7b
#7445: 'You can now color jaeger any color you want' by TiviPlus at commit 98caa5c073
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7641: 'Convert a number of tochats to balloon messages' by TiviPlus at commit b883e8599c

Local commit: 8eb472ff215d6c1bd21027b07f1ed471ead04ab6
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Get a window frame
2. Place a unwired cade facing the frame
3. Go over the frame as a rouny
4. Watch as you phase through the cade and cant go back

**Comment by lbnesquik** [comment]
I think that is on purpose

**Comment by TiviPlus** [comment]
THis i the same issue as the tables -> window thing

**Comment by Lumipharon** [comment]
This is a quirk of having passtable, and how moving over various 'raised' structures works.
