### ISSUE TITLE
Can't phase shift into LV LZ2 as wraith

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/TerraGov-Marine-Corps#7752]
### Description

I was wraith, tried to use phase shift to enter the fob at LZ2 but got stopped by invisible  walls.

### Test Merges

Round ID: [10151](https://scrubby.melonmesa.com/round/10151)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 1d9a13ec198ab7458469c289ed2ec9590b60f6de
The following pull requests are currently test merged:
#7618: 'King of the hill Civil War' by BraveMole at commit 4623530c7b
#7445: 'You can now color jaeger any color you want' by TiviPlus at commit 98caa5c073
#7210: 'Autodocs can now start on their own' by QualityVan at commit 6fca7f7957
#7641: 'Convert a number of tochats to balloon messages' by TiviPlus at commit b883e8599c

Local commit: 8eb472ff215d6c1bd21027b07f1ed471ead04ab6
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

be  wraith, stand outside LZ2 on LV jungle map
wait for shutters to open
use phase shift to try and enter the LZ
you cant

**Comment by Surrealaser** [comment]
There are certain areas that you are forbidden from entering as Wraith when you're outside of them; LZ areas are among those.

**Comment by BraveMole** [comment]
Intended
