### ISSUE TITLE
Tank part fabricator does not accumulate points

### ISSUE THREAD

**Issue by NotSchwann** [tgstation/TerraGov-Marine-Corps#776]
## Reproduction:

1). Play TC

2). Watch as your fabricator points do not increase

3). Cry to req when you can't get your armor replaced

Evidence below:

![tankpartfab](https://user-images.githubusercontent.com/45934768/52992195-ac1ecf00-33dd-11e9-807c-796b8160091a.png)

**Comment by WittyUsername816** [comment]
I was Schwann's gunner on this. Two rounds in a row we didn't get any points for the fabricator. In our first round we had 100 points left when we deployed, and still only 100 points when we returned to the ship.

**Comment by DominikPanic** [comment]
This is intended behavior, it's not supposed to generate points.
