### ISSUE TITLE
King is missing their minimap icon

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#7779]
### Description

The King can use the minimap, but is missing their icon.

### Test Merges

#7735: 'Neurotoxic Spit Tweaks.' by vilereaver41 at commit 37635222c2
#7635: 'Speeds up diagonal movement ' by BraveMole at commit 5f0eeb65d7
#7527: 'Motion detector is now a rail attachment for guns' by BraveMole at commit 35dfd3c383
#7475: 'Makes red dot sight reduce aim mode fire delay by 50%' by Walarks at commit 67fa46c5ca
#7618: 'King of the hill Civil War' by BraveMole at commit 4623530c7b
#7445: 'You can now color jaeger any color you want' by TiviPlus at commit 98caa5c073
#7681: 'Sentinel movement animation' by rusher210 at commit 494232e580
#7692: 'Adds a new rifle type to marines-Skirmish Rifle' by Pariah919 at commit 3624847265
#7263: 'Fancy lighting' by TiviPlus at commit 79442fe463

### Reproduction Steps

1. become king
2. check minimap
3. realize that you're not on it
4. cry

**Comment by KornFlaks** [comment]
Fixed in #7763
