### ISSUE TITLE
The tadpole no longer flies into high atmosphere and it is not fun

### ISSUE THREAD

**Issue by lbnesquik** [tgstation/TerraGov-Marine-Corps#7813]
### Description

The tadpole used to fly in many layers of clouds and it was pretty fancy looking. Now we do not have it. This makes tadpole operations sad, weak and uninspired. Please fix.

### Test Merges

irrelevant

### Reproduction Steps

Fly the tadpole. Look out. see space and not your clouds.

**Comment by BraveMole** [comment]
@TiviPlus

**Comment by joniroq** [comment]
I swear I've seen clouds recently...is it map specific?

**Comment by BraveMole** [comment]
no, it's because of tivi's paralax
