### ISSUE TITLE
Can't use antimat laser designation 

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7817]
### Description

read title

### Test Merges

#7768 #7618 #7263 #7445 #7527 #7635 #7534 #7692

### Reproduction Steps

1. Get antimat
2. Unique action
3. Nothing happens

### Screenshots

https://user-images.githubusercontent.com/24631139/128502729-e5122a6c-79a4-41b9-9039-4955e83a9573.mov

**Comment by Al-1ce** [comment]
I am 90% sure this only works on xenos.

**Comment by 2whatever2** [comment]
> I am 90% sure this only works on xenos.

This isn't really the problem, as in the video it doesn't toggle the designator at all even after unique action. Nor does the text for it appear in chat, or plays the sfx of toggling it. Unless antimat mechanics were changed, it should've made a notification and sound saying it's activated the laser designator after hitting unique action.

**Comment by BraveMole** [comment]
Fixed
