### ISSUE TITLE
Admins are unable to undo the Puzzle smite option

### ISSUE THREAD

**Issue by lKiseki** [tgstation/TerraGov-Marine-Corps#7871]
### Description

Per title.

### Test Merges

Irrelevant.

### Reproduction Steps

Irrelevant.

**Comment by lbnesquik** [comment]
Deserved

**Comment by SpaceLoveSs13** [comment]
why would this need a undo option? You shouldn't be pressing random buttons without knowing the actual consequences.

**Comment by jroinc** [comment]
Banishing the correct puzzle piece as wraith can free the target.

**Comment by BraveMole** [comment]
This doesn't need an undo option IMO
