### ISSUE TITLE
Big Red Silo in new area results in buggy larva spawn

### ISSUE THREAD

**Issue by joniroq** [tgstation/TerraGov-Marine-Corps#7885]
### Description

Trying to spawn as a larva at a silo in the new section causing a black screen and the spawn to fail. Resulting in the timer resetting and place in the larva queue lost.

### Test Merges

Round ID: [10238](https://scrubby.melonmesa.com/round/10238)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 0a29ed8475f78792db4331a39ac677bb0fa31c2c
The following pull requests are currently test merged:
#7806: 'king takes 90 minutes to enter the round' by Pariah919 at commit d0e68ddf90
#7692: 'Adds a new rifle type to marines-Skirmish Rifle' by Pariah919 at commit 602d247df3
#7773: 'Reduces ravager slash damage' by lbnesquik at commit ae6ba34430
#7527: 'Motion detector is now a rail attachment for guns' by BraveMole at commit 1c7b3d9230
#7635: 'Speeds up diagonal movement ' by BraveMole at commit 5f0eeb65d7
#7534: 'Transvitox Bonus Damage Now Applies to Converted Burn Damage Too' by Surrealaser at commit ab8000915d
#7602: 'Fultons are now limited use and more expensive, decreases price of ASRS, and adds fultons to SL vendor and operational vendor' by Hekzder at commit 7820fe5863
#7725: 'Big Red V2.1 - Big additions.' by vilereaver41 at commit 5ae12b4ef7

### Reproduction Steps

1. Head to the new SE secure area
2. Place a Silo there
3. Try to spawn as Larva at that Silo
4. If it happens, the screen should go black and will fail to spawn you into the game, eventually leaving your ghost floating about the silo

**Comment by vilereaver41** [comment]
![image](https://user-images.githubusercontent.com/64131993/128866864-367c5a25-f66b-4404-a0fb-e0ca5ab368fe.png)
was it crash? i spawned just fine in a live match
