### ISSUE TITLE
Mirrage grenade clones don't have a health bar.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7892]
### Description

They don't have a healthbar, this makes you able to instantly spot the real Person.

### Test Merges

a

### Reproduction Steps

b

### Screenshots

c

**Comment by BraveMole** [comment]
this is more of a feature request than anything

**Comment by AnCopper** [comment]
> this is more of a feature request than anything

The item is completely unusable for its intended purpose.

**Comment by BraveMole** [comment]
not a bug
