### ISSUE TITLE
A Crusher running over a TL-102 while you are scoped in it will result in your camera being permanently stuck in scoped view.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7906]
### Description

![image](https://user-images.githubusercontent.com/82319489/129104031-5aea33f7-e610-4ac7-9c7f-cf033704c1e8.png)

### Test Merges

#7725: 'Big Red V2.1 - Big additions.' by vilereaver41 at commit 5ae12b4ef7
#7534: 'Transvitox Bonus Damage Now Applies to Converted Burn Damage Too' by Surrealaser at commit ab8000915d
#7527: 'Motion detector is now a rail attachment for guns' by BraveMole at commit 1c7b3d9230
#7773: 'Reduces ravager slash damage' by lbnesquik at commit ae6ba34430
#7692: 'Adds a new rifle type to marines-Skirmish Rifle' by Pariah919 at commit 602d247df3
#7806: 'king takes 90 minutes to enter the round' by Pariah919 at commit d0e68ddf90
#7735: 'Neurotoxic Spit Tweaks.' by vilereaver41 at commit f591727729

### Reproduction Steps

a

**Comment by BraveMole** [comment]
@hyper2snyper
