### ISSUE TITLE
Xenos can summon multiple Kings.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7912]
### Description

This shouldn't be possible.

### Test Merges

#7725: 'Big Red V2.1 - Big additions.' by vilereaver41 at commit 5ae12b4
#7534: 'Transvitox Bonus Damage Now Applies to Converted Burn Damage Too' by Surrealaser at commit ab80009
#7527: 'Motion detector is now a rail attachment for guns' by BraveMole at commit 1c7b3d9
#7773: 'Reduces ravager slash damage' by lbnesquik at commit ae6ba34
#7692: 'Adds a new rifle type to marines-Skirmish Rifle' by Pariah919 at commit 602d247
#7806: 'king takes 90 minutes to enter the round' by Pariah919 at commit d0e68dd
#7735: 'Neurotoxic Spit Tweaks.' by vilereaver41 at commit f591727

### Reproduction Steps

If you have enough Psy Points you can summon multiple pods at once.

**Comment by BraveMole** [comment]
Completly intended? Stop using bug reports as a way to publish your opinion on the games

**Comment by AnCopper** [comment]
> Completly intended? Stop using bug reports as a way to publish your opinion on the games

I didn't know that's intended.
