### ISSUE TITLE
Random space tile assasinations.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7913]
Space tiles instantly killing you is a non-ideal solution, sometimes they randomly and invisibly appears on random parts of the map and instantly kill anyone stepping over it, a better solution would be if they teleported you back to the nearest-non space tile.

You're not supposed to be on them in the first place anyways.

**Comment by 2whatever2** [comment]
![image](https://user-images.githubusercontent.com/24631139/129457737-7721b83e-29a2-4a8b-aad3-e7e844ab7da1.png)

They happen due to mapper mistakes you shouldn't encounter space tiles in normal gameplay at all.
