### ISSUE TITLE
Bombing sentries explode the internal item and make it null

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7926]
### Description

Read title

### Test Merges

#7735 #7527 #7534 #7725

### Reproduction Steps

1. Sentry gets bombed
2. Xeno walks in front of it
3. Can't interact with the sentry or pick it up at all.

### Screenshots

https://user-images.githubusercontent.com/24631139/129435796-458298c3-b112-4550-8a2d-80a09091fe41.mov

**Comment by BraveMole** [comment]
@hyper2snyper fixed?

**Comment by hyper2snyper** [comment]
> @hyper2snyper fixed?

Not yet tho coming real soon

**Comment by BraveMole** [comment]
Fixed
