### ISSUE TITLE
Thesus lacks a cryo console

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#7927]
### Description

Why? If you get your things stolen by the roomba, you cannot get it back since there is no cryo console on the thesus.

### Test Merges

#7735: 'Neurotoxic Spit Tweaks.' by vilereaver41 at commit f591727729
#7527: 'Motion detector is now a rail attachment for guns' by BraveMole at commit 1c7b3d9230
#7534: 'Transvitox Bonus Damage Now Applies to Converted Burn Damage Too' by Surrealaser at commit ab8000915d
#7725: 'Big Red V2.1 - Big additions.' by vilereaver41 at commit 5ae12b4ef7

### Reproduction Steps

Not relevant

### Screenshots

![image](https://user-images.githubusercontent.com/35091844/129449571-a3e43228-277c-4fb9-80a8-78940d5a1744.png)
where is the console, if I am blind?

**Comment by lbnesquik** [comment]
There is one in medical

**Comment by lbnesquik** [comment]
Added one in my current theseus PR
