### ISSUE TITLE
Big red LZ 1 has space tiles

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#7931]
### Description

Read title

### Test Merges

#7735 #7527 #7534 #7725

### Reproduction Steps

1. Walk to top left of LZ 1 of big red
2. Die

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/129457773-5c4eaf2c-1b60-461e-8619-cb418442171e.png)

**Comment by lbnesquik** [comment]
This seems fixed. I can't find anything?

**Comment by BraveMole** [comment]
this is from a TM, big red one

**Comment by BraveMole** [comment]
Fixed
