### ISSUE TITLE
Spawning Slot Error

### ISSUE THREAD

**Issue by Larker77** [tgstation/TerraGov-Marine-Corps#796]
## Reproduction: Having a period "." in the user name/ckey supposedly might have something to do with this.  

Effect: Spawning as a marine PFC no matter what the character slot preferences are customized to, including xeno only preference.

**Comment by DominikPanic** [comment]
This will affect most parts of the game that need a ckey to work.

**Comment by DominikPanic** [comment]
Scratch that, may have been separate issue.
