### ISSUE TITLE
Xeno Group Evolution

### ISSUE THREAD

**Issue by Mr-Worth** [tgstation/TerraGov-Marine-Corps#797]
## Reproduction:

If all xenos evolve at once it does not appear a check is made to see if there is space for all evolving xenos in the higher caste. This was used in a recent game where the queen called all xenos to her and told them to evolve when she screeched. This lead to all the xenos evolving to t2 and then later in the round to t3.

**Comment by DominikPanic** [comment]
Good catch I'll see what I can do

**Comment by MiniMeatwad** [comment]
forgot to report it because i thought i already did, yea good
