### ISSUE TITLE
Alive People can see the AI eye.

### ISSUE THREAD

**Issue by AnCopper** [tgstation/TerraGov-Marine-Corps#7975]
### Description

Alive mobs can see the AI eye.

### Test Merges

#7725: 'Big Red V2.1 - Big additions.' by vilereaver41 at commit 5ae12b4ef7
#7735: 'Neurotoxic Spit Tweaks.' by vilereaver41 at commit f591727729
#7263: 'Fancy lighting' by TiviPlus at commit dbb5160d03
#7791: 'Crusher can fling objects that are not anchored' by BraveMole at commit e368cc3e28

### Reproduction Steps

?????

### Screenshots

![image](https://user-images.githubusercontent.com/82319489/129965493-09b2fec1-bdee-4d42-bc44-aba9760178ce.png)

**Comment by BraveMole** [comment]
JPR did the funny and VV'd it. Not a bug, just a mememin
