### ISSUE TITLE
Platforms block marine movement.

### ISSUE THREAD

**Issue by Terra1** [tgstation/TerraGov-Marine-Corps#7991]
### Description

Characters walk into platforms, the platform blocks them from moving onto the tile.
The _expected_ behavior is for platforms to use barricade-like mechanics, so characters can walk into the same tile as the platform, just not walk to the tile "elevated" by it.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm 
Round ID: [10422](https://scrubby.melonmesa.com/round/10422)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: a2addc33799cda752c8a0178b5e64dff36977b19 
The following pull requests are currently test merged:
#7791: 'Crusher can fling objects that are not anchored' by BraveMole at commit e368cc3e28 
#7735: 'Neurotoxic Spit Tweaks.' by vilereaver41 at commit f591727729 
#7725: 'Big Red V2.1 - Big additions.' by vilereaver41 at commit 5ae12b4ef7 

Local commit: 7f152dd8dc9cb8873414a6df4f2d3dd1dcf1be1d
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Try to move anything into the same tile as an /obj/structure/platform
2. Notice how the platform blocks you.

### Screenshots

![image](https://user-images.githubusercontent.com/17017931/130320117-bb05e04f-6d7f-43e5-b7eb-15cac799bf37.png)

**Comment by RipGrayson** [comment]
Fixed as part of https://github.com/tgstation/TerraGov-Marine-Corps/pull/8125.
This issue shouldn't exist anymore.

**Comment by SplinterGP** [comment]
@BraveMole @TiviPlus 


> 
> 
> Fixed as part of #8125.
> This issue shouldn't exist anymore.
