### ISSUE TITLE
Lobby and resin walls don't go away when you try to delete them.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8013]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Right click resin wall / lobby image
2. Press delete
3. Nothing happens

### Screenshots

https://user-images.githubusercontent.com/24631139/130376522-f7fb6a55-1cc8-4ad1-9a58-204e2448ee8c.mov

**Comment by BraveMole** [comment]
You cannot delete turfs zack, it is runtiming.
