### ISSUE TITLE
The loadout managers mass steal of pills.

### ISSUE THREAD

**Issue by Rayfod** [tgstation/TerraGov-Marine-Corps#8040]
### Description

I expected the loadout manager to find the nearest vendor, that had the required item. For then, for it to pull the necessary thing for your loadout.
Instead, it takes one of the required items from all vendors that it has access to. Meaning that it takes pill bottles from all the vendors, while only giving you one in your backpack.

### Test Merges

Tested on the latest code, on a testing server.

### Reproduction Steps

1. Go to the loadout manager with pill bottles in your backpack
2. Save it.
3. Equip yourself with a backpack with pill bottles. And see it filled with the joy of pills.
4. Check all the vendors, and see how everyone is screaming for bicadine pills.

### Screenshots

![Pill bottle vendor A](https://user-images.githubusercontent.com/63320341/130655887-22dca616-cfcd-4152-b949-8d006d435d74.jpg)
![Pill bottle vendor B](https://user-images.githubusercontent.com/63320341/130655903-05c23492-b123-457c-b59d-9b4ff0222c0a.jpg)
![Pill bottle vendor As](https://user-images.githubusercontent.com/63320341/130655919-8d4e5a7b-b753-4ce5-9c6f-617bc868a9a3.jpg)
![Pill bottle vendor bs](https://user-images.githubusercontent.com/63320341/130655936-db76e397-f9e4-401d-9d52-9de4a8f2b43e.jpg)

**Comment by BraveMole** [comment]
Mate, all vendors have shared inventory :). Not a bug
