### ISSUE TITLE
Scope bug

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#8105]
### Description

When using a scope of MG-08 or HSG, if someone tries using it, it breaks the vision permanently. Reconnecting fixes the alignment however it does not fix an error that shows up on chat whenever someone tries to use zoom again, "You are already using the scope..."

This can be fixed by opening the player's VV, searching zoom and scrolling to mg-08 ironsight and opening the vv and deleting that.[For Admins].

### Test Merges

#7815 
#7966  

### Reproduction Steps

1. Click something with scope, prefereably HMG or HSG.
2. Someone else tries to use.
3. Your alignment of view zoom is messed up now.
4. Reconnecting fixes the above.
5. You still get already zoomed error which does not go away with trying to use the zoom of the same weapon again.

**Comment by BraveMole** [comment]
@SplinterGP fixed?

**Comment by SplinterGP** [comment]
> @SplinterGP fixed?

Pretty much and wanst testmerge only.
