### ISSUE TITLE
Xeno has multiple UI buttons for toggling bumpslash, only 1 works

### ISSUE THREAD

**Issue by verywhiterabit** [tgstation/TerraGov-Marine-Corps#8111]
### Description

Seems to be occurring on multiple castes for different people. See images. 

### Test Merges

The following pull requests are currently test merged:
#8096: 'machete/officer sword have bump and +15 more force' by Pariah919 at commit d3a0d13c22
#8095: 'Resin wall rebalance' by Pariah919 at commit 27d63ff596
#7976: 'Hivemind rework v1' by BraveMole at commit a8eb6e9430
#7815: 'Adds movement and direction switch for scopes with ctrl+Wasd' by SplinterGP at commit 7e3f54674a

### Reproduction Steps

1. Join xeno
2. View UI buttons at top left

### Screenshots

![image](https://user-images.githubusercontent.com/24979527/131231829-fa490896-5251-43d1-9969-79b234536db8.png)

![image](https://user-images.githubusercontent.com/24979527/131231848-d1b58782-880e-4aa6-b8f3-e58a711cd309.png)

**Comment by BraveMole** [comment]
Fixed
