### ISSUE TITLE
cas still broken

### ISSUE THREAD

**Issue by mathis650** [tgstation/TerraGov-Marine-Corps#8112]
### Description

only the main gun works on the cas plane

### Test Merges

Round ID: [10548](https://scrubby.melonmesa.com/round/10548)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: c81df692d01b1a58bfb2c31375b7e3abdc5d7cc1
The following pull requests are currently test merged:
#8096: 'machete/officer sword have bump and +15 more force' by Pariah919 at commit d3a0d13c22
#8095: 'Resin wall rebalance' by Pariah919 at commit 27d63ff596
#7976: 'Hivemind rework v1' by BraveMole at commit a8eb6e9430
#7815: 'Adds movement and direction switch for scopes with ctrl+Wasd' by SplinterGP at commit 7e3f54674a

Local commit: 3e811b01d384aeaf3c779f6004919f96fd5146b8
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. set up cas plane
2. go onto a firemission
3. only condor main gun appears
4. ???
5. profit

**Comment by BraveMole** [comment]
Fixed i believe
