### ISSUE TITLE
Stop bugs from aciding objects when they get shot

### ISSUE THREAD

**Issue by Ridgyaxe** [tgstation/TerraGov-Marine-Corps#8113]
Bugs can't psydrain if marines are nearby, as when they get shot, they stop. I don't think Aciding should be any different, so make it when a bug gets shot mid-acid it stops. 

To be clear, this is only the acid pools that melt things after X amount of time, depending on if it's weak, regular, or strong acid

**Comment by BraveMole** [comment]
Not a bug
