### ISSUE TITLE
Loadout Issue: Unable to spawn with beret/cap

### ISSUE THREAD

**Issue by Nepoox** [tgstation/TerraGov-Marine-Corps#812]
## Reproduction:
If your selected class/role already spawns with headgear then your selected loadout-item won't spawn. Please change it so the loadout items spawn in your hands or something... I just want a beret!

**Comment by DominikPanic** [comment]
Is this for marines or what job were you trying to spawn as?

**Comment by Nepoox** [comment]
It usually happens when you spawn as a job that comes with headgear, like Pilot Officer or Tank-Crewman.

**Comment by DominikPanic** [comment]
Yep another one of mine. Oh well I'll refactor prefs.
