### ISSUE TITLE
Crushers can abduct resting runners (and potentially other valid rider castes.)

### ISSUE THREAD

**Issue by davidchan13** [tgstation/TerraGov-Marine-Corps#8122]
### Description

One would expect crushers would only be able to grab and let xenos who are not resting and in combat capable condition to be able to mount the crusher, as well as give the rider a chance to opt out.

Crushers infact, do not care, and can scoop up resting or potentially even critically injured xenos of the appropriate caste and run off into the sunset (or an OB) with them.

### Test Merges

#8096 #8095 #7976 #8020 #7974

### Reproduction Steps

1) Be a resting running, for health, plasma or other reasons.
2) Have a ~~sigma male~~ crusher casually approach you.
3) Crusher initiates rider procedure (grab rouny, ect)
4) Resting ~~young~~ rouny is now abducted and resting on crushers back. Tell the QM! AMBER ALERT!

**Comment by BraveMole** [comment]
I dunno, I for myself think it's okay. What do you think @TiviPlus , intented?

**Comment by TiviPlus** [comment]
Idk tbh ill let headmins rule if kidnapping someone resting is an admin or code issue

Imo its useful when you both rest and you can show them you're ready to go again but ill leave it to them

**Comment by BraveMole** [comment]
No headmin spoke on this, i'll hereby state that this is intended
