### ISSUE TITLE
drone can continue putting down infinite weed sacs even without any plasma

### ISSUE THREAD

**Issue by mathis650** [tgstation/TerraGov-Marine-Corps#8123]
### Description

literally in the title

### Test Merges

#8096: 'machete/officer sword have bump and +15 more force' by Pariah919 at commit d3a0d13c22
#8095: 'Resin wall rebalance' by Pariah919 at commit 27d63ff596
#7976: 'Hivemind rework v1' by BraveMole at commit bc7e234593
#7974: 'Attachment Refactor!' by hyper2snyper at commit 0b9900f7c9

### Reproduction Steps

1. go drone
2. place weeds until you have no plasma
3. continue placing weeds forever
4. cover yourself in oil
5. do a lil' trolling

### Screenshots

![image](https://user-images.githubusercontent.com/73616100/131273070-324eb6b4-f6be-45db-a51a-de1cd8dde76b.png)

**Comment by BraveMole** [comment]
Fixed, it was hivemind rework
