### ISSUE TITLE
Invisible handguns/ Handguns that are placed in backpacks can't be stored in belts, even if the belts are empty

### ISSUE THREAD

**Issue by Viniwizi** [tgstation/TerraGov-Marine-Corps#8124]
### Description

I was playing as a marine, wearing a IMP backpack filled with TP-23 hanguns and 2 belts with 2 hanguns each. When i runned out of handguns on the belts i tried storing the ones from the backpacks into the belts. For some reason the game didn't allow me to do that, telling me that i couldn't fit any more handguns into the belts, even tho the belts were empty.

### Test Merges

Local commit: 74e0a3afdc59810c3177b380dc8b786fe9c8c42d
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Grab a IMP backpack filled with hanguns.
Grab a belt.
Put 2 handguns in the belt.
Drop the handguns stored in the belt
Quick-Equip the handguns from your backpack by pressing E. 
Quickly swap to your free hand, while grabbing a handgun. ( Aka: Try to quick equip two handguns at once)
This ends up with you holding a invisible firearm, and the backpack having a invisible gun stored into it.
Now try to place the Handguns into the empty belts.

This does not works sometimes. I find it weird and i don't exactly recall how i pulled it of. Just mess around with the Ghost-Handgun thing, and you will eventually break the belts.

**Comment by BraveMole** [comment]
Cannot reproduce in local
