### ISSUE TITLE
R-2395 Derringer bullets turn into 12 gauge when unloaded unfired. (And begin working in normal shotguns.)

### ISSUE THREAD

**Issue by ChristianDenDanske** [tgstation/TerraGov-Marine-Corps#8154]
### Description

Just as the title says, when you load the R-2395 Derringer and close then open it again, the bullets that come out will be marked (12 guage), instead of the .41 Rimfire, ALSO they will begin working in normal shotguns, but refuse to fit in the R-2395 Derringer.

### Test Merges

#7618: 'King of the hill Civil War' by BraveMole at commit c9655d6b15
#8079: 'Xeno turret projectiles go faster' by BraveMole at commit 98d35a230a
#8052: 'Rebalances Marine turrets' by Pariah919 at commit 9f57cd2806
#8020: 'Jetpack are now free' by BraveMole at commit 3a12295237
#7976: 'Hivemind rework v1' by BraveMole at commit 992afeecc7
#8120: 'Adds marine motorbikes' by TiviPlus at commit c840b4b0b9
#8125: 'Chigusa Hydroelectric Dam - A damn big port.' by RipGrayson at commit 7798ef9449
#8133: 'Sentry Tweaks' by hyper2snyper at commit 1369df0197

### Reproduction Steps

1. Vend a R-2395 Derringer from a Automated Weapons Rack, in the Sidearms tab,
2.  Vend a box of .40 rimfire pistol rounds, from the Rack.
3. Load the bullets from box into gun,
4. Close the Gun, and then open it again to eject bullets.
5. Bullets are now 12 guage and work in other shotgun apart from the Derringer.

### Screenshots

Ammo before ejection:
![image](https://user-images.githubusercontent.com/71035203/131919384-6c095529-a638-4d4a-9c5d-ea18480907be.png)
Ammo After ejection:
![image](https://user-images.githubusercontent.com/71035203/131919524-75007299-81ce-4c7c-b750-645acf2b313d.png)

**Comment by BraveMole** [comment]
fixed
