### ISSUE TITLE
You can't repair droids 

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8160]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Get damaged droid
2. Try to weld
3. Nothing happens and the welding fuel amount goes down by 1

### Screenshots

https://user-images.githubusercontent.com/24631139/131959353-1b6da98d-8a14-4336-a9aa-e20d293e9b1c.mov

**Comment by BraveMole** [comment]
@TiviPlus broke
