### ISSUE TITLE
Beds don't make marines lay down

### ISSUE THREAD

**Issue by Durbles** [tgstation/TerraGov-Marine-Corps#8166]
### Description

This bug affects roller beds, medevac begs and normal beds. When buckled to them the marine does not lay down, instead standing up. Surgery beds however remain unaffected. 

### Test Merges

#8133: 'Sentry Tweaks' by hyper2snyper at commit 1369df0197
#8125: 'Chigusa Hydroelectric Dam - A damn big port.' by RipGrayson at commit 7798ef9449
#8120: 'Adds marine motorbikes' by TiviPlus at commit c840b4b0b9
#7976: 'Hivemind rework v1' by BraveMole at commit 992afeecc7
#8052: 'Rebalances Marine turrets' by Pariah919 at commit 9f57cd2806
#7618: 'King of the hill Civil War' by BraveMole at commit c9655d6b15

### Reproduction Steps

1. Grab marine, or move yourself over any bed.
2. Drag your sprite onto the bed.
3. Observe as you do not lay down, but instead stand up.

### Screenshots

Roller bed
![Bed bug](https://user-images.githubusercontent.com/64918895/132072181-a4e22217-b2d3-49f4-ac1a-68939c4ba884.png)
Medevac stretcher
![Bed bug 2](https://user-images.githubusercontent.com/64918895/132072191-1115eaf6-76c4-4602-9322-198a979fcb6e.png)
Normal bed
![Bed bug 3](https://user-images.githubusercontent.com/64918895/132072196-9c885056-1ddd-4337-a7dc-6db93bea9432.png)

**Comment by BraveMole** [comment]
@TiviPlus
