### ISSUE TITLE
Hunter Mirages Cannot Be Hit in Melee

### ISSUE THREAD

**Issue by halitosisman** [tgstation/TerraGov-Marine-Corps#8193]
### Description

I clicked on hunter mirage with a machete expecting an attack animation. Nothing happened and it proceeded to deal its free stamina damage as usual. 

### Test Merges

Round ID: [10694](https://scrubby.melonmesa.com/round/10694)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: c19e8e79ccf02187129c61ae92631eaa0c1740cd
The following pull requests are currently test merged:
#7815: 'Adds movement and direction switch for scopes with ctrl+Wasd' by SplinterGP at commit 49b21ffb9a
#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7618: 'King of the hill Civil War' by BraveMole at commit 1f4adf7191

Local commit: 50fb1f3aedcd91e20915973bea93c3c2fb65bfc2
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Get machete
2. Hit hunter mirage with it
3. be very sad

**Comment by BraveMole** [comment]
???

you cannot hit the illusion by design, and it's not doing anything (certainly not statima damage???) 

Shoot the real hunter, stop attacking the mirage
