### ISSUE TITLE
Automated vendor not working properly

### ISSUE THREAD

**Issue by Iceytuna** [tgstation/TerraGov-Marine-Corps#8200]
### Description

Tried using the automated vendor as a corpsman, left me unable to get basic corps supplies from the Auto Med Equ Rack and messed up the point buy system leaving me without meraderm and the rest.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [10709](https://scrubby.melonmesa.com/round/10709)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: c19e8e79ccf02187129c61ae92631eaa0c1740cd
The following pull requests are currently test merged:
#7815: 'Adds movement and direction switch for scopes with ctrl+Wasd' by SplinterGP at commit 49b21ffb9a
#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7618: 'King of the hill Civil War' by BraveMole at commit 1f4adf7191

Local commit: 50fb1f3aedcd91e20915973bea93c3c2fb65bfc2
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Have a corpsman loadout with everything, spending vending points, add basic medical equipement to backpack and try to use the loadout one you spawn in another round.

**Comment by BraveMole** [comment]
Unless your able to give me a precise loadout, and repeat the experience, i'm pretty sure the full bag just spawned on the floor and you didn't notice
