### ISSUE TITLE
Multiple kings at once

### ISSUE THREAD

**Issue by Dolth** [tgstation/TerraGov-Marine-Corps#8202]
### Description

There was three kings (one died apparently but I caught two on camera) at once.
I don't think it should be thing nor it's intended.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [10709](https://scrubby.melonmesa.com/round/10709)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: c19e8e79ccf02187129c61ae92631eaa0c1740cd
The following pull requests are currently test merged:
#7815: 'Adds movement and direction switch for scopes with ctrl+Wasd' by SplinterGP at commit 49b21ffb9a
#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7618: 'King of the hill Civil War' by BraveMole at commit 1f4adf7191

Local commit: 50fb1f3aedcd91e20915973bea93c3c2fb65bfc2
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

No idea how it happened.

### Screenshots

https://i.gyazo.com/0053c320ea4e68cd8eabed25db91802c.png

**Comment by Tennessee116** [comment]
~~We Three Kings of Orient Are...~~

This has been happening ever since the original introduction of the king as a stalemate breaker. I think it's an intentional feature.

**Comment by Ragecrabbo** [comment]
Not a bug

**Comment by Dolth** [comment]
Closing this then since it's apparently intended.
