### ISSUE TITLE
Xeno structures ignore LZ build restrictions

### ISSUE THREAD

**Issue by Ragecrabbo** [tgstation/TerraGov-Marine-Corps#8204]
### Description

Xeno structures shouldnt be buildable anywhere near either LZ, however due to unknown reasons they can be built on some rounds without the usual restrictions.

### Test Merges

#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7976: 'Hivemind rework v1' by BraveMole at commit 1c9dc216d6

### Reproduction Steps

Unsure/Needs more reproduction

### Screenshots

![ice is nice](https://user-images.githubusercontent.com/85963263/132415826-534a1c12-874c-4fed-98a9-516985c817dc.png)

**Comment by joniroq** [comment]
Working on fixing this, Testing its fixed tomorrow and will make PR

**Comment by BraveMole** [comment]
So i think someone fixed it, can't find the pr though
