### ISSUE TITLE
Facehuggers refuse to automatically enter resin holes and will stay alive ontop of them forever

### ISSUE THREAD

**Issue by Ragecrabbo** [tgstation/TerraGov-Marine-Corps#8205]
### Description

Title

### Test Merges

#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7976: 'Hivemind rework v1' by BraveMole at commit 1c9dc216d6

### Reproduction Steps

1.Be carrier
2.Make a resin hole
3.Throw a hugger at resin hole instead of putting it in or have hugger come out of its hole
4.Hugger will now stay ontop of hole in passive state forever until picked up or killed

### Screenshots

https://user-images.githubusercontent.com/85963263/132417511-0de086f7-6d4a-451d-b3e3-2bdb95d01282.mp4

**Comment by BraveMole** [comment]
Fixed
