### ISSUE TITLE
Sulaco evac pod doors wont open

### ISSUE THREAD

**Issue by Oscari-pog** [tgstation/TerraGov-Marine-Corps#8212]
### Description

I expected the doors to open. 
They didnt.
Cant even break them or crowbar them.

### Test Merges

The following pull requests are currently test merged:
#8120: 'Adds marine motorbikes' by TiviPlus at commit c48d10d56a
#7976: 'Hivemind rework v1' by BraveMole at commit 1c9dc216d6

### Reproduction Steps

1. Try to evac on sulaco.
2. Find out that immortal adamantium doors wont let you in.
3. Cry.

**Comment by BraveMole** [comment]
Fixed
