### ISSUE TITLE
Slowdown works across mobs locking you in place if you ever stack slowdown.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8239]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Get bike
2. Run over sticky multiple times
3. Get flinged out of it or have to unbuckle yourself
4. Get stuck until your accumulated slowdown runs out.

### Screenshots

https://user-images.githubusercontent.com/24631139/132931209-334e2060-59ae-4b49-99a1-7237abf23dd1.mov

**Comment by BraveMole** [comment]
ah you're right.
