### ISSUE TITLE
Rail scope sprite is visible on mounted machine guns

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#8275]
### Description

As per title, the rail scope shouldn't be visible at all.

### Test Merges

Irrelevant but anyways...

#8226: 'BigredV2.2' by vilereaver41 at commit 732139b826
#8141: 'Priority change in shuffling' by BraveMole at commit 53c5f19626
#8195: 'Build-A-Sentry' by hyper2snyper at commit 2117cc04e2
#8147: 'Reqtorio V1' by TiviPlus at commit 9e1cbda3c9
#8241: 'Update ooc.dm. Adds two new OOC verbs for team-based OOC.' by MiniMeatwad at commit 47995698ed

### Reproduction Steps

Just get the gun lmao

### Screenshots

![image](https://user-images.githubusercontent.com/35091844/132987718-10c6214d-637c-4d2c-9959-dbf0246a0213.png)

**Comment by BraveMole** [comment]
@hyper2snyper fix, dis ugly
