### ISSUE TITLE
trash compactor mini map

### ISSUE THREAD

**Issue by TGCMbetcher** [tgstation/TerraGov-Marine-Corps#8287]
### Description

If you hop into a trash compactor ship side you wont be able to see your corpse on the mini map until youre prema. Also you cant hop out of trash compactors or move on top of them or anything with them.

### Test Merges

Round ID: [10829](https://scrubby.melonmesa.com/round/10829)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 6f9a0cd328588756e8bc5669be46d60cdaa7f404
The following pull requests are currently test merged:
#8226: 'BigredV2.2' by vilereaver41 at commit 732139b826
#8141: 'Priority change in shuffling' by BraveMole at commit 53c5f19626
#8147: 'Reqtorio V1' by TiviPlus at commit ecfd17ab2d
#8222: 'Jaeger and M10 helmet storage. ' by SplinterGP at commit b9ee663026
#8282: 'Revert "Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines"' by BraveMole at commit 1aa7983956

### Reproduction Steps

hop into trash compactor and die
look at mini map

**Comment by BraveMole** [comment]
Nothing strikes me as anormal here
