### ISSUE TITLE
Loadouts don't spawn limited medical supplies.

### ISSUE THREAD

**Issue by Alexeivichi** [tgstation/TerraGov-Marine-Corps#8289]
### Description

Selecting a loadout containing any advanced brute/burn kits or pill bottles will seldom lack said items. Seem to happens to Corpsmen the most, but can also happen to marines or engineers with medical items saved in their inventory. This is understandable to avoid duplication of limited medical items, however it happens on the marine's first loadout selection for the round.

### Test Merges

#8282: 'Revert "Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines"' by BraveMole at commit 1aa7983956
#8222: 'Jaeger and M10 helmet storage. ' by SplinterGP at commit b9ee663026
#8147: 'Reqtorio V1' by TiviPlus at commit ecfd17ab2d
#8141: 'Priority change in shuffling' by BraveMole at commit 53c5f19626
#8226: 'BigredV2.2' by vilereaver41 at commit 732139b826
#8288: 'Delete fuel gas' by TiviPlus at commit 296c47042a

### Reproduction Steps

Spawn
Go to Loadout Selector
Select Loadout container belt, pouches, bag or vest with medical supplies (kits, pills, splints).
Sometimes get the containing item yet no kits or pills. Splints seem less affected.
Day ruined.

**Comment by BraveMole** [comment]
Can you send me a loadout import path?

**Comment by Alexeivichi** [comment]
Closed since problem was caused by loadouts made prior to #8188. We'll just remake em'.
