### ISSUE TITLE
Revert/Buff King Xenomorph Spawn time or Revert price for spawning one in.

### ISSUE THREAD

**Issue by MysteryMan21333** [tgstation/TerraGov-Marine-Corps#8291]
Im going to keep this simple, the nerf to the xeno king was beyond satisfactory, hell personally when I saw you could spawn in three kings in one round I thought that could use a nerf, but dear god, you went from giving the xenos one king, to multiple kings, to none at all. And its not because you cant afford it but no xenomorph and barely any rounds have a extra 45 mins to sit on their ass and wait for a king to spawn in. Id like the kings spawn or price lowered significatly as the king is suppose to be a round ender something the xenos can call to aid and assist them but so far I have never ever seen it spawned in once or even attempted to be spawned in due to how bad the nerf was, you can give marines bikes, more weapons, so forth and so on but cant simply determine to give one of the best roles to assist the xeno push. So either give us a buff to them or just remove them from the server as theres no reason to have it if no one can even use it.

**Comment by BraveMole** [comment]
Sorry mate, this is bug report, not feature request or balance request.

Feel free to open a pr about this, but the issue tracker is not for this
