### ISSUE TITLE
Robot armor bug

### ISSUE THREAD

**Issue by Lefunny** [tgstation/TerraGov-Marine-Corps#8316]
### Description

I died, when i got deffibed everybody armor got rekted

### Test Merges

The following pull requests are currently test merged:
#8282: 'Revert "Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines"' by BraveMole at commit 1aa7983956
#8138: 'Fixes zoom values.' by SplinterGP at commit f61fa7a810
#8226: 'BigredV2.2' by vilereaver41 at commit 732139b826
#8301: 'Combat Robots Race' by TiviPlus at commit 0a2401c8c8
#8308: 'Revert "Fix crash maturity not being properly updated"' by BraveMole at commit d7a05cd91f

### Reproduction Steps

1. die
2. get deffibed
3. profit

### Screenshots

![image](https://user-images.githubusercontent.com/89319185/133683919-69ae6fa6-bf2c-4e66-bab0-2119e41ba236.png)

**Comment by Lefunny** [comment]
also nobody was using armors like this

**Comment by BraveMole** [comment]
most probably sprite byond issue
