### ISSUE TITLE
Canterbury when landing ontop of walls replaces the tile sprite for the wall instead

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8318]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Play crash.
2. Canterbury lands ontop of a building.
3. Building walls clip into the ship.
4. They don't block movement.
5. Ignore them.

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/133705372-c0e5b606-460b-4d19-9dd2-4430284e41c3.png)

**Comment by BraveMole** [comment]
Fixed
