### ISSUE TITLE
You can stack build sentries ontop of eachother

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8329]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Drop sentries all in one tile
2. Alt click the tile
3. Fill your hands up
4. Ctrl click all of them at once
5. Works with any kind of sentry including buildasentry

### Screenshots

https://user-images.githubusercontent.com/24631139/133881285-12b7c0c7-20f3-4bb2-be09-f0ff119ff1eb.mov

https://user-images.githubusercontent.com/24631139/133881294-9717d0d4-90e9-4f17-9c79-f7b23413256c.mov

**Comment by BraveMole** [comment]
@hyper2snyper please fix
