### ISSUE TITLE
Wraith teleport causes extreme performance hits

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#8339]
### Description

Ever since fancy lighting was TM/Merged, wraith's teleport effect causes extreme FPS hits that can even result in the screen glitching to black until a reconnect. Wraith's teleport also leaves pitch black tiles under it, possibly unintended if it's meant to leave something else.

Using tac binos with a wraith suddenly teleporting around is effectively a guaranteed crash/several seconds long freeze.

### Test Merges

#8323: 'Fixes medvacs not working' by QualityVan at commit f4f99187bd
#8282: 'Revert "Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines"' by BraveMole at commit 1aa7983956
#8138: 'Fixes zoom values.' by SplinterGP at commit f61fa7a810
#8226: 'BigredV2.2' by vilereaver41 at commit 732139b826
#8308: 'Revert "Fix crash maturity not being properly updated"' by BraveMole at commit d7a05cd91f
#8299: 'Readds the ZX-76' by Pariah919 at commit 5749d66a7f

### Reproduction Steps

Just be around a wraith teleporting around. Seems milder if you're orbiting it rather than seeing it move around the screen.

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/133911887-d8a6dd5b-a07d-42d1-92d6-d6ea04e5a80e.png)
![image](https://user-images.githubusercontent.com/72712909/133911989-87963f65-6971-4e7d-b20a-c40ea5b4f344.png)

**Comment by BraveMole** [comment]
Try to downgrade to 1557
