### ISSUE TITLE
ClickOn()'s next_move is affected by melee preventing use of ClickOn() if you use melee

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#8360]
### Description

Using melee prevents clicking instead of preventing melee. I think you'd want to move the delay somewhere else and remove the next_move in click code (hopefully), since you might still want to click on someone despite meleeing them.

This might also explain why if you melee someone you can't shoot until the melee timer is up.

### Test Merges

Unrelated

### Reproduction Steps

Click on something to melee it, then try to click an ability/action on top left screen like issue an order or a xeno ability before the cooldown is up

**Comment by MiniMeatwad** [comment]
I think this is a matter of a bunch of code using ClickOn()'s next_move to make their delays work instead of putting the check on what they're doing, and I think just getting rid of "next_move" would be better so no one uses it.

**Comment by Lumipharon** [comment]
action delay, not melee delay
