### ISSUE TITLE
Ammo count for guns you vendor

### ISSUE THREAD

**Issue by TGCMbetcher** [tgstation/TerraGov-Marine-Corps#8404]
### Description

Occasionally hen I revendor a gun the ammo count will stick around.

### Test Merges

Round ID: [11012](https://scrubby.melonmesa.com/round/11012)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 4ec922624cf7ce50c6cddffd01621920e656b2fe
The following pull requests are currently test merged:
#8303: 'Jaeger refactor.' by hyper2snyper at commit e0c7a0b5cf
#8301: 'Combat Robots Race' by TiviPlus at commit 273e8c965a
#8384: 'Fix weed decaying' by BraveMole at commit 0e09679c3f
#8400: 'Hotfix weed' by BraveMole at commit c9344c5dad

### Reproduction Steps

Get gun from vendor
play with it
revendor
occasionally get random ammo counter

**Comment by thatguythere03** [comment]
Reconnecting seems to fix this, but yeah a proper patch would be nice.
