### ISSUE TITLE
REQ Mimir is MK1 and not MK2

### ISSUE THREAD

**Issue by Dolth** [tgstation/TerraGov-Marine-Corps#8413]
### Description

Basically the Mimir MK2 from REQ is actually Mimir MK1.

### Test Merges

Round ID: [11026](https://scrubby.melonmesa.com/round/11026)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 29a0efec09cae0f99ada419269815c42d7202bbb
The following pull requests are currently test merged:
#8390: 'Self-charging power cells' by jroinc at commit e33d204df6
#8303: 'Jaeger refactor.' by hyper2snyper at commit 3c02c53a34
#8385: 'Adds a resin turret' by TiviPlus at commit b7864bec1c
#8301: 'Combat Robots Race' by TiviPlus at commit 273e8c965a

### Reproduction Steps

1. Order and buy Mimir MK2 at REQ.
2. Bring the elevator up and open the crate.
3. Be disappointed at a Mimir MK1 set and not MK2.

### Screenshots

https://i.gyazo.com/e9822fd2d526dfd6046b5c419613f51d.png

**Comment by OceanFish1** [comment]
It's just trolling from xeno mains
