### ISSUE TITLE
combat robots can get brain damage

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#8416]
### Description

title

### Test Merges

#8390: 'Self-charging power cells' by jroinc at commit e33d204df6
#8303: 'Jaeger refactor.' by hyper2snyper at commit 3c02c53a34
#8385: 'Adds a resin turret' by TiviPlus at commit b7864bec1c
#8301: 'Combat Robots Race' by TiviPlus at commit 273e8c965a

### Reproduction Steps

1. get hit in the head several times
2. get brain damage
3. no way to cure it

### Screenshots

![image](https://user-images.githubusercontent.com/73626246/134750681-aaba85e9-ca12-448d-8cbb-bde5dbea3794.png)

**Comment by davidchan13** [comment]
Brain ***AND*** heart damage.

None of the surgery tools work to open them up
Screwdriver, Wrench, Wirecutters, Multitool and Crowbar do not open the robot up either.

**Comment by ivanmixo** [comment]
The brain damage is very fixable, steps are as follows.

Incision > saw > retractor > hemo til there's nothing left > retractor > bone gel x2 > bone settler > cautery. 

Don't question using tools made for flesh on robots, though.

**Comment by davidchan13** [comment]
> The brain damage is very fixable, steps are as follows.
> 
> Incision > saw > retractor > hemo til there's nothing left > retractor > bone gel x2 > bone settler > cautery.
> 
> Don't question using tools made for flesh on robots, though.

This literally doesn't work, OR tools, be it the Incision Management Tool or a Scalpel, will not start surgery on a robot.

**Comment by ivanmixo** [comment]
I'll record a video of me doing it later just for you.
