### ISSUE TITLE
Lights don't update properly

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8457]
### Description

Read title

### Test Merges

#8444 #8445 #8436 

### Reproduction Steps

1. Go to thunder dome.
2. Break some lights.
3. Still full bright.
////Crash////
1. Spawn in canterbury.
2. Oh god oh fuck I can't see shit.

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/135193523-eaf5aa61-2754-4073-84a7-024c93cf703d.png)

https://user-images.githubusercontent.com/24631139/135193534-638bc78d-bd38-42aa-a236-1e2b3dc04432.mov

**Comment by BraveMole** [comment]
thunder dome has natural lights

![image](https://user-images.githubusercontent.com/25491240/145818914-66cf74f7-e90d-42b1-a033-bbff5b648b25.png)

**Comment by Lumipharon** [comment]
I don't see any bug here, Zack was doing funny vv edits to break and unbreak a light which presumably doesn't actually trigger the proc that turns an atoms light on
