### ISSUE TITLE
Firemanning Live marines allows them to shoot while on your back

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8458]
### Description

Read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Grab marine
2. Chokehold them
3. Fireman carry them
4. Guy is standing ontop of you allowing them to shoot guns

### Screenshots

https://user-images.githubusercontent.com/24631139/135196228-6a9fbb30-d0db-4991-aaf0-a093cb88522d.mov

**Comment by Lumipharon** [comment]
is cool
