### ISSUE TITLE
Loadout Vendor doesn't give big hyposprays but spends points

### ISSUE THREAD

**Issue by zxcion123** [tgstation/TerraGov-Marine-Corps#8464]
### Description

As a corpsman with a loadout, big hyposprays don't appear in inventory or anywhere on the ground about 3/4ths of the time when latejoining. But points are still spent as if they were bought. Bug doesn't seem to happen when joining at the start of the round though.

### Test Merges

#8409
#8436
#8444

### Reproduction Steps

1. Be corpsman with a loadout that has a big hypospray
2. join late and use a loadout that contains a big hypospray
3. Big chance you don't find the hypo where you're supposed to

**Comment by BraveMole** [comment]
send me the loadout path please

**Comment by zxcion123** [comment]
predatory_neesan//Squad Corpsman//PAS_(Items)

**Comment by zxcion123** [comment]
Predatory_Neesan//Squad Corpsman//PAS (Items)

**Comment by zxcion123** [comment]
Predatory_Neesan//Squad Corpsman//PAS (Items)

**Comment by BraveMole** [comment]
Fixed
