### ISSUE TITLE
Using underbarrel attachments like the Masterkey prevents tactical reloads.

### ISSUE THREAD

**Issue by Pixelknightly** [tgstation/TerraGov-Marine-Corps#8478]
### Description

What it says on the title.

As far as I know, It's like this with the Masterkey and the Mini-flamer. Not sure about the plasma pistol or the UGL.

### Test Merges

Round ID: [11152](https://scrubby.melonmesa.com/round/11152)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 5013d9c4eb0c48221965f5771a6fadcb3c26d6e8
The following pull requests are currently test merged:
#8441: 'You no longer have to be in harm intent to PB people in enemy factions' by BraveMole at commit 667b46b58e
#8436: 'Fix language holder harddel [DNM]' by BraveMole at commit eb7cbacae1
#8444: 'Asay and msay pings' by TiviPlus at commit ea72d38296
#8356: 'More guns to civil war' by BraveMole at commit 9f8b9b8f24

### Reproduction Steps

1. Attach an underbarrel attachment to your gun.
2. Activate underbarrel attachment.
2. Shoot all your main gun bullets.
3. Try to do a tactical reload from your bag/ammo pouch/whatever
4. Get a failure message.

### Screenshots

![Screenshot (2)](https://user-images.githubusercontent.com/79366142/135693945-3d8537e2-1761-4bbe-b5ea-8c32a4f3a543.png)

**Comment by Xander3359** [comment]
https://user-images.githubusercontent.com/66163761/221996339-9ddd8f0e-6ca1-4669-84e5-9f2f8109235e.mp4

This issue is resolved.

**Comment by Xander3359** [comment]
Also tested masterkey and the tac reload works just fine.
