### ISSUE TITLE
Spit flies over mobs

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8485]
### Description

read title

### Test Merges

#8356 #8436 #8441 #8410

### Reproduction Steps

1. Spit at a marine
2. Spit misses
3. Cope

### Screenshots

https://user-images.githubusercontent.com/24631139/135728299-862472f5-fbc0-486b-8c4b-38cc6a91c7b5.mov

**Comment by ivanmixo** [comment]
Can't reproduce on local

**Comment by BraveMole** [comment]
Fixed
