### ISSUE TITLE
Unable to use corrosive acid as alien sentinel

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/TerraGov-Marine-Corps#851]
Title, was unable to use spray corrosive acid on anything (cades, guns, etc.) as a sentinel.
Local commit: e1b7522bfa4153117b63b1563cd99dacd72b27b1

## Reproduction:
Be alien sentinel,
Toggle on corrosive acid,
Try using it on something nearby,
end up facing the target but nothing happens.

Don't have a clue why this is happening, ahelped and was told to report the issue here.

**Comment by DominikPanic** [comment]
Was due to a test-merge, let me know if you ever encounter it again.

**Comment by DominikPanic** [comment]
Fixed in #805
