### ISSUE TITLE
Turnstile like cades

### ISSUE THREAD

**Issue by Captiajoe** [tgstation/TerraGov-Marine-Corps#8510]
### Description

I expected a cade that works as a barrier both ways, cant walk past it at all (has barb on it).

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [11195](https://scrubby.melonmesa.com/round/11195)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 0f208beb657bf678791f5c3f5fdefcceaa15cb82
The following pull requests are currently test merged:
#8486: 'Fix shuffling not working 100% as intended[DNM]' by BraveMole at commit 14e9f33a4b
#8356: 'More guns to civil war' by BraveMole at commit 9f8b9b8f24
#8436: 'Fix language holder harddel [DNM]' by BraveMole at commit eb7cbacae1
#8441: 'You no longer have to be in harm intent to PB people in enemy factions' by BraveMole at commit 667b46b58e
#8378: 'Lasers have hitscan' by BraveMole at commit feed4a51bb
#8395: 'Move code refactor' by TiviPlus at commit 7154bcba1a
#8442: 'Automatic cycle alamo mode' by BraveMole at commit 6c613378af

Local commit: e4065c4144fa1bd2018c3375e5632d4a6e844418
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1) Spawn in on a fresh map
2) find a pre placed cade (tad or canterberry)
3) walk through it from marine side (marine side is the side that would be the inside of a fob or in tads case from inside tad to out) while the cade/ plasteel cade is up and supposed to be un passable

### Screenshots

I have only noticed this on pre placed cades and plasteel cades from canterbery, bigbery, and tadpole, it seems you can take those pre-placed cades and remake cades that have the same property.

**Comment by BraveMole** [comment]
@TiviPlus this is from move code refactor, no?
