### ISSUE TITLE
Lasers on Automatic periodically stop firing

### ISSUE THREAD

**Issue by Tristan63** [tgstation/TerraGov-Marine-Corps#8515]
### Description

When firing the laser rifle on automatic it'll stop firing randomly when you are aiming directly at a mob.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [11197](https://scrubby.melonmesa.com/round/11197)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 0f208beb657bf678791f5c3f5fdefcceaa15cb82
The following pull requests are currently test merged:
#8486: 'Fix shuffling not working 100% as intended[DNM]' by BraveMole at commit 14e9f33a4b
#8356: 'More guns to civil war' by BraveMole at commit 9f8b9b8f24
#8436: 'Fix language holder harddel [DNM]' by BraveMole at commit eb7cbacae1
#8441: 'You no longer have to be in harm intent to PB people in enemy factions' by BraveMole at commit 667b46b58e
#8378: 'Lasers have hitscan' by BraveMole at commit feed4a51bb
#8395: 'Move code refactor' by TiviPlus at commit 7154bcba1a
#8442: 'Automatic cycle alamo mode' by BraveMole at commit 6c613378af

Local commit: e4065c4144fa1bd2018c3375e5632d4a6e844418
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Use Lasgun Rifle
2. Aim at mob
3. Fire
4. If the mob moves you stop firing even though you're on automatic 
5. Also works on terrain if you move then you have a chance to not fire on the move

### Screenshots

https://user-images.githubusercontent.com/66579448/135908246-07b9aece-754d-4a40-9dd8-82e4d42fb925.mp4

**Comment by BraveMole** [comment]
i was unable to reproduce, wether in local server or in the live one. Can you give more insight on this?

**Comment by Tristan63** [comment]
Though it happened without attachments at all on the Laser MG, this isn't an issue on the Sniper or Pistol.
