### ISSUE TITLE
TGUI crash upon opening robo species' loadout

### ISSUE THREAD

**Issue by Evie7056** [tgstation/TerraGov-Marine-Corps#8617]
### Description

So basically you crashes when you enter Loadout with robotic species. After that your char setup becomes a NTOS crash page and you won't be able to enter it until the server's restart when your setup resets to appearance tab. The issue might be with either robots or IE, but since I'm no TGUI expert I won't say anything for sure. 

Changing versions from 514.1557 to 514.1566 doesn't help as well as clearing BYOND's cache. This also seems seems to be unfixable until server restart with Admin pref changing.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [11501](https://scrubby.melonmesa.com/round/11501)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 20b600ed4e5d3ba574d4564c97581fc0c01fd59c
The following pull requests are currently test merged:
#8557: 'Makes throwing knives viable.' by hyper2snyper at commit 88ec93a1ef
#8540: 'Fixes a bug where guns that didnt allow their starting attachments didnt get their starting attachments.' by hyper2snyper at commit d6fde286db
#8550: 'Refactors foam code' by SplinterGP at commit 06a7de79ba
#8612: 'Fix autobalancing[DNM]' by BraveMole at commit 542cb20e8d

Local commit: a464d45b0ee95ee74b4e41a24a3338e2a67b29d5
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Set your species to robotic
2. Go to the loadout tab
3. Get your Char Setup NTOSd on. 
4. ???
5. Wait for the next round to resolve

### Screenshots

![image](https://user-images.githubusercontent.com/71145590/138103928-44f80d51-a043-4cd9-8b78-86f464518e9c.png)

**Comment by Mechanelize** [comment]
bump
