### ISSUE TITLE
Newly vatborns dont have access to the whole minimap

### ISSUE THREAD

**Issue by JanStruan** [tgstation/TerraGov-Marine-Corps#8641]
### Description

I expect to be integrated to the already present marine force, instead I am only aware of people with REQ issued headsets

Vatborns are only aware of the people who are incapacitated and dead, but not of currently alive marines with REQ given headsets

### Test Merges

Local commit: 03b643fab593ff92904578c199f2a7e21aa85f62
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Whenever you die, go to take offered MOB
Grab a vatborn
Suit up then ask req for a headset
Go to the surface
Wallow in despair because you have no idea where marines are

**Comment by BraveMole** [comment]
Fixed?
