### ISSUE TITLE
Ice Map has no pipes..

### ISSUE THREAD

**Issue by MrBobCool** [tgstation/TerraGov-Marine-Corps#869]
![image](https://user-images.githubusercontent.com/40435661/53294204-0d64ea80-37b0-11e9-9f30-421bda79c2b6.png)

There's not no.... Pipes..

No admin stuff, no test stuff, there are just no pipes.

**Comment by DominikPanic** [comment]
@spookydonut

**Comment by spookydonut** [comment]
It has pipes just in the wrong layer
