### ISSUE TITLE
You can load grenades inside flareguns

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8713]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Get flare gun
2. Load grenade
3. Fire

### Screenshots

https://user-images.githubusercontent.com/24631139/139522148-afbf1802-e009-47b1-9b2b-0f18eb1dd286.mov

**Comment by mrhugo13** [comment]
#8528

![bild](https://user-images.githubusercontent.com/17747087/139529826-b90e90c0-208e-4375-a855-329a8d729f8b.png)

thank you very cool
