### ISSUE TITLE
end round log

### ISSUE THREAD

**Issue by ZahaSanko** [tgstation/TerraGov-Marine-Corps#8717]
### Description

marine won shipside
log says xeno minor victory

### Test Merges

Master commit: 3b5ead61fe1f32270c2b854201d40944f450ddcf
The following pull requests are currently test merged:
#8690: 'King rebalance/buff' by David-Stormwell at commit 214741dfb3
#8710: 'Fix pill bottles being empty on loadouts sometimes' by BraveMole at commit 2ec11a2124

### Reproduction Steps

marine minor

**Comment by BraveMole** [comment]
Ok but if you don't even give the round id....
