### ISSUE TITLE
Robots getting brain damage after death

### ISSUE THREAD

**Issue by XANAv2** [tgstation/TerraGov-Marine-Corps#8730]
### Description

I expected to not have any problems with my legs after dieing as a robot as well they don't have brains. Or if they do they are getting brain damage. however, the game said no and decided to say I was having motor control issues and I was laying down mid-combat.  I tried using an auto doc to fix it but it didn't work so well. In this picture on November first this year.  Also, this is my first time posting on Github so i hope this is all in order

### Test Merges

1. #8634: 'Hivelord primordial and acid traps' by TiviPlus at commit cc91fa1640
2. #8710: 'Fix pill bottles being empty on loadouts sometimes' by BraveMole at commit 2ec11a2124
3. #8650: 'Grayscale Pillbottles Fixes and Additions' by chesse20 at commit a7d5f2d67a
4. #8659: 'Pathfinding improvement' by BraveMole at commit 4f3d8712d7

### Reproduction Steps

1. die
2. get brain damage somehow

### Screenshots

![your legs](https://user-images.githubusercontent.com/93561523/139773693-3c421357-bf84-4869-b15a-aae958eafaef.PNG)

**Comment by Pixelknightly** [comment]
This is probably only going to be fixed months later, if ever, as it's rather low priority. (Similar to how secondary fire attachments breaks tactical reload.)  Right now, you're better off just Ahelping it.

**Comment by ilikesaying** [comment]
They can also get heart damage when getting defibbed, literally causing them to have limited revives before being undefibbable

**Comment by BraveMole** [comment]
Fixed
