### ISSUE TITLE
CAS cannot start a fire mission despite enough marines being on the ground.

### ISSUE THREAD

**Issue by Ragecrabbo** [tgstation/TerraGov-Marine-Corps#8747]
### Description

''What did you expect to happen''
CAS fire missions to work
''and what happened instead?''
CAS fire mission no work :(((

### Test Merges

#8719: 'Silo collapse happens 15 minutes after shutter drop' by BraveMole at commit 8d42ae2fcb
#8710: 'Fix pill bottles being empty on loadouts sometimes' by BraveMole at commit 2ec11a2124
#8659: 'Pathfinding improvement' by BraveMole at commit 4f3d8712d7
#8735: 'Cas can begin fire mission without an active laser, flare and laser have better view range' by BraveMole at commit 6c13c211cd
#8644: 'Pain rebalance' by jroinc at commit fda4f92ab4
#8742: 'Diagonal move refactor electric boogaloo' by BraveMole at commit 6773c669fa

### Reproduction Steps

1.Launch CAS
2.Try to start fire mission
3.Get ''The signal from the planet is too weak, we cannot route towards the battle field.'' even when there are enough marines on the ground and they are actively lighting flares and lasing
4.CAS starts working again after some time has passed (seems to happen at the time when shutters open automatically, could use more reproduction though)

### Screenshots

![Ship no fly me sad](https://user-images.githubusercontent.com/85963263/140621323-07293244-0f4e-4d62-b6e8-eb01e67ca697.png)

**Comment by BraveMole** [comment]
Oh, that's because the monitor fire only every 5 minutes.

Hum, that's a tricky one to fix
