### ISSUE TITLE
mantis arm implant can be removed similar to removeing shrapnal

### ISSUE THREAD

**Issue by XANAv2** [tgstation/TerraGov-Marine-Corps#8786]
### Description

A medic was removing a piece of shrapnel and instead he got my mantis arm blade instead  

### Test Merges

#8684: 'Buff recurring injection' by BraveMole at commit cdf7267705
#8761: 'Remove parallax when on ground' by BraveMole at commit 5824f6d202
#8778: 'Should fix dead mobs in ssdmoblist' by BraveMole at commit 49837f3f4b
#8744: 'Auto fire spit and spitter primordial.' by hyper2snyper at commit bfd7ffae7b

### Reproduction Steps

 !. Select a  limb that has an arm blade with tweezers and extract the "shrapnel"
2. you get an arm blade instead.

**Comment by BraveMole** [comment]
This is a bug, but it's funny no?

**Comment by XANAv2** [comment]
yes yes it is but needs to be fixed

**Comment by XANAv2** [comment]
It's also for all implants I have come to learn as they are tied to shrapnel and are not their own thing, it is just another thing that needs to be coded not a part of shrapnel code I gather.  I gather sadly I can't code... I just sprite so I'm quite limited in what I can do about it.
