### ISSUE TITLE
Orbital cannon fuel requirements do not seem to matter for precision.

### ISSUE THREAD

**Issue by cebollense** [tgstation/TerraGov-Marine-Corps#8798]
### Description

Played a game on prison station, somebody loaded OB with HE with only 1 fuel out of 6 that was required. They fired it on the ground and it landed exactly where it was pointed instead of missing its target as it was supposed to happen.

Fuel requirements seem to not matter for precision, unintended glitch I assume. Can be easily tested by firing OB loading wrong amount of fuel.

### Test Merges

Round ID: [11908](https://scrubby.melonmesa.com/round/11908)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 301868cc9e463ebd7a478c54b9f2da057f0f9546
The following pull requests are currently test merged:
#8742: 'Diagonal move refactor electric boogaloo' by BraveMole at commit 8b3e3a3fd3
#8673: 'Modularizes gun operation to use flags.' by hyper2snyper at commit cfa155f146
#8684: 'Buff recurring injection' by BraveMole at commit cdf7267705
#8761: 'Remove parallax when on ground' by BraveMole at commit 5824f6d202
#8744: 'Auto fire spit and spitter primordial.' by hyper2snyper at commit bfd7ffae7b
#8784: 'Razorwire nerf' by jroinc at commit cf3bdb1651

Local commit: db730605db3c8b2968f0821bacd35ed7dcb82bd4
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1-Go to OB room.
2-Load it with wrong amount of fuel.
3-Fire it on ground and see if it is precise.

**Comment by mrhugo13** [comment]
![Code_2021-12-12_10-17-43](https://user-images.githubusercontent.com/17747087/145712356-fab74a68-fe70-40cc-a5e6-0dc606b400f6.png)
here's the math of OB deviation, numbers next to the different warheads show how many fuel canisters you need for a 100% accurate shot.
