### ISSUE TITLE
Metal Foam mix does not produce metal foam upon reaction

### ISSUE THREAD

**Issue by Three333Digit** [tgstation/TerraGov-Marine-Corps#8804]
### Description

Mixing 
3 iron
1 foaming agent
1 sulphuric acid 
Does not produce any metal foam upon reaction.

### Test Merges

The following pull requests are currently test merged:
#8797: 'A star pathfinding is put in a SS' by BraveMole at commit b0591b4e4f
#8768: 'Shoulder Gun Module' by hyper2snyper at commit 98bb72cd2a
#8784: 'Razorwire nerf' by jroinc at commit cf3bdb1651
#8684: 'Buff recurring injection' by BraveMole at commit cdf7267705

### Reproduction Steps

1. Get three seperate beakers containing Iron (3u), Foaming Agent (1u), and Sulphuric Acid (1u) each and an empty beaker
2. Transfer the contents of the three filled beakers to the empty beaker
3. Wait for the foam to dissipate
4. No metal foam.

**Comment by BraveMole** [comment]
@jroinc Intended right?

**Comment by jroinc** [comment]
> 
> 
> @jroinc Intended right?

Intended. The minimum amounts needed are now 3x what the recipe says, so a 3/1/1 mix won't give foam but a 9/3/3 mix will give foam. This only affects the minimum amounts, maximums are unchanged.

**Comment by Three333Digit** [comment]
I see. I thought this was unintended since the PR said """Razorwire""" nerf and not an overall nerf to foam reactions. Closed.
