### ISSUE TITLE
Wraith gets tangled in barbed wire while phase shifting over it

### ISSUE THREAD

**Issue by Oscari-pog** [tgstation/TerraGov-Marine-Corps#8811]
### Description

I dont know about you but last I checked barbed wire is a solid object and not a omnicorporeal one.
Wraith shouldnt be entangled in wire when it can phase through fucking walls.

### Test Merges

The following pull requests are currently test merged:
#8797: 'A star pathfinding is put in a SS' by BraveMole at commit b0591b4e4f
#8768: 'Shoulder Gun Module' by hyper2snyper at commit 98bb72cd2a
#8784: 'Razorwire nerf' by jroinc at commit cf3bdb1651
#8684: 'Buff recurring injection' by BraveMole at commit cdf7267705

### Reproduction Steps

1. Become wraith.
2. Try to phase shift over barbed wire.
3. Fucking die as you slug through barbed wire and un-shift inside the jungle of wire.
4. Cry and ponder if the wire really is a divine object that transcends reality.

**Comment by KrabSpider** [comment]
This is a result of how razorwire in general works. If you enter the tile, you will get entangled regardless of status.
