### ISSUE TITLE
Animation can make mobs untargetable

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8824]
### Description

read title

### Test Merges

#8684 #8766 #8797

### Reproduction Steps

1. Dragblink an allied xeno
2. Try to grab for another blink
3. Fail to even click them or see them in context menu

### Screenshots

https://user-images.githubusercontent.com/24631139/142758714-a37fd04c-e3af-4f84-b626-a34470fd6986.mov

**Comment by BraveMole** [comment]
Fixed
