### ISSUE TITLE
larva join timer sometimes extremely short

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#8838]
### Description

what I expect to happen: given 10~ seconds to make my choice on which silo I should spawn into and confirm my choice
what happened instead: near immediately kicked out of larva queue due to being slow 

I don't think it was based on any testmerges

I assume that the larva timer is based on some always running timer that doesn't reset when someone gets to pick where they'll emerge.

### Test Merges

#8803: 'Zombie mode first part' by BraveMole at commit ad3752b21a
#8773: 'Chem buffs' by jroinc at commit 9e2bf09aca
#8792: 'Refactor pathfinding element to a subsystem, should fix some pathfinding bugs' by BraveMole at commit b417682628
#8820: 'TGS Minerva' by AzonStarfall at commit 1ffcb52f69
#8805: 'Boiler primordial - Acid- / Neuro lance bombard' by DeltaFire15 at commit 783f6f9107

### Reproduction Steps

die
join larva queue
wait to become a larva
get to choose between which silo you want to spawn at
get kicked out of the queue before you can make a choice

### Screenshots

https://cdn.discordapp.com/attachments/877777075027714148/913312026535817216/Desktop_2021.11.25_-_00.07.58.72.DVR_Trim.mp4

**Comment by Lumipharon** [comment]
I've seen this happen prior to any of those test merges.
WHen it's happened to me, I've actually teleported to the silo it's asking if I want to spawn at, black screen like normal, then I become a ghost again.

**Comment by Lumipharon** [comment]
This seems to happen because the larva becomes available, but someone in lobby can just take it before you accept.
