### ISSUE TITLE
APCs unusable/unrepairable after xeno slashes

### ISSUE THREAD

**Issue by T1MM5H** [tgstation/TerraGov-Marine-Corps#8839]
### Description

Expected to fix APC by: screwing shut the cover, as stated was the issue by Examination
Result: APC does not distribute power to devices or lights, and cannot be set to ON for any of the categories, automatically switching OFF. No indicator as to damage or destruction on the APC itself.
Attempted: Replacing Board, Replacing terminal
Issue: Either unintended and bug, or intended and not communicated well enough.

### Test Merges

Round ID: [12059](https://scrubby.melonmesa.com/round/12059)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: a4b1fed51add257ebb4dbdf1987b1c98e1abb55d
The following pull requests are currently test merged:
#8803: 'Zombie mode first part' by BraveMole at commit ad3752b21a
#8773: 'Chem buffs' by jroinc at commit 9e2bf09aca
#8792: 'Refactor pathfinding element to a subsystem, should fix some pathfinding bugs' by BraveMole at commit b417682628
#8820: 'TGS Minerva' by AzonStarfall at commit 1ffcb52f69
#8805: 'Boiler primordial - Acid- / Neuro lance bombard' by DeltaFire15 at commit 783f6f9107

Local commit: 19553bce84c183126efb5fee3a925f05c269d8f3
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Have Xeno slash at functional APC until wires are exposed.
Screwdriver shut APC interface, while power supplied.
APC no longer functions as intended, still updates Cell Charge.

**Comment by DeltaFire15** [comment]
Xenos slashing an APC enough cuts the APCs wires and shorts it (the slash after the one that opens cover, specifically. Have you tried mending the wires?

**Comment by T1MM5H** [comment]
> Xenos slashing an APC enough cuts the APCs wires and thereby shorts it (the slash after the one that opens cover, specifically.) Have you tried mending the wires?

Yes, This does not fix the problem. Unless i am PHENOMENALLY retarded.

**Comment by T1MM5H** [comment]
Just tested some more, replacing the power Control Electronics does set all the switches to ON, but there is still no power being distributed to the room.

**Comment by SilencedMP5A5** [comment]
you need to completely disassemble and rebuild APC's that are broken (broken as in the cover looks like its hanging off)

1 - knock the cover off with anything with more than 5 force

2 - remove the cell if its there

3 - remove the tile under the APC and cut the wires

4 - unscrew and crowbar out the fucked electronics

5 - weld the empty APC frame

6 - place a new APC frame on the wall where the APC was or next to it if it won't let you place it in the old spot

might not be completely accurate because it's been forever since i played engi but that's the gist of it

also make sure you turn on the breaker

**Comment by Derrick2Electricboogaloo** [comment]
I have never encountered this issue, the only thing I can think is that maybe someone fucked with it and it shorted which all you have to do it cut then remend the wires.

**Comment by BraveMole** [comment]
You must have fucked up when fixing it
