### ISSUE TITLE
Tadpole camera busted so that it cannot land

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#8850]
### Description

Reported in November 26, 2021 8:80 PST
![image](https://user-images.githubusercontent.com/6610922/143668480-caa6d4c7-45bc-4a4f-97e8-c52e526b22e8.png)

Similar case reported by Lewd when PR got TMed

![image](https://user-images.githubusercontent.com/6610922/143668505-9f89e4a4-ddb1-49fb-8b74-afc39c0c1ed8.png)

### Test Merges

#8820: 'TGS Minerva' by AzonStarfall at commit 498b3236e5
#8548: 'Refactor rendering and new wraith blink effects' by TiviPlus at commit 158db83980 (like this one)
#8673: 'Modularizes gun operation to use flags.' by hyper2snyper at commit e24bd619e5
#8773: 'Chem buffs' by jroinc at commit 9e2bf09aca
#8805: 'Boiler primordial - Acid- / Neuro lance bombard' by DeltaFire15 at commit 718907ea0c

### Reproduction Steps

Try to land tadpole

**Comment by BraveMole** [comment]
related with rendering refactor
