### ISSUE TITLE
You can banish resin turrets to place another turret ontop of the same spot

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8852]
### Description

Read title, can probably do this with other structures like silos

### Test Merges

doesn't matter

### Reproduction Steps

1. make acid turret
2. banish it
3. start to make acid turret on the same spot
4. re-banish it when near completing the second structure

### Screenshots

later when i feel motivated

**Comment by BraveMole** [comment]
Appart from preventing banishing resin structure, i don't see anyway to fix this easily
