### ISSUE TITLE
Spaghetti Storage

### ISSUE THREAD

**Issue by T1MM5H** [tgstation/TerraGov-Marine-Corps#8856]
### Description

I cannot store MRE Component (spaghetti) in my marine combat boots. Unplayable.

### Test Merges

Round ID: 12082
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 6c7b6599a7d88be5f50ce5ef54cc744b4265d9dd
The following pull requests are currently test merged:
#8805: 'Boiler primordial - Acid- / Neuro lance bombard' by DeltaFire15 at commit a19821e384
#8773: 'Chem buffs' by jroinc at commit 9e2bf09aca
#8673: 'Modularizes gun operation to use flags.' by hyper2snyper at commit e19332772a
#8548: 'Refactor rendering and new wraith blink effects' by TiviPlus at commit 158db83980
#8820: 'TGS Minerva' by AzonStarfall at commit 9c13567fb8

Local commit: fa38aedfc5d48164420c8a56baf146cddf36fe03
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Get lucky with MRE Gacha.
2. Attempt to store spaghetti in lower extremity coverings, as is tradition.
3. Cry because the coders discriminate against my people
4. Drop said spaghetti in front of cute SO
5. get shoved into droppod and deposited on magmoor

### Screenshots

![Screenshot 2021-11-27 225359](https://user-images.githubusercontent.com/85063956/143721720-763ee892-a6d4-4c3d-8960-ed1cf7d4a8cf.png)

**Comment by mrhugo13** [comment]
Not a bug, this seems to be intentional.

...For now
![bild](https://user-images.githubusercontent.com/17747087/145674211-72f30a2c-694d-44fa-a7bb-6535535bdf0c.png)

**Comment by BraveMole** [comment]
Not a bug + a pr was made
