### ISSUE TITLE
On the CIC monitor the experimental testing room has the wrong name

### ISSUE THREAD

**Issue by CoolfoolFTW** [tgstation/TerraGov-Marine-Corps#886]
The experimental testing lab appears as the Intelligence Officer's room on the CiC squad monitor.

**Comment by DominikPanic** [comment]
@Rohesie most likely your TM as there's no intelligence officers on the master.

**Comment by Rohesie** [comment]
This was called `Staff Officer Bunks` before. I think this is a mapping issue. My PR merely changes the name to `Intelligence Officer Bunks`.

**Comment by DominikPanic** [comment]
Please include more information next time as I couldn't find any reference to an experimental testing lab or the squad monitor when inspecting it during a round.

**Comment by spookydonut** [comment]
whoever mapped the testing room just varedited the areas with a different name instead of making a new area type.

**Comment by DominikPanic** [comment]
Still unable to find any reference in the code to this (even in the maps). What room are we even talking about? On what map?

**Comment by Alterist** [comment]
Fixed in  #980
