### ISSUE TITLE
Two nukes spawn on magmoor

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#8864]
### Description

title

### Test Merges

#8806: 'LV624 Overhaul: 2021 Edition' by RipGrayson at commit e6bba24c00
#8647: 'Adds a new Winter-themed xeno' by Walarks at commit 86d771461d

### Reproduction Steps

E

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/144063810-416e2437-eaa4-40f6-8b8b-eb4178b3d5fb.png)
![image](https://user-images.githubusercontent.com/72712909/144063479-1cc0c682-fa2f-4c5d-9211-6245f586b35e.png)

**Comment by BraveMole** [comment]
fixed
