### ISSUE TITLE
T-21 and T-39 unique actions just deletes 1 round for magazine without ejecting it.

### ISSUE THREAD

**Issue by Alexeivichi** [tgstation/TerraGov-Marine-Corps#8869]
### Description

Using unique weapon action (spacebar by default) deletes 1 ammo from T-21 Skirmish Rifle and T-39 Combat Shotgun, no sound is played and no action is dropped, nor any prompts are given except ammo counter decreasing by 1.

Not immersive, please fix.

### Test Merges

#8806: 'LV624 Overhaul: 2021 Edition' by RipGrayson at commit e6bba24c00
#8799: 'Warrior primordial : Edition 2' by Canohaaaaaaa at commit aaf7e74fc0
#8820: 'TGS Minerva' by AzonStarfall at commit d3aa2ca958
#8858: 'Icy Cave's addition's and tweak.' by vilereaver41 at commit 93622240e2

### Reproduction Steps

Acquire T-21 or T-39.
Load weapon and hit Spacebar.
Cry as you die to xenos because your brain small as game mechanics wack.
Thank the c*ders.
Make an angry Bug Repor- **Wait...**

**Comment by AdmiralAwesome130** [comment]
Person that reported this to mentorhelp here, just in case it is relevant.
