### ISSUE TITLE
Runner's savage damage miscalculation

### ISSUE THREAD

**Issue by BeebBeebBoob** [tgstation/TerraGov-Marine-Corps#8882]
### Description

Was digging in rouny ability code and found out two line of codes that are mismatched with what wiki says. Wiki says 15 to 35 damage depended on plasma that in our case is calculated by plasma*0,2. The problem is wrong function.
`var/extra_dam = min(15, plasma_stored * 0.2)`
We need max(15 to 35 or 40 if 200plasma*0,2) instead of min(10plasma*0,2 to 15)

Also wrong comment or number
`use_plasma(extra_dam * 5) //Expend plasma equal to 4 times the extra damage.`
If it will be 5 the savage will drain all the plasma. But if 4 only 80%.

### Test Merges

1.i'm really sorry but i played on different server

### Reproduction Steps

1. Be rouny
2. Find target and savage him.(to fulltest without armor)
3. Check out plasma and targets health.
4. Be a sad rouny with secret nerfs.

**Comment by BraveMole** [comment]
Fixed
