### ISSUE TITLE
Jetpacking over razorwire damages you

### ISSUE THREAD

**Issue by Luxyboo** [tgstation/TerraGov-Marine-Corps#8899]
### Description

Using a jetpack to jump over razorwire damages you. 

### Test Merges

Round ID: [12192](https://scrubby.melonmesa.com/round/12192)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 911c74ee60c3850ef4f119c2014ae404b159a4ae
The following pull requests are currently test merged:
#8808: 'Xenos can now weed grass' by RipGrayson at commit 28fda80dfe

Local commit: ea37c160699d69bef6fd0e6b48365d22ea983da5
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. get jetpack
2. find or make razorwire 
3. jetpack over it
4. damage

### Screenshots

![explorer_OAd34lmxj2](https://user-images.githubusercontent.com/76012083/144700738-0098fc6b-922b-42b9-b2fc-375ed0ff2581.png)

![dreamseeker_ecQXJrGcty](https://user-images.githubusercontent.com/76012083/144700748-be7b016f-0de2-4889-8d3c-b961755ca32d.png)

**Comment by KrabSpider** [comment]
Unfortunately intended...

**Comment by mrhugo13** [comment]
What's going on is seemingly jetpacks only do turfchecks and doesn't check for structures which is why this is happening with the razorwire.
