### ISSUE TITLE
You cannot remove mining computers from miners

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#8907]
### Description

what I expect to happen:
see that miner has a auto miner in it
use welder
mining computer pops out

what actually happens:
see that miner has auto miner in it
use welder
"Tristan Quilt dismantles the mining computer from the miner!"
examine miner
"The Nanotrasen platinum Mining Well's module sockets are occupied by the mining computer."
is still automated
attempt to use overclock module
nothing happens

### Test Merges

The following pull requests are currently test merged:
#8901: 'Revert "Icy Cave's addition's and tweak."' by BraveMole at commit c3dca7ebf9
#8808: 'Xenos can now weed grass' by RipGrayson at commit 28fda80dfe
#8647: 'Adds a new Winter-themed xeno' by Walarks at commit 0eb4d9642e

### Reproduction Steps

repair miner
put autominer in miner
use welder on miner
wait for bar to end
try to use overclock/well reinforcement
cry as the Gods have abandoned you

**Comment by Derrick2Electricboogaloo** [comment]
Are you even allowed to remove mods from miners? I thought it was intended to make them that way.
