### ISSUE TITLE
Laser guns with buildasentry can't take new cells if both eject

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8936]
### Description

It also doesn't let you reload at all if you don't remove the attachment, Nor can you replace the turret cell at all while deployed.

### Test Merges

doesn't matter

### Reproduction Steps

1. Turn on radial while using a laser buildasentry
2. Wait till it goes to 0 charge
3. Cry as your gun stops working

### Screenshots

https://user-images.githubusercontent.com/24631139/145448038-84b23deb-4438-4ea9-bc84-50b1d3f0d4ec.mov

https://user-images.githubusercontent.com/24631139/145448052-5facac3a-94c4-4747-8263-068367bc8f3d.mov

**Comment by BraveMole** [comment]
@hyper2snyper

**Comment by Tristan63** [comment]
confirmed, happened to me during a game where i had two laser MGs with buildasentries 

you could only reload it by taking it down and putting the cell in manually, but the power cell could not be fixed at all
