### ISSUE TITLE
You can't attach a mateba long barrel on a mateba, nor can you normally get it in-game

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8937]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Look for mateba long barrel attachment
2. Realize it's admin only
3. Cope
4. The attachment doesn't even work or has a sprite

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/145455763-02a52089-9f72-4183-ac68-758e81d71678.png)

**Comment by BraveMole** [comment]
It's a starting attachment that cannot be removed
