### ISSUE TITLE
Devo bug

### ISSUE THREAD

**Issue by Naaanii** [tgstation/TerraGov-Marine-Corps#8960]
### Description

Devolving a Xeno as Queen, turns the Queen into the devo'd Xeno and ghosts the Xeno that she was aiming for.

Example: Queen tries to devo Rav. Queen gets turned into a hunter and Rav is ghosted.

Round ID: [12351](https://scrubby.melonmesa.com/round/12351)

Reproduction rate: 2/2

### Test Merges

#8647 #8808 #8901

### Reproduction Steps

Be Queen.
Watch Xeno.
Devolve Xeno.
Xeno is ghosted and Queen is turned into devolved version of the Xeno.

**Comment by ATH1909** [comment]
https://youtu.be/FkXlKQS5Elo?t=36
