### ISSUE TITLE
Spitters can spit while in vents

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8961]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Hop in vent.
2. While channeling hold down spit.
3. You keep spitting while in vents.

### Screenshots

https://user-images.githubusercontent.com/24631139/145734768-4ed3ebbd-da61-45f5-9f78-58571b730cbf.mov

**Comment by KuzyXD** [comment]
@BraveMole so it is bug or not?

**Comment by BraveMole** [comment]
> 

yes
