### ISSUE TITLE
Wraith can devo while shifted

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#8963]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Go wraith
2. Shift
3. Regress
4. Profit

### Screenshots

https://user-images.githubusercontent.com/24631139/145782082-1d9d9a50-ef83-4ca1-b0d5-1ea902c66349.mp4

The nuke panel blocks the text but you can see me devoing midshift, planting me below the nuke.
![image](https://user-images.githubusercontent.com/24631139/145782441-6859c2b3-589c-4179-aa83-f571d5c0e271.png)

**Comment by ThelastArchiver** [comment]
dont you need full plasma to devo and doesnt wraith shift consume plasma?
