### ISSUE TITLE
Pistol belt only fits two laser magazines if the Laser Pistol is in it

### ISSUE THREAD

**Issue by CormanQuewye** [tgstation/TerraGov-Marine-Corps#8985]
I'm guessing it's some issue with it using the size system. The pistol pouch is supposed to hold a pistol and a full complement of magazines. However, if you fill it with laser magazines, attempting to put the laser pistol in it will claim that there's no space for it. If you put the laser pistol in first, only two magazines fit.

Unsure if this is a bug or not, so just put it in feature request.

**Comment by BraveMole** [comment]
Not a bug, and perfectly intended. Laser pistol uses normal laser mags, hence you shouln't be able to fill a pistol pouch with rifle mags

**Comment by CormanQuewye** [comment]
> Not a bug, and perfectly intended. Laser pistol uses normal laser mags, hence you shouln't be able to fill a pistol pouch with rifle mags

They're not rifle magazines, they're batteries.
