### ISSUE TITLE
Reloading flares into M30E2 flare gun without opening the chamber

### ISSUE THREAD

**Issue by rusher210** [tgstation/TerraGov-Marine-Corps#8988]
### Description

i tried to pull a flare from a M30E2 flare gun without opening the chamber, it worked, so i tried reloading and it also worked.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [12389](https://scrubby.melonmesa.com/round/12389)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 3ab28caf8c0d1cacb2c5a3497c3f6d7f9b23678f
The following pull requests are currently test merged:
#8647: 'Adds a new Chinese-mythology-themed xeno' by Walarks at commit b582bc05ed
#8808: 'Xenos can now weed grass' by RipGrayson at commit 28fda80dfe
#8901: 'Revert "Icy Cave's addition's and tweak."' by BraveMole at commit c3dca7ebf9

Local commit: 150d77521661564232ddc9614135e514055c9937
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. put M30E2 flare gun on right hand
2. Select left hand
3. unload the flare gun just like a normal gun
4. load the flare gun with selected flare

**Comment by Verlurk** [comment]
This is the same for the single shot T81 grenade launcher. Icon state does not update upon removing a grenade with your empty hand, but does when fired.
