### ISSUE TITLE
CAS Auto Begin Firemission not working

### ISSUE THREAD

**Issue by FosterGrime-Heymynameslouie** [tgstation/TerraGov-Marine-Corps#9003]
### Description

CAS Auto Begin Firemission not working
You also need a signal flare to be deployed for CAS to go into firemission mode
returning back to pre auto firemission days of PO screaming in comms for a laze perhaps?

### Test Merges

The following pull requests are currently test merged:
#8944: 'FOB Drone Vision Improvements' by Three333Digit at commit 7c6fbfd593
#8926: 'Valhalla(Tm)' by BraveMole at commit 0ed5db426f

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [12434](https://scrubby.melonmesa.com/round/12434)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 0367e0847b9f66f4187167382a61501b502e028e
The following pull requests are currently test merged:
#8944: 'FOB Drone Vision Improvements' by Three333Digit at commit 7c6fbfd593
#8926: 'Valhalla(Tm)' by BraveMole at commit 0ed5db426f

Local commit: ba200ec5a9b14d1f76b58877e9ac48ecebcd99da
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Step inside CAS
2. Launch CAS
3. Once on Air, begin firemission
4. Receive no response
5. cry

**Comment by BraveMole** [comment]
duplicate
