### ISSUE TITLE
Tadpole destroys underground vent pipes where it lands

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/TerraGov-Marine-Corps#9018]
### Description

Round ID: [12485](https://scrubby.melonmesa.com/round/12485)

Underground ventillation pipes can be destroyed when the Tadpole drop shuffle lands, denying xenos from ventcrawling there and creating opening in the pipe network that can't be welded shut.

This issue report comes following a round of Magmoor where the Tadpole PO landed the Tadpole in the south west corner of LZ1 (South LZ), this created a breach in the pipe network allowing xenos to get inside the FOB early before shutters were opened.

Due to admin policy about xenos not being allowed to attack marines while shutters are closed, this seems a bit unintentional.

> Bwoink bait

### Test Merges

#5568: 'Christmas Testmerge PR! (2021 christmas not late!)' by SplinterGP at commit cd65d4b20e
#8926: 'Valhalla(Tm)' by BraveMole at commit 94b743b0c5
#8993: 'Martini rebalance' by Pariah919 at commit 4f287053ce
#9012: 'Razorwire grenades can no longer be opened' by Verlurk at commit cfe01635d2

### Reproduction Steps

1. Choose a landing zone via Tadpole controls that overlaps with the air or scrubber pipe networks.
2. Land Tadpole there
3. Tapole destorys the underground pipes where it lands.

**Comment by ThelastArchiver** [comment]
was that the round where the po got murdered by a wraith ?

**Comment by GravitronBlue** [comment]
> was that the round where the po got murdered by a wraith ?

Yes, I was also the wraith.

In some technical sense the PO was murdered mid-flight on the Tadpole, though apperanlty that's still covered by policy when FOB shutters are still closed.
Maybe I'll ask someone whether managing to sneak shipside while FOB shutters are closed is also against policy.
