### ISSUE TITLE
Deathsquad Pulse Energy rifle not working

### ISSUE THREAD

**Issue by XSlayer300** [tgstation/TerraGov-Marine-Corps#9029]
### Description

It does 'fire', but it does not use any projectile/beam.

### Test Merges

#5568: 'Christmas Testmerge PR! (2021 christmas not late!)' by SplinterGP at commit cd65d4b20e
#8993: 'Martini rebalance' by Pariah919 at commit 4f287053ce

### Reproduction Steps

- Get a pulse energy rifle, attempt to fire, but no projectile/laser happens.

**Comment by Verlurk** [comment]
Have tested, works fine. Projectile travels extremely fast.

`https://i.imgur.com/dSdL1N9.gif`
