### ISSUE TITLE
Condor cannot start fire mission without a CAS flare/laser - LZ624.

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9030]
### Description

Having a lase/flare is no longer supposed to be a requirement to start a firemission. However sometimes it will not allow you to start the fire mission unless there is an active flare/lase.
When this bug occurs, it's for the entire round. It's not individual flights.

Edit: Confirming it was happening to another PO, specifically on LZ, while it has not occured for me on any other maps.

### Test Merges

#5568: 'Christmas Testmerge PR! (2021 christmas not late!)' by SplinterGP at commit cd65d4b20e 
#8993: 'Martini rebalance' by Pariah919 at commit 4f287053ce 

### Reproduction Steps

Take off in Condor
Have no active flare/lase
Try start firemission/toggle your weapons
Cry when you sit in space

**Comment by BraveMole** [comment]
allright , i think i know why is causing this. And yeah it's the map, thanks for the report
