### ISSUE TITLE
You can make satchels and storage containers make noise as a ghost when observing a player

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9046]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Observe a guy
2. Click rapidly on their backpack
3. Watch them cope as they hear the sound of a backpack opening constnatly

### Screenshots

https://user-images.githubusercontent.com/24631139/147310615-fede534b-7aab-44c0-b15b-d23f4934d21e.mp4

**Comment by token-map** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOO
