### ISSUE TITLE
Bikes block acid spray/cone

### ISSUE THREAD

**Issue by Mannybrado** [tgstation/TerraGov-Marine-Corps#9047]
### Description

Bikes block acid spray/cone like walls do.

### Test Merges

#9024: 'Medical Nanites buff' by KAAITTT at commit a0aeaebe5b
#5568: 'Christmas Testmerge PR! (2021 christmas not late!)' by SplinterGP at commit 2593fc21f4
#9026: 'Moving harvester code into component' by Waselon at commit 5d27e4c847

### Reproduction Steps

Be spitter or prae. acid spray a bike. it will be blocked. problematic! i'm not sure if it requires someone to be on the bike or not.

**Comment by TiviPlus** [comment]
Balance issue
