### ISSUE TITLE
Warrior breaks limbs in one second

### ISSUE THREAD

**Issue by SrSC0ndition** [tgstation/TerraGov-Marine-Corps#9057]
### Description

Warrior should not deal 60 brute damage just by lunging and punching, and that is what happenning last 3 days, xenos easily cheese with 2-3 warriors breaking EVERYTHING in your body  just in 2-3 seconds

### Test Merges

#5568: 'Christmas Testmerge PR! (2021 christmas not late!)' by SplinterGP at commit 2593fc21f4
#9024: 'Medical Nanites buff' by KAAITTT at commit a0aeaebe5b

### Reproduction Steps

1. Play warrior
2. Target any arm
3. Do lunge, then punch your target
4. Hear crunch
5. Your friend warrior, who repeats the same, just delimbs marine in a second

### Screenshots

Didn't make any, but my last experience with that was 2 seconds delimb by two warriors just lunging+punching me

**Comment by SrSC0ndition** [comment]
Took a game of warrior just to make sure, lunge+punch just deletes mostly anything, one punch for an arm, punch+ a few slashes on chest - bone break

**Comment by novaepee** [comment]
Already resolved by #9052
