### ISSUE TITLE
railgun is missing from supplypack.dm

### ISSUE THREAD

**Issue by Araulius** [tgstation/TerraGov-Marine-Corps#9076]
### Description

you cannot order the railgun anymore.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [12604](https://scrubby.melonmesa.com/round/12604)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: ba2bcd5950ab0c29036bc5b5a07438f3a18c85bb
The following pull requests are currently test merged:
#9024: 'Medical Nanites buff' by KAAITTT at commit a0aeaebe5b
#5568: 'Christmas Testmerge PR! (2021 christmas not late!)' by SplinterGP at commit 2593fc21f4
#9039: 'Pill bottles show how many pills they have in overlays' by BraveMole at commit cf91e16d38

Local commit: 2a288c97f2d2f784e7c5f920db7a664f2b77ed40
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

go to asrs console

attempt to locate rail gun

it is not there

**Comment by BraveMole** [comment]
![image](https://user-images.githubusercontent.com/25491240/147497472-d0a8f92d-4bb0-4a7c-a238-fa39c3f6a869.png)
