### ISSUE TITLE
Every object after round end Every object The codex shift+click is empty 

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#910]

**Comment by Monikawales** [comment]
Every weapon shift-click is empty after round ended

**Comment by Monikawales** [comment]
result:
![image](https://user-images.githubusercontent.com/45321263/53450487-6beacc80-3a2d-11e9-8906-f65cb53ffcad.png)

**Comment by Monikawales** [comment]
result: broken interface
![image](https://user-images.githubusercontent.com/45321263/53450550-93da3000-3a2d-11e9-9ad3-a00333868750.png)

**Comment by DominikPanic** [comment]
What do you mean?

**Comment by DominikPanic** [comment]
@Hughgent could you investigate?

**Comment by Hughgent** [comment]
That's the game options screen though? and that's round start?

**Comment by Hughgent** [comment]
![image](https://user-images.githubusercontent.com/45076386/53688256-bb1f4e80-3d06-11e9-86a4-e5a66a68ec6b.png)
Seems to be working. I do believe that their description or name isn't accurate.

**Comment by Hughgent** [comment]
![image](https://user-images.githubusercontent.com/45076386/53688274-4698df80-3d07-11e9-8ad1-f6a2d5c3bd86.png)
I really got nothing.

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by DominikPanic** [comment]
Unable to reproduce
