### ISSUE TITLE
Acid stunning through Painkillers & Oxycodone

### ISSUE THREAD

**Issue by CharlieDownsin** [tgstation/TerraGov-Marine-Corps#912]
## Testmerges: 

#864 #903 #906 #907 #711 #894 #897 #904 #867 #844 #847 #839 #827 #860 #895 #893 #891 #890 #889 #888 #887 #880

## Reproduction:

Apply painkillers (Oxycodone being the strongest) and then enjoy being effortlessly & repeatedly stunned by (probably) all alien acid attacks with spammy pain noises despite not being able to feel your body.

**Comment by Rohesie** [comment]
Are we talking about acid or neurotoxin here? Because neurotoxin and halloss in general don't care about painkillers by design.

**Comment by CharlieDownsin** [comment]
> Are we talking about acid or neurotoxin here? Because neurotoxin and halloss in general don't care about painkillers by design.

Obliviously this is a bit hard with the server being up so rarely & having Oxycodone be a non-standard in kit but from the two encounters where I've had it in a bloodstream, one of them was "regular" acid for sure.

**Comment by DominikPanic** [comment]
@Surrealaser What's the intended behavior here?

**Comment by Surrealaser** [comment]
Oxy is effective against pain from acid; it does nothing against halloss. You would need more than ~133 burn damage before the painkilling effect of Oxy would be overwhelmed.

**Comment by DominikPanic** [comment]
Feel free to report back with concrete results, this could not be reproduced.
