### ISSUE TITLE
Final shot of scatter las carbine can be converted to autoburst, placing a new cell makes it shoot autoburst scatter shots

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9125]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Shoot scatter 9 times
2. Cell autoejects on the final shot
3. Turn on Burst mode
4. Insert new cell
5. You're now shooting scatter shots in burst mode

### Screenshots

https://user-images.githubusercontent.com/24631139/147844529-b4578edd-ba73-4489-9d06-1d21fb228830.mp4

**Comment by usnpeepoo** [comment]
WHY
