### ISSUE TITLE
LV caves mapping issues

### ISSUE THREAD

**Issue by Rohesie** [tgstation/TerraGov-Marine-Corps#913]
![1](https://user-images.githubusercontent.com/42041276/53457796-55834780-3a12-11e9-8c5d-b5330371edbe.png)
![2](https://user-images.githubusercontent.com/42041276/53457797-561bde00-3a12-11e9-928f-03557b1089e4.png)
![3](https://user-images.githubusercontent.com/42041276/53457798-561bde00-3a12-11e9-9035-f65036d37b6f.png)

**Comment by DominikPanic** [comment]
Are you sure about that? https://puu.sh/CSyCb/bc7941994e.png

**Comment by Rohesie** [comment]
Could be a TM's fault, I suppose.

**Comment by DominikPanic** [comment]
Considering you didn't include TMs feel free to open a new one if you see it again, including TMs.
