### ISSUE TITLE
Wraith takes accumulated damage while on fire in phase shift (this applies to banished xenos too, doesn't apply to humans for some reason)

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9136]
### Description

Inconsistency

### Test Merges

doesn't matter

### Reproduction Steps

1. Banish a xeno on fire /phase shift while on fire
2. Unbanish after a while/ Unshift after a while
3. Take accumulated damage depending on how long you were banished/shifted for
4. Do the same thing to a human and see that they take no damage

### Screenshots

https://user-images.githubusercontent.com/24631139/147868139-da889e01-69ca-4df9-8dcd-1cfe34964c65.mp4

https://user-images.githubusercontent.com/24631139/147868163-213f729e-8d64-4318-a611-d3f85fc89d2c.mp4

**Comment by BraveMole** [comment]
Phase shift
