### ISSUE TITLE
Cannot save custom mix hypospray in loadout

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#9139]
### Description

Corpsmen want to save custom mix hypospray in loadout so that they don't have to click so much. Instead, they get tricordizine hypospray and not their mix.

### Test Merges

Just loadout; no one expects this level of robustness

### Reproduction Steps

1. Dump tricord out of tricord hypospray
2. Make custom mix
3. Save it
4. Load it next round
5. Full of tricord instead of custom mix
6. Cry

**Comment by BraveMole** [comment]
Not a bug
