### ISSUE TITLE
Loadout miniflamer needs nozzle

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#9143]
### Description

Loadout miniflamer apparently comes without a nozzle despite being unable to get a nozzle

### Test Merges

#9061: 'Valhallastation: Christmas Edition' by RipGrayson at commit 566a8332a6
#9006: 'Makes psychic link usable while moving' by Walarks at commit 68cf1c36cb
#9039: 'Pill bottles show how many pills they have in overlays' by BraveMole at commit cf91e16d38
#9094: 'Fix cocoon psy point output' by BraveMole at commit 67dd38b8a8

### Reproduction Steps

get loadout with gun that has miniflamer
try to use miniflamer
???

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/147890856-095689ea-cd2a-47df-9d4b-882045c4f683.png)
![image](https://user-images.githubusercontent.com/72712909/147890858-495ae947-bec8-4efe-bb3b-627e336eec52.png)

**Comment by BraveMole** [comment]
duplicate
