### ISSUE TITLE
Pillar of spring doesn't have a hypersleep bay console (Map Issue)

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9145]
### Description

Roomba eat item, item goes to shadowrealm. (Spawning a new hypersleep console doesn't fix it.)

### Test Merges

Doesn't matter

### Reproduction Steps

N/A

### Screenshots

Medical cryo consoles do not get anything from roombas
![image](https://user-images.githubusercontent.com/24631139/147892160-8dbdea25-1645-4a75-ab09-4e31e336a9b9.png)

**Comment by BraveMole** [comment]
Fixed
