### ISSUE TITLE
UGL works onehanded

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9146]
### Description

Read title

### Test Merges

Doesn't matter

### Reproduction Steps

1. Get ugl
2. Put it in gun
3. Load it
4. Shoot it onehanded

### Screenshots

https://user-images.githubusercontent.com/24631139/147892720-9b4dba10-4b53-49d5-8a3d-2c1c6f2a4f0c.mp4

**Comment by BraveMole** [comment]
Is this really an issue?

**Comment by 2whatever2** [comment]
Inconsistent with other underattachments being unable to fire onehanded, if you think it's fine go ahead and close this issue.

**Comment by BraveMole** [comment]
> Inconsistent with other underattachments being unable to fire onehanded
true
