### ISSUE TITLE
Spitter faster fire rate doesn't even work, only with adminspawnned spitters with different maturity

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9149]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Be spitter
2. Mature
3. Fire rate doesn't go up
4. Be at ancient
5. Fire rate doesn't change at all

### Screenshots

Maturity Spitter

https://user-images.githubusercontent.com/24631139/147895646-c69a1295-16ef-404b-9f84-2c2d28bc0d91.mp4

Spawned in Spitters

https://user-images.githubusercontent.com/24631139/147895649-28c07774-33d2-4051-9caa-6ac62fa7799e.mp4

**Comment by BraveMole** [comment]
@hyper2snyper
