### ISSUE TITLE
You can stock limited items in broken vendors

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9164]
### Description

Read title, Before anyone yells at me for vending items inside thunder dome linked with the main game this was done with rebel vendors
![image](https://user-images.githubusercontent.com/24631139/148147380-92178114-c875-4d28-9d1f-f02ff157dfa9.png)

### Test Merges

Doesn't matter

### Reproduction Steps

1. Explode vendor
2. Vendor vends limited items
3. Restock em

### Screenshots

https://user-images.githubusercontent.com/24631139/148147560-b0d422a8-7a99-4643-ab4e-d79e9920073e.mp4

**Comment by BraveMole** [comment]
happened to me yesterday i was very mad
