### ISSUE TITLE
You can shoot attachments while in tarp

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9189]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Pick up gun with underattachment
2. Shoot while in tarp
3. Profit

### Screenshots

https://user-images.githubusercontent.com/24631139/148326645-2f70b909-9b0e-4903-8f65-c5447126a481.mp4

**Comment by BraveMole** [comment]
Fixed i think?
