### ISSUE TITLE
Bicardine Harvester no-longer prevents self-damage.

### ISSUE THREAD

**Issue by Mrrpip** [tgstation/TerraGov-Marine-Corps#9209]
### Description

Well.

I expected to heal 6 damage and some stamina.

I didn't expect to heal 6 damage, some stamina and stab myself for a lot more than 6 damage.

### Test Merges

#8967: 'Rebalance savage' by BraveMole at commit 5ee67665f0
#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 183b7da576
#9166: 'Sentry radial mode balance' by Three333Digit at commit 5f7bf9940f

### Reproduction Steps

-Grab Harvester Blade
-Load with Bicardine, use unique action.
-Help intent self with sword,

### Screenshots

https://cdn.discordapp.com/attachments/792079667494125591/929393502285090886/unknown.png

**Comment by BraveMole** [comment]
@Waselon
