### ISSUE TITLE
Minions noclip through shutters

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#9211]
### Description

They just ignore them

### Test Merges

#8967: 'Rebalance savage' by BraveMole at commit 5ee67665f0
#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 183b7da576
#9166: 'Sentry radial mode balance' by Three333Digit at commit 5f7bf9940f

### Reproduction Steps

E

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/148658368-675f9ae3-4dcb-4fcd-8342-920ff8e53961.png)

**Comment by vilereaver41** [comment]
LOL

**Comment by Verlurk** [comment]
They can also do this to move diagonally through barbed wire, instead of it blocking their path.
