### ISSUE TITLE
Droppodable area in wrong location

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/TerraGov-Marine-Corps#9215]
### Description

Found an area where marines can droppod in and get locked.

p.s. @vilereaver41 

### Test Merges

#icar

### Reproduction Steps

1. Put random cords in droppod.
2. Drop in random areas which are potentially just deathtraps or soft lock zone.

### Screenshots

![Annotation 2022-01-09 123354](https://user-images.githubusercontent.com/68121607/148672804-e4f9091b-3812-4cd5-a07b-ec877494fe10.png)

**Comment by Tristan63** [comment]
this is a feature
