### ISSUE TITLE
ChemMaster 3000 not naming pills

### ISSUE THREAD

**Issue by CharlieDownsin** [tgstation/TerraGov-Marine-Corps#922]
## Testmerges:

#864 #903 #906 #907 #711 #894 #897 #867 #844 #847 #839 #827 #860 #895 #918

## Reproduction:

The ChemMaster 3000 fails to label/name pills if you try to create more than one at once, despite there being an option to do so.

**Comment by Rohesie** [comment]
@Hughgent

**Comment by Hughgent** [comment]
Never been an issue personally. Any medic can look at the pill to get it's contents. PFC's get punished pretty hard for eating (multiple) floorpills. I've always just double entered past the name option.

Besides, that PR 927 fixes it.
