### ISSUE TITLE
Miniflamer cannot be linked to a backpack flamer tank when attached to a gun

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9230]
### Description

You cannot link the backpack tank to the miniflamer while it's attached to a gun.
Dragging the tank (left or right click) to the gun just tries to tac reload it, dropping your mag.

You can however still link the unattached miniflamer to the backpack, then attach it to the gun and it works fine.

### Test Merges

The following pull requests are currently test merged:
#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46514
#9131: 'Soldering iron for Squad Engineer' by novaepee at commit 98d8e26d90
#9115: 'Ghosts can assume control of minions' by BraveMole at commit 68c7fe4437
#8967: 'Rebalance savage' by BraveMole at commit 5ee67665f0

### Reproduction Steps

Try attach backpack flamer to miniflamer,
cry

**Comment by hyper2snyper** [comment]
non issue. RIght-click the backpack tank with the gun while the miniflamer is activated.
