### ISSUE TITLE
Backpack fuel tanks can remotely connect to flamers

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9231]
### Description

If you connect a backback flame tank (tested with normal and X type) to a flamer (tested with TL-84 and miniflamer), you can drop the backpack somewhere but the gun retains the connection, giving you a remote store of fuel while wearing a normal backpack.

Edit: Hilariously, this ALSO works if you make the flamer into a sentry, allowing you to have X flame sentries sucking juice through bluespace.
Edit 2: This also works with miniguns and their power pack things.

### Test Merges

The following pull requests are currently test merged:
#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46514
#9131: 'Soldering iron for Squad Engineer' by novaepee at commit 98d8e26d90
#9115: 'Ghosts can assume control of minions' by BraveMole at commit 68c7fe4437
#8967: 'Rebalance savage' by BraveMole at commit 5ee67665f0

### Reproduction Steps

Link backpack tank to gun.
Drop tank on the floor and walk away.
Flame things with impunity.

### Screenshots

![image](https://user-images.githubusercontent.com/7869430/148847740-a72bf130-d054-43a4-bc78-8fc28206696a.png)

**Comment by OpsCoretango** [comment]
okay, i got intel for ya.
its not dropped you just dupe texture but tank its self still in backpack slot.
Repeat your actions but now use shift+right mouse button on backpack slot.

**Comment by Lumipharon** [comment]
Only just looked at this but no, it's not on my back, as I can put an actual backpack on and use it.
