### ISSUE TITLE
MP uniform not savable in loadout vendor 

### ISSUE THREAD

**Issue by Tristan63** [tgstation/TerraGov-Marine-Corps#9232]
### Description

Loadouts using the MP uniform don't save the MP uniform.

### Test Merges

#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46
#9131: 'Soldering iron for Squad Engineer' by novaepee at commit 98d8e26
#9115: 'Ghosts can assume control of minions' by BraveMole at commit 68c7fe4
#8967: 'Rebalance savage' by BraveMole at commit 5ee6766

### Reproduction Steps

1. Save loadout with MP uniform
2. Attempt to vend
3. Watch as it vends all your uniform dependent items onto the floor, and you don't get red marine drip.

**Comment by BraveMole** [comment]
intended, only items in regular vendor are savec
