### ISSUE TITLE
New say box is buggy

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#9241]
### Description

Apostrophes are broken.

### Test Merges

#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46514
#9131: 'Soldering iron for Squad Engineer' by novaepee at commit 98d8e26d90
#9115: 'Ghosts can assume control of minions' by BraveMole at commit d7191bb4ba
#9233: 'Fix one crash runtime + add logging to jobs and larva' by BraveMole at commit 4de31acc29
#9190: 'Tgui Update' by SplinterGP at commit 233b4aad03

### Reproduction Steps

Self explanatory

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/149158658-9a3756fb-3983-4e06-8d27-57b4cde4a2cf.png)

**Comment by BraveMole** [comment]
I said on the pr :(

**Comment by Losenis** [comment]
Implying anyone reads prs :rounycool:
