### ISSUE TITLE
Unable to join as larva, valhalla, SSD mobs, or from offered mobs

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#9246]
### Description

what  I expect to happen: given menu and be able to join 
what actually happens: menu doesn't show up, is instead replaced with "Interface ListInput was not found."
probobly caused by my byond version (514,1569))
edit: also does not work on byond version 514, 1575

### Test Merges

#9233: 'Fix one crash runtime + add logging to jobs and larva' by BraveMole at commit 4de31acc29
#9115: 'Ghosts can assume control of minions' by BraveMole at commit 5f2185eefb
#9131: 'Soldering iron for Squad Engineer' by novaepee at commit 98d8e26d90
#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46514

### Reproduction Steps

die/observe
attempt to join as larva
wait through queue
see error
larva timer times out
attempt to join valhalla
see error
attempt to take SSD mob
see error
etc

### Screenshots

![image_2022-01-12_155413](https://user-images.githubusercontent.com/54422837/149219939-8b735258-d68b-4b52-9658-9410685a11da.png)

**Comment by BraveMole** [comment]
@SplinterGP
