### ISSUE TITLE
You can fire plasma pistol underattachment onehanded and while wielding

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9248]
### Description

Inconsistent with other attachments requiring to be wielded to work, and to be finished wielding to work

### Test Merges

none

### Reproduction Steps

1. Get Plasmapistol
2. Slap it on
3. Shoot it onehanded or while wielding

### Screenshots

https://user-images.githubusercontent.com/24631139/149244522-90ab1c7e-3a69-45a0-b577-1e6610bb1f3c.mp4

**Comment by Notamaniac** [comment]
This is apparently intended behaviour

**Comment by hyper2snyper** [comment]
inconsistent =/= unintended
