### ISSUE TITLE
Empty enegry sword window

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#925]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/53526323-ee8a8f00-3af4-11e9-894a-84ae7e05471b.png)

**Comment by Monikawales** [comment]
I don't know how to reproduce. A window sudden has popped out from nowhere

**Comment by DominikPanic** [comment]
I saw this one happen too, it will be a tough one.

**Comment by DominikPanic** [comment]
Have you seen it again recently?

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by DominikPanic** [comment]
This hasn't appeared since, I'm closing this, feel free to open it again but include testmerges please
