### ISSUE TITLE
Robots get heart damage and shrapnel

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9256]
### Description

Read title

### Test Merges

none

### Reproduction Steps

dunno

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/149267538-000caadf-dadf-4009-9845-5476aaf59440.png)

**Comment by Losenis** [comment]
I'd like to add here that as synth you can get force-rested with brain damage
