### ISSUE TITLE
IV bags and QC make your blood go above 100% capping at 107.143% (600CL)

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9260]
### Description

read title

### Test Merges

none

### Reproduction Steps

1. IV bag or QC
2. Inject or consume QC

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/149400621-5ad6b533-7003-43fc-82bd-6b31525da211.png)
![image](https://user-images.githubusercontent.com/24631139/149400726-476baed5-eb25-449b-9ccc-e3904c4229fc.png)

**Comment by BraveMole** [comment]
intended. Don't know why though, but intended
