### ISSUE TITLE
Corpse count includes groundside spawn corpses

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9261]
### Description

read title

### Test Merges

none

### Reproduction Steps

que

### Screenshots

Marines got wiped quickly here due to a lowpop tadop, total of all players including xenos was only 37 at round end
![image](https://user-images.githubusercontent.com/24631139/149401250-3e21d23b-5aa0-4fab-b5d0-5c9cf95c7ea4.png)

**Comment by TiviPlus** [comment]
```
	if(SSticker && SSticker.current_state == GAME_STATE_PLAYING) //game has started, to ignore the map placed corpses.
		GLOB.round_statistics.total_human_deaths++
		SSblackbox.record_feedback("tally", "round_statistics", 1, "total_human_deaths")
```
