### ISSUE TITLE
Flamer cant fire into the darkness anymore

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#9283]
### Description

equip flamer
click on dark/hidden tile
no shoot
cry

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [12883](https://scrubby.melonmesa.com/round/12883)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 16757236aabf72df4d11e217077a1ba6e6c7eecc
The following pull requests are currently test merged:
#9227: 'Evacuation can prevent xeno major' by BraveMole at commit 65dfee5d3f
#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46514
#9195: 'Add support for piercing projectiles' by Waselon at commit 1e22f86757
#9115: 'Ghosts can assume control of minions' by BraveMole at commit 5f2185eefb
#9237: 'The Hypospray Belt' by novaepee at commit b90fd4d2df
#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit 7148efa111
#9207: 'Add teleporters pad to req' by BraveMole at commit ebfc5be6ff

Local commit: b1d1626707a6a069dabcf6a5cf0e442a67809711
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

load flamer
equip flamer
click on tile hidden by resin walls/darkness
no shoot

**Comment by BraveMole** [comment]
They can. It's a weird bug that happens on very rare occasion, and it's client specific IIRC

**Comment by yyzsong** [comment]
> They can. It's a weird bug that happens on very rare occasion, and it's client specific IIRC

change byond versions to code
flamer stops working
mfw
