### ISSUE TITLE
sometimes roundstart gens aren't corrupted

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#9308]
### Description

expect to happen:
generator looks corrupted
marines open shutters
gives psy points

what actually happens: 
generator looks corrupted
marines open shutters
gives no psy points
needs to be corrupted to give psy again

seems to have been happening for quite a while now

### Test Merges

#9227: 'Evacuation can prevent xeno major' by BraveMole at commit c936480b59
#9207: 'Add teleporters pad to req' by BraveMole at commit ebfc5be6ff
#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit 7148efa111
#9220: 'Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.' by hyper2snyper at commit 15e0f46514
#9271: 'Reworks scatter.' by SplinterGP at commit cdd4c14974
#9115: 'Ghosts can assume control of minions' by BraveMole at commit 98d3a8d690
#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit dc916e17d5

### Reproduction Steps

open shutters
have marines groundside
check psypoints
no psy points gained

**Comment by Ragecrabbo** [comment]
can confirm this has happened in multiple rounds on different maps

**Comment by Ragecrabbo** [comment]
still happening as of today, recorrupting gens had no effect and xenos had no passive psi or larva gen for the entire hour long round.
