### ISSUE TITLE
Grille in Icarus Shipyard that takes up 3 tiles while having a 1 tile sprite

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9345]
### Description

read title

### Test Merges

#9333 #9266 #8932 #9115 #9220 #9239 #9207 #9227 #9144 (Im too lazy to grab only the map tm)

### Reproduction Steps

Just watch the video below

### Screenshots

https://user-images.githubusercontent.com/24631139/150293913-024cfe1f-d94b-4d1c-bd82-138fddf6e014.mp4

**Comment by BraveMole** [comment]
dead map
