### ISSUE TITLE
Last letter of command orders gets cut off

### ISSUE THREAD

**Issue by chesse20** [tgstation/TerraGov-Marine-Corps#9346]
### Description

The last letter shouldn't get cut off when sending command orders

### Test Merges

I remember this happening way before any of the current test merges were added

### Reproduction Steps

1. play captain
2. type in a command order
3. last letter gets cut off

**Comment by KuzyXD** [comment]
Can't reproduce. Tried as spatial agent, as latejoin captain. Everything is ok.
