### ISSUE TITLE
Nice flamethrower 

### ISSUE THREAD

**Issue by Braun1719** [tgstation/TerraGov-Marine-Corps#9354]
### Description

I don't know what idiot came up with this. But you have a flamethrower through the walls, you are completely fucked, right?

### Test Merges

1

### Reproduction Steps

1

### Screenshots

1

**Comment by BraveMole** [comment]
Not a bug

**Comment by Braun1719** [comment]
Oh it,s the stupid ficha very stupid for the good fire spam vs xeno for the wall
