### ISSUE TITLE
Putting the second teleporter in an area that can't take an APC lets you use it without needing a cell

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9360]
### Description

read title

### Test Merges

#9355 #9333 #9266 #8932 #9239 #9207 #9227

### Reproduction Steps

1. Put teleporter in fob
2. Put other teleporter in caves/areas that can't take apcs

### Screenshots

https://user-images.githubusercontent.com/24631139/150615433-a42b210c-45f0-4aa9-9709-cba3b04a1814.mp4

**Comment by BraveMole** [comment]
Fixed
