### ISSUE TITLE
King can summon to end-of-round deathmatch arena

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#9375]
### Description

mfw

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [13028](https://scrubby.melonmesa.com/round/13028)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: f133e1f9f8d117373017644e1c7f894620b2270d
The following pull requests are currently test merged:
#9262: 'Fix buckled bag not moving with roller bed' by BraveMole at commit 86666d1828
#9355: 'Debug pr to find out where that damn sleep is' by BraveMole at commit e6dc9a479e
#9333: 'Fix some move issues' by BraveMole at commit 07660a94d2
#9266: 'Pain update (tm first)' by BraveMole at commit e7fc7ada70
#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit c49d622ff9
#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit 7148efa111
#9207: 'Add teleporters pad to req' by BraveMole at commit bed7f685a7
#9227: 'Evacuation can prevent xeno major' by BraveMole at commit 1f287382ed
#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5
#9271: 'Reworks scatter.' by SplinterGP at commit c78e80a5b5
#9371: 'Add valhalla specific ban' by BraveMole at commit 1896a33fe0

Local commit: c63e7f25e9ddf26b88054078e781600a612411e3
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. get king
2. go to EORD dome
3. Psi summon
4. ???

### Screenshots

![image](https://user-images.githubusercontent.com/65325586/150659257-83a757c8-5a49-4e9d-999c-581fa730645d.png)

**Comment by BraveMole** [comment]
uh, how is that an issue? It's EORD, the game is over
