### ISSUE TITLE
IVs don't give non-blood

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/TerraGov-Marine-Corps#939]
As in, they seemingly won't give other chems if they're placed in an IV drop and set to injecting.

## Reproduction:

1) Insert beaker/bottle of a selected chemical into an IV drip.
2) Ensure IV is on inject mode.
3) Connect yourself, and analyze yourself with a HF2.
4) Observe... nothing?

**Comment by Ghommie** [comment]
I intended to port in /tg/code IV months ago, but apparently I didn't revert some initial changes when I opted it out for the time being.

**Comment by DominikPanic** [comment]
:whip: @Ghommie

**Comment by Ghommie** [comment]
Edit: Actually it wasn't me, it was some bad design choice from the past. They crapped out the injection of other reagents apparently.
