### ISSUE TITLE
New non-transparent transvitox and hemodile do not block sentry los.

### ISSUE THREAD

**Issue by Ragecrabbo** [tgstation/TerraGov-Marine-Corps#9394]
### Description

Sentries will target and shoot xenos that are hiding inside transvitox and hemodile smoke and will also not stop shooting if in the smoke themselves.

### Test Merges

Guh

### Reproduction Steps

1.Be defiler
2.Use transvitox or hemodile smoke
3.Sentries still target and shoot you in the smoke

### Screenshots

https://user-images.githubusercontent.com/85963263/150835493-26ffd799-e303-4659-b4b8-2e7bcf6ec283.mp4

**Comment by BraveMole** [comment]
fixed
