### ISSUE TITLE
Clicking req order console brings up blue screen

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#9398]
### Description

what I expect to happen: req supply console opens up, I'm able to see requests, req points, etc

what actually happens: bluescreen

### Test Merges

#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5
#9207: 'Add teleporters pad to req' by BraveMole at commit 422ec29add
#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit 7148efa111
#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 556685b6aa
#9266: 'Pain update (tm first)' by BraveMole at commit e7fc7ada70
#9355: 'Debug pr to find out where that damn sleep is' by BraveMole at commit e6dc9a479e
#9262: 'Fix buckled bag not moving with roller bed' by BraveMole at commit 86666d1828
#9271: 'Reworks scatter.' by SplinterGP at commit 9571dca728

### Reproduction Steps

be ghost
click on supply ordering console
pain

### Screenshots

https://cdn.discordapp.com/attachments/877777075027714148/935268180174180432/unknown.png

**Comment by BraveMole** [comment]
ghosts don't have acccess to req, this is more of a feature request than anything and this is a duplicate bug report
