### ISSUE TITLE
Laser Pistol Has Hidden Full Auto Mode

### ISSUE THREAD

**Issue by ghost** [tgstation/TerraGov-Marine-Corps#9401]
### Description

The laser pistol is supposed to have three modes of fire. When you first vend the gun it starts in Standard mode as intended with normal fire delay, but if you then select Standard mode from the radial menu the gun switches to firing full auto. The full auto bolts fire as fast as efficiency MG bolts and appear identically blue in color, but they do normal Laser pistol damage. There is no way (that I know) to return the gun to Standard mode.

So you double your fire rate while also making the recoil much more manageable via full auto with 0 draw backs

### Test Merges

BYOND Version: 514.1575
Server revision compiled on: 
Master commit: 09f4a141ad32e2952271bf7bd33f7633a7927494
The following pull requests are currently test merged:
#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5
#9207: 'Add teleporters pad to req' by BraveMole at commit 422ec29add
#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit 7148efa111
#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 556685b6aa
#9266: 'Pain update (tm first)' by BraveMole at commit e7fc7ada70
#9355: 'Debug pr to find out where that damn sleep is' by BraveMole at commit e6dc9a479e
#9262: 'Fix buckled bag not moving with roller bed' by BraveMole at commit 86666d1828
#9271: 'Reworks scatter.' by SplinterGP at commit 9571dca728

Local commit: 2296695494e68cc34ea4e8147938a6e29562ba29
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Vend Laser Pistol
2. Press space to bring up radial fire select menu
3. Choose "Standard"
4. Delete Rouny in .3 seconds

**Comment by BraveMole** [comment]
fixed
