### ISSUE TITLE
When strapped into a stasis bag and a medevac stretcher, can survive OBs and CAS

### ISSUE THREAD

**Issue by Repth1** [tgstation/TerraGov-Marine-Corps#941]
## Reproduction:

Was strapped into a stasis bag and a medevac stretcher in crit and had 2 CAS strikes and an incendiary OB fall on me without dying. Marine outside the bag died as expected.

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by Shadow-Quill** [comment]
Likely caused by the same thing as #868

**Comment by DominikPanic** [comment]
Nah that one is different

**Comment by DominikPanic** [comment]
All of this things should ideally have ex_act etc. passthrough but this would require components to be handled nicely.

**Comment by Ghommie** [comment]
ex_act() would call itself upon any atom inside the affected contents, but not here yet because the code is quite old.

**Comment by Rohesie** [comment]
It would be cheaper to simply make stuff that can contain mobs call `ex_act()` on their mob contents.
Calling itself on every single atom inside might be a bit of overkill for our purposes.

**Comment by Ghommie** [comment]
Taking an object/mob's bomb armor into account in order to dampen or stop explosions from affecting the contents would be a better long-term solution. Though barely anything calls . = ..() there as of now.
