### ISSUE TITLE
Some intel terminals don't let you activate it despite the round going on for a long amount of time

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9415]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Go to intel 
2. It's been almost an hour and a half
3."This terminal has nothing of use on it"

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/151099712-3bd3937b-0526-4c65-b5a7-089db6938143.png)

**Comment by BraveMole** [comment]
Isn't that completly random ?

**Comment by Derrick2Electricboogaloo** [comment]
It do be doing random chances though.
