### ISSUE TITLE
e to equip doesn't work with rail lights

### ISSUE THREAD

**Issue by factoryman942** [tgstation/TerraGov-Marine-Corps#942]
1. stand in dark room
2. put a rail light on your gun, put it into your armour
3. if you click the armour slot to take out/put in your gun, you will continue to be light
4. if you press E to equip your gun, the rail light will not produce light. You will still have light from other light sources on your person (e.g. armour lamp)
@DominikPanic 🗞

**Comment by Alterist** [comment]
Known issue

**Comment by DominikPanic** [comment]
@Surrealaser since he has a PR up

**Comment by Alterist** [comment]
#532
