### ISSUE TITLE
You can remove sentries off dropship hardpoint turrets

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9431]
### Description

Read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Deploy dropship turret
2. Undeploy it
3. Free sentry

### Screenshots

I'm too lazy to get one, I'll do it later if it's really needed.

**Comment by Lumipharon** [comment]
Isn't this intended? I swear there's even a tip about it or something.

**Comment by BraveMole** [comment]
Is that fixed ? @DeltaFire15
