### ISSUE TITLE
Primo spitter does not have Proper quick firerate.

### ISSUE THREAD

**Issue by vilereaver41** [tgstation/TerraGov-Marine-Corps#9433]
### Description

Figured it deserves its own bug report so it isnt forgotten.

Basically, primo spitter atm just nerfs basic spit damage without the quick fire rate.isn't

### Test Merges

Unsure which merge is affecting it as it was made available with the rest.

### Reproduction Steps

No reproduction steps. once you evolve into primo spitter you just have ancient spitter fire rate.

**Comment by BraveMole** [comment]
Duplicate
