### ISSUE TITLE
You can plasmacut valhalla and fulton xeno bodies

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9468]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Plasma cut the cave walls in valhalla
2. Fulton dead xeno bodies (WHY DO YOU GET FULTONS IN VALHALLA)
3. Profit.

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/151750646-7985b17b-5d5a-41bd-8349-0b639bf1ddf8.png)

**Comment by RipGrayson** [comment]
> ### Description
> 
> read title
> ### Test Merges
> 
> doesn't matter
> ### Reproduction Steps
> 
>     1. Plasma cut the cave walls in valhalla
> 
>     2. Fulton dead xeno bodies (WHY DO YOU GET FULTONS IN VALHALLA)
> 
>     3. Profit.
> 
> 
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/24631139/151750646-7985b17b-5d5a-41bd-8349-0b639bf1ddf8.png)

This shouldn't be possible outside of admin intervention, here's Valhalla with invincible sections revealed.
![revealedinvin](https://user-images.githubusercontent.com/49290523/151839939-477fed78-81cb-4788-ae9f-4f62c43aa58b.png)
I'll test it locally and see if I can replicate this bug.

**Comment by private-tristan** [comment]
it seems that the smoothed invincible walls can be plascutted, recently had a round end and see someone plascut the rock walls on the end of EORD

**Comment by BraveMole** [comment]
You can fulton xeno all you want, it won't give points since you are from the neutral faction

**Comment by RipGrayson** [comment]
> it seems that the smoothed invincible walls can be plascutted, recently had a round end and see someone plascut the rock walls on EORD

Yes, plasmacutter is full of undocumented shitcode and I wrongly assumed that "RESIST_ALL" would keep players from cutting the rock. 
I was wrong.
Turns out that the things a plasmacutter can't cut are both undocumented and hardcoded and a plasmacutter does not care at all about resistance flags when cutting turfs.  
As mentioned above, this pull should https://github.com/tgstation/TerraGov-Marine-Corps/pull/9480 fix the issue by making PCs actually check for proper resistance flags.

**Comment by Ragecrabbo** [comment]
As RipGrayson said this is a plasmacutter issue and doesent have anything to do with valhalla itself. You can cut any walls of a certain type with a plasmacutter which currently means you can freely leave valhalla, EORD arena and break a lot of groundmaps aswell. Hopefully this gets a fix merged soon as malicious use of this could seriously affect rounds.
