### ISSUE TITLE
Warrior Lunge Adjacent Range Failure

### ISSUE THREAD

**Issue by AzonStarfall** [tgstation/TerraGov-Marine-Corps#9478]
### Description

When lunging at a target with the Lunge ability as Warrior, if performed from the 8-adjacent tiles (4 cardinal, 4 diagonal), the lunge will always miss.

This lunge should contact and grab the marine, but it just cancels the ability and starts the recharge timer.

### Test Merges

#9438: 'hivemind tweaks lol' by lovegreenstuff at commit 28267a042e
#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5

### Reproduction Steps

1. Spawn as Warrior
2. Locate a target
3. Attempt to lunge at them from an adjacent tile
4. Observe as lunge fails

**Comment by BraveMole** [comment]
Fixed
