### ISSUE TITLE
Xenos can exit broken pipes into dense turfs

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9487]
### Description

If the ship in crash lands right on a wall with a pipe going through it, xenos can go through the pipe and exit it onto the outer hull tiles of the ship.

This leaves them free to shoot acid at nerds inside without being able to be shot, then they can just walk out when they're done.

### Test Merges

Doesn't matter

### Reproduction Steps

break pipe under a wall.
vent crawl out onto the wall.

**Comment by Notamaniac** [comment]
There's an edge case here where a xeno gets stuck between a pipe leading to a wall and a welded off vent. I don't think there's any way of practically solving that, so this is probably going to have to stay as the lesser evil. Then again there's the edge case of every single vent being welded off, so I'm not exactly sure how to handle this.

**Comment by Lumipharon** [comment]
would it be possible to just make it so xenos can't exit/enter a vent onto a dense turf? It seems a bit strange that if a wall is on top of a vent you can still use it.
