### ISSUE TITLE
Generations in prison station look corrupted (they're not)

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9541]
### Description

read title

### Test Merges

#8932 #8633 #9500 #9480 #9239 #9293 #9223 #9408

### Reproduction Steps

1. Psy passive gen not happening
2. Go to generators
3. They're all corrupted
4. Try to corrupt them anyway
5. It corrupts them as if they weren't corrupted

### Screenshots

https://user-images.githubusercontent.com/24631139/152697599-ec2374e8-b9a7-4310-9004-39fb4ed61425.mp4

**Comment by BraveMole** [comment]
duplicate
