### ISSUE TITLE
Devoing xenos snaps them out of existence (again)

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9545]
### Description

read title

### Test Merges

#8932 #8633 #9500 #9480 #9239 #9293 #9223 #9408

### Reproduction Steps

1. Ask to get devoed
2. Get vibechecked

### Screenshots

https://user-images.githubusercontent.com/24631139/152700391-c3279bf4-f574-4d3f-87eb-209755cd964f.mp4

**Comment by BraveMole** [comment]
any runtime?

**Comment by 2whatever2** [comment]
![image](https://user-images.githubusercontent.com/24631139/152705824-67064c25-f118-43ad-b0ea-a57e132ae398.png)
Only thing related to me.
