### ISSUE TITLE
Hivemind chat stops working due to hivemind core dying

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9549]
### Description

read title

### Test Merges

#9408 #9223 #9293 #9239 #9480 #8633

### Reproduction Steps

Tivi said the cause is nulling of hivemind reference + hard del in xeno_by_typepath.

### Screenshots

![image](https://user-images.githubusercontent.com/24631139/152704680-30dcd32f-5692-4416-96ce-6959ee4d9fb8.png)
Happened in these two rounds: 13284, 13269

**Comment by BraveMole** [comment]
I think it's fixed
