### ISSUE TITLE
Binding disguise and toggle stealth to the same key makes you perma invisble as hunter

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9551]
### Description

read title

### Test Merges

#9408 #9223 #9293 #9239 #9480 #8633

### Reproduction Steps

1. Bind disguise and toggle stealth to the same key
2. Use it
3. Leave disguise
4. Free stealth

### Screenshots

https://user-images.githubusercontent.com/24631139/152707499-528b8b1c-21c9-4671-a2c5-c9d4ab8b6ede.mp4

**Comment by BraveMole** [comment]
fixed
