### ISSUE TITLE
Shoulder gun module not reloading

### ISSUE THREAD

**Issue by SrSC0ndition** [tgstation/TerraGov-Marine-Corps#9555]
### Description

That bug is in since the shoulder module was introduced, you really had not enough time to fix it???

### Test Merges

The following pull requests are currently test merged:
[#9408: 'Xeno upgrade changes' by BraveMole at commit 6e96f331e5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9408)
[#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9223)
[#9293: 'Primos can be bought by tiers' by BraveMole at commit fa1768c49e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9293)
[#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit d08859caf8](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9239)
[#9480: 'Refactors some plasmacutter behavior, squashes a number of plasmacutter bugs' by RipGrayson at commit a20cdbfe21](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9480)
[#8633: 'Motorbike sidecar' by TiviPlus at commit acadda8c6b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8633)

### Reproduction Steps

1 - Get a module on gun and attach it on your armour
2 - Follow the instruction 
3 - Find our the instruction is flawed and no method of reloading works, aside from just strapping your armor off, taking the gun out and reloading it by hand.  Mags don't work on assigned button. Handfuls don't work on assigned button

### Screenshots

![image](https://user-images.githubusercontent.com/84919933/152717714-07e2706b-90a1-4f09-8b8a-aa5becb09331.png)

**Comment by OpsCoretango** [comment]
Tried a tactical reload?

**Comment by BraveMole** [comment]
"That bug is in since the shoulder module was introduced, you really had not enough time to fix it??" 

You should cut down on the entitlement, we are neither paid nor your slaves.

**Comment by OpsCoretango** [comment]
> "That bug is in since the shoulder module was introduced, you really had not enough time to fix it??" 
> 
> You should cut down on the entitlement, we are neither paid nor your slaves.
> Most people are gratefull that contributors are giving their free time to add content to this game, if you are not happy about it the door is right there.

So is only option is detach module from armor reload gun manually?

**Comment by SrSC0ndition** [comment]
Oh, I am so sorry I've insulted your great work, but don't justify yourself over it, you've coded in a half broken thing and simply forgot about it totally

**Comment by BraveMole** [comment]
> Oh, I am so sorry I've insulted your great work, but don't justify yourself over it, you've coded in a half broken thing and simply forgot about it totally, and if you're so easily offendable, consider taking pills to help your nerves
> 
> People have the other funny bug - their shoulder gun uses the unique action all the time, thus wasting munitions or not doing anything

Last warning, next time it's gitban
