### ISSUE TITLE
TX-73 Lasrifle

### ISSUE THREAD

**Issue by InterroLouis** [tgstation/TerraGov-Marine-Corps#9564]
### Description

I expected to be able to load it. I could not load the TX-73 lasrifle battery into the TX-73 lasrifle. 

### Test Merges

Round ID: [13300](https://scrubby.melonmesa.com/round/13300)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: 43171fc1f5b83f45c7f24b430fc5b7d355ec9d70
The following pull requests are currently test merged:
#8633: 'Motorbike sidecar' by TiviPlus at commit acadda8c6b
#9239: 'Adds the 6E Chameleon Cape' by hyper2snyper at commit d08859caf8
#9293: 'Primos can be bought by tiers' by BraveMole at commit fa1768c49e
#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5
#9408: 'Xeno upgrade changes' by BraveMole at commit 6e96f331e5
#9227: 'Evacuation can prevent xeno major' by BraveMole at commit d31a23edc6
#9496: 'Drone get ranged building ability ; Xenos can no longer build on their turf' by BraveMole at commit dbb92307d3
#9522: 'Ports TG vox system, AI can make vox announcements' by RipGrayson at commit 4e6cf73187

### Reproduction Steps

Get a TX-73 lasrifle such as is provided by the Emperor to the Imperial Guard, and try to reload it after the cell inside it runs out. Find that you cannot reload it with the provided cells. 

### Screenshots

![image](https://user-images.githubusercontent.com/29074600/152878350-8af0cd2e-692c-46c9-9b81-f4dc027b19af.png)

**Comment by David-Stormwell** [comment]
Mostly likely due to the new lasers gutting up most of any of the older lasers, as the older lasers where coded as the parents.
Most likely fix would be to shift the Guard's laser gun code into a child, and make the current parent unobtainable.
