### ISSUE TITLE
Sentries not firing

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9582]
### Description

I'm not sure if this a once off or not, but currently the sentries aren't firing at xenos even though they appear to be trying to target them.

I'm not certain what's causing it as I couldn't recreate it in valhalla trying all the firing modes and radial on/off, but all the fob turrets in this round had the same issue.

https://user-images.githubusercontent.com/7869430/153117819-6bdf0fc3-1d97-4c5d-99cc-e308111a6b49.mp4

### Test Merges

[#9293: 'Primos can be bought by tiers' by BraveMole at commit fa1768c49e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9293)
[#9223: 'You can send supply drop in caves' by BraveMole at commit 3418bbede5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9223)
[#9227: 'Evacuation can prevent xeno major' by BraveMole at commit d31a23edc6](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9227)
[#9496: 'Drone get ranged building ability ; Xenos can no longer build on their turf' by BraveMole at commit dbb92307d3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9496)
[#9522: 'Ports TG vox system, AI can make vox announcements' by RipGrayson at commit 4e6cf73187](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9522)

### Reproduction Steps

NA

**Comment by BraveMole** [comment]
they are on radial, which means lower range, which might be it

**Comment by Lumipharon** [comment]
> they are on radial, which means lower range, which might be it

Radial is 5 or something, but in the video benos are literally resting 3 tiles away, plus I watched them all just walk directly past another sentry to enter FOB.

**Comment by BraveMole** [comment]
not reproduced
