### ISSUE TITLE
Neurotoxins

### ISSUE THREAD

**Issue by krutoi2000** [tgstation/TerraGov-Marine-Corps#9593]
### Description

Transperent gas mask with activated oxygen tank doesn't help you againts neurotoxins

### Test Merges

-

### Reproduction Steps

Put mask, tank, let spiter through a grenade and die, because why?

### Screenshots

-

**Comment by novaepee** [comment]
BLOCKGASEFFECT does not 100% block neurotoxin, or for that matter any xenomorph gas. This is intended, not bug.

**Comment by BraveMole** [comment]
intended

**Comment by krutoi2000** [comment]
My problem later was that I probably received whole doze of neurotoxin. Later, I found out that pressure in oxygen tank haven't changed at all, which can assume that I wasn't protected at all.
