### ISSUE TITLE
Hunter standing still stealth doesn't even work

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9620]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Try to stand still as hunter,
2. It doesn't update
3. Cope
4. Check alpha values and realize they're both the same level despite the other hunter standing for more than 4 seconds

### Screenshots

https://user-images.githubusercontent.com/24631139/153696782-00cb3551-a071-4ab2-9a7c-edc9844d2025.mp4

![image](https://user-images.githubusercontent.com/24631139/153696786-4759cf28-e527-48af-bb92-87d165062969.png)

**Comment by Ragecrabbo** [comment]
Somewhat related thats been happening for ages, walking and then letting go of the walk button too soon after stopping will make you visible as if you had been running.
