### ISSUE TITLE
Synths can use throwing knives

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#9623]
### Description

as above

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [13362](https://scrubby.melonmesa.com/round/13362)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [18c321ebdf1f9ed795de779ca3e7fb9ec619b8b5](https://github.com/tgstation/TerraGov-Marine-Corps//commit/18c321ebdf1f9ed795de779ca3e7fb9ec619b8b5)
The following pull requests are currently test merged:
[#9293: 'Primos can be bought by tiers' by BraveMole at commit f13104225d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9293)
[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 7157f2d2bf](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9569: 'Xenomorphs cannot use most abilities nor attack while on a solid turf (e.g. a resin wall)' by DeltaFire15 at commit e7585bf82e](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9569)

Local commit: 167bddae25f5de798a845e64f550631ab5b92bcc
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

Be synth
grab knives
click
shoot bean

**Comment by Notamaniac** [comment]
This technically might not be a bug, since throwing knives loosely fall under the tag of 'melee' weapon, and synths are only restricted from using guns.
