### ISSUE TITLE
Admin "freeze"  + has entered long-term hypersleep storage bug.

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#963]
## Reproduction:
1. Admin "black screen freeze" someone
2. Doctor puts frozen someone to cryosleep. 15 minute timer starts
3. Doctor Removes someone from cryosleep sleeper
4. Black screen "admin freeze" disappears
5. After 15 minutes "has entered long-term hypersleep storage."

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by DominikPanic** [comment]
@Ghommie Since you have a PR up, people shouldn't be able to remove others from cryo

**Comment by DominikPanic** [comment]
Fixed
