### ISSUE TITLE
laser weapons on experimental attachment point

### ISSUE THREAD

**Issue by 2kajowsmol** [tgstation/TerraGov-Marine-Corps#9633]
### Description

When using the laser MG with the experimental shoulder attachment point, right clicking to shoot it constantly opened up the menu to choose efficiency mode or normal mode. 

I'm guessing this issue also occurs on other laser weapons with multiple fire modes.

### Test Merges

[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 7157f2d2bf](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9569: 'Xenomorphs cannot use most abilities nor attack while on a solid turf (e.g. a resin wall)' by DeltaFire15 at commit 069cbc60e3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9569)
[#9629: 'Deployables can no longer be deployed into nullspace' by Notamaniac at commit 8e5c02f3de](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9629)

### Reproduction Steps

Get experimental attachment point.
Attach laser MG
Shoot.
See menu pop up.

**Comment by BraveMole** [comment]
Fixed soon by a pr
