### ISSUE TITLE
Lv 624 tunnels are not initialized properly

### ISSUE THREAD

**Issue by Kingtrin** [tgstation/TerraGov-Marine-Corps#964]
## Testmerges:

#716 #951 #957 #896 #903 #914 #936 #864 #827 #711 #564 #772 #933 #935 #950 #954 #953 #894 #961 #960 #959

## Reproduction:

Certain tunnels on LV don't spawn correctly giving the message "this doesn't seem to lead anywhere" when benos attempt to use them. The examination text also confirms this. Furthermore, It has been reported but not reproduced that tunnels can end up being 'one-way' leaving benos stranded on the opposite side of the fog. Likely related to #750

**Comment by spookydonut** [comment]
All tunnels or only some?

**Comment by DominikPanic** [comment]
@spookydonut all tunnels on all maps #823 apparently failed again
