### ISSUE TITLE
Crusher primo doesn't stun unless you're adjacent

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9641]
### Description

read title (lowered cooldown and cost when I tested)

### Test Merges

doesn't matter

### Reproduction Steps

1. Try to use rapid advance
2. Cope when it doesn't stun

### Screenshots

https://user-images.githubusercontent.com/24631139/153816510-c42889b4-f438-4e97-a64c-c25e283bb6f3.mp4

**Comment by cheapcents** [comment]
Don't think this is a bug.
And if it is, it probably should be left this way 'cause it's a pretty good way to increase the skill cap on crusher
