### ISSUE TITLE
Clicking a Hand Held Cell Charger no longer removes the cell

### ISSUE THREAD

**Issue by ChocolateBickie** [tgstation/TerraGov-Marine-Corps#9643]
### Description

Until recently, clicking a Hand-Held cell charger with a power cell in it removed the cell.

However, now the Hand-Held Cell Charger simply moves to the alternate hand.

There is no way to remove the power cell without swapping in a new cell, which then becomes trapped.

### Test Merges

[#9569: 'Xenomorphs cannot use most abilities nor attack while on a solid turf (e.g. a resin wall)' by DeltaFire15 at commit 069cbc60e3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9569)

### Reproduction Steps

1. Get an empty hand held cell charger
2. Put in a power cell
3. Attempt to remove power cell
4. Fail

**Comment by Notamaniac** [comment]
#9572 changed it so it was a right click action, and can only ever be done via right click, as per the ethos of dabbing on people who disable their right click.

So um yeah.
