### ISSUE TITLE
Why ALL the spare power cells in engineering empty?

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#965]
## Reproduction:
It takes half hour to recharge powercell sitting

**Comment by Menshin** [comment]
Bad design decision.

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by Shadow-Quill** [comment]
They were changed in #626. Twelve are always on/generating power. The reactors produce more power and are less likely to implode.

**Comment by DominikPanic** [comment]
@Menshin Perhaps some should start filled?

**Comment by Menshin** [comment]
Probably, i'll discuss this on #balance when i'm done with flame spreading.

**Comment by Alterist** [comment]
Changed in #980
