### ISSUE TITLE
Dead synth shows as unrevivable in examine and minimap

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#9677]
### Description

As synth, dying ends up with your examine text showing as cold and your minimap icon as a red cross. Getting revived will keep your minimap icon as a red cross moving around. On minimap there is no distinction between unrevivable marine and dead revivable synth.

### Test Merges

None

### Reproduction Steps

Step 1: Die

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/154869969-3b1da56b-6b0f-47e1-8e30-968eacf5e428.png)
![image](https://user-images.githubusercontent.com/72712909/154869975-038c3bb2-c701-4e27-9f21-33a2f813f7ec.png)
![image](https://user-images.githubusercontent.com/72712909/154869986-f0f17872-1e3f-4591-8e50-11a47e5c0d3a.png)

**Comment by BraveMole** [comment]
Killed my self as a synth on loca, no problem. Are you immediately red on map ?

**Comment by Losenis** [comment]
Again got it, moved around to confirm it's me. Still there even after an aheal.

![image](https://user-images.githubusercontent.com/72712909/184736052-a0039505-e2dc-48b2-a214-1ef6f6ba9ebc.png)
![image](https://user-images.githubusercontent.com/72712909/184736080-45518f1f-3374-45f3-848f-a8398ac73aec.png)

**Comment by Derrick2Electricboogaloo** [comment]
> Killed my self as a synth on loca, no problem. Are you immediately red on map ?

Die and wait 5+ minutes, however long it takes for a marine to perma, and this will happen.

**Comment by Derrick2Electricboogaloo** [comment]
> Again got it, moved around to confirm it's me. Still there even after an aheal.
> 
> ![image](https://user-images.githubusercontent.com/72712909/184736052-a0039505-e2dc-48b2-a214-1ef6f6ba9ebc.png) ![image](https://user-images.githubusercontent.com/72712909/184736080-45518f1f-3374-45f3-848f-a8398ac73aec.png)

Eventually it will go away after an aheal, die and get revived usually works for me.
