### ISSUE TITLE
Synth keeps damaged UI when fully healed

### ISSUE THREAD

**Issue by Losenis** [tgstation/TerraGov-Marine-Corps#9678]
### Description

Self explanatory images

### Test Merges

None

### Reproduction Steps

Die, revive, heal to full

### Screenshots

![image](https://user-images.githubusercontent.com/72712909/154870121-a799e866-fa32-4e10-97b3-15690c1d17cd.png)
![image](https://user-images.githubusercontent.com/72712909/154870138-6246e102-c08c-4969-bd7a-378bf3c588dc.png)

**Comment by BraveMole** [comment]
Can't reproduce, is that happening every time ?

**Comment by Derrick2Electricboogaloo** [comment]
> Can't reproduce, is that happening every time ?

So this happens when the 'death timer' goes over 5 minutes, while you can get revived, the game shows you up as perma and this is a bug I noticed along with it. Overlay stays messed up until you get an Aheal.
