### ISSUE TITLE
FIX sprites

### ISSUE THREAD

**Issue by Monikawales** [tgstation/TerraGov-Marine-Corps#969]
## Reproduction:
![image](https://user-images.githubusercontent.com/45321263/53715417-cc7d6d80-3e62-11e9-8d9b-3b60f43ee7c0.png)

**Comment by DominikPanic** [comment]
@Alterist

**Comment by MrStonedOne** [comment]
Please do not leave format template noise in your issue body. Remove any section that does not apply.

**Comment by Alterist** [comment]
yes like i would know what that is
