### ISSUE TITLE
wraiths can't unbanish themselves

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9690]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Banish yourself
2. Try to unbanish
3. Realize you can't escape.

### Screenshots

https://user-images.githubusercontent.com/24631139/155266042-533f2589-1b25-4b53-bb94-b12688d39ebe.mp4

**Comment by Redstonize** [comment]
funny
