### ISSUE TITLE
Runechat for actions only shows up under walls

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#9703]
### Description

what I expect to happen: runechat is visible above my head, where I can read it easily

### Test Merges

[#9698: 'Implements Sanctions' by Squigger at commit 876846ddcb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9698)
[#9568: 'Make the T-64 Great Again' by Redstonize at commit cf661ac387](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9568)
[#9650: 'Adds the TAT-36 AT Gun' by Pariah919 at commit 5c5de72668](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9650)

### Reproduction Steps

be xeno or have some way of making runechat
stand next to wall/resin wall
toggle bumpslash/overheal a xeno/whatever else should make a overhead message
wonder why only words are visible under the wall tile

### Screenshots

![image](https://user-images.githubusercontent.com/54422837/155829107-d67672e6-7fab-402c-aead-82973d6bd215.png)

**Comment by RipGrayson** [comment]
Sounds like a problem with balloon_alert, which was fixed here https://github.com/tgstation/TerraGov-Marine-Corps/pull/9817.
Do you still see this bug when playing?

**Comment by private-tristan** [comment]
oops, forgot about this, it shows up just fine now.
