### ISSUE TITLE
burrowed don't spawn automatically when shutters are down

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#9705]
### Description

what I expect to happen:
see burrowed larva
see that shutters are down
enter larva queue
spawn as a larva 

what happens:
see burrowed larva
see that shutters are down
enter larva queue
not spawning in

the bug seems to happen around 12:25 or so? maybe it has to do with tadpole landing in FoB?

### Test Merges

[#9698: 'Implements Sanctions' by Squigger at commit 876846ddcb](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9698)
[#9568: 'Make the T-64 Great Again' by Redstonize at commit cf661ac387](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9568)
[#9650: 'Adds the TAT-36 AT Gun' by Pariah919 at commit 5c5de72668](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9650)

### Reproduction Steps

Observe
enter larva queue around 12:25

### Screenshots

![image](https://user-images.githubusercontent.com/54422837/155860391-f4efd6eb-77b8-4de2-9580-251e7674b292.png)
![image](https://user-images.githubusercontent.com/54422837/155860398-a3f0c69c-4342-4d81-b693-7f9558439901.png)

**Comment by private-tristan** [comment]
Okay I'm like 99% sure this is related to tadpole landing inside FoB, because it seems that tadpole gives psy points, silo larva points, and stops burrowed from automatically spawning from deadchat as long as it's on the ground.

**Comment by BraveMole** [comment]
not a bug, you are correct on you last comment.
