### ISSUE TITLE
FC's m1911 Custom cannot be reloaded

### ISSUE THREAD

**Issue by Araulius** [tgstation/TerraGov-Marine-Corps#9711]
### Description

after firing the pistol until empty the magazines that come with the pistol should be able to be loaded into it.

however, upon attempting to reload it, it gives a "There is no room for the M1911 magazine (.45)!" Error message.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [13606](https://scrubby.melonmesa.com/round/13606)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [7dc344fa61066ccaa06eb74592b1fab53c9aff9c](https://github.com/tgstation/TerraGov-Marine-Corps//commit/7dc344fa61066ccaa06eb74592b1fab53c9aff9c)
The following pull requests are currently test merged:
[#9650: 'Adds the TAT-36 AT Gun' by Pariah919 at commit 5c5de72668](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9650)
[#9568: 'Make the T-64 Great Again' by Redstonize at commit cf661ac387](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9568)

Local commit: c94d215a7a26fb0751af358b8e6a2c7336fad737
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

spawn as fc, fire pistol until empty, attempt to reload gun with ammo in belt, and fail.

**Comment by Lumipharon** [comment]
Did you uh... remove the old mag? If you read the description, it mentions it doesn't have the auto mag eject feature.

**Comment by TiviPlus** [comment]
```
	if((length(chamber_items) >= max_chamber_items) && max_chamber_items)
		if(!CHECK_BITFIELD(reciever_flags, AMMO_RECIEVER_ROTATES_CHAMBER))
			to_chat(user, span_warning("There is no room for [new_mag]!"))
			return FALSE
		if(rounds >= max_chamber_items)
			to_chat(user, span_warning("There is no room for [new_mag]!"))
			return FALSE
```
