### ISSUE TITLE
Deployables wipe their acid when undeploying them

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9721]
### Description

read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Acid a deployable (HMG,teleporter etc.) 
2. Marine finds it
3. Picks it up
4. Acid gone

### Screenshots

https://user-images.githubusercontent.com/24631139/156323078-afb3a55f-c66d-4005-b474-2f29ad0bd18d.mp4

**Comment by Lumipharon** [comment]
Isn't that intended? Probably the bug is the person picking it up doesn't get burnt like they do with a normal item like a gun.

**Comment by Losenis** [comment]
I imagine the bug is the acid not damaging the user rather than the acid leaving, given it's already a thing with normal items. Also I'd like to add that ammo boxes don't have their acid removed on pickup, and by extension don't damage the user.
