### ISSUE TITLE
"Grass" in lv624

### ISSUE THREAD

**Issue by chesse20** [tgstation/TerraGov-Marine-Corps#9728]
### Description

Dirt called Grass and function as grass

### Test Merges

BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [45c5f7a4a623a06ab010ee366eb4f1a23a690cf9](https://github.com/tgstation/TerraGov-Marine-Corps//commit/45c5f7a4a623a06ab010ee366eb4f1a23a690cf9)
The following pull requests are currently test merged:
[#9645: 'sentry rework' by Pariah919 at commit 93d1ebb043](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9645)
[#9650: 'Adds the TAT-36 AT Gun' by Pariah919 at commit 4b6864213a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9650)
[#9568: 'Make the T-64 Great Again' by Redstonize at commit 94f7ab116b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9568)
[#9691: 'Shutters now has an alarm played when opening early (and a 18,5~ second delay between button-press and opening)' by mrhugo13 at commit 5b01906629](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9691)
[#9707: 'Modularizes LV-624 lake area, makes a number of mapping QOL changes, fixes some issues.' by RipGrayson at commit 595ddcb35f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9707)

Local commit: 3ae66ba56186eeda98bbd5a73736bcf82a07633d
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

go to the area in the map shown

### Screenshots

![dreamseeker_bZm50G6KAK](https://user-images.githubusercontent.com/9161779/156901564-fc22b57f-4990-416e-a94d-c14bad928e30.png)

**Comment by RipGrayson** [comment]
Nice catch, that's an icon_state varedit from CM that slipped past me. I'll correct it when I get the chance.
