### ISSUE TITLE
CAS Auto fire mission dosent work in Barrenquilla

### ISSUE THREAD

**Issue by FosterGrime-Heymynameslouie** [tgstation/TerraGov-Marine-Corps#9736]
### Description

title

### Test Merges

Round ID: [13694](https://scrubby.melonmesa.com/round/13694)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [bb71356d77cc8022ee1c5b6a52524f1af4f37a5c](https://github.com/tgstation/TerraGov-Marine-Corps//commit/bb71356d77cc8022ee1c5b6a52524f1af4f37a5c)
The following pull requests are currently test merged:
[#9568: 'Make the T-64 Great Again' by Redstonize at commit 94f7ab116b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9568)
[#9707: 'Modularizes LV-624 lake area, makes a number of mapping QOL changes, fixes some issues.' by RipGrayson at commit 595ddcb35f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9707)

### Reproduction Steps

1. Go to CAS
2. Launch CAS
3. Press Being Firemission
4. Nothing happens
5. Cry because your cucked out of anything to do.

**Comment by RipGrayson** [comment]
As of https://github.com/tgstation/TerraGov-Marine-Corps/pull/9798 this issue is no longer a problem due to Barren's removal from our codebase.
