### ISSUE TITLE
Removing the bullets from a mag makes the mag disappear

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9741]
### Description

See title. emptying a mag by shooting is fine, but if you manually pull the bullets out it just vanishes. No invisible sprite, just straight up qdel or some shit.
This has been happening at least for a month or so as it was happening on my local server that I haven't updated in a minute.

### Test Merges

NA

### Reproduction Steps

click on mag with empty hand
repeat until empty
???
Mag is sucked into bluespace

**Comment by Redstonize** [comment]
Is this somehow related to how you can pull slugs from shotgun ammo boxes and make the ammo box disappear ?

**Comment by Lumipharon** [comment]
I assume so, yeah.

**Comment by yyzsong** [comment]
pretty sure it's related to this PR
https://github.com/tgstation/TerraGov-Marine-Corps/pull/9663

**Comment by Lumipharon** [comment]
Fixed by #9840
