### ISSUE TITLE
Most of Barrenquilla starts off unweeded

### ISSUE THREAD

**Issue by Victor239** [tgstation/TerraGov-Marine-Corps#9766]
### Description

It's a widely disliked map so here's one of the issues with it noted down. 

### Test Merges

N/A

### Reproduction Steps

Observe

**Comment by RipGrayson** [comment]
As of https://github.com/tgstation/TerraGov-Marine-Corps/pull/9798 this issue is no longer a problem due to Barren's removal from our codebase.
