### ISSUE TITLE
Game preference = alt F4 

### ISSUE THREAD

**Issue by arkon897** [tgstation/TerraGov-Marine-Corps#9768]
### Description

Duran Surik ( aint i a sinker?) 
round ID: 13758
Ckey: Carkon897
map: mining facility 
Verson: sever recommended byond verson 
simply put trying to change my key bindings mid round using game preference button in verb window (top right menu) would crash my client relogging didnt help, still happens into next round, setup char in lobby menu is also crashing client.

### Test Merges

i dont uhh know, date and time was 3/11/2022 3:10 PM PST hopefully that helps 

### Reproduction Steps

i was using scopedt21 with a officers sword during the round nothing out of ordinary

**Comment by BraveMole** [comment]
still can't reproduce
