### ISSUE TITLE
Setup character button fails to open character preferences

### ISSUE THREAD

**Issue by MacBlaze1** [tgstation/TerraGov-Marine-Corps#9799]
### Description

the setup character button did not load the character preferences menu when I clicked it. I could not setup my character, but I could click every other button and they all worked.

### Test Merges

#9701: 'Burst fire balance 2.0' by novaepee at commit 640e066255
#9698: 'Implements Sanctions' by Squigger at commit 12f970dea0
#9753: 'Surt light debuff removal' by Arctrooper8 at commit 319c4395aa
#9708: 'Arrowhead Energy Shield' by hyper2snyper at commit 2479047307

### Reproduction Steps

1. Click on setup character button from the main menu
2. See how it fails to open the character preferences screen

**Comment by ValoTheValo** [comment]
this happened to me aswell, it displayed a bluescreen

**Comment by BraveMole** [comment]
Lack of context
