### ISSUE TITLE
Hunter stealth doesnt change unless they move

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#9802]
### Description

go invisible
hit stalk
still pretty visible

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [13829](https://scrubby.melonmesa.com/round/13829)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [2a6710d6adc09d0579ec5c11bce890639cbb9205](https://github.com/tgstation/TerraGov-Marine-Corps//commit/2a6710d6adc09d0579ec5c11bce890639cbb9205)
The following pull requests are currently test merged:
[#9708: 'Arrowhead Energy Shield' by hyper2snyper at commit 2479047307](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9708)
[#9753: 'Surt light debuff removal' by Arctrooper8 at commit 319c4395aa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9753)
[#9698: 'Implements Sanctions' by Squigger at commit 12f970dea0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9698)
[#9701: 'Burst fire balance 2.0' by novaepee at commit 640e066255](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9701)
[#9738: 'Adds the TX-54 Grenade launcher' by Lumipharon at commit 812b700e8c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9738)

Local commit: 66a859477c1211bb92a24c1cbda5c724677889f9
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. Become hunter
2. hit stealth
3. toggle walk
4. no invisibility change
5. walk
6. suddenly less visible

**Comment by Al-1ce** [comment]
I don't exactly see what the problem is here? Hunter does not become more invisible if you toggle "stalk" instead of "hunt", this has never been the case. Additionally, stealth is intended to become more visible if you are moving, while also draining plasma.

Stealth exists to service a "sneak attack" ability, which will be used on anything you attack once you have held still for long enough and the message appears. This is not a bug.

**Comment by 2whatever2** [comment]
> I don't exactly see what the problem is here? Hunter does not become more invisible if you toggle "stalk" instead of "hunt", this has never been the case. Additionally, stealth is intended to become more visible if you are moving, while also draining plasma.
> 
> Stealth exists to service a "sneak attack" ability, which will be used on anything you attack once you have held still for long enough and the message appears. This is not a bug.
> 
> edit: In addition, you will appear much more visible to yourself and other xenos than marines can actually see.

There's a difference in alpha between stalking and running, stealth attack still activates even while you move, and alpha doesn't update or change unless you start moving. And no it doesn't start draining plasma until the stealth attack message appears which is always 3 seconds or so letting you move around with it freely until then.

> edit: In addition, you will appear much more visible to yourself and other xenos than marines can actually see.

I have no idea what you mean by this alpha isn't something clientside, if you can see yourself visibly then other people can, if you barely can't even see yourself then other players can't.

https://user-images.githubusercontent.com/24631139/158914932-3fdb5e3d-8c6a-4e71-9a95-8ee71d6c766b.mp4

**Comment by yyzsong** [comment]
> I don't exactly see what the problem is here? Hunter does not become more invisible if you toggle "stalk" instead of "hunt", this has never been the case. Additionally, stealth is intended to become more visible if you are moving, while also draining plasma.
> 
> Stealth exists to service a "sneak attack" ability, which will be used on anything you attack once you have held still for long enough and the message appears. This is not a bug.
> 
> edit: In addition, you will appear much more visible to yourself and other xenos than marines can actually see.

![image](https://user-images.githubusercontent.com/65325586/158915898-a6efdbe2-7457-4dc8-bf28-fcfbf01ccd05.png)
ur dum :)
