### ISSUE TITLE
Evoing to t2 on crash makes you mature

### ISSUE THREAD

**Issue by yyzsong** [tgstation/TerraGov-Marine-Corps#9803]
### Description

reproduction steps

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [13829](https://scrubby.melonmesa.com/round/13829)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [2a6710d6adc09d0579ec5c11bce890639cbb9205](https://github.com/tgstation/TerraGov-Marine-Corps//commit/2a6710d6adc09d0579ec5c11bce890639cbb9205)
The following pull requests are currently test merged:
[#9708: 'Arrowhead Energy Shield' by hyper2snyper at commit 2479047307](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9708)
[#9753: 'Surt light debuff removal' by Arctrooper8 at commit 319c4395aa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9753)
[#9698: 'Implements Sanctions' by Squigger at commit 12f970dea0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9698)
[#9701: 'Burst fire balance 2.0' by novaepee at commit 640e066255](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9701)
[#9738: 'Adds the TX-54 Grenade launcher' by Lumipharon at commit 812b700e8c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9738)

Local commit: 66a859477c1211bb92a24c1cbda5c724677889f9
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1. become ancient t1
2. evo to t2
3. become mature t2
4. get buckshotted and die

**Comment by Wayland-Smithy** [comment]
Feature not a bug.
https://github.com/tgstation/TerraGov-Marine-Corps/blob/9140594244859b893dcb15397708623b7e767d89/code/datums/gamemodes/crash.dm#L175-L181

**Comment by yyzsong** [comment]
> Working as intended. (could use an update since upgrade transfer was added)
> 
> https://github.com/tgstation/TerraGov-Marine-Corps/blob/9140594244859b893dcb15397708623b7e767d89/code/datums/gamemodes/crash.dm#L175-L181

mfw coders
