### ISSUE TITLE
attempting to open the SSD mob menu causes a error

### ISSUE THREAD

**Issue by private-tristan** [tgstation/TerraGov-Marine-Corps#9809]
### Description

what I expect to happen:
> see that there's a SSD
> open the SSD menu
> take body

what happens:
> see that there's a SSD
> attempt to open SSD menu
> bluescreen

I assume it's related to my BYOND version (514.1575)

### Test Merges

[#9806: 'Nuke can no longer be teleported' by BraveMole at commit 3629b04667](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9806)
[#9805: 'New gamemode, nuclear war (or discrash or crashtess)' by BraveMole at commit 6278288d84](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9805)
[#9796: 'Double Acid Turret' by chesse20 at commit 6eefb3c41f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9796)
[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 361378815a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9738: 'Adds the TX-54 Grenade launcher' by Lumipharon at commit 812b700e8c](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9738)
[#9701: 'Burst fire balance 2.0' by novaepee at commit 640e066255](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9701)
[#9698: 'Implements Sanctions' by Squigger at commit 12f970dea0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9698)
[#9753: 'Surt light debuff removal' by Arctrooper8 at commit 319c4395aa](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9753)
[#9708: 'Arrowhead Energy Shield' by hyper2snyper at commit 2479047307](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9708)
[#9772: 'TGUI updates' by TiviPlus at commit 22e8f19fc1](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9776: 'update atomns init' by TiviPlus at commit 6660252eac](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9776)
[#9797: 'Larval hugger rebalance' by Lefunny at commit 93a9f027d4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9797)
[#9807: 'Updates Valhalla, adds missing items/features' by RipGrayson at commit 9a755dd464](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9807)

### Reproduction Steps

> see SSD
> try to open menu
> cry

### Screenshots

![image](https://user-images.githubusercontent.com/54422837/158929272-ff76ea7c-0ca0-4f15-ae70-2ed397fbd1ac.png)

**Comment by Wayland-Smithy** [comment]
Can confirm the bug is real, and also not easily reproducible locally. At least I could not make it happen with around a dozen SSD mobs of both xeno and human. Until someone can find reliable reproduction steps so we can see the real line number with tgui in debug mode this one will be a nuisance.

Worst still ListInputModal.tsx only checks length in three places and all of them seem fine except for `Math.ceil(message?.length / 3)` but if that was broken than it would BSOD 100% of the time.
