### ISSUE TITLE
Xenos exitting from vents wherever it wants 

### ISSUE THREAD

**Issue by Nirvan4** [tgstation/TerraGov-Marine-Corps#9823]
### Description

Marine pops inside the ship, larba gets away, evo to a drone, marines weld every single vent in the ship without exception, drone still appearing out of blue, orbit the drone, it can get out of the vent in any tile without any worries, gets out and do whatever it wants, slash a vent and goes away.

### Test Merges

[#9796: 'Double Acid Turret' by chesse20 at commit 6eefb3c41f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9796)
[#9797: 'Larval hugger rebalance' by Lefunny at commit ebec1e895f](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9797)
[#9738: 'Adds the TX-54 Grenade launcher' by Lumipharon at commit 98ee1996f0](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9738)
[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 361378815a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9776: 'update atomns init' by TiviPlus at commit 6660252eac](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9776)
[#9794: 'Make coverage code actually work' by Lumipharon at commit 5cbd70d51a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9794)

### Reproduction Steps

1. Be xeno
2. Get inside a vent
3. Get out in a random tile.

**Comment by Derrick2Electricboogaloo** [comment]
That explains a lot.

**Comment by BraveMole** [comment]
Cannot reproduce, can you try it yourself ?
