### ISSUE TITLE
generators still not working as intended

### ISSUE THREAD

**Issue by ThelastArchiver** [tgstation/TerraGov-Marine-Corps#9853]
### Description

https://github.com/tgstation/TerraGov-Marine-Corps/pull/9847 
was supposed to fix this but its still happening this round marines did a tadop and the generators did not  produce psypoints  even after an admin tried getting them to work it was on lv.

### Test Merges

The following pull requests are currently test merged:
[#9824: 'Tesla gun rebalance' by goose4429 at commit f450d28809](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9824)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [14006](https://scrubby.melonmesa.com/round/14006)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [ca0a26162265a25bb633570bd6d4b9c25b128169](https://github.com/tgstation/TerraGov-Marine-Corps//commit/ca0a26162265a25bb633570bd6d4b9c25b128169)
The following pull requests are currently test merged:
[#9824: 'Tesla gun rebalance' by goose4429 at commit f450d28809](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9824)

Local commit: a407fa2c642c2e02550a494ea5bb4df2a9f2c53c
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

1.play tgcm / observe
2. look at hive status
3. look again 
4.  see that psypoints are not being generated despite marines being on the ground with a tadop
5. sigh and smash your head against a wall

### Screenshots

none sorry

**Comment by DeltaFire15** [comment]
The server was not recompiled after merging, meaning the PR is not yet in effect. Please wait until there has been a server update.
