### ISSUE TITLE
Hunters primo

### ISSUE THREAD

**Issue by krutoi2000** [tgstation/TerraGov-Marine-Corps#9858]
### Description

Hunters stealth bind activates disguise too. In such state you lose an option to use stealth through bind(cause disguise sprite overcome stealth mode) and it drains plasma really fast, while moving(because two abilities are activated).
Solution: Make stealth and disguise bind separate.

### Test Merges

-

### Reproduction Steps

1. Bind stealth.
2. Place psymark on item.
3. Use stealth bind
4. Suffer

**Comment by BraveMole** [comment]
fixed
