### ISSUE TITLE
Shoulder mount bypasses T-29 skill check for smartgunner

### ISSUE THREAD

**Issue by novaepee** [tgstation/TerraGov-Marine-Corps#9864]
### Description

T-29 shoulder mount on a squad marine should have squad marine regret their life, but instead they use it with ease.

### Test Merges

Shoulder mount PR.

### Reproduction Steps

1. Get a squad marine
2. Get shoulder mount
3. Get T-29
4. Combine together
5. Squad marine is now smartgunner lite

**Comment by Lumipharon** [comment]
Shoulder mount just zeros out recoil, I assumed this was intended?

**Comment by Arctrooper8** [comment]
Isn't the shoulder mount handling all the aiming and other gun stuff? 
Also, shoulder mount is rare enough and squad marines would have to buy a smartgun (or grab from perma SG, but they'd still have to buy ammo later) that I don't think this would be too massive a problem.

**Comment by BraveMole** [comment]
intended I guess
