### ISSUE TITLE
Hivemind command minions.

### ISSUE THREAD

**Issue by krutoi2000** [tgstation/TerraGov-Marine-Corps#9896]
### Description

Hivemind command minions doesn't work on nuclear war on prison station.

### Test Merges

-

### Reproduction Steps

Try it, at least for me it didn't work. Minions didn't care about it.

### Screenshots

-

**Comment by BraveMole** [comment]
Are you playing on rutgmc ?

**Comment by krutoi2000** [comment]
> 

Yeap

**Comment by BraveMole** [comment]
Advanced pathfinding is disabled on rutgmc via config, because they said it was lagging too much
