### ISSUE TITLE
Flamers can shoot through solid windows

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/TerraGov-Marine-Corps#9898]
### Description

Flamethrowers are not stopped by any type of glass.

### Test Merges

[#9824: 'Tesla gun rebalance' by goose4429 at commit 38c1559b91](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9824)
[#9772: 'TGUI updates' by TiviPlus at commit 0984f0187b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9776: 'update atomns init' by TiviPlus at commit 8f37f788e7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9776)

### Reproduction Steps

shoot flame through windows

### Screenshots

![image](https://user-images.githubusercontent.com/7869430/161405406-7a8e3831-89af-470b-b73d-15f4dd047363.png)

**Comment by mrhugo13** [comment]
the relevant code
![Code_2022-04-11_12-29-23](https://user-images.githubusercontent.com/17747087/162722050-315f7964-a15a-4f54-912b-a908b4ef7371.png)
