### ISSUE TITLE
Drones can't use larva growth toxin on nested hosts.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#990]
## Reproduction: It says you reconsider bullying the nested host or whatever, which doesn't make much sense.

**Comment by Shadow-Quill** [comment]
I _think_ this is for balance, considering the other "You feel bad about abusing the nested, infected host." messages. (Whatever they actually are.)

**Comment by DominikPanic** [comment]
@Surrealaser

**Comment by Surrealaser** [comment]
This is intended for balance reasons; gives the host an opportunity to fight back.
