### ISSUE TITLE
Minimap has holes in it

### ISSUE THREAD

**Issue by RipGrayson** [tgstation/TerraGov-Marine-Corps#9902]
### Description

Minimap seems to be broken and has holes in it, the map itself seems mostly fine.

### Test Merges

[#9824: 'Tesla gun rebalance' by goose4429 at commit 38c1559b91](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9824)
[#9772: 'TGUI updates' by TiviPlus at commit 0984f0187b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9776: 'update atomns init' by TiviPlus at commit 8f37f788e7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9776)

### Reproduction Steps

Go to a map with lots of modular maps like Big Red, 
view minimap 
see holes

### Screenshots

![dreamseeker_A0P1PZU12k](https://user-images.githubusercontent.com/49290523/161454515-9fcb304b-4199-4b08-8597-ebf8cbaf3e37.png)

**Comment by magatsuchi** [comment]
![image](https://user-images.githubusercontent.com/88991542/167302101-32b390ff-a791-47f8-b558-370201229d70.png)

could not reproduce

**Comment by RipGrayson** [comment]
> ![image](https://user-images.githubusercontent.com/88991542/167302101-32b390ff-a791-47f8-b558-370201229d70.png)
> 
> could not reproduce

I only saw it on Big Red for a couple rounds. Suspect https://github.com/tgstation/TerraGov-Marine-Corps/pull/9776 of causing it and https://github.com/tgstation/TerraGov-Marine-Corps/pull/9916 of fixing it. I'm only leaving this bug up in the odd event it came up again.

**Comment by RipGrayson** [comment]
It's been a while and I haven't seen this bug since, I'm going to count it as closed. Will reopen if I encounter it again.
