### ISSUE TITLE
Wraith can warp into marines while in phased mode to give them stagger and blurry vision

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/TerraGov-Marine-Corps#9903]
### Description

Wraith can just warp into the marine frontline while unkillable to give everyone stagger + blurry vision. Marines can't aim, move slowly and do only 50% damage. Meanwhile the wraith is literally UNKILLABLE.

### Test Merges

doesnt matter

### Reproduction Steps

explained above

**Comment by BraveMole** [comment]
Feature and balance
