### ISSUE TITLE
T-27 Has no recoil while wielding

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/TerraGov-Marine-Corps#9919]
### Description

Read title

### Test Merges

doesn't matter

### Reproduction Steps

1. Pick up t-27
2. Shoot while wielding

### Screenshots

With attachments

https://user-images.githubusercontent.com/24631139/161648242-68f52f34-d95c-47f3-909f-0af7c91650e5.mp4

Without attachments

https://user-images.githubusercontent.com/24631139/161648293-6064190e-50bd-42b4-ac75-5ce7bad0fbdc.mp4

**Comment by Lumipharon** [comment]
I'm getting recoil when I try this on the live server, with and without a suppressor.

**Comment by InterroLouis** [comment]
Have you tested this while not being a spatial agent that has, by definition, all the gun skills?

**Comment by magatsuchi** [comment]
t-27 is no longer relevant as a weapon, cannot be reproduced
