### ISSUE TITLE
Huggers die when they jump onto the same tile.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#992]
## Reproduction: Bring someone to more than 1 egg and most likely the facehuggers will stack on the same tile, hug the guy and then kill each other. This could have something to do with old code made to prevent hugger stacking before it was coded in by CM to have huggers die from leaving eggs after a certain amount of time.
Possible solution is to have huggers not kill each other and also crawl back into eggs 1 tile nearby to make this issue less common. Also they might even kill each other even if the hugger on the ground is dead and the hugger is in your hand, haven't been able to find out but that might explain unexpected hugger deaths.

**Comment by DominikPanic** [comment]
@Ghommie

**Comment by Shadow-Quill** [comment]
Huggers currently die if: (from what I'm reading)

- There are more than two conscious, non-sterile (Lamarr) huggers on a tile, all but two will be qdeled.
- Or if they're out of an egg or a carrier's grasp for eight seconds(?), and they aren't on a tile with an empty egg.

**Comment by Ghommie** [comment]
I'll probably slap in a `prob(30)` and a chance of them leaping to an adjacent tile, so they don't just die when leaping on the same turf. Thanks.
