### ISSUE TITLE
You can prevent the queen from locking down a dropship before it's too late and it can be sent back to be blocked again.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/TerraGov-Marine-Corps#994]
## Reproduction:
Place a rocket frame and ripley blocking the shuttle console and lockdown button and you can prevent the xenos from using the dropship, call it back, kill any xenos on board and block it again if possible. Can be abused to stall a round for a long time. This only works if the queen doesn't know how to access the lockdown button or shuttle console, which is to climb over the rocket frame and break the ripley, which sometimes can only be destroyed by aciding it. As said by someone else, it's like a gate for xeno queens that don't know how to climb over a rocket frame, it's very obscure and unknown as even being an option, and doesn't really have a reason to exist other than for veterans to trick newer players into dying.

**Comment by DominikPanic** [comment]
This can't be feasibly fixed tbh

**Comment by InterroLouis** [comment]
Eh, I mean, you could prevent people from depositing things on the floor in the dropship using a Ripley if you really wanted to. Probably, somehow. Through the magics of coding, knowledge of which is byond me.

**Comment by DominikPanic** [comment]
> 
> 
> Eh, I mean, you could prevent people from depositing things on the floor in the dropship using a Ripley if you really wanted to. Probably, somehow. Through the magics of coding, knowledge of which is byond me.

Snowflake code not possible to do properly until components

**Comment by DominikPanic** [comment]
It's possible to fix properly now I suppose, though has it really been an issue?

**Comment by Rohesie** [comment]
This is more organically fixed by making those things destroyable by xeno melee attacks.

**Comment by DominikPanic** [comment]
Very goo idea, I'll get onto that.
